### ISSUE TITLE
Changing Calamares language doesn't change all text

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#1001]
![screenshot_20180711_221800](https://user-images.githubusercontent.com/3689821/42610753-8c6bf2fc-8558-11e8-9a90-b55992e46e23.png)

The system locale is English, however, I manually changed the Calamares language to Spanish (from Spain).

Are there just missing translations, or does it just not change the locale of all the text?

Thanks.

**Comment by tsimonq2** [comment]
Ah, it seems the translation is just missing.

**Comment by kkofler** [comment]
The untranslated status messages from the Python modules are already filed as #991. The untranslated game in the slide show is a downstream (distribution) issue, this is not part of Calamares itself.
