### ISSUE TITLE
Geoip does not seem to work - calamares installer automatic detecting location

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#1004]
During installation we no longer get an automatic location on screen 2 - world map. It is set now to New York rather than Brussels where I live. This was working in earlier version of ArcoLinux 6.8.2.
Both installing on VirtualBox and ssd

**Logs**
Session log from live iso is here : https://pastebin.com/WwCrGDN5
Calamares 3.2.0-5

I think these are the essential lines : 

```
2018-07-17 - 08:18:01 [6]: Fetching GeoIP data from "freegeoip.net/json/"
2018-07-17 - 09:18:01 [2]: WARNING: guessLocaleConfiguration can't guess from an empty list.
2018-07-17 - 04:18:01 [2]: WARNING: guessLocaleConfiguration can't guess from an empty list.
2018-07-17 - 04:18:01 [2]: WARNING: guessLocaleConfiguration can't guess from an empty list.
2018-07-17 - 04:18:01 [2]: WARNING: guessLocaleConfiguration can't guess from an empty list.
```
Ask away if you need more additional information.

**Comment by philmmanjaro** [comment]
We already [communicated that this service is no more](https://calamares.io/calamares-3.1.13-is-out/). Please adopt to a different one. More about it [here](https://github.com/calamares/calamares/issues/932).

**Comment by erikdubois** [comment]
It is not clear to me if it will be fixed by Calamares (in which case I will wait patiently) or if we as end-user should solve this and then the question is how?

**Comment by erikdubois** [comment]
I think this one can be used for now

https://geoip.tools/v1/json will return time_zone":"Europe/Berlin" (120 requests per minute. Once reached subsequent requests will result in error 503 until your quota is cleared)

**Comment by philmmanjaro** [comment]
@erikdubois: same as [we use](https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/blob/master/lib/util-yaml.sh#L260) for Manjaro.

**Comment by erikdubois** [comment]
Thanks for helping - doing that now

**Comment by erikdubois** [comment]
It seems https://geoip.tools/v1 is out again as useful url in calamares to find out the users whereabouts?
Did you know?
What url can we use now?

**Comment by philmmanjaro** [comment]
We always have some [tests](https://github.com/calamares/calamares/blob/master/src/modules/locale/GeoIPTests.cpp#L240). Remember to set also `geoipSelector` as needed, since JSON uses `"time_zone"` and XML uses `TimeZone`.

**Comment by erikdubois** [comment]
great.

This url works fine : https://geoip.kde.org/v1/calamares

**Comment by philmmanjaro** [comment]
Normally the others work also, except http://freegeoip.net/json/. You only have to configure it right:
```
# GeoIP based Language settings:
geoipUrl:      "https://geoip.kde.org/v1/calamares"

# GeoIP style. Leave commented out for the "legacy" interpretation.
# This setting only makes sense if geoipUrl is set, enabliing geoIP.
#
# Possible values are:
#   unset       same as "legacy"
#   blank       same as "legacy"
#   "legacy"    appends "/json" to geoipUrl, above, and uses JSON format
#   "json"      URL is not modified, uses JSON format.
# "xml" URL is not modified, uses XML format.
geoipStyle:    "json"

# GeoIP selector. Leave commented out for the default selector
# (which depends on the style: JSON uses "time_zone" and XML
# uses TimeZone, for the FreeGeoIP-alike and the Ubiquity-alike
# respectively). If the service configured via *geoipUrl* uses
# a different attribute name (e.g. "timezone") in JSON or a
# different element tag (e.g. "<Time_Zone>") in XML, set this
# string to the name or tag to be used.
geoipSelector: "time_zone"
```

**Comment by erikdubois** [comment]
ok got it  - will try again - geoipstyle was not defined

**Comment by erikdubois** [comment]
had a successful build with ArcoLinuxD - Europe/Brussels was pinned on the map
Content of locale.conf
`---
region:        "America"
zone:          "New_York"

# GeoIP settings. Leave commented out to disable GeoIP.
localeGenPath: "/etc/locale.gen"
geoipUrl:      "https://geoip.kde.org/v1/calamares"
geoipStyle:    "json"
geoipSelector: "time_zone"`

**Comment by erikdubois** [comment]
ArcoLinux build find too. 
Super this works
