### ISSUE TITLE
Error installing on hardware with 1 ssd and 1 harddisk present

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1005]
Error installing ArcoLinux (Xfce) when a computer has 1 ssd and 1 harddisk for data. In Xfce -Thunar we had set the harddisks to automount. (see picture) Calamares produces the error you see in the post.

Here are the pictures and more information of the 
https://arcolinuxforum.com/viewtopic.php?f=101&t=681&p=2610&sid=140663be50e256b10a558d238d9b1d10#p2610

Solved the issue by changing these settings in thunar
![xfce-settings](https://user-images.githubusercontent.com/36679406/42809850-d6a372d4-89b6-11e8-8d53-cdfee0e80db2.jpg)

Not an issue anymore on ArcoLinux. Just my intention to give you devs the information to improve Calamares even more.

**Comment by abucodonosor** [comment]
See https://github.com/calamares/calamares/issues/860

Not much can be done .. Simple do not magically mount things.

**Comment by arcolinuxz** [comment]
Correct - that has been done and no issue now.
