### ISSUE TITLE
support swapfiles instead of swap partitioning

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1006]
**Is your feature request related to a problem? Please describe.**
I hate it when my partition table is getting extra complexity because the installer thinks this is the 1980's and I need a dedicated swap partition.

**Describe the solution you'd like**
As a distribution I'd like a config option to switch calamares from swap-partitioning mode to swapfiles. In this mode it'd not create a swap partition but instead add a swapfile to the partition / is going to be on.

Care should be taken to consider the swapfile size when checking the requiredStorage requirement.

GUI options to set the size or disable the swapfile would be nice to have, but IMO entirely optional as this stuff can easily be changed after installation.

**Comment by abucodonosor** [comment]
@apachelogger 

https://github.com/calamares/calamares/issues/848
