### ISSUE TITLE
Calamares git master hangs on loading Partitioning page

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#1007]
Rebuilding Calamares today on Neon git unstable edition with Ubuntu 18.04 (bionic) base and libblkid1 2.32 and kpmcore from master on 1 August (yesterday) I found that Calamares would hang on switching to the Partitioning page.  The Gathering System Information page displays indefinately.  Tested on Virtualbox and on our openQA setup.
https://build.neon.kde.org/job/openqa_bionic_devedition-gitunstable_installation/88//artifact/testresults/install_calamares-54.png

**Comment by jriddell** [comment]
ISO at http://files.kde.mirror.pangea.pub/.bionic/neon-devedition-gitunstable-20180802-1342-amd64.iso

**Comment by philmmanjaro** [comment]
When I find time, I'll take a look. On Manjaro we are still using **kpmcore 3.3.0-1**, which works with git commit b0e55c0 of CAL. I'll merge the two missing commits of master and will check also on my end. However, I've also merged [update-lvm-support](https://github.com/calamares/calamares/tree/update-lvm-support) to my development sources. Does the latest stable release of CAL has similar issues on your end?

**Comment by philmmanjaro** [comment]
OK, I checked. I've it merged till ae7700f already. You may test [KDE v18.0-b3](https://osdn.net/projects/manjaro/storage/kde/18.0-beta-3/).

**Comment by jriddell** [comment]
I tried compiling calamares 3.1.x-stable branch but it does not compile with kpmcore master
https://build.neon.kde.org/job/bionic_unstable_extras_calamares_bin_amd64/37/console
error: kpmcore/backend/corebackenddevice.h: No such file or directory

**Comment by jriddell** [comment]
that manjaro-kde-18.0-beta-3-testing-x86_64.iso Live image shows the partition page fine on my Virtualbox

**Comment by stikonas** [comment]
@jridell We haven't done much testing of kauth'ed kpmcore with Calamares yet. Probably something in Calamares broke... 

Does scanning work with KDE Partition Manager (git)?

**Comment by jriddell** [comment]
We have tidied up our packaging and now the partioning page loads and works fine.  However calamares can't do partitioning operations during the install phase https://i.imgur.com/DUeAML5.png

**Comment by apachelogger** [comment]
This was fixed in kpmcore, which had trouble talking to its permission-elevated helper.
