### ISSUE TITLE
Partition does not start on physical sector boundary

### ISSUE THREAD

**Issue by aliveafter1000** [calamares/calamares#1008]
Bug in Calamares. Installed using auto partition.
First partition should start at 2048 but it starts at 2049.

![8af11eb6d8d92dd2053b8b83537987335846d62f](https://user-images.githubusercontent.com/42086053/43673532-619faf0e-9760-11e8-83d4-be4c24453566.png)
![9b2a950e9340b9a8f4fc969e21365f119a8d31b6](https://user-images.githubusercontent.com/42086053/43673535-65192c1e-9760-11e8-83e2-d6822099574d.png)

https://github.com/calamares/calamares/blob/master/src/modules/partition/core/PartitionActions.cpp

Quick perusal of the code.
Just gonna treat it as BOOL isEfi = FALSE; as I’m lazy:
```

    // we start with a 1MiB offset before the first partition
    empty_space_size = 1;
    qint64 firstFreeSector = MiBtoBytes(empty_space_size) / dev->logicalSize() + 1;

    MiBtoBytes(1) = 1048576
    1048576 / 512 + 1
    Calculated = 2049.
    Remove the + 1 so it is 2048.
```

Fix?:
   ` qint64 firstFreeSector = MiBtoBytes(empty_space_size) / dev->logicalSize();`

**Comment by philmmanjaro** [comment]
This issue is similar to https://github.com/calamares/calamares/issues/567. @stikonas: any changes needed to be made?

**Comment by philmmanjaro** [comment]
Code is present since 09/14 via https://github.com/calamares/calamares/commit/aeb20761cc91a0a6ef0ed5b0489730648cf556eb

**Comment by aliveafter1000** [comment]
It has been broken for a long time. Many people complained but were always told HOW to fix the alignment issues instead of hitting the actual problem. Not surprised it is incorrect, it is a very small screw up. The 0 screws with peoples heads.

Sector 0 to 2048 is actually a total of 2049 sectors (counting 0). 
The writer of the code made that mistake. 
firstFreeSectorIt is at "position" 2048 and not by the number of sectors.

012345
123456

If we want to create at number 5, just put 5. 
He made it 6 with the +1 because he counted the number of sectors.

get it? easy mistake.

**Comment by stikonas** [comment]
@philmmanjaro It's most likely Calamares specific, nothing to do with kpmcore. I always get properly aligned partitions with KDE Partition Manager.

**Comment by adriaandegroot** [comment]
This doesn't seem to cause any specific **problems**, (or we would have heard more about it), but it's just weird. It's fixable, for sure, but as @philmanjaro points out there may be more places where this shows up, and it needs to be carefully validated -- so we don't end up with overlapping partitions, for instance.

**Comment by adriaandegroot** [comment]
(Oh, and rather than "physical sector" I think this should be titled either "cluster" or "4k boundary"; a partition necessarily starts at a particular sector. This is quibbling, though :) )

**Comment by adriaandegroot** [comment]
@philmmanjaro Only the +1s in PartitionActions.h might be an issue. The others (e.g. in the model) are valid.

**Comment by philmmanjaro** [comment]
OK, should I send a PR or commit it directly? 




Kind regards


Philip Müller


Sent by mobile 







On Wed, Aug 8, 2018 at 11:27 AM +0200, "Adriaan de Groot" <notifications@github.com> wrote:












@philmmanjaro Only the +1s in PartitionActions.h might be an issue. The others (e.g. in the model) are valid.

**Comment by adriaandegroot** [comment]
@philmmanjaro There were lots of little things wrong, see the short-ish branch for more information.

**Comment by philmmanjaro** [comment]
Will do and merge it into my development branch for internal testing. Feedback as usual. 




Kind regards


Philip Müller


Sent by mobile 







On Wed, Aug 8, 2018 at 1:59 PM +0200, "Adriaan de Groot" <notifications@github.com> wrote:












@philmmanjaro There were lots of little things wrong, see the short-ish branch for more information.
