### ISSUE TITLE
Calamares build crashes after python upgrade to 3.7

### ISSUE THREAD

**Issue by jghodd** [calamares/calamares#1009]
[ 17%] Linking CXX executable ../../loadmodule
/bin/ld: warning: libpython3.6m.so.1.0, needed by /usr/lib/libPythonQt-Qt5-Python3.so.3, not found (try using -rpath or -rpath-link)
collect2: error: ld returned 1 exit status
make[2]: *** [src/calamares/CMakeFiles/loadmodule.dir/build.make:95: loadmodule] Error 1
make[1]: *** [CMakeFiles/Makefile2:519: src/calamares/CMakeFiles/loadmodule.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by agaida** [comment]
and why is that a Calamares bug?

**Comment by jghodd** [comment]
The issue is the pythonqt build. Am rebuilding it now and will post the results.

**Comment by jghodd** [comment]
PythonQt needs rebuilding. No issues with the rebuilt libraries.

**Comment by jghodd** [comment]
PythonQt needs rebuilding. No issues with the rebuilt libraries.
