### ISSUE TITLE
Calamares.io web gives a 404 error

### ISSUE THREAD

**Issue by q2dg** [calamares/calamares#1015]
That's all.
Thanks

**Comment by kkofler** [comment]
@adriaandegroot wrote on IRC that he will be looking into this tomorrow (Monday). (He was at Akademy this week.)

**Comment by adriaandegroot** [comment]
Fixed. The VM serving the domain was re-started, and nginx didn't come up automatically. For future reference, it was just a matter of `service nginx restart`.
