### ISSUE TITLE
Build on Debian 9

### ISSUE THREAD

**Issue by danwerspb** [calamares/calamares#1023]
A summary of the build report and pull request.
As a result of experiments, to build calamres on Debian 9, i needed to change the repositories on testing.
I used the service https://debgen.simplylinux.ch/.

Install dependencies:
cmake debhelper extra-cmake-modules gettext kio-dev libatasmart-dev libboost-python-dev libkf5config-dev libkf5coreaddons-dev libkf5i18n-dev libkf5iconthemes-dev libkf5package-dev libkf5parts-dev libkf5plasma-dev libkf5service-dev libkf5solid-dev libparted-dev libpolkit-qt5-1-dev libqt5svg5-dev libqt5webkit5-dev libyaml-cpp-dev os-prober pkg-config pkg-kde-tools python3-dev qtbase5-dev qtdeclarative5-dev qttools5-dev qttools5-dev-tools libkf5crash-dev qtwebengine5-dev libpythonqt3.0 libkpmcore-dev libpythonqt-qtall-qt5-common-dev libpwquality-common libpwquality-dev libpwquality-tools libpwquality1

It was necessary to install a separate package - libpythonqt-qtall-qt5-common-dev. The previous version had to be deleted - libpythonqt-dev.

The source code required changes.

Сhange CMakeModules / FindPythonQt.cmake:
include / PythonQt / to include / PythonQt5 /

Сhange src / libcalamaresui / modulesystem / PythonQtViewModule.cpp:
include <PythonQt_QtAll.h>

After that, the build on Debian 9 was successful.

PR - https://github.com/calamares/calamares/pull/1024

**Comment by adriaandegroot** [comment]
(The PR is closed, with its suggestions incorporated into master; I'm leaving the issue open for a bit because of the question of package names and dependencies)

**Comment by danwerspb** [comment]
Ok. It was information for you and others. On debian 9 with testing repos there is no package libpythonqt-dev. Files need for build exist in package libpythonqt-qtall-qt5-common-dev.

**Comment by adriaandegroot** [comment]
OK, thanks. I'll close this (it's still easy to find for others using Calamares on Debian 9) -- the other issues should be fixed now, with Calamares master finding the right headers also on Debian 9.

**Comment by kkofler** [comment]
(As I already wrote in your pull request:)
Please note that if you are using the testing repository, you aren't really using Debian 9, but what is going to eventually become Debian 10.
