### ISSUE TITLE
Automation of existing manual partitioning in "partition module" 

### ISSUE THREAD

**Issue by s012345preeti** [calamares/calamares#1028]
I am working on creating customized calamares installer for a project. 

I have one query related to automation of partitioning module (customized partitioning) . The current partition module requires user intervention for size/type/flags before proceeding with actual partition. So to avoid the user intervention a shell script is launched in the exec phase to create 6 partitions. But this resulted in the failure of subsequent mount/unpacks/fstab modules for missing data in "globalstorage" created by "partition" module. 

```
Installation failed
No mount point for root partition in globalstorage

globalstorage does not contain a "rootMountPoint" key doing nothing. 
```

>Mount module error

```
Installation failed
Boost.Python error in job "mount"
<class 'AtributeError'>
'NoneType' object has no attribute 'sort'
```

So is there any other way other than re-writing the "partition module" (QT/C++) as per automation required. I searched but didn't get any configuration options for automating this part of partitioning as per pre-defined memory maps to be used.

**Comment by philmmanjaro** [comment]
Instead of a bash-script, you may use **python** and add the needed values to **globalstorage**. Please refer to our [example](https://github.com/calamares/calamares/tree/master/src/modules/dummypython) and let me know if you need help with it.

**Comment by s012345preeti** [comment]
Thank you for the guidance!!!

I will refer to the dummy python module and will try to get the values populated in **globalstorage** to be used by mount and subsequent modules.

**Comment by philmmanjaro** [comment]
@s012345preeti: hope I could help. If you need someone to review, let me know.
