### ISSUE TITLE
calamares initialization failed....

### ISSUE THREAD

**Issue by TheUnable** [calamares/calamares#1034]
calamares was unable to load all of the configured modules. This is a problem with the way calamares is being used by the distribution.
The folowing modules could not be loaded
     .services

**Comment by adriaandegroot** [comment]
The message from Calamares says it all, really: this is a problem with the way Calamares is being used by the distribution. Please contact them instead.

As a guess: they have updated Calamares to 3.2.2 or later, but not updated the configuration files according to the instructions in the release notes, and therefore still refer to module *services* which has been renamed (I'll assume they should be using *services-systemd* now).
