### ISSUE TITLE
Default vconsole keymap for austrian keymap

### ISSUE THREAD

**Issue by s-john19** [calamares/calamares#1035]
I installed manjaro the first time and I noticed something about the installation process:
When you select German (Austria) or German (Austria, nodeadkeys) as your keymap, manjaro uses “at” as your keymap for your vconsole.conf.
But at doesn’t exist for vconsole, so you get an english layout and you need to search for a solution if you don’t know that you just have to edit the vconsole.conf.

Other distributions automatically sets “de” or “de-latin1-nodeadkeys” as your keymap, also if you selected the austrian version during installation. Would be great if manjaro could do that, too. Also for other keymap variants where that also happens (I only saw this with austria, I didn’t test anything else).

**Comment by kkofler** [comment]
The famous "Austrian keymap"… I have no idea why xkb has that to begin with. The keyboards sold here in Austria are absolutely identical to the ones sold in Germany, and I have not seen any difference whatsoever between the German (Germany) and German (Austria) xkb maps. (The only difference is that the Germany map has more variants available, so I actually use the `de-deadtilde` keymap.)

The mapping from xkb keymaps to legacy console keymaps is defined in the file `src/modules/keyboard/kbd-model-map`. So you probably want to add a line to that file. However, that file is an import of the upstream file https://cgit.freedesktop.org/systemd/systemd/tree/src/locale/kbd-model-map from `systemd-localed`, so it should also be reported there (but that file has last changed in 2015, so I'm not convinced they will fix it in a timely matter – we may have to fix this downstream, which unfortunately means that you will still get the wrong console layout if you use `localectl` to set your keyboard layout).

It shall be noted that this issue only affects distributions still shipping (only) the legacy console keymaps. Several distributions (such as Fedora) have switched to shipping converted versions of the xkb keymaps for the console instead or in addition. In those distros, `at` is actually a valid keymap for `vconsole.conf`. That setup is supported and preferred by both `systemd-localed` and Calamares. See:
* https://src.fedoraproject.org/cgit/rpms/kbd.git/tree/xml2lst.pl
* https://src.fedoraproject.org/cgit/rpms/kbd.git/tree/kbd.spec?id=7d9ad7580cd642537df56b3b21976bf7129478f7#n142

**Comment by s-john19** [comment]
> The famous "Austrian keymap"… I have no idea why xkb has that to begin with. The keyboards sold here in Austria are absolutely identical to the ones sold in Germany, and I have not seen any difference whatsoever between the German (Germany) and German (Austria) xkb maps. (The only difference is that the Germany map has more variants available, so I actually use the `de-deadtilde` keymap.)
> 
> The mapping from xkb keymaps to legacy console keymaps is defined in the file `src/modules/keyboard/kbd-model-map`. So you probably want to add a line to that file. However, that file is an import of the upstream file https://cgit.freedesktop.org/systemd/systemd/tree/src/locale/kbd-model-map from `systemd-localed`, so it should also be reported there (but that file has last changed in 2015, so I'm not convinced they will fix it in a timely matter – we may have to fix this downstream, which unfortunately means that you will still get the wrong console layout if you use `localectl` to set your keyboard layout).
> 
> It shall be noted that this issue only affects distributions still shipping (only) the legacy console keymaps. Several distributions (such as Fedora) have switched to shipping converted versions of the xkb keymaps for the console instead or in addition. In those distros, `at` is actually a valid keymap for `vconsole.conf`. That setup is supported and preferred by both `systemd-localed` and Calamares. See:
> 
> * https://src.fedoraproject.org/cgit/rpms/kbd.git/tree/xml2lst.pl
> * https://src.fedoraproject.org/cgit/rpms/kbd.git/tree/kbd.spec?id=7d9ad7580cd642537df56b3b21976bf7129478f7#n142

I also don't know why there is an extra keymap, but I don't have this in Linux only. I only know that in Austria we have some words which aren't used in Germany. But that shouldn't need an other keymap :)

About the other stuff: I am a newbie about Linux, so I don't actually know to a 100% what you mean with that.  Should I report this somewhere else? Believe me you don't want me to add lines to your code :D 

I just saw this and thought it is worth to report.

**Comment by kkofler** [comment]
One of us developers will have to add the missing line. We will look into this.

**Comment by adriaandegroot** [comment]
@kkofler if you feel like pushing this in (just add the one line at the bottom, probably with a comment line above saying that these are additions from Calamares) in master, go ahead. Otherwise I'll get around to it this week, once I can figure out what the file format means.

**Comment by philmmanjaro** [comment]
Well, this is used for `de`:

> de de pc105 - terminate:ctrl_alt_bksp

Is it then:

> at de pc105 - terminate:ctrl_alt_bksp

**Comment by s-john19** [comment]
Would this fix all AT keyboard variants (Austria, Austria nodeadkeys, ..)? Sry I am not so into coding and just want to be sure it will fix it completely.

**Comment by philmmanjaro** [comment]
Well, you can use the german layout and just change the `at`. Since @kkofler uses the `de-deadtilde` variant, I'd enabled it on my development package **calamares-git**. Still waiting for him to confirm or provide a better setting by default.

**Comment by s-john19** [comment]
Ok thanks and sry that I can't contribute more than just the issue here - especially because it's only a small issue. Still new this stuff for me :)

**Comment by kkofler** [comment]
Your line is backwards, it should be the console keymap name first, then the xkb keymap name (the file says "X11", but xkb is now also used by Wayland, so I prefer calling it xkb), so `de at`, not `at de`.

`deadtilde` should not be used, it is an option of the xkb `de` keymap, irrelevant for the xkb `at` keymap (which has no such option). The console keymaps have no such option (unless you are using the converted xkb keymaps, in which case `kbd-model-map` is not used or needed at all). Also, it is a personal preference that I use that. (`deadtilde` used to be the default, but they changed the default to not let ~ be a dead key anymore to match proprietary operating systems.)

**Comment by philmmanjaro** [comment]
@kkofler: woops. I thought I missed some. Will fix it on my branch. Who will provide it to the upstream branch?

**Comment by philmmanjaro** [comment]
@kkofler: right, makes sense. So I'm now currently at [this](https://gitlab.manjaro.org/applications/calamares/compare/d0488b7d...0c29aa2d) ...

**Comment by adriaandegroot** [comment]
So with the work of Phil and Kevin to prepare this, I've added the relevant line to the keymapping. It should show up in Calamares 3.2.3.
