### ISSUE TITLE
Please consolidate all Spanish translations into one, dialect-less and authoritative.

### ISSUE THREAD

**Issue by fitojb** [calamares/calamares#1040]
The current situation of having four (half-completed but completely inconsistent) translations to the *same language* is simply untenable. It is impossible to give them proper maintenance or to ensure they use the correct terminology and style throughout. And that is not including the fact that no volunteer will want to do the same work four-fold!

In the 99% of cases in FOSS projects, there is no need to create separate dialect versions of the Spanish translation, because terminology differences are minimal and negligible (a neutral choice of words will be understood everywhere) and the orthography is the absolute same for every place where Spanish is spoken.

Please consolidate Spanish (Spain), Spanish (Puerto Rico) and Spanish (Mexico) into Spanish at Transifex and at the repo.

**Comment by adriaandegroot** [comment]
This is probably something to discuss on Transifex **first** with the coordinators of the relevant languages. I don't know enough about the local use to know if the differences in the translations are relevant. For instance:

```
         <source>Feedback</source>
-        <translation>Respuesta</translation>
+        <translation>Retroalimentación</translation>
```

(I see that in the MX translations, there's also a "Feedback" translation without the ó and just a plain o)

**Comment by fitojb** [comment]
> (I see that in the MX translations, there's also a "Feedback" translation without the ó and just a plain o)

That's just one of many, many errors. Across Spanish dialects there are no spelling differences.

**Comment by adriaandegroot** [comment]
This has since been handled in Transifex.
