### ISSUE TITLE
Allow for users to mount /Data partitions.

### ISSUE THREAD

**Issue by benbullard79** [calamares/calamares#1041]
**Is your feature request related to a problem? Please describe.**
I use separate partitions to store Data instead of /home. So far I call them /Data1, and /Data2.

**Describe the solution you'd like**
In older versions of Calamares I was able to add the entries in the partitioner on the blank line then select keep rather than format and the entry for the partitions was automatically created in /etc/fstab. Now this functionality is gone as there has been a change where the partitioner now has the no blank line but instead the line 'no mount point'.

**Describe alternatives you've considered**
Seems like that line could be left blank as I don't know why user would create a partition and then not have it mounted. Alternatively include a line in the partitioner for user to add a /Data partition. Doesn't seem like this could be all that difficult to do especially as the functionality was previously possible.

**Additional context**
Keeping data in a separate partition is especially helpful for multi-boot users and testers. For testers even if you bow up your test system your data is intact as it is on a separate partition.

Thanks for your consideration.

**Comment by benbullard79** [comment]
Hope I made this obvious. I mean I want to have the partitioner step during Calamares install to be able to add mount points to /etc/fstab for existing Data partitions. This could or should be limited to 1 to 3 partitions to mount only? (Speculating on that.) This so the partitions are available to user after first boot in installed system. In other words a user friendly convenience or feature.

**Comment by philmmanjaro** [comment]
Well, this feature is already given. Open manual partitioning. Choose any option in the mountpoint drop-down. Go into the field again and edit it as you need/want:

![cal](https://user-images.githubusercontent.com/5050022/47244742-e871fc80-d3f6-11e8-989f-05d314c39173.png)

**Comment by benbullard79** [comment]
This is in OpenMandriva using Calamares 3.2.2. What you say was true until Calamares changed the partitioner from having the first line blank to the first line saying 'No mount point'. In fact I've been doing exactly as you said every since OpenMandriva switched to Calamares until now with most recent Calamares version where the first line was changed from blank to 'No mount point'.

If I delete 'No mount point' and add say for instance /Data1 no entry is listed under mount point in the partitioner so I presume it is not working. Worse is if I drop down to / and then add Data1 so it says again /Data1. What that does, at least in OpenMandriva, is somewhere during the install process all root partitions get mounted and installer won't format the requested partitions. 

Which having said all that brings up the point: Is this a Calamares issue or an OpenMandriva issue. If you could just help me confirm that it isn't Calamares that would be great.

**Comment by benbullard79** [comment]
FWIW: For us users it is very difficult to tell whether an issue that happens during installation is caused by Calamares or the distros configuration of Calamares. Since we are using Calamares that seems the logical place to start.

**Comment by philmmanjaro** [comment]
Currently I used a development snapshot of CAL which I ship with [Manjaro v18.0-rc2](https://osdn.net/projects/manjaro/storage/). I don't know about OpenMandriva. However, I had chosen `/opt` and changed it to `/data` as listed in the screenshot. Then I selected another partition and changed it there to `/whatever`.
 
I always recommend to start CAL in debug modus, which gives you more options to review your settings. You can do it via `sudo -E calamares -d`. Use `-h` switch to show more options.

**Comment by benbullard79** [comment]
I use:

$ pkexec /usr/bin/calamares -d

and I have terminal output of a failed install saved in a file if that 
would be helpful. First though I should try doing it the way you 
suggest, ie. changing say /opt and /var to /Data1 and /Data2. If that 
works (and I'm thinking it will) might be best to leave things as is. 
Don't think there are a lot of people doing this anyway.

Ben Bullard
ben79
--------------------
OpenMandriva-QA Team

**Comment by benbullard79** [comment]
Sorry for not replying sooner, but people and time... 

**Anyway this works for me.** 

I would wonder though if Calamares might not want to revert to leaving the original window blank so users can type in their mount point for data partitions. Is anyone that uses "Manual Partitioning" so stupid that need an option for (no mount point)? Don't quite understand that one. And to me it removes what was obviously functional and working. OR maybe include a blank line at the bottom of the list? Maybe (no mount point) has some functionality I'm not aware of?

Note: I'm operating on memory when I type (no mount point). Hope I got that correct. If not I think Y'all will get the gist of my comment.
