### ISSUE TITLE
LVM encrypted (LUKS) setup during manual partition incomplete

### ISSUE THREAD

**Issue by That-Random-Guy** [calamares/calamares#1042]
Terms Used:
LVM - Logical Volume Management
VG - Volume Group
LV - Logical Volume
FDE - Full Disk Encryption

**Describe the bug**
When manually partitioning an install where LVM is involved, the GUI goes as far as volume groups and does not then allow for the creation of LV or partitions. This leaves the user unable to continue with the install. I am attempting to install Lubuntu 18.10 x64 on a UEFI-enabled laptop. The target setup involves FDE utilizing LUKS under a LVM scheme where my /, home, and swap partitions are all encrypted.

**To Reproduce**
1. Start up Lubuntu live DVD/CD
2. Click on **Install Lubuntu 18.10** to run installer
3. Click **Next** for all timezone/keyboard layout screens until you get to **Partitions** section
4. From Partitions screen, click on/select **Manual Partition** and click Next
5. Assuming you have setup boot partition already, proceed to step 6. Otherwise, please take time to create that partition now. [OPTIONAL]
6. Click on **FreeSpace** from the visualization section of the screen. Click on **Create**. 
7. Create a Partition window will pop up. Click on the **File System** drop down menu where _ext4_ is currently selected. Select LVM2 PV.
8. Once selected, scroll down the Flags section listing different flags. Find LVM and check it.
9. Check the Encrypt checkbox found below the File System button from step 7. Enter passphrase.
10. At the bottom of the window, click OK.
11. Click on **New Volume Group** found below visualization portion of screen.
12. On Create Volume Group window, check the New Partition listing found on left pane. Enter volume group name on right pane. Click OK at bottom of window.
13. At top of the screen, click on the **Storage device** button to pull the drop down menu. Select the option that has the name of the volume you just created.
14. Visualization view is changed to volume and Create button is disabled alongside New Partition Table.

**Expected behavior**
If the installer can conceptualize up to the point of where I can create volume groups, why can't it then further process the creation of LV or partitions? It should be able to allow me to create those and then simply apply that configuration once I actually click on Install on the next screen.

**Screenshots and Logs**
Will provide on edit.

**Additional context**
I have been able to install Lubuntu 18.10 with LVM, however I needed to provision a LVM PV and VG before running the installer. Once that was setup, the installer/calamares recognized the volume and allowed me to create partitions. I had assumed up to this point that this was due to a preliminary setup being required for the LVM config. Later thinking about it, this doesn't map out correctly as throughout the entire process where I'm interacting with the GUI via Calamares, this is all conceptual. That is to say, nothing get's applied until install is initiated. So, now the question becomes: is the limitation LVM, LUKS, or Calamares? Where is the conflict coming from?

**Comment by sandrock** [comment]
Just had the exact same problem while trying to install PureOS 9.0.

Just had a similar problem with Manjaro 21.1.3.
