### ISSUE TITLE
CAL may delete partitions during disk-probe

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#1044]
**Describe the bug**
During the last phase of the **v17.1** development cycle we got a forums post claiming [**CAL** may delete existing partition content](https://forum.manjaro.org/t/37298) without a user intention to do so. Seems I mislead it with https://github.com/calamares/calamares/issues/882 back then. There was a partition mounted on `/tmp/Calamares-TqYRNd`. With some talk about it a [log](https://gist.githubusercontent.com/anonymous/84ccdff59bc8b057529b03f15ae5ea49/raw) was provided. Notable line was:

> [0]: QTemporaryDir: Unable to remove "/tmp/Calamares-TqYRNd" most likely due to the presence of read-only files.

Back then I tested further and only found `/tmp/calamares-root-5aoq_pz0` mounts, which is normal during installation phase. Since I couldn't reproduce the issue back then **v17.1** got released with **CAL v3.1.11-7**.

---

In February a second user [reported](https://forum.manjaro.org/t//37298/34) a similar issue with **CAL v3.1.12-3**. In that case it was mounted on `/tmp/Calamares-EmsHcv`. In the [log](https://gist.github.com/anonymous/2fbbba9f5104aa632091ccb6d3888641) we find a similar report:

> [0]: QTemporaryDir: Unable to remove "/tmp/Calamares-EmsHcv" most likely due to the presence of read-only files.

---

Now in October a third user [reports](https://forum.manjaro.org/t//37298/36) the same issue. In this case it got mounted in `/tmp/calamares-SxYYhk` and got the same line with **CAL v3.2.2.1-3**:

> [0]: QTemporaryDir: Unable to remove "/tmp/calamares-SxYYhk" most likely due to the presence of read-only files.

Also this drive was formatted with **ext4**. This you can see on the [session log](https://forum.manjaro.org/t/37298/38). So I went ahead and did a [full lengthy regression test](https://gist.github.com/philmmanjaro/e5926529105990e05da21f449a28c9b4) with **v18.0**. Beside a small coding issue on my end I didn't found any regression. However, we seem to [found the issue](https://forum.manjaro.org/t/37298/67). Probably because it failed to umount and then QTemporaryDir deleted the contents automatically when the function returned. By default a mount is with rw rights. Auto-remove is on by default for: QTemporaryDir mountsDir; - [doc.qt](http://doc.qt.io/qt-5/qtemporarydir.html)

Offending code exists since July-16 and got introduced with https://github.com/calamares/calamares/commit/f2f5a18984a1463f91e76790f4690104342b84ea.

**To Reproduce**
1. Start any ISO with **CAL 3.1-beta2** or higher
2. Start **CAL** and sit back
3. In rare cases *QTemporaryDir* may delete one of your existing partition during disk probe
4. You may close **CAL** at *Welcome* screen and try to restore your data if you have a backup

**Expected behavior**
Disk probe without the risk of loosing data.

**Screenshots and Logs**
![9f2dc88accc253354d9d540b9af17cd3023d9544_1_690x388](https://user-images.githubusercontent.com/5050022/47631875-1cac9200-db48-11e8-8b47-8baa7efae4f7.jpeg)

Logs: [Dec-17](https://gist.githubusercontent.com/anonymous/84ccdff59bc8b057529b03f15ae5ea49/raw), [Feb-18](https://gist.github.com/anonymous/2fbbba9f5104aa632091ccb6d3888641), [Oct-18](https://forum.manjaro.org/t/37298/67)

**Additional context**
You may find the whole story in our [forum](https://forum.manjaro.org/t/37298). Current v18.0 ISOs can be downloaded from here: [X](https://osdn.net/projects/manjaro/storage/xfce/18.0/), [K](https://osdn.net/projects/manjaro/storage/kde/18.0/), [G](https://osdn.net/projects/manjaro/storage/gnome/18.0/)

**Comment by stikonas** [comment]
Almost surely Calamares issue, never saw it with Partition Manager. @adriaandegroot can you look at it first?

**Comment by philmmanjaro** [comment]
Maybe [this](https://gitlab.manjaro.org/applications/calamares/commit/8c36035aa0015c43d1390b303449e1a86f922f86) might fix it ...

**Comment by philmmanjaro** [comment]
To be [save](https://gitlab.manjaro.org/applications/calamares/commit/5a92312cf212189c17d8b7537499a68d29ea4f05) ...

**Comment by philmmanjaro** [comment]
@adriaandegroot: do we need during disk probing write access to the drives? Seems when it fails to unmount data gets erased due to the functions of QTemporaryDir. Create random dir -> mount -> unmount -> destroy dir. We may miss some error check for unmounting drives ...

**Comment by adriaandegroot** [comment]
This is probably relevant too:

```
src/modules/unpackfs/main.py:            shutil.rmtree(source_mount_path, ignore_errors=True, onerror=None)
```

For do-not-format partitions, the whole cleanup process should be avoided entirely.

**Comment by philmmanjaro** [comment]
@adriaandegroot: it happens already in the disk-probing during displaying the **welcome** screen. The user doesn't have to interact with **CAL** at all. **unpackfs** is a different story.

**Comment by adriaandegroot** [comment]
In master I've followed @philmmanjaro suggestion, with some extra bits and pieces.

**Comment by aliveafter1000** [comment]
You wrote mountsDir.setAutoRemove( false ); twice.
Should only turn it off when mount succeeds and unmount fails.
Also mount as read only. I don't see a need for read-write mounting.

```
static FstabEntryList
lookForFstabEntries( const QString& partitionPath )
{
    FstabEntryList fstabEntries;
    QTemporaryDir mountsDir;
    mountsDir.setAutoRemove( false );

    int exit = QProcess::execute( "mount", { partitionPath, mountsDir.path() } );
    if ( !exit ) // if all is well
    {
        QFile fstabFile( mountsDir.path() + "/etc/fstab" );
        if ( fstabFile.open( QIODevice::ReadOnly | QIODevice::Text ) )
        {
            const QStringList fstabLines = QString::fromLocal8Bit( fstabFile.readAll() )
                                     .split( '\n' );

            for ( const QString& rawLine : fstabLines )
                fstabEntries.append( FstabEntry::fromEtcFstab( rawLine ) );
            fstabFile.close();
            std::remove_if( fstabEntries.begin(), fstabEntries.end(), [](const FstabEntry& x) { return !x.isValid(); } );
        }

        if ( QProcess::execute( "umount", { "-R", mountsDir.path() } ) )
        {
            cWarning() << "Could not unmount" << mountsDir.path();
            // There is stuff left in there, really don't remove
            mountsDir.setAutoRemove( false );
        }
    }

    return fstabEntries;
}
```

**Comment by philmmanjaro** [comment]
@adriaandegroot: shouldn't we go like [this](https://gitlab.manjaro.org/applications/calamares/compare/4c73fc0...7c6ff1a3)?
