### ISSUE TITLE
license module show_full

### ISSUE THREAD

**Issue by damianatorrpm** [calamares/calamares#1052]
**Is your feature request related to a problem? Please describe.**
Being able to show the full contents of a text file in the local file system e.g
singleEntry:
- id:       distro      
  name:     Linux      
  fullText: /usr/share/doc/GPL.txt

The current UI looks very nice but I am not sure that in case of any dispute only _linking_ to the actual licenses is somehow legally binding... I have never seen an installer except calamares linking to licenses and not showing them in full text.

**Comment by adriaandegroot** [comment]
That's a useful addition. The code in that module could use a re-work, in any case.

**Comment by adriaandegroot** [comment]
There's a branch for this now. It looks to me like a good example of something that could be done well in QML.
