### ISSUE TITLE
Make a .MSI installer for non techie newcomers - WUBI did this but it was closed -

### ISSUE THREAD

**Issue by mitcoes** [calamares/calamares#1053]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mitcoes** [comment]
Now liGNUx is getting a new hype with ChromeOS and Samsung Galaxy devices compatibility with deb packages.
Some small companies, employees, and students that are not very techie would love to prove liGNUx OSs if they were as easy way to install it as an ALMOST ONE CLICK system, plus a few yes/no/edit questions, including one to setup it in bare metal, LXC or QEMU/KVM.

And enjoy it as an appliance.

PS: A version for running in Android ARM devices under a hardware accelerated GPU LXC or better option would also be great - I know LXC GPU passthrough is soon to come, but still not here now -.

**Comment by kkofler** [comment]
IMHO, this is mostly out of the scope of Calamares, but there is a task that may be in scope. (I'll let @adriaandegroot make the call, he is the maintainer, I'm just a not-very-active-anymore contributor.)

First of all, FYI, a maintained fork of WUBI exists: https://github.com/hakuna-m/wubiuefi/

IMHO, the only thing that sounds like it may be in the scope of Calamares would be to allow it to be used together with WubiUEFI. The documented requirement that WubiUEFI expects from the distro and its installer is: _On the Linux side, the distribution must be capable of booting and rebooting off a loop file, perform an automatic installation and accept the special boot parameters that indicate the local preseed file and ISO image to boot from._ I think this is pretty much dependent on the existing feature requests #508, #530 and/or #942.

**Comment by mitcoes** [comment]
Thanks a lot. for the wubiuefi information, 
And I hope to see soon enough MSI or EXE wubiuefi based installers in CALamares' distributions web pages download sections, better if they also post "how to" videos for non techie people.
Because one thing is that "can be done"
The other "doing it"

**Comment by kkofler** [comment]
The idea here is to have an installer for a GNU/Linux distribution running on Windows. So the MSI/EXE installer downloads the ISO, boots into it, and installs it into a loop-mounted file on the Windows partition. The first two steps are probably not something Calamares ever wants to attempt doing, so a separate tool such as WubiUEFI is what would be used there. For the last step to work, the installation of the ISO is automated by WubiUEFI, so this can only work if Calamares were to implement a suitable automation interface (and possibly WubiUEFI adapted for it, if we cannot implement exactly the interface they expect; I doubt any version of Wubi has ever been tested with anything other than Ubiquity).

**Comment by adriaandegroot** [comment]
I'm closing this as "would be interesting, but must have engineering effort from those that want it". It's never going to get to the top of **my** pile of things-to-do, so the practical thing is to PR it.
