### ISSUE TITLE
Let add a menu to choose WM or DE

### ISSUE THREAD

**Issue by mitcoes** [calamares/calamares#1054]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by philmmanjaro** [comment]
Please update your request or we may close it without further notice.

**Comment by mitcoes** [comment]
**Describe the solution you'd like**
Choose WM or DE: 
1-GNOME 2.-KDE 4.-XFCE 5,.MATE 6.- LXQt 7.- Deepin 8.- Pantheon 9.- Trinity 10.- Cinnamon  11.- Budgie 12.- i3 13. Awesome 14.- Fluxbox 15.- JWM 16.- Xmonad 17.- Openbox 18.- DWM 19.- bsp 20.- Musca 21.- Spectr 22.- SF 23.- Ice 24.- Herbsluft 25.-Ratpoison 26.- Enlightenment 27.- 5d and some other more they can add
**Alternative**: CLI installers, Net installers, Antergos' installer
**Additional context** 
Save this way space hosting several ISOs spins making only, the big offline one with all the options inside, and the small one that have only common and default packages and configurations and download all what is selected to install that is different
Only differential packages and profiles from the default ISO stored in a text file to download

**Comment by philmmanjaro** [comment]
**CAL** is a installer framework. With the right modules developed it would be possible to achieve that request. This is however up to the distro maintainers on how to use **CAL**. Also it may fail, since you have to maintain the profiles, especially on a rolling release like Arch.

**Comment by philmmanjaro** [comment]
You may want to take a look at [netinstall](https://github.com/calamares/calamares/tree/master/src/modules/netinstall) ...

**Comment by mitcoes** [comment]
I do not need it, I use liGNux systems since the 90s when I had to copy spanish keyboard drivers from UNIX systems
I am asking it for not so techie people that want choice and KISS installer
By the way CALAMARES is going to be soon the "de facto" standard as it is better than others so congratulations

**Comment by mitcoes** [comment]
Sorry i did not read the one beginning with **CAL** in rolling releases, the very small files containing the list of packages and the configuration files, can be versioned, so this "version spin package" can be updated even before installing - or not -. 
Something similar that what is done in installed Manjaro systems when version changes.

**Comment by kkofler** [comment]
This is already possible with the `netinstall` module. If you want your distribution to set that up that way, you have to take that up with the distribution. This is a downstream distribution choice.

**Comment by adriaandegroot** [comment]
Aside from the `netinstall` module, as @kkofler points out, there are issues #1029, #1036, #1026 that are pointing the way to more fancy / configurable QML-based pages inside Calamares, where this kind of question could be asked.
