### ISSUE TITLE
Packages module can't handle dicts

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#1057]
I tried to use a wildcard with the packages module as shown here:

```
update_db: true
backend: apt
operations:
  - remove:
```
...
```
      - package: "language-pack-!(en)"
        pre-script: "shopt -s extglob"
```

This is the result:

![image](https://user-images.githubusercontent.com/3689821/48667507-0e91c780-ea9d-11e8-8d4a-d9df8142e5a2.png)

I should be able to do this no problem, but it seems I can't.

**Comment by tsimonq2** [comment]
A quick note for people who might be questioning my motive here; my long-term goal is to be able to do this:

```
      - package: "language-pack-!(${LOCALE})"
        pre-script: "shopt -s extglob"
```

**Comment by kkofler** [comment]
`pre-script` is only supported for `install`, not `remove`.

**Comment by tsimonq2** [comment]
> `pre-script` is only supported for `install`, not `remove`.

But it's possible. If it isn't supported, that needs to be made clear.

**Comment by adriaandegroot** [comment]
There's a branch *package-scripts* that adds this possibility to all operations, so you can use pre- and post-scripts as needed in remove situations as well.

As for @tsimonq2 your long-term goal, these(pre-script, installation, and post-script) run as three separate commands, in three separate shells, so setting shell options in one of the scripts is not going to persist into the installation shell. I **imagine** the thing you are trying to do is remove-all-the-packages matching the given regular expression. How will shell globbing do that? (In the sense of, the next shell command might then be `apt remove language-pack-!(de)`) Or, for that matter, isn't the package manager smart enough to handle those expressions? Don't forget that for (dumb?) reasons if English is selected, a LOCALE-naming package may be ignored (it is documented to be ignored on install, anyway).
