### ISSUE TITLE
Module Packages - try_remove gives an error

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1063]
In the first instance I would appreciate someone taking a look at this piece of code.
You know I am willing to help and debug it further if needed.

`        elif key == "try_remove":
            _change_mode(REMOVE)
            for package in package_list:
                try:
                    pkgman.remove_package(package)
                except subprocess.CalledProcessError:
                    warn_text = "Could not remove package "
                    warn_text += str(package)
libcalamares.utils.warning(warn_text)`

You can find it in this file.
https://github.com/calamares/calamares/blob/master/src/modules/packages/main.py
Line 465

On ArcoLinux calamares 3.2.2 this seems to give an error.

When I changed my settings to **remove** rather than **try_remove** everything uninstalls fine.
This seems to suggest that there might be an issue with the try_remove part.

Can you have a look?

![error](https://user-images.githubusercontent.com/36679406/50607611-103b1180-0eca-11e9-864e-fc562a167025.png)

**Comment by arcolinuxz** [comment]
Closing for now. 
This needs to be re-examined.

**Comment by adriaandegroot** [comment]
> On ArcoLinux calamares 3.2.2 this seems to give an error.

This code isn't in Calamares 3.2.2, only in master (unreleased). It's a bug, though, and thanks for reporting it.
