### ISSUE TITLE
Closing Calamares

### ISSUE THREAD

**Issue by dr0piing** [calamares/calamares#1065]
After start up Calamares closing.
`[manjaro@manjaro ~]$ sudo calamares -d
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
20:24:13 [6]: Using log file: "/root/.cache/calamares/session.log" 
20:24:13 [6]: Using Calamares QML directory "/usr/share/calamares/qml" 
20:24:13 [6]: Using Calamares settings file at "/etc/calamares/settings.conf" 
20:24:13 [6]: Using Calamares branding file at "/usr/share/calamares/branding/manjaro/branding.desc" 
20:24:13 [2]: WARNING: the branding component "/usr/share/calamares/branding/manjaro" does not ship translations. 
20:24:13 [6]: Loaded branding component "manjaro" 
20:24:13 [6]: STARTUP: initQmlPath, initSettings, initBranding done 
20:24:13 [6]: STARTUP: initModuleManager: module init started 
20:24:13 [6]: STARTUP: initModuleManager: all modules init done 
20:24:13 [6]: STARTUP: initJobQueue done 
20:24:13 [6]: Available size QSize(1366, 723) 
20:24:13 [6]:   Proposed window size: 1024 540 
20:24:13 [6]: STARTUP: CalamaresWindow created; loadModules started 
20:24:13 [6]: Loaded module configuration "/etc/calamares/modules/welcome.conf" 
20:24:13 [6]: Matching exact locale QLocale(English, Latin, United States) 
20:24:13 [6]:  .. Matched locale  "en_US" 
20:24:13 [6]: Looking for translations for "en_US" 
20:24:13 [6]:  .. Calamares using locale: "en_US" 
20:24:13 [6]: Welcome string false "Manjaro Linux 18.0.1 \"Illyria\"" 
20:24:14 [6]: ViewModule "welcome@welcome" loading complete. 
20:24:14 [6]: Loaded module configuration "/etc/calamares/modules/locale.conf" 
20:24:14 [2]: WARNING: guessLocaleConfiguration can't guess from an empty list. 
20:24:14 [6]: ViewModule "locale@locale" loading complete. 
20:24:14 [6]: Loaded module configuration "/usr/share/calamares/modules/keyboard.conf" 
20:24:15 [6]: ViewModule "keyboard@keyboard" loading complete. 
20:24:15 [6]: Loaded module configuration "/usr/share/calamares/modules/partition.conf" 
20:24:15 [8]: Loaded backend plugin:  "pmlibpartedbackendplugin"
20:24:15 [6]: ViewModule "partition@partition" loading complete. 
20:24:15 [6]: Loaded module configuration "/etc/calamares/modules/users.conf" 
20:24:15 [6]: ViewModule "users@users" loading complete. 
20:24:15 [6]: ViewModule "summary@summary" loading complete. 
20:24:15 [6]: Module "partition@partition" already loaded. 
20:24:15 [6]: QML import paths: 
     "/usr/share/calamares/qml" 
     "/usr/bin" 
     "qrc:/qt-project.org/imports" 
     "/usr/lib/qt/qml" 
20:24:15 [6]: Loaded module configuration "/usr/share/calamares/modules/mount.conf" 
20:24:15 [6]: Loaded module configuration "/etc/calamares/modules/unpackfs.conf" 
20:24:15 [6]: Loaded module configuration "/etc/calamares/modules/machineid.conf" 
20:24:15 [6]: Loaded module configuration "/usr/share/calamares/modules/fstab.conf" 
20:24:15 [6]: Module "locale@locale" already loaded. 
20:24:15 [6]: Module "keyboard@keyboard" already loaded. 
20:24:15 [6]: Loaded module configuration "/usr/share/calamares/modules/luksopenswaphookcfg.conf" 
20:24:15 [6]: Loaded module configuration "/etc/calamares/modules/initcpio.conf" 
20:24:15 [6]: Module "users@users" already loaded. 
20:24:15 [6]: Loaded module configuration "/etc/calamares/modules/displaymanager.conf" 
20:24:15 [6]: Loaded module configuration "/etc/calamares/modules/mhwdcfg.conf" 
20:24:15 [6]: Loaded module configuration "/etc/calamares/modules/services.conf" 
20:24:15 [6]: Loaded module configuration "/usr/share/calamares/modules/grubcfg.conf" 
20:24:15 [6]: Loaded module configuration "/etc/calamares/modules/bootloader.conf" 
20:24:15 [6]: Loaded module configuration "/etc/calamares/modules/postcfg.conf" 
20:24:15 [6]: Loaded module configuration "/usr/share/calamares/modules/umount.conf" 
20:24:15 [6]: Loaded module configuration "/etc/calamares/modules/finished.conf" 
20:24:15 [6]: ViewModule "finished@finished" loading complete. 
20:24:15 [6]: STARTUP: loadModules for all modules done 
20:24:15 [6]: STARTUP: Window now visible and ProgressTreeView populated 
20:24:15 [2]: WARNING: guessLocaleConfiguration can't guess from an empty list. 
20:24:15 [6]: Need at least storage bytes: 8482560409 
20:24:16 [6]: Need at least ram bytes: 1073741824 
20:24:16 [6]: A battery exists, checking for mains power. 
20:24:16 [6]: RequirementsChecker output: 
     enoughStorage :   true 
     enoughRam :   true 
     hasPower :   true 
     hasInternet :   true 
     isRoot :   true 
20:24:16 [6]: xkbmap selection changed to:  "us" - "" 
20:24:17 [0]: blkid: unknown file system type  ""  on  "/dev/sda1"
20:24:17 [8]: getting smart status failed for  "/dev/sdb" :  Operation not supported
20:24:18 [6]: Removing unsuitable devices: 2 candidates. 
20:24:18 [6]:   .. Removing device with iso9660 filesystem (probably a CD) on it "/dev/sdb" 
20:24:18 [6]: LIST OF DETECTED DEVICES: 
20:24:18 [6]: node      capacity        name    prettyName 
20:24:18 [6]: "/dev/sda" 500105249280 "ATA WDC WD5000LPVX-2" "ATA WDC WD5000LPVX-2 – 465.76 GiB (/dev/sda)" 
20:24:18 [6]: .. 1 devices detected. 
20:24:18 [6]: Fetching GeoIP data from "https://geoip.kde.org/v1/calamares" 
20:24:18 [8]: QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://geoip.kde.org/v1/calamares")
Segmentation fault
`

**Comment by philmmanjaro** [comment]
The service `https://geoip.kde.org/v1/calamares` is not available anymore. You may want to disable the connection to the internet and try again. Normally it should not matter if that service is given or not.

**Comment by dr0piing** [comment]
Thank you

**Comment by adriaandegroot** [comment]
> The service `https://geoip.kde.org/v1/calamares` is not available anymore. You may want to disable the connection to the internet and try again. Normally it should not matter if that service is given or not.

 - calamares shouldn't crash if the geoip service is not available
 - there's a weird message about startOperation in the log
 - the service wasn't supposed to be down, that was accidental; it has now been restarted.
