### ISSUE TITLE
Encryption crashes Calamares

### ISSUE THREAD

**Issue by es20490446e** [calamares/calamares#1066]
https://forum.manjaro.org/t/encryption-crashes-calamares/70713

**Comment by abucodonosor** [comment]
What kind of crappy bug report is that ?

**Comment by adriaandegroot** [comment]
@philmmanjaro Can you check this downstream and then file a good bug report with a backtrace here?

@abucodonosor There's a better way to phrase that.

@es20490446e Please don't just link. Copy the bug report text. Read the bug report form for Calamares: even the downstream report doesn't give us the information we need, and a backtrace is something we need **at minimum**. I'd suggest letting downstream handle this first.

**Comment by philmmanjaro** [comment]
@adriaandegroot: can be ignored. This seems to be in regard of our Sister Projekt Manjaro32. Also in the forum post nothing additional is added to this "report". No stacktrace, no logs, nothing.
