### ISSUE TITLE
New partition flags not shown when editing partition

### ISSUE THREAD

**Issue by paddatrapper** [calamares/calamares#1067]
**Describe the bug**
While in manual partitioning, flags set on a partition are not shown when editing a partition after creating it.

**To Reproduce**
1. Step through to partitioning
2. Click on 'Manual partitioning'
3. Create a partition and set the boot flag
4. Select partition and click 'Edit'
5. No flags are shown as active

**Expected behavior**
The active flags should be shown for the partition.

**Additional context**
Calamares version: 3.1.6

**Comment by adriaandegroot** [comment]
That Calamares version is a little over a year old, and there are five 3.1.x versions after it, as well as a bunch of 3.2 versions; this particular problem is fixed in 3.2.x (anything after May 2018).
