### ISSUE TITLE
Partition Page Combobox Does not Show Full Text

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#1071]
Partition page includes squashed drop down box 

The combobox after "Select Storage Device" on the Partitions page is squashed and doesn't display the full text.  Tested with master from January 10th in KDE neon Dev Unstable.

http://embra.edinburghlinux.co.uk/~jr/tmp/calamares-installer-disk-erase-selected.png
vs
http://embra.edinburghlinux.co.uk/~jr/tmp/calamares-installer-disk-erase-selected-old.png

**Comment by jriddell** [comment]
Same for the "Boot loader location:" combobox when installing in BIOS mode

**Comment by stikonas** [comment]
Should be fixed by https://invent.kde.org/kde/kpmcore/commit/e5a20926cdf405d01011a5789886e450882785cb

**Comment by adriaandegroot** [comment]
(upstream fix in kpmcore)

**Comment by jriddell** [comment]
Yeah looks lovely now 
https://i.imgur.com/LDgSg2M.png
