### ISSUE TITLE
Crash selecting Erase Disk

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#1084]
Calamares crashes when selecting Erase Disk in partitioning page.

Application: Calamares (_neon), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7fcc7c51a280 (LWP 1402))]

Thread 8 (Thread 0x7fcc2d69d700 (LWP 1435)):
#0  0x00007fcc7998d0b4 in __GI___libc_read (fd=20, buf=0x7fcc2d69cd50, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007fcc757e3cd0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcc7579f027 in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcc7579f4e0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcc7579f8d2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fcc2dbc5026 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007fcc757c7105 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fcc778746db in start_thread (arg=0x7fcc2d69d700) at pthread_create.c:463
#8  0x00007fcc7999e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fcc3d38f700 (LWP 1434)):
#0  __libc_disable_asynccancel () at ../sysdeps/unix/sysv/linux/x86_64/cancellation.S:96
#1  0x00007fcc79991c0d in __GI___poll (fds=0x7fcc4c090330, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#2  0x00007fcc7579f539 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcc7579f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcc7579f691 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fcc757c7105 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fcc778746db in start_thread (arg=0x7fcc3d38f700) at pthread_create.c:463
#7  0x00007fcc7999e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fcc3cb8e700 (LWP 1427)):
#0  0x00007fcc7998d100 in __GI___libc_read (fd=12, buf=0x7fcc3cb8dbc0, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007fcc757e3cd0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcc7579f027 in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcc7579f4e0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcc7579f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fcc7a4ec15b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fcc7a48d64a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fcc50b05a34 in ?? () from /usr/lib/x86_64-linux-gnu/libkpmcore.so.8
#8  0x00007fcc7a2b6bc2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fcc778746db in start_thread (arg=0x7fcc3cb8e700) at pthread_create.c:463
#10 0x00007fcc7999e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fcc3e98a700 (LWP 1422)):
#0  0x00007fcc7998d0b4 in __GI___libc_read (fd=15, buf=0x7fcc3e989c10, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007fcc757e3cd0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcc7579f027 in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcc7579f4e0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcc7579f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fcc7a4ec15b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fcc7a48d64a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fcc7a2b541a in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fcc7a2b6bc2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fcc778746db in start_thread (arg=0x7fcc3e98a700) at pthread_create.c:463
#10 0x00007fcc7999e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fcc4b5b6700 (LWP 1419)):
#0  0x00007fcc7998d0b4 in __GI___libc_read (fd=13, buf=0x7fcc4b5b5bf0, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:27
#1  0x00007fcc757e3cd0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcc7579f027 in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcc7579f4e0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcc7579f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fcc7a4ec15b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fcc7a48d64a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fcc7a2b541a in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fcc78e132e5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#9  0x00007fcc7a2b6bc2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fcc778746db in start_thread (arg=0x7fcc4b5b6700) at pthread_create.c:463
#11 0x00007fcc7999e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fcc6060b700 (LWP 1404)):
#0  0x00007fcc7579e9f1 in g_main_context_prepare () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007fcc7579f46b in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcc7579f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcc7a4ec15b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007fcc7a48d64a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fcc7a2b541a in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fcc70797015 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007fcc7a2b6bc2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fcc778746db in start_thread (arg=0x7fcc6060b700) at pthread_create.c:463
#9  0x00007fcc7999e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fcc6d25a700 (LWP 1403)):
#0  0x00007fcc79991bf9 in __GI___poll (fds=0x7fcc6d259d38, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fcc74aea747 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fcc74aec36a in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fcc70cbcd4a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007fcc7a2b6bc2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fcc778746db in start_thread (arg=0x7fcc6d25a700) at pthread_create.c:463
#6  0x00007fcc7999e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fcc7c51a280 (LWP 1402)):
[KCrash Handler]
#5  0x00007fcc7b618198 in QComboBox::currentData(int) const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007fcc50dce249 in ChoicePage::applyActionChoice(ChoicePage::InstallChoice) () from /usr/lib/x86_64-linux-gnu/calamares/modules/partition/libcalamares_viewmodule_partition.so
#7  0x00007fcc7a4bef3f in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fcc7a4bef3f in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fcc7b6071af in QButtonGroup::buttonToggled(int, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007fcc7b602ba0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fcc7b604176 in QAbstractButton::setChecked(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fcc7b603c7b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007fcc7b603edd in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007fcc7b55b838 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007fcc7b51b83c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007fcc7b523ca8 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fcc7a48f328 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fcc7b52229f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007fcc7b576a80 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007fcc7b57934a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007fcc7b51b83c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007fcc7b522dd0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007fcc7a48f328 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007fcc7aced52b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#25 0x00007fcc7acee695 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007fcc7acc714b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007fcc70cbdd2a in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#28 0x00007fcc7579f387 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fcc7579f5c0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007fcc7579f64c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007fcc7a4ec13f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007fcc7a48d64a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007fcc7a496800 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x0000556090031d6e in main ()

This happens both with and without the patch that crazy suggested on IRC https://crazy.dev.frugalware.org/cala/revert-some-lvm-code-causing-crashes.patch
so we do not think it is related to https://github.com/calamares/calamares/issues/1061

This is KDE neon git unstable build from today master

**Comment by adriaandegroot** [comment]
Is this every time you select *erase*, or -- like #1061 -- after clicking around a bit?

**Comment by adriaandegroot** [comment]
I built Calamares on a pre-release of Netrunner Blackbird (19.01; the 20190114 image I think) and it does crash every time I select *erase*. Entirely **unlike** my development VM (an older Manjaro) which hasn't complained at all.
