### ISSUE TITLE
Calamares crashes when being indecisive about encryption password

### ISSUE THREAD

**Issue by highvoltage** [calamares/calamares#1086]
Testing Calamares 3.2.3 on the latest debian live images (will test 3.2.4 as soon as that's on the next ISO), and when I enter encryption passwords and change my mind about it a few times, I gets a segfault. Sometimes after the first time, sometimes after several times (as in the gif below).

1. Start calamares from debian live (from https://cdimage.debian.org/cdimage/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-gnome.iso or any other image on https://cdimage.debian.org/cdimage/weekly-live-builds/amd64/iso-hybrid/)
2. On the partitioning screen, change/mismatch/match the encryption passwords for a bit

**Expected behavior**
No Segfaults ever! ♥

**Screenshot**
![peek 2019-02-15 14-59](https://user-images.githubusercontent.com/117850/52858527-0ea07280-3133-11e9-9fa1-e775d723858c.gif)

**Comment by abucodonosor** [comment]
same as https://github.com/calamares/calamares/issues/1061

patch with this:
https://github.com/calamares/calamares/commit/6316173f1ba87aede1a1c872b9997a6919374c30
https://github.com/calamares/calamares/commit/b9fa0398c0d286d98869b0f07a6078ed8148c2cd

or use v3.2.4 :-)

**Comment by adriaandegroot** [comment]
Thanks for the careful bug report. @abucodonosor is right, that looks pretty much exactly like the crash we solved for 3.2.4 release. I'll leave this open for you to check against the latest release.

**Comment by adriaandegroot** [comment]
Closing this as presumed-fixed presumed-duplicate.
