### ISSUE TITLE
Feature request: Details page.

### ISSUE THREAD

**Issue by Overc1ocker** [calamares/calamares#1088]
Hello, I recently installed manjaro with the calamares installer, and I really like it! I was wondering however, if you can add a “show details.” Tab for debugging purposes, kind of like Ubuntu’s ubiquity has it.

**Comment by philmmanjaro** [comment]
You can simply start **CAL** via `sudo -E calamares -d` to have the debug mode. Then simply click on the left button to get it visual displayed. Also you may get more output when starting from within a **terminal**.

**Comment by Overc1ocker** [comment]
Thanks! Will have to try that. This may be closed if no further work is required.

**Comment by adriaandegroot** [comment]
There's two parts to this (with three bullet points):
 - when you run Calamares with the `-d` flag, you put it in *debug* mode. In debug mode, there's a *Show debug information* button in the lower-left of the window, at the bottom of the *sequence* list. It may be hard to spot, depending on your color scheme. That will show you internal settings for Calamares.
 - When you start Calamares, it prints debugging information to the terminal. Warnings and errors are always printed. You can use the `-D` option to control how much is printed; in general for debugging you do `-D8` and get it all.
 - When you start Calamares, it **always** logs to a file, and it logs everything there. In the terminal it may even tell you where that file is, for instance:
    ```
   09:27:16 [6]: Using log file: "/home/adridg/.cache/Calamares/session.log" 
   ```
   The log file goes in the home-directory of the user running Calamares, so most often you'll have it in root:
   ```
   09:44:14 [6]: Using log file: "/root/.cache/Calamares/session.log" 
   ```

So from **inside** the application, you can use the *show debug* button. From outside the application, you can always look at the log file.
