### ISSUE TITLE
Allow changing the default ESP size in partition.conf

### ISSUE THREAD

**Issue by christophercormier** [calamares/calamares#1090]
**Is your feature request related to a problem? Please describe.**
Certain Calamares configurations tend to error out during the install because, with a 300MB ESP, it's still possible to hit the capacity of the EFI partition, especially with the growing size of initrd.img files. Recent Debian kernels have the size scaling to 60MB, requiring only a few of these to cause major issues. An inflexible default ESP size makes it hard to work around this.

**Describe the solution you'd like**
A configuration option in partition.conf which lets you set the default size of an EFI System Partition. 
This could work either as an option where you can set a static size for the ESP, e.g. 600M, or with something more nuanced like partition layouts where you can set a minimum size and a percentage of the total drive capacity that it'll scale to if possible.

**Describe alternatives you've considered**
None that I'm aware of.

**Comment by adriaandegroot** [comment]
That sounds like a pretty useful thing indeed. Existing code looks like this:

```
src/modules/partition/core/PartitionActions.cpp:    int uefisys_part_sizeB = isEfi ? 300_MiB : 0_MiB;
```

I'm going to set this -- it's a small feature -- for the next release.

**Comment by marcopik** [comment]
@chloecormier transgender pedophile from tf2c
watch out
they look like male, wear female clothes, have male voice and rape kids :(
![wattae](https://user-images.githubusercontent.com/107511933/173684846-93a267ac-0d2a-499b-bad6-2c520f5f79e2.jpg)
