### ISSUE TITLE
MBR install target selection resets after adding partition [3.2.4]

### ISSUE THREAD

**Issue by domohawk** [calamares/calamares#1098]
Manjaro Version: 18.03 stable
Calamares: 3.2.4

1. Enter manual partitioning
2. Select "Install boot loader on" to a disk other than first
3. Create a Partition
4. "Install boot loader on" is now reset to first selection

You can see in logs, after I create the partition:
    PartitionPage:updateBootLoaderInstallPath "/dev/sda"
is called, as the last log line after adding a partition.

**Comment by philmmanjaro** [comment]
Currently we use **v3.2.4** on Manjaro. I slightly remembered that this issue is still open.

**Comment by abucodonosor** [comment]
Version: 18.03 ? Are you guys talking about Manjaro versions ?

**Comment by philmmanjaro** [comment]
@abucodonosor: yes **18.0.3** is the current stable release with **CAL 3.2.4**.

**Comment by abucodonosor** [comment]
This one seems to be around since a long time.

But while looking at it I found a much worse bug ..

**Comment by adriaandegroot** [comment]
Confirmed. It's also surprisingly difficult to fix. When the partition is created, the devices are re-scanned, and the combo-box re-filled, and that seems to cause a selection event, and then your selection is lost.
