### ISSUE TITLE
Improve wording for "initial setup" use-case

### ISSUE THREAD

**Issue by a-wai** [calamares/calamares#1100]
When using calamares as an "initial setup" tool (create user, select locale & keyboard layout), the default wording can be confusing, leading the user to believe he is actually installing the system to disk, the primary issue here being the use of the words "installation" and "installer".

It could be useful to set a configuration option in order to select the use-case for calamares, and select the wording accordingly (having e.g. a new argument in strings referring to the installation process).

Another option would be to allow the strings to be imported from the branding or modules' config files (most notably the `welcome` and `finished` modules), but I guess it would complicate the translation process way too much.

Any thoughts about this are welcome.

**Comment by adriaandegroot** [comment]
If *dont-chroot* is *true*, then we're in (OEM) setup mode. Would we actually need a separate setting? I'd prefer not to introduce knobs if they are not needed.

In any case: if we know we're in *setup* mode rather than *install* mode then we'll have to go through strings to identify them and introduce alternatives.

**Comment by adriaandegroot** [comment]
There's some preliminary work in branch issue-1100; at least the welcome and quit parts have had strings adjusted. In the end I made *oem-setup* the key in `settings.conf` so that I could test this independently of the rest of the settings.

Please take a look and make suggestions.

**Comment by a-wai** [comment]
That looks good to me overall, it's quite close to what I had started actually (before I had to switch to other tasks for a while).
I can take it from here if you want, I should have some time to work on it this week.

**Comment by adriaandegroot** [comment]
Merged into master for 3.2.5 instead.
