### ISSUE TITLE
Trying to launch bash commands from within calamares

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1102]
I would like to launch the linux commands that are now in a cleanup script from within Calamares.

After installation of ArcoLinux we make sure all remnants are cleaned up.

I thought I could use shellprocess to do the job.

So I have tried adding it to calamares as you can see in the link.

https://github.com/arcolinux/arcolinux-calamares-dev/commit/94734ad8329fe0844a093540273466516ae47d50

I have added also shellprocess to the list in setttings.conf.

This is the original text

`dontChroot: false
timeout: 10
script:
    - "-touch @@ROOT@@/tmp/thingy"
    - "/usr/bin/false"
    - command: "/usr/local/bin/slowloris"
      timeout: 3600`

When I delete everything starting with the "-touch" line - there will be no errors.
Then I have tried several options one by one.

I had no luck in getting past the error.

Any insight is appreciated. Maybe I need an other module all together.

**Comment by abucodonosor** [comment]
The commit you pointing out has broken formating of the configuration file.

You should see a error from calamares about that. Something like:

```
ERROR: YAML parser error  yaml-cpp: error at line X, column X: illegal block entry
...

```
And then the module is disabled. 

In master you should see that in UIX on startup too also.

Also I would do that a bit different. 
Add some calamares-post-script you package with calamares.
In this script put all workarounds/cleanup for post install and then simple have that in shellprocess.

```
dontChroot: false
timeout: 10
script:
    - command: "/usr/sbin/calamares-post-script"
      timeout: 180

```

**Comment by adriaandegroot** [comment]
@abucodonosor, the whole point of the shellprocess module is to run shell commands, one at a time. By all means use a separate shell script if you have more complicated error-handling to do, but in **principle** the shellprocess module can do what's (seems to be) needed.

@arcolinuxz as pointed out, the file you've added is not formatted correctly as YAML. Also, *dontChroot* is *false*, so using *@@ROOT@@* is weird: the commands are executed in the chroot (target system). In any case: you don't say what the errors are that you get -- startup, or runtime, or during installation?

**Comment by abucodonosor** [comment]
@adriaandegroot 

sure but I don't mean in general , I was looking at was he is trying to do .. and all commads are 
'rm something' , with a script you can even know something failed to be deleted and print a message ,
since the cleaning seemsto be  important there.

**Comment by arcolinuxz** [comment]
@abucodonosor  - that is indeed what I did 
> dontChroot: false
> timeout: 10
> script:
>     - command: "/usr/sbin/calamares-post-script"
>       timeout: 180

Mine is called /usr/bin/cleanup.sh. I did not have the timeout of 180 in place and got an error. 
I will document some more later.

I will take a picture but it is just a general message

**Comment by arcolinuxz** [comment]
![shellprocess](https://user-images.githubusercontent.com/36679406/53664581-2581b180-3c69-11e9-8627-ff77b5a972c3.png)
I have immediately tried again.
You can see the shellprocess in the settings.conf
the contents in shellprocess.conf
the command exists
I do not know what Calamares wants now?

**Comment by arcolinuxz** [comment]
Calamares -d gives this

https://pastebin.com/FwH3hh79

These two lines seem out of place there nr 57 en 58

**Comment by abucodonosor** [comment]
@arcolinuxz 

your configuration is still wrong formated, see:

```

21:31:34 [1]: ERROR: YAML parser error  yaml-cpp: error at line 33, column 2: illegal block entry
21:31:34 [1]: ERROR: Module "shellprocess@shellprocess" cannot be created from descriptor "shellprocess.conf"

```

**Comment by adriaandegroot** [comment]
What **might** be confusing you is that the YAML file -- which is badly formatted -- may have mixed tabs and spaces. That may display as if it's all aligned correctly, but it isn't. Make sure sure sure that you are using only spaces to indent in YAML files, and that the spacing indent is consistent.

**Comment by arcolinuxz** [comment]
OMG - yam definitely hates tabs... 

it started off with a tab

No error - now I can continue developing.

Thanks @adriaandegroot  - tip of the end 
and for Calamares users to know
