### ISSUE TITLE
Need to use sed within shellProcess within Double Quotes, correct format?

### ISSUE THREAD

**Issue by d3signr** [calamares/calamares#1103]
Hi,
I'm trying to use the sed command within the shellProcess module but am a little stuck as to how to format the string correctly since the entire line is within double quotes as per the shellProcess examples.

However, i'm having trouble formatting the string correctly so that the part i want sed to act upon is also in double quotes. 
```
- "sed -i "s/^Icon=.*/Icon=/home/@@USER@@/.face/g" @@ROOT@@var/lib/AccountsService/users/@@USER@@"
```
As you can see this won't work as sed is seeing the quote "s as an unknown use flag.

Any suggestions please?

Many thanks

**Comment by kkofler** [comment]
You can either use single quotes or escape each double quote inside the double-quoted string with a backslash.

(Note that single-quoted strings do not support backslash escapes, so if you want a single quote inside a single-quoted string, you have to double the single quote, i.e., use 2 single quotes (not a double quote), instead.)

**Comment by d3signr** [comment]
Do you mean like this?

`- "sed -i \"s/^Icon=.*/Icon=/home/@@USER@@/.face/g\" @@ROOT@@var/lib/AccountsService/users/@@USER@@"`

I think i tried this and Calamares said their was a problem with the way the module was configured.

**Comment by abucodonosor** [comment]
How this is an calmares bug ?

That sed line is broken no matter where you would use it.

What you probably want is something like this:

```
sed -i -e "s/^Icon=.*/Icon=\/home\/@@USER@@\/.face/g" ...

```

**Comment by d3signr** [comment]
> How this is an calmares bug ?
> 
> That sed line is broken no matter where you would use it.
> 
> What you probably want is something like this:
> 
> ```
> sed -i -e "s/^Icon=.*/Icon=\/home\/@@USER@@\/.face/g" ...
> ```

Ah, my bad thank you. But, the line still needs to be within double quoted string as shown, so what is the best way to escape the double quotes for the sed part?

Thanks

**Comment by abucodonosor** [comment]
@d3signr 

Don't get me wrong but this is not the place to teach you how to use sed or regexp.

man sed should be a starting point for you.

**Comment by kkofler** [comment]
Both the double quotes and the backslashes must be escaped with a backslash each.

**Comment by d3signr** [comment]
> @d3signr
> 
> Don't get me wrong but this is not the place to teach you how to use sed or regexp.
> 
> man sed should be a starting point for you.

Understood, thank you

**Comment by d3signr** [comment]
> Both the double quotes and the backslashes must be escaped with a backslash each.

Thank you
