### ISSUE TITLE
Current master code won't install grub as bootloader

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#1104]
**Describe the bug**
current master doesn't install any bootloader

**To Reproduce**
- try to use the latest master code (or current **calamares-git** package in Manjaro (testing/unstable))
- **bootloader** module won't install **grub** to your target installation.

**Expected behavior**
Install **grub** as bootloader

**Comment by philmmanjaro** [comment]
Last tested with fdb4311a70ac7a63e8ba55d00b67033e78ce8cac, even with reverting that merge commit. In both cases no **bootloader** got installed.

**Comment by abucodonosor** [comment]
@philmmanjaro 

can you post an debug log please ?

I cannot reproduce that here.

Here it installs just fine.

```
21:17:27 [6]: Job description from __doc__ "bootloader" = "Starts procedure and passes 'fw_type' to other routine." 
21:17:27 [6]: [PYTHON JOB]:  "Bootloader: grub (bios)" 
21:17:27 [6]: Running "chroot" ("/tmp/calamares-root-_5porsmd", "grub-install", "--target=i386-pc", "--recheck", "--force", "/dev/sda") 
21:17:28 [6]: Finished. Exit code: 0 
21:17:28 [6]: Target cmd: ("grub-install", "--target=i386-pc", "--recheck", "--force", "/dev/sda") 
21:17:28 [6]: Target output:
Installing for i386-pc platform.
Installation finished. No error reported.

```

**Comment by philmmanjaro** [comment]
I tried with EFI, didn't tried BIOS yet. The log is missing the whole step. You may use the current Development ISO from us and install **calamares-git** on it. Then try to install it. It won't work.

**Comment by abucodonosor** [comment]
@philmmanjaro 

let me try with EFI ..

( please point me to your Developent iso )

**Comment by philmmanjaro** [comment]
[KDE](https://osdn.net/projects/manjaro/storage/kde/18.0.4-rc/), [XFCE](https://osdn.net/projects/manjaro/storage/xfce/18.0.4-rc/), [Gnome](https://osdn.net/projects/manjaro/storage/gnome/18.0.4-rc/). I used **3.2.4** on them, which still works. Simply install **calamares-git** when trying the second run.

**Comment by abucodonosor** [comment]
@philmmanjaro 

thx for the links but on EFI I can reproduce on my own iso.

we see now:

```
21:53:39 [6]: FillGlobalStorageJob writing empty bootLoader value 

```
That is an bug too also .. Erase cannot have such empty value on EFI,
in that case we need stop the installtion.

Can you confirm an BIOS installaion is working for you too ?

**Comment by abucodonosor** [comment]
@philmmanjaro 

I figured that , cuased by commit bd27dda474

it seems @adriaandegroot  forgot about detectFirmwareType().

I not sure why this need be exactly there ... I would do something like this:

https://crazy.dev.frugalware.org/bug1104.patch

**Comment by philmmanjaro** [comment]
@abucodonosor : your patch works on my end.

```
15:48:40 [6]: Starting job "bootloader" 
15:48:40 [6]: Job file "/usr/lib/calamares/modules/bootloader/main.py" 
15:48:40 [6]: Job description from __doc__ "bootloader" = "Starts procedure and passes 'fw_type' to other routine." 
15:48:40 [6]: [PYTHON JOB]:  "Bootloader: grub (efi)" 
15:48:40 [6]: Running "chroot" ("/tmp/calamares-root-eydxecsb", "grub-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=Manjaro", "--force") 
15:49:47 [6]: Finished. Exit code: 0 
15:49:47 [6]: Target cmd: ("grub-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=Manjaro", "--force") 
15:49:47 [6]: Target output:
Installing for x86_64-efi platform.
Installation finished. No error reported.
15:49:47 [6]: [PYTHON JOB]:  "UEFI Fallback: True" 
15:49:47 [6]: [PYTHON JOB]:  "  .. installing 'bootx64.efi' fallback firmware" 
15:49:47 [6]: Running "chroot" ("/tmp/calamares-root-eydxecsb", "grub-mkconfig", "-o", "/boot/grub/grub.cfg") 
15:49:58 [6]: Finished. Exit code: 0 
15:49:58 [6]: Target cmd: ("grub-mkconfig", "-o", "/boot/grub/grub.cfg") 
15:49:58 [6]: Target output:
Generating grub configuration file ...
Found theme: /usr/share/grub/themes/manjaro/theme.txt
Found linux image: /boot/vmlinuz-5.0-x86_64
Found initrd image: /boot/intel-ucode.img /boot/amd-ucode.img /boot/initramfs-5.0-x86_64.img
Found initrd fallback image: /boot/initramfs-5.0-x86_64-fallback.img
Found memtest86+ image: /boot/memtest86+/memtest.bin
done
```

**Comment by adriaandegroot** [comment]
This got lost in 3.2.4 even.
