### ISSUE TITLE
Does not detect the drive

### ISSUE THREAD

**Issue by Alficiro** [calamares/calamares#1105]
**Describe the bug**
The installer does not detect the drive. Tested with Lubuntu 18.10 and KDE Neon.
64 bit machine.

BIOS details:
CPU: Intel Core i3 CPU
IDE0 Model Name: ST500LM030-2E717D

BIOS Version: V1.16
VGA BIOS Version: Intel V2050

Product Name: Aspire 4738
Manufacturer: Acer

disk setup:

NTFS - System, Active
NTFS - Boot, Page File, Crash Dump
NTFS - Recovery Partition
ext4 - Ubuntu 18.10

**Screenshots and Logs**
[session.log](https://github.com/calamares/calamares/files/2922962/session.log)
![not detecting the drive](https://user-images.githubusercontent.com/38340848/53693713-e4a7ab00-3dd6-11e9-869a-e4b991a81934.png)
![detects removables though](https://user-images.githubusercontent.com/38340848/53693721-f426f400-3dd6-11e9-804b-d4ab2b1d0c80.png)
![windows disk management](https://user-images.githubusercontent.com/38340848/53693743-1c165780-3dd7-11e9-8fec-4958937ff0db.jpg)
![gparted](https://user-images.githubusercontent.com/38340848/53693728-04d76a00-3dd7-11e9-96b9-0b75e86cb1af.png)
![gnome disks](https://user-images.githubusercontent.com/38340848/53693729-07d25a80-3dd7-11e9-830b-b56f0a46421e.png)
![ubiquity works](https://user-images.githubusercontent.com/38340848/53693735-0e60d200-3dd7-11e9-98d9-57bab53b2644.png)

**Additional context**
* I successfully installed Lubuntu 18.10 before I installed Windows 10 over it, so it's probably not a hardware issue.

**Comment by abucodonosor** [comment]
From the log there are some problems but lets look the 2 are relevant to this:

First one and this is the one removing the drivers from UI:

```
2019-03-03 - 16:41:12 [6]: Removing unsuitable devices: 2 candidates. 
2019-03-03 - 16:41:12 [6]:   .. Removing device with iso9660 filesystem (probably a CD) on it "/dev/sda" 
2019-03-03 - 16:41:12 [6]:   .. Removing device with iso9660 filesystem (probably a CD) on it "/dev/sdb" 

```
Now if you look yor fifth picture all in there but boot seems to be CDROM/NTFS .. 
Calamares won't use any devices with iso9660 filesystem on it.

Please post result of this commands:

```
sudo blkid -s TYPE -o value /dev/sda
sudo blkid -s TYPE -o value /dev/sdb

```

Second one:

```
...
2019-03-03 - 16:41:16 [2]: WARNING: Could not read fstab from mounted fs
...

```
Seems like something or you monted some of the partitions. This cannot work.

It looks like partitioning mistake not like HW issue.

**Comment by Alficiro** [comment]
I tried to install Kubuntu using the earliest LTS, it worked but it seems to only recognize LTS versions even when I set software sources to check for stable.
In case that messes something up, have another log; made sure not to mount anything:
[session.log](https://github.com/calamares/calamares/files/2924427/session.log)

And yeah, `sudo blkid -s TYPE -o value /dev/sda` and `sdb` both return iso9660.

Also, have this error on trying to mount sda4, hope it might be helpful. (the top is Kubuntu, and the bottom is Windows)
![mount error](https://user-images.githubusercontent.com/38340848/53713017-d364aa00-3e7b-11e9-94c7-38be1e3afa3f.png)

**Comment by abucodonosor** [comment]
There is nothing can be done about .. you need fix your disks.

**Comment by Alficiro** [comment]
You mean all I can do is create a new partition table and reinstall everything?
Well, thanks anyway.

**Comment by abucodonosor** [comment]
@Alficiro 

if you want fix issues you are facing , sooner or later you have to do that , yes

like you see everything thinks your HDDs are CDROMs and 
therefore you'll hit all sort issues.

OFC I can give you an patch to bypass that in calamares since you know
these are not CDROMs but that won't fix all your other problems.

**Comment by Alficiro** [comment]
Oh, thanks. How would that work, though?

**Comment by adriaandegroot** [comment]
With current Calamares (master) you could compile it with some be-very-dangerous flags and then run it. You need to configure it with DEBUG_PARTITION_UNSAFE on (shoot-yourself-in-the-foot) and DEBUG_PARTITION_LAME off (the safety-catch). Then you can use it to destroy any partition or so.

More effective might be to find out **why** your hard disks seem to be CD-ROMs. Did you write an ISO image to the hard-disk before installing things to it?

I'm going to close this as "problem exists on the target HDD".

**Comment by dimasirfandanu** [comment]
I use Ventoy to install os to my pc, but I can't install to the same partitions where Ventoy there. Because calamares detect it as CD installer media.

**Comment by adriaandegroot** [comment]
@dimasirfandanu See #1855 and related issues. I'm open to specific suggestions to detect "this looks like a CDROM but really it isn't and it also isn't the USB stick you're installing from" in PRs.

**Comment by Flashwalker** [comment]
Calamares does not see the partitions if you use Ventoy to boot the live CD and put the ISO on the same hard disk you want to install the OS on.

Summary: the ISO is on the first partition, and the empty formatted linux partitions in the extended partition next to it on the same disk.

Result: Calamares fails to find any installable partittons -1.
KDE Partiotion Manager and GNOME Disks running on the same Live CD see partitions fine.

Tested: Nitrux, Feren, KDE neon
--


[KDE neon](https://distrowatch.com/kdeneon)
