### ISSUE TITLE
Welcome Page does not update internet status

### ISSUE THREAD

**Issue by cjlcarvalho** [calamares/calamares#1106]
**Describe the bug**

If you start Calamares and you don't have internet connection, the application will tell you that the system is not connected to the internet. Then, if you get a internet connection without closing Calamares, it will not update the Welcome Page.

**To Reproduce**

1. Disconnect internet
2. Start Calamares
3. Keep Calamares opened in the Welcome Page
4. Connect internet
5. Welcome Page will not update

**Expected behavior**

Welcome Page should update the message of internet connection if the user gets connected.

**Screenshots**

Internet is not connected and the message is showed:

![calamares_connection](https://user-images.githubusercontent.com/16494866/53705243-3ef93980-3de0-11e9-9a67-30bff14cc467.png)

After that, an internet connection is established and the message does not disappear:

![cala](https://user-images.githubusercontent.com/16494866/53705295-9bf4ef80-3de0-11e9-9fd7-0d66ffd6bb15.png)

**Comment by abucodonosor** [comment]
I don't think that should be done.

Either you have a working Internet connection when you start the installtion or you don't have one.

Is not that simple than just saying to you have now Internet.
Based on having or not having Internet modules functionality 
or modules altogether gets disabled or enabled on startup.

While you give that example on Welcome page how about someone pluggs the Internet cable
in the middle of the installation in ?

Basically what you are asking for is to store the state on the internet on startup when is a check item ,
ping internetCheckUrl all 2 secs and compare result ( is a Distribution decision right ? ) ,
if we go online at some point of the installtion ( no matter when ) , fire big red warning window asking 
the user to continue without internet or reset the installtion to startup..
 
I personally don't think that should be done not even with a configuration option , 
becase we already got one .. check or required.

**Comment by kkofler** [comment]
It is possible to listen to a state change event from NM, which would avoid the polling. But of course that does not handle the `internetCheckUrl`. It is possible to do a URL-based connectivity check within NM and some distros (e.g., Fedora) have that set up (and in that case, listening to the state changes from NM should indeed be enough), but usually NM will only react to changes at the transport level and ignore the actual reachability of websites.

**Comment by kkofler** [comment]
That said, the connectivity check at NM level means NM requests a web page from Fedora infrastructure each time (the NM plugin does a request and not just a ping because it also checks the contents to detect captive portals, something Calamares does not do yet), which can be a privacy concern.

**Comment by adriaandegroot** [comment]
The requirements are checked at startup. While network status can easily be changed (and indeed, there's a feature request for doing network configuration from *inside* Calamares) the other's can't easily be changed without re-starting Calamares.

So I'd file this under "very low priority, but could conceivably be one".

**Comment by adriaandegroot** [comment]
Fixed in 3.3.0
