### ISSUE TITLE
welcome module language list: display endonym and ISO name, put American English in proper sort location

### ISSUE THREAD

**Issue by wxl** [calamares/calamares#1107]
Right now, we're sorting against the ISO language name (e.g. Russian) but displaying the endonym aka native language name (e.g. русский), but we're also doing the strange thing of making American English the default, which puts it at the top of the list:

![language list long](https://i.imgur.com/0mQ53GD.png)

Two things would improve this:
 1. I propose that we keep the default within the sorting (so American English would appear above British English).
 1. Within an IRC discussion, @adriaandegroot also suggested adding the ISO language names with the endonym so we have something like "русский (Russian)" or "Russian (русский)" (I prefer the latter since this is what we're sorting on).

Regarding that former item, the suggestions made were:
 * dropping the special case in `LocaleItem::operator <`
 * just selecting US English at its correct spot in the drop-down

Regarding the latter, there was concern expressed about getting `QComboBox` to display like that. @kkofler suggested:
 * a custom item delegate `QComboBox::setItemDelegate`
 * store the ISO language name in the `userData` of the item and have the item delegate paint it

There's a [downstream bug](https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/1801498) concerning the apparent "randomness" of the list. Upon further inspection, that's clearly not the case and so I closed it, but these two changes would make a significant impact on removing any concern at all.

**Comment by kkofler** [comment]
The idea of the custom item delegate is to not just display a plain text `Russian (русский)`, but a formatted rendering like the one in Anaconda (see the first screenshot of [https://www.zdnet.com/article/hands-on-a-screenshot-walk-though-fedoras-anaconda/](https://www.zdnet.com/article/hands-on-a-screenshot-walk-though-fedoras-anaconda/)).
