### ISSUE TITLE
Tip of master causes installed system to boot to memtest86+

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#1108]
I have a CI system set up where Calamares is one of many packages pulled from the tip of upstream master and used with our current packaging to produce CI builds. The only thing that changed here is the Calamares source, the packaging and all of the rdeps have stayed the same. This is on a Lubuntu 19.04 daily.

When installing the Calamares package from my CI, after installation, the system boots into memtest86+, not the installed system. Using the package from the repositories, 3.2.4, produces the expected result. It was just a standard install, with "Erase disk" selected, no encryption and no special partitioning.

My Calamares configuration is available [here](https://phab.lubuntu.me/source/calamares-settings-ubuntu/).

This is *not* a downstream issue, it's simply an issue with the upstream source. *Nothing* else changed. Please don't close this out of spite.

**Comment by abucodonosor** [comment]
See https://github.com/calamares/calamares/issues/1104

**Comment by adriaandegroot** [comment]
Yeah, that's just a dup of #1104 because I broke stuff.

**Comment by adriaandegroot** [comment]
.. that one was just closed with a commit to master, @tsimonq2 please check.

**Comment by tsimonq2** [comment]
I'll check [as soon as my CI is back up](https://lubuntu.me/infrastructure-data-loss/).
