### ISSUE TITLE
Add an option to disable Cancel/Done

### ISSUE THREAD

**Issue by feren** [calamares/calamares#1109]
**Is your feature request related to a problem? Please describe.**
I've been working on integrating Calamares into a custom OEM Setup environment with either Cinnamon or Plasma providing some options such as WiFi and Battery status and such (the type of thing you'd see in Ubuntu's Ubiquity-only Mode, for instance), of which I'll upload my work on the matter soon to the feren-OS GitHub page...
But that's besides the point here - there's an annoying detail in the form of the Cancel button (or 'Done' if you disable the 'All Done' page and get to the installation phase), and the fact it lets you exit Calamares in places you might not want it to be closable, such as an OEM Setup screen. Due to this, for certain OEM Setup Screen implementations you end up having to put Calamares on a launch loop until the process is properly done to work around the fact it can be closed before the system is configured properly for the new user.

**Describe the solution you'd like**
I'd like to see the option in Calamares's global configuration to be able to at least disable the 'Cancel' button during the installation phase, if not throughout all of the installer, meaning that it can be disabled for certain situations and remain enabled in other situations. Something like 'allow-cancel', 'allow-done' or something similar would be great. I apologise if it's already an option in Calamares, but I tried looking through the documentation and could not find such an option at this current point in time.

**Describe alternatives you've considered**
The best alternative for me that has come into mind (which I'm using for now) is to launch Calamares in that environment via a BASH Script or similar that infinitely loops until the Calamares installer has finished properly (of course I also added a step into Calamares's installer at the end to make it so the BASH Script can identify when this is so). It works fine, but it's not the most elegant of solutions.

**Additional context**
Pretty much imagine the 'Cancel' button but insensitive.

**Comment by feren** [comment]
Oh, looks like it does exist now, nevermind and cheers for whoever suggested that before me.

**Comment by adriaandegroot** [comment]
You can thank @aferraris for that feature. In general, Calamares really likes to slurp things upstream. There's a number of open issues for OEM support (both pre-deploy and post-deploy OEM features), and at **some** point I need to get working on them, but there's always other stuff as well. Feel free to contact me out-of-band (e.g. email) if there's specific features you're interested in.
