### ISSUE TITLE
Partition 2 does not start on physical sector boundary.

### ISSUE THREAD

**Issue by reddeadbed** [calamares/calamares#1110]
> Disk /dev/sda: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
> Disk model: WDC WD10EZEX-75W
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 4096 bytes
> I/O size (minimum/optimal): 4096 bytes / 4096 bytes
> Disklabel type: dos
> Disk identifier: 0xe437535d
> 
> Device     Boot      Start        End    Sectors   Size Id Type
> /dev/sda1             2048 1917390096 1917388049 914.3G 83 Linux
> /dev/sda2       1917390097 1953520064   36129968  17.2G 82 Linux swap / Solaris
> 
> Partition 2 does not start on physical sector boundary.
> 

Used automatic partitioning with swap creation enabled.
Manjaro 18.0.3

Thought this was fixed already...
https://github.com/calamares/calamares/issues/1008

Another user complaining about it:
https://forum.manjaro.org/t/swap-partition-does-not-start-on-physical-sector-boundary/67296/7

odd.

**Comment by adriaandegroot** [comment]
It (`/dev/sda2`) starts where it has to start, namely the sector after `/dev/sda1`), but there's an off-by-one either in the end-calculation or the size-calculation: `/dev/sda1` is now an odd number of sectors, which is weird (actually I think it should be a multiple of 8 -- which it is, and then off-by-one). So, yeah, things need to shift up one sector.

**Comment by abucodonosor** [comment]
@adriaandegroot 

yes is a off-by-one in Manjaro but here on master I cannot reproduce that no matter what I am trying.

**Comment by adriaandegroot** [comment]
In the downstream bug report, the swap partition (partition 3) starts on sector 1935065126 (512 bytes) although the optimal alignment is on an 8-sector boundary (4096 bytes) .. so it is mis-aligned. In **this** report, the second partition starts on an odd 512-byte sector but optimal alignment would still be 4096. I probably don't see this locally because my drives report 512/512.

**Comment by adriaandegroot** [comment]
I'm going to close as already-fixed and can't-reproduce.
