### ISSUE TITLE
encoding problem on the language list (Welcome Module)

### ISSUE THREAD

**Issue by memoryleakx** [calamares/calamares#1113]
**Describe the bug**
The **language list** on the **Welcome Module** shows strange encoded strings

![](https://i.ibb.co/1Zs91NP/encoding-Bug-Calamares.jpg "Encoding Problem with Language List (Welcome Module)")

**To Reproduce**
System:  ArchLinux 
Desktop Environment: Budgie Desktop
Locales: en_US.UTF-8 UTF-8
Calamares 3.2.4

**Comment by memoryleakx** [comment]
I have found a solution.
After installing the Font **ttf-droid** the language list looks fine again :)

**Comment by adriaandegroot** [comment]
That's SwagArch, isn't it?

Good to know it's (only) a font issue, but that does mean we should document the font-requirements (all the interesting scripts are missing) for the welcome list. There's also #1107, which would have displayed something readable for you even without the scripts themselves.
