### ISSUE TITLE
Add option to disable cancel ONLY when the installation is in progress

### ISSUE THREAD

**Issue by feren** [calamares/calamares#1122]
**Is your feature request related to a problem? Please describe.**
It's kind of odd that Calamares lets you Cancel out of the installation procedure while the OS is installing, especially given that the damage of having begun the installation procedure is already done by the time you try and cancel out of installing the OS at that moment as a person who isn't aware that cancelling it won't undo the changes that have already happened.

**Describe the solution you'd like**
The option to disable cancel ONLY when in the 'Install' phase would be more than appreciated. This is not to be confused with the Pull Request for disabling cancel globally in the installer, however.

**Describe alternatives you've considered**
I've considered making use of the global cancel disabler, but to be honest globally disabling cancel for the purpose of preventing freak accidents from prematurely finishing the installation phase by cancelling it part-way through the phase is a little overkill.

**Additional context**
Pretty much just how Ubiquity and such do it where the effects of disabling cancel only hit Calamares once the Installation process has begun for real and then get enabled again at the end for the post-Install screens (usually just the 'finish' module)...

**Comment by abucodonosor** [comment]
maybe with some option .. 

I don't see why force that on all users while some peoples may 
not know what they are doing or what is means to cancel an installation.

Maybe one changes his mind , want to install something different and just cancel,
or realized he forgot something or what do it different .. So perfectly fine to 'cancel'
in such a cases ..

While I get your point , I don't think we should force everyone by defalt to wait the installation finished to 'cancel' , for whatever reason the user may have doing that.

Thx

**Comment by feren** [comment]
It'd be nice to have it as an option to do so, ala how the Cancel Button Global Disabling now works to be honest.

**Comment by kkofler** [comment]
One use case where it makes sense to cancel a running installation is if you realize that you are about to format (or already formatting) the wrong partition. The sooner you cancel, the higher your chances are to recover at least **some** of the data. If you have to wait until the end of the installation, it will be all gone for sure!

**Comment by abucodonosor** [comment]
@feren 

sure but there is still reason to cancel, like pointed out from @kkofler.

Maybe something like this will do it:

https://crazy.dev.frugalware.org/maybe-something-like-this.patch

**Comment by adriaandegroot** [comment]
That patch looks pretty good, actually; I'd call it something else, like *no-cancel-during-exec*, and it needs double-checking that when you come **out** of exec, the cancel is restored (put an extra view step after the first exec block in sequence to try it, eg. a dummypythonqt or some such). But that'd do the job for @feren

**Comment by abucodonosor** [comment]
@adriaandegroot 

If you like to implement that change name as you wish.

But while at it probably disable-cancel should be then global-disable-cancel or similar ?

**Comment by feren** [comment]
> But while at it probably disable-cancel should be then global-disable-cancel or similar ?

`global-no-cancel`, `no-cancel`? Eh, TBH that doesn't matter too much does it given it already has a relatively alright name for its value that names after its job of affecting Calamares the way it does and also the fact it'd be Documented on what the option(s) do/does anyway?

**Comment by adriaandegroot** [comment]
@fener Can you take the patch from @abucodonosor and turn it into a PR? Needs testing, as described.

**Comment by adriaandegroot** [comment]
This has been merged. Thanks @feren
