### ISSUE TITLE
License module and contextualprocess together don't work correctly with global variables

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#1124]
I'm writing a contextualprocess module that looks like this:
```
---
dontChroot: true
timeout: 120
licenseAgree:
    "true": "-touch /tmp/it-worked"
    "*": "-touch /tmp/it-didnt-work"
```
Even when replacing `"*"` with `""`, I'm getting the following debug warning when I **don't** check the license box:
```
WARNING: ContextualProcess checks for unknown variable "licenseAgree"
```
When the license acceptance box is checked, that script works fine.

**Comment by abucodonosor** [comment]
Well licenseAgree is not a 'global var' like you think it is.
It first becomes 'global' after you agree ( click ) on something.

So if you run your scripts before license modules you won't get any.

**Comment by adriaandegroot** [comment]
The code there is buggy as well: toggling the (accept) checkbox inserts a global variable, but if you don't touch the button then no global variable is ever created for it. It should, on entry, always create that variable. And there should be documentation that that global variable exists.

**Comment by tsimonq2** [comment]
> It should, on entry, always create that variable. And there should be documentation that that global variable exists.

You hit the nail on the head for what I was suggesting. 😄
