### ISSUE TITLE
License module doesn't understand not being required

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#1125]
I have a license.conf file which looks like this:

![image](https://user-images.githubusercontent.com/3689821/56171642-a8599400-5fab-11e9-8628-f3024d36cc19.png)

This is the default state:
![image](https://user-images.githubusercontent.com/3689821/56171691-d2ab5180-5fab-11e9-8a8e-6b64b9950069.png)

Then I check it:
![image](https://user-images.githubusercontent.com/3689821/56171713-e060d700-5fab-11e9-8c9e-9030a02dc675.png)

But then I uncheck it again:
![image](https://user-images.githubusercontent.com/3689821/56171721-e9ea3f00-5fab-11e9-931b-9bad46e44453.png)

Now the Next button is hidden. Nothing is set to required, so nothing should be blocking it.

**Comment by abucodonosor** [comment]
@adriaandegroot 

This module seems be buggy or has some logic to work I don't really get..

Not sure why we always set required to false and not really check the real value ?

I mean LicenseViewStep.cpp set it false and LicensePage.cpp loops over the entries
and does this:

```
......
    bool required = false;
    for ( const LicenseEntry& entry : entriesList )
    {
        if ( entry.required )
        {
            required = true;
            break;
        }
    }

    m_isNextEnabled = !required;
   .....
```

What I am missing ?

**Comment by kkofler** [comment]
This says, if at least one entry is required, then required = true and m_isNextEnabled = false, but if there is no required entry, required = false and m_isNextEnabled = true.

**Comment by adriaandegroot** [comment]
There's a branch issue-1052 (related to #1052, of course) for work on the license module. It's quite likely the module is full of issues; I think the module is rarely used. In that code snippet, the variable should be named *hasAtLeastOneRequiredAndNotAcceptedLicense* (I'm not kidding; better variable names, everywhere, plz.)

**Comment by tsimonq2** [comment]
> I think the module is rarely used

I would like to use it by default in 19.10. Many bug reports incoming, then. :wink:
