### ISSUE TITLE
storage checks are inconsistent with verbiage

### ISSUE THREAD

**Issue by wxl** [calamares/calamares#1129]
**Describe the bug**
Checks for RAM and storage use strict inequalities (`dev_size > required_space`), but the report to the user says "at least," which implies something less strict (`dev_size >= required_space`). Another way to say "at least" is "the minimum amount required" or as [one dictionary puts it](https://www.thefreedictionary.com/at+least), "not less than," which means both greater than and equal to.

There is an additional error in that we presume base 2 units (e.g. `GiBtoBytes()` converts with 1024 instead of 1000) but then we use the base 10 abbreviations (GB, not GiB as above) in the code (e.g. `m_requiredStorageGB`), in our response to the user (e.g. `%1 GB is required`), and in the documentation (e.g. `Amount of available disk, in GB`).

**To Reproduce**
 1. Set `requiredStorage: 8`.
 1. Create a virtual machine with a 8GiB disk.
 1. Run Calamares.

**Expected behavior**
Installation proceeds normally.

**Actual behavior**
Installation fails, with the confusing message that the amount of disk you created is required.

**Additional context**
Since these values enforce "minimum system requirements" essentially, I think it is sensible to use the "at least" verbiage, but that would require using a greater than or equal to inequality.

Also, base 2 is the only thing that makes any physical sense. Our computers are not decimal.

**Comment by kkofler** [comment]
And KDE recommends using binary units and the ISO `KiB`/`MiB`/`GiB`/`TiB` notation.

Using `kB`/`KB`, `MB`, `GB`, `TB` for binary units is obsolete and confusing and not recommended by any desktop environment. GNOME recommends using decimal units though, for some reason. But Calamares should really follow the KDE recommendation here, it makes more sense.

**Comment by wxl** [comment]
Yeah, there's also the question of standards. It's hard to argue with something as overarching as ISO standards. There have been lawsuits over this. It's not something to take lightly. I think the only reason there has been a mass conversion is cause of laziness, which one can see in the discussions that led to the kernel's adoption of the binary prefixes. Still, the kernel chose [unambiguity and following standards](https://lkml.org/lkml/2001/12/20/198) above all other arguments. I think this is what we should do, too. At the very least, being unambiguous.

**Comment by abucodonosor** [comment]
@wxl 

well the units are fine and so the calculation is. Just the text uses GB
and need probably corrected to use GiB.

We do:

qint64 requiredStorageB = CalamaresUtils::GiBtoBytes(m_requiredStorageGB);


you are right about > check , that should really be >=

**Comment by wxl** [comment]
@abucodonosor yeah I wasn't trying to suggest that the code or logic was wrong. In fact, I had mentioned that `GiBtoBytes()` ultimately uses 1024.

That said, this is a relatively minor fix. Hell, *I* might even get around to implementing it :stuck_out_tongue_winking_eye:

**Comment by adriaandegroot** [comment]
@wxl I'm going to assign this to you :stuck_out_tongue_winking_eye: PR is expected inside of two weeks.

**Comment by wxl** [comment]
Uh oh the pressure is on 😳

**Comment by adriaandegroot** [comment]
There's a branch for this, but it looks like there's more corner cases than you might expect to make it all consistent.
