### ISSUE TITLE
oemid not writing file if nothing is entered

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1136]
**To Reproduce**
1. have no oemid.conf
2. use oemid in settings.conf though
3. on the oemid page enter nothing
4. resulting system will not have the oem-id file written with a newline (as per oemid docs `If the identifier is empty, only a newline is written`)

**Expected behavior**
An empty file should be written when no oem id is provided.

**Comment by adriaandegroot** [comment]
Can't reproduce. Excerpts from the session log:

```
16:36:22 [6]: No config file found in 
     "/home/adridg/src/calamares/build/src/modules/oemid/oemid.conf" 
     "/etc/calamares/modules/oemid.conf" 
     "/usr/local/share/calamares/modules/oemid.conf" 
16:36:22 [6]: ViewModule "oemid@oemid" loading complete. 
16:36:26 [6]: Starting job "OEM Batch Identifier" 
16:36:26 [6]: Setting OEM Batch ID to "" 
```

After that, I have a new file `/var/log/installer/oem-id` which is 1 byte (namely, the newline).

**Comment by apachelogger** [comment]
Perhaps my test was flawed, I'll give it another go tomorrow and report back.

**Comment by apachelogger** [comment]
My bad.
