### ISSUE TITLE
Boot loader location is empty after switching erase disk options

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1141]
Using calamares 3.2.7 we have noticed a change in behavior against 3.2.4.

When you are in the partitions screen we can choose no swap, swap no hibernate and swap hibernate.

When you switch between these options the bottom dropdown gets emptied.

Picture at boot up - all is good - boot-loader is ok - installation will be ok

![swap0](https://user-images.githubusercontent.com/36679406/57272389-d0f91900-7093-11e9-8421-5b092566a9f6.png)

Picture after changing the options no swap, swap no hibernate and swap hibernate - empty boot-loader at bottom - no successful installation - black screen - so I have been told
![swap1](https://user-images.githubusercontent.com/36679406/57272422-f128d800-7093-11e9-9c17-c7b20379e425.png)

The options are available BUT if you did not notice you have a broken system.
![swap2](https://user-images.githubusercontent.com/36679406/57272459-19183b80-7094-11e9-925c-1b175d79d590.png)

Can you make sure that the first option will stay when you switch between choices.

A video to make it clear - password : calamares
https://vimeo.com/334584142

**Comment by adriaandegroot** [comment]
Note for testing: Doesn't show up on EFI (because *boot loader location* is a BIOS-only setting).

**Comment by arcolinuxz** [comment]
Tested it on VirtualBox with bios setting

**Comment by kkofler** [comment]
This still happens with 3.2.8.

**Comment by robin0800** [comment]
esp flag is missing in boot/efi and if format is chosen the boot flag, which is present, is overwritten as msfdata so no boot at all and as already stated the esp flag is missing.

**Comment by arcolinuxz** [comment]
Our users have been warned here : https://arcolinux.com/calamares-tip-make-sure-the-bootloader-is-filled-in-and-avoid-frustrations/

**Comment by Elrondo46** [comment]
There is a lot of bug with the last released version, random crash with erase and swap hiber or not config.
If you make custom partitions and want a home, the install crash or successful but no UUID in fstab for home partition

**Comment by arcolinuxz** [comment]
I just discovered that If you encrypt your harddisk and fill in the password,  you also loose the bootloader info even if you did not touch the noswap option above.

**Comment by adriaandegroot** [comment]
This was supposed to be fixed in #1098, but I guess not.

**Comment by adriaandegroot** [comment]
Well, #1098 was on the **manual partitioning** page, and this one is on a different page :face_with_head_bandage:

**Comment by adriaandegroot** [comment]
Marked this "fixed" because the situation has improved: the box doesn't end up empty now, but it remains "weird" and can change values unexpectedly. I've come to the conclusion that the partitioning module needs a serious rewrite and that that's the only thing for 3.2.10. This will probably drop LVM support again (but see all the LVM bugs filed, this might not be all that bad).

**Comment by arcolinuxz** [comment]
confirmed 3.2.9 keeps the box filled
thanks
super work
