### ISSUE TITLE
Calamares on debian 9 and 10 fails with "cannot find a device for /boot/grub (is /dev mounted?)" error

### ISSUE THREAD

**Issue by onions-knight** [calamares/calamares#1143]
Not sure whether this is a bug or something I am doing wrong. 

I am trying to use Calamares to install from a custom debian ISO on a virtual MBR hard drive. I installed calamares from debian repos and burnt the installer ISO, then booting it in KVM for testing purposes. I use a single partition (no separate /boot partition).

All goes well until I reach the bootloader stage, when it always fails with

```
Boost.Python error in job "bootloader".

Command 'grub-install --target=i386-pc --recheck --force /dev/vda' returned non-zero exit status 1.
Installing for i386-pc platform. grub-install: error: cannot find a device for /boot/grub (is /dev mounted?).

Traceback:
File "/usr/lib/x86_64-linux-gnu/calamares/modules/bootloader/main.py", line 444, in run
    prepare_bootloader(fw_type)

  File "/usr/lib/x86_64-linux-gnu/calamares/modules/bootloader/main.py", line 411, in prepare_bootloader
    install_grub(efi_directory, fw_type)

  File "/usr/lib/x86_64-linux-gnu/calamares/modules/bootloader/main.py", line 328, in install_grub
    boot_loader["installPath"]])

  File "<string>", line 5, in <module>
```
Am I missing something? Is there additional configuration to do? I couldn't find anything in the Wiki.

**Comment by adriaandegroot** [comment]
Closing as "configuration problem" (and I hope you get the other GRUB bits figured out: do document them or add another issue.
