### ISSUE TITLE
disable-cancel-during-exec does not affect Close Button trigger on exec

### ISSUE THREAD

**Issue by feren** [calamares/calamares#1146]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
A clear and concise description of what the bug is. Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.
Basically, I'm trying Calamares 3.2.7 with 'no-cancel-during-exec' turned on, and I just noticed that while 'Cancel' is disabled the window can still be closed via the close button, triggering a 'Cancel Installation?' prompt dialog.

**To Reproduce**
1. Enable 'no-cancel-during-exec' in settings.conf
2. Start a normal OS Installation
3. Click the Titlebar's Close Button
4. You'll have the ability to cancel installation

**Expected behavior**
Either an error dialog would appear telling you that you need to wait until installation has completed if this is done, or better yet (if possible) the 'closeable' window setting will be disabled during 'exec' from the titlebar.

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Calamares has an installation log (usually `~/.cache/calamares/session.log`), please check it for confidential information and attach it if possible.
![image](https://user-images.githubusercontent.com/11057934/57550863-74318300-735f-11e9-9159-bfc3154761c6.png)

**Comment by feren** [comment]
Whoops, screenshot at the wrong time... here's a better screencap
![image](https://user-images.githubusercontent.com/11057934/57550902-91fee800-735f-11e9-8adf-f8a5d5fd9e7e.png)

**Comment by abucodonosor** [comment]
@feren @adriaandegroot 

disable-cancel has the same problem

**Comment by adriaandegroot** [comment]
I tried to **also** toggle the presence of the window-close button in the WM decorations when disable-cancel-during-exec is active, but that makes the Calamares window vanish; adding a show() to it does bring the window back, but leads to uncomfortable flickering and the window being re-mapped by the WM, so it seems to move on the desktop.

For now:
 - disable-cancel will switch off the window-close decoration entirely (it already did)
 - all the disable-cancel variants will ignore close events when they are active.
