### ISSUE TITLE
ESP flag missing from calamares, and Calamares creates a empty /etc/fstab

### ISSUE THREAD

**Issue by kronikpillow** [calamares/calamares#1147]
**Describe the bug**
Hardware:
			Intel Core i5 3350P @ 3.10GHz Ivy Bridge 22nm Technology
			8.00GB Dual-Channel DDR3 @ 1333MHz
			MSI B75MA-E33 (MS-7808) (SOCKET 0)
			S22B150 (1920x1080@60Hz)
			1023MB NVIDIA GeForce GTX 650 Ti (MSI)
			931GB TOSHIBA DT01ACA100 (SATA )
			931GB Apacer External SCSI Disk Device (USB (SATA)
			14GB Kingston DataTraveler 3.0 USB Device (USB)
			ATAPI iHAS120 X
			M-Audio Delta 66

Distribution: ArcoLinux I3 19.06.1 (BETA) (Arco beta tester here)

Booting on EFI/GPT
I have deleted all my partitions and created a new GPT partition table
If i create the EFI partition from Calamares, I can not set a ESP,BOOT flag on the EFI partition at all, the ESP flag is missing 
[https://i.imgur.com/IYqyWHt.png](https://i.imgur.com/IYqyWHt.png) 
[https://i.imgur.com/LCqmvPp.png](https://i.imgur.com/LCqmvPp.png)

If i try to install with just BOOT flag Calamares doesn't allow me to install [https://i.imgur.com/qBJ5Fx3.png](https://i.imgur.com/qBJ5Fx3.png)

If I create EFI partition from gparted or cfdisk or fdisk and set the ESP flag on the partition, and create / and /home and swap from Calamares, grub will install, but / /home and /swap are not mounted in /etc/fstab 
[https://i.imgur.com/WPl3bOih.jpg](https://i.imgur.com/WPl3bOih.jpg) 
[https://i.imgur.com/G8qOZvZ.jpg](https://i.imgur.com/G8qOZvZ.jpg)

So, in general, If i create EFI partition from Calamares, Calamares doesn't allow me to install because it's missing the ESP flag, if i create / /home /swap partitions from Calamares, the system won't boot as the /etc/fstab/ is empty

** Scenario A To Reproduce**
1. Delete all partitions, including EFI
2. Create EFI system partition from Calamares and try to assign ESP,BOOT flag to
3. Create / and swap partition from Calamares
4. Continue to next user creation, and see the error asking for ESP flag

** Scenario B To Reproduce**
1. Delete all partitions, including EFI
2. Create EFI system partition from gparted or cfdisk and assign ESP,BOOT flag to it then proceed to installer
3. Create / and swap partition from Calamares
4. Install the system and reboot to see the error

**Expected behavior**
Expected behavior is to have the ESP flag in Calamares, and Calamares to be able to create the proper /etc/fstab

**Comment by abucodonosor** [comment]
What is your calamares and kpmcore version?

With kpmcore 4.0.0 and calamares  3.2.7, it installs just fine.

Can you start calamares with -d flag and attach the log in here?

**Comment by kronikpillow** [comment]
calamares 3.2.7-5 (3.2.9rc1.20190513-git-development-c7aa9ba-dirty)
kpmcore 4.0.0-3

Debug log:
https://pastebin.com/Neb91mbU

Terminal log:
https://pastebin.com/nu40WMpG

Result after booting:
Empty /etc/fstab
[boot screenshot](https://i.imgur.com/WPl3bOih.jpg)
[/etc/fstab](https://imgur.com/G8qOZvZ)

Note: the efi partition is not marked as ESP, as we do not have a ESP flag in Calamares for some reason

**Comment by erikdubois** [comment]
Is it normal that there is no esp flag available when you do a manual partitioning with gpt and choose a fat32 /boot/efi of 512 mb?

Is it in the code?

I choose now the boot flag and everything installs and reboots fine.

I was wondering if the boot flag replaces the old esp flag.

This is on the latest kmpcore 4.

**Comment by kkofler** [comment]
Yes, the boot flag replaces the old ESP flag. This was originally a change in libparted, where they decided that one flag was enough and that libparted should automatically do the right thing with it, and the new KPMcore sfdisk backend also uses that single-flag approach.

**Comment by kronikpillow** [comment]
So why are not my Partitions mounted?

**Comment by kronikpillow** [comment]
Rebuilt the Iso with
Calamares 3.2.8
kpmcore 4.0.0-3
and found a new problem

Scenario 1:
Create New GPT Partition Table over the old partition table from Calamares

result:
[](https://imgur.com/beUlv0N.png)

video: 
[](https://vimeo.com/336785458)

Calamares 3.2.8
kpmcore 4.0.0-3

Scenario 1:
Create New GPT Partition Table over the old partition table from Calamares

result:
[](https://imgur.com/beUlv0N.png)

video: 
[](https://vimeo.com/336785458)

**Comment by kronikpillow** [comment]
our team member Nick says that he has the same problem on his old Toshiba Laptop with a old Toshiba HDD ...

**Comment by robin0800** [comment]
I ran sudo  -E calamares -d   see log below
```
02:25:42 [6]: Check EFI bootable "/dev/sda1" "/dev/sda" 
02:25:42 [6]:  ..  flags QFlags(0x1) 
02:25:42 [6]: Check EFI bootable "/dev/sda2" "/dev/sda" 
02:25:42 [6]:  ..  flags QFlags() 
02:25:42 [6]:  ..  moved towards root 0x7f875c0a1090 
02:25:42 [6]:  ..  partition table 0x7f875c0a1090 type 6 
02:25:42 [6]: Check EFI bootable "/dev/sda3" "/dev/sda" 
02:25:42 [6]:  ..  flags QFlags() 
02:25:42 [6]:  ..  moved towards root 0x7f875c0a1090 
02:25:42 [6]:  ..  partition table 0x7f875c0a1090 type 6 
02:25:42 [6]: Check EFI bootable "/dev/sdb1" "/dev/sdb" 
02:25:42 [6]:  ..  flags QFlags() 
02:25:42 [6]:  ..  moved towards root 0x7f875c045090 
02:25:42 [6]:  ..  partition table 0x7f875c045090 type 6 
02:25:42 [6]: Check EFI bootable "/dev/sdb2" "/dev/sdb" 
02:25:42 [6]:  ..  flags QFlags(0x1) 
02:25:42 [6]: Check EFI bootable "/dev/sdb3" "/dev/sdb" 
02:25:42 [6]:  ..  flags QFlags() 
02:25:42 [6]:  ..  moved towards root 0x7f875c045090 
02:25:42 [6]:  ..  partition table 0x7f875c045090 type 6 
02:25:42 [6]: Check EFI bootable "/dev/sdb4" "/dev/sdb" 
02:25:42 [6]:  ..  flags QFlags() 
02:25:42 [6]:  ..  moved towards root 0x7f875c045090 
02:25:42 [6]:  ..  partition table 0x7f875c045090 type 6 
02:25:42 [6]: Check EFI bootable "/dev/sdb5" "/dev/sdb" 
02:25:42 [6]:  ..  flags QFlags() 
02:25:42 [6]:  ..  moved towards root 0x7f875c045090 
02:25:42 [6]:  ..  partition table 0x7f875c045090 type 6 
02:25:42 [6]: Check EFI bootable "/run/media/manjaro/Backup Disk" "/dev/sdc" 
02:25:42 [6]:  ..  flags QFlags() 
02:25:42 [6]:  ..  moved towards root 0x7f875c06f2d0 
02:25:42 [6]:  ..  partition table 0x7f875c06f2d0 type 6 
02:25:42 [6]: Check EFI bootable "/run/media/manjaro/Backup" "/dev/sdc" 
02:25:42 [6]:  ..  flags QFlags() 
02:25:42 [6]:  ..  moved towards root 0x7f875c06f2d0 
02:25:42 [6]:  ..  partition table 0x7f875c06f2d0 type 6 
02:26:03 [6]: old boundaries: 264192 61704191 61440000 
02:26:03 [6]: new boundaries: 264192 61704191 
02:26:03 [6]: dirty status: false 
02:26:03 [6]: Check EFI bootable "/dev/sda1" "/dev/sda" 
02:26:03 [6]:  ..  flags QFlags(0x1) 
02:26:03 [6]: Check EFI bootable "/dev/sda2" "/dev/sda" 
02:26:03 [6]:  ..  flags QFlags() 
02:26:03 [6]:  ..  moved towards root 0x7f875c0a1090 
02:26:03 [6]:  ..  partition table 0x7f875c0a1090 type 6 
02:26:03 [6]: Check EFI bootable "/dev/sda3" "/dev/sda" 
02:26:03 [6]:  ..  flags QFlags() 
02:26:03 [6]:  ..  moved towards root 0x7f875c0a1090 
02:26:03 [6]:  ..  partition table 0x7f875c0a1090 type 6 
02:26:03 [6]: Check EFI bootable "/dev/sdb1" "/dev/sdb" 
02:26:03 [6]:  ..  flags QFlags() 
02:26:03 [6]:  ..  moved towards root 0x7f875c045090 
02:26:03 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:03 [6]: Check EFI bootable "/dev/sdb2" "/dev/sdb" 
02:26:03 [6]:  ..  flags QFlags(0x1) 
02:26:03 [6]: Check EFI bootable "/dev/sdb3" "/dev/sdb" 
02:26:03 [6]:  ..  flags QFlags() 
02:26:03 [6]:  ..  moved towards root 0x7f875c045090 
02:26:03 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:03 [6]: Check EFI bootable "/dev/sdb4" "/dev/sdb" 
02:26:03 [6]:  ..  flags QFlags() 
02:26:03 [6]:  ..  moved towards root 0x7f875c045090 
02:26:03 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:03 [6]: Check EFI bootable "/dev/sdb5" "/dev/sdb" 
02:26:03 [6]:  ..  flags QFlags() 
02:26:03 [6]:  ..  moved towards root 0x7f875c045090 
02:26:03 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:03 [6]: Check EFI bootable "/run/media/manjaro/Backup Disk" "/dev/sdc" 
02:26:03 [6]:  ..  flags QFlags() 
02:26:03 [6]:  ..  moved towards root 0x7f875c06f2d0 
02:26:03 [6]:  ..  partition table 0x7f875c06f2d0 type 6 
02:26:03 [6]: Check EFI bootable "/run/media/manjaro/Backup" "/dev/sdc" 
02:26:03 [6]:  ..  flags QFlags() 
02:26:03 [6]:  ..  moved towards root 0x7f875c06f2d0 
02:26:03 [6]:  ..  partition table 0x7f875c06f2d0 type 6 
02:26:18 [6]: old boundaries: 61704192 976773119 915068928 
02:26:18 [6]: new boundaries: 61704192 976773119 
02:26:18 [6]: dirty status: false 
02:26:18 [6]: Check EFI bootable "/dev/sda1" "/dev/sda" 
02:26:18 [6]:  ..  flags QFlags(0x1) 
02:26:18 [6]: Check EFI bootable "/dev/sda2" "/dev/sda" 
02:26:18 [6]:  ..  flags QFlags() 
02:26:18 [6]:  ..  moved towards root 0x7f875c0a1090 
02:26:18 [6]:  ..  partition table 0x7f875c0a1090 type 6 
02:26:18 [6]: Check EFI bootable "/dev/sda3" "/dev/sda" 
02:26:18 [6]:  ..  flags QFlags() 
02:26:18 [6]:  ..  moved towards root 0x7f875c0a1090 
02:26:18 [6]:  ..  partition table 0x7f875c0a1090 type 6 
02:26:18 [6]: Check EFI bootable "/dev/sdb1" "/dev/sdb" 
02:26:18 [6]:  ..  flags QFlags() 
02:26:18 [6]:  ..  moved towards root 0x7f875c045090 
02:26:18 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:18 [6]: Check EFI bootable "/dev/sdb2" "/dev/sdb" 
02:26:18 [6]:  ..  flags QFlags(0x1) 
02:26:18 [6]: Check EFI bootable "/dev/sdb3" "/dev/sdb" 
02:26:18 [6]:  ..  flags QFlags() 
02:26:18 [6]:  ..  moved towards root 0x7f875c045090 
02:26:18 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:18 [6]: Check EFI bootable "/dev/sdb4" "/dev/sdb" 
02:26:18 [6]:  ..  flags QFlags() 
02:26:18 [6]:  ..  moved towards root 0x7f875c045090 
02:26:18 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:18 [6]: Check EFI bootable "/dev/sdb5" "/dev/sdb" 
02:26:18 [6]:  ..  flags QFlags() 
02:26:18 [6]:  ..  moved towards root 0x7f875c045090 
02:26:18 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:18 [6]: Check EFI bootable "/run/media/manjaro/Backup Disk" "/dev/sdc" 
02:26:18 [6]:  ..  flags QFlags() 
02:26:18 [6]:  ..  moved towards root 0x7f875c06f2d0 
02:26:18 [6]:  ..  partition table 0x7f875c06f2d0 type 6 
02:26:18 [6]: Check EFI bootable "/run/media/manjaro/Backup" "/dev/sdc" 
02:26:18 [6]:  ..  flags QFlags() 
02:26:18 [6]:  ..  moved towards root 0x7f875c06f2d0 
02:26:18 [6]:  ..  partition table 0x7f875c06f2d0 type 6 
02:26:42 [6]: old boundaries: 504465408 537233407 32768000 
02:26:42 [6]: new boundaries: 504465408 537233407 
02:26:42 [6]: dirty status: false 
02:26:42 [6]: Check EFI bootable "/dev/sda1" "/dev/sda" 
02:26:42 [6]:  ..  flags QFlags(0x1) 
02:26:42 [6]: Check EFI bootable "/dev/sda2" "/dev/sda" 
02:26:42 [6]:  ..  flags QFlags() 
02:26:42 [6]:  ..  moved towards root 0x7f875c0a1090 
02:26:42 [6]:  ..  partition table 0x7f875c0a1090 type 6 
02:26:42 [6]: Check EFI bootable "/dev/sda3" "/dev/sda" 
02:26:42 [6]:  ..  flags QFlags() 
02:26:42 [6]:  ..  moved towards root 0x7f875c0a1090 
02:26:42 [6]:  ..  partition table 0x7f875c0a1090 type 6 
02:26:42 [6]: Check EFI bootable "/dev/sdb1" "/dev/sdb" 
02:26:42 [6]:  ..  flags QFlags() 
02:26:42 [6]:  ..  moved towards root 0x7f875c045090 
02:26:42 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:42 [6]: Check EFI bootable "/dev/sdb2" "/dev/sdb" 
02:26:42 [6]:  ..  flags QFlags(0x1) 
02:26:42 [6]: Check EFI bootable "/dev/sdb3" "/dev/sdb" 
02:26:42 [6]:  ..  flags QFlags() 
02:26:42 [6]:  ..  moved towards root 0x7f875c045090 
02:26:42 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:42 [6]: Check EFI bootable "/dev/sdb4" "/dev/sdb" 
02:26:42 [6]:  ..  flags QFlags() 
02:26:42 [6]:  ..  moved towards root 0x7f875c045090 
02:26:42 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:42 [6]: Check EFI bootable "/dev/sdb5" "/dev/sdb" 
02:26:42 [6]:  ..  flags QFlags() 
02:26:42 [6]:  ..  moved towards root 0x7f875c045090 
02:26:42 [6]:  ..  partition table 0x7f875c045090 type 6 
02:26:42 [6]: Check EFI bootable "/run/media/manjaro/Backup Disk" "/dev/sdc" 
02:26:42 [6]:  ..  flags QFlags() 
02:26:42 [6]:  ..  moved towards root 0x7f875c06f2d0 
02:26:42 [6]:  ..  partition table 0x7f875c06f2d0 type 6 
02:26:42 [6]: Check EFI bootable "/run/media/manjaro/Backup" "/dev/sdc" 
02:26:42 [6]:  ..  flags QFlags() 
02:26:42 [6]:  ..  moved towards root 0x7f875c06f2d0 
02:26:42 [6]:  ..  partition table 0x7f875c06f2d0 type 6 
02:26:52 [6]: Check EFI bootable "/dev/sda1" "/dev/sda" 
02:26:52 [6]:  ..  flags QFlags(0x1) 
02:27:49 [0]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
02:27:49 [0]: QObject::setParent: Cannot set parent, new parent is in a different thread
02:27:49 [0]: QObject::setParent: Cannot set parent, new parent is in a different thread
02:27:49 [6]: Writing to GlobalStorage["partitions"] 
02:27:49 [6]:  ..  partitions on "/dev/sda" 
02:27:49 [6]:  ..  mapping for "/dev/sda1" "/dev/sda1" 
     mtpoint: :   "/boot/efi" 
     fs: :   "fat32" 
     fsname :   "fat32" 
     uuid :   "2395-BF91" 
02:27:49 [6]:  ..  mapping for "/dev/sda2" "/dev/sda2" 
     mtpoint: :   "/" 
     fs: :   "ext4" 
     fsname :   "ext4" 
     uuid :   "9ba13f5c-977a-4d97-97a5-2729440b50d4" 
02:27:49 [6]:  ..  mapping for "/dev/sda3" "/dev/sda3" 
     mtpoint: :   "/home" 
     fs: :   "ext4" 
     fsname :   "ext4" 
     uuid :   "d8f46e2a-47d2-4017-b0ce-0f18d0ee3364" 
``` should it be?
First entry is the boot/efi partition and you can see it was not processed should it be ?

**Comment by abucodonosor** [comment]
I cannot reproduce any of these..

Give me a link to your ISO, please.

**Comment by robin0800** [comment]
If you choose manual partitioning and format it as Fat 32 its during thist process that calamares looses the flags and where the log came from.

**Comment by abucodonosor** [comment]
@robin0800 

Again, if you use kpmcore 4.x there is no ESP flag, @kkofler explained to you already.
Also, @stikonas explained in  #891.

The missing 'fstab UUID' seems to be something specific to your ISO/Distro.

I tested the latest release, also 3.2.7 with Debian, Fedora, Gentoo based ISOs and my
own ISO and cannot reproduce.

So either you post a link to that ISO so we can look or you try to find out by
yourself.

**Comment by robin0800** [comment]
Have you formatted the fat32 partition with calamares as that is the only fault I am reporting. As the flags are missing, after the format I do not know if both boot and esp are there?

**Comment by robin0800** [comment]
https://osdn.net/projects/manjaro/storage/kde-dev/19.05.17/manjaro-kde-dev-19.05.17-unstable-minimal-x86_64.iso/

**Comment by kronikpillow** [comment]
@abucodonosor i will post a link to my ISO and the packages on it in a few hours

**Comment by kronikpillow** [comment]
sorry for the late reply, I was really busy in real life ... 
boot is only there, esp is not, even after formatting the partition, so after more experimentation, it has come to my attention, that when I do not set the root flag on the root partition, and the swap flag on the swap partition, the distro installs perfectly fine, which was strange to me because I was doing the same steps with the previous version of Calamares, and it installed fine, so I went ahead and redownloaded the ISO with the previous version of Calamares, repeated the same steps and set the root parittion with the root flag, and swap partition with the swap flag, and the system installed perfectly fine ... then i rebuilt the ISO with the newest version, repeated the same steps, and had the same error ... in the end, I just decided to bypass the problem by not setting root partition with the root flag, and not setting the swap flag to the swap partition, I just formated them to boot to fat32, root to ext4 and swap to linuxswap and mounted them to /boot/efi ; / ; swap

ArcoLinuxB is a build your own ISO, but i used the default packages, the package list can be found on ArcoLinuxB github, any of the desktops as they mainly have all packages in common with each other except the specific DE/WM packages, I can build it and upload it to my own google drive if anyone wants to test it out as you need to have ArcoLinux repositories to be able to build the ISO
