### ISSUE TITLE
welcome.conf - autoselect language set to true/false

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1148]
Welcome can now do GeoIP lookups as well (but be careful with the configuration, since you need a GeoIP that provides country information, not just timezones). This will let Calamares select a starting language that matches where it is – which might not be useful at all. #934

Can you include a variable set to true of false to enable or disable this automatic pre-select of the language?

https://calamares.io/calamares-3.2.8-is-out/

automatic-preselect-language=true or false

Living in Belgium it changes my calamares to dutch. In general this would be nice.
But I want it to be set to American English. 
First screen Welcome I change the language and calamares changes with it and on the
second screen Location the system changed to American English (United States) but NOT the numbers and dates that is still in Nederlands (Belgie). 
Now I need to change it manually to en_US.UTF-8. Maybe you can change this also automatically to the correct setting?

**Comment by adriaandegroot** [comment]
If you don't want it, either (a) leave out the `geoip` section, or set `style` in that section to something that is unsupported (e.g. `none`).  I guess the comment/documentation could be improved a little there.

**Comment by arcolinuxz** [comment]
Just wanted to be sure you read this part.
If you choose to set it back to American English and not dutch for Belgium, 
calamares will NOT set it right in the second screen.
The numbers and dates are still in Nederlands (Belgie).
I would assume calamares would change that back to american english as well.
