### ISSUE TITLE
finished restartNowMode always broken

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1151]
**Describe the bug**
The finished module's `restartNowMode: always` seems a bit broken right now. This was working when originally implemented but since stopped working. Clicking the 'Done' button currently does nothing on git master.

**To Reproduce**
1. have a settings.conf with finished
2. finished.conf to contain 

```
restartNowMode: always
restartNowCommand: "systemctl -i reboot"
```

3. install
4. click 'Done' button to close cala

**Expected behavior**
Cala issues the restart command.

**Screenshots and Logs**
![Screenshot_generic_2019-05-20_14:28:18](https://user-images.githubusercontent.com/809987/58022199-3a097380-7b0d-11e9-9403-cae65fae4d32.png)

**Additional context**
Possibly regressed in the "disable-progress-buttons-thingy re-hash"

**Comment by adriaandegroot** [comment]
Also needs `disable-cancel: true` in `settings.conf`.
