### ISSUE TITLE
Packages module misses a flag in pacman

### ISSUE THREAD

**Issue by CaioFViana** [calamares/calamares#1154]
When testing the netinstall module, I found an bug with the Packages module. Using the -d flag in calamares show that to update the Db is using -Sy, with is non-interactive, so no error will happen. However, when it's updating the system it uses -Su, with asks for permission in terminal, making the installation stuck on "installing packages" forever. To fix it, adding a --noconfirm at the end shoud enough .

The installer "just works" without this module.

**To Reproduce**

I am using a modification of Arch Linux with graphical interface. Everyone using pacman maybe is valid to test too.

1. Go to the settings.conf and add the packages module, on my testing it's after the bootloader module.
2. In packages.conf, enable update-db and update system. And use pacman as backend package manager.
3. Build the system, but install a package and wait for it to be updated in mirrors, so no "nothing to do" invalids the testing (sorry, no suggestions, only faking an old package seems quicker)
4. Let it install. It will stuck at "installing packages" and if you run the same commands in the live iso enviroment, (as the -d shows), it will wait for user confirmation.

**Expected behavior**
Just finish installing. With a --noconfirm, pacman don't ask users for anything.

**Additional context**
Sometimes, it ends the installation without the error, but I suspect that it just says "nothing to do" and finishes.

Finally, if I am just using it wrong, I am sorry.

**Comment by philmmanjaro** [comment]
Normally it should get set. See [here](https://github.com/calamares/calamares/blob/master/src/modules/packages/main.py#L284).

**Comment by CaioFViana** [comment]
It's set on installing packages. The bug is when updating the system. If you see some lines below:

def update_system(self):
        check_target_env_call(["pacman", "-Su"])

There is no --noconfirmin that. If I open my 8 days old VM (so there is at least any package to update) and do pacman -Sy, there is no need for confirmation to update the repos. But when I do pacman -Su right after....

![image](https://user-images.githubusercontent.com/48189068/58172707-a8fedd80-7c6f-11e9-932d-e28d239e6541.png)

It's waiting for confirmation. Calamares is executing the right command but waiting for user input is locking the installation, and it never finishes.

**Comment by adriaandegroot** [comment]
@philmmanjaro  so the point was that `pacman -Su` might need a `--noconfirm`. I added this just now, please check that that does the right thing as described by the reporter here.
