### ISSUE TITLE
Documentation lacking: no examples of instances/re-use of modules

### ISSUE THREAD

**Issue by jstnlth** [calamares/calamares#1158]
**Describe the bug**
Several modules like contextualprocess, shellprocess and interactiveterminal can be needed multiple times in the sequence. I found examples of doing this in lubuntu's settings, but I didn't see any reference to it in the wiki or in the .conf examples.

instances:
- id: unique_name_one
  module: shellprocess
  config: unique_name_one.conf
sequence:
- show:
  - welcome
  - shellprocess@unique_name_one

(or something like that - if I understood it correctly)
Would the example settings.conf file would be the best place to document this?

**Comment by kkofler** [comment]
There is the `webview@owncloud` example in the default configuration.

**Comment by jstnlth** [comment]
very true. I should have double-checked everything while writing up the bug report. I do remember seeing webview@xxx now, but I never understood anything about it at the time. It does seem clear enough to me as I re-read it. Sorry for the noise.
