### ISSUE TITLE
Installation under BTRFS is not working after reboot

### ISSUE THREAD

**Issue by gonzalo2099** [calamares/calamares#1162]
Hi, I get the following trouble with new version 3.2.8, with ext4, jfs and jfs I don't have any problem and all is working perfect later to install the system. The problem comes if I use BTRFS filesystem, after the installation when I reboot computer the system can't start. I don't have a log right now because I'm on my phone right now. Seem is not able to recognize the UUID of partitions correctly. I'm working with Arch Linux and with previous versions I never had that issue.

Thanks for the great job with Calamares!!

**Comment by abucodonosor** [comment]
@gonzalo2099 

An empty UUID in fstab?

**Comment by gonzalo2099** [comment]
No, just cannot identify correctly the UUID of disk partitions, so I have Kernel in panic mode

**Comment by abucodonosor** [comment]
@gonzalo2099 

How do you install with BTRFS? And what installation media you are using? Own?

**Comment by gonzalo2099** [comment]
I use an hdd with MBR partition table. Usually I take an extended partition for Linux installation, I make 1 partition for swap, 1 partition for "/", 1 partition for "/home"

**Comment by abucodonosor** [comment]
@gonzalo2099 

So BIOS installation on an extended partition.

Since ArchLinux do not support calamares, what 'installation ISO' 
are you using?

I use here BTRFS as default FS so I wonder cause working fine here.

**Comment by gonzalo2099** [comment]
I use my own iso, I'm building my own distribution based on arch repos

**Comment by gonzalo2099** [comment]
I solved the problem. The new installed system has an empty UUID partitions in /etc/fstab and no /home/$USER folder. I delete the extended partition and create primary partitions for "swap" and "/". Now btrfs works perfectly. In calamares 3.2.2 and 3.2.3 never get this issue.

**Comment by abucodonosor** [comment]
It seems like some ArchLinux based Distributions have UUID problems.

**Comment by abucodonosor** [comment]
This seems to be solved, closing now.
