### ISSUE TITLE
support swapfiles

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1166]
**Is your feature request related to a problem? Please describe.**
I hate it when my partition table is getting extra complexity because the installer thinks this is the 1980's and I need a dedicated swap partition.

**Describe the solution you'd like**
As a distribution I'd like a config option to switch calamares from swap-partitioning mode to swapfiles. In this mode it'd not create a swap partition but instead add a swapfile to the partition / is going to be on.

**Additional context**
Previously seen as #1006 which got partially resolved by having some of the infrastructure to support this but swapfile support itself was never actually added.

Swapfiles are simply crated by fallocating a file on the disk and adding it to the /etc/fstab.

As an example Ubiquity's implementation is here https://packaging.neon.kde.org/forks/ubiquity.git/tree/d-i/source/partman-swapfile/finish.d?h=Neon/unstable

Not all filesystems support swapfiles (e.g. BTRFS does not) so there probably to be some flexibility. Even when a swapfile was opted for, actual file system constraints may make it an unsuitable.

**Comment by emanuc** [comment]
Support for swapfile has been added to the 5.0 kernel, but it needs to be nocow.
These are the steps to activate it correctly: [https://wiki.archlinux.org/index.php/Swap#Swap_file_creation](url)
I reported the bug on launchpad (ubiquity) : [https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1818811](url)

**Comment by feren** [comment]
Something else I'd like to be implemented if this happens is allowing distributors to force Hibernate On swapfiles unless the swapfile is too big for the / partition in which case then resort to No Hibernate but warn the user that Hibernate won't be available on the installed Operating System due to the lack of disk space.

**Comment by adriaandegroot** [comment]
This is not going to make it, although more because
- other regressions are taking up time
- wading through the partition module takes so much cleanup before the part-where-swap-is-handled is visible

I don't know about .29, since I wanted  that one to be a quick progress-reporting improvement.

**Comment by emanuc** [comment]
As described [1] it is better to create the swapfile but on a separate subvolume on the filesystem toplevel.

1)  [https://www.spinics.net/lists/linux-btrfs/msg103213.html](https://www.spinics.net/lists/linux-btrfs/msg103213.html)

This is how I create swapfile on installers that don't support swapfile on Btrfs:
`sudo mount -t btrfs -o options /dev/sda1 /mnt`
`sudo btrfs subvol create /mnt/@swapfile`
`sudo chattr +C /mnt/@swapfile`

then I created the swapfile inside the subvol "@swapfile":
`sudo fallocate -l 512M /mnt/@swapfile/swapfile`
`sudochmod 600 /mnt/@swapfile/swapfile`
`sudo chattr +C /mnt/@swapfile/swapfile`

Then I edit fstab:
`UUID=b383c3a8-39dd-4edd-98e1-0217a87d266a /swap btrfs defaults,subvol=@swap 0 0`
`/swap/swapfile none swap sw 0 0`

I hope it is useful and **thanks** for the work you do.
