### ISSUE TITLE
call kpmcore's ExternalCommand::stopHelper()

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1167]
**Describe the bug**
Exiting calamares leaves kpmcore_externalcommand running. This is the elevated helper backing kpmcore. This is prevented by calling `ExternalCommand::stopHelper()` on exit (but before dbus is shut down) to forcefully "detach" from the helper causing to terminate within the next 10 seconds.

**To Reproduce**
1. start calamares
2. observe kpmcore helper running
3. quit calamares
4. start calamares immediately again
5. calamares won't initialize and is broken now because the running kpmcore helper refuses to talk to the unknown calamares

**Expected behavior**
Calamares should call ExternalCommand::stopHelper() to "unregister" itself from the helper. I ought to note that this is a bit incorrectly named as currently it doesn't actually stop the helper but rather schedules a stop, with currently released versions it still takes a while for it to actually stop. Even so, calling stopHelper allows another calamares to re-use it.

**Additional context**
As of today there's also an improvement in kpmcore master that makes helper shutdown much more timely and reliable, so when testing with newer kpmcores mind that the bug may actually be hidden by cleanup fallback already.

**Comment by adriaandegroot** [comment]
There's a branch issue-1167 for this, which has roughly the right code, but in the wrong place. ViewSteps and Jobs are not deleted on exit, so the destructors defined there don't run. The module destructors **do** run, so it might be possible to connect steps (and Jobs) up with modules, and clean them up there.

**Comment by apachelogger** [comment]
Destructor may actually be too late. You need a working qdbus for it to work and I am not sure you still have that on destruction.

I wonder if the modules couldn't just add an qapp::aboutToQuit handler?

```
connect(qApp, &QCoreApplication::aboutToQuit, [](){ ExternalCommand::stopHelper(); };
```

**Comment by adriaandegroot** [comment]
Branch issue-1167 is, as you point out, probably not the right approach. A new branch kpmcore-manager does a lot more in this direction, starting and stopping KPMCore services as needed. It still needs to be applied to the partitioning jobs, though.

The manager can also be used to deal with settling disks, although then we'll need to adapt the code that does things outside of kpmcore to call into that service first :S

**Comment by adriaandegroot** [comment]
This goes away with KPMCore >= 4.2 automatically, which is required for Calamares 3.3. For older Calamares / distributions that don't ship up-to-date KPMCore, I don't think this is worth chasing more.
