### ISSUE TITLE
Feature request : Save live desktop settings

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1171]
During my video of Mx Linux I have learned that this installer from MX Linux has an option to save the LIVE (like on the live dvd) desktop settings to the future harddisk.

They start out with a vertical xfce menu.

When I change that to an horizontal menu then the installer will make sure those settings come on the harddisk.

![mxlinux](https://user-images.githubusercontent.com/36679406/58887245-8e078100-86e5-11e9-8a5f-07d6900cf67c.png)

This image comes from the pdf of MX Linux at page 33.
https://www.mxlinux.org/user_manual_mx18/mxum.pdf

Just an idea I wanted to pass by you guys.

This is the video where I install MX Linux at 7:30
https://www.youtube.com/watch?v=kWJDoZXGg8c&lc=

**Comment by abucodonosor** [comment]
That is probably a bad idea.

Usually, the 'live' user is a special user and mostly has special 
$HOME/.config/* files for various reasons.

Like, do no automount things, disable suspend on idle and alike changes.

Copying that to a freshly created user is kind bad.

**Comment by adriaandegroot** [comment]
There are settings that can probably be copied (e.g. you're a Plasma-based live-CD and a Plasma-based DE is installed, you can install the Plasma layout from the live-user to the target user). The *plasmalnf* module does something similar,in letting the user pick a layout and then applying that in the target system. That said, you'd need to be pretty careful to not -- as @abucodonosor  points out -- pick up inappropriate settings from `.config`. You don't want to copy it over wholesale.

**Comment by arcolinuxz** [comment]
let us close this one for now
