### ISSUE TITLE
Missing labels in installer

### ISSUE THREAD

**Issue by muesli** [calamares/calamares#1173]
When trying to install Neon on an encrypted LVM, two unlabeled input fields are showing up. I assume I'm supposed to enter the encryption password here, but I really don't know.

See attached screenshot.

![image](https://user-images.githubusercontent.com/146378/58969033-4f41fb80-87b7-11e9-897d-953550d96ee3.png)

**Comment by abucodonosor** [comment]
Well, that is not calamares in that screenshot.

**Comment by muesli** [comment]
Well, now it's getting confusing. I reported it on Neon's bugtracker first, but was told to report it for Calamares here instead:

https://bugs.kde.org/show_bug.cgi?id=408267

**Comment by abucodonosor** [comment]
@muesli 

I see.

I re-opened the bug:

https://bugs.kde.org/show_bug.cgi?id=408267#c2

**Comment by kkofler** [comment]
Closing as not our bug.

**Comment by muesli** [comment]
Thanks @abucodonosor
