### ISSUE TITLE
Most lately reported partition module issue reports are related to kpmcore 4 api

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#1174]
**Describe the bug**
When we compile **CAL** against **kpmcore3** all seems to be fine. Only when **kpmcore 4.0** is used we see a lot of regressions in our [latest builds](https://twitter.com/ManjaroLinux/status/1137314768350588928).

**To Reproduce**
1. Download one of our [latest development releases](https://twitter.com/ManjaroLinux/status/1137314768350588928)
2. Try to install Manjaro
3. You may get crashes on partitioning or failures using swap in encryption mode

A more stable experience will give [18.1-rc1](https://twitter.com/ManjaroLinux/status/1136630587840782336).

**Expected behavior**
Work similar stable as with kpmcore 3.3 API

**Comment by abucodonosor** [comment]
Yes, @adriaandegroot started a branch for that.

https://github.com/calamares/calamares/commit/743530607282334d9f2b1f0b7cd4731306ee3fe5
