### ISSUE TITLE
Calamares fails to set the boot flag on a boot partition (BIOS)

### ISSUE THREAD

**Issue by salientos** [calamares/calamares#1175]
**Describe the bug**

Calamares fails to set the boot flag on the boot partition (bios legacy boot)

**To Reproduce**

Erase Disk

Start installer, select device from top drop-down, select Erase disk option. In this case, No Swap.
Select from Boot loader location: Boot Partition (/boot). Start Install process. Installation is successful except no boot flag ever gets set in this scenario.

partition.conf

partitionLayout:
    - name: "boot"
      filesystem: "ext4"
      mountPoint: "/boot"
      size: 512M
    - name: "root"
      filesystem: "ext4"
      mountPoint: "/"
      size: 20%
      minSize: 10G
      maxSize: 50G
    - name: "home"
      filesystem: "ext4"
      mountPoint: "/home"
      size: 100%

**Expected behavior**

Calamares to correctly set boot flag of boot partition.

**Screenshots and Logs**

No screen shot available at this time, log pending ISO rebuild and another installation test.

Short video available here: https://drive.google.com/open?id=1IGpOpyCa1o4M1yii9Xi4iatAYOpU3J94

**Additional context**

If I choose Manual method, obviously i am free to partition the drive however i wish and set appropriate flags. This works.

**Comment by apt-ghetto** [comment]
Why do you need a boot flag set? Could you please add a use case?

**Comment by d3signr** [comment]
> Why do you need a boot flag set? Could you please add a use case?

Otherwise the system won't boot!

**Comment by kkofler** [comment]
Different BIOSes behave differently, but many won't even try to boot from a disk's MBR if its partition table does not contain at least one partition with the boot flag set. GRUB won't care at all about the flag (other bootloaders may behave differently), but if the BIOS doesn't run GRUB to begin with, you lose.

**Comment by wxl** [comment]
Shouldn't we assign a new milestone for this? I didn't realize this was a thing until I ran into a support request this morning.

Am I correct in understanding the scope of this is confined solely to BIOS (my support request was, as this is, though I'm a bit confused as to why #1192 is related).

In any case, it seems that forcing a boot flag on root for automatic partitioning and popping up a warning as we do for esp with EFI for manual partitioning should solve the problem, no?

**Comment by adriaandegroot** [comment]
Confirmed with a Manjaro install just now. VirtualBox doesn't complain about this, it just boots, but as @salientos points out this *might* affect some real hardware.

**Comment by gene1wood** [comment]
I've observed this with calamares on lubuntu 20.04 installing on a legacy bios system. Provisions the system fine but upon rebooting, the system doesn't boot on the newly provisioned disk
