### ISSUE TITLE
Swap with hibernate should check image size

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#1179]
Hi, I'm working on my next release of GeckoLinux, based on openSUSE Leap 15.1 or Tumbleweed. The test image I'm working with has Calamares 3.2.9 with kpmcore 3.3.0. I'm using the default [partition.conf](https://raw.githubusercontent.com/calamares/calamares/master/src/modules/partition/partition.conf) file, except that I define `requiredStorage: 3.5`
My test VM has an 8GB disk and 2816MB of RAM.

When using the swap with hibernation option, it creates a `/` partition that is too small, and installation fails for lack of space.

![Screenshot_20190620_125554](https://user-images.githubusercontent.com/2692138/59870994-25163f00-935c-11e9-9c03-e2870a6f2fe8.png)

**Comment by abucodonosor** [comment]
@geckolinux 

Do you have requiredStorage set in welcome.conf too?

Also what version of calamares are you using?

**Comment by geckolinux** [comment]
Hi @abucodonosor , I'm not using a `welcome.conf`, so it must be using the default there.

Calamares 3.2.9.

**Comment by abucodonosor** [comment]
@geckolinux 

Uh :-) you really should. welcome.conf is the place you set checks on storage, memory etc.

Also if you have something set in there it will use that.

**Comment by geckolinux** [comment]
OK, I'll try that and let you know.

**Comment by adriaandegroot** [comment]
Calamares **master** branch also allows setting *requiredStorage* in `partition.conf`, that's so that you can get away with no welcome page. But it's "get away with", and for specialized purposes (in particular, the required storage **must** be set for Calamares to offer replace and alongside partitioning, and in OEM setups you might skip the welcome page; but for regular users the welcome page is **really really** recommended, because otherwise the user can't choose a language and general system requirements are not tested).

**Comment by adriaandegroot** [comment]
@geckolinux You're using the welcome module (I can see it in the screenshot) so do take care to configure it properly. I wouldn't count on requiredStorage, set in the partitioning module, to be treated the same way as globally (that's probably worth fixing, though).

**Comment by geckolinux** [comment]
@adriaandegroot  
> required storage must be set for Calamares to offer replace and alongside partitioning

Ah, so that's why it wasn't offering replacement options for partitions. :-) I'll check both `welcome.conf` and `partition.conf` more carefully and let you know. Thanks for help!

**Comment by adriaandegroot** [comment]
I'm going to close this issue as "configuration error". If you have the size set up either in `partition.conf` or in `welcome.conf` it will be used. There **is** no default for it, so everything depends on the actual configuration files you have.

If no size is set, the hibernate swap will gladly push on the root partition to make it too small. If you have a size set, it won't shrink farther than that, and will, in fact, prevent the hibernate partition from being created at all.
