### ISSUE TITLE
update-initramfs should be more specific

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#1180]
We recently ran into a bug where `update-initramfs`, when ran with `-k all`, fails to work when no initrd is present (for example, on any Ubuntu-based image). While this is a problem with `update-initramfs`, it is curious why, if the target is supposed to be a clean system, the `update-initramfs` call is not ran with a specific kernel version (the running kernel version) as an argument (for example, `-k $(uname -r)`).

tl;dr `sed -i "s/all/$(uname -r) (OR EQUIVALENT)/" src/modules/initramfs/main.py` will probably work better.

**Comment by adriaandegroot** [comment]
It's been that way since ~2015 so I wonder why it turns out to be a problem **now**. That said, the combination of `-c -k all` in options is a little weird.

**Comment by adconrad** [comment]
It's become a problem now because upstream seems to have broken how "all" is enumerated.  There are varying opinions on how or why the new behaviour is buggy, but we'll get that sorted.

Orthogonally, though, it does seem silly for an installer that knows what kernel it just installed (and knows it only installed one) to ask to generate for "all".

**Comment by wxl** [comment]
@adriaandegroot it's not *now* so much as it is [10 months ago](https://salsa.debian.org/kernel-team/initramfs-tools/commit/f39625afd6ba6c1aa2027286dc3ef1c933da14e0). tl;dr Debian seems to have messed with `update-initramfs::get_sorted_versions()` such that it loses all sense of `$STATEDIR`, i.e. doesn't know what `initrd`s have been created and only knows those that exist, which, as Simon said, is nothing in the Ubuntu image. Our [hacky workaround](https://phab.lubuntu.me/D15) for this is to simply `touch` the `initrd` using `uname -r`. 

This certainly seems to be a problem with `update-initramfs` and there's work to get that fixed. Meanwhile, I think a more explicit call does make sense. Calamares [has always used `-k all`](https://github.com/calamares/calamares/blame/99114e04d86d3a7a6756dcf97d79ae3c9df1c7cf/src/modules/initramfs/main.py) but [`-c -t` is relatively new](https://github.com/calamares/calamares/commit/086a019d19cc32c28731c7f65a55ffdad94f4ec3).

**Comment by adconrad** [comment]
I will note, however, that if Calamares supports installing upgrades during install (and I'd assume it does, to minimize vulnerability windows post-install), then Simon's suggestion of '-k $(uname -r)' also doesn't cut it.  You actually have to be aware of the kernel you just installed, not hope it's the same as the one the installer is booted under.  This may well be why the original code just opted for '-k all'.

Of course, if you don't support upgrading-while-installing, then it's not a stretch to always assume booted kernel == installed kernel.

**Comment by adriaandegroot** [comment]
Branch *issue-1180*

**Comment by adriaandegroot** [comment]
@adconrad Is there a way, from the host, to determine which kernel has been upgraded in the target? You're right that that is still an edge case (unless updating the kernel also creates an initramfs thingy for it, so that `-k all` again picks it up.
