### ISSUE TITLE
Help with the new css possibilities for debugging text

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1183]
Can we put the text in the bottom left in white?
It says "Show Debug Information" but we can hardly read until we click on it.

![calamares-debug](https://user-images.githubusercontent.com/36679406/60135757-b8a79f80-97a2-11e9-9fce-4222ea30ade3.png)

**Comment by adriaandegroot** [comment]
Sure! Bear in mind that the button itself is a debugging feature, and is only visible when Calamares is started in debug-mode (e.g. with `-d`). But it can be styled just like everything else: use the *dump widget tree* button in the debug window to find out that the button is called *debugButton* and then add this to the stylesheet:

```
#debugButton { color: white; }
```

(in Calamares 3.2.9 and later)

**Comment by arcolinuxz** [comment]
That works like a charm.
When you press the dump widget tree, nothing visually is happening or communicated.
Does it write a file somewhere?

**Comment by arcolinuxz** [comment]
I figured out if I run calamares -d from the terminal, you get a dump of all id's possible.
For any future readers - that is how you can get them.

**Comment by killajoe** [comment]
seems that stylesheet.qss is not used at all anymore, at current calamares? or do i need to set a config to make use of it?
