### ISSUE TITLE
Calamares never recovers from cancel and restart -- seconds keep counting

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1184]
As of late we have included a new desktop file to launch calamares like this

`pkexec calamares -d `

Developers, Beta-testers and users can then analyze via debugging what is going on.

Our iso starts Calamares automatically from /etc/xdg/autostart/calamares.desktop without debugging on.

When you stop/cancel Calamares in order to start Calamares with debugging on, Calamares hangs and keeps on going forever.

It does not happen always. It seems the process calamares is not closed off properly from time to time

![calamares-to-debug-seconds](https://user-images.githubusercontent.com/36679406/60180695-e6332e00-9820-11e9-8886-7897c2c77eac.png)

Probably the response from kde server to get the geographical position.

I have also made a video to show what is going on at our end.

https://vimeo.com/344568090
password : calamares

If we need to change our code to avoid the hanging, I would like to hear it.

**Comment by arcolinuxz** [comment]
I was correct in assuming it was geoip that is hanging

![geoip](https://user-images.githubusercontent.com/36679406/60181400-68702200-9822-11e9-8b8c-91d4cb9613e5.png)

**Comment by adriaandegroot** [comment]
It can get wedged (stuck) in a few different ways:
 - waiting for sfdisk
 - waiting for kauth helper
 - stuck somewhere else

In master I just added some extra debugging so you can see which modules are taking a long time. Issue #1167 is the case where Calamares restarts are too quick for kauth and kpmcore, so you might be seeing that one.

**Comment by adriaandegroot** [comment]
You can probably avoid the hang just by waiting 10 to 15 seconds before re-starting Calamares, but that's annoying. The other issue will fix that up.

**Comment by arcolinuxz** [comment]
old post - never seen it anymore 
closing
