### ISSUE TITLE
Feature request : Adding switch to webview module - internet or no internet

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#1185]
I was experimenting with webview today which looks like a great idea to get information of a release or about ArcoLinux in your calamares window.

This is how it may look IF YOU HAVE INTERNET.
This looks awesome. All it takes is a page on the net themed and tweaked to fit inside calamares.

![webview-with-internet](https://user-images.githubusercontent.com/10594806/60287772-06431a00-9913-11e9-8677-6192b3ff61f8.jpg)

This is how it looks if YOU DO NOT HAVE INTERNET.
![webview-calamares](https://user-images.githubusercontent.com/10594806/60287839-3094d780-9913-11e9-87e2-69ded19a3294.jpg)

Thankfully Calamares does not crash and just reports an error.

Two requests

**1. Short term request** 

For now another less frightning message can be displayed something in the lines of...

"It seems your internet connection is down.
We suggest you visit this [[link]] after the installation."

Or something along those lines.

**2. Mid long request**

What if ...

we check if internet is available then show the **url** variable in the welcome.conf
if not then we show and internal "file:///usr/share/calamares/welcome/welcome.html"

If we have a **backup-url** in our webview.conf to point to something local that would solve this issue entirely and would still look amazing.

**Comment by arcolinuxz** [comment]
I am testing it out now.
IF there is internet it would be great if the users sees some kind of animations while the page is loading.
The page stays totally white... you do not really know what is happening.
Some kind of loading message ... 
If you have a slow internet, you probably have gone to next already.

**Comment by erikdubois** [comment]
closing for now
