### ISSUE TITLE
Change text in popup from esp flag to boot flag in efi installation

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1192]
I started making a Calamares  youtube series after diving into the code last week.

I think you need to change one of the popups you get when you install an EFI system.
If you forget to set the boot flag for an fat32 /boot/efi partition it says this.

![error esp](https://user-images.githubusercontent.com/36679406/60621786-edd57280-9dde-11e9-94e4-4a616f43f92e.png)

In the code you can find it in all languages - 
![boot-esp](https://user-images.githubusercontent.com/36679406/60621813-fded5200-9dde-11e9-9886-32fbf2af273c.png)

or here

https://github.com/calamares/calamares/blob/master/lang/calamares_be.ts 
and search for the word esp.

When I set the flag to boot I can install ArcoLinux just fine. There is no esp flag in your selection window.

It can be confusing for people.

**Comment by arcolinuxz** [comment]
You can find the video with the message here: 
https://youtu.be/97GH6K43WjY
Fast forward to 12:14

**Comment by apt-ghetto** [comment]
The boot flag and esp flag are two different things. I don't think, that mixing two different things is less confusing.

And in the manual partitioning, I can select the esp flag.

If you have problems with the missing boot flag, there is #1175.

**Comment by kkofler** [comment]
For current KPMcore, the `boot` and `esp` flags are the same thing, so this is not a Calamares decision. And KPMcore also only changed it because `libparted` did. I guess it could be changed back now that KPMcore uses `sfdisk` instead of `libparted`, but it is an upstream KPMcore issue and any change there is an API and ABI change for KPMcore.

**Comment by apt-ghetto** [comment]
As far as I understand it, the boot flag is a flag with value 0x80 used in the MBR partition scheme. => [Wikipedia Boot flag](https://en.wikipedia.org/wiki/Boot_flag)

And the esp flag is used by GNU Parted for a GPT partition with `Partition GUID code: C12A7328-F81F-11D2-BA4B-00A0C93EC93B (EFI System)` or a MBR partition with partition type `0xEF`.

But I admit, I have no idea, what the flags defined in [KPMcore](https://github.com/KDE/kpmcore/blob/master/src/core/partitiontable.h#L71) represent.

**Comment by wxl** [comment]
BTW on 3.2.17.1 it seems nothing has changed as far as the warning dialogue is concerned but there is no `esp` flag at all. Setting the `boot` flag, things behave like normal, but still.

**Comment by wxl** [comment]
3.2.20 still has this very basic problem, i.e. the popup has the wrong text. You can see [here](https://github.com/calamares/calamares/issues/1147#issuecomment-493367185) and [here](https://github.com/calamares/calamares/issues/891#issuecomment-493750783) that `esp` and `boot` (on EFI) are the same thing.

Basically the warning popup will be one of two things:

https://github.com/calamares/calamares/blob/6d0f5e4111b5592aba73bfa6a41806ff691de0f9/src/modules/partition/gui/PartitionViewStep.cpp#L418-L421

https://github.com/calamares/calamares/blob/6d0f5e4111b5592aba73bfa6a41806ff691de0f9/src/modules/partition/gui/PartitionViewStep.cpp#L432-L434

I've heard that whole "if you're manual partitioning you know what you're doing" song and dance and I don't think it really applies here. This is literally misleading.

**Comment by philmmanjaro** [comment]
@wxl I think the warning is still valid when **kpmcore3** is used. For **kpmcore4** however, we should change the text slightly or check if that warning is needed after all. At least we should check for **boot** flag. @adriaandegroot

**Comment by abucodonosor** [comment]
@philmmanjaro 

Yes both are valid the one for kpmcore 3 API the other for the kpmcore 4 API.
We don't need to check for boot flag just change the message, the is_esp check is done
against mount point, eg this:

`
Partition* esp = m_core->findPartitionByMountPoint( espMountPoint );
`

So something like this should do it ( untested ):

```
diff --git a/src/modules/partition/gui/PartitionViewStep.cpp b/src/modules/partition/gui/PartitionViewStep.cpp
index 28ed77409..3eebbaff6 100644
--- a/src/modules/partition/gui/PartitionViewStep.cpp
+++ b/src/modules/partition/gui/PartitionViewStep.cpp
@@ -410,6 +410,11 @@ PartitionViewStep::onLeave()
 
             QString message;
             QString description;
+#if defined( WITH_KPMCORE4API )
+            const QString espFlag = "boot";
+#else
+            const QString espFlag = "esp";
+#endif
             if ( !esp )
             {
                 message = tr( "No EFI system partition configured" );
@@ -417,11 +422,12 @@ PartitionViewStep::onLeave()
                                   "<br/><br/>"
                                   "To configure an EFI system partition, go back and "
                                   "select or create a FAT32 filesystem with the "
-                                  "<strong>esp</strong> flag enabled and mount point "
-                                  "<strong>%2</strong>.<br/><br/>"
+                                  "<strong>%2</strong> flag enabled and mount point "
+                                  "<strong>%3</strong>.<br/><br/>"
                                   "You can continue without setting up an EFI system "
                                   "partition but your system may fail to start." )
                               .arg( *Calamares::Branding::ShortProductName )
+                              .arg( espFlag )
                               .arg( espMountPoint );
             }
             else if ( esp && !PartUtils::isEfiBootable( esp ) )
@@ -430,14 +436,15 @@ PartitionViewStep::onLeave()
                 description = tr( "An EFI system partition is necessary to start %1."
                                   "<br/><br/>"
                                   "A partition was configured with mount point "
-                                  "<strong>%2</strong> but its <strong>esp</strong> "
+                                  "<strong>%2</strong> but its <strong>%3</strong> "
                                   "flag is not set.<br/>"
                                   "To set the flag, go back and edit the partition."
                                   "<br/><br/>"
                                   "You can continue without setting the flag but your "
                                   "system may fail to start." )
                               .arg( *Calamares::Branding::ShortProductName )
-                              .arg( espMountPoint );
+                              .arg( espMountPoint )
+                              .arg( espFlag );
             }
 
             if ( !message.isEmpty() )
```
