### ISSUE TITLE
Partition module - moving back from summary module to partition module harddisk is lost

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1193]
Calamares 3.2.10

https://youtu.be/97GH6K43WjY

At 8:29 it just seems I do not have a harddisk at all.

That is because in the tutorial I go to the last viewing module summary and then go back to the partition module.

He does not reload our prior installation setup. (automatic one)

Worse he does not show any harddisk anymore.
It can be fixed by pressing the "new partition table" at 8:35 only if you know that.

It is super unimportant IF you know the button will fix it.

**Comment by adriaandegroot** [comment]
That's probably (I haven't tried it) very true. Once the page has been left, its state is pretty much ignored, and coming back to it might be surprising.

**Comment by arcolinuxz** [comment]
that is solved in the meantime
calamares 3.2.17.1
ArcoLinux 20.2.1
