### ISSUE TITLE
Encryption fails if root and home partition is set

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#1196]
Hi, 

I am studying up on encryption and calamares does support encryption as you can see in our playlist about calamares - 29 video's

https://www.youtube.com/playlist?list=PLlloYVGq5pS5_LBrFHGEZq6EfWMPLKlaR

But today I made a new video.

Setup 1 : 
/boot 500MB not encrypted ext 2
/ rest of space encrypted ext4
no swap
https://www.youtube.com/watch?v=Qy_RHWHmVFI&list=PLlloYVGq5pS5_LBrFHGEZq6EfWMPLKlaR&index=2&t=0s

That resulted in a faster boot-up (8 sec to 18sec). You get 18 seconds if you let calamares encrypt also the /boot folder - I have seen your message about safety guidelines. Users were comparing us with the faster bootup on Antergos - hence we started looking.

Setup 1 works fine on vb and harddisk.

Setup 2:
/boot 500MB not encrypted ext2
/10GB / encrypted ext4
/10GB /home encrypted ext4

This results in an error

Pastebin : https://pastebin.com/Yr0TLBBt

Video : 
https://vimeo.com/349292168
password : calamares

**Comment by philmmanjaro** [comment]
Based on your log you are still using **3.2.10**. Well, we updated to **3.2.11** and changed the whole setup of encryption. Please redo your tests and report back if the issue is still given. You may use **18.1-rc5** install medias from Manjaro, which provide the latest **CAL** already.

**Comment by erikdubois** [comment]
thanks Philip

I can not use the version 11 yet because of  #1181 and wait for #1188 

I can not use the newer packages until this fixed.

Unless you do things differently on your github.

**Comment by philmmanjaro** [comment]
Therefore please get the latest **Manjaro** ISO and retest to see if the new version of **CAL** fixes your current issue.

**Comment by erikdubois** [comment]
closing this topic for now
Work on other topics as @arcolinuxz
