### ISSUE TITLE
Installation Failed, failed to execute update-initramfs error code 147

### ISSUE THREAD

**Issue by SuperKnux** [calamares/calamares#1199]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
An error that occurs when trying to bypass the "Boost.Python error in job "packages"" issue. I am on an Acer computer whose hard drive failed, and am trying to use 16 gig drives to attempt to revive it. So far, Manjaro was the only OS that was able to install using Calamares. I am trying to install SparkyLinux right now. Neither the GameOver version, nor the latest version installed properly. 
**To Reproduce**
1. Turn off your internet
2. Go through the normal Calamares installation
3. Wait until 77%
4. Error occurs.

**Expected behavior**
I expected the installation to finish normally because it never did for me. I was trying to get past the "Boost.Python error in job "packages" issue by looking at another issue and turning off my internet to avoid the packages part. I thought it would finish properly but here I am.

**Screenshots and Logs**
I am sorry, I don't have any Screenshots at the moment, if you want I can try to obtain some and send them over. I forgot to make a screenshot and send it first try. I'll remember this time.

**Additional context**

**Comment by abucodonosor** [comment]
We need a full installation log.

**Comment by adriaandegroot** [comment]
Which distribution? It **seems** like SparkyLinux, in this case. We'd still need an installation log to know what's actually going on. Also, update-initramfs doesn't document its exit codes (that's not your fault) so we just don't have much to go on.

**Comment by demmm** [comment]
Closing since no further response from submitter.  Please re-open if you still have the issue and can provide the asked for information.
