### ISSUE TITLE
Help strings in user ui page is too long for the labels

### ISSUE THREAD

**Issue by fhdk** [calamares/calamares#1202]
I have noted the labels for help text on the user setup page is too small for the provided text **or** the help text is too long.

Maybe the labels could be extended to fit horizontally to the window size or the help texts could be shortened to fit the label size.

I have noted it on Manjaro installers and have opened an issue there as well.

https://gitlab.manjaro.org/applications/calamares/issues/42

An example for Manjaro installer can be seen in [this forum comment](https://forum.manjaro.org/t/iso-openbox-19-07-11-unstable/94461/21?u=linux-aarhus) on Manjaro Forum.

**Comment by adriaandegroot** [comment]
I'm minded to change them all to (?) icons with a tooltip, rather than putting the text into the page  itself.
