### ISSUE TITLE
[GRUB][ArchLinux Derivatives] When installing with Encryption + Swap with Hibernate, hibernation does not work

### ISSUE THREAD

**Issue by ftsimas** [calamares/calamares#1208]
**Describe the bug**

When installing with the current stable ([18.0.4](https://osdn.net/dl/manjaro/manjaro-kde-18.0.4-stable-x86_64.iso)) KDE ISO, the resulting /etc/default/grub configuration has "resume" pointing to the wrong partition.

**To Reproduce**

1. Get the current stable [KDE ISO](https://manjaro.org/download/kde/).
2. Use the default settings and choose erase disk with encryption and swap with hibernate.
3. Proceed to install.

**Expected behavior**
Hibernation should restore the stored session as expected.

**Current behavior**
The OS tries to resume from the main partition, resulting essentially into a clean boot.

**Possible solution**
To counter the problem above, I used `sudo fdisk -l` to find the swap partition's path:

```
Disk /dev/sda: 298,9 GiB, 320072933376 bytes, 625142448 sectors
Disk model: ST320LT007-9ZV14
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 01161A15-94CA-4214-84DB-F5F9C4CACE94

Device         Start       End   Sectors   Size Type
/dev/sda1       4096    618495    614400   300M EFI System
/dev/sda2     618496 589410636 588792141 280,8G Linux filesystem
/dev/sda3  589410637 625137344  35726708    17G Linux filesystem

Partition 3 does not start on physical sector boundary.




Disk /dev/mapper/luks-989552d5-c043-4a81-9ad4-fee4b07f7357: 280,77 GiB, 301459479040 bytes, 588788045 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/mapper/luks-80516968-f16d-4982-9072-9a5b93a89f02: 17,3 GiB, 18289975808 bytes, 35722609 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/loop0: 426,32 MiB, 447021056 bytes, 873088 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

Afterwards, I fetched the `/dev/mapper/luks-80516968-f16d-4982-9072-9a5b93a89f02` value and went on to correct the `resume=` variable in `/etc/default/grub'.

Before:

```
GRUB_CMDLINE_LINUX_DEFAULT="quiet cryptdevice=UUID=989552d5-c043-4a81-9ad4-fee4b07f7357:luks-989552d5-c043-4a81-9ad4-fee4b07f7357 root=/dev/mapper/luks-989552d5-c043-4a81-9ad4-fee4b07f7357 resume=/dev/mapper/luks-989552d5-c043-4a81-9ad4-fee4b07f7357"
```

After:

```
GRUB_CMDLINE_LINUX_DEFAULT="quiet cryptdevice=UUID=989552d5-c043-4a81-9ad4-fee4b07f7357:luks-989552d5-c043-4a81-9ad4-fee4b07f7357 root=/dev/mapper/luks-989552d5-c043-4a81-9ad4-fee4b07f7357 resume=/dev/mapper/luks-80516968-f16d-4982-9072-9a5b93a89f02"
```

Lastly, I used `sudo update-grub` to update the configuration. Following that, hibernation was working as expected.

**Comment by tabroughton** [comment]
I have extra info on this bug, having looked at the code here in github and my logfiles etc.  It seems like an important bug to fix to me as it must be a common use case resulting in hibernate not working for users who use Calamares in this way.

I don't think this is a Manjaro specific issue, I believe it might be how the partitions are formatted and the filesystem type that is used.  I'm not really a developer so can't make a pull request, it's too complex for me, but I have some info and possible suggestions/leads into the bug.

I confirm this issue, reproduced by:
- Installing Manjaro KDE 18.1.3
- Full disk erase
- Partition with Encryption for root
- Partition with encryption for swap (and hibernate)

resulting system info:
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.17.3
KDE Frameworks Version: 5.64.0
Qt Version: 5.13.2
Kernel Version: 5.3.12-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-3632QM CPU @ 2.20GHz
Memory: 15.3 GiB of RAM
```

If I'm not mistaken then the if statements [here in grub/main.py](https://github.com/calamares/calamares/blob/28141661da71893906b0cd85e0d1006c3b2a014c/src/modules/grubcfg/main.py#L80) are looking for filesystem "linuxswap"  and then the resume device id is written if there is a partition present for swap.

so if dracut and luks conditionals aren't throwing the setting of the swap UUID when writing grug.cfg something else must be a miss with the partitioning workflow.

In the Calamares partitioning workflow for swap the filesystem _is_ being set to [`FileSystem::LinuxSwap`](https://github.com/calamares/calamares/blob/28141661da71893906b0cd85e0d1006c3b2a014c/src/modules/partition/core/PartitionActions.cpp#L196)

But when I look at the Partitions created (from fdisk print) after installation the filesystem type is _not_ "Linux Swap"

```
Disk /dev/sda: 465.78 GiB, 500107862016 bytes, 976773168 sectors
Disk model: Samsung SSD 860 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos

Device     Boot     Start       End   Sectors   Size Id Type
/dev/sda1            2048 941409474 941407427 448.9G 83 Linux
/dev/sda2       941409475 976772909  35363435  16.9G 83 Linux
```

I did a quick grep on the calamares.log to see if I could see the partitioning that's happening.

```
2019-11-29 - 19:16:39 [6]: - "Create new msdos partition table on /dev/sdb." 
2019-11-29 - 19:16:39 [6]: - "Create new 476938MiB partition on /dev/sdb (ATA Samsung SSD 860) with file system ext4." 
2019-11-29 - 19:16:47 [6]: - "Create new msdos partition table on /dev/sdb." 
2019-11-29 - 19:16:47 [6]: - "Create new 459671MiB partition on /dev/sdb (ATA Samsung SSD 860) with file system ext4." 
2019-11-29 - 19:16:47 [6]: - "Create new 17267MiB partition on /dev/sdb (ATA Samsung SSD 860) with file system linuxswap." 
2019-11-29 - 19:18:07 [6]: - "Create new msdos partition table on /dev/sdb." 
2019-11-29 - 19:18:07 [6]: - "Create new 459671MiB partition on /dev/sdb (ATA Samsung SSD 860) with file system luks." 
2019-11-29 - 19:18:07 [6]: - "Create new 17267MiB partition on /dev/sdb (ATA Samsung SSD 860) with file system luks." 
2019-11-29 - 19:20:07 [6]: Starting job "Create new msdos partition table on /dev/sdb." 
2019-11-29 - 19:20:08 [6]: Starting job "Create new 459671MiB partition on /dev/sdb (ATA Samsung SSD 860) with file system luks." 
2019-11-29 - 19:20:16 [6]: Starting job "Create new 17267MiB partition on /dev/sdb (ATA Samsung SSD 860) with file system luks."
```
Maybe the final partitioning has changed the actual partition data changing the type from 'Linux Swap' to 'Linux' and the swap conditionals when writing the grub.cfg aren't returning true.

**Comment by philmmanjaro** [comment]
@ftsimas and @tabroughton is this still the case in **Manjaro 19.0** release with **CAL 3.2.19.1**?

**Comment by tabroughton** [comment]
I'm trying to find the time to test this, hope to do so in the next day or so

**Comment by tabroughton** [comment]
This is *not* fixed.  I've tested with latest download of Manjaro 19.02.

- Installed erasing entire disk
swap for hibernate
encryption on

The disk is set up correctly, I have 2 LUKS partitions.

The issue is that within `/boot/grub/grub.cfg' there is no mention of LUKS partition id for SWAP, only the root partition is found.  To be more specific, there is a `resume` variable which should have the SWAP partition id but it has the root partition id.

This is the same issue as was in the previous version.

**Comment by abucodonosor** [comment]
@tabroughton 

you are right, can you test a patch?

http://crazy.dev.frugalware.org/fix-1208.patch

**Comment by tabroughton** [comment]
> @tabroughton
> 
> you are right, can you test a patch?
> 
> http://crazy.dev.frugalware.org/fix-1208.patch


I would love to be able to do this but I'm  a bit out of my depth at this point.  I'm not a developer of any of these things so it's all new to me.  I'm using calamares when I install manjaro (with kde plasma desktop) as an end user.  I took a look at the calamares build tools etc and it's a bit over my head, but if I'd also have to integrate that into the manjaro build too then I'd drown...  Am I being too timid?  Is there an easy way to test the patch?

**Comment by abucodonosor** [comment]
@tabroughton 

I could give you the whole patched file but you still need to replace the file on the live iso. It probably better to wait  @philmmanjaro builds a testing calamares package for you to test.
