### ISSUE TITLE
Include UMASK=0077 only when needed

### ISSUE THREAD

**Issue by apt-ghetto** [calamares/calamares#1209]
**Is your feature request related to a problem? Please describe.**
With the security fixes in 3.2.11, Calamares creates the configuration `/etc/initramfs-tools/conf.d/calamares-safe-initramfs.conf` and sets `UMASK=0077`. This additional config file is created always, also for unencrypted installations.

**Describe the solution you'd like**
Add the additional configuration only, if the system is encrypted.

**Comment by adriaandegroot** [comment]
Is there a situation where having `UMASK=0077` on an unencrypted system causes problems? You can tell from the discussion on the mitigation that it'd also be a fix if distro's (Debian) fix the upstream initramfs configuration to always set UMASK=0077.

**Comment by kkofler** [comment]
For what it's worth, Dracut always uses umask 0077, with or without encryption, and it is hardcoded in the code and not configurable at all.

**Comment by apt-ghetto** [comment]
Hi @adriaandegroot and @kkofler, thank you for the answers.

No, there is no immediate problem, that I know of. And I can live with this solution, as long as no other, bigger problems emerge.

It is just something that I discovered, because I have time and we (Lubuntu) have to find a good and secure solution for the existing installations (18.10 and 19.04).
I wrote this issue initially to set it directly in the `initramfs.conf`, which is not a good solution, at least not for Lubuntu, because the config file is not under our control. And it will be overwritten by the configuration files in `/etc/initramfs-tools/conf.d`.
And unfortunately, we cannot assume, that there never will be any "stupid" configuration file with another `UMASK` setting.

The naming of the configuration file could cause a problem, if there is a configuration file, which overrides the `UMASK` setting and has a name, that is lexically greater than `calamares-safe-initramfs.conf`.
To make this problem more improbable, I propose to change the default name to `zz-safe-initramfs.conf`. It might be also an idea, to let the distributor choose a name: for example, that it follows a convention like `99-safe-initramfs.conf`.

And it might be helpful to add some comment to the configuration file.

--- 

Just a little helper script for illustrative purposes:
```perl
#!/usr/bin/perl -w

use warnings;
use strict;
use v5.10;

my @names = qw ! calamares-safe-initramfs.conf
                 99-safe-initramfs.conf
                 zz-safe-initramfs.conf
                 9-safe-initramfs.conf
                 9-calamares-safe-initramfs.conf
                 99-calamares-safe-initramfs.conf
                 ZZ-safe-initramfs.conf
                 09-safe-initramfs.conf
                 zz.conf
               !;

foreach (sort @names) {
    say;
}

```

**Comment by kkofler** [comment]
I'm not convinced we need to get into a business of fighting settings wars over umask. If something explicitly tries to set an insecure umask, that something is broken and ought to be fixed.

**Comment by apt-ghetto** [comment]
> I'm not convinced we need to get into a business of fighting settings wars over umask.

It is not a fight, but it is a discussion about several possibilities.

> If something explicitly tries to set an insecure umask, that something is broken and ought to be fixed.

If "something" sets the UMASK then "something" has reasons for doing that. But "something" may introduce some security issue without knowing it.
I prefer the secure solution over the insecure solution, even if it means, that "something" does not work with an encrypted installation.
Actually, I don't have an example for "something", .

Of course, you can decide not to fix it, and downstream can patch it. On the other hand, we can try to find the best solution here.

**Comment by kkofler** [comment]
What I mean with "fighting settings wars" is trying to manipulate the ordering to make sure our setting prevails over the others. This should really not be necessary.

**Comment by apt-ghetto** [comment]
Closing this issue, because the `UMASK=0777` solution is a good solution.
