### ISSUE TITLE
package-chooser not debian/dep11 compatible

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1212]
**Describe the bug**
The package-chooser expects 

```
# For data provided by AppData XML: the item has an *appdata*
# key which points to an AppData XML file in the local filesystem.
```

this is not a thing on Debian(-derived) systems where a yaml representation known as dep11 is used instead of unpacked xml files. The appstream cache contains the only "unpacked" data stream.

**To Reproduce**
1. try to find the xml file of an appstream component on a debian system

**Expected behavior**
Just use appstream. e.g. `appstreamcli dump org.kde.krita.desktop` if you don't want to use the libraries.

**Screenshots and Logs**
```
$ file /var/lib/app-info/yaml/archive.ubuntu.com_ubuntu_dists_bionic_main_dep11_Components-amd64.yml.gz 
/var/lib/app-info/yaml/archive.ubuntu.com_ubuntu_dists_bionic_main_dep11_Components-amd64.yml.gz: symbolic link to /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_bionic_main_dep11_Components-amd64.yml.g
```

**Additional context**

**Comment by kkofler** [comment]
Well, you can still write the `package-chooser` data directly to the YAML `package-chooser.conf`, using AppData XML is optional.

**Comment by adriaandegroot** [comment]
The AppStream data is annoying to work with because (also):

 - translations are difficult to load
 - most screenshots are going to be remote URLs

But there's a branch *issue-1212* for adding the *option* at least of using *appstream:* as a key in the configuration and getting some data from that.

**Comment by adriaandegroot** [comment]
Closing this one, although I'm still following up for remote URLs in screenshots. The AppStream data is loaded (just once) if you use an appstream: entry in the config file, and uses the upstream description as-is.
