### ISSUE TITLE
2 different languages after new install 

### ISSUE THREAD

**Issue by robin0800** [calamares/calamares#1223]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
After installation there are two languages installed

**To Reproduce**
install using calamaris but change the default language.

**Expected behavior**
the new language should be installed

**Screenshots and Logs**

from /etc/locale.gen

# Locales enabled by Calamares
en_US.UTF-8 UTF-8
en_GB.UTF-8 UTF-8

**Additional context**
As you can see the default language has been included with the new one

**Comment by philmmanjaro** [comment]
Which OS was installed? On Manjaro **en_US** is always installed, regardless which other locales are selected.

**Comment by kkofler** [comment]
In almost all applications, `en_US` is not a real translation, but just uses the default (`C` locale) strings included in the application code itself. (I have only ever encountered 1 or 2 weird applications defaulting to French strings.) So enabling `en_US` by default eats little to no space. Even more so when the other locale is `en_GB`, which, I think, shares several of the tables in the `glibc` locale database.

**Comment by robin0800** [comment]
> Which OS was installed? On Manjaro **en_US** is always installed, regardless which other locales are selected.

Yes and if its manjaro's fault then it should be fixed?

**Comment by agaida** [comment]
Why?

**Comment by robin0800** [comment]
> Why?

I think it is not correct to have two different locales enabled I know you can but would prefer only one.

**Comment by agaida** [comment]
you might be surprised how much locales are enabled in Ubuntu and other distributions by default

**Comment by robin0800** [comment]
> you might be surprised how much locales are enabled in Ubuntu and other distributions by default
> 
> Maybe more clear: It's not an installer thing - that's up to the distribution who use calamares. So i would guess: Not an upstream bug and nothing to fix upstream.

Yes I think You're right, I will raise it with them.
Many Thanks
