### ISSUE TITLE
Please consider making gdm path configurable

### ISSUE THREAD

**Issue by highvoltage** [calamares/calamares#1224]
In Debian, the gdm paths contain "gdm3" instead of the usual "gdm" you find in other distros.

See Debian bug #934504 for more details which also contains a patch to fix this in Debian-based systems: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934504

The patch will work, but it might be better to make it a configurable option upstream.

**Comment by adriaandegroot** [comment]
Seems reasonable-ish, possibly just make that class smarter so it picks gdm3 or gdm, whichever is available.

**Comment by adriaandegroot** [comment]
.. not configurable, but it does look for gdm and gdm3 and picks the right executable and config file.
