### ISSUE TITLE
Install with no swap, incorrect fstab entry

### ISSUE THREAD

**Issue by johnlrussell** [calamares/calamares#1225]
**Describe the bug**
Install done using 'No Swap' option results in entry for swap being placed in /etc/fstab as shown below:
`UUID=                                     swap           swap    defaults,noatime 0 2`

**Expected behavior**

This was observed on two separate distribution installs within 24 hrs of one another - SparkyLinux and EndeavourOS. The install for SparkyLinux was done using automatic partitioning and the install for EndeavourOS was done using manual partitioning. In both installs, the option for no swap was selected, and in both installs the exact same entry was made in fstab. 

I do not have the Calamares version for Sparky, but I was able to find it for Endeavour, and the version there was reported as 3.2.12rc1.20190816-git-master-c627954

**Comment by eznix55** [comment]
Install done using manual partitioning with the Calamares installer in Virtualbox. Created a msdos partition table, created 3Gb swap and 17Gb root partitions. Used Archman Linux 1909 with Calamares version 3.2.13-1. Entry for swap being placed in /etc/fstab as shown below:
UUID= swap swap defaults,noatime 0 2

**Comment by adriaandegroot** [comment]
I couldn't reproduce this one with current master (set to be 3.2.19 shortly). That's a side-effect of the fix for #1316, I think.
