### ISSUE TITLE
netinstall module / netinstall.yaml multiple post/pre-install commands

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1227]
**Problem: 
running more than one command inside netinstall.yaml with post/pre-install option is not possible 
It seems that it do not follow bash here, running two commands with && option is not working and result in confusing:
```
02:36:38 [6]: Running "chroot" ("/tmp/calamares-root-7ac2ew9a", "systemctl", "-f", "enable", "gdm", "&&", "pacman", "-R", "gnome-software") 
02:36:38 [6]: Finished. Exit code: 1 
02:36:38 [6]: Target cmd: ("systemctl", "-f", "enable", "gdm", "&&", "pacman", "-R", "gnome-software") 
02:36:38 [6]: Target output:
systemctl: invalid option -- 'R'
```
**Solution:
define in the documentation what exactly is working here as command:

>   - post-install: an optional command to run within the new system after
>     the group's packages are installed. It will run after each package in
>     the group is installed.
> 

We do try to use this to enable systemd service on installing its corresponding package

// EndeavourOS // Archlinux //
 
Reference:
https://github.com/endeavouros-team/install-scripts/blob/master/netinstall.yaml

**Comment by kkofler** [comment]
`&&` is processed by the shell, so it only works if the command is actually run in a shell.

This should work:
```yaml
  post-install: "sh -c 'systemctl -f enable gdm && pacman -R gnome-software --noconfirm'"
```

(Note the extra double-quoting to quote the shell metacharacters for YAML.)

**Comment by killajoe** [comment]
Thanks, we do not try that one yet, but I will today !

**Comment by killajoe** [comment]
the giving command does not work either...
and in the end, you can leave this closed, as it makes no sense to run the same script after each package will be installed for what we want to do with it... 
What for these options are created at all?

> 
>  pre-install: an optional command to run within the new system before the group's packages are installed. It will run before each package in the group is installed.
> post-install: an optional command to run within the new system after the group's packages are installed. It will run after each package in the group is installed.
