### ISSUE TITLE
[unpackfs] Feature request: Specify custom exclude list

### ISSUE THREAD

**Issue by highvoltage** [calamares/calamares#1229]
Problem:

To use the Debian live images as an example, we unsquash the squashfs filesystem to a new partition, and which includes a bunch of live packages and the calamares installer along with it's dependencies, then we remove those packages again when the installation is done.

Copying all those files just to delete them again takes some unnecessary time, especially on older hardware which still has mechanical drives.

Solution for unpackfs:

At image build time, it's trivial to generate a file list of all the files that are only meant for the live system and include that on the media.

Unpackfs already has a function for excluding some files, if an external file list could be added to this as a configuration option, then it could save a meaningful amount of time during the installation process.

**Comment by adriaandegroot** [comment]
Unfortunately, we use unsquashfs only to list files and then mount the image and use rsync to do the actual copying, so we need (er .. pending a total re-write of the module) to use the rsync approach. It looks like file-exclusion is available, but I'm not clear on how the patterns work exactly.

```
            --exclude-from=FILE     read exclude patterns from FILE
```

**Comment by kkofler** [comment]
The correct option to use is really:
```
     --exclude=PATTERN       exclude files matching PATTERN
```
since you don't want to create a temporary file just to put the exclude patterns in. And IIRC we already have a hardcoded list of `--exclude=`… options, we just need to make it configurable.

**Comment by adriaandegroot** [comment]
The reason I mention `--exclude-from` is that the list of files to exclude is known at image-creation time. You could write that into, say, `/etc/calamares/modules/unpackfs/exclude-list.txt` and then hand that to rsync, rather than writing that list into the Calamares configuration file. In any case, supporting both is trivial.
