### ISSUE TITLE
3.2.12 compile error on openSUSE Leap 15.x (Qt 5.9.x) "no member named 'constKeyValueBegin'; did you mean 'constBegin'?"

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#1236]
Hi, I'm trying to compile Calamares 3.2.12 for openSUSE Leap 15.x and Tumbleweed. For some reason it compiles successfully for Tumbleweed but not for Leap. The error I'm seeing on the openSUSE build service is:

`/home/abuild/rpmbuild/BUILD/calamares-3.2.12/src/libcalamares/locale/TranslatableConfiguration.cpp:43:25: error: 'const QVariantMap {aka const class QMap<QString, QVariant>}' has no member named 'constKeyValueBegin'; did you mean 'constBegin'?`

Here's the complete build log:
https://build.opensuse.org/package/live_build_log/home:sb56637:geckolinux/calamares/openSUSE_Leap_15.1/x86_64

Thanks for the help!

**Comment by kkofler** [comment]
`constKeyValueBegin` was introduced in Qt 5.10, OpenSUSE Leap has Qt 5.9.7.

The official requirement for Calamares is Qt >= 5.9, so Calamares should be fixed.

**Comment by geckolinux** [comment]
Ah, I see. So I take it there's no fix for Qt <5.10 ?

**Comment by philmmanjaro** [comment]
@adriaandegroot can you take a look? Maybe a bump to qt 5.10 is needed or a solution found for qt 5.9

**Comment by geckolinux** [comment]
I'm going to revert to 3.2.11 for now, so if anybody wants to see the failed build logs please look here instead:
https://build.opensuse.org/package/live_build_log/home:sb56637:branches:home:embar-:calamares/calamares/openSUSE_Leap_15.1/x86_64

**Comment by kkofler** [comment]
The fix would be to not use this API in Calamares. But this is not fixed yet. (We all use newer Qt versions, as does the CI, so we had not noticed the problem before your report.)

**Comment by adriaandegroot** [comment]
Qt 5.9 is the LTS version, and that's what Calamares supports, (although I'm not sure that current KDE Frameworks do, or KPMCore, so you may have issues from that side as well). I've modified the code to use Qt 5.9-compatible iterators for the3.2.13 release today.

**Comment by geckolinux** [comment]
Perfect, thanks very much @adriaandegroot for the quick fix!

The rest of the KDE/KF5/Plasma and KPMcore (3.3.0) versions in openSUSE Leap work fine with Calamares.
