### ISSUE TITLE
The user shell is no longer hard-coded to `/bin/bash` but still defaulting to it at archbased install

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1238]
**What happens:**
* Using calamares to install Archlinux (mostly) using their repositories and do not modify system related stuff (only theming) calamares is defaulting to /bin/bash also if we setup **/etc/default/useradd** to use **/bin/zsh**.

* removing **/bin/bash** from:
https://github.com/endeavouros-team/Calamares_current/blob/master/src/modules/users/users.conf
Do not have an effect.

**What should happen:**

 * The user shell is no longer hard-coded to `/bin/bash`,
   but follows the default setting for useradd(8), e.g.
   those set in `/etc/default/useradd`. 

**What else we do find out till now?**
* src/modules/users/UsersViewStep.cpp
contains:
![calamares-bash-1](https://user-images.githubusercontent.com/16797647/64098702-d6c3ea00-cd67-11e9-861d-fd37f5670237.png)

* setting a different shell inside useradd config and remove /bin/bash from users.conf do not have any effect.

* this is how the default useradd config looks like at archlinux:

```
cat /etc/default/useradd
# useradd defaults file for ArchLinux
# original changes by TomK
GROUP=users
HOME=/home
INACTIVE=-1
EXPIRE=
SHELL=/bin/bash
SKEL=/etc/skel
CREATE_MAIL_SPOOL=no
```

**Comment by kkofler** [comment]
You have to set:
```yaml
userShell: ""
```
explicitly, as already documented:
```yaml
# Shell to be used for the regular user of the target system.
# There are three possible kinds of settings:
#  - unset (i.e. commented out, the default), act as if set to /bin/bash
#  - empty (explicit), don't pass shell information to useradd at all
#    and rely on a correct configuration file in /etc/default/useradd
#  - set, non-empty, use that path as shell. No validation is done
#    that the shell actually exists or is executable.
```

**Comment by killajoe** [comment]
Thanks! Again!
Must have overseen this.
