### ISSUE TITLE
install error on Archman linux (main.py for python job initcpio is not readable)

### ISSUE THREAD

**Issue by tulliana** [calamares/calamares#1239]
Hi, my precious teammates. 
install error on Archman linux (main.py for python job initcpio is not readable). Should not need main.py, but it gave an error. (Calamares release 3.2.13) What's missing from my attention? I had no problems with Calamares versions 3.10 and earlier. 

Best regards..

```
07:33:59 [1]: ERROR: Installation failed: 
07:33:59 [6]: - message: "Bad main script file" 
07:33:59 [6]: - details: "Main script file /usr/lib/calamares/modules/initcpio/main.py for python job initcpio is not readable."
```

![Screenshot_2019-09-02_07-37-24](https://user-images.githubusercontent.com/2324162/64112500-4c43b080-cd90-11e9-8d78-9aa77a31d245.png)
[calamares install.log](https://github.com/calamares/calamares/files/3565904/calamares.install.log)

**Comment by adriaandegroot** [comment]
After Calamares 3.2.10, the initcpio module was switched from a Python module (with a `main.py`) to a C++ module. You probably have an older `module.desc` lying around from the Python days, when you should now be using the `module.desc` file that is generated during the build.

**Comment by tulliana** [comment]
thanks for information
