### ISSUE TITLE
GRUB seems to be misinstalled on UEFI hardware

### ISSUE THREAD

**Issue by feren** [calamares/calamares#1244]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

*Mainly reporting this bug as I'm at a loss of where the source of the issue may be*

**Describe the bug**
I've noticed with Feren OS at least that on machines without a /boot/efi/EFI/(chosen-grub-efi-id-here) folder before installing the OS then after installing the OS GRUB will just boot into 'minimal bash-like editing is supported' mode. I've also replicated this issue once on real hardware (Secure Boot off).

**To Reproduce**
1. Install the OS while /boot/efi/EFI/ on the target installation location doesn't have a folder for the chosen GRUB EFI ID name (for Feren OS it's 'feren')
2. Reboot after the installation is done to see a misinstalled GRUB

**Expected behavior**
GRUB will work right away.

**Screenshots and Logs**
I'll get the log later if it's needed - it should be fairly easy to reproduce anyway using any Feren OS ISO.

**Additional context**
Interestingly enough running `grub-install --efi-directory=/boot/efi --target=x86_64-efi --uefi-secure-boot --root-directory=(insert the mounted installed / partition here) --force` on the Live Session after installing `grub-efi-amd64-bin` seems to fix the GRUB installation immediately.
Updating everything to the latest packages available and pre-removing `grub-efi-amd64-bin` from the ISO does nothing effect-wise.

Calamares 3.2.12

Additional Boot Repair Log (also fixes the issue post-installation): http://paste.ubuntu.com/p/yCZHcDgtSZ/

**Comment by abucodonosor** [comment]
Well, we run just grub commands. If you say grub itself does that on your distribution then the bug
maybe on the distro side. 

Can you please upload an installation log with debugging enabled?
Maybe we hit some error before installing grub, or some config var gets broken/empty.

Also, I think @kkofler added some secure boot support sometimes, maybe he has some clues.

**Comment by kkofler** [comment]
Secure Boot support is the `sb-shim` mode, which is not what is being used here.

**Comment by feren** [comment]
@kkofler Is Secure Boot automatically used in Calamares if the package is there, or does it have to be enabled in Calamares configurations?
BTW, `shim-signed` is installed during installation alongside the `grub-efi-amd64-signed` package if Secure Boot is detected before the bootloader module step.

**Comment by feren** [comment]
By chance, does Calamares log the exact command for installing GRUB that it uses, so I can look into the command arguments used?

**Comment by feren** [comment]
Small update: I tried reinstalling GRUB after wiping /boot/efi/EFI again on the installed affected system using the command above, but with `--bootloader-id=feren` added to it on the end, and that seems to be what causes GRUB to be broken... alright, seems like a downstream issue, I'll report it to the Ubuntu Bug Tracker after trying with another ID to see if it breaks in that case too and also change Feren OS's GRUB ID back to 'ubuntu' for now...

**Comment by feren** [comment]
`grub-install /dev/sda --uefi-secure-boot --bootloader-id=feren` Resulted in broken GRUB
`grub-install /dev/sda --uefi-secure-boot --bootloader-id=ubuntu` Resulted in working GRUB
`grub-install /dev/sda --uefi-secure-boot --bootloader-id=testlabel` Resulted in broken GRUB

Reporting it to Launchpad now...

**Comment by feren** [comment]
...and reported. https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1843483

Feel free to mark this issue as 'Downstream' or close it if you feel like doing so, and cheers.

**Comment by kkofler** [comment]
> Is Secure Boot automatically used in Calamares if the package is there, or does it have to be enabled in Calamares configurations?

It has to be enabled explicitly, by changing `efiBootLoader` from `grub` to `sb-shim`. But then it doesn't run `grub-install` at all, but `efibootmgr` to install `shim`, and GRUB is loaded by `shim` directly from the directory (on the EFI System Partition) to which the GRUB package installs it. This implies that the `efiBootloaderId` (which is actually a subdirectory name) is hardcoded in the GRUB package (it has to install the files **somewhere**) and thus downstream remix distributions must not change it (unless they rebuild the GRUB package to use a different directory). It is the same in Fedora: `efiBootloaderId` is always `fedora`, even on Kannolo or any other Fedora Remix. In fact, this is the reason why I introduced a separate setting to begin with, allowing to override the branding's `bootloaderEntryName`.

**Comment by feren** [comment]
Given that explanation, I'll close the issue. Cheers for the explanation.
