### ISSUE TITLE
[SOLVED]Fail run dracut on the target

### ISSUE THREAD

**Issue by peter-kl** [calamares/calamares#1245]
Hello,
Maybe I'm doing something wrong but can someone help  me with this error:
(tumbleweed - opensuse calamres old version 3.2.13))

> 19:54:56 [6]: Starting job "dracut"
19:54:56 [6]: Determining gettext path from ("/home/tuxie", "/usr/bin", "/usr/share/locale")
19:54:56 [6]: .. Found "en_GB" in "/usr/share/locale/en_GB"
19:54:56 [6]: Job file "/usr/lib64/calamares/modules/dracut/main.py"
19:54:56 [6]: Job description from pretty_name "dracut" = "Creating initramfs with dracut."
19:54:56 [6]: Running "chroot" ("/tmp/calamares-root-x9137fj2", "dracut", "-f")
19:54:56 [8]: [JOBQUEUE]: Progress for Job[ 22 ]: 0 % completed
19:54:56 [8]: [JOBQUEUE]: Progress Overall: 78.5714 % (accumulated) + 0 % (this job) = 78.5714 % (total)
19:54:58 [6]: Finished. Exit code: 1
19:54:58 [6]: Target cmd: ("dracut", "-f")
19:54:58 [6]: Target output:
dracut: Executing: /usr/bin/dracut -f
dracut: dracut module 'caps' will not be installed, because command 'capsh' could not be found!
dracut: dracut module 'modsign' will not be installed, because command 'keyctl' could not be found!
dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!
dracut: dracut module 'multipath' will not be installed, because it's in the list to be omitted!
dracut: dracut module 'stratis' will not be installed, because command 'stratisd-init' could not be found!
dracut: dracut module 'cifs' will not be installed, because command 'mount.cifs' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsiadm' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsid' could not be found!
dracut: 95nfs: Could not find any command of 'rpcbind portmap'!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: dracut module 'kiwi-live' cannot be found or installed.
19:54:58 [6]: Skipping non-emergency job "grubcfg"
19:54:58 [6]: Skipping non-emergency job "bootloader"
19:54:58 [6]: Skipping non-emergency job "packages"
19:54:58 [6]: Skipping non-emergency job "removeuser"
19:54:58 [6]: Skipping non-emergency job "umount"
19:54:58 [1]: ERROR: Installation failed:
19:54:58 [6]: - message: "Failed to run dracut on the target"
19:54:58 [6]: - details: "The exit code was 1"
19:54:59 [6]: Calamares will quit when the dialog closes.
19:54:59 [6]: FinishedPage::setUpRestart(), Quit button setup= "never" command= ""
19:55:34 [8]: Shutting down Calamares...
19:55:34 [8]: .. Finished 

> 
Thanks

**Comment by kkofler** [comment]
> `dracut: 95nfs: Could not find any command of 'rpcbind portmap'!`

So the image you are trying to install is missing `rpcbind` or `portmap`, which your `dracut` configuration wants to use.

**Comment by peter-kl** [comment]
Hi 
Ok that `dracut: 95nfs: Could not find any command of 'rpcbind portmap'!` is now done, but I still have the other errors and I do not understand the error `dracut module 'kiwi-live' cannot be found or installed` because to build the live iso that is a base package dracut-kiwi-live.rpm and is installed in the live iso.

**Comment by adriaandegroot** [comment]
This error message is when you're running dracut in the **target** system, so it needs to be installed there as well (not just in the host, live, system).

**Comment by peter-kl** [comment]
Hi
@adriaandegroot 
So just to confirm, and sorry for wasting your time with basic stuff, I need to edit the module _packages.conf_:

 

```
......
backend: zypp
.....
operations:
  - install:
    - dracut-kiwi-live

```

**Comment by kkofler** [comment]
Sure, this solves the problem, but it is not the correct fix. It will fail if there is no Internet connection. The required packages should be included in the base image during the image compose, not installed during the Calamares-driven installation.

**Comment by peter-kl** [comment]
Hi

> ...should be included in the base image during the image compose...

Yes and they were included, darcut-kiwi-live is a base package already in the kiwi config.xml
```
...
<packages type="iso">
        <package name="gfxboot-branding-openSUSE"/>
        <package name="dracut-kiwi-live"/>
    </packages>
          ...
</image>
  
```

**Comment by kkofler** [comment]
I guess this needs to be in a `<packages type="image">` rather than a `<packages type="iso">` to actually end up on the base image and not on some live-only overlay.

**Comment by peter-kl** [comment]
Hello,
So I was just updating a more than one year old image  with the **same configs**  and all was ok I was able to install it using the same calamres version.
I think this error of dracut as nothing to do with it maybe something went wrong during the process of the iso creation.
I'm going to wait  until I get some time to work this thing out.
Thanks.

**Comment by vinyanalista** [comment]
Hi, @peter-kl. I solved that problem for [Linux Kamarada](https://github.com/kamarada/Linux-Kamarada-GNOME/issues/49).

Besides adding the `rpcbind` package to the [image](https://github.com/kamarada/Linux-Kamarada-GNOME/commit/f0a8c8b848cb3b9760df078715045e197bb0ea79#diff-9548941214d8b68f631a533b85693f25R105), I had to do one action during installation: delete the file `/etc/dracut.conf.d/02-livecd.conf` from the installed system, which was causing dracut to try to include the `kiwi-live` module in initramfs.

I already had a post install script, so I moved the Calamares `shellprocess` module to be executed prior to the `dracut` module in my [settings.conf](https://github.com/kamarada/branding/commit/01253b958af17bdf29c00e52f6948efbc550bacf). In that [script](https://github.com/kamarada/Linux-Kamarada-GNOME/commit/6c122673fd036fd3f571c0a52769950d717add97), I delete the file `/etc/dracut.conf.d/02-livecd.conf`.

Also note that the `dracut-kiwi-live` package does not make sense on an installed system. So, I kept removing it in my [packages.conf](https://github.com/kamarada/branding/blob/01253b958af17bdf29c00e52f6948efbc550bacf/calamares/packages.conf#L150).

Thank you for reporting me that bug! I hope my findings help you and anyone else who need them.

**Comment by peter-kl** [comment]
Hello all
@vinyanalista the new test made today there is no more `/etc/dracut.conf.d/02-livecd.conf` but I keep getting same error - funny thing if I update for more than one hour an one year old image it works fine out-of-box maybe I missing something in the configs kiwi.
Here is my pastebin of the calamares log from [today](https://pastebin.com/DYWdPWUy)

**Comment by vinyanalista** [comment]
I see:

```
dracut: dracut module 'kiwi-live' cannot be found or installed.
```

That was appearing to me.

Did you see what I did to solve that problem for me?

Please, take a look at the 3 commits mentioned on this issue: kamarada/Linux-Kamarada-GNOME#49

Is the source code of your image available?

**Comment by kevinsmia1939** [comment]
> I see:
> 
> ```
> dracut: dracut module 'kiwi-live' cannot be found or installed.
> ```
> 
> That was appearing to me.
> 
> Did you see what I did to solve that problem for me?
> 
> Please, take a look at the 3 commits mentioned on this issue: [kamarada/Linux-Kamarada-GNOME#49](https://github.com/kamarada/Linux-Kamarada-GNOME/issues/49)
> 
> Is the source code of your image available?

 did have rpcbind install on the live ISO, but still have "dracut module 'kiwi-live' cannot be found or installed."
Not sure what happen.

According to your commit, I have to add rcpbind, remove /etc/dracut.conf.d/02-livecd.conf just before starting calamares, but still the problem is still there.

My config.xml is like this:

```
<?xml version="1.0" encoding="utf-8"?>

<image schemaversion="6.8" name="BananaOS">
    <description type="system">
        <author>Banana</author>
        <contact>Banana</contact>
        <specification>
            Banana
        </specification>
    </description>
    <preferences>
        <type image="iso" primary="true" flags="overlay" hybrid="true" hybridpersistent_filesystem="ext4" hybridpersistent="true"/>
        <version>1.99.1</version>
        <packagemanager>zypper</packagemanager>
        <locale>en_US</locale>
        <keytable>us</keytable>
        <timezone>Asia/Bangkok</timezone>
        <rpm-excludedocs>true</rpm-excludedocs>
        <rpm-check-signatures>false</rpm-check-signatures>
        <bootsplash-theme>bgrt</bootsplash-theme>
        <bootloader-theme>openSUSE</bootloader-theme>
    </preferences>
    <preferences>
        <type image="vmx" filesystem="ext4" bootloader="grub2" kernelcmdline="splash" firmware="efi"/>
        <type image="oem" filesystem="ext4" initrd_system="dracut" installiso="true" bootloader="grub2" kernelcmdline="splash" firmware="efi">
            <oemconfig>
                <oem-systemsize>2048</oem-systemsize>
                <oem-swap>true</oem-swap>
                <oem-device-filter>/dev/ram</oem-device-filter>
                <oem-multipath-scan>false</oem-multipath-scan>
                <oem-unattended>false</oem-unattended>
            </oemconfig>
            <machine memory="512" guestOS="suse" HWversion="4">
                <vmdisk id="0" controller="ide"/>
                <vmnic driver="e1000" interface="0" mode="bridged"/>
            </machine>
        </type>
    </preferences>
    <users>
        <user password="1234" pwdformat="plain" home="/root" name="root" groups="root"/>
        <user password="1234" pwdformat="plain" home="/home/tux" name="tux" groups="tux"/>
    </users>
    <repository type="yast2" alias="Tumbleweed-Oss" imageinclude="true" priority="99">
        <source path="http://download.opensuse.org/tumbleweed/repo/oss"/>
    </repository>
    <repository type="yast2" alias="openSUSE-Tumbleweed-Non-Oss" imageinclude="true" priority="99">
        <source path="http://download.opensuse.org/tumbleweed/repo/non-oss/"/>
    </repository>
    <repository type="yast2" alias="openSUSE-Tumbleweed-Update" imageinclude="true" priority="99">
        <source path="http://download.opensuse.org/update/tumbleweed/"/>
    </repository>
    <repository type="yast2" alias="Science" imageinclude="true" priority="90">
        <source path="https://download.opensuse.org/repositories/science/openSUSE_Tumbleweed/"/>
    </repository>
    <repository type="yast2" alias="MultiMedia" imageinclude="true" priority="100">
        <source path="https://download.opensuse.org/repositories/multimedia:/apps/openSUSE_Tumbleweed/"/>
    </repository>
    <repository type="rpm-md" alias="VSCodium" imageinclude="true" priority="99">
        <source path="https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/rpms/"/>
    </repository>
    <repository type="rpm-md" alias="NVIDIA" imageinclude="true" priority="99">
        <source path="https://download.nvidia.com/opensuse/tumbleweed/"/>
    </repository>
    <packages type="image" patternType="plusRecommended">
        <namedCollection name="base"/>    
        <namedCollection name="enhanced_base"/>    
        <namedCollection name="x11"/>  
        <namedCollection name="kde"/>  
        <namedCollection name="kde_plasma"/>
        <namedCollection name="yast2_basis"/>
        <package name="calamares"/>
        <package name="update-desktop-files"/>
        <package name="desktop-data-openSUSE-extra"/>
        <package name="yast2-qt-branding-openSUSE"/>
        <package name="yast2-control-center"/>
        <package name="yast2-fonts"/>
        <package name="htop"/>
        <package name="ksystemlog"/>
        <package name="testdisk"/>
        <package name="kate"/>
        <package name="psmisc"/>
        <package name="command-not-found"/>
        <package name="sudo"/>
        <package name="libsecret-1-0"/>
        <package name="iproute2"/>
        <package name="python2-SecretStorage"/>
        <package name="xorg-x11-server"/>
        <package name="fuse-exfat"/>
        <package name="exfat-utils"/>
        <package name="python"/>
        <package name="perl"/>
        <package name="patterns-openSUSE-base"/>
        <package name="grub2-branding-openSUSE"/>
        <package name="ifplugd"/>
        <package name="iputils"/>
        <package name="vim"/>
        <package name="grub2"/>
        <package name="grub2-i386-pc"/>
        <package name="grub2-x86_64-efi" arch="x86_64"/>
        <package name="syslinux"/>
        <package name="lvm2"/>
        <package name="plymouth"/>
        <package name="plymouth-theme-bgrt"/>
        <package name="plymouth-dracut"/>
        <package name="fontconfig"/>
        <package name="fonts-config"/>
        <package name="curl"/>
        <package name="w3m"/>
        <package name="cabextract"/>
        <package name="tar"/>
        <package name="unzip"/>
        <package name="gzip"/>
        <package name="parted"/>
        <package name="openssh"/>
        <package name="iproute2"/>
        <package name="sensors"/>
        <package name="libQt5Sensors5"/>
        <package name="libsensors4"/>
        <package name="hddtemp"/>
        <package name="less"/>
        <package name="bash-completion"/>
        <package name="dhcp-client"/>
        <package name="which"/>
        <package name="kernel-default"/>
        <package name="timezone"/>
    </packages>
    <packages type="iso">
        <package name="gfxboot-branding-openSUSE"/>
        <package name="dracut-kiwi-live"/>
    </packages>
    <packages type="oem">
        <package name="gfxboot-branding-openSUSE"/>
        <package name="dracut-kiwi-oem-repart"/>
        <package name="dracut-kiwi-oem-dump"/>
    </packages>
    <packages type="bootstrap">
        <package name="udev"/>
        <package name="filesystem"/>
        <package name="glibc-locale"/>
        <package name="cracklib-dict-full"/>
        <package name="ca-certificates"/>
        <package name="ca-certificates-mozilla"/>
        <package name="openSUSE-release"/>
    </packages>
</image>
```

and config.sh

```
#!/bin/bash
#================
# FILE          : config.sh
#----------------
# PROJECT       : OpenSuSE KIWI Image System
# COPYRIGHT     : (c) 2006 SUSE LINUX Products GmbH. All rights reserved
#               :
# AUTHOR        : Marcus Schaefer <ms@suse.de>
#               :
# BELONGS TO    : Operating System images
#               :
# DESCRIPTION   : configuration script for SUSE based
#               : operating systems
#               :
#               :
# STATUS        : BETA
#----------------
#======================================
# Functions...
#--------------------------------------
test -f /.kconfig && . /.kconfig
test -f /.profile && . /.profile

#======================================
# Greeting...
#--------------------------------------
echo "Configure image: [$kiwi_iname]..."

#======================================
# Mount system filesystems
#--------------------------------------
baseMount

#======================================
# Setup baseproduct link
#--------------------------------------
suseSetupProduct

#======================================
# Add missing gpg keys to rpm
#--------------------------------------
suseImportBuildKey 
rpm --import /keys/nvidia.key
rpm --import /keys/codium.gpg
rpm --import /keys/geo.key
rpm --import /keys/graphics.key
rpm --import /keys/multimedia.key
rpm --import /keys/nvidia.key
rpm --import /keys/opensuse-oss.key
rpm --import /keys/packman.key
rpm --import /keys/science.key
#======================================
# Disable services
#--------------------------------------
baseRemoveService wicked
baseRemoveService wickedd
baseRemoveService wickedd-auto4
baseRemoveService wickedd-dhcp4
baseRemoveService wickedd-dhcp5
baseRemoveService wickedd-nanny
#======================================
# Activate services
#--------------------------------------
suseInsertService sshd
baseInsertService apparmor
baseInsertService appstream-sync-cache
baseInsertService auditd
baseInsertService avahi-daemon
baseInsertService bluetooth
baseInsertService cron
baseInsertService display-manager
baseInsertService firewalld
baseInsertService getty@tty1
baseInsertService haveged
baseInsertService irqbalance
baseInsertService iscsi
baseInsertService kbdsettings
baseInsertService mcelog
baseInsertService ModenManager
baseInsertService NetworkManager
baseInsertService NetworkManager-dispatcher
baseInsertService NetworkManager-wait-online
baseInsertService nscd
baseInsertService purge-kernels
baseInsertService smartd
baseInsertService systemd-remount-fs
baseInsertService systemd-timesyncd
baseInsertService YaST2-Firstboot
baseInsertService YaST2-Second-Stage

#======================================
# Setup default target, multi-user
#--------------------------------------

#==========================================
# remove package docs
#------------------------------------------
rm -rf /usr/share/doc/packages/*
rm -rf /usr/share/doc/manual/*
rm -rf /opt/kde*

#======================================
# only basic version of vim is
# installed; no syntax highlighting
#--------------------------------------
sed -i -e's/^syntax on/" syntax on/' /etc/vimrc

#======================================
# SuSEconfig
#--------------------------------------
baseUpdateSysConfig /etc/sysconfig/windowmanager DEFAULT_WM plasma5
baseUpdateSysConfig /etc/sysconfig/displaymanager DISPLAYMANAGER sddm
baseUpdateSysConfig /etc/sysconfig/displaymanager DISPLAYMANAGER_AUTOLOGIN tux
baseSetRunlevel 5
suseConfig

#==========================================
# configure flatpak
#------------------------------------------
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -vv --ostree-verbose flathub net.openra.OpenRA
flatpak install -vv --ostree-verbose flathub com.slack.Slack
#======================================
# Remove yast if not in use
#--------------------------------------


#======================================
# Umount kernel filesystems
#--------------------------------------
baseCleanMount

exit 0
```

**Comment by vinyanalista** [comment]
> 
> According to your commit, I have to add rcpbind, remove /etc/dracut.conf.d/02-livecd.conf just before starting calamares, but still the problem is still there.
> 

I use the `shellprocess` Calamares module to run a post install script, which is [`/usr/sbin/kamarada-postinstall.sh`](https://github.com/kamarada/Linux-Kamarada-GNOME/blob/15.1-Beta-Build16.1/root/usr/sbin/kamarada-postinstall.sh#L33-L34). That script deletes `/etc/dracut.conf.d/02-livecd.conf`. Also, I use the `shellprocess` module before the `dracut` module in my [`/usr/share/calamares/settings.conf`](https://github.com/kamarada/branding/blob/15.1-Beta-Build6.1/calamares/settings.conf#L122-L123).

Please note that `02-livecd.conf` is not removed "just before starting Calamares", but during installation, after the filesystem has been created and Calamares is performing post install configuration. It is removed just before the `dracut` module is run.

**Comment by kevinsmia1939** [comment]
@vinyanalista 

> I use the shellprocess Calamares module to run a post install script

So I also need shellprocess.conf in the /usr/share/calamares/modules as well right?
I was looking through your repo, but didn't found the said modules, what is it look like? Thanks.

**Comment by kevinsmia1939** [comment]
The content of shellprocess.conf is like this?
```
dontChroot: false
timeout: 10
script:

    - "/usr/sbin/kamarada-postinstall.sh"

```

**Comment by kevinsmia1939** [comment]
I got 
```
WARNING: YAML parser error yaml-cpp: error at line 122, column 3: end of map not found in "usr/share/calamares/settings.conf"
FATAL ERROR: branding component not set in settings.conf
```

**Comment by vinyanalista** [comment]
@kevinsmia1939, the calamares package on openSUSE Leap 15.1 repos (version 3.1.11) does not have the shellprocess module.

"My" calamares package is a fork of the package by @embar- here:

https://build.opensuse.org/package/show/home:embar-:calamares/calamares

It is the latest version (3.2.14), which has the shellprocess module.

**Comment by peter-kl** [comment]
Eureka !!
So I was trying to delete `/etc/dracut.conf.d/02-livecd.conf` in the wrong place - the live iso itself (idiota!!) - after running calamares (`sudo -E calamares -d`) with error, check the log for _/tmp/root-calamares-xxxx_ make the changes by @vinyanalista there and then run calamares again in the same partition but now without format - select keep root - et voilá it's working.
Now I can rebuild the live image again with the certain that with those changes it will work. 
Thanks everyone and special to @vinyanalista _Obrigada_
@kevinsmia1939 you can also search for a calamares  package in the [openbuild-suse](https://build.opensuse.org/search?name=1&package=1&project=1) 
Solved!!

**Comment by adriaandegroot** [comment]
With the *exclude* settings in the *unpackfs* module that will land with 3.2.15 you should be able to simplify this again: you don't have to unpack that config file to the target system in the first place! (3.2.15 will land in an hour or so)
