### ISSUE TITLE
displaymanager: explicit executable key moot

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1248]
**Describe the bug**
displaymanager wants an `executable` key for the `defaultDesktopEnvironment` it's purpose entirely eludes me and likely does more bad than good (e.g. easily breaks if the exec changes #1246)

**To Reproduce**
1. have a desktop file change exec key
2. session is no longer found because the old (in calamares hardcoded) executable path no longer exists

**Expected behavior**
stuff still works even when a session file changes its executable

**Additional context**
Calamares should really only require the desktopFile name, then look for the desktop file in the well-known paths, read it's `TryExec` key and use that to determine whether a given entry is valid. As a somewhat less spec-compliant option you could fall back to reading the `Exec` key to determine whether a given session is valid, BUT mind that the Exec entry needs running through a shell parser to "guess" its actual executable because "shelly" expressions are allowed in Exec.

https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

**Comment by kkofler** [comment]
Some display managers (of those we currently support, this is the case for LXDM) require the raw executable path for the desktop environment rather than the `.desktop` file to select the session.

**Comment by apachelogger** [comment]
So at best it'd be optional, although I would also argue that for LXDM the exec should (by default) be obtained from the desktop file, not hardcoded in cala.

**Comment by adriaandegroot** [comment]
This was fixed with d2899d4beeb65537383fe600689869b1f62c227f (which also did #1247)

**Comment by apachelogger** [comment]
displaymanager.conf documentation needs updating I think (:

**Comment by adriaandegroot** [comment]
This wasn't fixed at all and the code is all so tangled  that I don't want to think about it. All the fixing that went into #1247 was for **finding** DE's, based on the hard-coded path of an executable and the name of a .desktop file (which might contain a TryExec key that should be used instead of the executable).

What goes into the *defaultDesktopEnvironment* is fed as-is to the DM configuration part, **most** of them don't even configure a default (e.g. Calamares's SDDM-configurator has no support for it), and the ones that do only use the *desktopFile* key.

**Comment by kkofler** [comment]
For SDDM, the lack of support for a configurable default desktop environment is a longstanding upstream SDDM issue: https://github.com/sddm/sddm/issues/346

**Comment by kkofler** [comment]
Or this one: https://github.com/sddm/sddm/issues/326
(The former is for a per-user setting, the latter for a systemwide default, SDDM has neither.)
