### ISSUE TITLE
Install error on Manjaro KDE (OpenGL related)

### ISSUE THREAD

**Issue by MatthiasH0** [calamares/calamares#1250]
Hi everyone, I am very new to GitHub.
So I have tried to install Manjaro 18.04 KDE lately, booted from a live USB, however the installer failed multiple times. Basically I can go through all the steps, but once I click install and then confirm install, it doesn't do anything.
I have described the error in this forum here:
 https://forum.manjaro.org/t/manjaro-kde-wont-install-from-live-usb/104520/6

I have been asked to report this bug here by a member of the community, I am quite inexperienced with Linux, but maybe there is a fix for this.
I have done sudo -E calamares -d during the installation process and it gives me the following terminal output, I think the error comes right at the end of the output,  I am unsure if it's okay to post a pastebin here, but this would be it:
https://pastebin.com/CnedYYrn

Any advice on why this would happen is greatly appreciated.

**Comment by philmmanjaro** [comment]
Hmm, you error out with:

> 02:17:13 [0]: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Aborted

Might be some issue with the selected hardware. **Calamares** works in general. So posting an issue about it here, might only sense if it is an issue related to the code of **Calamares** itself.

Also you use our ISO in 18.1 release and not 18.0.4. Did you tried the older version of Manjaro too?
Always search our forums first. A similar problem was already posted. See [here](https://forum.manjaro.org/t/mhwd-bumblebee-340x-failed-to-create-opengl-context-for-format-qsurfaceformat-version-2-0/44576).

You may want to try it again with free drivers and not the proprietary ones. Also check what `mwhd` and `mhwd -li` might tell you. Hybrid cards are always tricky to handle.

The question here is: what part of **Calamares** needs OpenGL. Most likely the slideshow might need it.

**Comment by adriaandegroot** [comment]
I'm going to close this one, @MatthiasH0 , as "needs info; handle downstream." Please follow Phil's suggestions (he's really good at collecting things in Manjaro and bringing them back to me as needed)
