### ISSUE TITLE
Boost.Python error in "displaymanager" stage:  'str' object has no attribute 'append'

### ISSUE THREAD

**Issue by embar-** [calamares/calamares#1253]
I installed Clamares 3.2.14 in openSUSE Leap 15.1 Linux. During LiveCD installation via Calamares, I get Boost.Python error in task "displaymanager":

```
<class 'AttributeError'>
'str' object has no attribute 'append'

Traceback:
File "/usr/lib64/calamares/modules/displaymanager/main.py", line 895, in run
    dm_names.append("sysconfig")
```

In /usr/share/calamares/modules/displaymanager.conf I have options:
```
displaymanagers:
    None
basicSetup: false
sysconfigSetup: true
```

I have these boost packages installed:
```
> zypper se -i -s boost
Įkeliami saugyklų duomenys...
Skaitomi įdiegti paketai...

B | Pavadinimas                | Tipas   | Versija          | Arch   | Saugykla   
--+----------------------------+---------+------------------+--------+------------
i | boost-license1_66_0        | paketas | 1.66.0-lp151.4.5 | noarch | 15.1 atviri
i | libboost_python-py3-1_66_0 | paketas | 1.66.0-lp151.4.6 | x86_64 | 15.1 atviri
i | libboost_system1_66_0      | paketas | 1.66.0-lp151.4.5 | x86_64 | 15.1 atviri
i | libboost_thread1_66_0      | paketas | 1.66.0-lp151.4.5 | x86_64 | 15.1 atviri

```
![Screenshot_20191003_104857](https://user-images.githubusercontent.com/1218781/66108557-8391c100-e5cb-11e9-9ca0-b2cf06e80fdd.png)

**Comment by embar-** [comment]
I attach full installation log.
[calamares3.2.14.log.txt](https://github.com/calamares/calamares/files/3685147/calamares3.2.14.log.txt)

**Comment by adriaandegroot** [comment]
```
displaymanagers:
    None
```
that is not a valid configuration for displaymanagers. It must be a list of strings (or empty), so if you want to avoid displaymanagers, use

```
displaymanagers: []
```

**Comment by embar-** [comment]
If I change settings into 

`displaymanagers: []`

then I get error:

```
No display managers selected for the displaymanager module.
The displaymanagers list is empty or undefined in bothglobalstorage and displaymanager.conf.
```

in openSUSE Linux, display managers should not be configured via /usr/share/calamares/modules/displaymanager.conf "displaymanagers:" option at all; it should be configured via /etc/sysconfig/displaymanager configuration file. That's why we set option:

`sysconfigSetup: true`

See screenshot and  new logs below:

![VirtualBox_Calamares_no_display_manager](https://user-images.githubusercontent.com/1218781/66251946-a0123280-e75e-11e9-8f18-da3eccbffb9c.png)

[calamares_log.txt](https://github.com/calamares/calamares/files/3692978/calamares_log.txt)

**Comment by embar-** [comment]
P.S. Calamares 3.1.11 worked just fine in this case. Seems that regression introduced in Calamres 3.2 series (3.2.2?) with https://github.com/calamares/calamares/commit/ebae7e1f476a28bd57b7d83d175ad7e156b875e1 

![paveikslas](https://user-images.githubusercontent.com/1218781/66252162-c33de180-e760-11e9-8e99-11dd573f4110.png)

![paveikslas](https://user-images.githubusercontent.com/1218781/66252150-8f62bc00-e760-11e9-9290-8399915211a4.png)

**Comment by embar-** [comment]
For testing purposes, you can use [this](http://lietukas.lt/ISO/testavimui/Lietukas_15.1.x86_64-15.1.0rc_installer_fails.iso) LiveDVD/LiveUSB ISO image. It is based on openSUSE Leap 15.1 and contains Calamares 3.2.14.

**Comment by embar-** [comment]
This bug seems to be duplicate of https://github.com/calamares/calamares/issues/582

**Comment by embar-** [comment]
Thanks! I applied your patch I tested Calamares in openSUSE based appliance. Now installer works again and success to set autologin!

**Comment by embar-** [comment]
For testing purposes you can also grab openSUSE based ISO with patched Calamares from [here](https://download.opensuse.org/repositories/home:/embar-:/Lietukas/images/iso/?C=M;O=D). Please select ISO after 2019-10-07. These images will be automatically rebuilded after any change in relevant package.
