### ISSUE TITLE
SetPasswordJob generates salt insecurely

### ISSUE THREAD

**Issue by cyveris** [calamares/calamares#1254]
This was originally introduced in commit f1ab9df7ee3a03e579fde535a9b7d16d789478e6, which was intended to address a previous salt generation issue.

The salt generation routine (function make_salt() in src/modules/users/SetPasswordJob.cpp) uses an implementation of the Mersenne Twister (MT) pseudorandom number generator (PRNG) to generate the salt value. (This edges up against "thou shalt not roll your own crypto.")

None of the variants of the MT PRNG algorithm are cryptographically secure, with a singular exception that is patent-encumbered (and is not the one in use here). Usage of a weak PRNG is covered under CWE-338, Use of Cryptographically Weak Pseudo-Random Number Generator. [1]

This function needs to be rewritten so as to derive its randomness from a cryptographically-secure source. There are a number of ways one could accomplish this, such as sourcing directly from /dev/urandom, libsodium, etc.

[1] https://cwe.mitre.org/data/definitions/338.html

**Comment by abucodonosor** [comment]
How /dev/urandom is more secure regarding cryptography entropy?

**Comment by theciaguy** [comment]
By the fact that the Mersenne Twister algorithm is explicitly stated to be unsuitable for cryptographic use, and the /dev/urandom device is explicitly stated in `man 4 random` to be the preferred source of cryptographically-secure pseudorandom data.

> The /dev/random interface is considered a **legacy interface**, and **/dev/urandom is preferred and sufficient in all use cases**, with the exception of applications which require randomness during early boot time; for these applications, getrandom(2) must be used instead, because it will block until the entropy pool is initialized. (Emphasis mine.)

**Comment by adriaandegroot** [comment]
PRs are welcome. I'd suggest adding Random.cpp to src/libcalamares/utils, as near as I can tell a single function QByteArray getMeSomeRealRandomStuff(size_t count) is all that's needed. Then that can be used for the salt and also src/modules/machineid/Workers.cpp can be refactored to use that .. I'll note that there is already an implementation squirreled away in createNewEntropy().

**Comment by cyveris** [comment]
Commit 02e5e0de5ee43d33b860a00df490dc32137d604b includes a warning about `/dev/urandom` being "low quality" (lines 74-77).

This is inconsistent with the contents of `man 4 random`, which states that `/dev/urandom is preferred and sufficient in all use cases with the exception of applications which require randomness during early boot time`. Calamares is not one of those cases.
