### ISSUE TITLE
Erase Disk should be available at all times

### ISSUE THREAD

**Issue by feren** [calamares/calamares#1258]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I want to erase the disk of a disk and cannot directly choose Erase Disk because of a certain partition table structure that makes Erase Disk non-choosable.

**Describe the solution you'd like**
I'd like Erase Disk to ALWAYS be visible like Manual Partitioning is so that the user can ALWAYS choose the OS recommended partition structure regardless of their partition table structure.

**Describe alternatives you've considered**
You could say Manual Partitioning does the job, but this is not only a complicated way to just Erase Disk and install OS on new partitions but it also isn't obvious what partitions the OS recommends be placed on the erased disk.
Furthermore every other installer I've tried (Ubiquity, Anaconda, etc.) shows Erase Disk at all times, so how come can't Calamares?

**Comment by arcolinuxz** [comment]
I recognize this on ArcoLinux and second this feature request.

It happens now and again that calamares crashes on partitioning.

What if we can do what we then later do on gparted is behind a button.
Start from a clean slate and erase everything before partitioning.
I do not even a button. It can be programmed in automatically.
First full zap of all partitions.

**Comment by wxl** [comment]
It's often the case that something is mounted on the drive (e.g. swap; Ubuntu automounts them) that causes the problem. Is this not the case for you?

**Comment by arcolinuxz** [comment]
Can we add a 

`wipefs -a /dev/sda`

or

`sgdisk -Z /dev/sda`

to the code (if the commands are available) to completely wipe the harddisk (if that was the choice of the user) and if you are on Arch Linux.

We have tested 35 isos for ArcoLinux 20.1.4 and on a total of 35 isos we have around 3 crashes and that number corresponds with the 19.12 release.

About 10% of the installations crash. If you restart calamares immediately it often installs the system but not always. The users know they have to open up gparted and delete all partitions.

Can calamares handle this with the proposed code?

If on Arch Linux and if the user asks to do a clean install and if the commands are available then first delete all partitions. 

I am sure we will not see any more crashes then. 

These crashes occur on real metal and on virtualbox. I have not found any logic behind them yet and we have observed them already several months.

**Comment by wxl** [comment]
I'm not sure @feren was talking about a crash. I wasn't. You should file a seperate bug with logs.

**Comment by arcolinuxz** [comment]
I still may. But an erase disk button seems like a super idea if that is what this topic is about.

**Comment by feren** [comment]
This issue was created on the topic of adding an Erase Disk button no matter what the partition layout is and what the table is at that current time.

**Comment by wxl** [comment]
@feren It is typically shown unless the target drive has a mounted partition. Can you confirm in your case that this is *not* true? If so, we have a new bug. Otherwise, we have a known problem.

**Comment by feren** [comment]
@wxl It appears to be as you've stated, now. It'd be better though if Calamares maybe mentioned that there are mounted partitions hence why the options aren't there though as I didn't know that's intended behaviour for when partitions are currently mounted.

**Comment by wxl** [comment]
@feren if you'd like to further discuss the issue see the known problem https://github.com/calamares/calamares/issues/860

@arcolinuxz since this is closed and it sounds like you have a unique issue, you really should file a new one.
