### ISSUE TITLE
[Gentoo] 3.2.12: Boost.Python error in job 'unpackfs' class "KeyError" line 334

### ISSUE THREAD

**Issue by realKennyStrawn93** [calamares/calamares#1260]
**Describe the bug**
All attempts to configure the unpackfs module using configuration files similar to, e.g. [the configuration that Sabayon uses](https://github.com/Sabayon/sabayon-distro/blob/master/app-misc/calamares-sabayon-base-modules/files/modules-conf/modules/unpackfs.conf) but with different filenames fail with the error described in the title.

**To Reproduce**
1. Use [this shell script](https://github.com/calamares/calamares/files/3773349/customize.sh.txt) as "livecd/fsscript" in a Gentoo Catalyst livecd-stage2.spec file (make sure to run `mv customize.sh.txt customize.sh && chmod a+x customize.sh` on your local system before performing this step)
2. Boot the live image that Catalyst creates via step 1
3. Attempt to install
4. This happens:
![Screenshot from 2019-10-25 11-22-52](https://user-images.githubusercontent.com/3030773/67595745-2695b080-f71c-11e9-8f74-94cecd0b5fbd.png)
Note that unpackfs.conf is open in gedit on the same desktop as the failed installer and, with the only glaring exception of the file to unsquash, it, again, is virtually identical to [Sabayon's](https://github.com/Sabayon/sabayon-distro/blob/master/app-misc/calamares-sabayon-base-modules/files/modules-conf/modules/unpackfs.conf).

**Expected behavior**
Shouldn't run into any problems given how many changes to the configuration files the attached shell script is designed to make.

**Screenshots and Logs**
Screenshot: see above
Log: [session.log](https://github.com/calamares/calamares/files/3773322/session.log)
Ebuild: [calamares-3.2.12.ebuild](https://github.com/calamares/calamares/files/3773354/calamares-3.2.12.ebuild.txt)

**Additional context**

**Comment by realKennyStrawn93** [comment]
[Here](https://github.com/realKennyStrawn93/TriggerLinux) is the rest of the files that go with the fsscript in question if you’re either curious or short on time.

**Comment by realKennyStrawn93** [comment]
Related Gentoo bug: https://bugs.gentoo.org/698430

**Comment by abucodonosor** [comment]
I have no idea what script you are talking about but from your log
is clear what is wrong. Your calamares is not configured at all.

You have to provide valid configuration files. 

Look for these in your log:
No config file for "<SOMETHING>" found anywhere at ....

And add valid configurations for what you are using.

In short, that is not a bug.

**Comment by abucodonosor** [comment]
Ok, quick looked that script. 

Besides, it will break all the time, this is not the proper way to add/fix/change configurations, ( a single space or tab too much etc will break hell ),
you put these in /usr/lib64 in that script while your calamares expect the files, 
either in /etc or in /usr/share.

**Comment by realKennyStrawn93** [comment]
That’s a bug with the ebuild then because the ebuild installs the modules themselves (that is, the Python code for them) in the /usr/lib64 location. Unless, of course, one needs to `mkdir /etc/calamares/modules` and install the module config files in that location — trying that next.

**Comment by kkofler** [comment]
Config files go to a different place than binaries or scripts in the FHS.

**Comment by realKennyStrawn93** [comment]
Yeah, that’s what I figured. Alright, closing for that reason
