### ISSUE TITLE
Ambiguous error message in username validation

### ISSUE THREAD

**Issue by nslxndr** [calamares/calamares#1261]
**Describe the bug**
If username does not match the specified regexp, then validation error message may sound ambiguous in some cases.

1. Type `123` into username field.
2. See error message: _Your username contains invalid characters. Only lowercase letters and numbers are allowed._

The given username meets all requirements presented in hint text. It does not contain any invalid character. It just does not to follow the expected format, because does not contain all required character class. I think that specific error message pointless and unhelpful in the above case.

**Expected behavior**
I expect a clear, more general or more specific error message. Because red X already marks the username invalid, I suggest a more detailed hint text as error message: _Your username must begin with a letter or underscore, followed by letters, digits, underscores or hyphens._

**Screenshot**
![VirtualBoxVM_gIjnnnqhnj](https://user-images.githubusercontent.com/3685156/67595024-f5da6900-f765-11e9-9544-c38fc763cb78.png)

**Comment by adriaandegroot** [comment]
To a **tiny** extent this is "unfixable" because the distro can set username validation rules, which may not match the regexp Calamares uses anyway. But, you're quite right that the message does not match the RE Calamares has.

**Comment by adriaandegroot** [comment]
I think this had best be split into multiple cases to explain the "must begin" and "must contain" better. There's work in the *bill-auger-patch-6* branch.
