### ISSUE TITLE
Feature Request: Optional configuration of all jobs textual output to the progress process

### ISSUE THREAD

**Issue by salientos** [calamares/calamares#1262]
**Is your feature request related to a problem? Please describe.**

The current implemenatation doesn't really explain to the end user what is happening during the installation process. Esoteric return strings do not help when things go wrong. 

**Describe the solution you'd like**

An optional configuration of the "Pretty Name" text output of every job which outputs to the progress status.

**Describe alternatives you've considered**

Alternatively, an additional job based progress bar (above or below) the primary overal progress that shows each job process as they occur. This would definately give peace of mind for many at the unsquash stage for example, so at least the file transfer process itself can be seen. If for nothing else then for the unsquash  / rsync process alone would help. As of now many reports come back that end users perceive Calamares to have stalled when it hasn't.

**Comment by bill-auger** [comment]
ive noticed too that there are many points in the install process that display some uninformative text in the progress area (like a function name IIRC) - most of them fly past very rapidly; and ive never made specific note of any, in order to track down from where they emanate

**Comment by kkofler** [comment]
Well, if the stuff flies by quickly, a terse description is actually better than a verbose one.

**Comment by demmm** [comment]
Thought about using the slideshow for this?  Example https://github.com/KaOSx/calamares/blob/master/src/branding/kaos_branding/show.qml#L50

**Comment by bill-auger** [comment]
that would be a superficial fix, though - i dont think these strings need to be configurable though - they just need to be identified, made to be more informative, and added to the translation system

**Comment by adriaandegroot** [comment]
@salientos To return to the original question: you can massage the translations however you like, including the en_US translation. That allows you to display different strings than the source code does. You would have to use the `-T` flag (load translations from current-directory) and do a bit of futzing, but it'd work.

That said, I'm sure there's messages that can be improved.

But I'm going to close this issue as "needs details". Specific improvements or callouts to things that are bad. Note that modules can send progress reports, like the *unpackfs* module does -- it tells you how things are progressing. 

If you want to mention specifics, you could look in the source: both View Steps and Jobs have messages that are shown to the user (Jobs are the ones that flash by during installation). This might be handy from the top-level of a Calamares checkout:

```
grep -r -A3 ::prettyName src/
grep -r -A3 ::prettyStatusMessage src/
```

(This assumes that the messages are in short functions, formatted according to the Calamares coding style. There's 65 names, 24 status messages defined. This **won't** find the messages from Python modules -- those are a lot more inconsistent.

The prettyName is printed to the log during execution, although I think it's the statusMessage that is displayed if a job reports progress. Look for `[JOBQUEUE]` in the debug output.

**Comment by adriaandegroot** [comment]
(So to reiterate: bad messages are bad; let's fix them. I need more details, though, on **which** ones are bad)
