### ISSUE TITLE
Request for more information regarding printout

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1263]
ArcoLinux 19.12.2
Calamares 3.2.15
Goal : share knowledge of Calamares via project Carli on https://arcolinuxiso.com
There are no problems and ArcoLinux is installing fine with the latest addition for unpackfs to get vmlinuz-linux in our system.

When I run calamares with pkexec I get this print out.
Is there anything I should be worried about?
What do these lines mean?

I will get these questions myself once we start explaining how Calamares works in our tutorials.

```
[liveuser@ArcoLinuxB-budgie-min Desktop]$ pkexec calamares
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
09:54:56 [0]:   OpenType support missing for "Droid Sans", script 11
09:54:56 [2]: WARNING: Partition-module does not support *userSwapChoices* setting "file"
09:54:56 [2]: WARNING: Partition-module does not support *userSwapChoices* setting "reuse"
09:55:19 [0]: QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
09:55:19 [0]: QObject::setParent: Cannot set parent, new parent is in a different thread
chcon: failed to get security context of '/': Operation not supported
chcon: failed to get security context of '/dev': Operation not supported
chcon: failed to get security context of '/proc': Operation not supported
chcon: failed to get security context of '/run': Operation not supported
chcon: failed to get security context of '/run/udev': Operation not supported
chcon: failed to get security context of '/sys': Operation not supported
mount: /tmp/tmp550mge4p/airootfs: WARNING: device write-protected, mounted read-only.
umount: /tmp/calamares-root-34vifqxe/sys (sys) unmounted
umount: /tmp/calamares-root-34vifqxe/run/udev (run) unmounted
umount: /tmp/calamares-root-34vifqxe/run (tmpfs) unmounted
umount: /tmp/calamares-root-34vifqxe/proc (proc) unmounted
umount: /tmp/calamares-root-34vifqxe/dev (dev) unmounted
umount: /tmp/calamares-root-34vifqxe (/dev/sda1) unmounted
```

https://pastebin.com/H9jiEYkG

**Comment by abucodonosor** [comment]
These are things you need to fix in your configuration files:

```
09:54:56 [2]: WARNING: Partition-module does not support *userSwapChoices* setting "file"
09:54:56 [2]: WARNING: Partition-module does not support *userSwapChoices* setting "reuse"

```
You can ignore these if you don't use SELinux:

```
chcon: failed to get security context of '/': Operation not supported
chcon: failed to get security context of '/dev': Operation not supported
chcon: failed to get security context of '/proc': Operation not supported
chcon: failed to get security context of '/run': Operation not supported
chcon: failed to get security context of '/run/udev': Operation not supported
chcon: failed to get security context of '/sys': Operation not supported

```
@kkofler maybe we should make that configurable, it confuses people it seems.

This is a info what got umounted:

```
umount: /tmp/calamares-root-34vifqxe/sys (sys) unmounted
umount: /tmp/calamares-root-34vifqxe/run/udev (run) unmounted
umount: /tmp/calamares-root-34vifqxe/run (tmpfs) unmounted
umount: /tmp/calamares-root-34vifqxe/proc (proc) unmounted
umount: /tmp/calamares-root-34vifqxe/dev (dev) unmounted
umount: /tmp/calamares-root-34vifqxe (/dev/sda1) unmounted

```

That is a normal warning from mount, if you mount RO or the fs is RO:

```
mount: /tmp/tmp550mge4p/airootfs: WARNING: device write-protected, mounted read-only.

```

This seems to be from theme/branding:

```
09:54:56 [0]:   OpenType support missing for "Droid Sans", script 11

```

This one may need some investigation:

```
09:55:19 [0]: QObject::setParent: Cannot set parent, new parent is in a different thread

```

None of the warnings/infos are fatal.

**Comment by arcolinuxz** [comment]
I found this in the config file here
https://github.com/calamares/calamares/blob/master/src/modules/partition/partition.conf

> 09:54:56 [2]: WARNING: Partition-module does not support *userSwapChoices* setting "file"
> 09:54:56 [2]: WARNING: Partition-module does not support *userSwapChoices* setting "reuse"

You do not support this yet.

`userSwapChoices:
    - none      # Create no swap, use no swap
    - reuse     # Re-use existing swap, but don't create any (unsupported right now)
    - small     # Up to 4GB
    - suspend   # At least main memory size
    - file      # To swap file instead of partition (unsupported right now)`

**Comment by arcolinuxz** [comment]
> 09:54:56 [0]:   OpenType support missing for "Droid Sans", script 11
I did not set the font anywhere in the setup - I think
So I tried setting every element in there and the code kicks in but just in title and in last screen after installation. I can not set anything more it seems.
![fonts](https://user-images.githubusercontent.com/36679406/68081810-00ef6200-fe14-11e9-87d2-cab3b76cf83c.png)

**Comment by arcolinuxz** [comment]
> > 09:54:56 [0]:   OpenType support missing for "Droid Sans", script 11
> 
> I did not set the font anywhere in the setup - I think
> So I tried setting every element in there and the code kicks in but just in title and in last screen after installation. I can not set anything more it seems.
> ![fonts](https://user-images.githubusercontent.com/36679406/68081810-00ef6200-fe14-11e9-87d2-cab3b76cf83c.png)

I am now down to this message when launching calamares.
![errors](https://user-images.githubusercontent.com/36679406/68958460-7d971e80-07cc-11ea-8280-6d8ba9e03113.jpg)

It still eludes me why he is point to a font that is installed and what is this script number?

**Comment by adriaandegroot** [comment]
It's not that it's missing that font, it's that that font is missing support for script number 11. That is *probably* Malayalam, which is a beautiful and complicated script. Not all fonts support it. You can safely ignore the warning (but scroll through the language-selection drop-down to see which languages are displayed correctly in their native format).
