### ISSUE TITLE
Feature request :  layout and content of license module

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1268]
We are using calamares 3.2.16 and added now the license module.
For us it will be our switch to either install the opensource drivers or nvidia drivers.

**Layout**

- have more impact on the size of the slider so we do not have these large gaps at the top and the bottom (we set our size of calamares rather big)
- can we move text from place (If you do not agree with the terms... at the bottom - can that go after the top text and before the license slider.
- can we design certain parts of this page (bold - larger font) so users know the consequences of their action (make more dummy proof)

**Content**
- can we override the content of the text displayed in the config file (second sentence under License Agreement) - instead of "can ..." use "will install proprietary"

![improvement](https://user-images.githubusercontent.com/36679406/68539833-a1e89a80-0389-11ea-9746-c07580e4c6ef.png)
Thanks in advance for looking into the matter

Thanks to make it work technically.
Lets make it great now.

**Comment by demmm** [comment]
What about this layout as default?  Is that what you are looking for? (ignore text)
![Screenshot_20191119_153536](https://user-images.githubusercontent.com/5360485/69155668-6fa21000-0ae2-11ea-9330-b2711de2fecb.png)
This can be achieved by toggling the initial state to expanded for the license file.

**Comment by arcolinuxz** [comment]
That would be a great addition to calamares - the abililty to have the license text opened by default
Can we put that on the request list? @adriaandegroot

**Comment by demmm** [comment]
>the abililty to have the license text opened by default

That is only an option when there is just one license in use, License Page has the option to put 4-5 licenses, so that would make the above linked commit useless.  That can only work if adding an ifdef for when just one license is in use.

**Comment by adriaandegroot** [comment]
- default expand sounds like a sensible thing (although as @demmm  mentions, it's only sensible for local licenses and probably only when there's a single one).
 - with the newer translatable-string configurations, you could introduce a description / custom text into the window
 - moving the "please check" text above makes sense to me
 - expanding the actual license-scrollwindow which contains all the license wigets to fill the window instead of compressing it down is an "of course!" kind of fix

The KaOS patch looks really weird to me, though.

**Comment by demmm** [comment]
>The KaOS patch looks really weird to me, though.
You mean the reversing of up and down arrows?  The Calamares master way of looks very weird, see the image in the first post (to me arrow should point down there).

**Comment by adriaandegroot** [comment]
I think we should ask a VDG person for input, since I'm just not sure what to do for arrow-directions on an expanding text.

The rest of the stuff is being worked on in the issue-1268 branch and will land next release (since it affects translations).

**Comment by arcolinuxz** [comment]
I added expand: true to license.conf - I have a working 3.2.17.1. Finished the installation with success.
But should it not be expanded now

![test](https://user-images.githubusercontent.com/36679406/70057224-12778580-15dd-11ea-9fd9-ff0d79468216.png)

**Comment by arcolinuxz** [comment]
Ps. the next button not being available anymore if you select and unselect nvidia is fixed

**Comment by adriaandegroot** [comment]
I have had a discussion with designers and we'll be changing that button / the expand-collapse mechanism for 3.2.18

**Comment by arcolinuxz** [comment]
ok thanks 
looking forward to testing it
