### ISSUE TITLE
More info for users about manual partitioning on calamares

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1278]
Could you provide more info on the partition module so users know what to do on grub and what to do on efi? We get way to many questions about the efi and boot flag - partition size for efi, formatting for it.

I came across this screen on Kaos that tries to remedy all those questions.

Could you think about it please?
![calamares](https://user-images.githubusercontent.com/36679406/69521907-5d035d00-0f60-11ea-8fd5-90607e984bc3.png)

**Comment by 2wing** [comment]
I second that request ... 
This guide on [https://calamares.io/docs/partitions/](url) is vague for new penguins.
Especially see the bottom two pale blue boxes ...
And this is supposed to be "up to date" - Jan'21

**Comment by arcolinuxz** [comment]
We filled the void with 30+ tutorials

https://arcolinux.com/the-calamares-series-all-you-ever-need-to-know-about-calamares/

**Comment by demmm** [comment]
The doc/guide section was specifically created so it would be easy for any Calamares distributor to contribute to more complete documentation.
https://github.com/calamares/calamares.github.io/tree/calamares/_docs
PRs are very welcomed & needed, setup now is more a framework of what is possible.

**Comment by demmm** [comment]
Since this is now open for 3 years, there needs to be an answer whether distributions can agree upon an extended text for Manual partitioning, text now:
https://github.com/calamares/calamares/blob/calamares/src/modules/partition/gui/ChoicePage.cpp#L1648

Or leave as is and close this issue.

**Comment by demmm** [comment]
As this issue is now approaching 5 years being open, and no discussion or consensus has been reached whether to expand the text for manual partitioning, it is time to close this.
For anyone still wanting to implement, KaOS has had this expanded text for 10 years:
https://github.com/KaOSx/calamares/blob/master/src/modules/partition/gui/ChoicePage.cpp#L1659
