### ISSUE TITLE
unauthorised data sniffing, openness and GDPR.

### ISSUE THREAD

**Issue by J-Dunn** [calamares/calamares#1279]
I have just been looking at installing lubuntu which uses calamares. The nice clean look of the installer and its ergonomic design impressed me. Some tasks, like partitioning, which are complex are clearly presented and easy to follow. Very nice to use. 

However, one aspect I did not find too agreeable is sneaking leaking of system configuration information.  It seems that whenever a working network connection is found certain system information is automatically sent to ... well who knows, since you do it behind our backs.

While I can see that having a database of hardware descriptions for target systems can be useful to a distro in targeting hardware support, the underhand way in which this is done behind the user's back and without his knowledge and consent, is not good. 

Not only is this not in the spirit the open source community and the social contract of distributions like Debian/Ubuntu it is very likely illegal under the EU General Data Protection Regulations. 

I would expect a dialogue box giving the user the option of transmitting his system data. A "details" option allowing him to review the contents being sent would probably encourage users to authorise what is being sent. 

I do not expect to have to unplug my network before running an installation because I cannot trust the installer. This is NOT an encouraging way to start a new OS installation.  

You may like to review how this is done and make it more honest and transparent.

**Comment by kkofler** [comment]
This is a downstream issue. They either set up the `tracking` module or ship their own such module. Calamares does not do that by default.

**Comment by kkofler** [comment]
I would argue for removing the `tracking` module from Calamares (I was against adding it to begin with), but realistically, that will just mean that they will be shipping it downstream instead.

**Comment by J-Dunn** [comment]
Thanks for the reply kkofler, I'm glad that you agree in principal, at least.  Obviously they can add whatever they like to their sub-distro. I don't see that as a strong reason for facilitating  downstream adopters in doing such  things by providing and maintaining a tool which provides that capability. _That is rather an open invitation to do it, even if it is not enabled by default._

Maybe removing it would send a signal and trigger serious reconsideration downstream too, before they copied it into their own code, if it is removed from calamares.

I'm not sure exactly what info is transmitted but my particular concern is that there is an IP ( which are more commonly now fixed IPs ) and  plenty of machine specific details which could be enough to nearly or surely uniquely identify a particular machine. As data gets sold or leaked or spied on and recombined in the world of big data we're moving into this is very likely a bad thing. 

 Hopefully calamares is destined for broader adoption. It would be nice to get this right.

**Comment by philmmanjaro** [comment]
This seems to be requested by KDE Neon project. More about the feature [here](https://github.com/calamares/calamares/wiki/Users-Guide#installation-tracking).

**Comment by adriaandegroot** [comment]
#783 is the original request. Note also that the original requester ended up **not** using it for reasons of privacy.

Or **is** this even about the user-tracking module? Calamares checks if you have a working internet connection (e.g. for GeoIP location, downloading packages during installation, fetching license texts, ...) by doing an HTTP get. Looking at the lubuntu configuration (19.04), it has both internet-check and GeoIP configured. It doesn't even have the user-tracking module configured, so there's more to this issue than as originally reported.

**Comment by J-Dunn** [comment]
Well if lubuntu are not, in fact, using it and Neon wisely chose against it, presumably no one will be upset if it is deleted.  

The text in the user's guide above make no mention of this being optional (and not enabled by default). That description was the origin of my initial concerns, I had not got to the stage of get out a packet sniffer to see what is was sending. 

The text should probably better reflect the state of calamares as supplied, until such time as there is a change as to whether this module is included.

**Comment by wxl** [comment]
I can indeed confirm Lubuntu is **not** using the `tracking` module. You can take a look at our [Calamares configuration](https://phab.lubuntu.me/source/calamares-settings-ubuntu/browse/master/lubuntu/settings.conf) to confirm this for yourself.

There is one additional thing that Lubuntu does as far as HTTP requests are concerned: call out to https://ipapi.co/json to try to select a more appropriate local mirror for downloading packages. The source for the module is [here](https://phab.lubuntu.me/source/calamares-settings-ubuntu/browse/master/common/modules/automirror/). 

Incidentially, we also use this in the [`welcome` module](https://phab.lubuntu.me/source/calamares-settings-ubuntu/browse/master/lubuntu/modules/welcome.conf) to try to set the right localization. You'll also notice there we run an HTTP request to check the Internet connectivity. Against lubuntu.me, which is assumedly non-concerning.

---

With regards to the `tracking` module, I should point out, too, that one does not simply flip the module on and call it good. The [default configuration](https://github.com/calamares/calamares/blob/master/src/modules/tracking/tracking.conf) for the module itself has all of the different types disabled.

I see the utility for such a thing but can certainly imagine a huge backlash against this. As far as I'm concerned, the only way this could be reasonably implemented without facing such a backlash is by explicitly asking the user to accept the release of their information. I think simply supplying a policy link isn't sufficient. That's my 2¢ at least.

**Comment by J-Dunn** [comment]
I am reassured that everyone seems to be on the right side of this issue. 

In view of other network activity which has been outlined above, as a slight aside, do I really want ANY network activity on a system which allows sudo su and has an empty root pw !?

**Comment by wxl** [comment]
That's technically a downstream (Lubuntu, not Calamares) issue since it doesn't universally apply across distros, so you might want to continue that conversation on the post you have on the Lubuntu Discourse.

**Comment by adriaandegroot** [comment]
I've updated the generic [user's guide](https://github.com/calamares/calamares/wiki/Use-Guide) to be more clear that user tracking is disabled by default and configured to off as well; the generic users guide could use more work (it's a wiki, have at it).

**Comment by J-Dunn** [comment]
kkofler: 
> I would argue for removing the tracking module from Calamares (I was against adding it to begin with), but realistically, that will just mean that they will be shipping it downstream instead.

Fair enough closing the bug since I was mistaken about this being actively in use.  However, is there any current discussion about removing this unholy feature while no one apparently is taking advantage of it ( and their users )?
