### ISSUE TITLE
CMakeFiles error 1 and error 2

### ISSUE THREAD

**Issue by CJandDarren** [calamares/calamares#1280]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, misconfiguration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.
Background:
My partner and I are a disabled couple, but we are trying to learn to do something to help other disabled people building SLOWLY a disabled-friendly version of a Linux os. www.foreverhomeos.org
Now that said, it is daft but neither I nor her can program. We are trying to muddle along and maybe get help at a later point but leaning as much as we can. 

But we will try out best to explain the error we get.

**Describe the bug**
**A clear and concise description of what the bug is**.
The error was created after doing the specific steps of 
1: $ **cmake -DCMAKE_BUILD_TYPE=Debug ..**
2: We then typed and executed $ **make**

**Our error is:** 
```
/usr/bin/ld: /home/thedarrens/gubbins/calamares/src/libcalamares/PythonJobApi.cpp:62: undefined reference to `boost::python::throw_error_already_set()'
collect2: error: ld returned 1 exit status
make[2]: *** [src/libcalamares/CMakeFiles/calamares.dir/build.make:600: libcalamares.so.3.2.18] Error 1
make[1]: *** [CMakeFiles/Makefile2:411: src/libcalamares/CMakeFiles/calamares.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.**

```
Linux 5.3.12-1-MANJARO #1 SMP PREEMPT Thu Nov 21 10:55:53 UTC 2019 x86_64 GNU/Linux

Motherboard:  Z270X-Gaming 7

description: | CPU
-- | --
product: | Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
vendor: | Intel Corp.
physical id: | 46
bus info: | cpu@0
version: | Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
size: | 4499MHz
capacity: | 4500MHz
width: | 64 bits
```

**Expected behavior**
For the build to finish with no error. 

**Screenshots and Logs**
![2019-11-29_12-49](https://user-images.githubusercontent.com/52346724/69871253-31f37300-12aa-11ea-98dc-248becd8dd42.png)

**Additional context**

**Comment by adriaandegroot** [comment]
Hi CJandDarren, I see you also contacted me by email -- that's fine, and I'll write you there as well.

For this kind of compilation errors, .. hm. It **can** be quickest to ask on IRC, but sometimes there's no response there for hours or even days; it depends on who is watching and what everyone is doing. The information you've provided **suggests** that some dependency packages are missing, but I don't know how the Calamares build would get that far with missing boost libraries.

I'll take a brief stab at reproducing this -- I have some other Boost-related issues that need to be sorted out as well.

**Comment by CJandDarren** [comment]
We, did sort it out, dont ask me how. As a non programmer it was a ok poke about till it works kind of thing. 
Yes, we did email you and we do hope that is ok. 
CJ and Darren

**Comment by HUSKI3** [comment]
Was this issue resolved? If so how? I have installed all dependencies, but still get the same error as above. Im building it inside a chroot and everything works as normal except this.
