### ISSUE TITLE
Using swap+luks option in Calamares causes crash

### ISSUE THREAD

**Issue by taschenlampe** [calamares/calamares#1281]
**Describe the bug**
Using ArcoLinx iso + Calamares v. 3.2.16 + Virtualbox 6.0.14_Ubuntu r132055. 
When adding SWAP(+luks) to my setup the installer crashes in the begining of installation/creation process-  

**Reproduce**
1. Go to delete all disk
2. Click on swap option and enable hibernate || no hibernate (both do not work)
3. Error during installation process.

**Expected behavior**
Well ;-) Installer finds the proper partitions incl. swap+efi+

**Logs**
Debug info -> https://pastebin.com/3M6e5AJM

Please tell me if you need additional information about that issue.

**Comment by taschenlampe** [comment]
Hi there!

Is there a chance to someone could explain, why I have this issue? I am quite curious to understand what is happening here. Or maybe someone knows a workaround for my issue. 
Please, if you need more information, I am happy to provide any files that could help.

Cheers!!

**Comment by mseidel05** [comment]
Hello,
i have the same issue with the arcolinuxb-gnome-v19.11.3.iso when I add SWAP (+luks, no hibernate) to my setup, the installer crashes at the beginning of the installation.

I would be interested in a workaround for this issue. Please let me know if you need further information about this issue.

**Comment by killajoe** [comment]
Same at EndeavourOS

**Comment by taschenlampe** [comment]
I suppose that this issue #1281 is a duplicate of #1163 . So my guess is that this won't be fixed, as there is no reaction from devs.

**Comment by abucodonosor** [comment]
Closing, please follow the discussion from https://github.com/calamares/calamares/issues/1163
