### ISSUE TITLE
fatal error: 'network/utils/moc-warnings.h' file not found

### ISSUE THREAD

**Issue by tpgxyz** [calamares/calamares#1286]
**Describe the bug**
Can not compile 3.2.17.x with LLVM/clang-9.x.x

**To Reproduce**
1. compile calamares-3.2.17.1 on OpenMandriva Lx cooker
2. Observe error

**Expected behavior**
Compile without errors

**Screenshots and Logs**
Logs and configuration taken from https://abf.openmandriva.org/build_lists/651632

```
FAILED: src/libcalamares/CMakeFiles/calamares.dir/calamares_autogen/mocs_compilation.cpp.o 
/usr/bin/clang++  -DDLLEXPORT_PRO -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SHARED -DQT_SHAREDPOINTER_TRACK_POINTERS -DQT_STRICT_ITERATORS -DQT_XML_LIB -Dcalamares_EXPORTS -Isrc/libcalamares/calamares_autogen/include -Isrc/libcalamares -I../src/libcalamares -I/usr/include/python3.8 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/./mkspecs/linux-clang -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/KF5 -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtXml -Os -fomit-frame-pointer -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4  -m64 -mtune=generic -flto -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-padded -Wno-undefined-reinterpret-cast -Wno-global-constructors -Wno-exit-time-destructors -Wno-missing-prototypes -Wno-documentation-unknown-command -Wno-unknown-warning-option -Werror=return-type -DNOTREACHED='//' -DFALLTHRU='[[clang::fallthrough]]' -O2 -g -fPIC   -fPIC -std=gnu++14 -MD -MT src/libcalamares/CMakeFiles/calamares.dir/calamares_autogen/mocs_compilation.cpp.o -MF src/libcalamares/CMakeFiles/calamares.dir/calamares_autogen/mocs_compilation.cpp.o.d -o src/libcalamares/CMakeFiles/calamares.dir/calamares_autogen/mocs_compilation.cpp.o -c src/libcalamares/calamares_autogen/mocs_compilation.cpp
In file included from src/libcalamares/calamares_autogen/mocs_compilation.cpp:10:
src/libcalamares/calamares_autogen/5SSUPNRDSB/moc_Manager.cpp:10:10: fatal error: 'network/utils/moc-warnings.h' file not found
#include "network/utils/moc-warnings.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[21/376] Building CXX object src/libcalamares/CMakeFiles/calamares.dir/ProcessJob.cpp.o
[22/376] Building CXX object src/libcalamares/CMakeFiles/calamares.dir/geoip/Interface.cpp.o
[23/376] Building CXX object src/libcalamares/CMakeFiles/calamares.dir/geoip/GeoIPJSON.cpp.o
[24/376] Building CXX object src/libcalamares/CMakeFiles/calamares.dir/JobQueue.cpp.o
[25/376] Building CXX object src/libcalamares/CMakeFiles/calamares.dir/GlobalStorage.cpp.o
[26/376] Building CXX object src/libcalamares/CMakeFiles/calamares.dir/geoip/Handler.cpp.o
[27/376] Building CXX object src/libcalamares/CMakeFiles/calamares.dir/Settings.cpp.o
ninja: build stopped: subcommand failed.

```
**Additional context**

**Comment by abucodonosor** [comment]
Compiles here.

**Comment by tpgxyz** [comment]
@abucodonosor very helpful, indeed.

**Comment by fedya** [comment]
Something wrong with includes

**Comment by fedya** [comment]
```
[omv@248a0cfa3a01 calamares-3.2.17.1]$ ninja -C build
ninja: Entering directory `build'
[9/321] Building CXX object src/libcalamares/CMakeFiles/calamares.dir/calamares_autogen/mocs_compilation.cpp.o
FAILED: src/libcalamares/CMakeFiles/calamares.dir/calamares_autogen/mocs_compilation.cpp.o 
/usr/bin/clang++  -DDLLEXPORT_PRO -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SHARED -DQT_SHAREDPOINTER_TRACK_POINTERS -DQT_STRICT_ITERATORS -DQT_XML_LIB -Dcalamares_EXPORTS -Isrc/libcalamares/calamares_autogen/include -Isrc/libcalamares -I../src/libcalamares -I/usr/include/python3.8 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/./mkspecs/linux-clang -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/KF5 -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtXml -Os -fomit-frame-pointer -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4  -m64 -march=znver1 -mtune=znver1 -mmmx -msse -msse2 -mssse3 -msse4a -msse4.1 -msse4.2 -mavx -mavx2 -msha -maes -mclflushopt -mfsgsbase -mrdrnd -mfma -mrdseed -mpopcnt -madx -mbmi -mbmi2 -mfxsr -mxsave -mxsaveopt -mxsavec -mxsaves -mmwaitx -mclzero -mfpmath=sse -flto -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-padded -Wno-undefined-reinterpret-cast -Wno-global-constructors -Wno-exit-time-destructors -Wno-missing-prototypes -Wno-documentation-unknown-command -Wno-unknown-warning-option -Werror=return-type -DNOTREACHED='//' -DFALLTHRU='[[clang::fallthrough]]' -O2 -g -fPIC   -fPIC -std=gnu++14 -MD -MT src/libcalamares/CMakeFiles/calamares.dir/calamares_autogen/mocs_compilation.cpp.o -MF src/libcalamares/CMakeFiles/calamares.dir/calamares_autogen/mocs_compilation.cpp.o.d -o src/libcalamares/CMakeFiles/calamares.dir/calamares_autogen/mocs_compilation.cpp.o -c src/libcalamares/calamares_autogen/mocs_compilation.cpp
In file included from src/libcalamares/calamares_autogen/mocs_compilation.cpp:10:
src/libcalamares/calamares_autogen/5SSUPNRDSB/moc_Manager.cpp:10:10: fatal error: 'network/utils/moc-warnings.h' file not found
#include "network/utils/moc-warnings.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by fedya** [comment]
moc warning placed in
./src/libcalamares/utils/moc-warnings.h
include points to
#include "network/utils/moc-warnings.h"

cp -r  src/libcalamares/utils/ ./src/libcalamares/network/

fixes this issue

well it's 100% upstream bug.

**Comment by abucodonosor** [comment]
@tpgxyz 

as helpful as your report.

@fedya 

I have to disagree, you have to find out what in cooker breaks it.

Compiles here no matter what I do.

```
==> Elapsed Time: 1m 25s
==> Removing unwanted files...
==> Preparing package documentation...
==> Compressing info and manual pages...
==> Checking symbolic links...
==> Stripping symbols from from calamares-frugalware...
==> Generating files for calamares-frugalware:
   -> .PKGINFO file... 
   -> .CHANGELOG file... 
   -> .FILELIST file... 
   -> Compressing calamares-frugalware-3.2.17.1-1-x86_64.fpm 

```

Can you try with plain cmake, please?

**Comment by kkofler** [comment]
What I see is that the OpenMandriva Cooker build is using Qt 5.14.0 RC1 (and QtWebEngine is even a 5.15 snapshot). Maybe there is a moc regression in Qt 5.14.0 RC1?

I have also noticed that the OpenMandriva Cooker build uses Clang rather than GCC/g++.

**Comment by fedya** [comment]
@abucodonosor well, yes think you right

**Comment by berolinux** [comment]
I've looked at it a bit, and found the line

`set( CALAMARES_AUTOMOC_OPTIONS "-butils/moc-warnings.h" )`

in the top level CMakeLists.txt file is what's causing the problem.
This happens to be in a

`if( CMAKE_CXX_COMPILER_ID MATCHES "Clang" )`

block, so the problem is exposed by using clang, but it's not a bug in clang itself. You can reproduce it with gcc as well if you move the CALAMARES_AUTOMOC_OPTIONS line out of that block.

The real problem is automoc injecting "network/" before the utils/moc-warnings.h filename, making it network/utils/moc-warnings.h, which doesn't exist.
Not sure why automoc (cmake 3.16.1) is doing that, will need to look at this some more -- but in the mean time just getting rid of the CALAMARES_AUTOMOC_OPTIONS line "works".

**Comment by berolinux** [comment]
The command being run by automoc to generate the file with the bogus #include is

`
/usr/lib64/qt5/bin/moc -DDLLEXPORT_PRO -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SHARED -DQT_SHAREDPOINTER_TRACK_POINTERS -DQT_STRICT_ITERATORS -DQT_XML_LIB -Dcalamares_EXPORTS -I/home/bero/temp/abf/calamares/BUILD/calamares-3.2.17.1/build/src/libcalamares -I/home/bero/temp/abf/calamares/BUILD/calamares-3.2.17.1/src/libcalamares -I/usr/include/python3.8 -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/lib64/qt5/mkspecs/linux-clang -I/usr/include/KF5/KCoreAddons -I/usr/include/KF5 -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include -I/usr/include/c++/9.2.1 -I/usr/include/c++/9.2.1/x86_64-openmandriva-linux-gnu -I/usr/include/c++/9.2.1/backward -I/usr/local/include -I/usr/lib64/clang/9.0.1/include --include /home/bero/temp/abf/calamares/BUILD/calamares-3.2.17.1/build/src/libcalamares/calamares_autogen/moc_predefs.h -p network -butils/moc-warnings.h -o /home/bero/temp/abf/calamares/BUILD/calamares-3.2.17.1/build/src/libcalamares/calamares_autogen/5SSUPNRDSB/moc_Manager.cpp /home/bero/temp/abf/calamares/BUILD/calamares-3.2.17.1/src/libcalamares/network/Manager.h
`

Note the `-p network` -- that's where the prefixed `network/` comes from.

I'm not familiar with the inner workings of automoc, but given the file being automoc-ed is network/Manager.h, smells of someone fixing a problem in automoc with files in subdirectories by adding -p<subdirectory> without thinking of the use case in calamares where you want automoc to add an include that lives outside of the file's subdirectory.

**Comment by berolinux** [comment]
The code doing this (cmake 3.16.1, Source/cmQtAutoMocUic.cxx, around line 1928) seems to be doing this intentionally to make sure files included with -b are relative to the current file's subdirectory.

As @abucodonosor found, replacing `"-butils/moc-warnings.h"` with `--include utils/moc-warnings.h` looks like the right fix.

**Comment by berolinux** [comment]
https://github.com/calamares/calamares/pull/1292

**Comment by kkofler** [comment]
Looking at the documentation of `--include` (in the `--help` output), no that does not look like the right fix at all. For `utils/moc-warnings.h` to be actually useful, that file has to be `#include`d by the generated `moc` output (so that Clang sees it), but `--include` is actually documented as telling `moc` itself to include the file during parsing (which will have no effect on the Clang warning controls).

**Comment by adriaandegroot** [comment]
If it's a change in CMake 3.16 then it'll take some wrangling to fix because my usual development environment is a slightly older Netrunner. Good thing I have a new slimbook with openSUSE tumbleweed on it, for modern testing :)

... confirmed.

**Comment by adriaandegroot** [comment]
Not *that* much wrangling, though. A new knob was introduced to specify whether `-p` would be added, so it's just a matter of switching it off; this is compatible with older CMake versions that just don't have that knob, too.
