### ISSUE TITLE
Accentuation problems in Portuguese (Brazil) and maybe others

### ISSUE THREAD

**Issue by CaioFViana** [calamares/calamares#1288]
**Describe the bug**

When configuring the keyboard to be in the layout I want, the moment I test it, it works only the layout itself.
In languages that uses accentuation, we first type the accent and after the letter we want. Like ~ and then 'a' to form 'ã'. But in the testing, it only appears '~a' in the box. this happens to every combination we normally use.

**To Reproduce**
I found it in my own testing. but I reproduced in Manjaro too. so...
1. Download manjaro (my version was manjaro-kde-18.1.3-191114-linux53)
2. Just boot it without changing languages or anything (in my live iso, I have the correct keyboard normally, selecting in calamares will break it)
3. In my case, select Portuguese Brazil as the language (was pre-selected in manjaro) and go to the keyboard part. If it matters, I selected São Paulo (Brazil) as the location.
4. Now, in Keyboard, select Portuguese Brazil, and select "no dead keys", as is ABNT2, our default keyboard layout.
5. Try to type a character like 'ã' or 'é', and see '~a' or 'e (not even ´. but it doesn't matter in this case)

**Expected behavior**
My keyboard typing the right things in calamares and after install.

**Screenshots and Logs**
Not relevant, as it's the keyboard text only and logs don't show anything relevant as far as I checked

**Additional context and what I tried on my own**
Arch Linux using the latest released Calamares in my testing. Not a 'old bug'.

In the linux brazil community, we use the command 'setxkbmap -model abnt2 -layout br' to fix it. But for me it only goes until rebooting, with is not ideal (it's what I am using now to write this and fix my language. but it is in my autostart as a script... not ideal).

I also heard about the command 'localectl --no-convert set-x11-keymap br pc104 "" ""' (yes, 2 empty strings at the end) that also works, but for calamares, it maybe won't because it fails in chroot (I tried in the past).

In my ISO, I have the following 2 files, configuring the keyboard behavior. I remember it not fully working in the console (like in ctrl alt fn), but it was working!

The keyboard.conf is left as default config in my testing.

File /etc/vconsole.conf
KEYMAP=br-abnt2

File /etc/X11/xorg.conf.d/
(Omitted comments autogenerated by systemd-localed)
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "br"
        Option "XkbModel" "pc104"
EndSection

If relevant, the file /etc/locale.conf
LANG=pt_BR.UTF-8

So, someone knows what is happening?

**Comment by kkofler** [comment]
Sorry, I do not see how this is a bug.

Do not select "no dead keys" if you want the tilde ~ to be a dead key (i.e., to get ã when you type ~a). (Type `~ ` (tilde and space) to get `~` (tilde) with a dead key tilde.)

**Comment by CaioFViana** [comment]
But there is no other option for the ABNT2 keyboard with the accents on the side, with is the most used in Brazil. If you compare the image of the dead keys to the others, it's the only one with shows the correct one.

Maybe I misinterpreted what each option is, but then, the images sound misleading in my opinion... 

If it's my misinterpretation, can you send me a link with details/man page of each option of keyboard?

**Comment by kkofler** [comment]
Is there no "Default" variant listed? That should be the one you want (as far as I can tell from the preview images in Plasma System Settings, I haven't fired up a VM to check this in Calamares yet).

**Comment by CaioFViana** [comment]
There is no "default". And the one that looks like default (Just "Portuguese( Brazil, Native)") is one that I think I never saw in Brazil. But looking for the behavior I wanted, I found It under "IBM/Lenovo". Weird the ABNT2 keyboard and default behavior (even in windows is called ABNT2) being called like that...

**Comment by CaioFViana** [comment]
So my real title should me "misleading previews? In the ibm/lenovo, It shows everything except the accents, misleading to think there is no accent in the configuration

**Comment by kkofler** [comment]
Looks like there are 2 bugs: the missing "default" (not sure whether it is a bug in Calamares or in the version of `xkeyboard-config` on the ISO you are using, I have a "default" entry in Plasma System Settings, in any case) and the wrong preview for "IBM/Lenovo" (I see the accent keys in Plasma System Settings). I am going to check whether I can reproduce these bugs in Calamares.

**Comment by CaioFViana** [comment]
Now that I re-opened the VM, the 'default' was cut in the screen. There really was one and was my mistake.

Second, the behavior of default is the same as the Lenovo/IBM. But I don't remember being this when I started working with calamares. Maybe I tried the default because of the accents missing...?

yeah, I think this issue is a giant misunderstanding of my part. I really think the pictures are misleading but this is not related to this. Sorry by wasting your time

**Comment by CaioFViana** [comment]
Just a post note:
I won't create a second issue for this. But I need to say what I though was misleading.

this is the default, with works like the normal behavior

![image](https://user-images.githubusercontent.com/48189068/70856275-7b9da980-1eb7-11ea-85f3-475c61cd3645.png)

but this is the no-dead-keys, with has the accents missing.

![image](https://user-images.githubusercontent.com/48189068/70856284-a556d080-1eb7-11ea-8e39-bf320dc472a5.png)

note the number 6 and the keys on the right. This is the drawing I see on my keyboard, I clicked originally.

**Comment by kkofler** [comment]
So the bug is that the preview does not show the dead keys, which is a bug / missing feature somewhere in `src/modules/keyboard/keyboardwidget/keyboardpreview.cpp`.

**Comment by CaioFViana** [comment]
So maybe I should make another issue adressing this... Thank you!
