### ISSUE TITLE
Calamares does not center on monitor at start

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1293]
On ArcoLinux 20.1.1 we are using Calamares 3.2.17.1 and we now see that when Calamares is started it does not center anymore on our screens.
Tested on virtualbox and on real metal
![not in middle](https://user-images.githubusercontent.com/36679406/71306169-86879b00-23dd-11ea-9fa6-0bb417efe63f.jpg)
Has there been a change in code that can explain this?

**Comment by arcolinuxz** [comment]
Just installed on a dual screen with xfce and calamares appears on the second screen at the very top-left corner then.

**Comment by kkofler** [comment]
Yes, this was a deliberate change: https://github.com/calamares/calamares/commit/fc7ea80d9969038eb2c5fabc954f55a3d3b3319b

**Comment by arcolinuxz** [comment]
Can the developers decide whether they do like to center it?
So an extra parameter to set centering to true.

**Comment by philmmanjaro** [comment]
On XFCE you can decide which window size is needed to center windows on the screen. KDE and other desktop environments might have similar options to set. If you still want to have **CAL** to center the screen you may revert that commit as needed in your local package you distribute with your distribution.

**Comment by adriaandegroot** [comment]
That commit was a bit lazy of me.

**Comment by adriaandegroot** [comment]
Note that you can do tricks with the window manager as well: Netrunner seems to start **everything** centered unless the application has saved a location (e.g. Spectacle re-starts where you left it). On a generically-configered kwin (FreeBSD) Calamares shows up somewhere on the screen my mouse cursor is on.

**Comment by arcolinuxz** [comment]
thanks for pointing me in the right direction
for future reference and developers 
**in xfce** 
/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml 
<property name="placement_ratio" type="int" value="100"/>

see commit also : https://github.com/arcolinux/arcolinux-xfce/commit/712ea5c5325b735cbac6a2d1a00d8fb2fc3c5195

**Comment by adriaandegroot** [comment]
In the best tradition: there's more than one way to do it.

In any case, Calamares branding now has a *windowPlacement* setting as well which will switch on a center-on-primary-screen code path very similar to what it had before -- so you can go either with a Calamares setting or with a window manager setting (I think the latter is a better idea in general: the WM knows all about geometry, and Cala can only best-guess).
