### ISSUE TITLE
Calamares failing to install a bootloader on Manjaro

### ISSUE THREAD

**Issue by Secondmineboy** [calamares/calamares#1295]
Hello,

Calamares recently failed to install a bootloader on my laptop in the newer ISOs of Manjaro.

Ive opened a topic in their community here:

https://forum.manjaro.org/t/calamares-failing-to-install-a-bootloader/116118

Ive also tried with an older ISO image and it ends up in the same issue.

**Comment by philmmanjaro** [comment]
Did you tried it in a virtual machine like **Virtualbox**. Also provide the full installation log via: `sudo -E calamares -d`

**Comment by Secondmineboy** [comment]
Ima try in VirtualBox in a bit tho it will take a while cause the wifi is very slow the last days.

**Comment by abucodonosor** [comment]
@philmmanjaro 

I'm closing this now, it seems to be fixed now in Manjaro.

https://forum.manjaro.org/t/calamares-failing-to-install-a-bootloader/116118/21
