### ISSUE TITLE
Cannot build Calamares with Qt 5.9

### ISSUE THREAD

**Issue by mkrawiec** [calamares/calamares#1296]
The minimal requirement according to the readme is Qt 5.9, however the codebase includes a reference to https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance-1 which was introduced in Qt 5.11, making it impossible to build with the earlier version:

```
[  161s] /home/abuild/rpmbuild/BUILD/calamares-3.2.17.1/src/modules/locale/timezonewidget/timezonewidget.cpp:228:39: error: 'class QFontMetrics' has no member named 'horizontalAdvance'
[  161s]      const int textWidth = fontMetrics.horizontalAdvance( LocaleGlobal::Location::pretty( currentLocation.zone ) );
[  161s]                                        ^~~~~~~~~~~~~~~~~
```

**Comment by adriaandegroot** [comment]
That was changed in ad868033f3ede77f09fbd34df85332854e5aa749 , and you're right, for Debian old that's an issue. I'll #ifdef it to bits

**Comment by adriaandegroot** [comment]
(please double check)
