### ISSUE TITLE
Is this a forgotten message in module summary?

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1301]
Calamares 3.2.17.1
Running calamares in debug I see a message from module summary
No config file for "summary" found anywhere at ... 3 locations

I do not find a summary.conf at this location: 

https://github.com/calamares/calamares/tree/master/src/modules/summary

![summary](https://user-images.githubusercontent.com/36679406/72364683-360f0f00-36f7-11ea-9349-6afd6b38e536.png)

**Comment by adriaandegroot** [comment]
Summary doesn't have a config file at all, but the general module-loading code **always** looks for a config file. And it complains somewhat if it doesn't find one. This is not something to worry about for the summary module, but it might make sense to add some `module.desc` key to avoid loading after all.
