### ISSUE TITLE
Is this a forgotten message in module localecfg?

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1302]
Calamares 3.2.17.1

Running calamares in debug I see a message from module localecfg
No config file for "localecfg" found anywhere at ... 3 locations

I do not find a localecfg.conf at this location: 

https://github.com/calamares/calamares/tree/master/src/modules/localecfg

![localecfg](https://user-images.githubusercontent.com/36679406/72365050-d107e900-36f7-11ea-9066-cc6e7da9c1ae.png)

**Comment by arcolinuxz** [comment]
May I just say that these messages also occur in the following modules

networkcfg
hwclock

I was just wondering why they are there and/or if I am missing something here?

**Comment by adriaandegroot** [comment]
Those are all modules where no config file is expected (this reinforces the idea that a `module.desc` key to suppress the config-warning would be useful)
