### ISSUE TITLE
Feature request: two or three netinstall screens/modules for users to select from 

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1303]
I can make a second netinstall modules with the name netinstallkernel (in the video - just an example - copy/paste of the netinstall module) and it will show up in calamares as a second screen to choose applications from. 

When I tried this out. The choices from the first netinstall modules are lost. The second netinstall module will override the settings the user choose in the first rendering the first module void.

My guess is that the choices get overwritten and not appended.

I looked at the code where this list (plist I think is the variable) gets overwritten to see if I can solve it myself. I do not see what to change where to get to my desired result.

Dreaming away here it would be great that a user gets 3 netinstall modules
1. Select kernels and drivers
2. Select desktop (xfce, ...)
3. Select applications
and then let calamares install all three selections.

At the moment the last screen/module will be installed.

I hope this feature can be added since it is my gut feeling you need to append rather than overwrite. My gut can be wrong.

Here is a video I made without sound if you need it. Mute video.
https://vimeo.com/385770160
Password : calamares

**Comment by kkofler** [comment]
Have you tried using instances:
https://github.com/calamares/calamares/blob/9acf80db8b449b9b3e060a4b80c31b62899711bc/settings.conf#L28
instead of copying the whole module?

**Comment by arcolinuxz** [comment]
Is there a practical example somewhere?
Do not quite know what this can do and how it should be implemented when I read this.

**Comment by arcolinuxz** [comment]
![currentdev](https://user-images.githubusercontent.com/36679406/72703762-c6fe4400-3b56-11ea-88c6-dbfdcc7637a3.png)
This is the current development. Ideally it could be in 4 screens.

**Comment by arcolinuxz** [comment]
Thanks @kkofler  for mentioning instances to me. That is a great feature.
I was able to understand how to create instances (I think) and applied it to our distro.

However if you use two instances. The first selection of packages will be overwritten by the second selection and so on ... the last selection is the only one that counts and will be installed. Might be doing something wrong here.

I like to here your input.

First video - the use of instances and prove that the applications of the first screen are NOT installed. Only the second instance.

https://vimeo.com/385932288
password : calamares

Second video - the use of the default instance - netinstall - no second screen to choose applications
All packages are installed
https://vimeo.com/385933196
password : calamares

**Comment by kkofler** [comment]
So this is the bug:
https://github.com/calamares/calamares/blob/090aee91960f77df8f2fa4fdee25cfa6b23fc269/src/modules/netinstall/NetInstallViewStep.cpp#L164

This overwrites any previous `packageOperations` value in the global setting. This needs to retrieve the existing value from the global settings and append to it, or perhaps better, they could already be retrieved here:
https://github.com/calamares/calamares/blob/090aee91960f77df8f2fa4fdee25cfa6b23fc269/src/modules/netinstall/NetInstallViewStep.cpp#L123
so that we directly append to the existing list.

**Comment by philmmanjaro** [comment]
It might take a while to get this fixed. @adriaandegroot is currently on a workshop and might come back in couple of days ...

**Comment by arcolinuxz** [comment]
I am already glad we figured out the issue. Now we can solve it. I will probably do a meet and greet at Fosdem @adriaandegroot on Sunday.

**Comment by adriaandegroot** [comment]
Labeled as both bug and new-feature because I don't think anyone thought of doing multiple netinstalls before (and I'd probably recommend using packagechooser instead, nowadays, although that might not have the large range that netinstall has).

**Comment by arcolinuxz** [comment]
The new feature is actually quite useful and necessary @adriaandegroot .
We will give the user 4 screens.
1. kernel, nvidia and microcode
2. Display manager - lightdm - sddm - gdm - lxdm
3. Plasma, Cinnamon, Xfce, and 12 more
4. Applications of all categories

It is the fact that they are presented to the user when it starts to make sense and they see the parts they need to have an OS.

Tried Packagechooser - not ideal for our purpose so moved to netinstall. This is just great. If only we could make copies of the module or in this case instances.

**Comment by arcolinuxz** [comment]
I just had an idea. Maybe you can add a line to this module as an intermediate solution.
If we can divide the list into blocks that would be great.
![arcolinuxd-calamares](https://user-images.githubusercontent.com/36679406/74239843-fc6efb00-4cd8-11ea-852d-fdbbea33b9f0.png)

**Comment by kkofler** [comment]
I think it is actually much easier to fix this bug than to implement that suggestion.

**Comment by arcolinuxz** [comment]
i leave that up to you to decide.
