### ISSUE TITLE
LUKS2 Support

### ISSUE THREAD

**Issue by HulaHoop0** [calamares/calamares#1306]
Hi. We are a downstream privacy distro (WhonixOS) using Calamares. Can you please add support for LUKS2 volume creation? Grub has started o support it recently. The new format should provide superior protection from passphrase bruteforce attacks.

https://www.phoronix.com/scan.php?page=news_item&px=GRUB-Boots-LUKS2-Disk-Encrypt

cc/ @adrelanos

**Comment by abucodonosor** [comment]
See https://github.com/calamares/calamares/issues/1099
