### ISSUE TITLE
Feature request - module netinstall - select all checkbox

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1309]
Working with calamares 3.2.17.1 on ArcoLinux 20.2.9.

Is it possible to have a select all button in the netinstall window?

![selectallcalamares](https://user-images.githubusercontent.com/36679406/73345009-979cb500-4283-11ea-91de-3b0f64f9c777.png)
It is sometimes easier to select all and then deselect the ones you do not need.

**Comment by adriaandegroot** [comment]
If you put all that into a group you can select the group (at the expense of having a slightly deeper tree).

But I'd really like to try to avoid adding UI elements to the netinstall module: I consider it  a "throwback" module that should be replaced by better UI. (Designs welcome)

**Comment by arcolinuxz** [comment]
ok gotcha - i do hope we can split this screen into different instances see #1303

**Comment by kkofler** [comment]
Am I the only one who actually **likes** the netinstall module's UI?

**Comment by abucodonosor** [comment]
No, I like the UI also.

**Comment by arcolinuxz** [comment]
No, I like netinstall module too
