### ISSUE TITLE
Feature request : module packages - netinstall - be more verbose

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1310]
Working on calamare 3.2.17.1 on ArcoLinux 20.2.9.

Would it be possible to show all the packages that will be installed - you write them to the log - could you write them behind "install packages" - at the bottom of the page.
so users see what calamares is doing 
install package firefox
install package vivaldi ...
Let developers maybe choose whether they want to be verbose or not...

![installing packages](https://user-images.githubusercontent.com/36679406/73345306-26113680-4284-11ea-8afa-29ec9fc5ed5c.png)

**Comment by adriaandegroot** [comment]
Added to the milestone, but I'm not sure this has a really satisfying solution; we call the package manager (whatever it is) sometimes with a long list of packages to install, and don't know how to handle progress reporting from it. So we can show progress before-or-after each package-installer run (with `try_install` this is after every package, though) using **some** name.

**Comment by adriaandegroot** [comment]
This is a dup of #1200
