### ISSUE TITLE
Installer fails at "Generate machine-id"

### ISSUE THREAD

**Issue by artixnous** [calamares/calamares#1314]
Recently, Arch and probably all derivates [removed /var/lib/dbus](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/dbus&id=7ec6e58c004db097820ac87e678ad55ff1825762) from dbus, probably because it was empty anyway. However, this has led to installation failures, because the module that tries to generate the machine-id doesn't check if /var/lib/dbus exists and fails.
```
06:42:48 [6]: Starting job "Generate machine-id." 
06:42:48 [6]: Running "chroot" ("/tmp/calamares-root-81i1rglm", "dbus-uuidgen", "--ensure") 
06:42:48 [6]: Finished. Exit code: 1 
06:42:48 [6]: Target cmd: ("dbus-uuidgen", "--ensure") 
06:42:48 [6]: Target output:
Could not create /var/lib/dbus/machine-id.IHSZsFL5: No such file or directory
...
06:42:48 [1]: ERROR: Installation failed:
06:42:48 [6]: - message: "External command finished with errors." 
06:42:48 [6]: - details: "Command <i>dbus-uuidgen --ensure</i> finished with exit code 1.\nOutput:\nCould not create /var/lib/dbus/machine-id.IHSZsFL5: No such file or directory" 

```

**Comment by adriaandegroot** [comment]
I was going to close this as downstream-bug, although Phil's fix is fine (and more helpful than "Arch ships a broken dbus-uuidgen, then")

**Comment by philmmanjaro** [comment]
Seems `ln -sf` fails when the folder not existing. Somehow on Manjaro we have that folder. So now it will get created. We might need to check the CPP code then.

**Comment by adriaandegroot** [comment]
So, overall a good issue, @artixnous . Kind of annoying that this kind of change sneak in from the "sidestream" (neither up- nor down-). In any case:

 - the old `main.py` has been removed, so it's not misleading anymore
 - following Manjaro's lead `ln -sf` is used when symlinking
 - the /var/lib/dbus directories are created as needed
 - various unittests added and expanded
 - infrastructure methods added to `CalamaresUtils::System` for other modules (when they get around to migrating to C++)
