### ISSUE TITLE
There are no partitions to install on

### ISSUE THREAD

**Issue by grygaz** [calamares/calamares#1320]
Hello.
My problem is that when i start: sudo ./camares -d it not find any partitions on my pc. 
How can i fix it? Where i did make mistake?
Thanks 

![DeepinScreenshot_select-area_20200218192341](https://user-images.githubusercontent.com/48222649/74761401-a673f780-5284-11ea-8f16-29ecdfb5e8f0.png)
![DeepinScreenshot_nemo_20200218192356](https://user-images.githubusercontent.com/48222649/74761398-a4aa3400-5284-11ea-8f96-6f5cd00c6927.png)
![DeepinScreenshot_select-area_20200218192446](https://user-images.githubusercontent.com/48222649/74761409-a7a52480-5284-11ea-85c1-9682a4dd2651.png)

**Comment by abucodonosor** [comment]
That screenshot is telling you. You only provide /dev/sdb which seems to have iso filesystem on it. Those are ignored ofc.

**Comment by grygaz** [comment]
Thanks!!! 
I format it: sudo mkfs.ext4 /dev/sdb and it works fine.
