### ISSUE TITLE
squashfs is not supported"

### ISSUE THREAD

**Issue by grygaz** [calamares/calamares#1321]
Hello.
I can't unsquash my FS. I have installed on my pc unsquashfs , but calamares tells me, that he can't unsquash. How can i fix it?
Thanks

![DeepinScreenshot_select-area_20200218222256](https://user-images.githubusercontent.com/48222649/74775018-7c7aff00-529d-11ea-831a-a50d8cdac725.png)
![DeepinScreenshot_xed_20200218222207](https://user-images.githubusercontent.com/48222649/74775022-7dac2c00-529d-11ea-8940-15ac781c2839.png)
![DeepinScreenshot_xed_20200218222222](https://user-images.githubusercontent.com/48222649/74775026-7f75ef80-529d-11ea-8a1c-5602170df348.png)

**Comment by abucodonosor** [comment]
@grygaz 

This here is a bug tracker, not a support line.
Please join our IRC channel ( #calamares ) on Freenode for general help.
