### ISSUE TITLE
Chinese Translation Strings

### ISSUE THREAD

**Issue by samurailostinjapan** [calamares/calamares#1323]
Hi, 
There was a user on the ArcoLinux telegram that was asking about the Chinese fonts that needed to be added to the Calamares installer. The Arcolinux core team quickly added the fonts and I volunteered to do a test of the ISO. During the testing, I noticed some of the strings were not translated. I have asked the user that requested the Chinese fonts if he would be willing to help translate the remaining strings. He responded is willing to try to help or ask other people to help translates the strings but he doesn't want to be involved in communicating with anyone because his English is not so good. If I can get the remaining Chinese strings that need to be translated, I am willing to be the go-between to help get them translated. I am not confident on much he can help, but any help is better than none.

**Comment by adriaandegroot** [comment]
That's great!

Calamares translations happen on Transifex, so depending on which Chinese variant you want to translate, there are:
- https://www.transifex.com/calamares/calamares/translate/#zh_CN
- https://www.transifex.com/calamares/calamares/language/zh_TW/

Taiwanese is at 100%, so I imagine your correspondence-partner would like to contribute to Chinese. For *me* the easiest way is for you (and them) to contribute via that translation platform -- you don't need to communicate with anyone but the website. There's a Chinese team, and I see them discussing issues in the strings in Chinese (I get a notification, and chime in in English if I have a suspicion what it's about, but otherwise it's up to the team).

It's also possible to submit changes through GitHub (e.g. by editing `lang/calamares_zh_CN.ts`) but that has a definite downside: it's more work for me (since then I need to merge and then push to Transifex) and more error-prone (the synchronisation with the translation team is missing, and I can't check/review anything).

So, summary: that's great! There's plenty of ways to add to the translations, just let me know.

**Comment by samurailostinjapan** [comment]
Thanks for the feedback!
I have given him the lang/calamares_zh_CN.ts file as I believe it will be easier to get a response than having them log into a system. He did mention he was going to ask the Arch Linux forum in China to help with the translation so that is a positive. 
My apologize if it creates more work for you and if I have time I will try to add them to the transifex system. I will check in with him every few days to check on the status.

**Comment by andy1247008998** [comment]
All done. Have fun!

**Comment by samurailostinjapan** [comment]
Thanks!!!!! Closing the ticket

**Comment by adriaandegroot** [comment]
Thank you both. The updated translations will be in Calamares 3.2.21, due for release this month (march). Then it will reach distributions (KDE neon and Manjaro first, usually) after that.

**Comment by linlinger** [comment]
When I update to Calamares version 3.2.42 I found that some strings not being translated into Chinese. I have to manually translate the string and mark them as completed in QT linguist application. And I replace the original files and the translation works again. Please fix this

**Comment by philmmanjaro** [comment]
Did you update the string on Transifex?


- https://www.transifex.com/calamares/calamares/translate/#zh_CN
- https://www.transifex.com/calamares/calamares/language/zh_TW/

**Comment by linlinger** [comment]
No,and I don't know how to update the translation file. What I did is download the latest release package from Github and compile it

**Comment by philmmanjaro** [comment]
If you didn't register to that servers nor being part of the translation team there yet, you may also simply attach the modified file here, so we may create a needed diff or add it to the translation from our end.

**Comment by linlinger** [comment]
I'm a part of calamares Chinese translation now and I translate some string a couple of days ago.
And the issue is that the missing strings were translated in previous version

**Comment by philmmanjaro** [comment]
If the release is already out then the translations will be pulled in for the next one. Let me check.

**Comment by linlinger** [comment]
[calamares_zh_CN.ts.zip](https://github.com/calamares/calamares/files/7159692/calamares_zh_CN.ts.zip)
And this is the file I translated. I did some thing to make sure that QT linguist shows no warning

**Comment by philmmanjaro** [comment]
Here is the history:

https://github.com/calamares/calamares/commits/calamares/lang/calamares_zh_CN.ts
https://github.com/calamares/calamares/commits/calamares/lang/calamares_zh_HK.ts
https://github.com/calamares/calamares/commits/calamares/lang/calamares_zh_TW.ts

Simply check if your string changes are in.

**Comment by linlinger** [comment]
Thanks! It look like my changes are in

**Comment by philmmanjaro** [comment]
Before we do a release we normally pull the translations to have them in. We just had vacation time here in Europe. That's why it took longer to get your changes in.

**Comment by adriaandegroot** [comment]
As a general rule, the translations lag behind Calamares by about 1 release -- which isn't that much of an issue when short cycle releases happen every two weeks. There's another release scheduled in three days. The background is that strings *do* change in Calamares, and the translators need to be informed that the strings exist, some days pass, and then translations are pulled into Calamares and put into a release. When changes to strings land close to a release, translations break. I try to avoid that, but it's not always possible (well, it **is** possible, by putting in a serious string freeze and doing releases with updated strings for already-released versions and asking distro's to not chase the latest Calamares release -- that would be a fairly big change to project workflow, which I don't think I can manage on my own).

Anyway, the string updates are here, and there should be better overall translation of some corner cases in 3.2.43

**Comment by linlinger** [comment]
Tanks for telling me this and I will not chase the latest release.  And I wanna know that when there would be a new release. And I would like to make sure Chinese strings are fully translated. I think this is what I can do now
