### ISSUE TITLE
3.2.19 fatal regressions

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1324]
- [x] `/etc/hostname` isn't overwritten, because CreateTargetFile doesn't have an overwrite mode. This is breaking when the unsquahsed FS already has that file because the users's hostname isn't written.
 - [x] `udevadm` may live elsewhere, so that path should be configurable somehow. Or run it without the full path.
 - [x] Lubuntu reports that the "Set administrator password" textboxes show up, even when *setRootPassword: false* is in the configs.
 - [x] Manjaro reports resume hook is set even if there is no swap or resume kernel parameter

**Comment by adriaandegroot** [comment]
(the presence of these fatal regressions, plus translation updates in Latvian and Chinese, means a 3.2.19.1 will have to be rolled, monday)

**Comment by monetaryabyss** [comment]
This is a [link](https://bugs.launchpad.net/calamares/+bug/1864352) to the downstream (L)Ubuntu bug for the hostname issue.

**Comment by wxl** [comment]
The `udevadm` path is the conclusion is now part and parcel of the [downstream bug](https://bugs.launchpad.net/calamares/+bug/1851188) which was previously linked to #1170.

**Comment by adriaandegroot** [comment]
What changed wrt. the "Set administrator password" is that **previously**, the *Reuse password* checkbox was only modified if you actually had an entry in the config file for it. No config entry, no checkbox -- and the code that handles toggling of the checkbox, also does something with the visibility **without checking** for the other fields.

Now, the checkbox is always explicitly set; if you don't have a config entry, it is explicitly set to the default (which is false). But that triggers the code that handles toggling of the checkbox!

**Comment by philmmanjaro** [comment]
[possible solution](https://gitlab.manjaro.org/applications/calamares/commit/ee99e34e25ed1224504bbef93fb41e5cad6b0ee8) if I got the **resume hook** issue right ...

**Comment by adriaandegroot** [comment]
Thanks @wxl @philmmanjaro (and other Lubuntu and Manjaro contributors) for helping out with good bug reports and explanations on IRC and in testing the fixes. We're good to go.
