### ISSUE TITLE
Calamares UEFI and boot flags

### ISSUE THREAD

**Issue by robin0800** [calamares/calamares#1327]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
Calamares version 3.2.19.1-1
Wrong flag being set in manual partitioning if format is chosen

**To Reproduce**
1.Use Calamares installer on a UEFI system
2. Choose manual partitioning
3. Select boot flag
Does this also set esp flag?
Choose to format the fat32 partition
4. Checking in gparted the flag set is msftres  

**Expected behavior**
boot and esp flags should be set.

**Screenshots and Logs**

**Additional context**
Would like to see the esp flag back but not as important as the above bug.
https://forum.manjaro.org/t/unstable-update-2020-02-14-blender-2-82-firefox-dev-python-haskell-mesa-19-3-4-breakage-expected/124285/12 refers

**Comment by philmmanjaro** [comment]
@robin0800 can you check if it is reproducible with **Manjaro 19.0** release?

**Comment by abucodonosor** [comment]
@philmmanjaro 

kpmcore4 changed that, it is not a bug. 

See https://github.com/calamares/calamares/issues/1147#issuecomment-493367185.

**Comment by philmmanjaro** [comment]
@robin0800 please see also here: https://github.com/calamares/calamares/issues/891#issuecomment-493750783 and https://github.com/calamares/calamares/issues/1147#issuecomment-493367185
