### ISSUE TITLE
add tags in logs

### ISSUE THREAD

**Issue by wxl** [calamares/calamares#1328]
**Is your feature request related to a problem? Please describe.**
It's hard to pick through the logs for useful info. Certainly hard to grep through.

**Describe the solution you'd like**
Most importantly, I'd like to see each line have a module name and a job name. Example:

    01:51:59 [6]: [welcome] [GeneralRequirements] All requirements have been checked.

As an addition, it might be nice to use markers like e.g. Xorg logs have, e.g. `(WW)` for warnings and `(EE)` for errors, or something similar.

**Describe alternatives you've considered**
Wasting all my time trying to figure out which line is related to which job and module :rofl: 

**Additional context**
I wasted a bunch of time (other people's) trying to diagnose an issue that I could have found much easier if this sort of organization was there. I had looked at the logs a bunch of times and didn't notice the problem. Once I had identified the problem, it was pretty much fixed immediately.

**Comment by adriaandegroot** [comment]
> As an addition, it might be nice to use markers like e.g. Xorg logs have, e.g. (WW) for warnings and (EE) for errors, or something similar.

They already do: the log **level** is there in square brackets after the time (this list of values from `Logger.h`):
```
    LOGERROR = 1,
    LOGWARNING = 2,
    LOGINFO = 3,
    LOGEXTRA = 5,
    LOGDEBUG = 6,
    LOGVERBOSE = 8
```
In addition, error and warning specifically log "ERROR:" or "WARNING:", although that only works if the code uses the "standard" debugging calls (`cWarning()` and `cError()`, and doesn't go out of its way to create a logging object of a given level via the base-class `CLog`).

**Comment by adriaandegroot** [comment]
See commit log, but roughly this: debug calls -- ones that don't do something special in the code -- now print Q_FUNC_INFO as well, which should help chase things considerably. It'll bloat the executable and the size of the log, though.
