### ISSUE TITLE
Packages Module Reports Incorrect Output for Remove / Try Remove Operations

### ISSUE THREAD

**Issue by salientos** [calamares/calamares#1330]
**Describe the bug**
The packages module is reporting the incorrect output for the configured operation. 

**To Reproduce**
I am using the following configuration:

`operations:
  - remove:
    - calamares
  - try_remove:
    - arch-install-scripts ... (snipped for brevity but there are several here for removal)`

**Expected behavior**
I would expect the output of this operation to report 'Removing one package.' or 'Removing [number] packages' and not 'Install Packages' as is the case now.

Unless, of course, i'm missing something here?

**Comment by abucodonosor** [comment]
It does say that, however as long you rsync over you Install first.

 https://github.com/calamares/calamares/blob/master/src/modules/packages/main.py#L58-L75

**Comment by salientos** [comment]
If this is the intended behaviour then that's fine! Thanks.

**Comment by adriaandegroot** [comment]
Thing is, the *packages* module doesn't actually cause the progress bar to update with the message installing-so-much or removing-so-much, so the original report is valid.
