### ISSUE TITLE
Module umount reports an error - signals Sigpipe 13

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1333]
Building experience of ArcoLinux - 18 isos
Calamares 3.2.18
Once in a while the iso will end in an error in the umount module BUT the system is by then already installed. So the installation is working.
![calamares-openbox](https://user-images.githubusercontent.com/36679406/75759473-ea133a80-5d35-11ea-8a9c-d8b56f981eb2.png)

**Comment by abucodonosor** [comment]
Please test that with the latest released code.

**Comment by adriaandegroot** [comment]
SIGPIPE is an interesting way for umount to die; perhaps it's trying to print an error message? this issue illustrates one reason why I don't like the python modules: they are very very variable in how they run processes, and where, and what kiind of error-checking they do. Here, `subprocess.check_call()` is used, depriving us of a chance to do useful error reporting, as well as being fragile.

In any case one might think to try umount more than once, or using the mount-service that's in Calamares now (that means: at some point this whole umount module needs to become obsolete).

**Comment by adriaandegroot** [comment]
Closing this one as "not reproduced"
