### ISSUE TITLE
During unsquashing we see a glitch in progress after 26%

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#1335]
**Version**
- 3.2.20-1 on Manjaro 19.0.2 ISOs

**Describe the bug**
During unsquashing we see a glitch in progress after 26%

**To Reproduce**
1. Install as normal
2. Keep attention to the progressbar during unsquash of the filesystem
3. After 26% the progress goes up to ca. 45% to drop down to 26% again

**Expected behavior**
Smooth progress without glitches

**Comment by adriaandegroot** [comment]
What's happening is that the progress is being calculated once over the first squashfs (rootfs) and then resetting when the second one is unsquashed.
