### ISSUE TITLE
Boost.Python error in job "bootloader".

### ISSUE THREAD

**Issue by marco-parillo** [calamares/calamares#1337]
**Error Panel**

```
Command 'grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Manjaro --force' returned non-zero exit status 1.
Installing for x86_64-efi platform. Could not prepare Boot variable: No space left on device grub-install: error: efibootmgr failed to register the boot entry: Input/output error.

Traceback:
File "/usr/lib/calamares/modules/bootloader/main.py", line 457, in run
    prepare_bootloader(fw_type)

  File "/usr/lib/calamares/modules/bootloader/main.py", line 429, in prepare_bootloader
    install_grub(efi_directory, fw_type)

  File "/usr/lib/calamares/modules/bootloader/main.py", line 293, in install_grub
    check_target_env_call([libcalamares.job.configuration["grubInstall"],

  File "<string>", line 6, in <module>
```
**System Information**

```
$ inxi -Fxxxz
System:    Host: manjaro Kernel: 5.4.23-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.1 Desktop: KDE Plasma 5.17.5 
           tk: Qt 5.14.1 wm: kwin_x11 dm: SDDM Distro: Manjaro Linux 
Machine:   Type: Laptop System: Hewlett-Packard product: HP EliteBook 8460p v: A0001D02 serial: <filter> Chassis: type: 10 
           serial: <filter> 
           Mobo: Hewlett-Packard model: 161C v: KBC Version 97.4E serial: <filter> UEFI: Hewlett-Packard v: 68SCF Ver. F.63 
           date: 05/27/2016 
Battery:   ID-1: BAT0 charge: 40.4 Wh condition: 42.1/42.1 Wh (100%) volts: 12.5/11.1 model: Hewlett-Packard Primary 
           type: Li-ion serial: <filter> status: Unknown 
CPU:       Topology: Dual Core model: Intel Core i5-2540M bits: 64 type: MT MCP arch: Sandy Bridge rev: 7 L2 cache: 3072 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 20761 
           Speed: 798 MHz min/max: 800/3300 MHz Core speeds (MHz): 1: 798 2: 798 3: 798 4: 798 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Seymour [Radeon HD 6400M/7400M Series] vendor: Hewlett-Packard 
           driver: radeon v: kernel bus ID: 01:00.0 chip ID: 1002:6760 
           Display: x11 server: X.Org 1.20.7 driver: radeon FAILED: ati unloaded: modesetting alternate: fbdev,vesa 
           compositor: kwin_x11 resolution: 1600x900~60Hz 
           OpenGL: renderer: AMD CAICOS (DRM 2.50.0 / 5.4.23-1-MANJARO LLVM 9.0.1) v: 3.3 Mesa 19.3.4 compat-v: 3.1 
           direct render: Yes 
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio vendor: Hewlett-Packard driver: snd_hda_intel 
           v: kernel bus ID: 00:1b.0 chip ID: 8086:1c20 
           Sound Server: ALSA v: k5.4.23-1-MANJARO 
Network:   Device-1: Intel 82579LM Gigabit Network vendor: Hewlett-Packard driver: e1000e v: 3.2.6-k port: 5020 
           bus ID: 00:19.0 chip ID: 8086:1502 
           IF: enp0s25 state: down mac: <filter> 
           Device-2: Intel Centrino Ultimate-N 6300 driver: iwlwifi v: kernel port: 4000 bus ID: 25:00.0 chip ID: 8086:4238 
           IF: wlo1 state: up mac: <filter> 
Drives:    Local Storage: total: 126.34 GiB used: 7.13 GiB (5.6%) 
           ID-1: /dev/sda vendor: Team model: T2535T120G size: 111.79 GiB speed: 6.0 Gb/s serial: <filter> rev: 2A0 
           scheme: GPT 
           ID-2: /dev/sdb type: USB model: General USB Flash Disk size: 14.55 GiB serial: <filter> rev: 1100 scheme: MBR 
Partition: ID-1: / size: 5.79 GiB used: 183.5 MiB (3.1%) fs: overlay source: ERR-102 
Sensors:   System Temperatures: cpu: 48.0 C mobo: N/A gpu: radeon temp: 0 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 212 Uptime: 32m Memory: 7.72 GiB used: 2.01 GiB (26.0%) Init: systemd v: 242 Compilers: gcc: 9.2.1 
           Shell: bash v: 5.0.16 running in: konsole inxi: 3.0.37 


$  sudo parted -l
Model: ATA TEAM T2535T120G (scsi)
Disk /dev/sda: 120GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End    Size    File system     Name  Flags
 1      2097kB  317MB  315MB   fat32                 boot, esp
 2      317MB   111GB  110GB   ext4
 3      111GB   120GB  9449MB  linux-swap(v1)        swap


Model: General USB Flash Disk (scsi)
Disk /dev/sdb: 15.6GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start   End     Size    Type     File system  Flags
 2      3044MB  3048MB  4194kB  primary               esp

$ test -d /sys/firmware/efi && echo UEFI || echo BIOS
UEFI

$ efibootmgr
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0001,0002
Boot0000* Notebook Upgrade Bay
Boot0001* Notebook Hard Drive
Boot0002* USB Hard Drive 1 - General USB Flash Disk
Boot0003* Notebook Ethernet
```

**Comment by marco-parillo** [comment]
[Uploading Log…]()
Log from sudo -E calamares -d

**Comment by marco-parillo** [comment]
![Screenshot_20200310_180534](https://user-images.githubusercontent.com/32338352/76365757-0dcf1580-6320-11ea-963a-f311328d2cf1.png)
These are the options I selected.

**Comment by marco-parillo** [comment]
[Log.txt](https://github.com/calamares/calamares/files/4315149/Log.txt)

Log from sudo -E calamares -d

**Comment by philmmanjaro** [comment]
The latest **Calamares** we always add to [KDE-Dev](https://osdn.net/projects/manjaro-community/storage/kde-dev/20.0/). Please check if it still is the case. **Manjaro 18.1.5** used **kpmcore3**. Is it possible to install Manjaro with that medium? 19.0.2 was tested in VirtualBox with automated installation. Manual partitioning was also possible. Seems to be an edge case.

**Comment by philmmanjaro** [comment]
Similar issues for: `efibootmgr failed to register the boot entry: Input/output error. - no space left`

https://www.linuxquestions.org/questions/linux-laptop-and-netbook-25/grub-install-results-in-unbootable-laptop-4175616572/
https://bbs.archlinux.org/viewtopic.php?id=252598
https://forum.manjaro.org/t/113762
https://github.com/rhboot/efibootmgr/issues/100

... I might need to patch **grub** once more ...

**Comment by philmmanjaro** [comment]
The problem is not with your EFI partition but the EFI NVRAM. Try disabling secure boot in the UEFIand reset the secure boot configuration as well including the stored keys, if you've got that option.

Likely you got a faulty UEFI and should look for a BIOS update which will fix this.

**Comment by philmmanjaro** [comment]
See also [here](https://forum.manjaro.org/t/calamares-does-anybody-know-what-is-going-on/128517) for more details ...

**Comment by marco-parillo** [comment]
> The latest **Calamares** we always add to [KDE-Dev](https://osdn.net/projects/manjaro-community/storage/kde-dev/20.0/). Please check if it still is the case. **Manjaro 18.1.5** used **kpmcore3**. Is it possible to install Manjaro with that medium? 19.0.2 was tested in VirtualBox with automated installation. Manual partitioning was also possible. Seems to be an edge case.

Yes, KDE-Dev worked.

**Comment by philmmanjaro** [comment]
The question is what changed. As installing that part of the bootloader is in your EFI NVRAM. I'll check if **efibootmgr** package change or something ...

**Comment by philmmanjaro** [comment]
@marco-parillo can you do me a favour and reinstall 19.0.2 KDE ISO on your device and only change the **Calamares** installer by issuing the following before start:

```
sudo pacman -U http://repo.manjaro.org.uk/pool/overlay/calamares-git-3.2.21.r7386.6af4da1db-1-x86_64.pkg.tar.zst
sudo -E calamares -d
```

Also share the full install log. If it has issues to start, please ping me again, so I rebuild **Calamares** for stable branch. Comparing the packages overall only showed me that Calamares is different.

**Comment by philmmanjaro** [comment]
I've uploaded **19.0.2-minimal-200311** of KDE, XFCE and Gnome. Please confirm if that fixes the issue. It includes updated **Calamares**.

**Comment by abucodonosor** [comment]
@philmmanjaro 

I can't see how this has something to do with calamares itself. The error is from 
grub2/efibootmgr, possible BIOS and calamares just return the errors.

**Comment by philmmanjaro** [comment]
I've also no clue why an updated **Calamares** works. Lets see what happens ...

**Comment by philmmanjaro** [comment]
19.0.2-2020-03-11 is now online for all major editions (Gnome, KDE, XFCE). Feedback appreciated.

**Comment by marco-parillo** [comment]
In both the [full version dated 200311](https://osdn.net/projects/manjaro/storage/kde/19.0.2/) as well as the [minimal version also dated 20311](https://osdn.net/projects/manjaro/storage/kde/19.0.2/minimal/)?

**Comment by marco-parillo** [comment]
I successfully installed the full version.

**Comment by philmmanjaro** [comment]
Both versions have the new **Calamares** installer. The weird thing is. Why does an update help here. Anyway. I'm glad that a re-release made it possible to install Manjaro on more Hardware.

**Comment by l-ucky** [comment]
I am having the exact same issue while installing Arcolinux v21.03.1-x86_64.iso using Calamares.
* Kernel: Linux -zen, Linux, Linux-NVIDIA
* NVIDIA GeForce 2060 Super
* AMD Ryzen 7 3700X
* ASUS B550 Motherboard
* 16gb RAM
* NVMe Western Digital 500Gb
* SSD ADATA SU720

I have been trying to use Calamares on both NVMe and SSD today, and I have the eexact same failure on both hard drive types.
![image](https://user-images.githubusercontent.com/66523959/112206444-b3d08380-8bf4-11eb-8ca9-1e4975d26f3c.png)

**Comment by demmm** [comment]
Last comment, duplicate of https://github.com/calamares/calamares/issues/1650
Hardware issue again?  Checked for UEFI/BIOS update?  Issue will stay closed.

**Comment by Roy-Wanyoike** [comment]
> Similar issues for: `efibootmgr failed to register the boot entry: Input/output error. - no space left`
> 
> https://www.linuxquestions.org/questions/linux-laptop-and-netbook-25/grub-install-results-in-unbootable-laptop-4175616572/ https://bbs.archlinux.org/viewtopic.php?id=252598 https://forum.manjaro.org/t/113762 [rhboot/efibootmgr#100](https://github.com/rhboot/efibootmgr/issues/100)
> 
> ... I might need to patch **grub** once more ...

am still getting an issue with this "Boost.python error in job bootloader"

**Comment by Roy-Wanyoike** [comment]
I think this is an issue related with Calmares since i have experienced in five different laptops. Its affecting when am installing parrot OS
