### ISSUE TITLE
Improve default QML for sidebar

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1340]
The sidebar can have a QML version now. This is configurable at runtime, by setting `sidebar: qml` in `branding.desc`. The QML is loaded from the branding directory (file `calamares-sidebar.qml`). There's also a pre-compiled one in QRC, which is both basic and ugly.

- [x] The model doesn't correctly signal when the current page has changed (which would change both `current` and `completed` roles of data).
- [x] The QML is a very basic Text item, which shows the name of the step. It should have the same highlighting (current-step should have a different color) as the widget version, and adjust text-sizes for long-winded steps.

For QML-development purposes, you can build Calamares once, copy QML into `build/src/branding/default/calamares-sidebar.qml` and then edit that file. Re-start Calamares each time to see the new QML in action. To update the compiled-in QML once things look better, copy the QML file into `src/calamares/calamares-sidebar.qml` and it will be compiled in.

**Comment by adriaandegroot** [comment]
@milohr Can you chase this? `ViewManager.cpp` holds the model used for this, and to me it looks like `emit currentStepChanged()` is the bit that should also emit model-changed signals for the current and completed roles (both going forward and back).

**Comment by milohr** [comment]
Checking this now

**Comment by milohr** [comment]
Working on it now. A question, would it be possible to hide the sidebar cimpletely and intead draw the progress in the actual views?

**Comment by adriaandegroot** [comment]
Yes, the sidebar is configurable (widget, qml, off), that was one of the changes in 3.2.21 release:

https://github.com/calamares/calamares/blob/master/CHANGES#L37
https://github.com/calamares/calamares/blob/master/src/branding/default/branding.desc#L44

**Comment by milohr** [comment]
does the _current_ and _completed_ roles are any different then the currentStepIndex?
meaning: can the currentStepIndex be at index 4 and the indexes 1,2 or 3 can be no _completed_ ?
In case the currentStepIndex is different form each step being marked as completed, what does it mean that a step is completed? that all requirements are met? 

in case the currentStepIndex already indicates that the past steps are completed we could use that and not have to use the custom completed or current roles.

**Comment by milohr** [comment]
by exposing this property:
  Q_PROPERTY( int currentStepIndex READ currentStepIndex NOTIFY currentStepChanged FINAL )
and withouth the current or completed roles, one can do something like this:
![Peek 2020-03-29 11-23](https://user-images.githubusercontent.com/5911329/77854394-c239ba00-71af-11ea-8dd9-2b6a2ab96227.gif)

**Comment by adriaandegroot** [comment]
That'd do it (see *issue-1340* branch off of master). The only tricky bit is that the QWidgets delegate needs to be handled as well (it doesn't have direct access to the currentIndex, but that can be fixed).

**Comment by adriaandegroot** [comment]
(Marked closed, although the example QML is still really really basic -- at least it shows progress; it'd still be worthwhile to polish this QML up so it has nicer font, colors -- maybe following the branding scheme -- and includes a logo.)
