### ISSUE TITLE
netinstall module: description per application

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1342]
ArcoLinuxD 20.4.3
Calamares 3.2.20
We will be using 6 different netmodules to install a diversity of packages.
Users will recognize some applications but not all.
Is it possible to add a description behind the application?
![description](https://user-images.githubusercontent.com/36679406/76971178-239a9700-692d-11ea-94b1-9daa64f5c1f9.png)

**Comment by kkofler** [comment]
You can make the applications subgroups.

**Comment by adriaandegroot** [comment]
I really don't want to make Calamares another package-manager-information-displayer. As Kevin points out, you can use subgroups for this -- like you have with *zsh* for instance -- and put a single package into every subgroup. At that point, though, I'd really suggest moving to packagechooser which does support this.

Or develop a module that embeds a Discover UI, and then uses a backend inside the chroot.
