### ISSUE TITLE
Netinstall module : extra parameter - selected, visible and unchangeable

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1343]
ArcoLinux 20.4.3
Calamares 3.2.20
Currently the rule the show the applications in the netinstall is the following.

If the application is on the iso (package list) we do not show it in Calamares as it will be installed anyway whether they would select or deselect it? Is that correct?

The netinstall will only install more applications but never less. Is that correct?

The user will take a look at all the packages and they see a lot of software is "missing". It is not in Calamares however it is on the iso. This adds to the confusion and we get questions about it.

Hence our question.

Can you make it possible to add packages with a parameter so that 

1. the user can see it will be installed on the system
2. the user can not change it (gray and/or italic)
3. the packages are never hidden - always visible
4. the packages are selected

Zsh is always installed on the iso - whether the user wants to or not.
We would like that to become visible in Calamares somehow.

![request-calamares](https://user-images.githubusercontent.com/36679406/76973198-eaaff180-692f-11ea-918b-3b0376ddfa82.png)

**Comment by erikdubois** [comment]
You could add the option not to install but just to display the text. Then the back-end will not install what is already installed on the iso.
