### ISSUE TITLE
Navigation from QML

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1344]
The navigation parts (back, next, quit) are now widgets -- even when the QML sidebar is enabled -- so that should be selectable as well.

 - [x] Configuration setting for *navigation*, like the *sidebar*
 - [x] Switchable navigation part
 - [ ] Basic QML for navigation
 - [ ] Connect `ViewManager` navigation signals to QML (or the other way around)
 - [ ] More fancy QML for navigation (optional)

**Comment by adriaandegroot** [comment]
![Screenshot_20200402_172059](https://user-images.githubusercontent.com/19431457/78266666-60a68200-7506-11ea-8e45-2a16b923286f.png)

With QML sidebar and navigation and @demmm 's work on the *welcomeq* module.

**Comment by milohr** [comment]
cool
