### ISSUE TITLE
Grubcfg error

### ISSUE THREAD

**Issue by Hayao0819** [calamares/calamares#1349]
**Describe the bug**
The following screenshot error occurred in Grubcfg on ArchLinux.
We report Grubcfg on the downstream side because we thought it was an upstream problem without any changes.

**To Reproduce**
This error occurs when Calamares with [the source code](https://github.com/SereneTeam/alterlinux-calamares) is built with [this PKGBUILD](https://github.com/SereneTeam/alterlinux-pkgbuilds/blob/master/stable/alterlinux-calamares/PKGBUILD) and installed on ArchLinux.

**Screenshots and Logs**
![image](https://user-images.githubusercontent.com/32128205/77275171-04b84e00-6cfb-11ea-8c40-05cf54ceaa32.png)

The version of Calamares that occurred is the latest master (2eb84e2de1dc2585ee0bdc90d8ae48cc9907165b).

**Comment by kkofler** [comment]
What are the contents of your `/etc/default/grub` before Calamares tries to modify it?

**Comment by abucodonosor** [comment]
Also, can you post the installation log, please?

**Comment by adriaandegroot** [comment]
The full line is

```
                kernel_cmd = "GRUB_CMDLINE_LINUX_DEFAULT=\"{!s}\"".format(
                    " ".join(kernel_params)
                    )
```

So something is sneaking in a tuple into those params .. I don't see anything stand out though. Unfortunately the log won't show you what **is** in those params; Kevin's guess that the existing file might be an issue seems on-point though (a split() call gone wrong?)

**Comment by Hayao0819** [comment]
The extension .txt has been added for uploading to GitHub.
[grub.txt](https://github.com/calamares/calamares/files/4372665/grub.txt)

I mentioned earlier that no modifications were made, but that was a mistake.
Only one place adds the kernel parameters when Plymouth is enabled.
[Here](https://github.com/SereneTeam/alterlinux-calamares/blob/master/src/modules/grubcfg/main.py#L83) is the source code.

**Comment by abucodonosor** [comment]
Well and now with your changes, you broke it. If you want to keep it that way you have to change L132 too, that need become .extend().

**Comment by Hayao0819** [comment]
Thank you
It was a problem downstream, not upstream.
I will fix it.
