### ISSUE TITLE
If the last page is Set up, disable-cancel-during-exec is ignored

### ISSUE THREAD

**Issue by feren** [calamares/calamares#1351]
**Describe the bug**
When in OEM Setup mode, on a configuration where Set up is the last step in the installer and disable-cancel-during-exec is enabled the "Done" button remains enabled during the setting up procedure despite being configured to be disabled during exec.
64-Bit, EFI, N/A

**To Reproduce**
1. Configure Calamares to have install be the last part of installation with no finish page at end, and also have disable-cancel-during-exec enabled
2. Open Calamares and proceed as normal
3. When installing, Done is sensitive and closes the installer regardless of what it was doing on the installation process

**Expected behavior**
The "Done" button will be insensitive, the window can't be closed as normal, and when it's all done Calamares will close itself automatically.

**Comment by adriaandegroot** [comment]
Example `settings.conf`:

```
sequence:
- show:
  - welcome
  - summary
- exec:
  - dummypython
  - dummyprocess
#- show:
#  - finished
disable-cancel-during-exec: true
```

(Those two dummies give you about 10 seconds of "install time", and you can uncomment the second show-section with *finished* to see the expected behavior)
