### ISSUE TITLE
Calamares 3.2.21 fails to get language (first screen)

### ISSUE THREAD

**Issue by Portergos** [calamares/calamares#1361]
Hi! 
New version is failing to get the correct language for the installer, i already checked the url https://geoip.kde.org/v1/ubiquity (settings.conf) and is working fine. I also tried using xml and json, no luck.

I'm not sure if there is a new config file for doing that or only settings.conf?

Interesting to notice the timezone is properly set as usual (second "slide") (locale.conf ok )

We even tried using the latest ckbcomp just in case, didn't fix the issue.

Can you confirm if this is happening with other distros too?

Thank you for you attention!

**Comment by killajoe** [comment]
@Portergos is one of the devs from https://github.com/endeavouros-team too ;)

**Comment by philmmanjaro** [comment]
**welcome.conf** setting: https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/-/blob/master/lib/util-yaml.sh#L190-195
**locale.conf** setting: https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/-/blob/master/lib/util-yaml.sh#L265-270

each setting is using different values ...

**Comment by killajoe** [comment]
> **welcome.conf** setting: https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/-/blob/master/lib/util-yaml.sh#L190-195
> **locale.conf** setting: https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/-/blob/master/lib/util-yaml.sh#L265-270
> 
> each setting is using different values ...

thanks for jumping in here @philmmanjaro 
this **util-yaml.sh** is a default file from calamares sources or created for manjaro?

**Comment by Portergos** [comment]
> **welcome.conf** setting: https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/-/blob/master/lib/util-yaml.sh#L190-195
> **locale.conf** setting: https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/-/blob/master/lib/util-yaml.sh#L265-270
> 
> each setting is using different values ...

we tested using ipapi.co but doesn't work either. The thing is 3.2.20 detects language fine, 3.2.21 doesn't work. Bellow is 3.2.20 version, to all others the language is always english.

https://i.imgur.com/GRA8P3p.png

**Comment by philmmanjaro** [comment]
Can't reproduce your issue. Double-check your settings ...

![VirtualBox_Manjaro_30_03_2020_18_56_48](https://user-images.githubusercontent.com/5050022/77940029-555e1700-72b8-11ea-99e8-cfd8bc197d7b.png)

Feel free to [test](https://osdn.net/projects/manjaro/storage/gnome/19.1.0-pre2/) it out.

**Comment by adriaandegroot** [comment]
I've looked at the [config file](https://github.com/endeavouros-team/Calamares_current/blob/master/src/modules/welcome/welcome.conf_online) EndeavourOS is using, and that looks OK to me -- especially if the same config file works in Calamares 3.2.20 and not in 3.2.21.

What you can always do is just `curl` the GeoIP URL to see what it thinks of you: here's what it looks like for me:

```
[adridg@beastie .../git/calamares]$ curl https://geoip.kde.org/v1/ubiquity
<Response><Ip>8.8.8.8</Ip><Status>OK</Status><CountryCode>NL</CountryCode><CountryCode3></CountryCode3><CountryName>Netherlands</CountryName><RegionCode>ZH</RegionCode><RegionName>South Holland</RegionName><City>The Hague</City><ZipPostalCode>2596</ZipPostalCode><Latitude>52.0937</Latitude><Longitude>4.3205</Longitude><AreaCode>0</AreaCode><TimeZone>Europe/Amsterdam</TimeZone></Response>
```

But looking at the log @killajoe posted, I see this:

```
09:51:55 [6]: WelcomeViewStep::setConfigurationMap(const QVariantMap&)::<lambda()>
    GeoIP result for welcome= "DE" 
09:51:55 [6]: void Config::setLocaleIndex(const int&)
    Selected locale QLocale(German, Latin, Germany) 
09:51:55 [6]:  ..  Branding using default, system locale not found: "de_DE" 
09:51:55 [6]:  ..  No translation for "tz_" "de_DE" using default (en) 
09:51:55 [6]:  ..  Loaded QRC translation "calamares_" "de_DE" 
```

Which tells me at least that @killajoe should be getting it in German automatically.

**Comment by Portergos** [comment]
Ok, it seems i got confused and didn't explained well...
As i see manjaro has the same problem, i tested your iso here and see the same.

here is a better screen the installer language is set properly but the "selection language box" is still english.

![image1](https://i.imgur.com/jm6kQL1.png)

![image2](https://i.imgur.com/fIgNPqG.png)

![image3](https://i.imgur.com/VwECQ2R.png)

**Comment by demmm** [comment]
Seeing the same issue on KaOS since moving from 3.2.19 to master (3.2.22).  If Calamares detects locale (Amsterdam > Dutch) and you want to switch to en_US, first time selecting that language does change the selection bar to American English, but language shown is still Dutch, on second time clicking, it actually changes.....

**Comment by philmmanjaro** [comment]
Maybe it started with https://github.com/calamares/calamares/commit/d7f7c16958efbe97dd1948d432572722806a8096 ... most likely based on some re-coding for configuration also used by [welcomeq].

**Comment by adriaandegroot** [comment]
Thanks for the detailed explanation -- that does make sense, that the switching-models-around part has confused the GeoIP-changes-the-language part.

**Comment by adriaandegroot** [comment]
.. I can reproduce the problem. Branch *issue-1361* is (for now) where things will be getting fixed. So far, a bunch of tech-debt cleanups; next up:

 - move unneeded warning message from requirements model back to welcome config (the model should not have an opinion on what its satisfaction state means)
 - do not apply retranslate to model
 - check retranslation of Config -- i think it isn't necessary, since the UI can have a retranslate slot and call into Config to get `tr()` strings
 - RequirementsModel::getEntry can leak memory
 - (*up to here was just more tech-debt*) the selection model for the language list should be updated when `setLocaleIndex()` is called
