### ISSUE TITLE
[welcome] about text variables mismatch

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#1370]
With 3.2.22 we introduced some text variables mismatch in **welcome** module.

![Bildschirmfoto_2020-04-09_11-08-32](https://user-images.githubusercontent.com/5050022/78878695-16b42380-7a53-11ea-943d-dd51bf9785ec.png)

**Comment by demmm** [comment]
FWIW, bug is not in calamares/src/modules/welcome/WelcomePage.cpp, I have a local branch that is even with the welcome module, but doesn't show this.
It does show here too on the master branch (calamares/src/libcalamares is ahead of my local branch).

**Comment by adriaandegroot** [comment]
This is something in the translation files; the **source** doesn't have those odd curlies, but the translation files **do**. You can see in 8a6925c5bea942469417c5c238432d78c9aaa02d -- I'm pretty sure that was just me running the usual Transifex extraction tools and committing the English result -- these curlies showed up, and then in b2106287a6ecc38875c5967d1cb4beec47b7795d all the translations got them pulled from Transifex -- even though the source string for each and every one of them does not have the curlies.

**Comment by adriaandegroot** [comment]
.. but if I look in Transifex **now**, the source is listed with curlies. I'll try to refresh the translations and see what happens.

**Comment by adriaandegroot** [comment]
I went a couple of rounds with the Transifex tools and now the translations look normal again.
