### ISSUE TITLE
FEATURE REQUEST: Passwordless LUKS encryptation

### ISSUE THREAD

**Issue by Zeioth** [calamares/calamares#1372]
LUKS passwords can be easily cracked by dictionary attacks. Instead, I suggest to give the users the chance to choose an USB stick to create a keyfile during the installation of Manjaro.

So they can use it to unlock the disk.

**Comment by abucodonosor** [comment]
And how this is more secure? Especially for ArchLinux based distros?

I doubt that will ever work on full encrypted installation but even if, you are not more or less secure since you have to expose the *key* path on the command line and probably will break anyway across reboots for a lot of people. AFAIK you need for ArchLinux this:

```
cryptkey=/dev/sdX:FS:/PATH_TO/secretkey

```

**Comment by Zeioth** [comment]
It is more secure for many reasons:

1. You don't need to introduce the password in front of people, which makes it strong against social engineering. You usually work surrounded by your peers and/or security cameras.
2. A keyfile is way harder to break using brute force than the 5-20 characters passphrase you offer right now.

Therefore the current system is not suitable for truly securing your data.

**Comment by Zeioth** [comment]
Also, personally I used 

`cryptkey=/dev/sdX:FS:/PATH_TO/secretkey`

On my Manjaro installation, but it seems to interfere to whatever Calamares did during the full disk encryption when I installed my system. I still see [the screen before the boot menu](https://www.youtube.com/watch?v=nfnE2yr3KMg) asking for password. How can I disable it?

**Comment by abucodonosor** [comment]
Nope is not more secure :-) You have to generate your key the same way calamares does,  unless you are using /dev/random with 4096byte key files, which you clearly do not use from your video.

> > How can I disable it?

Well edit crypttab and remove crypto_keyfile.bin from initrd.

Anyway that https://github.com/VfcD/P7/blob/master/README.md, is missing the 
'you could make it more secure' part. With that said, without you to 'hide' the key, one can very easily find it on your device, so no is not more secure at all.

How you'll hide the key? As an example, you can place the key between MBR and the first partition, etc, then use udev+an_script.

**Comment by Zeioth** [comment]
Actually yes, I generated my keyfile with

    dd if=/dev/urandom of=/mnt/usbkey/archkey bs=1024 count=4

Apart from that, I think I got it correctly. My cryptab looks like this

```
# <name>               				            	<device>                              		<password> 					<options>
luks-fe0ede32-da97-41d0-bc57-ca75cdf6aad7		UUID=fe0ede32-da97-41d0-bc57-ca75cdf6aad7	/mnt/usbkey/archkey	luks
```

Then I've re-generated initrd using

    sudo mkinitcpio -P && sudo grub-mkconfig -o /boot/grub/grub.cfg

But as I mentioned before, I still see the pre-grub password screen.

**Comment by Zeioth** [comment]
And your hiding key concept is very interesting, I'll research it as soon as I have this working correctly.

**Comment by abucodonosor** [comment]
Looks like you are using full encryption, I don't think you can unlock /boot that way,
since this solution need userspace ( udev and friends first ).

IOW, for that to work right you'll need a custom installation where you let /boot
unencrypted and unlock with USB for everything else.

**Comment by kkofler** [comment]
Calamares supports only full encryption. Unencrypted `/boot` is **not** supported and doing it manually will either not boot at all or be entirely insecure. See bug #1073 and bug #1311.

**Comment by abucodonosor** [comment]
@kkofler 

I know that, is why he needs some custom installation if he wants to have this USB unlock thing.

I don't think one can get Grub to read the key from USB but I am not 100% sure about that.

**Comment by Zeioth** [comment]
You helped me a big deal, thank you. Now I'm fired up. 

@abucodonosor do you know about a good source to document myself in the keyfile hiding method you described before?

And more importantly, in the post-grub checkings, do you know a way to make it stop asking for password when the keyfile is not available? This is the only point I actually need.

**Comment by abucodonosor** [comment]
@Zeioth 

After a quick search, I found that https://possiblelossofprecision.net/?p=300#3-hiding-key should give you some idea on how to do that.

As for grub asking for a pass when /boot is encrypted is normal. I don't know of any way to make it read from the USB or elsewhere, I need to do some research myself to see if that is possible at all. ( maybe some custom grub-core img but not sure on that either )

**Comment by abucodonosor** [comment]
@Zeioth 

Unfortunately, upstream grub does not have a keyfile support, however, there seems to be that:  http://grub.johnlane.ie/. See also https://github.com/johnlane/grub/issues/18 which has some fix for the latest grub source and suggest there is some AUR package for that.

**Comment by Zeioth** [comment]
What I want is to avoid the message 

    "Keyfile could not be opened, reverting to passphrase"

 I don't want it to revert to passphrase, I want to fail if there's no keyfile available.

**Comment by abucodonosor** [comment]
Which doesn't have anything to do with either calamares or grub :-)

https://git.archlinux.org/svntogit/packages.git/tree/trunk/hooks-encrypt?h=packages/cryptsetup#n33

**Comment by Zeioth** [comment]
Wow I'm surprised you were able to find that thanks. 

If I modify the source code and compile it myself I should be able to do it. It should be easier... But at least is doable.

Thank you again for everything, you helped me way more than you had to.

**Comment by Zeioth** [comment]
Guess what:

* The line you showed me [doesn't exist upstream](https://gitlab.com/cryptsetup/cryptsetup/-/issues/550), it is an arch only thing.
* So [I reported the problem to the owners of the package](https://bugs.archlinux.org/task/66190) and it should be solved in the future.

**Comment by Zeioth** [comment]
I'm gonna re-open this issue for the next reason:

Even if the maintainers of arch's cryptsetup package fix that issue, Calamares should still offer a way to create a luks encrypted disk without password out of the box.

Think about this scenario:
* Someone see how you introduce your luks password when you start the computer (a quite common scenario).
* He use a livecd to mount your disk.
* Now he has full access to your disk.

**Comment by abucodonosor** [comment]
Sorry but I am going to close this. You have to patch grub for that to work with *kind* full encryption and like @kkofler told already unencrypted /boot is not supported, which you'll need to have with stock grub in order for that to work.

However, think about this scenario ( ignoring the unencrypted /boot which is a security issue itself ):

 - Someone steals or have access to your USB ( which is more likely than someone can figure what you type on your keyboard )
- and you effed, no password needed, right?

There are many options to setup luks, including custom solution, but those are special cases and require special setup and like this one.

Moreover, your arguments are moot, it is not about security, in fact using a stock grub with this solution is less secure. Also, in fact, the whole point of any sort encryption is
to have a password the one or the other way and ideally requires you to type it.
Any *kind* automatization eg: scripts, auto-unlock, etc are a security issue on their own.  In your case is more convenient to not have to type the password, not about security.

**Comment by abucodonosor** [comment]
>EDIT: Now that I think about it... If the only way to boot into the system with a keyfile is by not encrypting /boot, but if you don't encrypt /boot then you are vulnerable to injections of code in the ramdisk. Then indeed, the current system is the only one truly secure, as long as no one know your password.

Exactly, for your setup to fully work you need a patched grub version, and that is not something we can add support for.

Hell, we cannot even add luks2 support right now since the first bits of that support exists just in grub git and not even complete by now.

**Comment by JoelStienlet** [comment]
Just some semantic precision that may be useful (here I'm talking about cryptography in general, not LUKS in particular): there is a common misconception that something should be encrypted to be protected against modification. This is totally false. What you actually need is authentication. You can authenticate unencrypted data. You can also corrupt encrypted data who aren't authenticated! (see for example [ECB mode of encryption](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation) to convince you of this)
For the sake of clarity I thought It was useful to point that out.
