### ISSUE TITLE
Problem when using automatic LUKS partitioning and BTRFS

### ISSUE THREAD

**Issue by UriHerrera** [calamares/calamares#1379]
**Describe the bug**
When using the automated options _erase disk_ and _replace partiiton_ and selecting _Encrypt system_ the resulting installation while successful does not complete the boot process. 

The partitioning is successful, it creates the key, and it asks me for the passphrase at boot up, but it doesn't seem to work, the boot process ends with the system dropping to busybox. 

Whereas if I change the filesystem to EXT4 in `partition.conf`, it works fine.

_Manually creating the partitions does work_, however. I had to create the ESP (/boot/efi and boot flag) first and then the BTRFS partition (mounted /, check the encrypt checkbox and add the passphrase).

**To Reproduce**
1. Open Calamares and click next until the options erase a disk or replace a partition are available.
2. Select one of the options followed by enabling the checkbox _Encrypt system_ and adding a passphrase. 
3. The system installation is successful but the installed system drops to busybox.

**Expected behavior**
Working installation when using the automated partitioning.

**Additional context**
Here's the `partitiion.conf` that I'm using: https://github.com/Nitrux/calamares-settings-nitrux/blob/master/etc/calamares/modules/partition.conf

And here's a link to the ISO where this file is used: https://osdn.net/projects/nitrux/downloads/72652/nitrux-stable-amd64_2020.03.27.iso/

**Comment by abucodonosor** [comment]
I did a virtualbox installation with that iso and it boots just fine with btrfs+luks, eg the default you have.

But in general, such an error just means the initrd is somehow broken/wrong.
It cannot unlock your luks partition(s) and drops you to an emergency shell.
That part is your Distribution, not calamares,

**Comment by adriaandegroot** [comment]
![image](https://user-images.githubusercontent.com/19431457/79619820-45df2a80-810e-11ea-8c29-1fd5d9f4a4f9.png)

In Dutch, because the GeoIP picked that.

**Comment by adriaandegroot** [comment]
(This is all in VBox, BTW)

 - reboot, "EFI boot failed; enter unlock password" (or something like that), so I enter password. There's no indication I'm entering the password, and after hitting enter there's a 10 second nothing-is-happening delay
 - **then** I get grub and can pick NX
 - it boots normally to the NX login manager

So I can't reproduce this, either :S

**Comment by UriHerrera** [comment]
I quadrupled test again, and it works, it must have been something else on my end.
