### ISSUE TITLE
Move welcome settings out of branding

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1384]
There's a bunch of settings in branding that only apply to the welcome module. The logo and wallpaper are meant to be used throughout, but banner sections and the logo are really welcome-page specific. They should move to `welcome.conf` entirely and be removed from the branding.

Similarly, the URLs for buttons should go to `welcome.conf` entirely, and be dropped from branding, with lots of code simplification to boot.

**Comment by kkofler** [comment]
This makes it harder for derivative distributions (e.g., Fedora Remix distributions) to rebrand Calamares and significantly complicates the Fedora Calamares packaging. Currently, all the settings that remix distributions have to rebrand are in one place, and the packaging can even automatically generate the branding (though the remix can customize it if wanted or needed), picking up the logos from the expected file system locations for Fedora and remixes. Your proposal would mean having 2 separate configurations to customize, and make the centralized branding fairly pointless.

**Comment by adriaandegroot** [comment]
You're saying it's easier to change the `branding.desc` file than `welcome.conf` because the *functionality* settings in welcome are shared across derivatives, while the branding settings are unique to each individual derivative.

That suggests taking a different tack: move branding settings out of welcome. Make sure that all the relevant settings **can** be done in branding.

After writing this I realise that it might be desirable to have the same buttons on the *finished* page as well (or at least the release notes, known issues ones) so there's a stronger reason to split the functional settings from the branding / string-settings.

**Comment by adriaandegroot** [comment]
So to be clear, the purpose now is:

 - [ ] put donate URL in branding
 - [ ] remove dual URL-or-bool handling from `welcome.conf` for the *show...Url* keys

**Comment by adriaandegroot** [comment]
Close because it would be weirdly incompatible in Calamares 3.3 series.
