### ISSUE TITLE
Button Back and Next are not needed during install process.

### ISSUE THREAD

**Issue by Portergos** [calamares/calamares#1388]
**To Reproduce**
After selecting all options and starting the install process buttons Back, Next and Cancel are available.

**Expected behavior**
Only Cancel button is needed.

**Screenshots and Logs**
![button_view](https://i.imgur.com/tm7l5Mz.png)

Regards,
EndeavourOS Team.

**Comment by adriaandegroot** [comment]
Hacktoberfest 2020 has not yet started, but this is a good kind of issue to do for it.

## Procedural

- [ ]  Make sure you can compile Calamares locally (see https://github.com/calamares/calamares/blob/calamares/CONTRIBUTING.md, which will point you onwards to the wiki)
- [ ]  Some relevant sources are in https://github.com/calamares/calamares/tree/calamares/src/calamares/CalamaresWindow.cpp ; make a branch, add your copyright statement to one of the .cpp files and add your name to top-level CHANGES, then start a PR with WIP in the title

## Functional

- [ ] The ViewManager class has signals `quitVisibleChanged()` and `quitLabelChanged()` (and others) . Those are not very meaningful -- the names are tied to what they do, not what they're for. It might be nice to add meaningfully-named signals (e.g. "installStarted" and "installFinished").
- [ ] Add suitable configuration options, next to the existing *disable-cancel* and similar in `settings.conf` to control whether the next and prev buttons are shown. You may argue that *disable-cancel-during-exec* is already the right signal for that.
- [ ] Connect the signal to the navigation panels -- both QML and widgets! -- and handle the hide/show behavior there.

A very minimal implementation would just hook up `quitEnabledChanged()` to the buttons `visible()` slots.

## Extras

I can't think of anything extra to do with this feature.

## Post-Procedural

Feel free to push to the PR branch regularly; this shows how your progress is and allows early comments. Please stick to the commit-message style used in the rest of Calamares; do write out what-and-why with commits. It's OK to leave fixme's around for later in the branch and we can coordinate force-pushes if need be.

**Comment by demmm** [comment]
Implemented, shouldn't this be closed?

**Comment by adriaandegroot** [comment]
I think it even works in the QML navigation, too.

**Comment by demmm** [comment]
>I think it even works in the QML navigation, too.

Just for the record, I **know** it works in QML navigation.
