### ISSUE TITLE
Calamares wants to write grub MBR to a floppy if inserted before run

### ISSUE THREAD

**Issue by guiverc** [calamares/calamares#1393]
**Describe the bug**
A clear and concise description of what the bug is. Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.

i386 test machine
hp dx6120mt (mini-tower, pentium 4 dual core, 3gb, winfast clone of nvidia 7600gt), 3 pata drives of 40 & 80gb
amd64 test machine
dell [optiplex] 755 (c2d-e6850, 5gb, amd/ati radeon rv516/x1300/x1550), single 160gb sata hdd

This bug was discovered on Lubuntu, see https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/1873128 during the 20.04 cycle (amd64), but existed before then as re-tested with a 19.04 (i386) ISO on another box.

The issue does not occur if there is no floppy in the drive during boot, however if a floppy is in the drive (even if BIOS is set to ignore it), the installer wants to write the MBR to /dev/fd0.

On the amd64 (20.04) box I also noted `calamares` treated the 1.44mb floppy as if it has ~1920GB storage (this is on a system with a single 160gb hdd)

I did not test with systems that have a external 3.5" fdd connected via USB thumb-drive, only on boxes which have internal drives.

**To Reproduce**
1. Insert floppy in drive
1. Boot your Lubuntu 20.04 (or LXQt release using `calamares`) thumb-drive
2. Click to install the system
3. You'll note the "Select Storage Device" is set to /dev/fd0
see https://launchpadlibrarian.net/474810917/installing_to_floppy.jpg

**Expected behavior**
I would expect a floppy drive to be ignored even if a floppy is inserted during boot process, or 'calamares' loading. I can't imagine anyone wanting to install MBR to floppy these days.

**Screenshots and Logs**
Screenshot of install using Lubuntu 20.04 - https://launchpadlibrarian.net/474810917/installing_to_floppy.jpg
~/.cache/calamares/session.log for install (Lubuntu 20.04) - https://launchpadlibrarian.net/474810997/session.log
Screenshot of final summary screen Lubuntu 20.04 - https://launchpadlibrarian.net/474818360/installing_mbr_to_dev_fd0.jpg
(note the install boot loader is /dev/fd0)

Screenshot of how it appeared on x86 box (Lubuntu 19.04) - https://launchpadlibrarian.net/475648389/floppy_calamares_19.04.jpg

On the launchpad bug report other session.log files are available

**Additional context**

As already stated, this is not an issue if there is no floppy in the drive (possibly why it wasn't noticed earlier).

 I just booted Lubuntu 20.04 (amd64) and 19.04 (i386) boxes without floppy inserted during the boot cycle, but inserted floppy before `calamares` is started to install system, and both wanted to install to /dev/fd0 as my storage device.

The amd64 (20.04) box shows the ~1920gb space map as current partitioning, where as the i386 (much older calamares) shows a dark partitioned space in the current map (same floppy used for both tests).

**Comment by guiverc** [comment]
If you'd like me to test another distribution/other (esp. without actual install, eg. to summary screen which is as far as I took the i386 box and can see the /dev/fd0 is going to be used on screen; full install being performed on amd64 box only), let me know what you'd like me to test.

**Comment by abucodonosor** [comment]
I don't know if /dev/floppy is still a thing but something like this may fix that:

```
diff --git a/src/modules/partition/core/DeviceList.cpp b/src/modules/partition/core/DeviceList.cpp
index 944940d9a..0d67163f0 100644
--- a/src/modules/partition/core/DeviceList.cpp
+++ b/src/modules/partition/core/DeviceList.cpp
@@ -143,6 +143,11 @@ getDevices( DeviceType which, qint64 minimumSize )
             cDebug() << Logger::SubEntry << "Removing zram" << it;
             it = erase( devices, it );
         }
+        else if ( ( *it )->deviceNode().startsWith( "/dev/fd" ) || ( *it )->deviceNode().startsWith( "/dev/floppy" ) )
+        {
+            cDebug() << Logger::SubEntry << "Removing floppy" << it;
+            it = erase( devices, it );
+        }
         else if ( writableOnly && hasRootPartition( *it ) )
         {
             cDebug() << Logger::SubEntry << "Removing device with root filesystem (/) on it" << it;

```

**Comment by guiverc** [comment]
I just tested the same Lubuntu 20.04 (last RC before release) install media on 
hp dc7700 (c2d-e6320, 5gb, nvidia quadro nvs 290)
which does **not** have a floppy drive in the box or capacity to have one; and it acts differently there.  I don't consider it a problem with external floppy drive (from this limited test case of one box anyway)

The floppy appears in the "Select Storage device" as /dev/sdd  (sda is internal drive, sdc is an external drive, and sdd is the "NEC USB UF000x - 0B" floppy, and didn't appear in various install options selected (but not executed).  Floppy was inserted & mounted (`pcmanfm-qt`) prior to starting calamares to verify drive worked. 

Of note `KDE Partition Manager` shows the floppy as a device with numerous partitions there adding to approx ~1920GB (so `calamares` isn't making those figures up; they're coming from somewhere); 530GB unallocated, sdd2 has 257GB, sdd4 has... on that 1.44mb floppy disk.

Navigating thru to the install screen, `calamares` acts normally and doesn't want to install to that device unless I specifically choose it (then it shows the ~1920GB "Current:" storage map on the same 1.44MB floppy I've used in prior testing).

**Comment by abucodonosor** [comment]
I don't have any box with floppy so I cannot test at all.

Some distributions remove the floppy driver altogether, some blacklist it, some have
patches etc. Not sure what Debian/Ubuntu does there.

However, I think is fine to just ignore floppy, nothing can be really installed on a floppy these days.

>  Floppy was inserted & mounted

So auto-mounted by the Distribution?

**Comment by guiverc** [comment]
With my testing using the external drive, I'd mounted the floppy primarily as a means of testing to ensure my drive was working. It didn't matter if the floppy was ejected & re-inserted before opening `calamares`, except the behavior in calarames required the floppy to be inside the drive for the issue to occur.

Sorry if I've used imperfect wording (inserted/mounted).

No the floppy does not need to be mounted in the OS, and is not mounted in the manner that I can view files located on it, or `cd` to it automatically.

**Comment by guiverc** [comment]
Sorry I'd hoped to be able to patch code, compile & place in PPA, so I could boot lubuntu ISO, add PPA & *update* (using ubuntu terminology) then run patched `calamares`  to test (thru install).  

I'm having trouble achieving this, so if another way is possible (code put in PPA, or ISO generated, or something else), feel free to provide clue...

**Comment by abucodonosor** [comment]
@guiverc you need to patch the code to ignore floppy or at least everything shows as a /dev/{fd,floppy}.

@adriaandegroot opinions on that floppy mess?

**Comment by adriaandegroot** [comment]
@guiverc I assumed that "too small" would prevent the floppies from showing up (and I haven't had a floppy in a machine in *ages*, although there's probably a USB floppy drive lying around here *somewhere*). But it turns out that the check for capacity of the target device isn't used. In any case there's a branch to fix this, with suggestions from @abucodonosor and a prod from @philmmanjaro it'll be in this week's release.
