### ISSUE TITLE
[fstab] Is 'discard' option still wise to use these days?

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#1395]
I got reminded once again about our [default discard option](https://github.com/calamares/calamares/blob/master/src/modules/fstab/fstab.conf#L20-L28) we set in **fstab** module for all SSD devices. This setting is six years old and a lot had changed in Linux world since then.

All major Linux distribution publishers report that `discard` option can have a negative effect on data integrity or [slows down](https://patrick-nagel.net/blog/archives/337). Systemd can now handle TRIM via a timer and manages it well. At least **Ubuntu** and **OpenSuse** are using this service via a weekly timer. **Fedora** added this default with [32 release](https://fedoraproject.org/wiki/Changes/EnableFSTrimTimer).

According to the [ArchWiki](https://wiki.archlinux.org/index.php/Solid_state_drive) it is recommended to use the [periodic TRIM](https://wiki.archlinux.org/index.php/Solid_state_drive#Periodic_TRIM) via a timer. Even upstream had a long [discussion about discard option](https://lwn.net/Articles/787272/) without a proper result.

**Comment by robin0800** [comment]
I think, as I said in the thread, calamares does not add discard if f2fs file system is used, there may be other file systems where this is true?

**Comment by abucodonosor** [comment]
@philmmanjaro 

it is a configuration option so you can turn in off or change the options to what you wish.

Regarding 'systemd' not everyone is using it.

@robin0800 

mountOptions and ssdExtraMountOptions are configurable, so it is a matter of how the distribution you install is setting these.

**Comment by kkofler** [comment]
`f2fs` is not a reasonable choice for standard SSDs (drop-in HDD replacements), which do wear leveling in firmware. It makes sense only for Flash chips with raw addressing, with no wear leveling firmware inbetween.

**Comment by philmmanjaro** [comment]
More or less it is the question if we should adjust our defaults for the base configs similar to [this](https://gitlab.manjaro.org/applications/calamares/-/commit/160f8c2aea87ab4ff318b1729a171620f8379441).
