### ISSUE TITLE
Wrong KEYMAP on /etc/vconsole.conf

### ISSUE THREAD

**Issue by eronis** [calamares/calamares#1397]
**Describe the bug**
Calamares records "KEYMAP=trq" on /etc/vconsole.conf file when I chose TRF during installation.

**To Reproduce**
1. Choose Turkish F variant during the installation.
2. Finish the installation
3. Open TTY in your newly recorded system. You will see it's using TRQ. It can be annoying having to edit vconsole.conf.

**Expected behavior**
TRQ and TRF are different layouts. In /etc/vconsole.conf file, Calamares should have recorded "KEYMAP=trf" instead of "KEYMAP=trq". Other than that, Calamares takes care of 00-keyboard.conf. There was no problem there.

**Additional context**
TRQ is still the most widely used keyboard layout here in Turkey. Calamares does a magnificent job in keyboard settings too. That was one thing I always found annoying. It is not a Manjaro specific problem too. I had the same problem on Gecko Linux as well. I give you my best regards!

**Comment by abucodonosor** [comment]
That may need some manual exception then?

**Comment by adriaandegroot** [comment]
From the log file, installing an English-language Calamares with a Turkish F-variant layout keyboard:

```16:29:02 [6]: KeyboardPage::onListVariantCurrentItemChanged(QListWidgetItem*, QListWidgetItem*)::<lambda()>
    xkbmap selection changed to:  "tr" - "f" 
16:29:11 [8]: QML Component (default slideshow) activated
16:29:11 [6]: virtual void Calamares::JobThread::run()
    Starting job "Set keyboard model to pc105, layout to tr-f" ( 1 / 1 ) 
16:29:11 [6]: virtual Calamares::JobResult SetKeyboardLayoutJob::exec()
    Executing SetKeyboardLayoutJob 
16:29:11 [6]: QString SetKeyboardLayoutJob::findConvertedKeymap(const QString&) const
    Looking for converted keymap in "/home/adridg/src/calamares/build/lib/kbd/keymaps/xkb" 
16:29:11 [6]: QString SetKeyboardLayoutJob::findLegacyKeymap() const
    Looking for legacy keymap in QRC 
    ..  Found legacy keymap "trq" with score 11 
16:29:11 [6]: bool SetKeyboardLayoutJob::writeVConsoleData(const QString&, const QString&) const
    Written KEYMAP= "trq" to vconsole.conf 
16:29:11 [6]: bool SetKeyboardLayoutJob::writeX11Data(const QString&) const
    Written XkbLayout "tr" ; XkbModel "pc105" ; XkbVariant "f" to X.org file "/
```

You can see the UI Information (from *KeyboardPage*) is correct, but the `findLegacyKeymap()` method is finding the wrong keymap.

**Comment by adriaandegroot** [comment]
The effect is,

```
12:23:20 [6]: QString findLegacyKeymap(const QString&, const QString&, const QString&)
    Looking for legacy keymap "tr" "pc105" "f" in QRC 
    ..  Found legacy keymap "trq" with score 11 
    ..  Found legacy keymap "trf" with score 12 
```

In the log (so you get vconsole KEYMAP=trf).
