### ISSUE TITLE
Adding Persian language

### ISSUE THREAD

**Issue by MRazian** [calamares/calamares#1401]
I started translation strings in Persian. How is and how much does it take the review process of translations?

**Comment by adriaandegroot** [comment]
Translation happens in Transifex,

https://www.transifex.com/calamares/calamares/language/fa/

If you have modified `calamares_fa.ts` you can send it to me or pull-request it and I can update the existing translations with what you've done. You can also upload a changed `ts` file to Transifex. See also https://github.com/calamares/calamares/pull/1382 (that was Esperanto)

**Comment by MRazian** [comment]
Thanks,
Ok, I do that.
