### ISSUE TITLE
Add a dialog

### ISSUE THREAD

**Issue by NSK-1010** [calamares/calamares#1403]
I'd like you to add a GPL summary dialog.
The repository of the dialog is in [NSK-1010 / Summary-of-the-GPL](https://github.com/NSK-1010/Summary-of-the-GPL).

**Comment by abucodonosor** [comment]
What for?

**Comment by abucodonosor** [comment]
Besides, wrong language, python or C++ ( or use QML ), but what is wrong with the 'license' modules doing that?

**Comment by NSK-1010** [comment]
I thought it would be a good idea for you to understand a little bit about the GPL, because I've found people seeking compensation for defects in GPL licenses.

**Comment by NSK-1010** [comment]
You can even just run it before the installer starts!
In addition, I can only use HTML, CSS and bash.

**Comment by demmm** [comment]
Have you checked the license module?  It can load/present any and all licenses you'd like to present.
https://github.com/calamares/calamares/tree/master/src/modules/license

**Comment by NSK-1010** [comment]
What do you think about calling a shell script in Python and running it?

**Comment by philmmanjaro** [comment]
Seems this goes nowhere. **Calamares+** supports already a [license](https://github.com/calamares/calamares/tree/master/src/modules/license) module. So any license can be added. I don't know what you try to achieve here. So far I don't think we need to make any changes to our installer framework.

**Comment by NSK-1010** [comment]
I think it's necessary because I've found people seeking compensation for defects in software distributed by the GPL.

**Comment by adriaandegroot** [comment]
For general "run a thing" there is the *shellprocess* module, which can be configured to run whatever shell commands you like. This doesn't require any work upstream: you add an item in the *exec* section of `settings.conf` for a particular shellprocess instance, and configure that instance to run e.g. `python3 /my/script.py`.

- `settings.conf`
   ```
   instances:
       - id: explain
         module: shellprocess
         config: shellprocess-explain.conf
   ```
- `shellprocess-explain.conf`
   ```
   dontChroot: true
   timeout: 10
   script:
      - "python3 /usr/local/bin/explain-the-gpl.py &"
```

If you want to display release notes or other text, you can use the webview (sometimes: browsers no longer like to be embedded into Calamares) or notesqml modules, where you can place whatever text you like.

If you need the user to accept a license, then the license module does that, and can be configured to display license texts from a local source. Then the user needs to tick the box.

All-in-all I'm not convinced there's a need to add a special dialog or special explanation module **upstream**.

**Comment by kkofler** [comment]
I think that if you want to display the license text, it should be within the Calamares UI (using a module such as `webview`, `notesqml` or `licenses`, or a new C++ or QML module) and not in a separate `zenity` dialog.

**Comment by NSK-1010** [comment]
Sorry, I can't use C+ and Python and QML.

**Comment by NSK-1010** [comment]
I can't use subprocess.
Can't I use a shell script?

**Comment by philmmanjaro** [comment]
Seems most is lost in translations ...

Explain in simple words why this dialog is needed and how you try to implement it? What should happen and how should your dialog on your end be used? Maybe share a mockup so we might understand better.

In general **Calamares** already offers a lot of option to display that GPL license, however we don't know why you still want to do something extra.

- [webview](https://github.com/calamares/calamares/tree/master/src/modules/webview) can display any URL in Calamares
- [notesqml](https://github.com/calamares/calamares/tree/master/src/modules/notesqml) even has some nice [example](https://github.com/calamares/calamares/tree/master/src/modules/notesqml/examples)
- [license](https://github.com/calamares/calamares/tree/master/src/modules/license) offers a way to display licenses in a pleasant way

Check each module and their config files to see what might be needed. They are using the [YAML](https://learn.getgrav.org/16/advanced/yaml) format.

**Comment by NSK-1010** [comment]
This is to make it as easy as possible for you to understand the GPL.

**Comment by philmmanjaro** [comment]
I don't get it? What is needed to understand the GPL. I see no point in your request at all. GPL is a license and Calamares uses it. Also it is packaged as needed and a user can read up on the license if he wants.

So what exactly do you expect? A feature for the user to click on something to display your dialog or should the dialog displayed anyway? like: `/usr/bin/your-gpl-script && pkexec /usr/bin/calamares`

**Comment by NSK-1010** [comment]
I think the dialog should be shown because some users don't understand the GPL.

**Comment by philmmanjaro** [comment]
I still don't get it. You summarize the GPL without linking to the full GPL license. Also I don't know why this specific dialog should be shown before any application gets started. It makes no sense. Most users don't care about license and will find it odd if such a nag-dialog appears. So be more specific what your goal here is. As it makes totally no sense to me.

**Comment by NSK-1010** [comment]
Sorry, this issue is closeing.

**Comment by adriaandegroot** [comment]
I looked at the repo with the 

> I can't use subprocess.
> Can't I use a shell script?

Yes, you can: as I explained earlier, the *shellprocess* module can run **any shell script**. I gave an example of how you can configure that module to run whatever you like during the execution of Calamares (in the install step). The example I gave has an **example** command which calls Python -- but you can use anything else. For instance, put the content of your GPL.sh (now that I looked at your repo) into the shellprocess configuration, or call GPL.sh on its own. Many different ways of achieving the same thing -- showing a dialog / extra information during the installation step.

If you want to display information about the GPL **before** Calamares runs in your distro, then you can wrap up Calamares in a shell script that calls zenity or whatever before actually running the Calamares executable; again that is up to you as a distro.

I reject any **upstream** button in Calamares for "explain the license that Calamares is under" because that's not functionality for the application itself.
