### ISSUE TITLE
Japanese strings in Netinstall modules no longer working 

### ISSUE THREAD

**Issue by samurailostinjapan** [calamares/calamares#1411]
Distro: Arcolinux
Calamares Version 3.2.24

I previously asked about adding Japanese translation to additional modules created by the distro in #1367. The solution provided worked perfectly from 3.2.20 until 3.2.22.

From 3.2.23 - we went to create three new modules and the provided solution is no longer working.
It is possible some code change has affected this functionality?

Screenshot from 3.2.24 - the three modules are still in English while the rest is in Japanese.
![2020-05-17_05-40](https://user-images.githubusercontent.com/10843832/82139952-d2dce700-9866-11ea-9ef4-4a8efd985fe1.png)

This is how we have the netinstall.conf configured for the three new modules.
label:
    sidebar: "Graphics"
    sidebar[nl]: "Grahpics"
    sidebar[jp]: "グラフィックス"
    title: "Graphics"
    title[nl]: "Graphics"
    title[jp]: "グラフィックス"

label:
    sidebar: "Filemanagers"
    sidebar[nl]: "Filemanagers"
    sidebar[jp]: "ファイルマネージャ"
    title: "Filemanagers"
    title[nl]: "Filemanagers"
    title[jp]: "ファイルマネージャ"
    
    label:
    sidebar: "Terminals"
    sidebar[nl]: "Terminals"
    sidebar[jp]: "ターミナル"
    title: "Terminals"
    title[nl]: "Terminals"
    title[jp]: "ターミナル"
    
Please let me know if you need any additional information or testing.

**Comment by adriaandegroot** [comment]
The language code for Japanese is *ja*, not *jp*:

```
    sidebar[ja]: "グラフィックス"
```

.. is what you want.

**Comment by adriaandegroot** [comment]
(I see that the configuration file mentions "country code" in the documentation of this feature, so I can see where the confusion comes from. I'll fix that up.)

**Comment by arcolinuxz** [comment]
We have used **jp** in all our configs. All of them worked. Just not these three.
I have changed jp to ja in the three that did not work.
Does not seem to be the solution.
![calamares](https://user-images.githubusercontent.com/36679406/83660674-659ab700-a5c5-11ea-8cc2-920f532a9c0f.png)

**Comment by arcolinuxz** [comment]
Correction. I happen to have selected Korean and not Japanese.
I can not tell the difference but @samurailostinjapan  can.

Confirming that "ja" is working for the Japanese strings

![calcorrection](https://user-images.githubusercontent.com/36679406/83719017-80594400-a636-11ea-895e-b3962b722c04.png)
