### ISSUE TITLE
Compressed BTRFS rootfs / Allow specifying mount options for target root filesystem somewhere

### ISSUE THREAD

**Issue by eMPee584** [calamares/calamares#1416]
When installing onto a BTRFS root volume, one might want to set `compress=zstd` so less space will be used. Currently, it seems only possible to add these mount options to the `fstab` after installation, which means all files will already have been copied uncompressed.
This is a low priority scenario I guess, but might be cool to be supported in the future.

(Needs to be noted that GRUB supports zstd from 2.04 onwards only; with earlier grub, `/boot/` should either be marked non-compressed `chattr -R -c /boot` before copying files there or recompressed with standard compression by `btrfs filesystem defrag -rc /boot`)

**Comment by philmmanjaro** [comment]
This is totally up to the distribution. On Manjaro, we [use **zstd**](https://gitlab.manjaro.org/applications/calamares/-/blob/development/src/modules/fstab/fstab.conf#L41) since a while now.

**Comment by abucodonosor** [comment]
Only possible once we move all this stuff to UI, I mean you cannot even choose the FS right now unless you do a manual installation.

**Comment by andriuss-xilinx** [comment]
This will probably need upcoming kpmcore  4.2.0 (no ETA yet) or at the very least 4.1.0. It gained an option to create filesystem with features (e.g. `mkfs.btrfs --features`). And then of course Calamares needs to wire it it.

**Comment by stikonas** [comment]
This will probably need upcoming kpmcore  4.2.0 (no ETA yet) or at the very least 4.1.0. It gained an option to create filesystem with features (e.g. `mkfs.btrfs --features`). And then of course Calamares needs to wire it it.

**Comment by eMPee584** [comment]
But actually, the only thing missing to enable compression _at all_ before copying all files uncompressed is a `mount -o remount, compress[=zstd]` call?

I'm as much a fan of the over-engineering approach as you are, but at this point in time, I'd prefer a quick fix to just overcome this issue...
Is there a way to stick this command into a hook that is run at the appropriate time?

**Comment by adriaandegroot** [comment]
A *shellprocess* (in the `exec` phase, I suppose **after** the *mount* but before the *unpackfs* modules) can use `@@ROOT@@` (see the example `shellprocess.conf` file; also set *dontChroot* to `true` there) to refer to the place-where-the-target-is-mounted.

**Comment by geckolinux** [comment]
So I'm a bit confused about this issue, if I specify `btrfs: defaults,noatime,space_cache,autodefrag,compress=zstd` in `fstab.conf` will it not use compression as Calamares installs the OS to the disk?

**Comment by adriaandegroot** [comment]
The *mount* module has lots and lots of options-options, so, um .. yes. You can add options per mount-point, and per-fs.

**Comment by eMPee584** [comment]
> A _shellprocess_ (in the `exec` phase, I suppose **after** the _mount_ but before the _unpackfs_ modules) can use `@@ROOT@@` (see the example `shellprocess.conf` file; also set _dontChroot_ to `true` there) to refer to the place-where-the-target-is-mounted.

So such manual intervention is not needed anymore to set the mount options for the initial mount, so f.e. any data copied actually ends up compressed?

**Comment by dalto8** [comment]
> So such manual intervention is not needed anymore to set the mount options for the initial mount, so f.e. any data copied actually ends up compressed?

In 3.3 or later, yes.

The mount options were moved to the mount module so compression and other options are now applied before installation.

**Comment by geckolinux** [comment]
@dalto8 Wow, nice improvement!
