### ISSUE TITLE
Dark theme support / Force light theme

### ISSUE THREAD

**Issue by srevinsaju** [calamares/calamares#1417]
**Describe the bug**
Dark theme makes Calameres unreadable and unusable

**To Reproduce**
1. On a KDE Neon ISO or any KDE Plasma based ISO
2. Go to `System Settings` > `Global Theme` > `Breeze Dark`
3. Exit `System Settings`,
4. Open Calameres, 

**Expected behavior**
The theme should be actually reflected on Calameres as dark theme. This is completely okay even if it doesn't

**Observed behavior**
The theme renders the text as black (given by calameres) and sets the background of `QtWidget` as dark (overriden by any Dark theme) making it impossible to see anything. 
On the second page, the checkbox text  is white,
On the device selection page, the `QListView` is completely black / grey making it unusable 

**Screenshots and Logs**
<none>

**Additional context**
Please feel free to close this issue if it seems unnecessary at the moment

**Comment by srevinsaju** [comment]
Wrong repo :smile:

**Comment by adriaandegroot** [comment]
@apachelogger Maybe one for your issues tracker.

@srevinsaju Calamares is -- maybe unfortunately -- quite ignorant of the theming around it. It has specific color schemes set up in the branding file, which **should** be kept up whatever the surroundings do. If part of Calamares widgets do follow the theme, and other bits don't, then that is a reportable bug (either to switch the whole thing to follow-theme or to add settings in branding to avoid the theme harder).

**Comment by apachelogger** [comment]
fwiw I'm sure we only set sidebar colors, so listview and checkboxes being off sound like actual bugs

**Comment by srevinsaju** [comment]
I guess its a bad configuration for KDE Neon. I did not have the issue with Kubuntu + calameres; Maybe its a configuration error. will update the thread if any progress is made

**Comment by apachelogger** [comment]
I wouldn't at all surprised if more than the sidebar followed the sidebar style sheet

**Comment by srevinsaju** [comment]
I am not sure how calameres works (not well versed with C++), I am sorry I would not be able to debug :cry:
