### ISSUE TITLE
root partition set with 777 permissions

### ISSUE THREAD

**Issue by jstnlth** [calamares/calamares#1418]
"ufw status" brought to my attention that the root folder has 777 permissions instead of 755 after installing, since mksquashfs automatically uses 777 for the root.  (I am using Ubuntu 20.04 using calamares installer). An Internet search suggests this is a known problem in general with Calamares. 
See https://github.com/plougher/squashfs-tools/issues/33

So when unpackfs.conf identifies a sourcefs: squashfs, a "chmod go-w /" should probably be issued.

**Comment by highvoltage** [comment]
Not sure I'd call this a calamares issue per sé. In Debian we set the correct permissions for the squashfs root during build time, I'd say that that's the correct place to do so in other distributions too. Might be nice for calamares to have an option for this, but then you're really just fixing a bug that might be better solved at the source.

**Comment by jstnlth** [comment]
Thank-you Adrian. I think it is great that a tool that installs an operating system takes care of details like making sure that the installation is safe - addressing common issues that distributors might not be aware of, instead of forcing everyone to be an expert in every detail of OS installation.
