### ISSUE TITLE
reasonable keyboard mapping would be nice

### ISSUE THREAD

**Issue by ovenwerks** [calamares/calamares#1419]
When doing an install the keyboard mapping has a default based on IP described location. For some reason an IP from Canada gets a "French Canadian keyboard" which almost no one uses or sells in Canada. The standard US keyboard is what all the Computer stores in Canada I know of sell. This should be the default keyboard for Canadians. It is certainly what most installers default to. It is also the keyboard someone has to use to get essential programing characters for most computer languages.

**Comment by adriaandegroot** [comment]
Sacré bleu! I should ask my friends in Quebec if they've ever seen a French Canadian keyboard (maybe at the federal offices in Gatineu?). They might be rare as Ogopogo teeth.

I do agree it's an odd choice; however, these are driven algorithmically so it will need an exception added. I'm fairly sure there's exceptions made already, so it will be a matter of finding the right spot in the keyboard module

**Comment by ovenwerks** [comment]
To add to this... Before I am given the choice of a French Canadian Keyboard, the installer sets the language to Canadian English because it has detected that I live close to Vancouver (well sorta). I would guess that there is no Canadian English keyboard and so the only Canadian keyboard available is the French one. The installer has decided that Canadian is more important than English. It needs to know that a Canadian English keyboard is the same as a standard US.

**Comment by adriaandegroot** [comment]
There's already a special case in the code: `en_CA` (the language, Canadian English, is mapped to keyboard `eng_CA`, which is the Canadian keyboard, in English mode. This is **called** "French (Canada)" in the left column, and "English" in the right column of the keyboard layout screen.

**Comment by adriaandegroot** [comment]
(branch issue-1419)
