### ISSUE TITLE
Calamares 3.2 fails to build with Qt 5.15

### ISSUE THREAD

**Issue by embar-** [calamares/calamares#1425]
Calamares 3.2.15 and 3.2.24 fails to compile for openSUSE Factory with latest Qt 5.15. We get a lof of warning like this:
`warning: <...> is deprecated: Use <...> variant instead  [-Wdeprecated-declarations]`

`grep -Po "warning:.*deprecated.*$" build_log.txt | uniq` 
returns:

```
warning: 'QStringList QString::split(QChar, QString::SplitBehavior, Qt::CaseSensitivity) const' is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
warning: 'QNetworkAccessManager::NetworkAccessibility QNetworkAccessManager::networkAccessible() const' is deprecated [-Wdeprecated-declarations]
warning: 'void QTime::start()' is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]
warning: 'int QTime::elapsed() const' is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]
warning: 'QImage QImage::alphaChannel() const' is deprecated: Use convertToFormat(QImage::Format_Alpha8) [-Wdeprecated-declarations]
warning: 'void QTime::start()' is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]
warning: 'int QTime::elapsed() const' is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]
warning: 'void QComboBox::currentIndexChanged(const QString&)' is deprecated: Use currentIndexChanged(int) instead, and get the text using itemText(index) [-Wdeprecated-declarations]
warning: 'QStringList QString::split(const QString&, QString::SplitBehavior, Qt::CaseSensitivity) const' is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
warning: 'QStringList QString::split(QChar, QString::SplitBehavior, Qt::CaseSensitivity) const' is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
warning: 'const QBrush& QPalette::background() const' is deprecated: Use QPalette::window() instead [-Wdeprecated-declarations]
warning: 'QStringList QString::split(QChar, QString::SplitBehavior, Qt::CaseSensitivity) const' is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
warning: 'QStringList QString::split(const QString&, QString::SplitBehavior, Qt::CaseSensitivity) const' is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
warning: 'int QFontMetrics::width(const QString&, int) const' is deprecated: Use QFontMetrics::horizontalAdvance [-Wdeprecated-declarations]
warning: 'QStringList QString::split(const QString&, QString::SplitBehavior, Qt::CaseSensitivity) const' is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
warning: 'QStringList QString::split(const QRegExp&, QString::SplitBehavior) const' is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
warning: 'QStringList QString::split(QChar, QString::SplitBehavior, Qt::CaseSensitivity) const' is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
warning: 'QStringList QString::split(const QRegExp&, QString::SplitBehavior) const' is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
warning: 'QStringList QString::split(QChar, QString::SplitBehavior, Qt::CaseSensitivity) const' is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
warning: 'const QBrush& QPalette::background() const' is deprecated: Use QPalette::window() instead [-Wdeprecated-declarations]
warning: 'const QRect QDesktopWidget::availableGeometry(int) const' is deprecated: Use QGuiApplication::screens() [-Wdeprecated-declarations]
warning: 'QVariant qVariantFromValue(const T&) [with T = void*]' is deprecated: Use QVariant::fromValue() instead. [-Wdeprecated-declarations]
warning: 'const QBrush& QPalette::background() const' is deprecated: Use QPalette::window() instead [-Wdeprecated-declarations]
warning: 'void QButtonGroup::buttonToggled(int, bool)' is deprecated: Use QButtonGroup::idToggled(int, bool) instead [-Wdeprecated-declarations]
warning: 'const QBrush& QPalette::background() const' is deprecated: Use QPalette::window() instead [-Wdeprecated-declarations]
warning: 'QList<T> QMap<K, V>::values(const Key&) const [with Key = QString; T = QVariant]' is deprecated: Use QMultiMap for maps storing multiple values with the same key. [-Wdeprecated-declarations]

```

See [attached build_log.txt](https://github.com/calamares/calamares/files/4723029/build_log.txt) for more details.

**Comment by adriaandegroot** [comment]
Those are just warnings though, does Factory build with -Werror?

But, you're in luck, I happen to have a Tumbleweed VM with Qt 5.15 installed so I can chase this. Some are obvious: QTimer things, which I *think* I already fixed.

**Comment by embar-** [comment]
I can see in previously attached file line 1376 option `"-Werror=return-type"`.

 Full line 1376 is:

`
[   71s] + cmake -DCMAKE_BUILD_TYPE=None -DKDE_INSTALL_USE_QT_SYS_PATHS=OFF '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-Bsymbolic-functions' '-DCMAKE_MODULE_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-Bsymbolic-functions' '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-Bsymbolic-functions' -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_PREFIX_PATH=/usr -DKDE_INSTALL_LIBDIR=lib64 -DKDE_INSTALL_SYSCONFDIR=/etc -DKDE_INSTALL_QTPLUGINDIR=lib64/qt5/plugins -DKDE_INSTALL_PLUGINDIR=lib64/qt5/plugins -DKDE_INSTALL_QMLDIR=lib64/qt5/qml -DKDE_INSTALL_QTQUICKIMPORTSDIR=lib64/qt5/imports -DECM_MKSPECS_INSTALL_DIR=/usr/lib64/qt5/mkspecs/modules -DKDE_INSTALL_METAINFODIR=/usr/share/metainfo -DBUILD_TESTING=OFF .. -DINSTALL_CONFIG=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DSKIP_MODULES=plasmalnf -DBoost_NO_BOOST_CMAKE=ON 
`

**Comment by adriaandegroot** [comment]
0e7c984854bcf9b25655e36998606fcbc116d00f

I managed to break my Tumbleweed trying to get enough things installed to build Calamares with Qt 5.15, so I'm going to leave it at just the two QPainterPaths until I get Qt 5.15 done on FreeBSD.

**Comment by philmmanjaro** [comment]
I'll check as soon as **Manjaro** updates to **QT 5.15**.

**Comment by Cal8031** [comment]
It builds! [https://build.opensuse.org/package/live_build_log/home:gmbr3:branches:Education/calamares/openSUSE_Tumbleweed/x86_64](https://build.opensuse.org/package/live_build_log/home:gmbr3:branches:Education/calamares/openSUSE_Tumbleweed/x86_64)

**Comment by embar-** [comment]
Although Calamares 3.2.24 builds for openSUSE Tumbleweed in Education repository (see [https://build.opensuse.org/package/show/Education/calamares](https://build.opensuse.org/package/show/Education/calamares) ), Calamares 3.2.24 failed to build for openSUSE Factory staging and thus was rejected while trying to update version in  openSUSE Factory (see https://build.opensuse.org/request/show/808606 ). However Calamares 3.2.15 also started fail to build at openSUSE Factory (https://build.opensuse.org/package/show/openSUSE:Factory/calamares) after Qt 5.15. Seems openSUSE Tumbleweed (in Education repository) and openSUSE Factory are different things. According openSUSE workflow, Calamares must at first enter into openSUSE Factory, and only later it goes into default openSUSE Tumbleweed repository.

**Comment by kkofler** [comment]
openSUSE Factory = rolling development (like Debian unstable)
openSUSE Tumbleweed = rolling release (like Debian testing)
openSUSE Leap = non-rolling releases (like Debian stable)
The comparison with Debian might only be partially accurate, but it gives you an idea.

**Comment by embar-** [comment]
openSUSE Tumbleweed still has Qt 5.14 (not 5.15 yet)
https://build.opensuse.org/public/build/Education/openSUSE_Tumbleweed/x86_64/calamares/_log has line:
`[   17s] [355/534] cumulate libQt5Core5-5.14.1-2.2`

I attach build log as of today [openSUSE_TW_Qt514_log.txt](https://github.com/calamares/calamares/files/4725351/openSUSE_TW_Qt514_log.txt)

**Comment by embar-** [comment]
I edited post too as build date was week ago... 
@Cal8031 your repository home:gmbr3:branches:Education is not public

**Comment by embar-** [comment]
Yes, latest openSUSE Tumbleweed snapshot is 20200528 and it has Qt 5.14

**Comment by Cal8031** [comment]
> I edited post too as build date was week ago...
> @Cal8031 your repository home:gmbr3:branches:Education is not public

Try home:gmbr3:testing

**Comment by embar-** [comment]
Now I see: calamares-master compiles in your repo

**Comment by Cal8031** [comment]
> Now I see: calamares-master compiles in your repo

Yep I just downloaded calamares master which comes as a zip and moved it to a tar gz for OBS and it works

**Comment by embar-** [comment]
> [0e7c984](https://github.com/calamares/calamares/commit/0e7c984854bcf9b25655e36998606fcbc116d00f)
> 
> I managed to break my Tumbleweed trying to get enough things installed to build Calamares with Qt 5.15, so I'm going to leave it at just the two QPainterPaths until I get Qt 5.15 done on FreeBSD.

If you use BTRFS, you will be able to revert changes into previous filesystem snapshoot to have openSUSE TW working again; see [System Rollback by Booting from Snapshots](https://doc.opensuse.org/documentation/leap/archive/15.0/reference/html/book.opensuse.reference/cha.snapper.html#sec.snapper.snapshot-boot)

**Comment by embar-** [comment]
calamares 3.2.24 with https://github.com/calamares/calamares/commit/0e7c984854bcf9b25655e36998606fcbc116d00f patch was submitted as [SR811237](https://build.opensuse.org/request/show/811237) and successed to build in openSUSE:Factory:Staging:adi:10, i.e. in temporal place for evaluating (see 
[openSUSE-Factory-Staging-adi-10-calamares_log.txt](https://github.com/calamares/calamares/files/4728113/openSUSE-Factory-Staging-adi-10-calamares_log.txt) )

**Comment by Cal8031** [comment]
> calamares 3.2.24 with [0e7c984](https://github.com/calamares/calamares/commit/0e7c984854bcf9b25655e36998606fcbc116d00f) patch was submitted as [SR811237] (https://build.opensuse.org/request/show/811237) into openSUSE Factory and successed to build in openSUSE:Factory:Staging:adi:10, i.e. in temporal place for evaluating (see
> [openSUSE-Factory-Staging-adi-10-calamares_log.txt](https://github.com/calamares/calamares/files/4728113/openSUSE-Factory-Staging-adi-10-calamares_log.txt) )

@embar- Cool.

**Comment by adriaandegroot** [comment]
Closing this as "it works now". Note that older Calamares releases aren't going to be patched. You can try the  0e7c984 change, although Calamares has gone through a lot of code-cleanup and reorganization in each release so it might be non-trivial.
