### ISSUE TITLE
Feature Request : extra dropdown to choose formatting 

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1433]
I am experimenting with Timeshift and btrfs.
I always choose an automatic installation and as such it is set to become an ext4 formatting.
What if we added a dropdown to decide on the formatting.
Ext4 being the default but leave the choice to the user
Possibilities : ext2, ext3, reiser, xfs, jfs, btrfs + ext4

What are your thoughts on the matter?

![btrfs](https://user-images.githubusercontent.com/36679406/84589377-52da7a80-ae2e-11ea-97b2-9fbc0ace85e8.png)

**Comment by abucodonosor** [comment]
Duplicated of https://github.com/calamares/calamares/issues/847
