### ISSUE TITLE
Idea to show install process output instead of slider images 

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1440]
**Is your feature request related to a problem? Please describe.**
No issue  but a nice enhancement for the install process

**Describe the solution you'd like**
I just have the idea to show a terminal window instead of the slider images while installing, with outputting install process + may package manager output.

would look like this:
![calamares-terminal](https://raw.githubusercontent.com/killajoe/shots/master/calamares-terminal.png)

**Additional context**
this should be possible or not? i am still not much into qt quick qml stuff  but a terminal ouput in qml/c++ should work as far as i understand: something like this ?
https://github.com/jorgen/yat
I would like to get some hints and remarks on what do you think about this.

**Comment by adriaandegroot** [comment]
From looking at the README of *yat*, it seems that it's entirely self-contained and entirely qml? If so you can just drop-in that as the slideshow; if you add an `onActivated()` and `onLeave()` method to the main QML component you could do something there to (I don't know if this is possible) run a command in the shell -- like `tail -f ~/.cache/calamares/session.log` and then you have the thing you want.

On the other hand, a QML component that just shows 10 lines of text and tails a given file shouldn't be that hard to create, either. If the resulting QML is a small file then I'd be happy to include it alongside the default slideshow code (or put it in a separate slideshow module in the *calamares-extensions* repository)

**Comment by demmm** [comment]
Implemented:
https://github.com/calamares/calamares/pull/1899
