### ISSUE TITLE
grub-efi problem (on Debian)

### ISSUE THREAD

**Issue by prp-e** [calamares/calamares#1445]
As I worked on my distribution and chose calamares as the installer, I just found something. When I install it on an EFI machine, GRUB looks for `/efi/Debian` and what I told calamares to make is `/efi/Caprice`. So, I've heard even a lot of Debian users had same problem. Is there anyway to solve this?

**Comment by kkofler** [comment]
That's what this setting in `bootloader.conf` is for:
```yaml
# Optionally set the bootloader ID to use for EFI. This is passed to
# grub-install --bootloader-id.
#
# If not set here, the value from bootloaderEntryName from branding.desc
# is used, with problematic characters (space and slash) replaced.
#
# The ID is also used as a directory name within the EFI environment,
# and the bootloader is copied from /boot/efi/EFI/<dirname>/ . When
# setting the option here, keep in mind that the name is sanitized
# (problematic characters, see above, are replaced).
#
# efiBootloaderId: "dirname"
```
So set:
```yaml
efiBootloaderId: "Debian"
```
and it will override the branding settings and always hardcode the directory name that GRUB assumes.

The only alternative is to modify the Debian GRUB package on your derivative distribution.

See also this comment in my Fedora packaging, where I had the same issue:
```yaml
# PACKAGER NOTE: If you really want to change this value, you will also have to
#                change the hardcoded directory name in the grub2(-efi) package.
efiBootloaderId: "fedora"
```

**Comment by prp-e** [comment]
Thanks, it's solved.
