### ISSUE TITLE
[netinstaller][package selection] UI improvements.

### ISSUE THREAD

**Issue by codesardine** [calamares/calamares#1448]
Default UI is squeezed in making it hard to read long names.

![cal](https://user-images.githubusercontent.com/4250006/85939865-b07fc400-b910-11ea-9576-9e213cf97662.png)

If we had some space it would improve readability, maybe split space in half.

![cal](https://user-images.githubusercontent.com/4250006/85939906-0bb1b680-b911-11ea-8b81-ca563fa2fa8e.png)

**Comment by adriaandegroot** [comment]
It's a bit of a toss-up (and depends on the relative lengths of *name* and *description* for a given set of packages) but in general, that's a good idea.
