### ISSUE TITLE
Public signing key missing

### ISSUE THREAD

**Issue by gmbr3** [calamares/calamares#1450]
@adriaandegroot 
Just tried to gpg verify Calamares release 3.2.26.1 so it can be added to openSUSE repos. However, it looks like your [public key](https://github.com/adriaandegroot.gpg) is outdated compared to the signing key for the the release.
```
gpg --import calamares.keyring
gpg: key 7FEA3DA6169C77D6: 37 signatures not checked due to missing keys
gpg: key 7FEA3DA6169C77D6: public key "Adriaan de Groot <groot@kde.org>" imported
gpg: removing stale lockfile (created by 2002)
gpg: Total number processed: 1
gpg:               imported: 1
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
```
 ```
gpg --verify calamares-3.2.26.1.tar.gz.asc calamares-3.2.26.1.tar.gz
gpg: Signature made 23 Jun 2020 16:26:19 GMTST
gpg:                using RSA key 57E14BD1CD6C198BC11BF18D61A7D26277E4D0DB
gpg: Can't check signature: No public key
```

**Comment by adriaandegroot** [comment]
You're right. The signing is a bit of a mess: for a while I was signing with something else entirely, because GPG was silently using a different key. Then I realised that I had a specific signing key set up for this, and used that but didn't update the public keys on GH. Bleh.

I'll sort the keys out at some point before a next release.

**Comment by adriaandegroot** [comment]
The GPG key has been updated at:
 - my [GH profile](https://github.com/adriaandegroot.gpg)
 - on the [Calamares site](https://calamares.io/pk-7FEA3DA6169C77D6.txt)
 - my [own site](https://euroquis.nl/doc/pubkey.asc)

Next release gets signatures from both the recently-used-but-set-to-expire-in-September and a newer signature.
