### ISSUE TITLE
What algorithm the "Encrypt system" is using, and where are the configuration options?

### ISSUE THREAD

**Issue by informer2016** [calamares/calamares#1452]
Is there any possibility to choose the custom LUKS cryptsetup strong encryption flags in a Calamares installer, like ```--verbose --type luks1 --cipher serpent-xts-plain64 --key-size 512 --hash whirlpool --iter-time 10000 --use-random --verify-passphrase luksFormat /dev/sdX2``` mentioned in this thread? [**Artix Linux** _(great Arch with OpenRC or runit/s6 instead of SystemD)_ - **Full Disk Encryption for a new install**](https://forum.artixlinux.org/index.php/topic,1541.0.html)
Because, going through these lengthy manuals is time consuming and a bit intimidating for the new users, who would like a **much stronger encryption at cost of some performance.**

Right now, Calamares just gives a **[ ] Encrypt system**, without any custom options or even a description of used encryption method!

Would be nice if there'd be some button which **gives you a list of available encryption methods & options** : i.e. I had to figure out why a usual "serpent-xts" cryptsetup option didn't work in this time - now it seems to require something like -plain64 at the end

**Comment by adriaandegroot** [comment]
There's no options, no. The keyfile is setup by dd-ing from urandom, and then added to luks with ` { "cryptsetup", "luksAddKey", d.device, keyfile }`. I can imagine three extensions:
  - a config key in `luksbootkeyfile` to add flags; this would allow distro-level setting and the distro could distinguish itself with specific LUKS setup bits
  - a button to pop-up a text field so the user can shoot themselves in the foot
  - some fancy UI (your "button that gives a list")
I don't much feel for the third one, since it adds a lot of complexity and ties the UI to particular versions of LUKS tooling. If someone writes such a widget (and/or a QML component for it) then it would probably be acceptable, though. Foot-shooting is something I would like to avoid as well.

(See `src/modules/luksbootkeyfile/LuksBootKeyFileJob.cpp` for details)

**Comment by informer2016** [comment]
@adriaandegroot if there are truly no options - and a simple `cryptsetup luksFormat -v /dev/sdX2` instead - that means it's using the cryptsetup default flags for encryption (encryption method, length of a key, etc.) - which may be different for various cryptsetup versions and distros. Perhaps that's not transparent enough

Perhaps a fancy UI is more tricky; would be nice if you'd at least give us a button to pop-up a text field, where we could enter something like
`--verbose --type luks1 --cipher serpent-xts-plain64 --key-size 512 --hash whirlpool --iter-time 10000 --use-random --verify-passphrase luksFormat /dev/sdX2`

**Comment by merinfor2021** [comment]
@adriaandegroot @demmm Any chance for this essential feature? I tried digging by myself, but can't find where Calamares specifies the arguments for LUKS encryption - otherwise this could've been resolved manually with a simple sed...

**Comment by kkofler** [comment]
Everything happens in C++ code, so sedding Python code will not get you anywhere, you actually have to recompile libkpmcore and Calamares to change this.

The encrypted partition is created in the KPMcore library (libkpmcore) shared with the KDE Partition Manager (KPM). So you will not find the code that initially sets up the partition in the Calamares source code at all, it is in the library. Then the keyfile for `/` is created in the `/boot` partition and added in a keyslot for `/` in the C++ source file `src/modules/luksbootkeyfile/LuksBootKeyFileJob.cpp` that @adriaandegroot has already mentioned. Everything happens with the default options, so the answer to the question in the subject line is: whatever `cryptsetup` defaults to on the given distribution.

**Comment by merinfor2021** [comment]
@kkofler Could it be possible to at least load the encryption options from some external human-editable config?

**Comment by adriaandegroot** [comment]
The questions are largely answered. There is a sketch of how you could PR something to implement finer-grained control, but the issue itself is done.

**Comment by geckolinux** [comment]
Hi there, I received this well-researched request from a user about the `cryptsetup` `--iter-time` value that Calamares uses:
https://github.com/SpiralLinux/SpiralLinux-project/issues/328
I wonder if there are others here that would support allowing configuration of some  `cryptsetup` options via a Calamares config file? (I would say that a UI for the user to configure this during installation isn't very necessary at this point.)

Sorry for posting this in this closed issue, or should I open a new one?

**Comment by dalto8** [comment]
> I wonder if there are others here that would support allowing configuration of some `cryptsetup` options via a Calamares config file?

Personally, I am always supportive of adding useful customization options that give distro developers more control over the installation.

**Comment by adrelanos** [comment]
Related KPMCore pull request: [Harden default LUKS2 settings](https://invent.kde.org/system/kpmcore/-/merge_requests/54)
