### ISSUE TITLE
little error in translation

### ISSUE THREAD

**Issue by bigbruno** [calamares/calamares#1455]
In Brazlilian portuguese translation using maiúscula as lowercase, but maiúscula=uppercase, and minúscula=lowercase

Now
      <location filename="../src/modules/users/UsersPage.cpp" line="402"/>
      <source>Your username must start with a lowercase letter or underscore.</source>
      <translation>Seu nome de usuário deve começar com uma letra maiúscula ou com um sublinhado.</translation>

Fixed
      <location filename="../src/modules/users/UsersPage.cpp" line="402"/>
      <source>Your username must start with a lowercase letter or underscore.</source>
      <translation>Seu nome de usuário deve começar com uma letra minúscula ou com um sublinhado.</translation>

**Comment by philmmanjaro** [comment]
Maybe join the [pt-BR translation team](https://www.transifex.com/calamares/calamares/language/pt_BR/)

**Comment by adriaandegroot** [comment]
Thanks for reporting. I went over to Transifex and fixed it there, and the change in translation will be in the next release.
