### ISSUE TITLE
do not mangle /etc/default/grub if /etc/default/grub.d exists (Debian/Ubuntu)

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1457]
**Is your feature request related to a problem? Please describe.**
grubcfg mangles /etc/default/grub which on debian distros makes

- the distro config system angry causing it to always ask the user what to do about a clash in a config that was modified on-disk (by cala) but supplied by packaging. 
- conceivably breaks the supplied default config because it's rewriting the entire beast

**Describe the solution you'd like**
if `overwrite` is false and `/etc/default/grub.d/` exists then  write `/etc/default/grub.d/0calamares` or somesuch to get eval'd after the regular default/grub which would also allow recycling previously defined values (e.g. `GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT foobar"`)

**Comment by kkofler** [comment]
I agree that it makes sense to use `/etc/default/grub.d/` **if** it exists. The reason this was not yet implemented is that this is a Debian-only thing, you will not find this directory on any other distribution (that is not derived from Debian, or from Ubuntu which is itself derived from Debian). So we were not even aware of its existence. But yes, if it exists on the system, it makes sense to use it, definitely.
