### ISSUE TITLE
Encrypted Partition With no Password Does not Encrypt

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#1459]
When I ask for an encypted partition and tick the box but forget to give it a password my install completes and the disk is not encrypted.

![calamares](https://user-images.githubusercontent.com/89822/87803008-ddf1ca80-c849-11ea-81d3-ad13236238e3.jpg)

It should not let me proceed until I have supplied a password

**Comment by geckolinux** [comment]
Confirmed, I made the same mistake.
