### ISSUE TITLE
Tajik Language Support

### ISSUE THREAD

**Issue by Ibragimov** [calamares/calamares#1463]
Dear Calamares Team,

Please, add Tajik Language on Transifex for Calamares, so I start and manage to complete Tajik translation.

Thank you for prompt reply,
Victor Ibragimov

**Comment by adriaandegroot** [comment]
I have added Tajik (will this be in cyrillic, I presume?) to the list of languages. It looks like your profile on Transifex (tajikfedora) is private or no longer exists -- this is generally a weird situation when languages are requested. So I can't make you a coordinator for the language, because I can't see your profile and don't have your email address.

To resolve that, you can mail me directly, or create a public Transifex account.

**Comment by Ibragimov** [comment]
Hi,

Thank you for adding Tajik language to the list of languages. Yes, it should be in Cyrillic, UTF-8. Please, re-check my profile to complete the setup on your side.

Have a great day!
Victor Ibragimov

**Comment by Ibragimov** [comment]
Please, consider "ibragimov" account on Transefix to make as coordinator

**Comment by Ibragimov** [comment]
Hi,

Overnight I have translated over 30% or 1,327 words into Tajik language so far. Please, advise if I can test Tajik translations of Calamares on a daily build of KDE Neon Testing or Unstable Edition or Debian Live or any other distribution promptly? At this translation stage a test on a live system will help to update and improve current Tajik translations and style, and help to figure out where to keep consistency or apply contextual translation for the other translatable strings.

Thank you for prompt reply,
Victor Ibragimov

**Comment by adriaandegroot** [comment]
![image](https://user-images.githubusercontent.com/19431457/88475536-0b690300-cf31-11ea-8055-1492f8fea17c.png)

Wow, you're fast at that. I've added you again as language coordinator. I've updated the translation in Calamares, and enabled Tajik language. It looks like that screenshot, above (this is using the *welcomeq* module, which I'm not sure does translations right -- the regular *welcome* module does).

So, for testing:
 - build calamares from the development branch (the main branch is called *calamares*, you can just git clone this repo)
 - run it and see!

To update strings:
 - download the .ts file for Tajik and replace `lang/calamares_tg.ts` (or one of the other files). Alternatively, if you have a Transifex account and have a `~/.transifexrc` with your API token, you can run `sh ci/txpull.sh` to pull all the updated translations -- this does some git commits so it can get messy to follow normal upstream source again, though.
 - then build Calamares again
 - run it and see updated strings!

**Comment by adriaandegroot** [comment]
More translations instructions should be available in the [Translators Guide](https://github.com/calamares/calamares/wiki/Translate-Guide) .. if you have suggestions or fixes for the wiki, please file PRs. (I see that I also built some special translator support once, use the `-T` command-line-flag)

Once again, thank you for translating Calamares!
