### ISSUE TITLE
Translation issues for Tajik Language (Same issues may refer to some other languages - Tested!)

### ISSUE THREAD

**Issue by Ibragimov** [calamares/calamares#1467]
Hi,

I am about to complete Tajik translation for Calameras. During the linguistic tests, primarily for Tajik language, I have noticed that some of translated texts are not responsive (do not fit on buttons) and look truncated, for instance the translation of "Show debug information" string is centered and truncated. I have also noticed that translation of this string in some other languages have the same issue. Could you please, check if the issue could be automatically fixed by splitting the string into two lines? A screenshot with the issue for this stings attached (issue-1.png)

The other issue is that some translated stings still remain untranslated. For instance, the string "Manual partitioning. You can create or resize partitions yourself" is translated, but still is shown in source language. I suggest that this stings for some reason was merged with "Having a GPT partition table and fat32 512Mb /boot partition is a must for UEFI installs, either use an existing without formatting or create one." it can be noticed if to look inside the source file .ts A screenshot with the issues for this stings attached (issue-2.png). Also, could you please, check for the other issues related to translation/localization, like issue-3.png this sting also is shown in the source language.

Hope this feedback will help to improve translations for Tajik and some other languages with similar issues.

Thank you for prompt reply,
Have a great day!
Victor Ibragimov

![issue-1](https://user-images.githubusercontent.com/1321588/88709925-4769b700-d12f-11ea-85bc-35e5103daa6c.PNG)
![issue-2](https://user-images.githubusercontent.com/1321588/88709933-49cc1100-d12f-11ea-8c64-01493bfcad85.PNG)
![issue-3](https://user-images.githubusercontent.com/1321588/88709938-4a64a780-d12f-11ea-98e4-5090f7b11def.PNG)

**Comment by adriaandegroot** [comment]
The "buttons and UI elements do not resize to reflect string lengths" is a known issue -- for the **specific** case of the debug-button, I would say it's a developer-oriented button that should not be visible for regular users. You can put a newline in your translation, though, that will be displayed correctly (the button gets taller). Here it is in Dutch, with the message badly translated so it would be too long, and the background of the sidebar adjusted so it's easier to see:

![image](https://user-images.githubusercontent.com/19431457/88783753-7d3e8800-d18f-11ea-82c1-4109e74da34c.png)

The other issues you have circled are a product of the way Calamares is developed: it runs on short cycles (about two weeks between releases) and there is no real string freeze. I **try** to do string changes early in each cycle, but .. that doesn't really help. What you see here is that strings have changed in the source code, but Transifex hasn't been notified of the changes (that's a manual step in the development process).

I just pushed new translations to Transifex: that means that the current source-code strings are now in there, and others have gone away; you may need to re-do some translations to match the sources again.

(Specifically, the code was previously including `<br/>` in the string-to-be-translated about timezones, and I got rid of that; the message about manual partitioning included a warning about EFI that wasn't always useful or correct.)

**Comment by Ibragimov** [comment]
Great! Thank you for the advise and fixes. Everything looks just perfect now!
Hope to see Calamares Installer in all available distributions with Tajik Language Support.
And thank you for the Calamares Installer - this framework / application really ensoul the computers with Linux systems!

Have a wonderful day!
Victor Ibragimov

![issue-1-fixed](https://user-images.githubusercontent.com/1321588/88833260-6a59a100-d1eb-11ea-8f2e-a0f2055e2bce.PNG)
![issue-2-fixed](https://user-images.githubusercontent.com/1321588/88833262-6b8ace00-d1eb-11ea-9616-f63eacb7b4e7.PNG)
![issue-3-fixed](https://user-images.githubusercontent.com/1321588/88833265-6c236480-d1eb-11ea-8ad8-6f6657ef8905.PNG)

**Comment by adriaandegroot** [comment]
Excellent! I'll close this issue then, and we'll have a Calamares release real soon (maybe, just maybe, tomorrow already) with full Tajik support.
