### ISSUE TITLE
Tajik Language is now 100% translated!

### ISSUE THREAD

**Issue by Ibragimov** [calamares/calamares#1468]
Tajik Language is now 100% translated!

It took me 5 days to complete the full Tajik translation task with tests on a live system with working Calamares Installer on Debian and Ubuntu, and make style, spelling, consistency and terminology improvements on the fly.

Once we have a new Calamares release I will make more QA tests on live systems with full Tajik support to see if something needs to be improved in translations for next releases.

I hope this contribution for the Calamares Installer will help to build Linux distributions with full Tajik language support for individuals, education, businesses, government and public needs.

Have a great day!
Victor Ibragimov

![Tajik Language Support for Calamares Installer](https://user-images.githubusercontent.com/1321588/88963255-01dcf380-d2c1-11ea-90c5-69d20f511c36.PNG)

**Comment by Ibragimov** [comment]
Now Tajik language is 100% completed and 100% reviewed!

![100% Complete and Reviewed](https://user-images.githubusercontent.com/1321588/89014513-08a24f80-d32f-11ea-8ae2-44c3079ab5cf.PNG)

**Comment by adriaandegroot** [comment]
Complete at least until the next string changes :) You will get Transifex notifications of that, I think.

**Comment by Ibragimov** [comment]
Yes, please, keep me informed about any changes, so I try to keep them updated.
