### ISSUE TITLE
hostinfo test fails on non-Intel CPU's

### ISSUE THREAD

**Issue by PureTryOut** [calamares/calamares#1471]
**Describe the bug**
When running the hostinfo tests, specifically `HostInfoTests::testHostOS()`, it fails on non-Intel CPU's due to expecting `hostCPU()` returning "Intel". Obviously not everyone has Intel CPU's so it'll fail in those cases, including on my AMD machine.

**To Reproduce**
1. Run the tests (`ctest`) on a non-Intel machine
2. Observe hostinfo failing

**Expected behavior**
The test to succeed no matter what CPU is used

**Comment by PureTryOut** [comment]
Not a great improvement, but it should solve it for the majority of x86* CPU's. I wonder what to do with other architectures like ARM, but I doubt Calamares is used much there.

**Comment by adriaandegroot** [comment]
? the test should pass on your ARM machine now, although I have not actually built it on my Rock64 (the rock64 images are all fairly old, so building things is a pain). The one commit mentioned above is not the whole thing. You could help by adding a chunk from your `/proc/cpuinfo` (ARM seems to have a "CPU implementer" line).

**Comment by PureTryOut** [comment]
Oh sorry, I only saw the command that referenced this issue 3 days ago, somehow I thought 5066624 was the same commit (but it obviously isn't). Yeah that does seem to do the trick better, nice work.

> the rock64 images are all fairly old, so building things is a pain

I run a close-to mainline Linux kernel on a rolling release userland with postmarketOS/Alpine Linux on my RockPro64, you should give it a shot, it's cool!
