### ISSUE TITLE
unpackfs should support tarballs

### ISSUE THREAD

**Issue by PureTryOut** [calamares/calamares#1472]
**Is your feature request related to a problem? Please describe.**
I'm trying to make an Alpine Linux image with the Calamares installer. Our image creation scripts creates the rootfs as a tarball using gzip compression (so `.tar.gz` extension). The `unpackfs` module however does not support this and seems to expect either a filesystem (specifically ext4) or a squashfs image.

**Describe the solution you'd like**
The `unpackfs` module to support tarballs, preferably independent of the compression used.

**Describe alternatives you've considered**
In this case I can use squashfs instead, but I have to edit more existing scripts for this than I'd really like. Tarballs seem to be the most used way to distribute such things as root filesystems.

**Comment by adriaandegroot** [comment]
The *unpackfsc* module of *calamares-extensions* now supports tarballs (at least, I threw something together that might work). Please give that a shot and file issues / PRs there.
