### ISSUE TITLE
calamares default language is C (also C is listed)

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1475]
**Describe the bug**
when starting latest calamares calamares the language field is pre-selected with the C locale.
Also C likely shouldn't even be in the model, it's not a user-relevant locale

**To Reproduce**
1. https://files.kde.org/neon/images/focal-preview/unstable/
2. start calamares

**Expected behavior**
Language should be a sane default

**Screenshots and Logs**
[cala.log](https://github.com/calamares/calamares/files/5021477/cala.log)
![Screenshot_20200804_120720](https://user-images.githubusercontent.com/809987/89282291-99d53700-d64b-11ea-9f2e-90e07c64bc07.png)

**Comment by adriaandegroot** [comment]
That is [Interlingue](https://en.wikipedia.org/wiki/Interlingue), which isn't supported by Qt although the translation is -- in-principle -- complete enough to try to run Calamares with it. This would have been caught by pre-release testing, but those don't run often in development.
