### ISSUE TITLE
Calamares fails to create user

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#1482]
![image](https://user-images.githubusercontent.com/89822/89789278-49148100-db18-11ea-9962-a630db27de99.png)

![image](https://user-images.githubusercontent.com/89822/89789334-5a5d8d80-db18-11ea-8254-c34e08617069.png)

**Comment by adriaandegroot** [comment]
Fixed in 03871db59 (and soon-to-be-released 3.2.28.1)
