### ISSUE TITLE
Can't make sb-shim work with openSUSE, "grub.cfg.new: No such file or directory"

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#1484]
Hi there, I create "GeckoLinux" with Calamares 3.2.27 on openSUSE (Leap 15.2 and Tumbleweed).

A user recommended to me that for optimum SecureBoot support the sb-shim bootloader method should be used. But I can't make it work. No matter what I try for `efiBootloaderId:` it always fails with _"grub.cfg.new: No such file or directory"_. I've tried `opensuse`, `grub`, and `geckolinux`, as well as not defining `efiBootloaderId` so that it takes it from the branding.

Here's the [log](https://github.com/calamares/calamares/files/5052114/log.txt).

And here's my [bootloader.conf](https://github.com/calamares/calamares/files/5052117/bootloader.conf.txt).

Thanks!

**Comment by abucodonosor** [comment]
I have no idea about Secureboot implementation in calamares or in openSuse but that error is simple,
the 'folder' grub is trying to write the configuration to doesn't exists.

Also, I have NO idea why grub.cfg is written into the /EFI/ folder in openSuse, at least is what your log is saying.

**Comment by abucodonosor** [comment]
@kkofler I guess we need to make sure that dir exists before writing to it?

I saw you committed that:

https://github.com/calamares/calamares/commit/ec7c5a4611182368e9c4844724d31ac2c8edc382#diff-bfa2594912fd81abeb71d7a4b98c2905

**Comment by geckolinux** [comment]
Here is openSUSE's EFI's stock configuration:
https://en.opensuse.org/openSUSE:UEFI

```
 /boot/efi
 /boot/efi/EFI
 /boot/efi/EFI/boot
 /boot/efi/EFI/boot/bootx64.efi
 /boot/efi/EFI/boot/fallback.efi
 /boot/efi/EFI/opensuse
 /boot/efi/EFI/opensuse/MokManager.efi
 /boot/efi/EFI/opensuse/grub.efi
 /boot/efi/EFI/opensuse/shim.efi
 /boot/efi/EFI/opensuse/boot.csv
 /boot/efi/EFI/opensuse/grub.cfg
 /boot/efi/EFI/opensuse/grubx64.efi
```

**Comment by geckolinux** [comment]
But when I use `efiBootLoader: "grub"` it does correctly install the bootloader into that directory...

**Comment by abucodonosor** [comment]
@geckolinux 

probably @kkofler has an answer to that, but from the error, the dir is trying to write to does not exist.

**Comment by adriaandegroot** [comment]
There's code in the `install_grub()` function to create target directories, which is not there in the `install_secureboot()` version. I think that's safe to add (after refactoring it to a function and cursing how cobbled-together the Python modules are).

**Comment by geckolinux** [comment]
As a workaround I wonder if I could pre-create the `/boot/efi/EFI/opensuse/` directory when I generate the ISO (preferred) or else use a `shellprocess` command in Calamares? Any downsides to doing so, apart from there being that empty directory there if it's a legacy BIOS system?

**Comment by adriaandegroot** [comment]
You could even use *contextualprocess* to create the directory only if there's an EFI firmware (you'll need to mess around a bit with what-gets-set-in-globalstorage and how to react to that).

**Comment by kkofler** [comment]
So the `/boot/efi/EFI/opensuse/` directory exists on stock openSUSE, but not on your GeckoLinux live image?

I don't think creating the directory in Calamares is the solution, because the directory would also be missing all the other required files, not just `grub.cfg`. I also don't think `efiBootLoader: "grub"` makes sense, because the directory should not be named `/boot/efi/EFI/grub`.

I suspect that your live image is missing the package(s) (probably one or more subpackage(s) of `grub` and/or `shim`) that contain(s) this directory. (In Fedora, the directory is co-owned by both `efi-filesystem` and `grub2-common`, the files it contains are owned some by `grub2-efi-x64` and the others by `shim-x64`.) So you need to add the missing package(s) to your live image.

**Comment by kkofler** [comment]
Looking at #1485, I think that the main issue here is that openSUSE apparently does this setup significantly differently from Fedora.

On Fedora, GRUB is never actually "installed" (as in `grub2-install`) on the end-user machine on UEFI, the files are installed directly to the hardcoded `/boot/efi/EFI/fedora` by the RPMs (not by scriptlets, the files are actually owned directly by the package) and `shim` is hardcoded to use that directory name. Only `shim` is installed (using `efibootmgr`).

In contrast, it looks like openSUSE is actually running `grub2-install` or something equivalent in a scriptlet, using different directory names for remixes, and if that scriptlet has not been run for whatever reason, the directory does not exist at all (which seems to be the case on your live image).

**Comment by geckolinux** [comment]
And what about if I manually include `boot.csv grub.cfg grub.efi MokManager.efi shim.efi` in `/boot/efi/EFI/geckolinux` when generating the live ISO?

**Comment by kkofler** [comment]
That should work.

**Comment by geckolinux** [comment]
So I tried switching to `sb-shim` and building an ISO with pre-populated `/boot/efi/EFI/geckolinux/` containing:
- `grub.efi`
- `MokManager.efi`
- `shim.efi`

I didn't add `grubx64.efi` because it always got added automatically during the installation routine, but in retrospect maybe that was also necessary, because the resulting live ISO wouldn't boot in VirtualBox EFI mode, there was only a `grub>` prompt.

So I then tried building a new ISO with just an empty `/boot/efi/EFI/geckolinux/` directory. This one booted in VirtualBox EFI and successfully completed the Calamares installation, but the installed system wouldn't boot, there was only an EFI shell. I check the contents of the filesystem, and apparently Calamares didn't touch the `/boot/efi/EFI/geckolinux/` directory, because it was still blank.

**Comment by geckolinux** [comment]
I tried every possible combination I could think of to pre-populate `/boot/efi/EFI/geckolinux/` and/or `/boot/efi/EFI/boot/` with the EFI files, but it results in either the live ISO not booting or the installed system not booting. I didn't try copying any of the `.cfg` or `.csv` files from a correctly installed system because I think those should be generated during the install routine and are probably specific to each system.

So ideally, it would be best for Calamares to handle this so that the shim install routine does its thing.

**Comment by abucodonosor** [comment]
@geckolinux 

since OpenSuse by itself changes/generates things on installing/reinstalling the grub* package(s)
there is not much calamares can do.

At very least you should identify what exactly OpenSuse is doing.
