### ISSUE TITLE
Calamares 3.2.28.1 is not creating group AutoLogin in Archlinux Install

### ISSUE THREAD

**Issue by marcoobaid** [calamares/calamares#1488]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
The Calamares installer fails at the point when it tries to create the user that is selected for autologin. It complains about the group "autologin" does not exist. 

**To Reproduce**
1. Launch Calamres Installer
2. Go through the sequence 
3. When creating the user, select the checkbox next to the "autologin"
4. Run installer

**Expected behavior**
If the autologin group does not exist, Calamares installer will create.
![calamares_errror_01](https://user-images.githubusercontent.com/48951325/89961451-53617880-dc07-11ea-83c1-06b4ca7758fc.png)

**Screenshots and Logs**
Please see attached screenshot.

**Additional context**
The same process works correctly in calamares 3.2.27. I have narrowed it down to CreatUserJob.cpp between lines 89 - 100

**Comment by adriaandegroot** [comment]
Hi @marcoobaid , thanks for the report. I think the list-of-groups-to-create is not being populated correctly before calling the code you've identified. This needs a little debugging output and I'll run one round of installation to see what happens.

**Comment by adriaandegroot** [comment]
There's a 3.2.28.2 that resolves this

**Comment by marcoobaid** [comment]
> There's a 3.2.28.2 that resolves this

Fantastic! Thank you Adriaan for your quick fix.
