### ISSUE TITLE
User password is null

### ISSUE THREAD

**Issue by marcoobaid** [calamares/calamares#1489]
**Describe the bug**
In Calamares 3.2.28.x, the user creation password is always set to blank after installation on Archlinux.

**To Reproduce**
1. Launch Calamares
2. Follow the sequence to Users
3. Enter user information and password, as usual
4. Complete installation and reboot
5. When you login to the target system, the user password is null. (for example: sudo su and hit enter will allow root access). Or, if not auto-login, hit enter at the Login Manager page and it will be accepted.

**Expected behavior**
Calamares will set the user password as entered in the User module screen.

**Screenshots and Logs**
![calamares-passwd-change](https://user-images.githubusercontent.com/48951325/90082695-157f5580-dcd6-11ea-98ef-62343f0741a6.png)

**Additional context**
The log in the screenshot above shows that the password is set, but it is blank. I have performed the same installation using Calamares 3.2.27 and it works correctly. It seems that 3.2.28.x included lots of changes in the Users module so I am unable to pinpoint the bug in the code.

**Comment by adriaandegroot** [comment]
This is just the release that keeps on giving, isn't it -- it illustrates that we don't have a really good mechanism for integration testing of non-release parts, which **because** of the large-scale changes in the users module this time are full of regressions.

I think the right thing to do is hold off on 3.2.28 now and more hotfix releases until I can get a round of **local** installation testing done.

**Comment by marcoobaid** [comment]
> This is just the release that keeps on giving, isn't it -- it illustrates that we don't have a really good mechanism for integration testing of non-release parts, which **because** of the large-scale changes in the users module this time are full of regressions.
> 
> I think the right thing to do is hold off on 3.2.28 now and more hotfix releases until I can get a round of **local** installation testing done.

Will be glad to assist in testing future releases on Arcolinux or Arch-based systems. We love Calamares.

**Comment by arnav7633** [comment]
I am on 3.2.40 but still the same bug
