### ISSUE TITLE
localetest fails on Alpine Linux (non-glibc system)

### ISSUE THREAD

**Issue by PureTryOut** [calamares/calamares#1490]
**Describe the bug**
When running the tests, `localetest` fails on Alpine Linux. Since it's a locale failure and Musl (which Alpine uses rather than glibc) doesn't really support that, I'm guessing it's because of using Musl.

**To Reproduce**
1. Get an Alpine Linux system or container image running
2. Compile the latest Calamares
3. Run the tests

**Expected behavior**
`localetest` to succeed.

**Screenshots and Logs**
```
74/84 Test #74: localetest .......................***Failed    0.14 sec
QStandardPaths: error creating runtime directory /run/user/1000 (No such file or directory)
********* Start testing of LocaleTests *********
Config: Using QtTest library 5.15.0, Qt 5.15.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.3.0)
PASS   : LocaleTests::initTestCase()
PASS   : LocaleTests::testEmptyLocaleConfiguration()
PASS   : LocaleTests::testDefaultLocaleConfiguration()
PASS   : LocaleTests::testSplitLocaleConfiguration()
XPASS  : LocaleTests::testTZImages() QCOMPARE(overlapcount, 0) returned TRUE unexpectedly.
   Loc: [/home/bart/Documents/Git/alpine/aports/testing/calamares/src/calamares-3.2.28.1/src/modules/locale/Tests.cpp(174)]
FAIL!  : LocaleTests::testTZLocations() 'zones.rowCount( QModelIndex() ) > 100' returned FALSE. ()
   Loc: [/home/bart/Documents/Git/alpine/aports/testing/calamares/src/calamares-3.2.28.1/src/modules/locale/Tests.cpp(216)]
FAIL!  : LocaleTests::testSpecificLocations() 'gibraltar' returned FALSE. ()
   Loc: [/home/bart/Documents/Git/alpine/aports/testing/calamares/src/calamares-3.2.28.1/src/modules/locale/Tests.cpp(245)]
PASS   : LocaleTests::testConfigInitialization()
PASS   : LocaleTests::cleanupTestCase()
Totals: 6 passed, 3 failed, 0 skipped, 0 blacklisted, 108ms
********* Finished testing of LocaleTests *********
```

**Additional context**
This happens on Alpine Linux, which uses Musl rather than glibc so that's probably to blame here.

**Comment by adriaandegroot** [comment]
What's in your `/usr/share/zoneinfo/zone.tab` ? The test checks that there's at least 100 entries (which is sensible: there are 34-or-so valid offsets, but many more zones when you take daylight-saving into account. The second tests that Gibraltar exists (as a timezone). So if you have a very-much-truncated `zone.tab` these are going to fail.

**Comment by PureTryOut** [comment]
```
✔︎ ~ wc -l /usr/share/zoneinfo/zone.tab
452 /usr/share/zoneinfo/zone.tab
```

Enough I'd say

**Comment by PureTryOut** [comment]
Ok, never mind, this was a packaging issue. `/usr/share/zoneinfo/zone.tab` is provided by the `tzdata` package which wasn't installed in the build root. Installing it made it work :see_no_evil:  Thanks for the pointer!
