### ISSUE TITLE
Translation of Calamares installer into Telugu language

### ISSUE THREAD

**Issue by Dantusaikamal** [calamares/calamares#1493]
**We are willing to translate the Calamares installer into Telugu language and other Indian languages.**
I'm an intern at Swecha organization which has more than 250 active interns and so many more active contributors working towards open-sourced projects.

**We have created our Distro based on Debian.**
Since Calamares installer is well known for it's simplicity and reliability, we decided to include it in our distribution. We definitely are amazed to see how easy Calamares makes the installation process.   

**Calamares installer already works in 54 languages as of 2019.**
Out of the languages Calamares is available in, there are a few Indian languages like Hindi, Gujarati, Malayalam already available in the installer. That's a wonderful job.
 
But we want to make the installer accessible for more people. Our OS is targeted towards Engineering students and there are about **5 lakhs students (500k)** joining Engineering colleges in Telangana and Andhra Pradesh states **every year** where Telugu is the native language.

We're also working on an Operating System which will aid school students in both the states. The OS is completely in Telugu except the installation part.

_We are ready to help translating the installer into Telugu language which would be really helpful for so many people out there. We can also translate the installer into other languages in India like Marathi and other languages._

**Comment by adriaandegroot** [comment]
![image](https://user-images.githubusercontent.com/19431457/91302731-38663b00-e7a7-11ea-9e0b-a584753024ea.png)

I obviously don't have Telugu fonts loaded and configured, but your first six strings **can** be seen. I have enabled Telugu in the languages list even if it's still at only 1%, on the assumption that some more translation will show up in the next week-and-a-half. Having it enabled makes it easier for you to test, as well.

**Comment by Dantusaikamal** [comment]
Thank you so much. We're starting the translation. We will see to it that we will reach a noticeable progress by the end of this week :)

**Comment by adriaandegroot** [comment]
I just added this to the changelog:

```
This release contains contributions from (alphabetically by first name):
 - Anke Boersma
 - Asif Mahmud Shimon
 - Sai Kamal
```

If that is **not** the way I should list your name, please let me know.
