### ISSUE TITLE
Misspelled PT-BR translation - Can't fix it from Transifex.

### ISSUE THREAD

**Issue by raploz** [calamares/calamares#1496]
Hi, i'm one of the [translators](https://www.transifex.com/user/profile/guimarcalsilva/) for Brazillian Portuguese and I've just noticed a misspelling in the translation of the string "Choose a password to keep your account safe." that went unnoticed for about 6 years. It's on the account creation screen. Unfortunately I don't have the necessary privileges to fix the translation as it has already been reviewed. I also didn't know where to ask for help, so I'd like to ask for someone else to fix it or tell someone in charge of the translations to take a look at it.

The original string is found at: ../src/modules/users/page_usersetup.ui:321

The translated string is here:  ../lang/calamares_pt_BR.ts:2326 [Transifex Link](https://www.transifex.com/calamares/calamares/translate/#pt_BR/calamares/36497817?q=text%3A'keep+your+account')

It's currently translated as: "Escolha uma senha para **mantar** a sua conta segura."

It should be translated as: "Escolha uma senha para mant**e**r a sua conta segura."

The word "mantar" doesn't exist, it should be "manter" (keep).

Thanks.

**Comment by adriaandegroot** [comment]
I checked with the Portuguese Portuguese translation, which uses *manter* as well. I have changed the string in the Brasilian translation accordingly. It is updated in the sources as well (pulled from Transifex). Thanks for reporting.
