### ISSUE TITLE
Timezones translation into Tajik Language (Any Language)

### ISSUE THREAD

**Issue by Ibragimov** [calamares/calamares#1497]
Hi Adriaan,

Today, I was so happy to explore the latest version of KDE neon with the final version of Calamares and Tajik language support in the installer! After the installation you just directly dive into Plasma Desktop and Apps with Tajik language. With love to Tajik language and actually all the languages at all it motives to make more translations and see more Tajik on the environment.

So, I noticed that in Timezone the list of territories and cities at Region and Zone selection are not translated into Tajik language, and other languages have no translations in their languages too.

How can I get to that list of countries and cities and translate them into Tajik language?

Thank you for prompt reply,
Victor Ibragimov

**Comment by adriaandegroot** [comment]
Timezone translations are a bit special.

The *name* of the zone is "Europe/Kiev", for instance and a lot of names don't get translated at all. So I didn't put that into Transifex because it would drop 600 strings on everyone, of which 95% are untranslatable anyway. "Kiev" is actually special, in that its spelling in English is now "Kyiv". I can imagine, though, that you want to represent Dushanbe propertly, and possibly other zones nearby that have a reasonable transliteration.

Anyway: the way to do this particular translation bit is to take the [translation source](/calamares/calamares/blob/calamares/lang/tz_en.ts) and translate it by hand, then add it to the source tree. Or, if you know of a resource somewhere that has translations  / transliterations of timezone names, please tell me where and I can try to import that directly.

**Comment by adriaandegroot** [comment]
So, for completeness:

- you take [this source file](https://github.com/calamares/calamares/blob/calamares/lang/tz_en.ts) with the region and zone names
- do do your translations by hand, putting the translation in the `<translation>` element and removing the `type` attribute; for instance, you'll want to end up with this (assuming I spelled it right) around line 825:
  ```
    <message>
        <location filename="../src/libcalamares/locale/ZoneData_p.cxxtr" line="176"/>
        <source>Dushanbe</source>
        <comment>tz_names</comment>
        <translation>Душанбе</translation>
    </message>
  ```
- add that file with translations as `lang/tz_tj.ts` and either PR it or let me know some other way.

So I'm going to close this issue as "explained how to do it", but I'll add the explanation to the translator's guide as well.

**Comment by Ibragimov** [comment]
Dear Adriaan,

Thank you for the explanation on how to do Tajik translation. I will translate the source file you provided and send it back to you once ready.

Have a great day!
Victor Ibragimov

**Comment by adriaandegroot** [comment]
For even more completeness (I was hoping to save you some work, but it doesn't look good):

- Unicode has giant databases of names, places, etc with translations. You can download them [here](http://cldr.unicode.org/index/downloads) . This is a **global** "source of truth" for names and the like.
- I got release 37, file `core.zip`
- That zip file contains a file `common/main/tg.xml` for the Tajik translations (note that ISO codes and Qt language codes are different here)
- That file already contains a translation for .. Dushanbe, and no other timezones. So any work you do on translating / transliterating timezones could **also** be submitted to ISO / Unicode / the CLDR tables to save other people time and effort.

**Comment by adriaandegroot** [comment]
(For other languages/scripts, like Marathi, the CLDR data is quite extensive, and I'll be looking at tools to extract this translation so I can push the whole thing to Transifex with minimal effort on the part of the translators -- except for you, since Tajik is so incomplete in the Unicode tables)

**Comment by Ibragimov** [comment]
Could you please, also take a look at https://salsa.debian.org/iso-codes-team/iso-codes to see if those translations can be handy?

**Comment by Ibragimov** [comment]
Some translations are also available at https://l10n.kde.org/stats/gui/trunk-kf5/package/kgeography/

**Comment by Ibragimov** [comment]
Tajik Translation for Timezones in now 100% translated

[tz_tg.zip](https://github.com/calamares/calamares/files/5148593/tz_tg.zip)

Have a great day!
Victor Ibragimov

**Comment by adriaandegroot** [comment]
Returning to this one briefly: Keyboard models are **not** translated at all as far as I know; much like the timezone translations I haven't got a convenient source of the strings. Calamares uses the list from `/usr/share/X11/xkb/rules/base.lst` for the keyboard names and layouts and that obviously doesn't contain any translations. If it seems feasible at all we should open an issue for getting it done systematically.
