### ISSUE TITLE
Autologin not working (Lightdm) Calamares 3.2.30

### ISSUE THREAD

**Issue by pcrepix** [calamares/calamares#1498]
Hi,
With the newest version (3.2.30), and at least one earlier (3.2.29), the Autologin option in the users Module doesn't work (at least when using LightDM). Maybe it is a similar problem to the now fixed issue where the user's password didn't get set.

**Comment by asif-mahmud** [comment]
you must set autologin group in the configuration properly. if it still doesn't work, i myself have been using users module from 3.2.26 release. new users module has a lot of changes.

**Comment by pcrepix** [comment]
The autologin group is fine. It also used to work before, but I'm not sure which was the last version. I think it has stopped working from version 3.2.29.

**Comment by erikdubois** [comment]
We have been building 21 isos all with autologin.

I can say the autologin still works fine. Calamares 3.2.29

Check out the github of ArcoLinux to see how we set it.

https://github.com/arcolinux

**Comment by philmmanjaro** [comment]
I can confirm that autologin doesn't work. However we see this additionally on **sddm** and **gdm**. Can be tested with our latest [Developer-ISO](https://osdn.net/projects/manjaro-community/storage/kde-dev/20.1/manjaro-kde-dev-20.1-unstable-minimal-200824-linux58.iso).

**Comment by pcrepix** [comment]
It works now with the new updates
