### ISSUE TITLE
Calamares do not have Urdu language in calamares_ur.ts

### ISSUE THREAD

**Issue by manzoorahmedmunawar** [calamares/calamares#1503]
**Is your feature request related to a problem? Please describe.**
I am shipping calamares in Laxer OS and the Urdu language translation is not available in it.

**Describe the solution you'd like**
Want to contribute to Urdu translation for the installer. I am a native Urdu speaker.

**Describe alternatives you've considered**
No alternative considered.

**Comment by adriaandegroot** [comment]
Hi Manzoor,

(Let me start out by being curious about transliteration: is your name منصور and the transliteration surprising to me, or is the spelling in Urdu different?)

There is an Urdu translation file for Calamares, and although the team has been around for some time there have never been any strings submitted for use, so if you look on [Transifex](https://www.transifex.com/calamares/calamares/language/ur/) at the team stats, you'll see 0 strings translated. That is also why you don't see Urdu in the language-selection drop-down. 

There is a [team](https://www.transifex.com/calamares/teams/20061/ur/) but, clearly, not very active. Take a look at the [translators guide](https://github.com/calamares/calamares/wiki/Translate-Guide) for Calamares (you probably already have, to file this request). If you tell me your Transifex username here, or via a message on Transifex, I'll add you to the coordinator position for Urdu and you can get started.

So, welcome!

**Comment by adriaandegroot** [comment]
PS. should we add Laxer OS to the [list of distributions](https://calamares.io/about/) that use Calamares?

**Comment by manzoorahmedmunawar** [comment]
Hi, and thanks for the response,

My name is "Manzoor:منظور" we write منصور for Mansoor. both names are common in south Asia.

Previously I was not on transifex and today I created an account only for translating calamares, now I am on the Urdu team but as a translator, add me to coordinator position my user name is manzoor.

from tomorrow is will start working on translation.

**Comment by manzoorahmedmunawar** [comment]
> PS. should we add Laxer OS to the [list of distributions](https://calamares.io/about/) that use Calamares?

yes, please glad you asked.

**Comment by adriaandegroot** [comment]
- I've moved you to a coordinator role in Urdu, so you can also manage other translators (if you have friends who want to help out) and review  / unreview strings. Note that Calamares doesn't care about reviewed / unreviewed status, it just pulls all the strings.
 - Laxer OS added to the list.

I'll close this ticket as "done", if you have questions or comments don't hesitate to file a new issue here or on Transifex (transifex preferred if it's a translation issue).

**Comment by manzoorahmedmunawar** [comment]
ok, thanks.
