### ISSUE TITLE
Timezones is now 100% translated into Tajik Language!

### ISSUE THREAD

**Issue by Ibragimov** [calamares/calamares#1504]
Tajik Translation for Timezones is now 100% translated:

[tz_tg.zip](https://github.com/calamares/calamares/files/5148625/tz_tg.zip)

Could you please, add the translated file to Calamares, so I try to test it with Timezones in Tajik and see if everything is OK!

Have a great day!
Victor Ibragimov

**Comment by adriaandegroot** [comment]
I have broken something else in translations in the calamares development branch, but that will be fixed before release.

**Comment by Ibragimov** [comment]
By the way, did you have a chance to preload Timezone translations for other languages? I can help with Russian translation. So please, let me know if you have something in progress?
