### ISSUE TITLE
Systematic TZ translations

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1506]
The timezone data **can** be translated. That's useful for:
- non-Latin languages, so the zones are readable
- languages which have alternate spellings for some cities
- Kyiv (Europe/Kiev)

There's a handful of translations; the Tajik translation is complete (transliteration, from Abijan to Абиҷон for instance). The translations currently do **not** go through Transifex, since it's a huge pile of names which would increase workload a great deal, and the data is **probably** already available elsewhere.

This ticket is for collecting information on other data sources and figuring out a way to import that data so that we have workable translations for all the languages Calamares supports. The Calamares [wiki](https://github.com/calamares/calamares/wiki/Translate-Guide#timezone-translations) has information on doing this translation by hand, but let's be smarter. The target format is .ts (XML sources for Qt translations), so anything that can spit out such an XML file is acceptable.

**Comment by adriaandegroot** [comment]
Comments from @ibragimov in other issues (#1497 and #1504):

-  take a look at https://salsa.debian.org/iso-codes-team/iso-codes 
- Some translations are also available at https://l10n.kde.org/stats/gui/trunk-kf5/package/kgeography/

Other data sources:
- Unicode CLDR

**Comment by adriaandegroot** [comment]
Plan of attack: post comment in this issue when there's a TZ translation for a given language.

**Comment by adriaandegroot** [comment]
**Complete**
- Tajik

**Partial**
- English (Kyiv)
- Dutch (Berlijn, Parijs)
- Swedish

**Comment by Ibragimov** [comment]
Here is a more complete list for Timezones at https://l10n.kde.org/stats/gui/trunk-kf5/package/kdelibs4support/

**Comment by Ibragimov** [comment]
Hi!

Russian translation is now 100% completed!
[tz_ru.zip](https://github.com/calamares/calamares/files/5163786/tz_ru.zip)

Have a wonderful day!
Victor Ibragimov

**Comment by Ibragimov** [comment]
By the way, the translation of the Timezones is the most easiest and the most enjoyable part of translation: It took me to listen to about 7 songs about cities on Youtube to complete this task )) Just pick up a city from the list, search it on Youtube - listen, watch and translate! ))) Good luck for other languages to complete the Timezones translation!

**Comment by Ibragimov** [comment]
Please, update both Tajik and Russian files and consider these files as final:

[tz_tg_ru.zip](https://github.com/calamares/calamares/files/5163982/tz_tg_ru.zip)

Translation of "Indian" updated to "Индийский океан" for Russian and "Уқёнуси Ҳинд" for Tajik

**Comment by Ibragimov** [comment]
Hi,

I have tested Tajik, Russian and English Timezone settings - they look so great in their native languages! Auto-detection worked perfectly and automatically set Asia/Dushanbe for me. Screenshots attached for those interested to see the beauty:

![TZ_in_Tajik](https://user-images.githubusercontent.com/1321588/92394092-597d4300-f13a-11ea-8107-885a3096d80f.PNG)
![TZ_in_Russian](https://user-images.githubusercontent.com/1321588/92394084-55e9bc00-f13a-11ea-884a-4e1599cf5857.PNG)
![TZ_in_English](https://user-images.githubusercontent.com/1321588/92394616-49b22e80-f13b-11ea-9e67-7d065437c952.PNG)

Next turn is to find a way to translate Keyboard section!
Have a wonderful day!
Victor Ibragimov

**Comment by Ibragimov** [comment]
Please, update Tajik file: The translation of "Tashkent" corrected to "Тошканд".

[tz_tg.zip](https://github.com/calamares/calamares/files/5183459/tz_tg.zip)

**Comment by Ibragimov** [comment]
Please, update Tajik file: The translation of "New York" corrected to "Ню-Йорк".

[tz_tg.zip](https://github.com/calamares/calamares/files/5255226/tz_tg.zip)

**Comment by adriaandegroot** [comment]
Yes, it's the city and not the state, well-spotted.

**Comment by Ibragimov** [comment]
Thank you for the update!

**Comment by t-tran** [comment]
This is timezone for Vietnamese
[tz_vi.ts.gz](https://github.com/calamares/calamares/files/5472672/tz_vi.ts.gz)

**Comment by adriaandegroot** [comment]
Vietnamese translation and timezone-translation added for v3.2.33

**Comment by adriaandegroot** [comment]
Closing this as "it's available, deserves regular attention though, but doesn't need to be an open issue anymore"
