### ISSUE TITLE
Finished Module (Calamares 3.2.30) "Done" button no longer available

### ISSUE THREAD

**Issue by pcrepix** [calamares/calamares#1507]
Hi,
In Calamares 3.2.30 the "Finished" module no longer shows the "Done" button when the installation has ended. Also the "Restart Now" check-box is missing, whatever setting I use in the finished.conf file.

There is only the "Cancel" button, and if it gets selected, I get a warning message whether I really want to cancel and all changes will be lost. If I click on Yes, Calamares closes, and the installation itself has worked.

So it isn't really a big bug, but it doesn't look very nice and can cause new users who install a distro to think the installation failed...

**Comment by adriaandegroot** [comment]
Have you got a link to an ISO or config files or screenshots? A quick test here doesn't show that problem, although I can get some weird results if I leave the *finished* module in the *exec* section of the sequence, e.g.

```
- show:
  - welcome
  - summary
- exec:
  - dummycpp
  - finished
```

er .. and this warning is telling, so maybe I **can** reproduce it locally already:

```
15:18:34 [0]: QMetaObject::invokeMethod: No such method Calamares::JobQueue::finish()
```

**Comment by pcrepix** [comment]
Great, it works now.
