### ISSUE TITLE
Calamares / *buntu BoF at Akademy

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1508]
This issue is filed to keep track of things discussed at the Calamares BoF at Akademy (if there is one). It's probably going to be fairly Ubuntu and OEM-oriented.

**Comment by adriaandegroot** [comment]
Relevant existing tickets from the *buntus:
 - #956 "Minimal Install" .. this should be doable with existing tools, but needs configuration (either via packagechooser, or netinstall, and I can imagine there being an ongoing need to integrate packages / netinstall with the packagechooser module)
 - #871 "OEM" is kind of stalled on "what is this supposed to look like, and what is the overall collection of features"

**Comment by Conan-Kudo** [comment]
That's unfortunate that this would be Ubuntu-oriented, otherwise I'd consider using it for Fedora KDE OEM mode.

**Comment by adriaandegroot** [comment]
@Conan-Kudo  The BoF would (have been) Ubuntu-oriented, the features are -- like all Calamares modules -- cross-distro, and cross-desktop. If there's a fedora OEM mode to be made, by all means add comments to #871 or file a separate issue so we can reconcile what's needed.
