### ISSUE TITLE
Testing Plan

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1509]
We've bumped into the people from Kiwi TCMS repeatedly at FOSDEM, and the Kiwi folks have [written up](https://github.com/kiwitcms/open-source-test-management/) a useful generic guide on getting-started-with-testing, which comes down to: you need a plan first, tools second. So this ticket is for figuring out the plan further.

**Comment by killajoe** [comment]
We do start with a testing team to start installer before releases, and it is indeed good to have a plan first. First testing phase we do out of the blue and we need to communicate a lot after starting, and there was a lot misunderstanding, then we create a little plan with introducing testers what exactly they should go to test and what different procedures they can choose from, and exactly what feedback we need including the needed logs. with this plan, it was much faster to track down issues, and the amount of useful data was multiple times bigger.

**Comment by adriaandegroot** [comment]
Here's a sample of the kind of test we might **start** with writing up and executing before a release.

## Integration Test (KaOS)

> Legend: questions marked :question: want the answer "yes", while questions marked :grey_question: want the answer "no"


 - Boot a recent KaOS ISO image in VirtualBox. Use a BIOS system (not EFI)
 - Zero out the start of the HDD with `sudo dd if=/dev/zero of=/dev/sda bs=1M count=64`
 - Prepare the filesystem -- Calamares thinks that this is a Debian-ish system and will try to install to `lib64/`
   ```
    cd /usr
    sudo ln -s lib lib64
   ```
 - Build Calamares via standard *deploycala* method:
   ```
   cd
   curl -o dp.py https://calamares.io/deploycala.py
   python3 dp.py -n
   ```
 - :question: Did it build successfully?
 - Edit the `/usr/share/calamares/settings.conf` file to replace QML modules with the widgets modules (this just to avoid UI surprises and at least one known problem with the QML modules), e.g. replace *localeq* by *locale*.
 - Run Calamares: `sudo calamares -D6`
 - :question: Does it start? :grey_question: Does it have a debug-button in the lower-left? :question: After clicking on *About*, does the pop-up show the expected Calamares version?
 - Click though the installation (**TODO:** that's a bit vague) and wait for the installation to complete.
 - :question: Does it complete successfully? :question: Can you reboot the system? :question: Does the system reboot into KDE Plasma as designed?
