### ISSUE TITLE
Systematic Keyboard Translations

### ISSUE THREAD

**Issue by Ibragimov** [calamares/calamares#1515]
Dear Adriaan,

Could you please, set up Systematic Translations for Keyboard. At least language names and some other strings can be translated into Tajik and any other languages.

Calamares Installer in Tajik Language have untranslated strings:

![Tajik-2020-09-25-12-55-05](https://user-images.githubusercontent.com/1321588/94242326-4d152a80-ff2f-11ea-9bf8-cf196f4f69f9.png)

Have a great day!
Victor Ibragimov

**Comment by adriaandegroot** [comment]
Now that #1211 has landed, there is a model that **could** support translations, so this is finally possible (but not implemented yet).

**Comment by adriaandegroot** [comment]
@Ibragimov Can you take a look at https://github.com/calamares/calamares/blob/issue-1515/lang/kb_tg.ts ? The branch is https://github.com/calamares/calamares/tree/issue-1515/ and I'll push a few more things to that. It could land in the next release if you fix the few strings I have translated in the Tajik file -- I used Google translate set to Russian, and then a Ukranian keyboard layout to make up some more strings. The most important strings there are "Generic <N>-key PC", "Default" (keyboard variant) and possibly some mentions of Tajik.

![image](https://user-images.githubusercontent.com/19431457/97803888-791d7d00-1c4c-11eb-8eec-c5834321f61c.png)

**Comment by Ibragimov** [comment]
Dear Adriaan,

Thank you so much for making it possible!!!
Tajik translation is in progress!!! Hope to complete it soon!!!

Have a great day!
Victor Ibragimov

**Comment by adriaandegroot** [comment]
(There is some more infrastructural work to be done here, so I'm moving it to the next milestone so I can get 3.2.33 out today with new translations and groups-fixes)

**Comment by Ibragimov** [comment]
Dear Adriaan,

Please, add partial Tajik translations for the Keyboard.

[kb_tg.zip](https://github.com/calamares/calamares/files/5485944/kb_tg.zip)

Have a great day!
Victor Ibragimov

**Comment by adriaandegroot** [comment]
The Tajik support has landed in Calamares 3.2.33, released just now.

**Comment by demmm** [comment]
Can this be closed?  Seems the linked commit fixed the issue.

**Comment by Ibragimov** [comment]
It can be closed - Tajik translations will be completed over time to 100% to have the Installer work fully in Tajik Language. Thank you so much for support!
