### ISSUE TITLE
find_package( KPMcore 3.3 ) should be find_package (KPMcore) ... I think

### ISSUE THREAD

**Issue by dufresnep** [calamares/calamares#1520]
While installing KaOS 2020.09, I discovered that when I do manual partitioning, the type of the /boot partition with boot flag is set to 700 (Basic Microsoft data), rather than EF00 (Uefi partition).

This result in:
```
***************************************************************
Found invalid GPT and valid MBR; converting MBR to GPT format
in memory. 
***************************************************************

Python Error:
 <class 'FileNotFoundError'> 
 [Errno 2] No such file or directory: '/tmp/calamares-root-m3u8rswz/boot/loader/entries/KaOS_2020.09.conf' 
 File "/usr/lib/calamares/modules/bootldr/main.py", line 229, in run
    install_bootloader(boot_loader, fw_type)

  File "/usr/lib/calamares/modules/bootldr/main.py", line 210, in install_bootloader
    create_conf(uuid, conf_path)

  File "/usr/lib/calamares/modules/bootldr/main.py", line 104, in create_conf
    with open(conf_path, 'w') as f: 
```
I then found that if during the installation, during unpacking, I change the type of the /boot partition to EF00, installation works fine.

I have read that you need KPMCore greather than 4.0 for calamares to be able to set the partition type to EF00 when the boot flag is set.

I dicovered that in https://github.com/KaOSx/calamares/blob/master/src/libcalamares/CMakeLists.txt line 117:
you do:
find_package( KPMcore 3.3 )

It seems that you think 3.3 is a minimal version. It is not, you are asking for KpmCore to act like if it was a 3.3 version.
As explained in: https://cmake.org/cmake/help/latest/command/find_package.html#version-selection
More precisely, this set KPMCore version to be 3.3, so that later in the code:
```
    if( KPMcore_VERSION VERSION_GREATER_EQUAL "4.2" )
        add_definitions(
            -DWITH_KPMCORE42API
            -DWITH_KPMCORE4API
        ) # kpmcore 4.2 with new API
    elseif( KPMcore_VERSION VERSION_GREATER_EQUAL "4.0" )
        add_definitions( -DWITH_KPMCORE4API ) # kpmcore 4 with new API
    elseif( KPMcore_VERSION VERSION_GREATER "3.3.70" )
        message( FATAL_ERROR "KPMCore beta versions ${KPMcore_VERSION} not supported" )
    endif()
```
I believe... not tested, not really knows much about CMake, but by the documenation of CMake I believe -WITH_KPMCORE4API is not defined, even if the version of the package KPMCore on the system is greather then version 4.

I would suggest you do: find_package( KPMcore 4.1 ) ... which I would believe will work even if the system have a 3.x version.

**Comment by abucodonosor** [comment]
@dufresnep 

that is a KaOS only modules downstream, you have to report that to @demmm.

**Comment by dufresnep** [comment]
I mistakenly given the link downstream, but I believe I see the same at:
https://github.com/calamares/calamares/blob/calamares/src/libcalamares/CMakeLists.txt line 117

**Comment by abucodonosor** [comment]
Well, your problem is coming from;

```
Python Error:
 <class 'FileNotFoundError'> 
 [Errno 2] No such file or directory: '/tmp/calamares-root-m3u8rswz/boot/loader/entries/KaOS_2020.09.conf' 
 File "/usr/lib/calamares/modules/bootldr/main.py", line 229, in run

....

```
and not from cmake.

That module is a KaOS only thing.

**Comment by dufresnep** [comment]
Still, you have code that never execute in your version, because the -DWITH_KPMCORE4API is never done.

**Comment by dufresnep** [comment]
I say this because find_package doc says in https://cmake.org/cmake/help/latest/command/find_package.html#version-selection that "If the version is acceptable the following variables are set:

<PackageName>_VERSION
full provided version string" as I understand, provided by the find_package version parameter... not from the package found.

**Comment by abucodonosor** [comment]
The cmake code is fine, I don't see anything wrong with it.

**Comment by adriaandegroot** [comment]
> It seems that you think 3.3 is a minimal version. 

Calamares (the 3.2 series, still) **does** have KPMCore 3.3 as a minimal version, and there are distro's that use that older version of KPMCore.

> It is not, you are asking for KpmCore to act like if it was a 3.3 version.
> As explained in: https://cmake.org/cmake/help/latest/command/find_package.html#version-selection

I think you're reading that document incorrectly. We ask for a KPMCore version **at least** 3.3 that is 3.3 compatible; what is compatible is entirely up to the versioning file from KPMCore. It is, of course, free to do whatever silly things.

> More precisely, this set KPMCore version to be 3.3,

It should very much not do that, and if it does, that's a bug to report to KPMCore. Where the documentation of CMake talks about "full provided version", thats the version provided by the software you're looking for, not the version that is stated in the `find_package()` call (which is called the "full requested version").


> so that later in the code:


```
    if( KPMcore_VERSION VERSION_GREATER_EQUAL "4.2" )
        add_definitions(
            -DWITH_KPMCORE42API
            -DWITH_KPMCORE4API
        ) # kpmcore 4.2 with new API
    elseif( KPMcore_VERSION VERSION_GREATER_EQUAL "4.0" )
        add_definitions( -DWITH_KPMCORE4API ) # kpmcore 4 with new API
    elseif( KPMcore_VERSION VERSION_GREATER "3.3.70" )
        message( FATAL_ERROR "KPMCore beta versions ${KPMcore_VERSION} not supported" )
    endif()
```

The CMake code in the *partition* module, and the code in *libcalamares* are unfortunately different; that's something that can be fixed-up.

> I believe... not tested, not really knows much about CMake, but by the documenation of CMake I believe -WITH_KPMCORE4API is not defined, even if the version of the package KPMCore on the system is greather then version 4.

You can test this, with `message( STATUS "About KPMcore: ${KPMcore_FOUND} ${KPMcore_VERSION}" )`, possibly also printing some other bits, in the CMake code. And on KaOS 2020.04, it tells me `KPMcore_VERSION` is 4.1.0.

**Comment by adriaandegroot** [comment]
Similarly, doing the build with `make VERBOSE=1 calamares` you can see that `-DWITH_KPMCORE4API` is passed to the build of the library (in particular, to the build of libcalamares).

So I'm fairly sure that this isn't the issue.

**But** let's return to the original problem, ignoring the red herring of CMake and KPMcore versioning (er.. unless KaOS 2020.09 did something weird there). When doing manual partitioning, the boot flag seems to be picking the wrong value. **That** is worth debugging, in the relevant C++ code (in the *partition* module).

**Comment by abucodonosor** [comment]
@adriaandegroot 

AFAIK, the FLAGS problems occurred in Kpmcore 4.0 and should be sorted since then. 
Anyway, that flag is not really a problem regarding booting at least for the GRUB bootloader, I've no idea about systemd-boot.

The only problem for us having that flag set on a partition right now is when you try to reuse it since we only check for the EFI flag
alone.

**Comment by demmm** [comment]
This issue can be closed.
KaOS builds obviously use the correct cmake, output shows KPMCORE4API.
In KaOS forum it has been asked to use automated, for it has never been clear if the manual options chosen were done correctly (from the many posts, one after the other showed doing complete unsupported actions).
Whatever cmake call is used is clearly not the issue.

Plus, this does not belong at all in upstream Calamares, needs to be reported in downstream KaOS.
