### ISSUE TITLE
Update "About" page screenshots

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1532]
The [About page](http://calamares.io/about/) on the Calamares website shows some screenshots, which are quite outdated **and** which are missing the range of styling that is available to Calamares. The website lives in [this repository](https://github.com/calamares/calamares.github.io), also on GitHub.

For this task, collect a dozen screenshots of Calamares "in action", from a few different distributions (e.g. KDE neon, KaOS, and ArcoLinux or Manjaro) and update the About page with them. For bonus points, replace the existing grid-layout of screenshots with a carrousel or some other way of displaying more screenshots with captions so it looks a little more modern.

**Comment by themayankjha** [comment]
This would be my first actual contribution to open source. I would love to work on this issue.

**Comment by demmm** [comment]
Implemented, see https://github.com/calamares/calamares/issues/1533
Hopefully a few more distros will respond, but better track that in 1533 issue/website branch.
