### ISSUE TITLE
Update website overall look-and-feel

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1533]
The  [Calamares website](http://calamares.io/) is a GitHub pages site -- Jekyll plus Markdown -- is basically a blog with release announcements and some pages about the product. It looks rather dated, and as a product presentation is lacking a lot of, shall we say, marketing pizzazz.

This task is to update the look-and-feel of the site -- within the limits of GitHub pages -- so that it's a little less "2010", while preserving the essential "release notifications" and "developer notes" role of the blog part of the site. There's plenty of space for innovation: if you have a good-looking Jekyll theme that works somewhere else, point it out in comments and then let's figure out how to shove existing Calamares content into it.

**Comment by demmm** [comment]
Are you looking for the same layout, with home page the blog, or (my preference) the home page much more an intro to cala, with screenshots etc (splitting out from the about page)?
I maintain a lot of Jekyll sites, so not too hard to adjust one of the themes to cala.

**Comment by adriaandegroot** [comment]
I think more of a product-presentation page, the releases / news / history bits easily findable (after all, our audience of distro's needs to find the release notes), less pagination in the blog archive. I like the band site.

**Comment by deprov447** [comment]
I looked up for some themes and these found these fitting in quite good for Calamares : 
- [Forty](https://andrewbanchich.gitlab.io/forty-jekyll-theme/) (*although somewhat fancy)
- [Hyde](https://hyde.getpoole.com/)
- [Just the Docs](https://pmarsceill.github.io/just-the-docs/)

We can also combine Hyde and JustTheDocs to come up with something aesthetic. Maintainers please have a look and tell if you like any.

**Comment by adriaandegroot** [comment]
@deprov447 Of those 3, *Hyde* seems most instantly-applicable to Calamares, but that's because it has a sidebar like the application does. What I should stress is this: my sense of aesthetics can fit in a matchbox filled with non-aesthetic sand. You can paint the website pink, I probably won't notice.

The Calamares site needs to present *two* things well, and link to a handlful of other things:
- what-is-this-product
- what's new
The links are to source, documentation, team, etc. Having a nicer product presentation, rather than just the blog-roll of release announcements, should be the thing to focus on.

**Comment by deprov447** [comment]
Okay then, I would try to customize the theme to fit in with requirement. And then ask for content required.

**Comment by adriaandegroot** [comment]
@deprov447 All the content is in the existing Calamares website repo, https://github.com/calamares/calamares.github.io

**Comment by deprov447** [comment]
> Work in progress

I am working here: [https://github.com/deprov447/calamares-web.github.io](https://github.com/deprov447/calamares-web.github.io)
And a temporary deployment is is [https://calamares.netlify.app/](https://calamares.netlify.app/)

**Comment by adriaandegroot** [comment]
The netlify deployment has been updated.

There are three **distinct** areas / directions for improvement:
 - using GH APIs to provide information about Calamares (requires Javascript?)
 - updating the looks (requires CSS)
 - updating content with new / current information (requires text)

I do not really understand what would drive to netlify, though: do GH pages have limitations on Javascript loading, or .. . For the looks, @demmm has some more flashy ideas (moving into what to me feels like more-modern, with more and bigger graphics rather than mostly text-on-flat-background), and content is **mostly** the release blog posts.

**Comment by demmm** [comment]
>have limitations on Javascript loading

No such issues afaik, you can make GH Pages as flashy as you want to them to be.

One more question, is it preferred to keep the documentation on the github Wiki, or create a Docs section on the new website?

**Comment by deprov447** [comment]
GH-pages don't offer much theming options. There is only a set of jekyll-themes supported by github. And Hyde isn't one of them.

**Comment by demmm** [comment]
@deprov447 have you looked at my first response in this thread? The site linked there is pure github pages/jekyll. I never found any restriction yet working with GH pages in all of the sites I maintain.

**Comment by demmm** [comment]
And if you are looking for flexibility in listing the posts, here an example of a Jekyll/GH page using a little js to make the sidebar collapsible/expanding:
https://kaosx.us/news/

**Comment by deprov447** [comment]
[there is a section here, stating "not all jekyll sites are supported by gh-pages" ](https://help.github.jp/enterprise/2.11/user/articles/adding-a-jekyll-theme-to-your-github-pages-site/)

I don't know about yours but hyde isn't getting support from gh-pages (unless you know a workaround)

**Comment by deprov447** [comment]
> And if you are looking for flexibility in listing the posts, here an example of a Jekyll/GH page using a little js to make the sidebar collapsible/expanding:
> https://kaosx.us/news/

js isn't big of a deal... And Im using  github-api for the necessary update

**Comment by adriaandegroot** [comment]
Looking at the theming docs, there is also the *remote_theme* key, and the option to add the styling and templates directly to the repo.

**Comment by demmm** [comment]
A very "rough cut" of what I was thinking of, this is based on the minimal-mistakes theme.  None of the images are what they will be/should be, neither is the News page done or About page updated:
https://demmm.github.io/
If this is something to work on more, then I can add as a new branch for the cala site, leave old as is, and anyone can cooperate on this site.
Minimal-mistakes has one of the best options to adjust all with very well documented settings.

**Comment by erikdubois** [comment]
![calamares-1](https://user-images.githubusercontent.com/10594806/99806608-8ab4bf00-2b3e-11eb-8147-3f1cc97405a4.png)
![calamares-2](https://user-images.githubusercontent.com/10594806/99806612-8b4d5580-2b3e-11eb-9c13-b2a6b91ffafa.png)
![calamares-3](https://user-images.githubusercontent.com/10594806/99806614-8be5ec00-2b3e-11eb-859d-6db49ba2462d.png)
Larger version

**Comment by erikdubois** [comment]
Smaller version 1070 width

![calamares-1-small](https://user-images.githubusercontent.com/10594806/99806640-9acc9e80-2b3e-11eb-9507-2c911f746ec2.png)
![calamares-2-small](https://user-images.githubusercontent.com/10594806/99806642-9b653500-2b3e-11eb-92ac-3808df999307.png)
![calamares-3-small](https://user-images.githubusercontent.com/10594806/99806644-9bfdcb80-2b3e-11eb-9f36-6e2b84f2d1ef.png)

**Comment by apachelogger** [comment]
Welcome
![1](https://user-images.githubusercontent.com/809987/99817349-16cde300-2b4d-11eb-8662-e5ddd626e02a.png)

Partitioning
![2](https://user-images.githubusercontent.com/809987/99817376-1e8d8780-2b4d-11eb-88b9-c015c01dcdf9.png)

Slideshow
![3](https://user-images.githubusercontent.com/809987/99817420-2e0cd080-2b4d-11eb-807e-23575d7b91ed.png)

**Comment by demmm** [comment]
Thanks.  Arco & KDE Neon added:
https://demmm.github.io/#gallery

**Comment by demmm** [comment]
@apachelogger I could use this shot with default calamares to use for header background, just in case you also have a vanilla Cala around.....
https://user-images.githubusercontent.com/809987/99817349-16cde300-2b4d-11eb-8662-e5ddd626e02a.png
Used that one for now, to get the colors right.

**Comment by demmm** [comment]
Branch issue-1533 is ready for deployment, preview still at https://demmm.github.io/ (kept in sync with that branch to keep preview possible)

**Comment by apachelogger** [comment]
@demmm here you go

![Screenshot_20201123_110851](https://user-images.githubusercontent.com/809987/99955683-115add80-2d85-11eb-8dc3-c8659c18fe6d.png)
