### ISSUE TITLE
Change timeout in module shellprocess

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1536]
https://github.com/calamares/calamares/blob/calamares/src/modules/shellprocess/shellprocess.conf

We got feed-back from users that the timeout was too short.
Now 10 seconds. 
It depends what we do in those scripts but it also depends on the hardware of the users. 
Since Linux is often installed on the oldest machine they can find... Calamares will time-out and the installation halts.

We have changed our timeout.

I would advise to set the timeout higher by default. Say 30.

**Comment by abucodonosor** [comment]
This is why it is a distribution thing.

If you have known scripts to run something huge you have to set appropriate timeout values on those script(s).

I personally think 10 sec is a good default value, everything else is up2 the distros to change.

**Comment by adriaandegroot** [comment]
The timeout needs tuning for whatever is being done. The default timeout (when none is specified) isn't particularly special and 10 or 30 is arbitrary anyway -- you should be setting a timeout based on some kind of expectations of "this finishes quick" or "this depends on disk speed" or something else, and then best-guess it.

TODO in 3.3: remove the default value and just bail out during config-reading if there isn't one set explicitly.

**Comment by adriaandegroot** [comment]
That said, 30 or 10 is arbitrary, so ..
