### ISSUE TITLE
Friulian translation transifex

### ISSUE THREAD

**Issue by tmtfx** [calamares/calamares#1537]
Hi, I'd like translate Calamares to friulian language.
As other projects under transifex, I need to ask someone within the project to add this language before (requesting the language and) joining the team; this is because even if friulian language is supported by transifex, for some reason it won't show up in the request language section.

Best regards
Fabio

**Comment by tmtfx** [comment]
sorry my fault

**Comment by adriaandegroot** [comment]
I have approved the language now, but I can't find your Transifex account in order to add you as language coordinator.

**Comment by adriaandegroot** [comment]
.. and that's resolved, too.

**Comment by adriaandegroot** [comment]
I translated one string (a welcome message, to "Sono pazzi questi Friuliani", which is something Obelix might say if Obelix visited Friulia; he certainly said "Sono pazzi questi Romani", although in Gaulish in the original, and not even the French "Ils sont fous ces Romains"). I fetched and built the translations and added language code "fur" and then Friulian shows up in the language-selector for Calamares.

**Comment by tmtfx** [comment]
Thank you so much, I'll start translating as soon as possible, btw actually "Sono pazzi questi friulani" is Italian :)
Regards
Fabio

**Comment by tmtfx** [comment]
my transife profile name is TmTFx
