### ISSUE TITLE
GeoIP JSON handling failing

### ISSUE THREAD

**Issue by wxl** [calamares/calamares#1540]
**Describe the bug**
Modules that use GeoIP (e.g. `welcome`, `locale`) are failing to parse JSON correctly, whereas XML is no problem.

**To Reproduce**
 1. Ensure Internet is connected
 1. Make sure that GeoIP is being used and modules using it are set to use `style: json` with a provider that actually serves JSON.
 1. Run the installer
 1. Advance to the time zone selection map

**Expected behavior**
The actual time zone is selected.

**Actual behavior**
New York is selected, apparently due to invalid data, though fetching the data manually shows no such problem.

**Screenshots and Logs**
Logs include lines like:
```
virtual QString CalamaresUtils::GeoIP::GeoIPJSON::rawReply(const QByteArray&)
    WARNING:Invalid YAML data for GeoIPJSON
setGeoIP(Config*, const QVariantMap&)::<lambda()>
    GeoIP result for welcome= ""
void setCountry(Config*, const QString&, CalamaresUtils::GeoIP::Handler*)
    Unusable country code ""
.. Obtained from "https://ipapi.co/json" ( 1 "country" )
```

**Additional context**
We had a similar bug that was resolved when we switched from 3.2.12 to 3.2.14. It looks like the issue has existed again since at least 3.2.20, if not sooner.

The above results were obtained also with the latest master.

FWIW, downstream bug is [here](https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/1898501).

**Comment by demmm** [comment]
Can you post the used welcome.conf?

**Comment by wxl** [comment]
```
---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true
showDonateUrl:  https://lubuntu.me/donate/

requirements:
    requiredStorage:    8
    requiredRam:        0.5
    internetCheckUrl:	https://lubuntu.me

    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - root
        - storage
        - ram
geoip:
    style:  "json"
    url:    "https://ipapi.co/json"
    selector: "country"
```

Changing `style` and the `url` endpoint to `xml` resolves the issue.

**Comment by adriaandegroot** [comment]
There is a specific test application for GeoIP things, namely `test_geoip` (built as part of Calamares if tests are enabled, not installed). You can do the following:

```
curl https://ipapi.co/json | ./test_geip  json
```

.. although right now neither the JSON or XML variants give me a suitable response (in both cases the output of the test program is "No TimeZone determined from input.")

**Comment by adriaandegroot** [comment]
I have added some debug-logging, and in the depths of the network request, QNetworkReply is giving me an error:
```
HTTP error QNetworkReply::UnknownContentError on request for QUrl("https://ipapi.co/json")
```
Using `curl --verbose` on that URL, and on the XML endpoint, I see that the **JSON** endpoint has a `content-type:` header without an encoding. That *might* be the cause of the problem.

**Comment by adriaandegroot** [comment]
It isn't the content-type, as far as I can tell. Instead, while I can `curl` that URL all I like, when I fetch it inside Calamares, I get the unknown content error and the body of the reply has a "rate limited" JSON body. But I changed the user-agent in the requests, and then all of a sudden I'm getting data again.

So to sum up:
- **not** a bug in Calamares (except maybe that it didn't log things very clearly)
- an online service provider changed the data that was being sent back from an endpoint
- now it works again (briefly, perhaps: you're using the "free access" tier of this GeoIP provider)

**Comment by wxl** [comment]
Ok, I stand corrected. However, your mention about user-agent brings a question: should we consider a user-agent that is going to be more compatible?

**Comment by adriaandegroot** [comment]
It's really weird that (whatever the QNAM default user-agent is) triggers something in the consumer. I wonder if maybe all the Calamares uses in the world are eating up the free trial numbers, and this change of User-Agent is just a lucky chance? Maybe Calamares should construct a distro/branding-specific User-Agent string so that at least Lubuntu can be distinguished from Manjaro at the receiving end. I really don't know: ipapi.co is a commercial service.

**Comment by wxl** [comment]
I think that any clarity that could be exposed through the logs would be helpful. Perhaps having the full response be something that is shown in the debug window would be helpful.
