### ISSUE TITLE
After Installation of Custom KDE with Calamares SDDM only shows black screen and cursor - with Ubiquity Installer it works fine

### ISSUE THREAD

**Issue by ibuntuos** [calamares/calamares#1541]
**Bugdescription**
I have a custom ISO here which is basically just a remastered fresh install auf KDE Neon. No changes made, only a normal Remastering of the System was done. Both Ubiquity-Installer and Calamares Installer were put in it. The Custom ISO was started in legacy mode and than the Ubiquity-Installer was run. Installation went through without problems, System booted, everything fine. 

Than the same ISO was started again, this time the Calamares Installer was used to install the system, it went through with success, no error messages, System boots for the first time and get's stuck when sddm should load, presenting only a black screen with a cursor. 

**To Reproduce**

You can basically remaster any KDE Neon or Kubuntu Version and it always will be installable with ubiquity but not with Calamares, it always will get stuck when SDDM loads with black screen and cursor. So Calamares clearly misses to do something what ubiquity does when configuring the new installed system. 

I don't know what KDE Neon has changed within the Calamares Modules so that their system can be installed without this bug - but I would need to know what they changed. 

My calamares setting you can see here:
https://github.com/ibuntuos/iBuntu-builder/tree/master/conf/calamares
We just installed calamares on a Kubuntu 20.04 version from the standard ressources but as I said the problem also already occured in 18.04

Would be nice if I wouldn't need to re-engineer what KDE neon did different - can someone please help me out how to get rid of this bug?

**Comment by abucodonosor** [comment]
This is a configuration issue, not a calamares bug.

You should probably use the Neon configuration files and change branding.

A quick look shows some of your configuration files are incomplete. Also from what I remember Neon has some custom scripts running to setup needed things.

Your dysplaymanager.conf is missing sysconfigSetup: false as an example, also why would you need basicSetup: true?

**Comment by ibuntuos** [comment]
Thanks for the advice. I actually took this settings from the life-edu project but their building tool only copies the whole home folder of the existing user to the live cd and than they use calamares to pure copy the live system permanent to the hard drive like the old remastersys did in Backup mode. I couldn't find documentation on how to propperly configure Calamares all I had so far was if I use their config files in this kind of "backup" mode it works but if I want to create my own user during install it leads to this black screen with cursor issue. 

Is there either a link on where it's documented how to configure calamares? I googled a lot but I only can dig myself through other bug reports but didn't found yet a document which explains the content of the .conf files. Is there something like this or is it in a way like "the code of the calamares modules is documentation enough" ?

Thanks for any further help

**Comment by abucodonosor** [comment]
Each configuration file has his options explained, also see:

https://github.com/calamares/calamares/wiki/Deploy-Configuration

**Comment by ibuntuos** [comment]
Thanks, that link I missed, I will read myself into it.

**Comment by ibuntuos** [comment]
I edited now the displaymanager.conf and the other config files like in kde neon but still i get black screen with mouse cursor after first boot I'm not sure what I have missed.

**Comment by abucodonosor** [comment]
I don't know, but your calamares is still different from Neon's, very different.

See:

https://invent.kde.org/neon/neon/calamares-settings/-/tree/Neon/unstable/desktop

**Comment by abucodonosor** [comment]
Also, boot to CLI and find out what the error is?
