### ISSUE TITLE
(Arch-based) Use pacman -Syr or pacstrap for the packages module

### ISSUE THREAD

**Issue by SkyyySi** [calamares/calamares#1545]
**Is your feature request related to a problem? Please describe.**
When using the packages module with pacman (and probably other package managers, too), several components need to be copied onto the new root (mainly the base meta-package and a working network config). Some users may want this solution as that can also be used offline, but others may prefer using pacman directly as it avoids the need of updating the system after a install, thus slightly reducing the risk of breakage (depending on how well the install medium has been maintained). Plus the current approach of calamares requires more work than just a package list.

**Describe the solution you'd like**
Arch Linux itself uses another aproach to calamares: It uses a script called `pacstrap`, which can also install packages to a new root, except it does not need the prior configuration. However, since some Arch derivatives don't ship with it, the better option will probably be `pacman -Syr`. the -r flag allows for setting a custom package root, so it could be used to use the boot media's install of pacman which can automatically handle installing the applications to the desired location.

**Describe alternatives you've considered**
As stated above, either `pacstrap` (upside: handles basic setup; downside: not always present) or `pacman -Syr` (upside: can be expected, as, in practice, no one would base an Arch installed on another base; downside: cannot handle as many things).

**Additional context**
Maybe the best option would be to keep the `pacman`-backend option to do the same, but too add a `pacstrap` option along side it. That way, existing installers wouldn't need configuration.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/Calamares_current/tree/master/src/modules/pacstrap

**Comment by adriaandegroot** [comment]
Presumably EndeavourOS has something (although that link now 404s), and an alternative *packages* backend -- I **think** that's what you are asking for -- should be PR'ed directly to that module.
