### ISSUE TITLE
Non-latin keyboard switcher does weird things with options

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1556]
@LordTermor to reproduce:

- start Calamares with a *us* keyboard layout, and *ctrl:swapcaps* set, go to the keyboard page
  ```
   adridg@saskatoon:~/src/calamares/build> setxkbmap -query
   rules:      evdev
   model:      pc105
   layout:     us
   options:    ctrl:swapcaps
   ```
- select Russian keyboard
   ```
   rules:      evdev
   model:      pc105
   layout:     us,ru
   variant:    ,
   options:    grp:alt_shift_toggle,ctrl:swapcaps
   ```
- select Chuvash variant
   ```
   rules:      evdev
   model:      pc105
   layout:     us,ru
   variant:    ,cv
   options:    grp:alt_shift_toggle,ctrl:swapc,grp:alt_shift_toggle,ctrl:swapcaps
   ```

**Comment by adriaandegroot** [comment]
Switching to the default Russian variant again adds another corrupted set of options, so it then has `options: grp:alt_shift_toggle,ctrl:swapc,grp:alt_shift_toggle,ctrl:swapc,grp:alt_shift_toggle,ctrl:swapcaps`

**Comment by LordTermor** [comment]
https://github.com/calamares/calamares/blob/c36aa43f86118f2fd8c7c1304c27a3c7b6ce5605/src/modules/keyboard/Config.cpp#L111

`return outputLine.mid( index, lastIndex - 1 );` should be `return outputLine.mid( index, lastIndex - index );`

I thought (somewhy) that `QString::mid` takes absolute position as second parameter but in fact it takes number of characters. I tested and it works fine with this change. I really apologize.
