### ISSUE TITLE
plasmalnf not changing LookAndFeelPackage in kdeglobals

### ISSUE THREAD

**Issue by jghodd** [calamares/calamares#1573]
I was doing some testing on my distro of plasmalnf and realised that although splash and lockscreen were being changed as expected, the plasmalnf module was not changing the LookAndFeelPackage setting in .config/kdeglobals, which is what actually changes the theme. Am I missing something in the plasmalnf config file? I checked through the source code and could only find where setting preselect read the contents of kdeglobals, and the call to lookandfeeltool which correctly appears to use its --apply option. The issue is, as I described, if kdeglobals' LookAndFeelPackage setting isn't changed to the selected theme, the selected theme isn;t properly applied.

Suggestions?

Edit: just an FYI that this used to work correctly, and I understand that this issue may have arisen due to a change in plasma - specifically plasma-desktop that provide lookandfeeltool. I'm currently running plasma v5.20.2, although this change would have occurred a couple or a few versions back.

**Comment by adriaandegroot** [comment]
If I run `lookandfeeltool  -a org.kde.breezedark.desktop` in my local KDE Plasma setup, there are 7 files changed plus the directories *gtk-3.0* and *xsettingsd*. The theme changes to Breeze Dark -- I'll check in a moment if it survives a logout/login. None of the files contains a *LookAndFeelPackage* setting (I assume you wrote it that way to indicate it is a key in the *kdeglobals* file). I **do** have this in `~/.config/kdeglobals`:

```
[General]
ColorScheme=BreezeDark
Name=Breeze Dark
```

**Comment by adriaandegroot** [comment]
(It does survive a reboot)

If your live environment is also Plasma, you should see the look-and-feel of the live environment follow the setting in Calamares, as it calls the lookandfeeltool each time. In the log of the installation, you should be able to see the command that runs lookandfeeltool; it is a bit unusual since it uses `sudo` to change to the (just-created, and hopefully sudo-able -- perhaps you are running afoul of the problem that sudo isn't being set up correctly in the target system?) user in the target system and it is supposed to just DTRT there.

The code on the Calamares side hasn't changed for a long time.

What distro, BTW? It's often easier if I have a live ISO I can play with, myself.

**Comment by jghodd** [comment]
Hey bud. Thanks for the response. I know the code hasn;t changed for a while. I use my own lookandfeel themes and the files I see changing when I change a global theme via systemsettings are these:

kdeglobals:LookAndFeelPackage=org.bluestarlinux.summerview
kscreenlockerrc:Theme=org.bluestarlinux.summerview
ksplashrc:Theme=org.bluestarlinux.summerview
kwinrc:DesktopLayout=org.bluestarlinux.summerview
kwinrc:DesktopListLayout=org.bluestarlinux.summerview
kwinrc:LayoutName=org.bluestarlinux.summerview

so, four files, six changes. When I do an installation using calamares, plasmalnf correctly changes kscreenlockerrc, ksplashrc and kwinrc, but does not change kdeglobals - it's the kdeglobals::LookAndFeelPackage setting that changes the desktop background, so it's kinda important. If I manually change it after the fact and reboot, that, of course, does what i expect and the desktop background changes. I'm going to make the assumptions here that 1) if there were an issue with sudo-ing the lookandfeeltool command, then kscreenlockerrc, ksplashrc and kwinrc would not have been changed; and 2) this issue may be the result of a plasma change somewhere along the line because it used to work just fine (which is why I hadn;t tested this feature in a while). It may not be the plasmalnf code at all that's the problem - it could be a deficiency introduced to lookandfeeltool. As I pointed out, I looked through your code and found nothing amiss. The syntax of your call to lookandfeeltool appears perfectly correct. I was bringing this to your attention as a potential issue that I might still have to solve on my own. If I have to add my own custom code to plasmalnf to fix this, I will. I do note that your code grabs the current theme from the live system's kdeglobals::LookAndFeelPackage setting, so I'll make a 3rd assumption that the installation's kdeglobals::LookAndFeelPackage does also need to get set correctly.

As the theme settings suggest, my distro is bluestar linux. You can download my latest iso from here: 

https://sourceforge.net/projects/bluestarlinux/files/distro/bluestar-linux-5.9.3-2020.11.02-x86_64.iso

**Comment by jghodd** [comment]
Perhaps I could get a suggestion from you as to how to set LookAndFeelPackage in the installation's kdeglobals file. Just for grins I went ahead and tried this from PlasmaLnfJob::exec

        KConfigGroup cg( KSharedConfig::openConfig( QStringLiteral( "kdeglobals" ) ), "KDE" );
        cg.writeEntry( "LookAndFeelPackage", m_id );

fully expecting that to only change the live system's kdeglobals::LookAndFeelPackage setting, which is exactly what it did. Is there some graceful way, along the same lines, to change the installation's kdeglobals settings without having to hobble together a bash + sed command?

**Comment by adriaandegroot** [comment]
You will need to add in the root mount path -- since the **target** system needs to be modified, not the host, and `/home` (just plain like that) is a path in the host. Calamares mounts the target root somewhere in `/tmp`, but provides a (convenient?) C++ API to get paths in the target:
```
CalamaresUtils::Systemm::instance()->targetPath( "/home" );
```

**Comment by jghodd** [comment]
That was already in there, Adriaan.

KConfigGroup cg( KSharedConfig::openConfig( **system->targetPath(configPath)** ), "KDE" );

Here's the working exec():

Calamares::JobResult
PlasmaLnfJob::exec()
{
    cDebug() << "Plasma Look-and-Feel Job";

    auto system = CalamaresUtils::System::instance();
    Calamares::GlobalStorage* gs = Calamares::JobQueue::instance()->globalStorage();

    QStringList command( { "sudo",
                           "-E",
                           "-H",
                           "-u",
                           gs->value( "username" ).toString(),
                           m_lnfPath,
                           "-platform",
                           "minimal",
                           "--resetLayout",
                           "--apply",
                           m_id } );

    int r = system->targetEnvCall( command );
    if ( r )
    {
        return Calamares::JobResult::error( tr( "Could not select KDE Plasma Look-and-Feel package" ),
                                            tr( "Could not select KDE Plasma Look-and-Feel package" ) );
    }

#ifdef WITH_KCONFIG
    QString targetConfig = system->targetPath( "/home/" + gs->value( "username" ).toString() + "/.config/kdeglobals" );
    KConfigGroup cg( KSharedConfig::openConfig( targetConfig ), "KDE" );
    cg.writeEntry( "LookAndFeelPackage", m_id );
#endif

    return Calamares::JobResult::ok();
}

Works like a champ. Not exactly sure if this fix is required here, or if the issue is with lookandfeeltool. As you pointed out, your code hasn't changed in a long time and I know for a fact it used to work. That suggests that the issue was introduced into lookandfeeltool by the kde/plasma group.

Anyway. For now, this hack is a viable workaround.

Thanks much for the input.

**Comment by adriaandegroot** [comment]
> That was already in there, Adriaan.

I'm clearly not reading closely enough :face_with_head_bandage: In any case, downloading the ISO to try to figure out what's going on -- then I have the same *lookandfeeltool* as you do, rather than my local frankensetup.

.. I have the Plasma folks looking at the problem; it does seem to be something missing in *lookandfeeltool*, but in the meantime I'll pick up your workaround.

**Comment by adriaandegroot** [comment]
See https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/441 for the fix, will arrive with whatever next Plasma is .. and in the meantime Calamares has your workaround code as well (once I merge that branch).

**Comment by adriaandegroot** [comment]
.. and branch *iussue-1573* for the Calamares side of things. Your workaround is a part of it, but I figured while-I-am-here that the module deserves the same treatment as all the other widgets ones: preparation for a QML variety by disentangling the business logic from the Widgets.

**Comment by jghodd** [comment]
Thanks for doing a dive into this, Adriaan. I knew it wasn't your code - it's been solid since you first introduced it (been using calamares since v1.0.4 and using plasmalnf since it was introduced). Your call to lookandfeeltool was spot on and always worked as expected. That was why I hadn't bothered to test it for a while. I don't know exactly when lookandfeeltool stopped working, but by process of elimination, it had to be the problem. Happy to hear it'll be resolved. Also, happy to be of some help.

Cheers, bud.
