### ISSUE TITLE
Packages don't get installed/removed in version 3.2.34

### ISSUE THREAD

**Issue by pcrepix** [calamares/calamares#1576]
Hi,
In version 3.2.34 the packages module won't install or remove installed packages any longer. At least not when using apt on a Debian Testing based OS. Since the module itself doesn't seem to have changed, it must be a problem somewhere else. I can't see any error messages, the system says installing packages, it lust doesn't do anything.

Thanks for any help,
Cheers,
rindi

**Comment by adriaandegroot** [comment]
This doesn't give me a lot to go on:
 - what was a previously working version of Calamares?
 - what distro / ISO?
 - which configuration files? (This is obvious from the ISO, though)
 - what's in the log file `session.log`? (This can be re-created with the ISO at hand, by doing an install)

**Comment by pcrepix** [comment]
I'm so sorry. It wasn't a Calamares problem but rather a file permission problem which had blocked a pre-calamares script from overwriting the packages.conf file properly. Some process had changed the file's permission which I didn't notice.

Thanks for the reply anyway, cheers.
