### ISSUE TITLE
Netinstall module : package will be installed even after unselecting it after selecting it at first

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1577]
We have many netinstall modules to install applications.

We noticed in a tutorial that if you select a package and then lateron decide to unselect it again, it will get installed anyway.
We assume the list of packages is not updated when you unselect a package.

Could you look into that?

https://www.youtube.com/watch?v=RpWdiSIudvI

Version calamares 3.2.32.1.
https://youtu.be/RpWdiSIudvI?t=270

Here we select the i3 desktop.
https://youtu.be/RpWdiSIudvI?t=373

Here we deselect the i3 desktop.
https://youtu.be/RpWdiSIudvI?t=601

Here you see i3 was installed although we did not select it.
https://youtu.be/RpWdiSIudvI?t=882

**Comment by adriaandegroot** [comment]
This *sounds* like the problem that was solved in 0cb6c89876f88e17a364df38264df9371c3c320a (just after 3.2.32.1), where the fancy netinstall setup -- which is heavily used by ArcoLinux -- **un**selected packages.

Ok, now I write that down it doesn't sound like it at all :(

**Comment by adriaandegroot** [comment]
I can confirm the problem exists using the *arco-calamares-config* configuration files, for instance in the *Office* group. It's instructive to use `-d` command-line option so you can watch the global storage:

 - select *Onlyoffice* and click next: there's a package operation to *try_install* of that one package.
 - go back, select *Moneydance* as well and click next: there's now two items in the *try_install*.
 - go back, unselect *Onlyoffice*, click next: just one item left in global storage.
 - go back, unselect *Moneydance* as well, click next: the GS is unchanged :bug:

**Comment by arcolinuxz** [comment]
I can confirm that selecting all packages in the netinstall and then deselecting them, none of the packages will get installed.

Solved.
Test on ArcoLinuxD Spectrwm

![test](https://user-images.githubusercontent.com/36679406/99955827-46ffc680-2d85-11eb-8860-ebe105209dbf.png)
