### ISSUE TITLE
Feature request : netinstall online packages list fallback

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1579]
Netinstall has two basic deployment schemes 

1. static package lists
2. online package lists

What if we gave both options?

The idea is to use the static file if the online fails.

If online url is not working (calamares is offline), use the static file.
If online url is not working (github for example is offline), use the static file.

Create a fallback option **true** to enable the static file if the online url is failing?

**Comment by abucodonosor** [comment]
Why?

It is not about the packages lists but your ISO, right?

If you have an ISO build as 'install from the internet' how would a fall back help you?

**Comment by arcolinuxz** [comment]
I have discussed this with @adriaandegroot.

Maybe he can explain better. 

First off I am not using online netinstall configs. EndeavourOs is.
When they used the online url option, it failed. Github was failing or was just slow.
Hence it made sense to have a fallback on the iso if this happens.

**Comment by kkofler** [comment]
If you cannot retrieve the package list from the Internet, from where would the actual packages come?

**Comment by killajoe** [comment]
The issue seems to affect only getting files directly from GitHub and only in some cases, could be related to Firewall restrictions or similar.
Packages do not come from GitHub and generating a mirrorlist for used Archlinux Mirrors + we do have some mirrors outside Github for Distro specific packages, taking care to fetch packages. 
So if calamares would be able to use the local list as fallback installations will proceed also if they do not get the list from GitHub (or similar) We do use list online because we can do changes on them without the need to build a new ISO.

**Comment by abucodonosor** [comment]
"We do use list online because we can do changes on them without the need to build a new ISO."

So if calamares uses the fallback from the ISO your lists are different anyway, I still don't get the point of that.

**Comment by killajoe** [comment]
> So if calamares uses the fallback from the ISO your lists are different anyway, I still don't get the point of that.
If it fails to get netinstall.yaml from the net it will show an empty packages slide, and install will fail, as in case of EndeavourOS we do not use squashfs image to install system in online mode all DE's packages come from the netinstall.yaml file.

**Comment by abucodonosor** [comment]
Again you reason being:

We use an online file to offer the packages(groups) because we don't want to redo the ISO, so we can changes as we wish.

With this option, your OLD ISO with an OLD yaml fallback file, won't match what you really want to install, right? 
Which means, the part may get the online file will see a different set of packages that the one is using hell knows how old fallback.

**Comment by killajoe** [comment]
> With this option, your OLD ISO with an OLD yaml fallback file, won't match what you really want to install, right?
Which means, the part may get the online file will see a different set of packages that the one is using hell knows how old fallback.

You are completely right, it would be only a workaround to an issue we still do not track down, my first idea was simple to fetch netinstall.yaml from another place, as it is most likely an issue with GitHub and not calamares. 
There are a lot of "if" inside the fallback to local file solution, a sit will do workaround if the user can not fetch the file from GitHub, it will then get a not up to date list if there is a change on the list, and if GitHub fails at all install will be screwed if the user installs p.e. i3 what will git clone and placing configurations from GitHub...

**Comment by killajoe** [comment]
>  using hell knows how old fallback.

oldest could be 3 months, as we do release every 3 month ;)

**Comment by killajoe** [comment]
So i do try to find out how calamares is fetching the list... and i do not see this (or i do not c this?) 
Can someone hint me it is most likely defined somehow generic

**Comment by adriaandegroot** [comment]
The code doing the loading is in `src/modules/netinstall/Config.cpp`, function `loadGroupList()` which takes either a URL (for loading from a URL, whee) or variant data (for loading straight from the `netinstall.conf` file).  This gets called from `src/modules/netinstall/NetInstallViewStep.cpp`.

One approach might be to add a *fallbackUrl* key to the config, so that if loading of the groups data from the one URL fails, the fallback is tried (or, heck, the URL could be a list of them instead of a single one). Because the list is loaded asynchronously via the Config object it may be a bit tricky to detect when something has been completely tried and when to start trying the next URL).

**Comment by adriaandegroot** [comment]
But I'm also with @abucodonosor here: what difference is there going to be between the contents of the regular and the fallback URL? Are your package lists so fragile or changeable that, say, *bash* in the package list would change from one week to the next (and I mean the name of the package, not the version of bash that gets installed).

**Comment by arcolinuxz** [comment]
I think I have a good example today on our ArcoLinux project.

Distrotube mentioned that gimp and inkscape are not in the netmodule graphics of calamares.
And he is right. We forgot it.
Check the url.
https://github.com/arcolinux/arcod-calamares-config-next/blob/master/calamares/modules/netinstall-graphics.yaml

If users will install ArcoLinux with version 20.11.9 they will get a fixed file from the iso till the next release - that is mid January.
No gimp or inkscape for them.

What if I can use an url and update this particular file to include gimp and inkscape.
The iso 20.11.9 will look at the url will find my update and will use that. 
We are fixing calamares on the fly and the user can install gimp and inkscape but a fall-back should be in place - what if there is no internet - it should take the one without gimp and inkscape and not crash.

I hope I am making clear that there is an advantage to be gained here.

**Comment by killajoe** [comment]
> But I'm also with @abucodonosor here: what difference is there going to be between the contents of the regular and the fallback URL? Are your package lists so fragile or changeable that, say, bash in the package list would change from one week to the next (and I mean the name of the package, not the version of bash that gets installed).

Package names will not change that often almost never, and also the list will normally not change as in our case it mainly holds the main packages for a DE to be installed they do not change that often mostly only on a release upgrade what do not happen in between our release cycle mostly (3 months) and it would be only a fallback option for some cases when fetching the file fails.

**Comment by killajoe** [comment]
> loadGroupList()

and what is in use to fetch the file? curl wget or something else?

**Comment by abucodonosor** [comment]
"Calamares should then take the one without gimp and inkscape and not crash."

I have to disagree. Ofc calamares crashing is a bug, but instead of crashing it should just say:

"Fetching the online package list failed ( put_error_here ), try again later"

That is.

**Comment by erikdubois** [comment]
Like I said prior - ArcoLinux never used the url option. So I do not know what happens if the url fetch fails. @abucodonosor 

During discussions on Telegram we had the idea to provide a fallback option IF the url fetch fails.

The  post is created by me on demand of @adriaandegroot  for @killajoe.

The idea sounds good and would help my issue I have today.
https://github.com/calamares/calamares/issues/1579#issuecomment-730676672

**Comment by arcolinuxz** [comment]
Today I had another possibilty to use this feature.

I needed to add htop and remove riot-desktop.
If the files come from github then the users would have it now if they install it.

**Comment by abucodonosor** [comment]
That's fine but this is, in reality, your distribution problem.

And to be clear, you can do that right now with 3 bash functions by using ping, wget & a wrapper to start calamares.

IOW, you always have the list on the ISO, with the start wrapper you ping the online host, if OK, you use wget --spider to check the file exists, if so, wget and replace the on ISO one if not you use whatever you have on your ISO. Really very simple.

**Comment by adriaandegroot** [comment]
Let's retreat alll the way back to the initial request:

- lots of online resources have mirrors
- if you try one mirror and it is not available **for whatever reason** you try another
- can Calamares do that with the package lists for netinstall

That would mean making *groupsUrl* a list (interpreting the current setting of a single string as a list with one entry), and then trying the URLs in that list one-by-one until they all fail, or one succeeds.

**Comment by kkofler** [comment]
IMHO, the request makes sense, the presented use case does not.

It is a valid request to silently fall back to a mirror, if the mirror can be expected to be reasonably in sync with the primary server.

It makes a lot less sense to silently fall back to a local file that can be very out of date. This sort of fallback warrants at least a warning of some kind. You should also look into finding a more reliable primary location, or at least a more reliable online mirror that Calamares can try before falling back to a local file.

**Comment by killajoe** [comment]
I do see this the same way, fallback URL over the net would be a nice addition but fallback to a local file is not solving the issue in a complete matter, in its core, it is an issue with using GitHub as a source for these files, and using another synced fileserver to get the files is a better solution, but only have one source for the files can bring the same issue as we have for Asian and US users having an issue accessing European servers they do timeout a lot of times... 
So the possibility to have fallback URLs would be a good solution. 
We do already work on something checking access to GitHub and then parsing the settings.conf with a fallback URL what will be a workaround solution.

**Comment by arcolinuxz** [comment]
And what if a user does not have a working internet solution - drivers and kernels - do not get me started - a local file on the iso is the last fallback.

Having a second url fallback sounds great for me too.

**Comment by killajoe** [comment]
> And what if a user does not have a working internet solution

we do have optional online and offline installs ;)
