### ISSUE TITLE
Calamares failed to start with newer updates of Python3 and boost

### ISSUE THREAD

**Issue by dev-andi** [calamares/calamares#1587]
Hi All,

Hope you guys are doing well.  

This is a new issue that I am facing while testing Calamares release 3.2.32 and 3.2.35 ( git version from AUR ).  

Python version was 3.8.6-1 but then it was upgraded to Python3.9.0-1 recently. 
Boost-lib version was 1.72.0-2 and now has been upgraded to version 1.72.0-4

I had to downgrade to previous versions for it to start again. I am trying to implement Calamares on a new upcoming distro. Please check the attached file for the entire process that has taken place.

**Error received** :  calamares: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

This is in Arch, so there's no way to use update-alternatives - as we do in Debian distros.  Right now I am using hard-coded script to use the previous versions of the two dependencies that I mentioned above.  Any help would be much appreciated. Thankyou.

[log.txt](https://github.com/calamares/calamares/files/5640667/log.txt)

**Comment by philmmanjaro** [comment]
Did your recompile it against the new Python 3.9.

**Comment by abucodonosor** [comment]
@dev-andi 

This is a distribution problem, by updating to python 3.9 everything needs to be recompiled against it.

**Comment by adriaandegroot** [comment]
@dev-andi your Calamares links with a **versioned** Python library. You can see that from the error message, which comes from the linker: it is trying to load Python 3.8 libraries, which have gone away. Python does not provide unversioned libraries or ABI stability-guarantees between versions (which you need to provide unversioned libraries).

There's nothing that can be done at the Calamares level about this: if you build Calamares against Python (the same applies to Boost, which is similarly versioned) then you need to provide the libraries of the version you built it against. If you have packages then you'll need to rebuild them (or get your upstream to rebuild them).

**Comment by erikdubois** [comment]
Rebuilding against new python version - all is well in Calamares land

**Comment by DN-debug** [comment]
Hey Guys, I haven't got time today to check it.  I do think there are some residuals still remaining coz its not only calamares, one more library is messed up for me. And I think I know where to look, gonna. Pretty confident now that its not calamares. Thank you for quick response ( and apologies for my late response ).  😅

**Comment by dev-andi** [comment]
Phil, rebuilding didnt work coz as I said the library is all messed up. Its not calamares that I know now.  I haven't got time to look into it today. Started a while back and I think I know where to look. Its not only calamares that's messed up, one more library that's python dependent is also not working.  You are right about it Adrian/Erik. 

Thanks Guys for immediate help, and apologies for late response 😅

**Comment by kkofler** [comment]
I guess Boost::Python is the other library that you need to rebuild. (It is the only Python-using library that Calamares normally links to, unless you still use the deprecated PythonQt?)

**Comment by philmmanjaro** [comment]
All packages need to be rebuilt against python. That is why **Manjaro** is snapshoting the repos rather than depending on them directly. On our end the rebuilds are still pending in **unstable** branch. **python-qt** is not used, at least on our end.

**Comment by dev-andi** [comment]
@philmmanjaro  its fixed . 
@kkofler all of the packages were upgraded that's when the issue started. But definitely something broke due to the other tests that I was doing with Flatpak-builder.

So I went ahead and fixed the python env ( you guys made it obvious for me since I had my doubts ). Now I don't wanna ruin my joyous Friday night pondering over it.  I think I can finally go get some drinks 🏃🏼 😄 . 

Thanks to everyone in this thread for the help. This time apologies for my stupidity. Cheers.
