### ISSUE TITLE
Links on welcome page of installer pointing to wrong pages

### ISSUE THREAD

**Issue by deprov447** [calamares/calamares#1588]
**Describe the bug**
The links "Generic Support" and "Known Issues" on the first page of installer are pointing to wrong pages.

**To Reproduce**
1. Open Calamares
2. Click on 'Generic support' or "Known Issues"
3. See the links that open up in browser

**Expected behavior**
"Generic support" should point to [Calamares Wiki](https://github.com/calamares/calamares/wiki) and "Known Issues" to [issue page](https://github.com/calamares/calamares/issues) on Github.

**Comment by adriaandegroot** [comment]
Fixed by merge
