### ISSUE TITLE
Crypto setup on Manjaro results in bogus Plymouth prompt that accepts an empty passphrase (IRC report)

### ISSUE THREAD

**Issue by kkofler** [calamares/calamares#1592]
This was reported on IRC by `ester7879[m]` (= @MamasLT on GitHub), who uses Manjaro:

> I just found out that to bypass the second password promt after unlockd ar GRUB, i don't even need to enter anything. Just press Enter and it boots OS 😀 Someone was asking you about this before...

So, the generated initramfs brings up a Plymouth prompt that is not actually needed because an empty passphrase allows it to proceed, presumably because the partition can be unlocked with the keyfile Calamares sets up.

Maybe this is a side effect of the recent Calamares change to enable graphical password prompts in Plymouth on Arch-based distros (distros using `mkinitcpio`), i.e., commit 3bf57c7785a5efd6c43d50b97212c6a995598953?

**Comment by philmmanjaro** [comment]
This needs a revisit as on non-encryption we don't have **plymouth** hook anymore: https://github.com/calamares/calamares/commit/3bf57c7785a5efd6c43d50b97212c6a995598953. Proper way would be adding a variable called **plymouth_hook** and give it **plymouth** by default and change it to **plymouth-encrypt** as needed. Now we only add **plymouth-encrypt**. Since CAL does adding a keyfile this is not needed anyway, at least wen doing auto-partitioning ...

**Comment by philmmanjaro** [comment]
From the Arch-Wiki: `If you use hard drive encryption with the encrypt hook, you must replace the encrypt hook with plymouth-encrypt and add it after the plymouth hook in order to get to the TTY password prompts.` Seems the **plymouth** hook is needed after all.

**Comment by philmmanjaro** [comment]
Sorry for the noise. Seems it was already fixed by this: https://github.com/calamares/calamares/commit/84558333bfe1e94e40a7964cf4a7ac50a2112f4e. Which might leave us just with the fact this issue might occur in auto-partitioning ...

**Comment by Chrysostomus** [comment]
I suspect that Plymouth-encrypt hook gets set even if keyfile is in use. I'll look into this.

**Comment by kkofler** [comment]
Of course, it would be helpful if the startup scripts generated by `mkinitcpio` would only bring up a passphrase prompt when one is actually needed. As far as I can tell, other initramfs generators manage to do the right thing automatically, without having to manually enable or disable a `plymouth-encrypt` module. But Calamares has to work with what is there.

**Comment by Chrysostomus** [comment]
Yeah, I had kinda assumed it would do the right thing, so I didn't take this into account. Also, for some reason this bug didn't come up when I tested the normal manual installation with encryption.

**Comment by philmmanjaro** [comment]
I assume it is the automatic install which creates that issue. As that is full-encrypted anyway. @Chrysostomus. So we have to check if it gets installed in that mode and skip to set the hook. However we have to check if the normal `encrypt` hook would be needed then.

**Comment by Chrysostomus** [comment]
It is needed with keyfile, yes.

**Comment by MamasLT** [comment]
> I assume it is the automatic install which creates that issue. As that is full-encrypted anyway. @Chrysostomus. So we have to check if it gets installed in that mode and skip to set the hook. However we have to check if the normal `encrypt` hook would be needed then.

Hi. Just to clarify, the install was manual, 4 partition install: /boot/efi, /boot (encrypted), / (encrypted), /home (encrypted).

**Comment by kkofler** [comment]
Your separate `/boot` is encrypted, so your setup should also be covered by this fix, which will be included in the next release of Calamares.
