### ISSUE TITLE
Cannot find libboost_python39.so.1.74.0 after libboost update to 1.75.0 in Arch

### ISSUE THREAD

**Issue by ezsit55** [calamares/calamares#1599]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
Calamares 3.2.35.1 compiled on Friday, Dec 9, will not run when included in an Arch Linux build because Calamares is looking for libboost_python39.so.1.74.0 and libboost_python39 has been updated to 1.75.0. I am currently recompiling Calamares with the new libboost_python39.so.1.75.0. 

**To Reproduce**
Build Arch Linux with archiso and include all the dependencies for Calamares. Include a build of Calamares compiled with an older version of libboost_python39 and it failed to load.

**Expected behavior**
It would be great of Calamares was not tied to the exact version of libboost_python39 when compiled, but specified more generally a minimum version of the library so recompilation was not necessary for each small bump in library version numbers.

**Comment by kkofler** [comment]
As the text you quoted states:

> If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first.

This is clearly a distribution issue: Arch needs to recompile its Calamares package against the new Boost.

**Comment by kkofler** [comment]
> It would be great of Calamares was not tied to the exact version of libboost_python39 when compiled

Sorry, that is not something Calamares can do. It is a decision of Boost::Python, and Boost in general, to not support a stable ABI, but to require recompiling any and all applications and libraries linking to Boost against each and every new version.

**Comment by ezsit55** [comment]
Ok, thank you.

**Comment by D3vil0per** [comment]
@kkofler @ezsit55 I agree. I got the same error now that libboost_python310.so.1.78.0 has been updated to libboost_python310.so.1.79.0. And I guess for each future update of libboost_python we will get this kind of issue.

**Comment by demmm** [comment]
>only solution is to retrieve

No, only correct solution is to rebuild your packages when you are on a rolling distribution. Thus in this case, rebuild Calamares.

**Comment by D3vil0per** [comment]
> > only solution is to retrieve
> 
> No, only correct solution is to rebuild your packages when you are on a rolling distribution. Thus in this case, rebuild Calamares.

So you mean, in our specified case, we must only rebuild Calamares and specifying somewhere that it must refer to latest libboost_python version?

**Comment by ezsit55** [comment]
> So you mean, in our specified case, we must only rebuild Calamares and specifying somewhere that it must refer to latest libboost_python version?

Calamares needs to be rebuilt when something like boost updates. I just got in the habit of recompiling Calamares before I release a new ISO. As long as your packages are up to date, simply recompiling Calamares will get it rebuilt against the newer libraries.

**Comment by D3vil0per** [comment]
> > So you mean, in our specified case, we must only rebuild Calamares and specifying somewhere that it must refer to latest libboost_python version?
> 
> Calamares needs to be rebuilt when something like boost updates. I just got in the habit of recompiling Calamares before I release a new ISO. As long as your packages are up to date, simply recompiling Calamares will get it rebuilt against the newer libraries.

So, in practice, when an update of a dependency like libboost is updated, my purpose is summarized like:
```
$ sudo pacman -S qt5-tools yaml-cpp kf5
$ git clone https://github.com/calamares/calamares
$ cd calamares
$ mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DWITH_PYTHONQT=ON -DAppStreamQt_DIR=... ..
$ make
$ sudo make install
```
is it correct or is there an additional step?

**Comment by ezsit55** [comment]
> So, in practice, when an update of a dependency like libboost is updated, my purpose is summarized like:
> 
> ```
> $ sudo pacman -S qt5-tools yaml-cpp kf5
> $ git clone https://github.com/calamares/calamares
> $ cd calamares
> $ mkdir build && cd build
> $ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DWITH_PYTHONQT=ON -DAppStreamQt_DIR=... ..
> $ make
> $ sudo make install
> ```
> 
> is it correct or is there an additional step?

If that is your process for building Calamares, then yes. I assume you have built Calamares before? Just repeat the steps that work for you.
