### ISSUE TITLE
Unable to choose bootloader during installation

### ISSUE THREAD

**Issue by kq01526** [calamares/calamares#1606]
Hi,

https://github.com/calamares/calamares/blob/calamares/src/modules/bootloader/bootloader.conf seems to suggest that it would be possible to choose the bootloader with Calamares.

However, there doesn't seem to be any option in the installer GUI offering a choice on which bootloader to use. It always seems to use GRUB with no way to change it to systemd-boot for example.

Is this intentional?

Regards

**Comment by kkofler** [comment]
The choice of bootloader is a distribution packager choice, not an end user choice. Distribution ISO images normally include only one bootloader (or two: one for BIOS and one for UEFI), more would be redundant and pointlessly include the ISO size. Therefore, it would not make sense to offer this choice to the end user in the Calamares GUI. The setting can only be modified in the configuration file.

**Comment by kq01526** [comment]
@kkofler 

> Distribution ISO images normally include only one bootloader (or two: one for BIOS and one for UEFI), more would be redundant **and pointlessly increase the ISO size**.

Would that also be true for systemd-boot, which is part of systemd/included in systemd anyway?

>Therefore, it would not make sense to offer this choice to the end user in the Calamares GUI

The Cnchi installer that came with Antergos offered the choice between GRUB and systemd-boot in the GUI and it was working just fine and was much appreciated. So if Calamares would offer the same, that would be good.

That being said:

> The choice of bootloader is a distribution packager choice, not an end user choice [...] The setting can only be modified in the configuration file.

A quick Internet search comes up with a comment from @killajoe in https://forum.endeavouros.com/t/how-to-completely-remove-grub/6648/7 on the EndeavourOS forum which seems to suggest that the Calamares systemd-boot config does not work on Arch based distros.

Is it expected to not work?

**Comment by abucodonosor** [comment]
@kq01526 

Then use that Cnchi thing.

> Is it expected to not work?

Does that distros support sysemd-boot ? Including in the ISO's, initramfs, etc ?

**Comment by abucodonosor** [comment]
@kq01526 

A quick note to your 'quick internet searches', I suggest you spend more time 'searching' and reading.

Thx.

**Comment by kkofler** [comment]
Actually, at least Fedora indeed installs `bootctl` by default, which is kinda surprising considering that Anaconda does not support it and that the files required to install GRUB directly (with `grub2-install`) on UEFI are deliberately omitted by default because one is expected to use `shim`. The `systemd` package is split into subpackages, but `bootctl` is in the `systemd-udev` subpackage and not in a separate one.

**Comment by kq01526** [comment]
> @abucodonosor asked:
> 
> Does that distros support sysemd-boot ?

Maybe you should have done a quick Internet search, then you probably would have come across the post from @killajoe on https://forum.endeavouros.com/t/add-option-for-systemd-boot-to-the-future-installer/2041/7 which says that the distro is waiting for it to be implemented in Calamares :blush: ?

Regards

**Comment by kq01526** [comment]
> @kkofler wrote:
> 
> which is kinda surprising

Does that mean the systemd-boot choice in the Calamares GUI installer is on the horizon now?

Regards

**Comment by kq01526** [comment]
PS:

> @abucodonosor commented:
> 
> Then use that Cnchi thing.

Perhaps you should have done a quick Internet search, then you probably would have realized that the Antergos distro and it's installer Cnchi are no longer being actively developed :blush: ?

https://en.wikipedia.org/wiki/Antergos#History_and_development

Regards

**Comment by demmm** [comment]
The use of systemd-boot for UEFI installs was implemented in Calamares in 2014, and has worked very well ever since.  AFAIK, only one distribution has chosen to use the systemd-boot option so far.  Just an FYI, no comment on making this a user (GUI) option, right now it is the choice of the distribution not to use systemd-boot.

**Comment by abucodonosor** [comment]
> > @abucodonosor asked:
> > Does that distros support sysemd-boot ?
> 
> Perhaps you should have done a quick Internet search, then you probably would have come across the post from @killajoe on https://forum.endeavouros.com/t/add-option-for-systemd-boot-to-the-future-installer/2041/7 which says that the distro is waiting for it to be implemented in Calamares  ?

Perhaps you should just STFU?

**Comment by kkofler** [comment]
> Does that mean the systemd-boot choice in the Calamares GUI installer is on the horizon now?

Well, as the Fedora packager for Calamares, I am not really interested in supporting anything other than the supported setup on Fedora, i.e. the "Secure Boot" `shim` indirectly loading GRUB 2, even if the required `bootctl` tool happens to be installed for some reason.

But we can reopen the bug if @adriaandegroot is interested in adding a GUI option for this.
