### ISSUE TITLE
Wrong flag when manual partition make system unbootable.

### ISSUE THREAD

**Issue by rago666** [calamares/calamares#1607]
In latest manjaro, while manual partitioning. Making the efi partition like {512mb,fat32,flags=boot,mount=/boot/efi} .
But It actually set fat32 partition flag to Legacy. Thus firmware shows no  bootable device found.

**Comment by abucodonosor** [comment]
This is not a bug, "Manual partitioning' means I know what I am doing. 

PEBCAK cannot be solved by calamares.

**Comment by rago666** [comment]
Sorry, if I didn't make sense. I will go again
If you make a fat32 efi partition with boot flag and boot/efi as mount point, the system should be bootable, Right? 
but in that case calamares set the flag of efi to legacy, Not esp or boot. 
It happened on Manjaro  to me. I fixed it by booting to live usb and editing the flags by gparted.
Same thing happend to 2 users in last 24 hours who asked tech support on manjaro reddit.

**Comment by abucodonosor** [comment]
@rago666 

So you are saying you set the right flag in the GUI and you ended up with something else?
If that is the case, open a new bug report with installation logs and an exact description of what you are doing.

However, basically, you should report to Manjaro first, @philmmanjaro will take care usually, if is a calamares bug and report it upstream.

**Comment by killajoe** [comment]
#1724
