### ISSUE TITLE
failed to create compose table

### ISSUE THREAD

**Issue by jcfrosty** [calamares/calamares#1608]
**Describe the bug**
When trying to install everything seems to work smoothly until you go to perform the actual partitioning process and it fails and gives up. viewing the install process with -d shows "failed to create compose table" during the selection of partitioning. I can use another partition tool to create a new partition table, then try the install again and it works fine.

Its possible that this isn't a KPMcore or Calamares issue, but I'm not sure. I could really use some assistance here.

**To Reproduce**
Sabayon/Mocaccino live disc, boot and attempt to install. attempt will fail.

**Expected behavior**
I expect it to create a new partition table and move along just fine.

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Calamares has an installation log (usually `~/.cache/calamares/session.log`), please check it for confidential information and attach it if possible.

[calamares.log](https://github.com/calamares/calamares/files/5758162/calamares.log)
[session.log](https://github.com/calamares/calamares/files/5758176/session.log)

**Comment by adriaandegroot** [comment]
This looks **vaguely** like the ol' "automount problem" where the host system is agressively grabbing partitions as they show up on the system, thus blocking KPMCore (or rather, sfdisk) from doing more disk-editing. You might try to turn that off before doing the installation: see issue #1604 for some details, and https://euroquis.nl/calamares/2020/12/19/plamo.html for my blog with some screenshots of where to look *if* you happen to be running KDE Plasma.

**Comment by jcfrosty** [comment]
I've have zero automounted. In fact I have a blank VDA that has a fresh GPT table added to it with no partitions. it attemps to create fat32 partition for EFI and fails shortly after. I'll try updating Calamares to see if that fixes the issue, if not. I'll return with more data.

**Comment by jcfrosty** [comment]
The issue is KPM Core is too old and its attempting to enter an empty FAT32 label.  Empty FAT labels are no longer allowed. Labels can be cleared or created, but they cannot be entered as empty. going from 20.12.0 to 12.12.3 fixes this issue.

**Comment by adriaandegroot** [comment]
Yes, that was dosfstools changing the rules (which affects KPMCore, and calamares .. I think there's a workaround at the Calamares level, although I don't remember where)
