### ISSUE TITLE
Calamares 3.2.35.1 manual partitioning : "keep" option doesn't seem to work.

### ISSUE THREAD

**Issue by V3n3RiX** [calamares/calamares#1611]
Distro : Redcore Linux 2101 KDE ALPHA, 64bit, UEFI setup.

Selected partition layout : 
/ -> **format**
/boot/efi -> **format**
/home -> **keep**

/home was formatted regardless of **keep** option, data lost.
1. Go to 'Manual partitioning'
2. Select any partition and click on 'keep', choose a mountpoint.
3. Despite **keep** option being selected, partition summary will tell you that the partition **WILL** be formatted. Since I have backups in place, I ignored the warning on purpose, to check if it's a typo or if it will actually format the partition.
4. Watch calamares format that partition destroying all the data.

Expected behavior:
Do NOT format that partition, only add a fstab entry to mount it as is.

The ISO image is available at : http://mirrors.redcorelinux.org/redcorelinux/iso-next/Redcore.Linux.Hardened.2101.KDE.amd64.ALPHA.iso if you wanna play, could be something on our end. 

Live login details : user redcore, password redcore_live

Any other distro shipping with the latest calamares? Post a link even if is a testing ISO as ours, and I'll try to reproduce the issue. Could be widespread and affect everybody.

**Comment by demmm** [comment]
Yes, test ISO has all the latest commits:
https://sourceforge.net/projects/kaos-test/files/iso/KaOS-2021.01.01-x86_64.iso

**Comment by V3n3RiX** [comment]
Sorry but I forgot to update you guys on this one. Something along the way fixed it. I can no longer reproduce it. Closing now!
