### ISSUE TITLE
in situ Calamares update

### ISSUE THREAD

**Issue by wxl** [calamares/calamares#1612]
From the perspective of the Ubuntu ecosystem, which is not a rolling release, it is sometimes the case that we need to make so-called Stable Release Updates to already released versions. This is a bit of a bureaucratic process, so sometimes the effort of doing it is weighed against the impact on the user (at least for our small team). In the case of the installer, the answer is almost always a resounding no because it would involve respinning the ISO which is not something the Ubuntu Release Team will typically allow.

With that context, I had the idea of a module that would be similar to the `packages` module that would exist for the sole purpose of updating Calamares and its configuration files. It would need to be the first module run, obviously. The unique aspect of this module is that it would have logic to restart Calamares (and thus reloading the settings) and it would be updating packages on the running system rather than the the system being installed.

Obviously, too, it would require an Internet connection, so this is not a perfect solution, but it at least offers an option not otherwise available.

This is a pretty high level way of looking at this and I may be missing some low level details that would make this impractical, but it certainly makes sense to me from that perspective :smile:

**Comment by abucodonosor** [comment]
Why would you need a calamares module for that?

Start calamares with a wrapper and use apt to update/check for updates before starting?

**Comment by kkofler** [comment]
For the record, how Fedora handles the same issue is that the Anaconda team will update Anaconda, but no official ISOs will be spun with the updated Anaconda. (None of the official ISOs ship with Calamares, they all use Anaconda.) Instead, the unofficial Live Respins that get spun by the community will pick up the updated Anaconda along with all the other updated packages.

**Comment by wxl** [comment]
@abucodonosor I think your idea is totally workable. Just inelegant, especially as it relates to packaging.

**Comment by adriaandegroot** [comment]
I'm closing this as "aged out". It's an interesting idea, and a PR for it -- which will probably also involve figuring out exec-before-show problems -- would be welcome. THis issue, though, has languished enough.
