### ISSUE TITLE
Auto-partitionining with encryption results in slow boot times

### ISSUE THREAD

**Issue by kq01526** [calamares/calamares#1615]
Hi,

When installing with auto-partitioning and encryption, the boot is quite slow, see loader times:

```
$ systemd-analyze
Startup finished in 6.358s (firmware) + 19.937s (loader) + 6.591s (kernel) + 1.589s (userspace) = 34.476s 
graphical.target reached after 1.059s in userspace
```
Is this possibly because Calamares does not use LVM with LUKS and just uses plain LUKS?

This also seems to be causing the prompt for the encryption passphrase to appear before reaching the GRUB menu.

With other installers which use LVM with LUKS, the prompt for the passphrase appears after the GRUB menu and the boot is much faster.

Regards

**Comment by kkofler** [comment]
> This also seems to be causing the prompt for the encryption passphrase to appear before reaching the GRUB menu.
>
> With other installers which use LVM with LUKS, the prompt for the passphrase appears after the GRUB menu and the boot is much faster.

That is not a result of not using LVM, but of encrypting all partitions including `/boot`.

**Comment by abucodonosor** [comment]
This is not slow. This is bc you need to type in your password which systems will count as time.

>With other installers which use LVM with LUKS, the prompt for the passphrase appears after the GRUB menu and the boot is much faster.

Nothing about LUKS but full encryption. That said, either you wish 'security' or fast booting ( which is irrelevant if you want security ).

**Comment by abucodonosor** [comment]
Not a bug..,

**Comment by kq01526** [comment]
Hi,

> @ abucodonosor commented:
> 
> That is not a result of not using LVM, but of encrypting all partitions including `/boot`.

Okay, thanks. So by default Calamares is using LUKSv1 instead of LUKSv2 so that FDE (Full Disk Encryption) can be utilized with GRUB being able to decrypt `/boot`?

That would actually be nice and be a good default.

> @ abucodonosor commented:
> 
> Nothing about LUKS but full encryption. 

As per https://forum.manjaro.org/t/make-more-sensible-choice-for-luks-full-disk-encryption-parameters-during-install/15528 it's apparently due to GRUB not being able to use the full CPU performance when having to decrypt `/boot` at this early stage during bootup, so that would explain it.

Regards
