### ISSUE TITLE
travis-ci.org is shutting down

### ISSUE THREAD

**Issue by ollieparanoid** [calamares/calamares#1616]
I've noticed that calamares CI is using travis-ci.org, which is [shutting down](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom).

(When moving to something new, how about adding CI to [calamares-extensions](https://github.com/calamares/calamares-extensions) too?)

**Comment by demmm** [comment]
In case useful:
https://blog.earthly.dev/migrating-from-travis/

**Comment by adriaandegroot** [comment]
This is, unfortunately, one of those things that chews up a huge amount of time with very little net benefit :disappointed:

**Comment by kkofler** [comment]
That's what you (or whoever at Blue Systems makes those infrastructure decisions) get from relying on commercial, hosted, proprietary web services.

**Comment by demmm** [comment]
Looks like ci is moved:
https://github.com/calamares/calamares/commit/d267d4ab7b3ce188668ccd649f3de17104dc2c30
Closing or keep open until calamares-extensions are included too?

**Comment by adriaandegroot** [comment]
Keep open until -extensions is ok *and* we've seen that this other CI actually works :/

**Comment by Conan-Kudo** [comment]
> That's what you (or whoever at Blue Systems makes those infrastructure decisions) get from relying on commercial, hosted, proprietary web services.

The commercial and hosted bit makes sense, but [Travis CI is actually open source](https://github.com/travis-ci). It's just almost impossible for anyone else to deploy without a ton of legwork.
