### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by wsalmeida** [calamares/calamares#1618]
Translation error
Hello, I noticed a translation error in the installer
![2021-01-22_11-19](https://user-images.githubusercontent.com/38542279/105504145-2d57fe00-5ca6-11eb-9787-96ba1bbcc69d.png)

**Comment by adriaandegroot** [comment]
Since I don't speak (Brasilian) Portuguese, it would help if you told me *what* the error is. Although, I can check some translation history: it was changed to "para manter" in august 2020 before Calamares 3.2.30, so I think this ISO just has an old Calamares version.
