### ISSUE TITLE
opt into partial encryption

### ISSUE THREAD

**Issue by hsitter** [calamares/calamares#1625]
**Describe the bug**
Currently the new partial encryption doesn't work on neon. It shouldn't really be on by default

**To Reproduce**
1. install neon with /boot not encrypted
2. doesn't boot

**Expected behavior**
Distros should have to opt into the feature once it is known to actually work.

**Comment by adriaandegroot** [comment]
You're going to have to give more of a hint what you're doing:
- which neon
- how do you install neon with /boot not encrypted (steps in the installer, in the partitioning pages in particular)

I tried various neon releases (developer-20210111, user 20200821, user 20210506) and *erase* offers one single checkbox / password for encryption, and via manual partitioning I don't get any option for encryption at all.

**Comment by apachelogger** [comment]
user edition 20210624

steps:

- pick manual partioning
- delete old parts
- crate partition for /boot do not tick encrypt
- create partition for / tick encrypt

![Screenshot_20210706_141936-1](https://user-images.githubusercontent.com/809987/124598831-58559900-de65-11eb-871b-1357327da39b.png)

**Comment by adriaandegroot** [comment]
Manual partitioning, though, means "I know what I am doing", so I don't think there is actually anything to do here. With #1311 and PR #1931 this is somewhat more visible / viable, and there's a new PR to make it **actually** visible in the UI -- which puts it more under user and distro control. Manual partitioning remains the C++ of installation (ie. allows footguns).
