### ISSUE TITLE
crypttab wrong with partial encryption

### ISSUE THREAD

**Issue by hsitter** [calamares/calamares#1626]
**Describe the bug**
The fstab module still writes `/crypto_keyfile.bin` instead of `none` as password. So crypto setup fails on for example neon (probably other debians too).

**To Reproduce**
1. install neon with / encrypted but /boot not
2. reboot
3. no booty

**Expected behavior**
booty

**Additional context**
Upon inspection /etc/crypttab contains the incorrect password value. With partial encryption we want to query the password on-demand during bootup so the value ought be `none`. Hacking the password to be none appears to trigger proper decryption detection and bootup to work.

**Comment by apt-ghetto** [comment]
Might be introduced with #1566?
@Chrysostomus

**Comment by abalfoort** [comment]
On Debian 11 (Bullseye) installing with unencrypted /boot partition and manually replacing /crypto_keyfile.bin with none in  /etc/crypttab still unbootable.

Directly after boot:
`cryptsetup failed, bas password or options?
maximum number of tries exceeded`

I would prefer it would be the user's choice whether or not to choose to create an unencrypted /boot partition, but Is it possible to at least prevent users to create an unencrypted /boot partition to prevent having an unbootable system?

**Comment by abalfoort** [comment]
This issue can be closed. Fixed in #1931
