### ISSUE TITLE
Calamares fails to compile in older distributions: error: 'm_runningJobs' was not declared in this scope

### ISSUE THREAD

**Issue by embar-** [calamares/calamares#1631]
In some older distributions, like openSUSE Leap 15.1, almost recent Calamares 3.34 version fails to compile:
`error: 'm_runningJobs' was not declared in this scope` at multiple lines of `src/libcalamares/JobQueue.cpp`
see [openSUSE151_buillog.txt](https://github.com/calamares/calamares/files/5900277/openSUSE151_buillog.txt)

**Comment by embar-** [comment]
I can reproduce with Calamares 3.2.35.1: 
[openSUSE151_32351_buillog.txt](https://github.com/calamares/calamares/files/5900344/openSUSE151_32351_buillog.txt)

**Comment by abucodonosor** [comment]
The real error is bc you are using some very old compiler. Eg:

```
error: 'unique_ptr' in namespace 'std' does not name a template type ...

```

Try adding 

#include <memory>

into JobQueue.cpp, also be sure you compile with -std=c++11.

**Comment by adriaandegroot** [comment]
Er .. Calamares is C++17, it checks and enforces that at CMake-time. Regardless of that, `<memory>` was missing (in the sense of "include what you use and don't rely on implicit includes from elsewhere") from JobQueue, which I've now added. @embar- , thanks for reporting.

Now that we use GitHub Actions for CI, it might be easier in some ways to try builds on other / older platforms as well (I don't have to care about being polite about Travis-CI resources anymore), if you care to try a variation on the existing CI script.
