### ISSUE TITLE
The question of priority of language installer

### ISSUE THREAD

**Issue by AdrianusWest** [calamares/calamares#1634]
What follows is not so much a bug as ignorance of the specifics.

When auto-detecting my location as Belarus, the standard language is Belarusian.

This is not true. In Belarus, Belarusian is spoken by >5% of the population, and it is not a literary language, but a mixture of Russian and Belarusian. The main language in all areas is Russian.

My suggestion for ease of use is to change the standard language for Belarus to Russian, keeping Belarusian as an alternative for its fans, of which there are very few.

This will prevent most of your users from scrolling through a huge list of languages in search of their primary language.

**Comment by adriaandegroot** [comment]
You can see a similar issue in #1284, which was fixed in 0e7982ec371246cc6e189ada32b2787f204479e5 . Calamares follows the Unicode tables for "likely language", which you can find here https://unicode-org.github.io/cldr-staging/charts/38.1/supplemental/territory_language_information.html in HTML form. Wikipedia has https://en.wikipedia.org/wiki/Belarusian_language showing anywhere from 12-85% of Belarusian population using the language (depending on which definition you pick and which census year). The Unicode table says that only 12% of the population uses Russian -- which is why Calamares picks Belarusian instead.

Calamares is flexible, though. I'm just a little unsure of who to believe: you (a real person, and probably the only Belorusian I have ever interacted with), Wikipedia, or Unicode. So I'm going to do a totally unscientific thing and ask around for some more opinions (because I understand language is politics and it can get tricky) and then pick something likely -- which, to be clear, is probably going to be what you suggest.

**Comment by AdrianusWest** [comment]
In the Unicode tables, you need to change the Russian and Belarusian places: 9.9 million speak Belarusian?)))))))))))))) Well, well...)))) It is good if a million people speak Belarusian, and that is debatable.

Wikipedia is generally written by people in random order. Many articles and sections are supported exclusively by minorities. Minorities are overly politicized, as you correctly noted.
I advise you not to take into account the article about the Belarusian language in Wikipedia - it corresponds to reality well, if only half.

Here is my example:
I was born in 1988 in Belarus. Both higher education courses were taught here in Russian. Both schools were Russian-speaking.

Russian Russian, Belarusian (pure, literary, which is familiar only to philologists) and "trasyanka" (a dialect consisting of a wild mixture of Russian-Belarusian words, often laced with obscene language (in rural areas)). The issue of language is indeed politicized, but the Russian language was, is, and remains ubiquitous.

Of course, the radical nationalist community wants to impose Belarusian on the majority, but as a result of the referendum, both languages were retained as state languages.

Just this fact with the language of the installer surprised me and I decided to check with the creators why it turned out this way. It turns out that you relied on unreliable statistics, which is not surprising with such a primary source.

In any case, thank you for your hard work and your answer. I will try to deal with the data you have provided links to, but it seems to me that this will be useless.

**Comment by creio** [comment]
> In the Unicode tables, you need to change the Russian and Belarusian places: 9.9 million speak Belarusian?)))))))))))))) Well, well...)))) It is good if a million people speak Belarusian, and that is debatable.
> 
> Wikipedia is generally written by people in random order. Many articles and sections are supported exclusively by minorities. Minorities are overly politicized, as you correctly noted. I advise you not to take into account the article about the Belarusian language in Wikipedia - it corresponds to reality well, if only half.
> 
> Here is my example: I was born in 1988 in Belarus. Both higher education courses were taught here in Russian. Both schools were Russian-speaking.
> 
> There are three options: Russian, Belarusian (pure, literary, which is familiar only to philologists) and "trasyanka" (a dialect consisting of a wild mixture of Russian-Belarusian words, often laced with obscene language (in rural areas)). The issue of language is indeed politicized, but the Russian language was, is, and remains ubiquitous.
> 
> Of course, the radical nationalist community wants to impose Belarusian on the majority, but as a result of the referendum, both languages were retained as state languages.
> 
> Just this fact with the language of the installer surprised me and I decided to check with the creators why it turned out this way. It turns out that you relied on unreliable statistics, which is not surprising with such a primary source.
> 
> In any case, thank you for your hard work and your answer. I will try to deal with the data you have provided links to, but it seems to me that this will be useless.

Привет, севершенно верно, большинство в Беларуси говорит и пишет на русском языке, но тем не менее в школе экзаменом идет бел мова и в большинстве своем этот экзамен выбирают основным, не знаю как сейчас, но я сдавал бел мову. Родился я в 89 году и прожил в РФ в 90-20.

Считаю, что не нужно решать в данном треде этот вопрос, пусть решает приняте государства данный момент, даже если я и согласен с тс. Неприемлимо, тем более писать в опэн сор проект. Не нам решать, мы можем выдвинуть предложении, но не более.

И как бы нужно уважать деда, он бы мне рот порвал за такое).

**Comment by QManCorp** [comment]
"Of course, the radical nationalist community wants to impose Belarusian on the majority" - далей можна не працягваць... калі я размауляю па-беларуску, то адразу "radical nacionalist"...

**Comment by QManCorp** [comment]
> In the Unicode tables, you need to change the Russian and Belarusian places: 9.9 million speak Belarusian?)))))))))))))) Well, well...)))) It is good if a million people speak Belarusian, and that is debatable.
> 
> Wikipedia is generally written by people in random order. Many articles and sections are supported exclusively by minorities. Minorities are overly politicized, as you correctly noted. I advise you not to take into account the article about the Belarusian language in Wikipedia - it corresponds to reality well, if only half.
> 
> Here is my example: I was born in 1988 in Belarus. Both higher education courses were taught here in Russian. Both schools were Russian-speaking.
> 
> There are three options: Russian, Belarusian (pure, literary, which is familiar only to philologists) and "trasyanka" (a dialect consisting of a wild mixture of Russian-Belarusian words, often laced with obscene language (in rural areas)). The issue of language is indeed politicized, but the Russian language was, is, and remains ubiquitous.
> 
> Of course, the radical nationalist community wants to impose Belarusian on the majority, but as a result of the referendum, both languages were retained as state languages.
> 
> Just this fact with the language of the installer surprised me and I decided to check with the creators why it turned out this way. It turns out that you relied on unreliable statistics, which is not surprising with such a primary source.
> 
> In any case, thank you for your hard work and your answer. I will try to deal with the data you have provided links to, but it seems to me that this will be useless.

"Of course, the radical nationalist community wants to impose Belarusian on the majority" - далей можна не працягваць... калі я размауляю па-беларуску, то адразу "radical nacionalist"...

**Comment by Atos4444** [comment]
[Uploading Ne_peremotaesh_33.ico…]()

**Comment by kkofler** [comment]
This issue tracker is **not** the place for:
* political discussion,
* national and/or ethnic conflicts,
* posts in non-English languages, including but not limited to the two languages being discussed in this issue,
* uploads of icons or other files that are not useful to fix an issue in Calamares (and by the way, your link is broken).

So either we have a polite discussion in English that we can all understand, or we moderators will be forced to lock the conversation in this issue.
