### ISSUE TITLE
Full disk encryption failing to boot OS without systemd

### ISSUE THREAD

**Issue by Sarcasmo220** [calamares/calamares#1640]
**Describe the bug**
A clear and concise description of what the bug is. Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.
CPU: Intel 6500-U 64 bit
Firmware: EFI
OS: Nitrux
init: OpenRC. Does not have systemd

OS will not load after successfully unlocking LUKS encryption

**To Reproduce**
1. Install OS with full disk encryption selected 
2. Restart device
3. Enter encrypted disk password
4. See error: OS does not load and a prompt reading "<initramfs>" is the only thing visible.

**Expected behavior**
OS would boot.

**Comment by abucodonosor** [comment]
Do you have openrcdmcryptcfg enabled? And if you have and do something different from gentoo, send patches in.

**Comment by demmm** [comment]
Is Nitrux not using it's own (calamares based) installer? Do you know when it last synced with Calamares regarding LIUKS?

**Comment by Sarcasmo220** [comment]
I'm not sure when the last time Nitrux was synced with Calamares regarding LUKS. I am not the maintainer, but was directed by the maintainer to file a bug. I can test for the openrcdmcryptcfg, is that a package I need to install or something I enable in Calamares config file?

**Comment by Sarcasmo220** [comment]
The maintainer for Nitrux did some research and found some info on `openrcdmcryptcfg`. He says:

> 
> The file openrcdmcryptcfg.conf goes in /etc/calamares/modules and it's content from what I found should be
> 
> ---
> configFilePath: /etc/conf.d/dmcrypt
> 
> Then add it to /etc/calamares/settings.conf

The problem is, we don't know where in the `settings.conf `the module needs to be. I have been trying to plug it somewhere in the exec, but so far it has not worked. Are the contents for the module correct? Is there a particular order the `exec `portion should read? Any guidance you can give @abucodonosor  and @demmm would be greatly appreciated.

**Comment by adriaandegroot** [comment]
This conversation got kind of lost, so to pick it up again a bit:

- module configuration files go in `/etc/calamares/modules` and should be named after the module they're for.
- module configuration files are YAML files, so need to be YAML-correct. Calamares will complain if they're not, which will at least help you figure out if the file content is good. There's an example file with the right content in this repository.
- I don't see any indications **where** in the sequence this belongs. After partitioning, probably before *initcpio* modules. Most effective would be to find a distro that uses this module and check where in the sequence it happens. I don't know which distro that might be, though.

**Comment by V3n3RiX** [comment]
http://git.redcorelinux.org/cgit/redcore-desktop/tree/app-misc/calamares-config-redcore/files/settings.conf

As you can see, openrcdmcryptcfg module MUST be in the exec phase AFTER luksbootkeyfile module. The module will add (for each encrypted partition other than /root) something like : 

target=luks-and-a-random-uuid
source=/dev/disk/by-uuid/a-random-uuid
key=/crypto_keyfile.bin

to /etc/conf.d/dmcrypt which is the configuration file for /etc/init.d/dmcrypt . Make sure /etc/init.d/dmcrypt is added to default runlevel. 

Be aware that the openrcdmcryptcfg module was written to deal with partitions other than encrypted root and swap. Those are usually dealt by initramfs generators.

**Comment by adriaandegroot** [comment]
This issues was answered / explained by @V3n3RiX  over a year ago.
