### ISSUE TITLE
Fails to mount swap on fresh install

### ISSUE THREAD

**Issue by BananaLoaf** [calamares/calamares#1644]
**Describe the bug**
Fails to mount swap on fresh install. On both Manjaro and EndeavourOS.

**To Reproduce**
1. Setup encrypted swap and encrypted **BTRFS** root

**Expected behavior**
I expect system to not have problems with reading key file from BTRFS fs

**Screenshots and Logs**
```Failed to open key file.``` on boot screen

**Additional context**
Error comes from __openswap__ mkinitcpio hook. System fails to mount the right way volume on which key file is located.
In file ```/etc/openswap.conf```
line ```#keyfile_device_mount_options="--options=subvol=__active__"```
should look something like this: ```keyfile_device_mount_options="-t btrfs -o subvol=@,defaults"```

**Comment by adriaandegroot** [comment]
@Chrysostomus @codesardine can you take a look at this? It may be improved by the just-landed btrfs configurations, I can't tell.

**Comment by philmmanjaro** [comment]
At Manjaro we only updated **calamares-git** package in our **unstable** branch ...

**Comment by BananaLoaf** [comment]
@philmmanjaro hey, are there any updates on the issue?

**Comment by Spunkie** [comment]
@BananaLoaf I think there's a duplicate issue where more active discussion is happening, #1659?

**Comment by BananaLoaf** [comment]
> The content of `/etc/openswap.conf` is created by the _luksopenswaphookcfg_ module, which reads the file as-is from the installed system and then writes it out again, with modifications. Is the conf file supposed to be bash-sourceable, or is it purely key-value assignments? (I'll check at some point with a live ISO)

`/etc/openswap.conf` is sourced in `/usr/lib/initcpio/hooks/openswap`
