### ISSUE TITLE
transient hostname support

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1654]
**Is your feature request related to a problem? Please describe.**
Condensing the hostname aspect of #534

One might want to use transient hostnames (e.g. from DHCP) instead of static ones. Fortunately the main network middlewares already support this [1][2] and so this is relatively easy to achieve for calamares by simply relying on "some other thing" to actually set up the transient hostname.

[1] https://www.freedesktop.org/software/systemd/man/systemd.network.html#UseHostname=
[2] hostname-mode https://manpages.ubuntu.com/manpages/hirsute/man5/NetworkManager.conf.5.html

**Describe the solution you'd like**
The users module should grow a number of options to choose for hostname selection:

- makeSuggestion: the current behavior, pick a hostname based on other metadata set by the user
- current: suggest the current (possibly transient) hostname, make no dynamic suggestion, this allows the installation image itself to be transient but the target system to be static based on the transient name or a user override
- currentOrMakeSuggestion: same as above, in absence of a hostname (can that happen?) make a suggestion
- transient: do not set a static hostname on the target (`rm -f /etc/hostname`) and hide the input field in the UI

To fully support transient hostnames cala technically only needs the first and the last option, with 'current' being merely nice to have really.

**Comment by adriaandegroot** [comment]
There are new revamped settings available in `users.conf`:

- "make suggestion": use a suitable *location* setting (e.g. `EtcFile`) and a suitable *template* (e.g. `${first}-${product}`). These two e.g.'s are the default anyway.
- "current": use a suitable *location* setting, and a suitable *template* (e.g. `${host}`).
- "currentOrMakeSuggestion" seems overly complicated.
- "transient" use a suitable *location* setting (e.g. `Transient`).
