### ISSUE TITLE
mkinitcpio fails on encrypted installations with swap partition

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1656]
Calamares version : v3.2.38
ArcoLinux version : 21.03.10
mkinitcpio-openswap version : 0.1.0-3
Log file : https://termbin.com/zadeu
Package list : https://pastebin.com/FkrhR1at

Error messages : 

Command <i>mkinitcpio</i> finished with exit code 1
==> ERROR: Hook 'openswap' cannot be found

![error](https://user-images.githubusercontent.com/36679406/111176010-3fb92e80-85a9-11eb-8d18-0c8908b59680.png)
![fs](https://user-images.githubusercontent.com/36679406/111176028-434cb580-85a9-11eb-9718-c0a7a141868b.png)

All files and hooks present.

![hooks](https://user-images.githubusercontent.com/36679406/111176899-06cd8980-85aa-11eb-963c-ece1bdfe0bd9.png)

**Comment by kkofler** [comment]
I think you need to run the `luksopenswaphook` module before the `mkinitcpio` module.

**Comment by arcolinuxz** [comment]
sounds like a plan - let me get back to you

**Comment by arcolinuxz** [comment]
That is the current order of the modules.

![order](https://user-images.githubusercontent.com/36679406/111179560-7ba1c300-85ac-11eb-8ce0-4eda6ea8da89.png)

**Comment by arcolinuxz** [comment]
I just installed Garuda Linux with encryption and big swap.
May this shed some light on the issue.
https://gitlab.com/garuda-linux/packages/pkgbuilds/calamares-garuda-git/-/blob/master/garuda-btrfs.patch

**Comment by philmmanjaro** [comment]
Is it automatic or manual partitioning ?

**Comment by arcolinuxz** [comment]
It is ONLY automatic.

**Comment by philmmanjaro** [comment]
I just did a quick test on my end:

![image](https://user-images.githubusercontent.com/5050022/111284478-72facc80-8640-11eb-8b54-4e9308c599ef.png)
![image](https://user-images.githubusercontent.com/5050022/111284515-7aba7100-8640-11eb-9a19-37986f546304.png)

No issues found on [here](http://pastebin.com/jY7m3U8f). Must be a self-made issue on your end. Check the modules order and if you may have issues in grub.cfg.

**Comment by arcolinuxz** [comment]
As discussed I must have made changes in the past for a reason.

Fixed the issue by rechecking the current order of the modules.

  - luksopenswaphookcfg
  - luksbootkeyfile
  - initcpiocfg
  - initcpio

These 4 should not be seperated. The last two modules had moved down in the list over time. Maybe add to a readme @adriaandegroot.

Furthermore I had added in the **grubcfg.conf** this line   
GRUB_ENABLE_CRYPTODISK: true

I have removed that line now after comparing with the Calamares modules.

**Comment by arcolinuxz** [comment]
Another mistake is to switch these two from place.

luksopenswaphookcfg
luksbootkeyfile

should be

luksbootkeyfile
luksopenswaphookcfg

**Comment by arcolinuxz** [comment]
Ext4 is a success.
![ext4-enc](https://user-images.githubusercontent.com/36679406/111310463-66d13800-865d-11eb-8146-45173fabf2ff.png)

**Comment by arcolinuxz** [comment]
BTRFS works but gives an error at start
![btrfs-error](https://user-images.githubusercontent.com/36679406/111310641-9da74e00-865d-11eb-954c-4d3c1db9e632.jpg)

**Comment by arcolinuxz** [comment]
Xfs encrypted is a success
![Uploading xfs-enc.png…]()

**Comment by philmmanjaro** [comment]
I only tested **ext4** so far from my end. I maybe do other file systems later and update here. You may find our [daily dev-builds](https://github.com/manjaro/plasma-daily/releases) if you want to test on your own. Most likely you need to create a symlink for kpmcore lib, as otherwise CAL won't start.

**Comment by arcolinuxz** [comment]
thanks @philmmanjaro

**Comment by arcolinuxz** [comment]
Jfs encrypted is a success

![jfs-enc](https://user-images.githubusercontent.com/36679406/111313720-f9270b00-8660-11eb-8ce2-532520a5e4c0.png)

**Comment by arcolinuxz** [comment]
Reiser enc is a success.
![reiser-enc](https://user-images.githubusercontent.com/36679406/111315338-90d92900-8662-11eb-900d-5d221de06431.png)

**Comment by philmmanjaro** [comment]
I think it is more or less BTRFS and how it uses encryption ...

**Comment by arcolinuxz** [comment]
> I only tested **ext4** so far from my end. I maybe do other file systems later and update here. You may find our [daily dev-builds](https://github.com/manjaro/plasma-daily/releases) if you want to test on your own. Most likely you need to create a symlink for kpmcore lib, as otherwise CAL won't start.

Following your advice @philmmanjaro I downloaded this iso.
manjaro-kde-dev-21.0-unstable-210316-linux510.iso
Installed it - ran Calamares (new link from libkpmcore 10 to 11) rebuild is necessary there
and got same error but everything loads and seems to work just like on ArcoLinux
![manjaro-error](https://user-images.githubusercontent.com/36679406/111327318-9425e200-866d-11eb-8167-9cca5fb2f3fc.jpg)

![manjaro](https://user-images.githubusercontent.com/36679406/111327340-97b96900-866d-11eb-9f4e-49381c17ceec.jpg)

**Comment by arcolinuxz** [comment]
I see that in this line of code we add "openswap" to the mkinitcpio.conf while using mkinitcpio-openswap.
https://github.com/calamares/calamares/blob/186d32ebeebf1a11f0553b47d3386e85187478a9/src/modules/initcpiocfg/main.py#L171

On **encrypted** installations that word stays in on the future system as you can see in this image.
![openswap-hook](https://user-images.githubusercontent.com/36679406/111368726-820c6980-8696-11eb-8c5d-7394575dd631.png)

Removing the word openswap from the /etc/mkinitcpio.conf and rebuilding with sudo mkinitcpio -p linux will remove the first line of the error message.
![encrypted-rebuild-mkinitcpio](https://user-images.githubusercontent.com/36679406/111369139-fe9f4800-8696-11eb-9210-b2ec04029078.png)
Then we reboot
![less-errors](https://user-images.githubusercontent.com/36679406/111369298-31494080-8697-11eb-9ba0-49304368df4f.png)

**Comment by arcolinuxz** [comment]
I tried keeping the mkinitcpio-openswap after installing - same issue.

**Comment by arcolinuxz** [comment]
After a lot of testing I believe there are only 2 issues left to solve and both are for btrfs.
For future readers
The order of the modules matters - see config file
Keep mkinitcpio-openswap on the future system if you want your users to be able to encrypt.
closing this topic and opening two issues.
