### ISSUE TITLE
Dropdown to choose the filesystem : ext4, btrfs, xfs, jfs and reiser

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1657]
For now ArcoLinux has created a tool to easily change the partition.conf (line105) file from ext4 to any other filesystem.

Could this be incorporated in the installer please? 
Can the developers fill up the list of the dropdown?
Add an option to enable or not.

![gnome-btrfs-encrypted1](https://user-images.githubusercontent.com/36679406/111277431-bc471e00-8638-11eb-81d4-db40ab078ef4.png)

**Comment by asif-mahmud** [comment]
Hi, i think you are using a custom/edited partition.conf which does not match with the current repo.

**Comment by abucodonosor** [comment]
@arcolinuxz 

An extra tool? Nah, that needs to be done in the calamres itself. 

See https://github.com/calamares/calamares/issues/847

**Comment by philmmanjaro** [comment]
See here: https://github.com/calamares/calamares/pull/1667

**Comment by demmm** [comment]
Is it sufficient that this is now implemented in the `erase disk` option?  If so, can be closed.

**Comment by arcolinuxz** [comment]
Option1 : install alongside - is there a problem in combining partitions with different filesystem formats - if not - give the option here too when clicked

Option 2 : Replace partition - replace one formatting system with another - give the option here too when clicked

![calam](https://user-images.githubusercontent.com/36679406/127806872-278fe6ff-1bd9-4c63-8794-0c4783c863ff.png)

What do other developers think?

**Comment by demmm** [comment]
IMO, automated should be just that, set defaults per distro. Erase disk is borderline, since you start over completely, but for the rest, for me, it should be handled by manual partitioning.

**Comment by arcolinuxz** [comment]
I have been thinking and am in the process to make things more KISS on my project

Giving more choices and more freedom seems to be counterproductive for "the general user"
I would keep it as is for now and close the issue.

**Comment by carbon-ui** [comment]
@arcolinuxz nt closed till now?

**Comment by erikdubois** [comment]
this can be closed for me
