### ISSUE TITLE
Btrfs Encrypted with small or big swap - partitioning automatically - error message

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1659]
![btrfs-error](https://user-images.githubusercontent.com/36679406/111484077-b420d880-8735-11eb-9a44-cee4d415efb1.jpg)
Failed to open key file.
ERROR: resume: hibernation device ... not found

Calamares version : v3.2.38
Calamares config : v21.03.11
https://github.com/arcolinux/arco-calamares-config/releases/tag/21.03.11
ArcoLinux version : 21.03.11
https://github.com/arcolinux/arcolinux-iso/releases/tag/21.03.11
mkinitcpio-openswap version : 0.1.0-3
Package list : https://pastebin.com/uR6F5CSq
1 Probe link hardware and software overview : https://linux-hardware.org/?probe=79e3573fed
2 Probe link hardware and software overview : https://linux-hardware.org/?probe=d91551dac1

We do however boot up and we have a working system. Working on it now. See for more info in the probe link number 1.

Gparted

![gparted](https://user-images.githubusercontent.com/36679406/111487389-9a34c500-8738-11eb-9642-a1ad1b6e9b6c.png)

Lsblk
![lsblk](https://user-images.githubusercontent.com/36679406/111487443-a6b91d80-8738-11eb-8c61-f519a333776b.png)

Lsblk -f
![lsblk-f](https://user-images.githubusercontent.com/36679406/111487455-a91b7780-8738-11eb-8c9e-6524bcdda28c.png)

fstab

![fstab](https://user-images.githubusercontent.com/36679406/111487585-c7817300-8738-11eb-92ef-6715d724ee91.png)

crypttab

![cryptab](https://user-images.githubusercontent.com/36679406/111487981-1deeb180-8739-11eb-98c4-d2d9b6076fdc.png)

default/grub
![default-grub](https://user-images.githubusercontent.com/36679406/111488198-51c9d700-8739-11eb-9276-6643ddc95c8b.png)

**Comment by arcolinuxz** [comment]
Test with manjaro build of 
https://github.com/manjaro/plasma-daily/releases from 2021/03/17.
Updated for boost version - made symlink for libkpmcore from 10 to 11

Calamares version

![man-calamares](https://user-images.githubusercontent.com/36679406/111499820-9f4b4180-8743-11eb-804c-f700d153a393.png)

Settings - /usr/share/calamares/modules/partition.conf set to btrfs

![man-choices](https://user-images.githubusercontent.com/36679406/111499848-aa05d680-8743-11eb-95bf-200aec5bf82b.png)

Error
![manjaro](https://user-images.githubusercontent.com/36679406/111499940-bf7b0080-8743-11eb-8789-6ef3242de260.png)

**Comment by arcolinuxz** [comment]
Garuda linux Cinnamon
garuda-cinnamon-linux-zen-210225.iso

![gar-calamares](https://user-images.githubusercontent.com/36679406/111505633-1e8f4400-8749-11eb-8d89-3d9a614902b4.png)

Settings
With hibernate - standard in btrfs
![gar-settings1](https://user-images.githubusercontent.com/36679406/111505984-762daf80-8749-11eb-9ea2-e9e45255895f.png)

Then switch to encrypted
![gar-settings2](https://user-images.githubusercontent.com/36679406/111506028-8180db00-8749-11eb-8b49-df7c53985feb.png)

**Comment by killajoe** [comment]
EndeavourOS
install with full disk encryption, efi, default fs=BTRFS, swap-partition with hibernate:
boot error is also:
`ERROR: resume: hibernation device ' /dev/mapper/luks....' not found`

![resume error](https://i.imgur.com/AbqPcn8.png "boot resume error")

Calamares install log: http://ix.io/2TdJ

filesystems, grub, fstab:
`lsblk -f
NAME    FSTYPE      FSVER LABEL       UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sr0     iso9660           ENDEAVOUROS 2021-03-17-12-14-34-00                              
vda                                                                                       
├─vda1  vfat        FAT32 NO_LABEL    C853-0FE3                             510,3M     0% /boot/efi
├─vda2  crypto_LUKS 1                 17b97331-37bd-416b-8d3e-ad1502f26749                
│ └─luks-17b97331-37bd-416b-8d3e-ad1502f26749
│       btrfs                         4e9461d3-8b17-4738-b206-12ac144b57a9    5,2G    45% /home
└─vda3  crypto_LUKS 1                 0567d825-c4fc-400d-b327-6015bc997ef0                
  └─luks-0567d825-c4fc-400d-b327-6015bc997ef0
        swap        1                 21d85f31-5a68-48ba-b5e5-6b5d22a23800                [SWAP]
----
cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a device; this may
# be used with UUID= as a more robust way to name devices that works even if
# disks are added and removed. See fstab(5).
#
# <file system>             <mount point>  <type>  <options>  <dump>  <pass>
UUID=C853-0FE3                            /boot/efi      vfat    umask=0077 0 2
/dev/mapper/luks-17b97331-37bd-416b-8d3e-ad1502f26749 /              btrfs   subvol=@,defaults,noatime,space_cache,autodefrag 0 1
/dev/mapper/luks-17b97331-37bd-416b-8d3e-ad1502f26749 /home          btrfs   subvol=@home,defaults,noatime,space_cache,autodefrag 0 2
/dev/mapper/luks-0567d825-c4fc-400d-b327-6015bc997ef0 swap           swap    defaults,noatime 0 0
---
# GRUB boot loader configuration

GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="EndeavourOS"
GRUB_CMDLINE_LINUX_DEFAULT="quiet cryptdevice=UUID=17b97331-37bd-416b-8d3e-ad1502f26749:luks-17b97331-37bd-416b-8d3e-ad1502f26749 root=/dev/mapper/luks-17b97331-37bd-416b-8d3e-ad1502f26749 resume=/dev/mapper/luks-0567d825-c4fc-400d-b327-6015bc997ef0 loglevel=3 nowatchdog"
GRUB_CMDLINE_LINUX=""`

**Comment by philmmanjaro** [comment]
So guys, does the code work for other filesystems other as **btrfs** as expected? Like has it the right swap file/partition and grub entries?

**Comment by arcolinuxz** [comment]
Yes that all works
![overview](https://user-images.githubusercontent.com/36679406/111526583-383b8600-875f-11eb-900f-57d7761088c8.png)

**Comment by philmmanjaro** [comment]
@arcolinuxz should I produce an ISO with **linux54** just to see if it is a kernel issue? And if so, which DE you like to test?

**Comment by killajoe** [comment]
same here it seems only if rootfs is BTRFS and full encrypted then swap-partition failed to be usable for resume, as swap itself is available on booted system.

**Comment by killajoe** [comment]
i am also not sure if it would not be legit to create a BTRFS subvolume for swap?

**Comment by arcolinuxz** [comment]
> @arcolinuxz should I produce an ISO with **linux54** just to see if it is a kernel issue? And if so, which DE you like to test?

Xfce would be best to compare

**Comment by philmmanjaro** [comment]
I just released Manjaro 21.0 RC1 yesterday. It ships with 3.2.37 still. Give it a try: https://sourceforge.net/projects/manjarotest/files/21.0-210318/

**Comment by erikdubois** [comment]
Does it throw the same error when selecting encrypted and btrfs with swap

**Comment by philmmanjaro** [comment]
Didn't test as it has the older CAL. The latest CAL can be found here: https://github.com/manjaro/plasma-daily/releases

**Comment by philmmanjaro** [comment]
So lets test this all again on 3.2.39 release. Based on the report by @killajoe we have this:

```
└─vda3  crypto_LUKS 1                 0567d825-c4fc-400d-b327-6015bc997ef0                
  └─luks-0567d825-c4fc-400d-b327-6015bc997ef0
        swap        1                 21d85f31-5a68-48ba-b5e5-6b5d22a23800                [SWAP]
```
And this in **grub**:

```
GRUB_CMDLINE_LINUX_DEFAULT="quiet cryptdevice=UUID=17b97331-37bd-416b-8d3e-ad1502f26749:luks-17b97331-37bd-416b-8d3e-ad1502f26749 root=/dev/mapper/luks-17b97331-37bd-416b-8d3e-ad1502f26749 resume=/dev/mapper/luks-0567d825-c4fc-400d-b327-6015bc997ef0 loglevel=3 nowatchdog"
```

Which results in: ERROR: resume: hibernation device ' /dev/mapper/luks....' not found

For **btrfs** we have this subvolume **21d85f31-5a68-48ba-b5e5-6b5d22a23800** here. So we have to find a way on how **grubcfg** module is dealing with that fact. @Chrysostomus any idea?

**Comment by Chrysostomus** [comment]
Some things to note:

- why does the mapper name look like uuid? Seems very inconvenient
- resuming from swapfile requires the parameter resume_offset={swap_file_offset}. The given parameters should not work even with ext4
-

**Comment by killajoe** [comment]
>     * resuming from swapfile requires the parameter resume_offset={swap_file_offset}. The given parameters should not work even with ext4

and getting needed names and numbers is different on BTRFS and ext4: https://wiki.archlinux.org/index.php/Power_management/Suspend_and_hibernate#Hibernation_into_swap_file_on_Btrfs

but the issue here is with swap-partition and encryption what fails.
Swap without encryption is created in the same way like it is done is rfs is ext4 or anything else.. 
![2021-03-21_10-37](https://user-images.githubusercontent.com/16797647/111900251-c77fbc80-8a31-11eb-82f0-f9bed54d878b.png)
Question is also if swap is usable at all together with BTRFS rfs for hibernation if it is unencrypted?

**Comment by killajoe** [comment]
tested:
encryption, automatic partition (BTRFS), swap with hibernate
same error warning on startup, but swap seems to be working on system.
crypttab says:
```
NOTE: Do not list your root (/) partition here, it must be set up
       beforehand by the initramfs (/etc/mkinitcpio.conf). The same applies
       to encrypted swap, which should be set up with mkinitcpio-openswap
       for resume support.
```
so both / and swap should not be inside /etc/crypttab but they are as @arcolinuxz shows above. and still with cal39 the same. 

I could not really test hibernation on VM ..

**Comment by philmmanjaro** [comment]
>     * resuming from swapfile requires the parameter resume_offset={swap_file_offset}. The given parameters should not work even with ext4

We have to double check this. As I see it: for now we have swap as a file but not enabled to be used for hibernation. If we want that, we should open a new issue for that.

**Comment by killajoe** [comment]
> Didn't test as it has the older CAL. The latest CAL can be found here: https://github.com/manjaro/plasma-daily/releases

https://github.com/manjaro/plasma-daily/releases/tag/202103210305
calamares is build against older kpm version then is installed on the ISO ;)

**Comment by philmmanjaro** [comment]
Yes, is a known issue. Create a symlink.

**Comment by killajoe** [comment]
> Yes, is a known issue. Create a symlink.

yes done that, and install result in exactly the same as my test with EndeavourOS ISO and cal39.

**Comment by NirmalManoj** [comment]
I installed Manjaro KDE using the erase disk option(encryption ticked), choosing btrfs with hibernation. However, when I boot to Manjaro, I get the following message, and then it starts the OS. 

![boot message](https://user-images.githubusercontent.com/18501167/132747545-ec462d03-824d-4890-b912-9a0e807c06da.jpg)

So the flow is like this when PC starts, grub asks for my encryption password, then it loads the grub boot menu (I have windows 11 on another SSD). When I choose Manjaro, it shows the message in the above image, either getting stuck for 10-30 seconds before booting Manjaro or getting stuck forever, in which case I have to restart the PC using the power button manually.


The encrypted swap partition works, except for hibernation.

The following screenshot contains some details about my system, which might be helpful to understand things better.

![details](https://user-images.githubusercontent.com/18501167/132747956-7ba3535b-1f49-4151-8a2f-ac8a980e647e.png)

Please let me know if any more details about my system are required to understand what's happening here.

**Comment by NirmalManoj** [comment]
@arcolinuxz @philmmanjaro @killajoe I'm sorry for tagging. I have been trying to find a way to make hibernation work in the last couple of days, but nothing worked. If you know a way to fix this, for the time being, I would appreciate it if you would let me know about it.

**Comment by killajoe** [comment]
This is still the same for latest calamares 3.2.42 (just tested it)
Also system boots fine.

**Comment by killajoe** [comment]
i see some confusion swap partition vs swap file.. but still only swap partition with hibernate is a option in cal42.
the only issue i can see is that crypttab says swap should not be inside it and handled by mkinitcpio-openswap.
So could be that this is the issue. it uses mkinitcpio-openswap but has the swap entry in crypttab what fails

**Comment by killajoe** [comment]
... But: 
i try to remove the swap device from /etc/crypttab leads to system not booting.. and if we are using openswap hook it should not be needed to have swap device in /etc/crypttab what leads to the conclusion openswap is not working!

**Comment by killajoe** [comment]
I will go to check if i can fix it be checking what is going wring with mkinitcpio-openswap // AUR build..

**Comment by killajoe** [comment]
> @arcolinuxz @philmmanjaro @killajoe I'm sorry for tagging. I have been trying to find a way to make hibernation work in the last couple of days, but nothing worked. If you know a way to fix this, for the time being, I would appreciate it if you would let me know about it.

Issue is solved .. you need to simply edit the `/etc/openswap.conf `

```
## additional arguments are given to mount for keyfile_device
## has to start with --options (if so desired)
keyfile_device_mount_options="--options=subvol=@"
```
the option `keyfile_device_mount_options="--options=subvol=@"` is needed to get BTRS subvolume mounted .. 
So i was right in a way that openswap was not working .. it could not read the keyfile because it was not able to open swap partition..

After editing you should rebuild kernel images ? (not sure if it is needed) 
`sudo mkinitcpio -P`

And you can remove the swap partition from /etc/crypttab.

**Comment by killajoe** [comment]
![2021-09-15_17-56](https://user-images.githubusercontent.com/16797647/133469144-d45d028e-9e8a-49c5-b0c1-b40a067784ce.png)
No more errors and hibernating should work.. i can not test this here in VM but it should work now..

**Comment by NirmalManoj** [comment]
@killajoe Thank you so much for finding a fix for this. I will try this in two days and let you know how it goes.

**Comment by killajoe** [comment]
without you bringing this up again it would not be known

**Comment by killajoe** [comment]
Is it possible to set this up to be solved in calamares?
if btrfs and encryption is used set openswap.conf ..

**Comment by Spunkie** [comment]
Thank you @killajoe & @BananaLoaf :heart: 

I tested out @killajoe fix, it resolves the error message at boot and at first glance looks to have fixed hibernate on my manjaro install. 🥳
___
Also it seems like there has been a duplicate issue and suggested fix sitting quietly in #1644 since Feb, 2021. Shame that @BananaLoaf contributions were somewhat ignored and the bug has made it way into live installs on multiple distros now.

refs:
https://forum.manjaro.org/t/impossible-to-hibernate/79833/14
https://forum.endeavouros.com/t/key-file-not-found/17707/2

**Comment by NirmalManoj** [comment]
@killajoe 
I tried it two days ago. Now I don't see the missing keyfile error when Manjaro boots. But when I try to hibernate, it shuts down normally, but gets stuck at Acer Predator logo on reboot. Then I have to press the power button to reboot again - which boots me to a non-hibernated state. I thought I would try fixing it myself before reporting here.

**Comment by NirmalManoj** [comment]
@Spunkie Did you try hibernation? Error message was gone for me also.

**Comment by Spunkie** [comment]
@NirmalManoj I gave it a few quick tries and it certainly seems less broken than before. 

But as a new convert from windows, I'm honesty not 100% on how a working hibernate with luks is supposed to function/appear. 
___
Previously if I tried to hibernate it would appear like it hibernates fine, but after pressing the power button, and after my bios boot screen, I would end up stuck on a blank screen. 

Now it hibernates, after pressing the power button I get shown a luks decrypt/password prompt, and from there it dumped me into an active KDE wayland session. So... success?

There is certainly a lot of "glitchyness" though, like while hibernating the system appears to go to sleep and awaken quite a few times before eventually actually hibernating. Same for the resumed sessions, many visually flashes and glitches during wake up, and random things like audio devices are missing, etc

**Comment by dalto8** [comment]
In my initial testing, it seems that setting the default subvolume to `@` also resolves this error.  

I am not sure if this is better or worse than the workaround suggested by @killajoe

**Comment by Tealk** [comment]
> > @arcolinuxz @philmmanjaro @killajoe I'm sorry for tagging. I have been trying to find a way to make hibernation work in the last couple of days, but nothing worked. If you know a way to fix this, for the time being, I would appreciate it if you would let me know about it.
> 
> Issue is solved .. you need to simply edit the `/etc/openswap.conf `
> 
> ```
> ## additional arguments are given to mount for keyfile_device
> ## has to start with --options (if so desired)
> keyfile_device_mount_options="--options=subvol=@"
> ```
> 
> the option `keyfile_device_mount_options="--options=subvol=@"` is needed to get BTRS subvolume mounted .. So i was right in a way that openswap was not working .. it could not read the keyfile because it was not able to open swap partition..
> 
> After editing you should rebuild kernel images ? (not sure if it is needed) `sudo mkinitcpio -P`
> 
> And you can remove the swap partition from /etc/crypttab.

When I set the following, the SWAP partition no longer works.

**Comment by killajoe** [comment]
> When I set the following, the SWAP partition no longer works.

same way to install system ? using BTRFS ? full encryption ?

**Comment by Tealk** [comment]
> same way to install system ? using BTRFS ? full encryption ?

yes, full encryption and btrfs file system. Is it possible that removing the swap partition from /etc/crypttab is the problem?

**Comment by dalto8** [comment]
> > same way to install system ? using BTRFS ? full encryption ?
> 
> yes, full encryption and btrfs file system. Is it possible that removing the swap partition from /etc/crypttab is the problem?

Which distro are you using?

**Comment by Tealk** [comment]
> Which distro are you using?

Kernel: 5.13.19-2-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 Desktop: GNOME 40.5 tk: GTK 3.24.30
           wm: gnome-shell dm: GDM 40.1 Distro: Manjaro Linux base: Arch Linux

**Comment by vitor-mariano** [comment]
> > @arcolinuxz @philmmanjaro @killajoe I'm sorry for tagging. I have been trying to find a way to make hibernation work in the last couple of days, but nothing worked. If you know a way to fix this, for the time being, I would appreciate it if you would let me know about it.
> 
> Issue is solved .. you need to simply edit the `/etc/openswap.conf `
> 
> ```
> ## additional arguments are given to mount for keyfile_device
> ## has to start with --options (if so desired)
> keyfile_device_mount_options="--options=subvol=@"
> ```
> 
> the option `keyfile_device_mount_options="--options=subvol=@"` is needed to get BTRS subvolume mounted .. So i was right in a way that openswap was not working .. it could not read the keyfile because it was not able to open swap partition..
> 
> After editing you should rebuild kernel images ? (not sure if it is needed) `sudo mkinitcpio -P`
> 
> And you can remove the swap partition from /etc/crypttab.

For any reason, my `/etc/openswap.conf` came from installation with:

```conf
keyfile_device_mount_options=keyfile_device_mount_options=--options=subvol=@
```

I just removed the duplicate key and it worked like a charm. Thank you!

**Comment by demmm** [comment]
@vitor-mariano This bug report needs to be re-opened.  Initial report was fixed, but with the port of the initial fix to C++, there is now an error on reading & replacing the `#keyfile_device_mount_options=` line
https://github.com/calamares/calamares/blob/calamares/src/modules/luksopenswaphookcfg/LOSHJob.cpp#L109
https://github.com/calamares/calamares/blob/calamares/src/modules/luksopenswaphookcfg/LOSHJob.cpp#L168
