### ISSUE TITLE
Possibility to autologin lost in v3.2.39 in SDDM

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1665]
Using Calamares 3.2.39 and selecting the user to autologin is not adding the user to the /etc/sddm.conf [Autologin] part of the file.
Autologin is no longer possible.
Not sure but to help you I see this commit about the users module - change in name there - 44ac33845dd3068c1c29439fc853e64b717fe3cd

**Comment by demmm** [comment]
Just an FWIW, autologin for sddm works as always for KaOS with the above commit included (using the users module, usersq not ready yet).

**Comment by adriaandegroot** [comment]
Fixed in 42d00ffe38f854f90fb966e3f3ee32e26811ed96
