### ISSUE TITLE
GS key *locale* not always set

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1671]
The *packages* module has special handling for packages with `LOCALE` in their name, and substitutes the chosen locale. This is used to install, for instance, localization packages for something -- like an office suite. The value for `LOCALE` comes from the *locale* GS key. See `subst_locale()` in the *packages* module.

The *locale* GS key is **not** set when just clicking through; even when changing the default language on the welcome page. It is only set (in current development) by going through the *change* button on the locale / location page.

**Comment by demmm** [comment]
FWIW, this bug does show itself clearly in localeq, when setting a different local in the welcome page, localeq shows in old locale, until the map is clicked, only then does it adjust.

**Comment by adriaandegroot** [comment]
In v3.2.24 (just picked something "old") the *locale* GS key is set as soon as you arrive on the locale page.

**Comment by demmm** [comment]
Just pulled all the latest, issue not fixed in localeq, so I will double check the QML, probably an error there.
