### ISSUE TITLE
Autologin feature in Calamares 3.39.2

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1672]
i do just test on autologin with latest cal 3.39.2 and changed `autologinGroup:  autologin` to `autoLoginGroup:  autologin` and `doAutologin:     false` to `doAutoLogin:     false` in users.conf and i got autologin back working  so seems that the scriptlet to solve old namings in config is not working ?

users.conf autologinGroup:
https://github.com/calamares/calamares/blob/ea61ac4386bc74a35685fed41d7c1990ae58a8fd/src/modules/users/users.conf#L48

users.conf doAutologin:
https://github.com/calamares/calamares/blob/ea61ac4386bc74a35685fed41d7c1990ae58a8fd/src/modules/users/users.conf#L54

related change:
https://github.com/calamares/calamares/commit/8949b079e1d88ecfeddc420a17b63140ae2ba01a

![2021-04-13_12-43](https://user-images.githubusercontent.com/16797647/114540571-fca8b480-9c55-11eb-9d0a-de3b44e60a6a.png)

@adriaandegroot

**Comment by adriaandegroot** [comment]
Fixed in 3.2.39.3
