### ISSUE TITLE
Error Startup: Failed modules (users@users, users@users) - just started with Archiso builds today

### ISSUE THREAD

**Issue by ezsit55** [calamares/calamares#1678]
I am getting this error when starting Calamares in my own Arch based respin: 

Arch Linux can not be installed. Calamares was not able to load all of the configured modules. This is a problem with the way Calamares is being used by the distribution. The following modules could not be loaded:
users@users
users@users

There is this line in the debug output:

ERROR: STARTUP: failed modules are ("users@users", "users@users")

Before you blame the user and my Arch respin, the identical Calamares version, 3.2.39.3, and the identical modules and their configuration files were used just three days ago with success. My Calamares build and the module configuration files have not changed in the last three days. The only changes are Arch packages. Systemd has been updated within the last three days, among various other Arch packages.

I have already tried running Calamares with the default users.conf as shipped by Calamares and I receive the exact same error, telling me this is not a problem with my users.conf file.

Is anyone else seeing this error?
![Screenshot at 2021-04-18 17-34-15](https://user-images.githubusercontent.com/74875965/115168347-6d453c00-a06f-11eb-8a29-aa1f76846710.png)

**Comment by adriaandegroot** [comment]
The actual problems with the *users* module would have been visible earlier in the log, but glad to see that this was resolved one way or another.

**Comment by erikdubois** [comment]
you had to rebuild Calamares because of boost and boost-libs update

https://youtu.be/F03I9EECQY8

**Comment by killajoe** [comment]
If it is an issue with libs you will see it in the log:
![b100aea362a397d0680ef0b4b1d66e0bbed841b4](https://user-images.githubusercontent.com/16797647/115204825-3287e600-a0f9-11eb-9f29-c858fee6020b.png)
This was shown on building cal with ico 68 and run it on icu 69 ;)

**Comment by philmmanjaro** [comment]
Well, Calamares needs a rebuild on ICU.

**Comment by ezsit55** [comment]
Thank you Erik. I spotted your video just minutes after posting this issue. As soon as I rebuilt Calamares, the problem was solved. I noticed boost released 1.76.0 and it has yet to hit the Arch repos. We will need to do this again very shortly. :-)

**Comment by kkofler** [comment]
You Arch folks really need a way to track this automatically. There are package managers out there (RPM, at least) that automatically track soname dependencies and will not even let you install the package if its required libraries are not present. And then there are daily checks at repository level that check for broken dependencies. I suppose the latter could even be done without package manager support, with more effort. (You will have to do a lot of unpacking and of `nm`ing and/or `ldd`ing.) But only figuring this out by manually scanning logfiles for runtime errors from `ld.so` is clearly suboptimal.

**Comment by ezsit55** [comment]
"You Arch folks really need ..."
Are you serious? most of the time this stuff happens its related to a boost update. We users do not have a choice is how often boost updates and how every minor point release of boost breaks something in Calamares. The only solution for rolling release users is to remember to recompile Calamares before every deployment. I was lazy, that's my own fault. But after being burned twice by a boost update breaking Calamares I will remember to recompile Calamares immediate before deploying it. Thanks.

**Comment by kkofler** [comment]
All I am saying is that a QA script (a repository consistency check script) running daily on some server can save you from runtime surprises and prevent a lot of pain. Now, `pacman` is also less than helpful here (because it does not track soname dependencies), but that does not preclude doing this QA on the repository, it just makes it harder.

**Comment by kkofler** [comment]
So when the Boost or ICU maintainers bump their package, the script would report that Calamares has a broken dependency on the old soname and needs to be rebuilt. But somebody needs to write the script.
