### ISSUE TITLE
Kde neon Not installed on Btrfs 

### ISSUE THREAD

**Issue by Revvz** [calamares/calamares#1679]
The system is not installed if you select the btrfs file system as the / root partition.
Gives an error message:

"Failed to unpack image "/cdrom/casper/filesystem.squashfs" rsync failed with error code 11!

STEPS TO REPRODUCE
1. Download the User Edition installation image
2. Start the installation of the distribution kit, and select btrfs as the file system under the / root partition
3. Start installation

**Comment by adriaandegroot** [comment]
There have been a lot of btrfs-related improvements since this issue, and since it's light on details (and I never picked it up when first filed) I'm going to close it as "overcome by events".
