### ISSUE TITLE
(KDE neon) root on btrfs fails; target volume is unmounted before rsync

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1682]
Downstream bug https://bugs.kde.org/show_bug.cgi?id=436005

From logfiles (not attached to that BR though) it looks like the target FS is being mounted, and then immediately **un**mounted; screenshot:

![image](https://user-images.githubusercontent.com/19431457/115931288-2dc18a00-a48b-11eb-8926-d28749656980.png)

**Comment by nagi1999a** [comment]
I also cannot install KDE neon if I selected btrfs as root file system, but my problem is that grub would not install because of wrong mount options. After some investigation, I found that the config file in live cd maybe loss some content for btrfs subvolume definitions, so I did following:
1. Download https://github.com/calamares/calamares/blob/calamares/src/modules/mount/mount.conf
2. copy the file to the /calamares/desktop/modules/mount/ on live cd before start calamares
3. start calamares and start installation
and then everything goes well.
BTW, I also seen the error message shown in the downstream log, but it only occurs when I try to install again after a fail installation without reboot.

**Comment by apachelogger** [comment]
Another defect where defaults change out from under the distro? Certainly sounds similar in style to https://github.com/calamares/calamares/issues/1625 where a change was made and then stuff is broken.

**Comment by cpatrick08** [comment]
> I also cannot install KDE neon if I selected btrfs as root file system, but my problem is that grub would not install because of wrong mount options. After some investigation, I found that the config file in live cd maybe loss some content for btrfs subvolume definitions, so I did following:
> 
> 1. Download https://github.com/calamares/calamares/blob/calamares/src/modules/mount/mount.conf
> 2. copy the file to the /calamares/desktop/modules/ on live cd before start calamares
> 3. start calamares and start installation
> 
> and then everything goes well.
> BTW, I also seen the error message shown in the downstream log, but it only occurs when I try to install again after a fail installation without reboot.

This didn't work on the latest testing ISO, will try with the user edition ISO and report back.

**Comment by cpatrick08** [comment]
Error i get on User Edition and Testing Edition.
![InstallationError](https://user-images.githubusercontent.com/1483904/120909630-5336db80-c666-11eb-83ff-b19d397ddc2f.png)

**Comment by nagi1999a** [comment]
> Error i get on User Edition and Testing Edition after trying nagi1999a's work around.
> Error message from Konsole on User Edition.
> Not enabling extra modes
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> 20:38:40 [1]: Calamares::Module* Calamares::moduleFromDescriptor(const Calamares::ModuleSystem::Descriptor&, const QString&, const QString&, const QString&)
> ERROR: YAML parser error yaml-cpp: error at line 103, column 65: illegal map value
> 20:38:40 [1]: void Calamares::ModuleManager::loadModules()
> ERROR: Module "mount@mount" cannot be created from descriptor "mount.conf"
> 20:38:40 [1]: bool Calamares::ModuleManager::checkModuleDependencies(const Calamares::Module&)
> ERROR: Module "unpackfs" requires "mount" before it in sequence.
> 20:38:40 [1]: void CalamaresApplication::initFailed(const QStringList&)
> ERROR: STARTUP: failed modules are ("mount@mount", "unpackfs@unpackfs")
> 20:38:41 [0]: unknown file system type "" on "/dev/nvme0n1p2"
> 
> ![InstallationError](https://user-images.githubusercontent.com/1483904/120909630-5336db80-c666-11eb-83ff-b19d397ddc2f.png)

Hello, I have tried with latest User Edition again, and have no problems. However, I could reproduce the Initialization Failed message by having a typo in mount.conf, so there maybe something wrong with your procedure. Could you share how you copied the updated conf file to /calamares/desktop/modules/ ?

And here what I have done:
1. Download [](https://github.com/calamares/calamares/blob/calamares/src/modules/mount/mount.conf)
2. Reboot
3. In grub menu, select first KDE neon option
4. Open konsole and do "sudo mv /calamares/desktop/modules/mount.conf /calamares/desktop/modules/mount.conf.old"
5. Find the download file location (Suppose it is in /media/neon/<UUID>/mount.conf)
6. In konsole, do "sudo cp /media/neon/<UUID>/mount.conf /calamares/desktop/modules/mount.conf"
7. start calamares with desktop icon, or "sudo calaremares" with konsole

BTW, the mount.conf can be simply replaced with calamares official one is because that the mount option in neon is totally the same with calamares one.

**Comment by cpatrick08** [comment]
> > Error i get on User Edition and Testing Edition after trying nagi1999a's work around.
> > Error message from Konsole on User Edition.
> > Not enabling extra modes
> > QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> > QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> > QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> > QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> > QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> > 20:38:40 [1]: Calamares::Module* Calamares::moduleFromDescriptor(const Calamares::ModuleSystem::Descriptor&, const QString&, const QString&, const QString&)
> > ERROR: YAML parser error yaml-cpp: error at line 103, column 65: illegal map value
> > 20:38:40 [1]: void Calamares::ModuleManager::loadModules()
> > ERROR: Module "mount@mount" cannot be created from descriptor "mount.conf"
> > 20:38:40 [1]: bool Calamares::ModuleManager::checkModuleDependencies(const Calamares::Module&)
> > ERROR: Module "unpackfs" requires "mount" before it in sequence.
> > 20:38:40 [1]: void CalamaresApplication::initFailed(const QStringList&)
> > ERROR: STARTUP: failed modules are ("mount@mount", "unpackfs@unpackfs")
> > 20:38:41 [0]: unknown file system type "" on "/dev/nvme0n1p2"
> > ![InstallationError](https://user-images.githubusercontent.com/1483904/120909630-5336db80-c666-11eb-83ff-b19d397ddc2f.png)
> 
> Hello, I have tried with latest User Edition (neon-user-20210527-0944.iso), and have no problems. However, I could reproduce the Initialization Failed message by having a typo in mount.conf, so there maybe something wrong with your procedure. Could you share how you copied the updated conf file to /calamares/desktop/modules/ ?
> 
> And here is what I have done:
> 
> 1. Download https://github.com/calamares/calamares/blob/calamares/src/modules/mount/mount.conf
> 2. Reboot
> 3. In grub menu, select first KDE neon option
> 4. Open konsole and do "sudo mv /calamares/desktop/modules/mount.conf /calamares/desktop/modules/mount.conf.old"
> 5. Find the download file location (Suppose it is in /media/neon/UUID/mount.conf)
> 6. In konsole, do "sudo cp /media/neon/UUID/mount.conf /calamares/desktop/modules/mount.conf"
> 7. Start calamares with desktop icon, or "sudo calaremares" with konsole
> 
> BTW, the mount.conf can be simply replaced with calamares official one is because that the mount option in neon is totally the same with calamares one.
> 
> Typo in btrfsSubvolumes part:
> ![Screenshot_20210606_020658](https://user-images.githubusercontent.com/49529145/120914385-8e003a00-c68d-11eb-814b-cff509be1070.png)
> 
> Correct One:
> ![Screenshot_20210606_020724](https://user-images.githubusercontent.com/49529145/120914390-92c4ee00-c68d-11eb-9e01-26fa51bf8ec5.png)

I didn't run the mv command. I did that then copied the old file and that didn't work. I then deleted the file,  created the file again with nano and pasted the contains in and that worked. Thanks for your help.

**Comment by adriaandegroot** [comment]
## Before update

- downloaded KDE neon user edition 20210624
- tried install with:
  - manual partitioning
  - 300MiB /boot/efi FAT32
  - rest of disk / btrfs
- installation failed as described here

## After update

- fetched latest `main.py` for the mount module
- replaced the code in the VM image with the new version
- ran the same installation
- installation was successful; post-installation screenshot:

![image](https://user-images.githubusercontent.com/19431457/124754277-4f7acb00-df2a-11eb-9c19-a8e4b0534643.png)
