### ISSUE TITLE
Not so much of an issue but a question?

### ISSUE THREAD

**Issue by mrgreen3** [calamares/calamares#1683]
Am thinking of using calamares under ArchBang. Is it possible to run installer from a script? My plan is not to ship iso with all the deps but pull then in during a live session. Or even dare I say an online installer?

**Comment by kkofler** [comment]
Pulling in the installer during a live session is theoretically possible, **but** a lot of the dependencies are expected to be inside the installed chroot, which is normally rsynced from the base live image and not the RAM overlay, so the dependencies that you omit from the live image will be missing, unless you explicitly install them early in the process, e.g., using the `packages` module.

**Comment by adriaandegroot** [comment]
```
#! /bin/sh
sudo apt-get install calamares
sudo -E calamares
```
It's not really clear to me what you think to gain from this, though. (Maybe *pacman* instead of *apt-get*)

**Comment by mrgreen3** [comment]
Think it is more about keeping my iso size down. Currently at 1Gb. While I get that isos are no longer restricted in size (down mostly to cost of usbkeys). Downloading of a large iso file for some still takes quite a while. From my point of view it would be an ideal way to test under a VM rather than having to rebuild iso at every minor change.

**Comment by demmm** [comment]
>having to rebuild iso at every minor change.

Installing Calamares (and all depends) in a live session is not the issue. The ISO shipping with an older Boost or ICU (as examples) IS the issue, Calamares will fail to run then. Many times major updates will require a reboot.  Unless you can script a way of fully updating the live session, restarting the session, then installing and running Calamares will work.  But that will completely negate any benefit of a smaller ISO download, you will and up with more to download then just a larger ISO.

**Comment by kkofler** [comment]
> But that will completely negate any benefit of a smaller ISO download, you will and up with more to download then just a larger ISO.

Even if you don't have to upgrade any package, just install the additional ones, that is still the issue. There is no point in making the ISO smaller if all users will then end up downloading the size difference.

**Comment by mrgreen3** [comment]
Was merely bouncing idea in my head. Can clearly see from replies it not a viable option which is a real shame. Know that isos go stale very quickly, in the case of Archlinux a matter of days. Please forgive the noise ;-)

**Comment by adriaandegroot** [comment]
Maybe the thing you are **actually** looking for is not pulling in the installer over the internet, but pulling **the packages to install** over the internet. There's the *netinstall* module for that, and *packages*. That allows you to either run the installation with a fixed package list, or to fetch a package list and give the user some choice. Either way the version of the installer itself doesn't matter; it's what you end up putting on the system that does. See ArcoLinux for an example that heavily uses netinstall.

**Comment by mrgreen3** [comment]
Was thinking about about using pacman to pull in required deps rather than shipping iso with them. Provided it is not kernel related then it should work. Will read up on netinstall module. Do chat with guys from endeavour os, they may be able to give me some advice.  Have mulled over local or network installs over the years. They both have advantages and disadvantages. 

Thanks again for your time and help ;-)
