### ISSUE TITLE
Theme issues: black text on a black background

### ISSUE THREAD

**Issue by TROMsite** [calamares/calamares#1685]
I am creating a custom spin of Manjaro and we have a custom theme for Calamares (branding). However with the latest Calamares updates I see the text has a darkish color on a darkish background 
![image](https://user-images.githubusercontent.com/38043315/116824243-7a8f1a00-ab89-11eb-99f4-905885045e36.png)
The weird part is that it is so when not in focus/active. But if I click the window and drag it, the text is as the theme (branding) tells it to be (lighter). I cannot seem to be able to fix this.
![image](https://user-images.githubusercontent.com/38043315/116824316-ccd03b00-ab89-11eb-9df5-168b1fdbafec.png)

I tried removing all of our branding. Everything. Plus change the default theme of the OS. Nothing makes it better. Is this an isolated problem?

**Comment by adriaandegroot** [comment]
In your `stylesheet.qss`,
```
#mainText { color: green; background-color: red; }
```
That won't fit your theme *at all*, but it might show that the stylesheet is being applied correctly. If you're not setting a stylesheet, what does your (desktop) theme say about colors?

If you've got an ISO link to experiment with, I can try to figure out where the specific colors are coming from.

**Comment by TROMsite** [comment]
That only changes to main text and not the description text unfortunately. I am testing with this ISO https://www.drive.tromsite.com/s/ZR6gXgrEzt8t4eP

But it might be an issue with the ISO and its settings since I see the same issue with some other QT applications. However if you can quickly have a look, would be great.

**Comment by adriaandegroot** [comment]
There's multiple QLabels in there:
- `#mainText`
- an anonymous one that is the first child of *ResultsListWidget*
- more anonymous ones that are children of *ResultWidget*

You'll need to style all of them, e.g.

```
#mainText, .ResultsListWidget > .QLabel, .ResultWidget > .QLabel { color: red; background: green; }
```

If you want the explanation to be styled differently from the text explaining each individual check, then you'll need to split that up a bit -- I leave that to your CSS skills. That said, these are annoying (when unnamed), so I'll put in some meaningful names as well.

**Comment by TROMsite** [comment]
I managed to fix that by fixing some QT styles that were not properly loaded... Calamares should provide a more simple way to customize it, so we know what selectors there are.
