### ISSUE TITLE
HELP!!!!

### ISSUE THREAD

**Issue by Doctor-Sauce28980** [calamares/calamares#1690]
I downloaded the calamares-3.2.39.3.tar.gz file. I don't know the first thing about Linux, so I thought I would start with this. I don't know what to do next. Do I move the file somewhere? Do I restart the computer? what do I do? Is this the right place to submit this?

**Comment by kkofler** [comment]
> I don't know the first thing about Linux, so I thought I would start with this.

Uh, no, sorry. If you don't know anything about Linux, the source code (which has to be compiled before it can do anything) of a generic installer framework (which has to be tuned for the specific distribution by the distribution packager) is most definitely not the right download to start with.

You have to choose a [(GNU/)Linux distribution](https://en.wikipedia.org/wiki/Linux_distribution) and download the ISO for the distribution of your choice. It will come with a ready-to-use installer, which, depending on the distribution, may or may not be based on Calamares. In case you wish to use Calamares specifically, [this list](https://calamares.io/about/#who-ships-calamares) lists the distributions known to include Calamares.
