### ISSUE TITLE
Change calamares title

### ISSUE THREAD

**Issue by azharrafif5** [calamares/calamares#1691]
Hello, im need a help for changing calamares installer title

i have tried to change the "calamares.desktop" section but it doesn't work

And i need help for change default filesystem label in disk
and custom grub name

**I hope anyone can help, pleasee**

**Comment by azharrafif5** [comment]
then how to replace it

**Comment by adriaandegroot** [comment]
All of these strings come from `branding.desc`:

1. Is *productName* ; it always has "Installer" added in installer-mode, and "Setup Program" in OEM-mode. If you really want to change also the string added to the product name, you'll need to mess with the translation files. You can use substitutions in the value for *productName*, see comments / documentation in `branding.desc`.
2. Is *versionedName*, which is put inside a sentence ("welcome to the *versioned-name* installer"). Same comments apply.
3. Is *shortVersionedName*.

**Comment by azharrafif5** [comment]
Thanks for help
