### ISSUE TITLE
Update (push) French translation please

### ISSUE THREAD

**Issue by roxfr** [calamares/calamares#1693]
Hi,
I just updated the French translation of "Calamares" to 100% on Transifex.
Could you update (push) the translation, please.
Thank you.
Regards,
Roxfr

![image](https://user-images.githubusercontent.com/52124613/118294943-907ed200-b4db-11eb-8984-125b852d48a6.png)

**Comment by adriaandegroot** [comment]
It will take until a next release to arrive at the users, but I've pulled the translations into the Calamares code. Merci a vous pour traduire Calamares.
