### ISSUE TITLE
Only memtest 86+

### ISSUE THREAD

**Issue by azharrafif5** [calamares/calamares#1695]
After installing os using calamares grub bootloader only show memtest86+
my custom os not show on grub

![VirtualBox_Cala Test Ubuntu_15_05_2021_18_54_42](https://user-images.githubusercontent.com/75826509/118361000-90ea9c00-b5b3-11eb-9ae8-6019ea79f2a1.png)

please help for my OS

**Comment by demmm** [comment]
Make sure to use the ISSUE_TEMPLATE, second time asked.  As you have noted before, these kind of reports will be closed. Without logs & distro settings, no-one can help you.

**Comment by azharrafif5** [comment]
I use default bootloader config

# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Bootloader configuration. The bootloader is installed to allow
# the system to start (and pick one of the installed operating
# systems to run).
---
# Define which bootloader you want to use for EFI installations
# Possible options are 'grub', 'sb-shim' and 'systemd-boot'.
efiBootLoader: "grub"

# systemd-boot configuration files settings, set kernel and initramfs file names
# and amount of time before default selection boots
kernel: "/vmlinuz-linux"
img: "/initramfs-linux.img"
fallback: "/initramfs-linux-fallback.img"
timeout: "10"

# Optionally set the menu entry name and kernel name to use in systemd-boot.
# If not specified here, these settings will be taken from branding.desc.
#
# bootloaderEntryName: "Generic GNU/Linux"
# kernelLine: ", with Stable-Kernel"
# fallbackKernelLine:  ", with Stable-Kernel (fallback initramfs)"

# GRUB 2 binary names and boot directory
# Some distributions (e.g. Fedora) use grub2-* (resp. /boot/grub2/) names.
# These names are also used when using sb-shim, since that needs some
# GRUB functionality (notably grub-probe) to work. As needed, you may use
# complete paths like `/usr/bin/efibootmgr` for the executables.
#
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

# Optionally set the bootloader ID to use for EFI. This is passed to
# grub-install --bootloader-id.
#
# If not set here, the value from bootloaderEntryName from branding.desc
# is used, with problematic characters (space and slash) replaced.
#
# The ID is also used as a directory name within the EFI environment,
# and the bootloader is copied from /boot/efi/EFI/<dirname>/ . When
# setting the option here, keep in mind that the name is sanitized
# (problematic characters, see above, are replaced).
#
# efiBootloaderId: "dirname"

# Optionally install a copy of the GRUB EFI bootloader as the EFI
# fallback loader (either bootia32.efi or bootx64.efi depending on
# the system). This may be needed on certain systems (Intel DH87MC
# seems to be the only one). If you set this to false, take care
# to add another module to optionally install the fallback on those
# boards that need it.
installEFIFallback: true

**Comment by azharrafif5** [comment]
hello please help meee

**Comment by azharrafif5** [comment]
i use default settings of calamares bootloader module

**Comment by demmm** [comment]
Issue reports are for reporting bugs or feature requests, it is not a help channel.
If you encountered a bug, full log (installation.log), full settings used (post relevant .conf of modules you are reporting) are needed and expected.
If you need help working with Calamares for your distribution, go to the IRC or Telegram channel for Calamares.
Closing now, feel free to reopen if you can point to a real bug, with asked for documentation.
