### ISSUE TITLE
Error in services-systemd@services-systemd

### ISSUE THREAD

**Issue by azharrafif5** [calamares/calamares#1698]
The first time I tried installing with calamares there were no errors

But the second time I tried to build my OS again this happened

![VirtualBox_Cala Test Ubuntu_21_05_2021_07_45_06](https://user-images.githubusercontent.com/75826509/119079965-6d947680-ba23-11eb-9e88-48b986fdbfcd.png)

How to fix it and is this a bug

**Comment by azharrafif5** [comment]
Is this a bug or not

please help mee

**Comment by azharrafif5** [comment]
My operating system based on arch linux

**Comment by adriaandegroot** [comment]
It's telling you that the *services-systemd* module can not be loaded. You put it in `settings.conf` in the *sequence*, so it's up to you to configure the module it correctly. Have you looked at the log file (`~/.cache/calamares/session.log`, usually) ? What does it say? You will find more information there. Maybe the module isn't even installed. Maybe Python modules are not enabled.

(It's cool to see the installer running with *Bahasa Indonesia* ; you might want to double-check the translations, though, since it's only about 70% complete)

**Comment by azharrafif5** [comment]
Reply for (Sangat menyenangkan melihat penginstal berjalan dengan Bahasa Indonesia ; Anda mungkin ingin memeriksa ulang terjemahannya, karena ini hanya sekitar 70% selesai)

Because Im from Indonesia

**Comment by azharrafif5** [comment]
Reply for (It's cool to see the installer running with Bahasa Indonesia ; you might want to double-check the translations, though, since it's only about 70% complete)

Because Im from Indonesia

**Comment by azharrafif5** [comment]
services-systemd is already in settings.conf but still fails

**Comment by adriaandegroot** [comment]
I'll say it again: look in the **log file**. It's there to help you. You can get more information in the log file by running Calamares with the `-D` flag (e.g. `-D6`). Calamares will print to standard output, too, so I'll spell it out for you:

- Start a terminal; I can see one on your launcher bar.
- Type `calamares -D6` and hit enter.
- If you get an error message (`calamares: command not found` or something like that) you will need to go looking for the right command or the right path to give it. I can not guess what your distro is like.
- If you do not get an error message, Calamares will print startup information to the terminal. The GUI will be displayed. Then output on the terminal will stop, when the error message that you have already seen, is displayed. Look at the output on the terminal.

The last few lines of output might look like this:

```
10:49:23 [1]: void Calamares::ModuleManager::loadModules()
    ERROR: Module "unpackfsc@unpackfsc" not found in module search paths. 
     "/usr/home/adridg/src/git/calamares/build/src/modules" 
     "/usr/local/lib/calamares/modules" 
10:49:23 [1]: void CalamaresApplication::initFailed(const QStringList &)
    ERROR: STARTUP: failed modules are ("unpackfsc@unpackfsc") 
```

Start debugging with the information you get there: look in the module search paths for *services-systemd*.

**Comment by azharrafif5** [comment]
No, thank you
I've fixed it
