### ISSUE TITLE
Show the disk encryption configuration in a separated screen

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#1699]
**Is your feature request related to a problem? Please describe.**
This screen is too cluttered:
<img src="https://user-images.githubusercontent.com/84561213/120093189-e87a2300-c0ee-11eb-88c2-2a53b3c27e1b.png" width="400"/>

Also, in this screen there is the dropdown menu for configuring swap partition. It shows up in distros like Manjaro.

**Describe the solution you'd like**
By showing the disk encryption in a separated screen, this would help:

- To reduce clutter;
- To provide more screen space to put a text explaining for the end-user more about the encryption and to [put the future option to not encrypt /boot](https://github.com/calamares/calamares/issues/1311);
- To have more space for putting a message informing the user when the passwords don't match. Currently, there is just space to put a warning icon (also, there is an inconsistency with this, because in the user creation, the message "password don't match" is shown and this doesn't happen in the installation options screen). The warning icon is too subjective.

**Describe alternatives you've considered**
N/A

**Additional context**
It looks too busy here:
<img src="https://user-images.githubusercontent.com/84561213/119216175-77ac8880-baa8-11eb-8213-d569b6604793.png" width="500"/>

[Ubuntu new installer mockup](https://github.com/canonical/ubuntu-desktop-installer) is a great example of how this could be done:
<img src="https://user-images.githubusercontent.com/84561213/120063284-c6c06380-c03c-11eb-9ed0-7bbd915d5a8c.png" width="500"/>

Next to the /boot encryption option, there could be a warning icon to open a tooltip, explaining why enable this option or not, like in [this mockup](https://github.com/calamares/calamares/issues/1711) I did):
![Screenshot_20210530_025852](https://user-images.githubusercontent.com/84561213/120093798-0184d300-c0f3-11eb-8928-9b3abf9a7dd3.png)

**See also**
https://github.com/calamares/calamares/issues/1710
https://github.com/calamares/calamares/issues/1711

**Comment by demmm** [comment]
This probably best referred to for partitionq:
https://github.com/calamares/calamares/issues/1954
Once that module is ready, anyone can create a partition page layout just as they like.
