### ISSUE TITLE
Disk names are truncated in the disk dropdown menu 

### ISSUE THREAD

**Issue by lyrebird-sound-cloning-system** [calamares/calamares#1700]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (I was using a VM in BIOS mode, I kinda forgot of this happens when UEFI is enabled):
1. Go to the "partitions section";
2. Open the disk dropdown menu.

**Expected behavior**
The dropdown menu to be a little bigger, so the disks names don't get truncated.

**Screenshots and Logs**
![Screenshot_20210522_030445](https://user-images.githubusercontent.com/84561213/119216510-7c723c00-baaa-11eb-85ae-93d486809da0.png)

**Additional context**
Version: 3.2.39.3
OS: KDE Neon 5.21.5 (Ubuntu 20.04)

**Comment by adriaandegroot** [comment]
The width of the collapsed combo-box is based on the **small** icon, but when it folds out it shows the big icon. That's probably a delegate / item model thing to chase.

**Comment by lyrebird-sound-cloning-system** [comment]
The big disk icon could be reduced.
