### ISSUE TITLE
If the user do manual partitioning and choose GPT, Calamares will still warn the user to switch to GPT

### ISSUE THREAD

**Issue by lyrebird-sound-cloning-system** [calamares/calamares#1701]
**Describe the bug**

**To Reproduce**
1. Create a manual partition scheme with GPT partition table;
2. Press next.

**Expected behavior**
The message telling to switch to GPT shouldn't appear if the user already had chosen GPT.

**Screenshots and Logs**

https://user-images.githubusercontent.com/84561213/119216831-58175f00-baac-11eb-809b-0bd569b7f6c6.mp4

**Additional context**
Version: 3.2.39.3
OS: KDE Neon 5.21.5 (Ubuntu 20.04)

**Comment by adriaandegroot** [comment]
That sounds fixable (and annoying, if you're doing installations regularly)

**Comment by adriaandegroot** [comment]
- requires a *BIOS* machine (e.g. one that would default to MBR); it took me a while to spot that and I was wondering why I was getting totally different messages
- the message pops up **every** time you leave the partitioning page, even if the requirements are met

**Comment by lyrebird-sound-cloning-system** [comment]
>     * requires a _BIOS_ machine (e.g. one that would default to MBR); it took me a while to spot that and I was wondering why I was getting totally different messages

Whoops, I forgot to mention that I was using MBR (in a VM).

>     * the message pops up **every** time you leave the partitioning page, even if the requirements are met

Yeah.

**Comment by lyrebird-sound-cloning-system** [comment]
Welcome o/
