### ISSUE TITLE
boost.python error in job fstab

### ISSUE THREAD

**Issue by azharrafif5** [calamares/calamares#1702]
Heyy, I need a help again 
for the third time i built my OS again i got another problem in calamares installer

![VirtualBox_Cala Test Ubuntu_22_05_2021_20_01_31](https://user-images.githubusercontent.com/75826509/119227605-edf8cb80-bb38-11eb-9bc5-c6562df10ee5.png)

maybe this is the last problem i got

**Comment by adriaandegroot** [comment]
You are either missing `fstab.conf` or are missing the *mountOptions* key in that file. The *mountOptions* key is required.
