### ISSUE TITLE
Rename "[distro name] installer" to "Install [distro name]"

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#1709]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
"Install [distro name]" creates more friendliness. Pop_OS! and macOS  installers have this way of displaying the window name ([Ubuntu new installer](https://github.com/canonical/ubuntu-desktop-installer/issues/42) will have this too)

**Describe alternatives you've considered**
N/A

**Additional context**
![1_language-cropped](https://user-images.githubusercontent.com/84561213/120063078-cf646a00-c03b-11eb-8c3e-ab1d4ebd39bf.png)
![macOSSierraInstallProgress-57d83d083df78c58337484b4](https://user-images.githubusercontent.com/84561213/120063128-0fc3e800-c03c-11eb-9f37-5dc8b4e88c09.jpg)

**Comment by kkofler** [comment]
IMHO, the window title should be the name of the application, not a verb.

"Install FooOS" might make sense on the icon (though even that would be an abuse of the `.desktop` file `Name=` key, but at least it would make sense there to have an action verb on what is effectively an action button), and that is up to the distro to set up (and some, like Fedora and Kannolo, already use such an icon name), but in the window title, it just does not make any sense to me.

**Comment by demmm** [comment]
To be sure this is known, there already is an option to use an alternate naming:
https://github.com/calamares/calamares/blob/calamares/src/branding/default/branding.desc#L19

**Comment by adriaandegroot** [comment]
The setting @demmm refers to changes the wording in the welcome message, not the window title (here with bogus product names and random colors from debugging stylesheet issues some time in the past). Headers refer to the value of *welcomeStyleCalamares* in the branding file.

### true
![image](https://user-images.githubusercontent.com/19431457/120205602-6c84f580-c22a-11eb-8009-7c308e4d625c.png)

### false
![image](https://user-images.githubusercontent.com/19431457/120205669-845c7980-c22a-11eb-84c7-570fbfde6053.png)


There's another knob, though, and that's *oem-setup* in `settings.conf`, which changes Calamares from an "installer" to a "setup program". That does change the window title -- and also a lot of other strings in the application. It still sticks to "*distro* Setup Program" as title, though.

The relevant code (naming the top-level window) is in `CalamaresWindow.cpp` with the knobs-code in `Branding.cpp`. I can imagine yet-another knob in branding to switch between noun-ish window titles (like now, which @kkofler describes, and which certainly make sense for regular applications) and verb-ish window titles (as proposed here). It doesn't tangle up too much code (just the window title with some extra ifs). A different aproach would set the window title from a string in the branding file itself (but that raises minor complications with translations, although there's plenty of infrastructure for that now in Calamares). Yet another approach would just **not** set the window title within Calamares itself and rely on the automatic title setting (e.g. process name) or Qt's `--title` argument to set it to something arbitrary (with more complications).

**Comment by adriaandegroot** [comment]
[[ closing with "insufficient traction, OP is gone" ]]
