### ISSUE TITLE
Don't show the disk consumption bars in the Partitions screen

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#1710]
**Is your feature request related to a problem? Please describe.**
This screen is too cluttered:
<img src="https://user-images.githubusercontent.com/84561213/120093189-e87a2300-c0ee-11eb-88c2-2a53b3c27e1b.png" width="400"/>

Also, in this screen there is the dropdown menu for configuring swap partition. It shows up in distros like Manjaro.

**Describe the solution you'd like**
There is already the Summary screen to show the "before and after":
<img src="https://user-images.githubusercontent.com/84561213/120063925-06d51580-c040-11eb-8acc-4247b58eccae.png" wifth="400">

It seems that some distros don't show the Summary screen, like KDE Neon. I think this screen should be mandatory in case the disk consumption bars get removed in the Partitions screen.

**Describe alternatives you've considered**
N/A

**Additional context**

Ubuntu showing the disk consumption bars only when doing manual partitioning:
<img src="https://user-images.githubusercontent.com/84561213/120063520-e0ae7600-c03d-11eb-916c-2d2b388247e2.png" width="400"/>

**Fixing other problems**
This change would also help to fix this problem (reducing the clutter in this screen would make the bootloader dropdown menu more noticeable):
https://github.com/calamares/calamares/issues/1662

**See also**
https://github.com/calamares/calamares/issues/1699

**Comment by abucodonosor** [comment]
I disagree with you.

But let me start with what 'others are doing'.. completely irrelevant.

To see 'what is NOW' and 'AFTER' before hitting 'NEXT' has the advantage to change mistakes before is too late.

Can that be redesigned? Probably, but not removed.

**Comment by lyrebird-sound-cloning-system** [comment]
But isn't redundant since there is the Summary screen?

**Comment by abucodonosor** [comment]
There is a summary, sure and the user sees what is done, but having it visualized is different, and some
understand better what will be changed to their current setup.

**Comment by demmm** [comment]
This probably best referred to for partitionq:
https://github.com/calamares/calamares/issues/1954
Once that module is ready, anyone can create a partition page layout just as they like.

**Comment by adriaandegroot** [comment]
Closing feature-request issues that don't get acted on inside a year (I think this might be a neat feature, but it needs some volunteer to step up and do the actual work).
