### ISSUE TITLE
Can’t install any distro with Calamares, other installers work fine

### ISSUE THREAD

**Issue by gityosha** [calamares/calamares#1715]
HI there, thanks for the software and community. The following is adapted from a post to the Manjaro forum because that is the distro i most wanted to install. I got not help there and as you will see it appears to be a Calamares issue, so i'm trying here for the first time.

I have a newish Lenovo Ideapad5 laptop  with Intel 11th gen chipset (which has been giving me a lot of hardware recognition issues, which may or may not be related to the current problem).

**I’m not able to install any distro that uses Calamares as the installer.**

Manjaro gives this error on trying to boot after seemingly successful installation:
ERROR: device ‘UUID=[where root is, i checked]’ not found. Skipping fs ck. mount: /new_root: can’t find ‘UUID=[where root is]’. You are now being dropped into an emergency shell. sh: can’t access tty; job control turned off. 

I tried 2 distros based on Manjaro. I get the identical error with Mabox, and Garuda stalls almost immediately on the first splash screen, so that could be the same issue.

Other distros using Calamares give other problems, various failures to install at all, boot at all, etc. One distro couldn’t even see the unallocated space to install to…

Meanwhile i’ve had no problem installing every distro i tried that didn’t use Calamares, such as Ubuntu, Mint, Fedora, as well as (i don't have my notes in front of me) i believe opensuse/gecko leap. To be clear: some distros had problems at the liveusb/etc level recognizing my hardware etc, so i didn't try to install them; but every distro that seemed to basically work, that i did try to install, if it used Calamares it wouldn't work, and if it didn't it did.

I performed all these installations the same way: dual booting with Win10 by editing the Win10 boot partition to include the boot/efi/ mount point with boot flag, and creating from unallocated space a single ext4 partition as root for the linux distro with root flag. And i tried other things along the way such as an additional linux boot partition, telling Calamares what to do in different orders, etc, nothing worked. I’ve looked at forums and watched videos, checked my UEFI settings after various people’s advice, nothing relevant (legacy mode, secure boot, fast boot, RAID, LVM, etc etc). It just seemed to come down to whether i’m using Calamares or not.

Please note that i am a long-time end user but not a programmer or linux expert. I'm happy to try suggestions that are relatively simple, but i'm not going to do elaborate CLI work; i would instead just use a distro that works for me. I'm writing both in the hopes of getting Manjaro to work, and even if not to give you some hopefully useful feedback.

Any help would be much appreciated; thanks again for everything,
gityosha

**Comment by demmm** [comment]
Best would be to post the installation.log from (several) of the failed attempts. But wrong UUID points to an issue of changed boot drives/wrong drive used in fstab. So posting the `/etc/fstab` of a failing install will be needed too.

**Comment by gityosha** [comment]
Could you please tell me specifically how to do that? Thank you!

**Comment by philmmanjaro** [comment]
You may want to start **Calamares** in debug mode and post the terminal output to a pastebin or attach a file here:

`sudo -E calamares -d`

**Comment by demmm** [comment]
>Could you please tell me specifically how to do that?

That depends on the distro you are using, some will automate the debug file for you, some will require that you start manually in debug mode. IF you tried KaOS, it will be automated, the log will be in `/var/log/installation.log` of the installed system, and in live mode (while doing the install) it will be in the live user home directory.
https://kaosx.us/docs/#info-to-provide-for-installation-issues

**Comment by adriaandegroot** [comment]
Closing as "feedback timeout". It'd be keen to have a section like KaOS has on providing useful information when reporting installation problems, in the Calamares website, but I'm not up to writing that right now. (The "wrong UUID" still seems familiar as a problem, though -- but we'd hear much more about that from Manjaro if it was pervasive).
