### ISSUE TITLE
Calamares crashes when the user do manual partitioning in a PC with BIOS mode

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#1723]
**Describe the bug**
Calamares crashes when attempting to install the bootloader in a disk that doesn't have a /boot partition.

**To Reproduce**
Create a partition for / (I use an encrypted partition in this case), one for bios_grub. Also, I tried to create a separated partition for /boot, but it didn't work.

**Expected behavior**
Calamares should install the system or not install it if this isn't possible.

**Screenshots and Logs**
![Screenshot_Neon_2021-06-09_15:58:50](https://user-images.githubusercontent.com/84561213/121413046-ad23f380-c93b-11eb-8bb6-d2575c685c2d.png)

**Additional context**
OS: KDE Neon 5.22
Calamares version: 3.2.39.3

**Comment by demmm** [comment]
Manual partioning is meant for users who know what they are doing. Next, there are warnings NOT to set up the way as is shown here, thus the install SHOULD fail (as the error shows, this is not a crash, but a fail to install with a faulty setup).

**Comment by lyrebird-sound-cloning-system** [comment]
What is exactly the error? The same thing happens when setting up a separated /boot partition. Also, I do the same partitioning scheme (with the exception of the bios_grub partition) and the installer doesn't crash.

**Comment by kkofler** [comment]
One big `/` actually works if it is not encrypted, at least it did last I checked. IIRC, there were also attempts to fix the issues with one big encrypted `/`.

The error message looks like GRUB did not detect the BIOS Boot partition that you claim you did actually set up, so maybe a missing flag (should be the `boot` flag, I think)?

**Comment by adriaandegroot** [comment]
This issue deserves a longer conversation -- I **do** see KCrash in the screenshot there, which is really peculiar, alongside a regular error display from the *bootloader* module which is GRUB complaining about a footcannon situation. If anything, Calamares might warn about "you have BIOS and GRUB but no suitable *bios_boot* partition".

However, OP is gone and the issue dangles; closing with "feedback timeout".
