### ISSUE TITLE
Calamares adding incorrect flags during manual partitioning on /boot/efi partition

### ISSUE THREAD

**Issue by adb-haknor** [calamares/calamares#1724]
**Describe the bug**
Creating a FAT32, /boot/efi partition with "boot" flag on Calamares manual partitioning makes Calamares to change the flags to generic wrong flags like legacy_boot and msftdata instead of boot and esp as it did in the past, making the system not bootable nor recognisable after the distro install.

Tested on a 64-bits machine/UEFI-only environment.

**To Reproduce**
1. Go to manual partitioning on Calamares;
2. Create firstly a /boot/efi partition, format it as FAT32, with 512 MiB and flag as "boot" (esp flag has been removed, unfortunately);
3. Create / (root) partition, format it as EXT4, put the size you want and flag as "root";
4. Create /home partition, format it as EXT4, put the size you want and no flags;
5. Complete the installation process;
6. Remove usb stick and reboot;
7. Now it doesn't boot.

**Expected behavior**
The expected behaviour is that the installation process ended and booted the system normally, but it doesn't happen.

**Screenshots and Logs**
It's not possible for me to add screenshots of the boot process. After all, it doesn't show no error messages, it just doesn't boot, goes to a black screen and goes back to BIOS UEFI setup as you were trying to boot into no system.
I've some partitions [screenshots](https://imgur.com/a/Jq8k6xQ) I've taken during my 15 attempts to install Manjaro KDE unsuccessfully. At first, I thought the issue was only related to Manjaro, but after testing Kubuntu and KDE Neon I noticed the same buggy behaviour.

**Additional context**
Again, the same issue happened on KDE Neon, Manjaro and Kubuntu. Firstly, I thought the issue was related to the removal of "esp" flag, but since I've read, "boot" now works as "esp" on UEFI-systems, so there is no need to flag it as esp anymore. However, Calamares seems to not put correctly the flags to /boot/efi partitions makes it undetectable by the system, so it doesn't boot as /boot/esp isn't treated nor recognised as a bootable partition

**OFF: My additional mitigation**
The way I've found out to boot the system properly was using the same live-usb key I used before to install the distro to check the installed partitions. I've used GParted (since I'm more used to) and installed it through the live-usb environment. Then, I removed the wrong flags added by Calamares, that were legacy_boot and msftdata and put both boot and esp instead. After doing that, the system boot normally.
The issue happens on a full UEFI environment with AHCI and GPT.
In the automatic partitioning this problem doesn't apply, only applies to the manual partitioning.

**Comment by adriaandegroot** [comment]
In summary:
- using **manuall** partitioning, on a UEFI system, with GPT partition table (check that?),
- setting the *boot* flag on the `/boot/efi` partition,
- does not actually set the *boot* flag in the partition that gets created.

Which Calamares version (or Manjaro, or KDE neon version, for that matter) are you using?

**Comment by adb-haknor** [comment]
> 
> 
> In summary:
> 
>     * using **manuall** partitioning, on a UEFI system, with GPT partition table (check that?),
Yes, I've used [GPT Partition Table](https://imgur.com/a/f5T9mNQ)

>     * setting the _boot_ flag on the `/boot/efi` partition,
Yes, I did it. If I don't put any flag on /boot/efi [the installation won't proceed](https://imgur.com/a/Qoqx5wq).

>     * does not actually set the _boot_ flag in the partition that gets created.
Yes, the installer doesn't set the correct flag. It keeps adding legacy_boot and msftdata. **However, I noticed if only msftdata is added, it at least can boot**, but with the addition of legacy_boot, it doesn't boot. If you remove both legacy_boot and msftdata and add only boot and esp, it also does boot. When I used to install Manjaro and KDE Neon, it always did that, boot and flag for /boot/efi partition. For some reason, it doesn't happen anymore.
>
> Which Calamares version (or Manjaro, or KDE neon version, for that matter) are you using?
>

I'm actually trying to install Manjaro, so Calamares version is 3.2.39.3-1.3. [Other Plasma infos might help you out](https://imgur.com/a/vEWXtPZ)

**Comment by killajoe** [comment]
I can confirm this from the latest EndeavourOS ISO.
1. manual partition set flag on ESP to `boot` results in  `msftdata` flag
2. automatic partition set the flag right and will be shown as `boot`
Checked autput from gparted/cdfdisk/fdisk/kpmcore

Calamares: 3.2.39.3
kpmcore: 20.12.3-1

Link to ISO:
https://github.com/endeavouros-team/ISO/releases/download/1-EndeavourOS-ISO-releases-archive/endeavouros-2021.04.17-x86_64.iso
![msftdata](https://user-images.githubusercontent.com/16797647/121804017-718f6f00-cc44-11eb-9a76-6fabdb368cc5.png)

But it is not preventing the system from booting up... and we do not have reports from users say it causes issues.

**Comment by adb-haknor** [comment]
> 
> 
> I can confirm this from the latest EndeavourOS ISO.
> 
>     1. manual partition set flag on ESP to `boot` results in  `msftdata` flag
> 
>     2. automatic partition set the flag right and will be shown as `boot`
>        Checked autput from gparted/cdfdisk/fdisk/kpmcore
> 

> But it is not preventing the system from booting up... and we do not have reports from users say it causes issues.

Good to know it's not only me, but in my specific case, for some unknown reason it still adds the flag legacy_boot that makes it not bootable. In the past, when "esp" flag was available as a flag in Calamares, I always added boot and esp for /boot/efi partition and in the end, it kept this way. It's very strange the fact it changes the flags after install.

A lot of people are not having issues with this specific partition probably because they are only using automatic installation. In my case, I needed to use the manual partitioning because I need to separate /home from /. I haven't also created a specific partition for swap because I would create a swapfile with the size I wanted. Manual partitioning was never a problem for me, neither with Calamares, Ubiquity or any other installer. It just started to be a problem recently.

**Comment by kkofler** [comment]
I would suspect a regression in KPMCore. @stikonas?

**Comment by stikonas** [comment]
> I would suspect a regression in KPMCore. @stikonas?

Unlikely. There were not changes in flag management recently. So my suspicion would be partitioning module of Calamares. What is strange to me is that Calamares seems to be showing MBR flags for GPT partition table.

**Comment by adb-haknor** [comment]
Guys, I've noticed another strange behaviour regarding the flags.

Today, I installed KDE Neon (User Edition) twice instead of Manjaro, just as a test. [First time](https://imgur.com/a/nUh0w4e), it booted (it hasn't set both legacy_boot and msftdata as it did on Manjaro this week), unfortunately, the bad news it is still set the msftdata instead of boot and esp. The good news is that it was at least bootable. I'm not sure if using msftdata will create any issues over time, but something else happened other than this... The / partition was set as legacy_boot instead of root and I don't know why. I've selected only "root" as a flag for /.
So, [for the second time](https://imgur.com/a/QNQTzdH), I installed KDE Neon, doing all the same except this time I didn't set any flag for /, and it hasn't added any weird flag (which is good, isn't?). That's why I said it's generic, it sets generic flags, especially MBR-related ones to the partitions, this time / was affected instead of /boot/efi. Both of them have booted after all, still with the wrong flags, but they've booted.
I've been testing this on a SSD.

> What is strange to me is that Calamares seems to be showing MBR flags for GPT partition table. @stikonas 

True. That's what I've noticed too.

**Comment by adriaandegroot** [comment]
What this really needs is someone to write a **painfully detailed** scenario. Which ISO, which version. What kind of machine. What is the HDD. What is the partitioning scheme on the HDD. BIOS or EFI? Take screenshots / photos of important steps. (Well, @killajoe has done a fairly good job and I can pick his brains via other channels if I have trouble reproducing this)

**Comment by abucodonosor** [comment]
> > I would suspect a regression in KPMCore. @stikonas?
> 
> Unlikely. There were not changes in flag management recently. So my suspicion would be partitioning module of Calamares. What is strange to me is that Calamares seems to be showing MBR flags for GPT partition table.

I can remember you fixed that one a while ago ( I believe we discussed that flags mess on IRC the time you switched to sfdisk ).

I don't remember exactly how the bug ( well for me it worked with msftdata set too just looked weird ) was triggered in calamares.
I think if you partitioned with old code, the used new kpmcore, some check about the active flag didn't work, but I may be completely wrong here.

Anyway off-topic for this one but looking at src/plugins/sfdisk/sfdiskpartitiontable.cpp, there are still some strange things?:)

```
{ FileSystem::Type::Fat12, { QLatin1String("EBD0A0A2-B9E5-4433-87C0-68B6B72699C7"), QLatin1String("6") } },
{ FileSystem::Type::Fat16, { QLatin1String("EBD0A0A2-B9E5-4433-87C0-68B6B72699C7"), QLatin1String("6") } },

```
So Fat12 is set to Fat16? Fat12 should be 01 

```
{ FileSystem::Type::Fat32, { QLatin1String("EBD0A0A2-B9E5-4433-87C0-68B6B72699C7"), QLatin1String("c") } },

```

That is not exactly plain Fat32, but Fat32 LBA, Fat32 is 0b.

**Comment by stikonas** [comment]
> > > I would suspect a regression in KPMCore. @stikonas?
> > 
> > 
> > Unlikely. There were not changes in flag management recently. So my suspicion would be partitioning module of Calamares. What is strange to me is that Calamares seems to be showing MBR flags for GPT partition table.
> 
> I can remember you fixed that one a while ago ( I believe we discussed that flags mess on IRC the time you switched to sfdisk ).
> 
> I don't remember exactly how the bug ( well for me it worked with msftdata set too just looked weird ) was triggered in calamares.
> I think if you partitioned with old code, the used new kpmcore, some check about the active flag didn't work, but I may be completely wrong here.
> 
> Anyway off-topic for this one but looking at src/plugins/sfdisk/sfdiskpartitiontable.cpp, there are still some strange things?:)
> 
> ```
> { FileSystem::Type::Fat12, { QLatin1String("EBD0A0A2-B9E5-4433-87C0-68B6B72699C7"), QLatin1String("6") } },
> { FileSystem::Type::Fat16, { QLatin1String("EBD0A0A2-B9E5-4433-87C0-68B6B72699C7"), QLatin1String("6") } },
> ```
> 
> So Fat12 is set to Fat16? Fat12 should be 01
> 
> ```
> { FileSystem::Type::Fat32, { QLatin1String("EBD0A0A2-B9E5-4433-87C0-68B6B72699C7"), QLatin1String("c") } },
> ```
> 
> That is not exactly plain Fat32, but Fat32 LBA, Fat32 is 0b.

Do you want to make a merge request to kpmcore :) ? Although I don't believe that will fix this issue but still good to have.

**Comment by killajoe** [comment]
someone checked if the gui may simply have something folded wrong?
Like it takes msftdata anyway independent from what you choose from dropdown?

**Comment by stikonas** [comment]
> someone checked if the gui may simply have something folded wrong?
> Like it takes msftdata anyway independent from what you choose from dropdown?

Unlikely. Anyway, there is no such thing as msfdata in GPT. It's just partition type set to either FAT32 or ESP (which should be controlled by boot flag).

**Comment by marghill** [comment]
I can confirm the issue since I'm having basically the same problem and I was about to create a bug request until I realize this one has been already created. In my case Calamares is setting `legacy_boot` for EFI and `msftdata` for /.

I really don't know why this happens.

I'll be watching this.

**Comment by killajoe** [comment]
> > someone checked if the gui may simply have something folded wrong?
> > Like it takes msftdata anyway independent from what you choose from dropdown?
> 
> Unlikely. Anyway, there is no such thing as msfdata in GPT. It's just partition type set to either FAT32 or ESP (which should be controlled by boot flag).

but still seems that calamares does not set any flag there

**Comment by demmm** [comment]
I cannot reproduce with kpmcore 21.04.1, Calamares 3.2.40rc, link to ISO used for testing:
https://sourceforge.net/projects/kaos-test/files/iso/KaOS-2021.06.14-x86_64.iso

Screenshot of options set:
![Screenshot_20210616_170159](https://user-images.githubusercontent.com/5360485/122247212-7ca60180-cec7-11eb-8505-02a9bdb611f6.png)
Summary shot:
![Screenshot_20210616_170307](https://user-images.githubusercontent.com/5360485/122247340-8fb8d180-cec7-11eb-93a3-d4070c57a8c8.png)
Fstab of the target system, after the install completed:
![Screenshot_20210616_170858](https://user-images.githubusercontent.com/5360485/122247492-aa8b4600-cec7-11eb-8344-8b7957807013.png)
Partitionmanager of installed system:
![Screenshot_20210616_171023](https://user-images.githubusercontent.com/5360485/122247587-c0007000-cec7-11eb-8296-1f058baa5c9c.png)

System boots without errors, or labels & flags are assigned correctly.

**Comment by killajoe** [comment]
with kpmcore 21.04.1 and calamares 3.2.39 i see the same here as with the older kpmcore i show before it does not have boot/esp flag and shows msftdata // archlinux archiso // so something changed on calamares after last release in that area ?

**Comment by adb-haknor** [comment]
I've created the same partitions as you @killajoe and it keeps changing the flags for me, it happens in different distributions (I haven't tested it though virtual manager though). I needed again to use the live-usb to check the partitions since it doesn't boot at all.

I didn't test on KaOS yet, but on Manjaro and other Debian or Ubuntu-based distributions.

![](https://i.imgur.com/02HsfBS.png)

![](https://i.imgur.com/z6arWlB.png)

It stills insists on setting legacy_boot and msftdata.

**Comment by adb-haknor** [comment]
> I can confirm the issue since I'm having basically the same problem and I was about to create a bug request until I realize this one has been already created. In my case Calamares is setting `legacy_boot` for EFI and `msftdata` for /.

For me it sets both legacy_boot and msftdata to /boot/efi and legacy_boot to / (root).
Even if it's formated as xls.
Yesterday it was set msftdata for /boot/efi making it bootable. It seems to be changing all the time the flag it adds after different installations with the same or similar partition scheme which is weird as hell.

**Comment by philmmanjaro** [comment]
So we may need to check which versions of **Calamares** are affected and which version of **KPMCore** is used. Also a list of known affected distros would be nice. Since @demmm reported her current linked ISO doesn't have that issue, you guys should test that one also. So we see what needs to be changed on other distributions to make it properly work again.

**Comment by adriaandegroot** [comment]
## Scenario

> This uses the EndeavourOS ISO mentioned in comment 4, testing on my local workstation in VirtualBox

- start with a 16GB disk, first 128MB zeroed out
- click start the installer, pick *offline*
- click through to partitioning; notice system is labeled "EFI" and partition table "unknown"
- choose manual partitioning
- new partition table, gpt
- create, 500MiB, fat32, /boot/efi
- flags shown include "bios-grub", "boot", ... "lba", "legacy-boot", select **only** the "boot" flag.
- create another partition, remainder of disk, ext4, no flags
- click next; there are no warnings, click through to "summary" page
- notice it says "flag 500MiB partition as boot", but in the debug output in the terminal window, I see a blank type, uuid, and attrs is 0 (this may not be a problem)
- do the installation; there's some output about the partitions, now with a non-blank uuid (see link to log, below)
- immediately after, parted shows `/dev/sda1` with flags msftdata (which I didn't ask for). Going through gparted and managing flags on `/dev/sda1` shows me a list of flags including bios_grub, boot, esp,, legacy-boot and msftdata. The msftdata flag is set.

So, yeah: totally confirmed. 

Log at https://termbin.com/e9n6

**Comment by adriaandegroot** [comment]
I'm building some older Calamareses now (which goes slowly in this particular VM). I can see what's going wrong
- a new partition is created
- flags are to be set, **but**
- by the time the *SetPartFlagsJob* (in Calamares) actually happens, the internal administration says that the partition has the same flags **already active** as that need to be set; in KPMCore the (different) *SetPartFlagsJob* that does the actual work wants to **toggle** flags from the current (active) state to the desired state. Since active = desired already, nothing is done.

So the problem lives somewhere in Calamares which is seems to be setting the active flags on a partition, before they are really set by KPMCore.

**Comment by adb-haknor** [comment]
Good to know it's not something related only to my system, but a general problem with Calamares and KPMCore. Anything I can help, just ask me. Unfortunately, I'm not a developer but I'll do my best to help.
