### ISSUE TITLE
[Help Request]

### ISSUE THREAD

**Issue by aravallios** [calamares/calamares#1727]
Can anyone help me how to create a custom calamares config

**Comment by erikdubois** [comment]
Check out the tutorials we have on 

https://alci.online
and
https://arcolinuxiso.com

**Comment by demmm** [comment]
Issues are for reporting bugs/problems/issues with Calamares, or add a feature request, as was shown to you with the ISSUE_TEMPLATE when opening this.
It is NOT a help channel. For help, please use IRC as linked on the website:
https://calamares.io/
https://calamares.io/about/
Follow the links there for all kinds of WIki pages of how to use Calamares, if something is not clear then, use IRC, many are there to help you.
