### ISSUE TITLE
Add memory available to partitioning module

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1728]
Would it be possible to add the memory a system has to this page?

As such users can decide - this computer has enough RAM -  and go for an installation without swap.

When jumping from machine to machine this would help to check how much was in this one again and base your decision on that.

I suppose you calculate the hibernate space on the basis of the memory + 10% more or less so I am hoping this parameter is in there somewhere and we only need to show it on the screen.

Ps. it should be clear that it is memory and not harddisk space - no confusion needed

see example image

![memory](https://user-images.githubusercontent.com/36679406/122685030-653d8000-d209-11eb-9843-8bd8ebd5df50.png)

**Comment by adriaandegroot** [comment]
This pushes in the opposite direction that #1710 and #1711 , which try to **un**clutter the page. Perhaps a button / pop-up / tool-tip for system information that is relevant here, which would collect BIOS / MBR / memory and everything would help.

However, the size of the swap file is **already** visible; I'm not sure what you gain by putting some other value on-screen that indirectly influences the size of the swap partition, when the swap partition can be examined directly.

**Comment by arcolinuxz** [comment]
I need to make a decision on that page as a user  
use no swap
use a small swap
use a big swap

I would decide that on the basis of the size of my memory.
As I jump from computer to computer there is a chance I do not remember again how much was in this one.
Is there a way to show the amount of memory in the computer so I have a basis to decide what swap choice is best for this computer.

**Comment by carbon-ui** [comment]
the filesystem one was merged it is there now in arcolinux and other distros
putting that memory one would be a good choice but with changed font and color
and swapfile?
