### ISSUE TITLE
Please allow adding a second keyboard layout

### ISSUE THREAD

**Issue by omeritzics** [calamares/calamares#1730]
**Is your feature request related to a problem? Please describe.**
As there are many writing systems, and the need for writing in English, most of the users cannot use only one keyboard layout.

**Describe the solution you'd like**
Please add an option to add a second (or even third) keyboard layout, and an option to choose the keyboard shortcut to switch between the keyboard layouts.

**Describe alternatives you've considered**
You can also configure Calamares to automatically add the English International keyboard layout for languages written in other writing systems.

**Comment by adriaandegroot** [comment]
This is mostly outside of the scope of Calamares, though -- in the live session, and in the target session, Calamares doesn't know about shortcuts or how to configure multiple layouts (for KDE Plasma, or XFCE, or GNOME, or ..). What it **does** know about is layouts-that-need-an-English-layout too. See #1642 for instance. There's a table of layouts that need that in `src/modules/keyboard/non-ascii-layouts`, pull requests to add layouts are very welcome.

**Comment by omeritzics** [comment]
Thank you. Hope to open a pull request soon.
