### ISSUE TITLE
Boot loader location selection is forgotten and goes back to default

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1743]
ArcoLinux
Calamares 3.2.40

The video explains and shows what happens if the users changes something to the filesystem dropdown or the swap dropdown. The bottom selection of the boot loader location goes back to the default in this case sda. We made a specific selection so that it is sdb by default.
Calamares switches it back - so loses the selection of the user

https://youtu.be/GHuDBpcwmPQ?t=1118

**Comment by adriaandegroot** [comment]
Duplicate of #1662
