### ISSUE TITLE
Calamares setting wrong password during install

### ISSUE THREAD

**Issue by arnav7633** [calamares/calamares#1745]
1. 

> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
Hi i am installing my own OS on my pc with 2 other operating systems installed a windows and a arch based distro, After installing my distro i reboot and find out that the password specified in the user setup page doesn't work, the username is fine but the password isn't

**To Reproduce**
1. Bootup
2. Install the system
3. Enter the password set during installation

**Expected behavior**
I should get logged into my system with the password set

**Comment by demmm** [comment]
To be able to help, make sure to follow instructions from:
https://calamares.io/issues/
What is the OS?  Installation log?  Possible link to ISO? How to reproduce? Keyboard layout used during the install?

**Comment by arnav7633** [comment]
Its my custom arch based OS and yes i do have the iso on mega , the keboard should be fine as i cross checked using the unhide option both during setting and unlocking the system

This iso - https://mega.nz/file/zuZ10IQb#AvB5FQ1WUDrC-eWtDFvLIEm464WPo8KtKenGkQhKkvU
The profile - https://mega.nz/file/fqJnlQhT#VDqQRk1oGcmZW9BoD7fysUn3uWUeo_RG0UIzxxBSoaY

**Comment by arnav7633** [comment]
I don't have a a calamares folder in .cache
Here is everything I could copy from the terminal
https://sourceb.in/7UfEt26dKG

**Comment by demmm** [comment]
From the log, it looks like you set a generic, `en` (variant is empty) keyboard and have a password set for user and root account.  Does the password fail for both user and root?

**Comment by arnav7633** [comment]
i set the same pass for root, i only got the option for the user on the login screen i tried clicking another user and entered root as username and the pass, same error

**Comment by arnav7633** [comment]
I got into tty and tried for both root and user both say incorrect :(

**Comment by arnav7633** [comment]
@demmm Does my profile look alright? I hope its not a issue at my end

**Comment by ezsit55** [comment]
Since @arnav7633 appears to be using my Ezarcher build system to construct their Arch based system, I need to add that my Ezarcher produced ISO that use Calamares for an installer do not experience this password setting problem. Any problems with setting the passwords during the Calamares installation of Vishwas Linux must be a direct result of the creator modifying my Ezarcher build process and causing the passwords to not be set correctly.

**Comment by arnav7633** [comment]
Um ok? i didn't blame you did i ?

Fix - Check your login shell for me it was a corrupted fish package
