### ISSUE TITLE
Website: Typos in welcome screenshot (RTL)

### ISSUE THREAD

**Issue by tomer** [calamares/calamares#1751]
The main webpage is featuring some screenshots of the tool. One of them is featuring KaOS Installer Welcome Page. Unfortunately the graphic is featuring reversed text for RTL languages, which make it feels broken in RTL languages, although it is just graphic.

URL: https://calamares.io/images/2020/kaos_welcome.png
![image](https://user-images.githubusercontent.com/50206/129461929-34d81f51-d892-4e48-9c43-57e736561174.png)

a. **The Hebrew word for Hello is שלום** (Shalom), not םולש. As it is written top-down, it is expected to read by turning the head to the left, not to the right as with LTR languages such as English. 
b. There is a **Yiddish translation for Hello as העלא** in Google Translate (the screenshot has אלעה), but I suspect it is not widely used by Yiddish speakers. 
c. **Arabic word سلام (Salam) is reversed as well**. @yarons Please verify me. 

**To Reproduce**
1. Go to https://calamares.io
2. Scroll down to the screenshot section
3. Click on the third image.

**Expected behavior**
A professional screenshot should not contain invalid translations.

**Comment by tomer** [comment]
I see that the image in `src/branding/default/languages.png` doesn't featuring these languages, but the KaOS branding has them. It might be a bug in KaOS installer as well, but I don't think you should feature typos in the project websites. 
https://github.com/calamares/calamares/blob/calamares/src/branding/default/languages.png
https://github.com/KaOSx/calamares/blob/master/src/branding/kaos_branding/languages.png

**Comment by demmm** [comment]
Images will be updated shortly, some shown for KaOS are outdated anyway.  Welcome image won't be used then (issue will be closed once the new images are up).
