### ISSUE TITLE
Networkcfg copies live user with file copy

### ISSUE THREAD

**Issue by demmm** [calamares/calamares#1754]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
As reported a few times over the years (IRC, telegram), the networkcfg module is not functional, file is copied when present, but on restarting newly installed system, new wifi credentials need to be added.

Issue is now found, not fixed yet in the module.
The .nmconection file that is copied contains a line for the user, thus it contains whatever name a distro uses for the live system, example KaOS line:
```
permissions=user:live:;
```
When you edit that file (as root) and set it to current user of the installed system, wifi works right away on rebooting into the newly installed system.
networkcfg/main.py will need some lines added to copy the correct target user.

**Comment by philmmanjaro** [comment]
In other words: we have to replace those lines with `permissions=user:$loginName:;` of which `$loginName` gets replaced by the actual target user.

**Comment by demmm** [comment]
Start of a fix:
```
    root_mount_point = libcalamares.globalstorage.value("rootMountPoint")
    user = libcalamares.globalstorage.value("username")

    if root_mount_point is None:
        libcalamares.utils.warning("rootMountPoint is empty, {!s}".format(root_mount_point))
        return (_("Configuration Error"),
                _("No root mount point is given for <pre>{!s}</pre> to use." ).format("networkcfg"))

    source_nm = "/etc/NetworkManager/system-connections/"
    target_nm = os.path.join(
        root_mount_point, "etc/NetworkManager/system-connections/"
        )

    # Sanity checks.  We don't want to do anything if a network
    # configuration already exists on the target
    if os.path.exists(source_nm) and os.path.exists(target_nm):
        for network in os.listdir(source_nm):
            # Skip LTSP live
            if network == "LTSP":
                continue

            source_network = os.path.join(source_nm, network)
            target_network = os.path.join(target_nm, network)

            if os.path.exists(target_network):
                continue

            try:
                shutil.copy(source_network, target_network, follow_symlinks=False)
                if 'live' in open(target_network).read():
                    text = []
                    with open(target_network, "r") as network_conf:
                        text = network_conf.readlines()
                        with open(target_network, "w") as network_conf:
                            for line in text:
                                if 'permissions=user:live:;' in line:
                                    line = 'permissions=user:{}:;\n'.format(user)
                                network_conf.write(line)
                    network_conf.close()
```

Line 2 added, then the last 10 lines added, `live` user hardcoded for now

**Comment by philmmanjaro** [comment]
I rather would check for `if 'permissions=` line and replace that regardless of the user used in live-session. Some like this:

```
                if 'permissions' in open(target_network).read():
                    text = []
                    with open(target_network, "r") as network_conf:
                        text = network_conf.readlines()
                        with open(target_network, "w") as network_conf:
                            for line in text:
                                if 'permissions=' in line:
                                    line = 'permissions=user:{}:;\n'.format(user)
                                network_conf.write(line)
                    network_conf.close()
```

I also assume the first if routine might not be needed as we would replace the permissions line anyway, if any ...
