### ISSUE TITLE
Layout default should be English for locales with no Latin letters (preferably add a secondary layout with the other locale)

### ISSUE THREAD

**Issue by feature-engineer** [calamares/calamares#1760]
**Is your feature request related to a problem? Please describe.**
Currently, the installer determines my geographic location, and sets the default keyboard layout accordingly - which would sound like the smart thing to do - but it’s actually not the right choice for anyone with no Latin characters in their keyboard layout, as it’s impossible to use the terminal with these layouts. 

**Describe the solution you'd like**
The default layout should always be English.
The smarter thing to do would be to automatically add the local layout as a secondary layout (and inform the user of the switch keys combo), or let the user define their multilingual keyboard layout.

**Describe alternatives you've considered**
Let users add several keyboard layouts, determine which one is default and select their switching shortcuts - although I think this may over-complicate the installation process. - it could be hidden behind a "Advanced layout management" button.

**Comment by killajoe** [comment]
also the installer is detecting a default setting, it shows still the slide where you can choose layout and language for your keyboard manually and let you test it.

> The default layout should always be English.

Would cause the same issue for the users where it is common to have non `en` layout...

It would be possible to disable the location detection the same as it would be if you install offline with no internet connection, there user will have `en` selected and has the option to change.

So the only way would be indeed the possibility to select more than one and have a switcher added .. but this is not something calamares should do and will be on the Distribution to add.

**Comment by feature-engineer** [comment]
How about a dictionary of locale -> default layout? This way the locales that benefit from autodetection still get it, and the ones that it's detrimental to would default to the layout which would enable writing Latin chars...

**Comment by kkofler** [comment]
Calamares already has a list of non-Latin layouts, for which a dual layout (the local layout + the US English one) is automatically set up. (The switching key combo is the xkb default.)

**Comment by feature-engineer** [comment]
If so, Hebrew should be added to that list. It doesn't happen for it.

**Comment by feature-engineer** [comment]
Should I open a bug report for it?

**Comment by feature-engineer** [comment]
Correct me if I'm wrong, but adding this behaviour for Hebrew would simply entail adding one line in `src/modules/keyboard/non-ascii-layouts` :  `he        us                  -                    il-heb`
