### ISSUE TITLE
Manual partition shows wrong error message

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1761]
**Choosing manual partition give wrong error message if EFI partition is to small**

**To Reproduce**
1. using EndeavourOS latest ISO with calamares 3.2.41 
2. choosing manual partitioning the drive 
3. create a new partition table in gpt
4. create EFI partition smaller then 300MB (fat32 boot flag)
5. add systempartiton..
6. after click next an error message shows up that says "No EFI system partition configured"
7. Log says WARNING: FAT32 filesystem is to small

![2021-08-23_23-21](https://user-images.githubusercontent.com/16797647/130523754-7ec44478-1f87-44ce-a17e-43838c86cfa2.png)

8. Also the error clicking OK and proceed with install went fine. 

How should this be ?
the error should say that partition is too small, or should not show up at all. 

Anyway, where is the minimum size set in configs? I would like to set it to a smaller size simply to avoid the error showing up.

**Comment by kkofler** [comment]
The minimum size for FAT32 is defined by the FAT32 file system specification. I assume that the installation then proceeds with a FAT16 or FAT12 EFI System Partition, which many UEFI firmwares will actually let you get away with, but which is not guaranteed to work according to the UEFI specification.

**Comment by killajoe** [comment]
![2021-08-24_02-30](https://user-images.githubusercontent.com/16797647/130536833-2cf033c3-0511-426c-856e-6cea32a1ed12.png)

https://itectec.com/superuser/the-absolute-minimum-size-a-uefi-partition-can-be/

Also, it is limited the shown error is misleading, if it would say _**size too small please increase the size of the EFI partition**_ it would be all good, but the current error text will confuse the user and mostly let you think something is not working or gone wrong.

**Comment by demmm** [comment]
https://github.com/calamares/calamares/blob/calamares/src/modules/partition/partition.conf#L13

**Comment by killajoe** [comment]
![2021-08-24_11-22](https://user-images.githubusercontent.com/16797647/130591910-d7badf8f-5162-4385-9c16-7a282a6e30cf.png)
This is triple booting using 420KB in size ;) would be fine using 50M partition here .. 
But as i say the issue here is mainly the wrong Error message also KPM-core is detecting that there is EFI Partition and also FAT32 warns that size is too small Calamares give a false Message what is confusing and wrong.
![2021-08-24_11-24](https://user-images.githubusercontent.com/16797647/130592832-db6f36fc-0525-4e9d-b656-4bf1ea7b2715.png)
![2021-08-24_11-26](https://user-images.githubusercontent.com/16797647/130592834-66a1d251-b718-47c5-a639-30445e27544b.png)

**Comment by killajoe** [comment]
> System partition
> 
> The device must contain a system partition. On GPT drives, this is known as the EFI System Partition, or the ESP. This partition is usually stored on the primary hard drive. The device boots to this partition.
> 
> The minimum size of this partition is 100 MB, and must be formatted using the FAT32 file format.
> 
> This partition is managed by the operating system, and should not contain any other files, including Windows RE tools.
> 
> Note
> 
> For Advanced Format 4K Native drives (4-KB-per-sector) drives, the minimum size is 260 MB, due to a limitation of the FAT32 file format. The minimum partition size of FAT32 drives is calculated as sector size (4KB) x 65527 = 256 MB.
> 
> Advanced Format 512e drives are not affected by this limitation, because their emulated sector size is 512 bytes. 512 bytes x 65527 = 32 MB, which is less than the 100 MB minimum size for this partition.


https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions#system-partition

**Comment by killajoe** [comment]
Thanks! @adriaandegroot
