### ISSUE TITLE
Fix a typo in a documentation header

### ISSUE THREAD

**Issue by elfring** [calamares/calamares#1764]
[The documentation](https://calamares.io/issues/#developers-of-distrubutions "Distribution developers") contains the following information at the moment.

“…
Developers of Distrubutions
…”

I suggest to use the word “Distributions” instead.

**Comment by carbon-ui** [comment]
@elfring please dont file bug report for such small things
you have irc matrix
please tell there

**Comment by elfring** [comment]
Thanks for [your small documentation improvement](https://github.com/calamares/calamares.github.io/commit/317e791d1022bf708e8cf4c6c1bcc6de10f7336c "spelling correction").
