### ISSUE TITLE
Add a test case for the determination of writable storage devices

### ISSUE THREAD

**Issue by elfring** [calamares/calamares#1767]
# Objective
[The function “PartUtils::getDevices”](https://github.com/calamares/calamares/blob/b54b486ee8bf7969982720c36a0063bc5720747c/src/modules/partition/core/DeviceList.cpp#L111 "Implementation of PartUtils::getDevices()") is called within [the implementation of the function “PartitionCoreModule::doInit”](https://github.com/calamares/calamares/blob/56ecf01dea93b9a4405cf302af4439ebcd5c59d1/src/modules/partition/core/PartitionCoreModule.cpp#L249 "Implementation of PartitionCoreModule::doInit()").
Such functionality should become usable also for another test case.

# Requirements
## User profile
Some users would like to [check the run time characteristics for such a general operation](https://github.com/calamares/calamares/issues/1752 "Installation tool is waiting for the partition module for a while.").

## Facilitator
This test can be performed on demand without using a graphical user interface.

**Comment by adriaandegroot** [comment]
`./partitiondevicestest`
