### ISSUE TITLE
Unable to boot Debian 11 after fresh installation with encrypted disk

### ISSUE THREAD

**Issue by rusio** [calamares/calamares#1768]
When disk encryption is used, the Calamares-based installation of a pristine Debian 11 stable distribution, is not bootable after the installation process completes.

**Steps to Reproduce**

- Use a "live" image flavor of the Debian distribution, which uses Calamares, found below, select the Gnome-Variant:
https://cdimage.debian.org/cdimage/release/current-live/amd64/bt-hybrid/
- In the disk partitioning dialog, choose to erase everything and to encrypt the disk.
- Wait for the installation to complete and reboot.

Now you should see an empty boot menu and booting the OS is not possible.

Update: Same procedure same symptoms with a current Manjaro Distribution:
https://manjaro.org/downloads/official/gnome/

**Comment by carbon-ui** [comment]
log file @rusio ?

**Comment by rusio** [comment]
I believe the issue is BIOS-related and no log file is available. After some investigations, I observed an interesting behavior:

When I power-off my laptop (Lenovo ThinkPad X220) it prompts for the disk encryption passwphrase and starts booting the OS, after a couple of seconds thinking.

But if I just reboot the OS without powering off, it displays a native startup menu, instead of the encryption password prompt. I believe this startup menu has nothing to do with Calamares but is something built-in in the BIOS firmware of the laptop.

I just updated the BIOS firmware, but the same weird behavior is observable. Fiddling with various BIOS settings like UEFI or legacy mode does not help much. 

I am just wondering why this startup menu never appeared while using Ubuntu 16. Pbobably, because Calamares uses an encrypted /boot partition by default and Ubuntu didn't encrypt it back then?

I will report any fufther findings.

**Comment by demmm** [comment]
>because Calamares uses an encrypted /boot partition by default

Calamares doesn't "use" any by default, that is all decided by your distribution. 
These kind of bug reports should go to your distribution first, they can much better decide if it is a setting they used, or if it is a general Calamares issue.
There is no way of knowing how the ISO you used was created, nor is it possible to debug any without those settings and log files.
https://calamares.io/issues/
https://calamares.io/issues/#end-users

**Comment by rusio** [comment]
Thank you for the clarification. I guess this false issue could be closed then.

**Comment by demmm** [comment]
It can be closed now, feel free to re-open if after working with Debian, it is decided it is a general Calamares issue.
