### ISSUE TITLE
India's default layout shouldn't be Hindi Inscript, but Indian English

### ISSUE THREAD

**Issue by subins2000** [calamares/calamares#1769]
**Describe the bug**
Related to #1284 

The default Indian keyboard layout is Hindi Inscript. It should be `English (India, with ruppee)`.

OS: neon-user-20210826-0945.iso
Calamares version: 3.2.41.1

**To Reproduce**
1. In Welcome tab, chose "American English" as installer language 
2. In the next Location tab, chose "Asia" region with "Kolkata" as zone.
3. The Keyboard tab chose Indian->Default as keyboard which is Hindi Inscript layout

![telegram-cloud-photo-size-5-6132017971091058077-y](https://user-images.githubusercontent.com/2305675/130435221-58ac6028-143b-4d7b-8c0d-fc143638377a.jpg)

**Expected behavior**
Should choose Indian English layout.

**Additional context**
If I choose "Malayalam" at the beginning of installer language, then the keyboard chosen is Indian English which is correct. Should it be Malayalam Inscript is a whole another question.

But Hindi Inscript shouldn't be the layout of "Default". It should be `English (India, with ruppee)`.

![Screenshot_20210901_164523](https://user-images.githubusercontent.com/2305675/131662123-683433ba-4a93-41a0-b145-c94988015a98.png)

**Comment by adriaandegroot** [comment]
It's dependent on .. on **something** in the host system, because on my FreeBSD development machine, it ends up with `en_US` layout every time regardless of language or locale:

```
00:04:25 [6]: void Config::setLocaleIndex(int)
    Index 37 Selected locale QLocale(Malayalam, Malayalam, India) 
    ..  Branding no translation for "ml_IN" using default (en) 
    ..  No translation for "tz_" "ml_IN" using default (en) 
    ..  Loaded QRC translation "calamares_" "ml_IN" 
    ..  No translation for "kb_" "ml_IN" using default (en) 
00:04:34 [6]: void Config::guessLocaleKeyboardLayout()
    Got locale language "en_US.UTF-8" 
    ..  extracted country "United States" :: ("en", "US") 
    ..  looking for locale part "US" 
    ..  matched "us" 
```

So I'll have to look at this one in a VM.

**Comment by adriaandegroot** [comment]
(tested with a KaOS VM, not neon, but it picks the right one from the list now)
