### ISSUE TITLE
Prior Btrfs partition, Erase disk, new F2FS root installation, filesystem still "Btrfs"

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#1771]
Hi everyone, here's a weird one: for my GeckoLinux spins based on openSUSE Tumbleweed I'm considering enabling support for F2FS in the Calamares "Erase disk" filesystem options menu. It works fine on a new VM with a blank virtual disk. (8GB disk, msdos partition table, legacy VirtualBox BIOS mode). However, if I previously installed to a Btrfs root on `/dev/sda1` and then reboot and install again with F2FS, the installation completes but it still sees it as a Btrfs partition and it won't boot, GRUB2 works fine but during the boot process it says there is another filesystem on the root partition and dumps me onto a rescue console. I can however manually mount the filesystem with `mount -t f2fs /dev/sda1 /whatever` and it's valid.

![Screenshot_2021-09-03_16-17-31](https://user-images.githubusercontent.com/2692138/132067829-596db68c-3efb-4b2d-872e-7aa43d5169ed.png)

This is with Calamares 3.2.41.1 and KPMcore 21.08.

Here's the log from an installation where this happened: [calamares_log-D8.txt](https://github.com/calamares/calamares/files/7108614/calamares_log-D8.txt)

And the [partition.conf](https://github.com/calamares/calamares/files/7108623/partition.conf.txt)

**Comment by adriaandegroot** [comment]
I'll give you "strange" indeed. Maybe mkfs.F2FS is not fully erasing other metadata from the partition, so that it is recognized later as BTRFS?

**Comment by geckolinux** [comment]
Is this of any interest? (From line 202 on)

```
17:05:31 [6]: void ChoicePage::applyActionChoice(InstallChoice)
    Prev -1 InstallChoice Config::Erase "erase" 
17:05:31 [6]: CalamaresUtils::Partition::KPMManager::KPMManager()
    KPMManager 2 created. 
17:05:31 [6]: PartitionTable* CreatePartitionTableJob::createTable()
    CreatePartitionTableJob::createTable trying to make table for device "/dev/sda" 
17:05:31 [6]: CalamaresUtils::Partition::KPMManager::KPMManager()
    KPMManager 3 created. 
17:05:31 [6]: CalamaresUtils::Partition::KPMManager::KPMManager()
    KPMManager 4 created. 
17:05:32 [6]: void PartitionCoreModule::dumpQueue() const
    # Queue: 
    ..  ## Device: "VBOX HARDDISK" 
    ..  - "Create new msdos partition table on /dev/sda." 
    ..  - "Create new 8188MiB partition on /dev/sda (VBOX HARDDISK) with file system btrfs." 
    ..  - "Set flags on 8188MiB btrfs partition."

**Comment by geckolinux** [comment]
Pinging @philmmanjaro too.

I just tried the latest Manjaro, first a Btrfs installation onto a new 8GB VirtualBox disk, which booted successfully, and then another Calamares "Erase disk" with F2FS. It looks like the same problem, although in the case of Manjaro the 2nd installation failed at the mkinitcpio stage:

![Screenshot_2021-09-04_10-31-01](https://user-images.githubusercontent.com/2692138/132100241-3fa9d361-0f8a-489f-bbba-e3c56771821a.png)

![Screenshot_2021-09-04_10-33-50](https://user-images.githubusercontent.com/2692138/132100244-8b092ad6-07d2-4dd6-823c-e85920a924d3.png)

**Comment by demmm** [comment]
https://bugzilla.opensuse.org/show_bug.cgi?id=1109665#c0
Kernel older on the running machine older then target?

**Comment by geckolinux** [comment]
> Kernel older on the running machine older then target?

I read about that F2FS quirk, but no, that can't be the case because the failure happens on the 2nd attempt to install the same OS from the same ISO.

> tried manually running mkfs.f2fs on the target?

Good idea, I'll do that next. Fortunately this bug is easy to reproduce consistently.

**Comment by geckolinux** [comment]
Sorry for a mistake in my last report, the mkinitcpio failure in Manjaro was simply because the 8GB virtual disk was full. >:-/

But, this bug report still holds true. I started over with a fresh 16GB disk, installed Manjaro with Btrfs, then re-installed with F2FS, and it behaved the same as in GeckoLinux. The F2FS installation completes successfully but the system isn't bootable and it's still detected as Btrfs.

My next step will be to manually create the F2FS filesystem to see what happens.

**Comment by geckolinux** [comment]
![Screenshot_2021-09-05_13-14-00](https://user-images.githubusercontent.com/2692138/132137223-72abd306-f0ae-4e1b-a12f-3509e722a879.png)

[mkfs.f2fs_log.txt](https://github.com/calamares/calamares/files/7112129/mkfs.f2fs_log.txt)

**Comment by demmm** [comment]
So you are saying the -f option is missing in Calamares/kpmcore?

**Comment by philmmanjaro** [comment]
@geckolinux can you create a partition after formating it with **BTRFS** or any other format to **F2FS** with KDE's **Partitionmanager**?

**Comment by geckolinux** [comment]
@philmmanjaro Good idea. What happens is that KDE Partition Manager crashes, I reproduced it twice:

```
partitionmanager 
Loaded backend plugin:  "pmsfdiskbackendplugin"
"Using backend plugin: pmsfdiskbackendplugin (1)"
"Scanning devices..."
"Device found: VBOX HARDDISK"
getting smart status failed for  "/dev/sda" :  Success
error during smart output parsing for  "/dev/sda" :  Success
"Partition ‘/dev/sda1’ is not properly aligned (last sector: 16,771,859, modulo: 788)."
"Scan finished."
"Add operation: Create filesystem f2fs on partition ‘/dev/sda1’"
"Applying operations..."
Segmentation fault (core dumped)

**Comment by geckolinux** [comment]
Given what happened [here](https://user-images.githubusercontent.com/2692138/132137223-72abd306-f0ae-4e1b-a12f-3509e722a879.png) it looks more like an f2fs-tools bug doesn't it? Because even `mkfs.f2fs -f` still resulted in the partition appearing as "Btrfs".

**Comment by demmm** [comment]
Oh, so result is the same (images do not mention what is before or after), so that means it is not a Calamares or Kpmcore bug, but f2fs.  Best to keep this report open, so it can be pointed too, but needs to be reported to upstream f2fs.

**Comment by geckolinux** [comment]
Thanks @demmm . Do they have a separate bug tracker? Or would it be directly to kernel.org ? Or here?
https://sourceforge.net/p/linux-f2fs/mailman/linux-f2fs-devel

**Comment by demmm** [comment]
Seems here https://sourceforge.net/projects/f2fs-tools/

**Comment by geckolinux** [comment]
OK, here's the bug report:
https://sourceforge.net/p/linux-f2fs/mailman/linux-f2fs-devel/thread/75f47f9c-4587-9105-81bd-38708df8fab9%40gmail.com/#msg37347249

**Comment by adriaandegroot** [comment]
The bug report from @geckolinux has been received well upstream, so a future f2fs will probably overwrite the btrfs bits anyway .. but there might be other "first filesystem X, then filesystem Y" kinds of combinations that are problematic.

If there is a "remove filesystem X metadata" command that might be inserted into either kpmcore or Calamares, to wipe the relevant bits, then we can avoid that; I don't know if it is feasible, though, because you'd have to know about all variants of filesystem X and where it might store metadata. And you don't want to go arbitrarily writing huge chunks of zeroes to disk "just in case". 

@stikonas For *this* specific case though, we know that btrfs metadata lives at the 64k offset in the partition, so before -- or after, since the fs is still empty -- creating the f2fs, something like `dd if=/dev/zero of=/dev/sdb1 bs=1k seek=64 count=8` will do the trick (to write 8kiB of zeroes from block 64 onwards). See *Superblock* heading at https://btrfs.wiki.kernel.org/index.php/On-disk_Format

Anyway, I'm going to close this as "bug upstream" and just right now, let's hope not-many people switch from btrfs to f2fs on one disk without changing anything else.

**Comment by stikonas** [comment]
> The bug report from @geckolinux has been received well upstream, so a future f2fs will probably overwrite the btrfs bits anyway .. but there might be other "first filesystem X, then filesystem Y" kinds of combinations that are problematic.
> 
> If there is a "remove filesystem X metadata" command that might be inserted into either kpmcore or Calamares, to wipe the relevant bits, then we can avoid that; I don't know if it is feasible, though, because you'd have to know about all variants of filesystem X and where it might store metadata. And you don't want to go arbitrarily writing huge chunks of zeroes to disk "just in case".
> 
> @stikonas For _this_ specific case though, we know that btrfs metadata lives at the 64k offset in the partition, so before -- or after, since the fs is still empty -- creating the f2fs, something like `dd if=/dev/zero of=/dev/sdb1 bs=1k seek=64 count=8` will do the trick (to write 8kiB of zeroes from block 64 onwards). See _Superblock_ heading at https://btrfs.wiki.kernel.org/index.php/On-disk_Format
> 
> Anyway, I'm going to close this as "bug upstream" and just right now, let's hope not-many people switch from btrfs to f2fs on one disk without changing anything else.

https://invent.kde.org/system/kpmcore/-/blob/master/src/plugins/sfdisk/sfdiskpartitiontable.cpp#L118 ?

**Comment by adriaandegroot** [comment]
Calling `wipefs --all` like KPMCore does **does** wipe the relevant FS metadata (the debug output says what it's doing, and in case of f2fs-after-btrfs, mentions **two** metadata things that it wiped -- confirming what we've analysed here).
