### ISSUE TITLE
pacman -Sy does not prepare updates

### ISSUE THREAD

**Issue by carbon-ui** [calamares/calamares#1778]
**Describe the bug**
pacman -Sy bug

**Expected behavior**
package manager should prepare updates

**Additional context**
this bug is coming from many editions of calamares
![Screenshot_20210907_200210](https://user-images.githubusercontent.com/88924590/132363019-2553e661-1ff2-4094-8fd5-f925e98678bf.png)

**THIS IS A VERY IMPORTANT BUG TO BE RESOLVED**

**Comment by adriaandegroot** [comment]
Attach a log file .. or better yet, quote a relevant part of a log file. Do not just post screenshots of lengthy error messages.

As you can see from the screenshot, name resolution is failing when running `pacman -Sy`. That's not a Calamares problem *per se*: your target system isn't configured to resolve the names of your mirrors. Fix that.
