### ISSUE TITLE
New user is not using zsh

### ISSUE THREAD

**Issue by kazi-sifat-plus9a** [calamares/calamares#1779]
New user is not using zsh. However liveuser is using zsh. Is there any way to remove bash?
My shell process final :- www.paste.rs/N8w
My shell process before :- www.paste.rs/IOv
I am missing customize_airootfs.sh 😔

**Comment by demmm** [comment]
Please create useful bug reports:
https://calamares.io/issues/
No indication if this is a report for an end user, or if you are a distribution developer.
If end user, go to your distro and make sure to ask they use or provide zsh in their Calamares configuration.

**Comment by kazi-sifat-plus9a** [comment]
Sorry, i know this is not a bug... But i was just creating a custom arch iso.
I included zsh . I tried to move customize_airootfs.sh to shell process but it's not working as i expected. And i couldn't find any good way to solve it.

**Comment by demmm** [comment]
>Sorry, i know this is not a bug.

Issues are for bug reports and feature request, it is not a help channel.
Read the documentation created for you, to learn about the module system and edit the needed configuration files:
https://github.com/calamares/calamares/wiki/Deploy-Guide
In your case:
https://github.com/calamares/calamares/blob/calamares/src/modules/users/users.conf

If you still have questions after reading the wiki and learning about all the different .conf options, ask questions & discuss in Matrix or IRC.

**Comment by adriaandegroot** [comment]
The typical way to configure the user's shell in Calamares would be to use the setting in the *users* module, called *userShell*. You have a pair of shell scripts -- before and after -- that do various things. Looking at the shellprocess configurations you have, you are running them in the target system -- make them log something, or create log files in /tmp in the target. Then, you can do an install, **do not** reboot, and you can mount the target system and take a look at what happened.

If you really want to use a shell script, by all means do. You might want to pass in the username that was entered in Calamares, e.g. `@@USER@@` as a parameter to your shell script.
