### ISSUE TITLE
Allow packagechooser intro screenshot to be sourced from packagechooser.conf

### ISSUE THREAD

**Issue by demonkilleralg** [calamares/calamares#1784]
**Is your feature request related to a problem? Please describe.**
Currently, the default intro screenshot is hard-coded to "no-selection.png". 
https://github.com/calamares/calamares/blob/calamares/src/modules/packagechooser/Config.cpp#L90, 

`defaultIntroduction->screenshot = QPixmap( QStringLiteral( "./images/no-selection.png" ) );`

I think, we should be able to set this introductory image through packagechooser.conf.

**Comment by demmm** [comment]
Make sure to read the instructions provided for you in the specific .conf:
https://github.com/calamares/calamares/blob/calamares/src/modules/packagechooser/packagechooser.conf#L96
Either psecify a path to the screenshot you wish to use, or possibly, use an appstream XML file that has an image uncluded.

Not a new feature request, already existing & implemented, if you need an example:
https://github.com/KaOSx/calamares/blob/master/src/modules/packagechooser/packagechooser.conf#L160

**Comment by demonkilleralg** [comment]
I understand this and have implemented this as well. I am not talking about this at all. Maybe the title was wrong.
https://github.com/arch-linux-gui/alg-xfce-cala-config/blob/master/etc/calamares/modules/packagechooser.conf#L136

I am talking about this image: 
![image](https://user-images.githubusercontent.com/55846983/133292459-9f86e915-da0d-40dd-a181-cbdf856ee5d7.png)


That no-selection.png comes before the user has selected either of the options. I would like to change that.

**Comment by killajoe** [comment]
yes you need to have an empty id for using your one there like so:
https://raw.githubusercontent.com/endeavouros-team/calamares_config_next/08-2021/calamares/modules/packagechooser.conf
