### ISSUE TITLE
initcpiocfg overwrites MODULES: line instead of merging it

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1788]
If Distribution is changing mkinitcpio.conf MODULES line on host it is getting used by initcpiocfg module but it simply overwrites the line (at least for MODULES line) what removes modules added to the file. 

Calamares Version: 3.2.42
Distro Base: Archlinux

**To Reproduce**
1. have a custom MODULES line in /etc/mkinitcpio.conf on host
2. enable initcpio module in settings.conf
3. Target has an empty MODULES section in /etc/mkinitcpio.conf

**Expected behavior**
Calamares should merge existing values into target file.

**Screenshots and Logs**
No logs but testing it by adding a "hook" line into host mkinitcpio and validate that the file is used by calamares as the "hook" line is on target file.

May issue is here?
https://github.com/calamares/calamares/blob/calamares/src/modules/initcpiocfg/main.py#L83

**Comment by philmmanjaro** [comment]
The module was never designed to merge anything from the host **mkinitcpio.conf** file. It creates always a fresh now. Also you looked at the wrong line: https://github.com/calamares/calamares/blob/calamares/src/modules/initcpiocfg/main.py#L119

**Comment by demmm** [comment]
It does seem to read from the host, correct?
https://github.com/calamares/calamares/blob/calamares/src/modules/initcpiocfg/main.py#L73
So is this line not taken from the host?
https://github.com/calamares/calamares/blob/calamares/src/modules/initcpiocfg/main.py#L83

**Comment by adriaandegroot** [comment]
it reads, but discards the previous contents, like phil says (it's also in need of some python-style-love).

**Comment by adriaandegroot** [comment]
@killajoe it's not documented to append / merge / anything. I've just added a tiny bit of documentations (saying just that). I am, frankly, not so sure about how module merge would work; I mean, we can append the calculated values to the (three) lines that are applicable, but sometimes there's an order required for modules. How would that work? The whole file looks like it is most-likely just sourced by `mkinitcpio`, which means that you could use some stupid bash tricks to do the modifications in bash -- except that the replacement algorithm is pretty dumb.

Perhaps you can write up in more detail what you actually would like; I can imagine that a config file could be invented to (a) copy-and-modify-host-file or (b) use values from config, along with options to append or replace the calculated values. But that's a separate conversation to have.

**Comment by killajoe** [comment]
Thank's @adriaandegroot it was mainly me not understanding why the module was reading the host file without using it in any way, and it seems that stuff like the compression method will get used and is present on target. 

```
# COMPRESSION
# Use this to compress the initramfs image. By default, gzip compression
# is used. Use 'cat' to create an uncompressed image.
COMPRESSION="zstd"
#COMPRESSION="gzip"
```
But true it would need to have a logic to place the modules in the right order, in my case i was testing to add a module needed for some raid systems to work, and while testing stumble over this .. one can also sed/patch stuff in after calamares has done its magic and rerun mkinitcpio to get it active.
