### ISSUE TITLE
Ext4 As The Default Others As The Choice

### ISSUE THREAD

**Issue by MohammadHisham** [calamares/calamares#1789]
**Describe the solution you'd like**
so calamares is a wonderful installer
if you put the default filesystem as ext4 and a dropdown menu to put other file systems as the CHOICE then it can actually help

**Additional context**
This can just be taken as a small feature request

**Comment by demmm** [comment]
No mention of what version or which distro you are reporting about, but this has been implemented already.
https://github.com/calamares/calamares/pull/1667
https://github.com/calamares/calamares/commit/56ecf01dea93b9a4405cf302af4439ebcd5c59d1

**Comment by MohammadHisham** [comment]
@demmm but i am takling about the default in calamares
not each distro has filesystem choices

**Comment by demmm** [comment]
Understand what Calamares is, see the README for example:
https://github.com/calamares/calamares/blob/calamares/README.md
>Calamares is not a "ready to use" application: distributions apply a huge amount of customisation and configuration to Calamares, and the target audience for this repository is those distributions, and the people who make those Linux distro's.

The defaults are there as examples, many times commented out in the respective .conf, with extensive documentation what is possible and what can be done when activated. For this case:
https://github.com/calamares/calamares/blob/calamares/src/modules/partition/partition.conf#L153
