### ISSUE TITLE
contextualprocess module does not take name values?

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1790]
simple question no issue ;) 

using contextualprocess it shows only "job for contextual process is running" in progress output.

I do try to set:
```
i18n:
 name: "installing package list for chosen Community Edition..."
 name[de]: "Paketliste für ausgewählte Community Edition installieren..."
 name[fr]: "installation de la liste des packages pour l'édition communautaire choisie..."
```
in the config, but it seems to be ignored?
Do I have to use a different id instead of name?

as conf says:
```
# The values after a value sub-keys are the same kinds of values
# as can be given to the *script* key in the shellprocess module.
# See shellprocess.conf for documentation on valid values.
```
and in shellprocess.conf it would be the way to go:
https://github.com/calamares/calamares/blob/528a8153072dfb7892089abdb8206779ec5cfc34/src/modules/shellprocess/shellprocess.conf#L87

**Comment by adriaandegroot** [comment]
Which modules support *i18n* as a key (and how they interpret the sub-keys) is quite arbitrary. It would be useful to PR some consistency into that. The *contextualprocess* module does **not** support it. The reference to the *shellprocess* module is for the **script** part, not all of the keys.

**Comment by killajoe** [comment]
Thank`s to clear this!
