### ISSUE TITLE
TCG OPAL 2 encryption support?

### ISSUE THREAD

**Issue by EvilMav** [calamares/calamares#1791]
Modern SSDs are always encrypting, no matter if you set a password on or not. In some systems the password can be managed by the BIOS transparently for the OS, but many do not support it.

OPAL 2 specifies a different mechanism: a locked HDD is presenting a "shadow" EFI partition with a bootloader and minimal system that only shows a password prompt and uses it to unlock the drive(s). Then it reboots. An unlocked HDD then presents the usual setup and the shadow is hidden. The encryption is transparent for any OS from here on.

**Describe the solution you'd like**
  * Add an OPAL encryption mode as a choice in addition to LUKS.
  * Enable encryption and set password. (see quirks)
  * Setup a shadow partition. Distributions may choose to modify the reference implementation from [Drive-Trust-Alliance](https://github.com/Drive-Trust-Alliance) to add fancy graphics or whatever. 
  * Add some package to target distribution to unlock after suspend. [This](https://wiki.archlinux.org/title/Self-encrypting_drives#Waking_up_from_suspend) keeps the key in a systemd unit on the unlocked HDD, which is arguably not perfect but acceptable for many users.

**Quirks to consider**
  * New Samsung SSDs [need an initial PSID revert](https://github.com/Drive-Trust-Alliance/sedutil/issues/232) command to activate encryption. This is can lead to data loss if this command is executed a second time rather then first.

**Why consider OPAL in addition to LUKS?**
  * CPU decryption is redundant and likely has some power saving disadvantage for laptops.
  * Can encrypt other dual-boot OS 
  * LUKS will likely block any effort to bring DirectStorage-like capability to linux. This may become an issue for linux gaming in some years.

**Comment by adriaandegroot** [comment]
Let's suppose we were to make such support: what **specific** commands would have to be executed between "starting installation" and "create the partition table" to make this work?

**Comment by adriaandegroot** [comment]
Closing as "wishlist", "feedback-timeout".
