### ISSUE TITLE
Calamares unable to generate grub configuration file for dual boot system

### ISSUE THREAD

**Issue by BGG-Dev** [calamares/calamares#1792]
Bug description:
While installing Arco linux L on system with already installed and stable Sabayon linux (https://www.sabayon.org/) on it, Calamares installer could not generate grub configuration file.
System description: Intel core i5 8600k 4.5ghz, 16 Gb ram, Samsung 980 pro 512Gb is the only ssd/hdd on machine.
Final disk partition:
![image](https://user-images.githubusercontent.com/72020023/134812847-f857e6a2-8d79-4ce5-8556-679368f92808.png)

1. Install Sabayon linux with plasma
2. Start to install Arco linux L with Calamares
3. In "Partition" step, choose "Install alongside" option
4. Start installation process
5. Get error at the end

Expected behavior:
Machine with stable ArcoLinuxL and Sabayon linux in dual boot

Calamares log:
https://termbin.com/ws7uf

**Comment by demmm** [comment]
What option used for partitioning?  One of the automated or manual? What size was set for the EFI partition?  Since the fail occurs after trying to create a fallback image. First kernel image completed successfully:
```
Running "chroot" ("/tmp/calamares-root-iz51ueki", "grub-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=ArcoLinux", "--force") 
2021-09-26 - 16:12:12 [6]:     ..  Finished. Exit code: 0 output:
 Installing for x86_64-efi platform.
Installation finished. No error reported.
```

Error starts when `2021-09-26 - 16:12:12 [6]: [PYTHON JOB]: "UEFI Fallback: <unset>" 
2021-09-26 - 16:12:12 [6]: [PYTHON JOB]: "  .. installing 'bootx64.efi' fallback firmware" `

**Comment by BGG-Dev** [comment]
> What option used for partitioning?  One of the automated or manual? What size was set for the EFI partition?  Since the fail occurs after trying to create a fallback image. First kernel image completed successfully:
> ```
> Running "chroot" ("/tmp/calamares-root-iz51ueki", "grub-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=ArcoLinux", "--force") 
> 2021-09-26 - 16:12:12 [6]:     ..  Finished. Exit code: 0 output:
>  Installing for x86_64-efi platform.
> Installation finished. No error reported.
> ```
> 
> Error starts when `2021-09-26 - 16:12:12 [6]: [PYTHON JOB]: "UEFI Fallback: <unset>" 
> 2021-09-26 - 16:12:12 [6]: [PYTHON JOB]: "  .. installing 'bootx64.efi' fallback firmware" `
> 

EFI size: 300mb
For both distributions disk partition was done automatically.
For sabayon: "erace all" option
For arco: "install alongside" option

**Comment by demmm** [comment]
Can you check the space left on the EFI partiton (300 MB should be plenty, but trying to exclude it running out of space when trying to create the fallback image)?

**Comment by BGG-Dev** [comment]
> Can you check the space left on the EFI partiton (300 MB should be plenty, but trying to exclude it running out of space when trying to create the fallback image)?

GParted tells that only 1.02mb was used on fa32 boot partition

**Comment by demmm** [comment]
Repeated error shown is `error: cannot find a GRUB drive for /dev/sda1.  Check your device.map.`, and it seems your setup uses `/dev/nvme0n1p1` for EFI. Not clear to me why grub commands look for sda1.

**Comment by BGG-Dev** [comment]
> Repeated error shown is `error: cannot find a GRUB drive for /dev/sda1.  Check your device.map.`, and it seems your setup uses `/dev/nvme0n1p1` for EFI. Not clear to me why grub commands look for sda1.

Year, I don't use any ssd's exept my nvme in current machine

**Comment by BGG-Dev** [comment]
> Can you check the space left on the EFI partiton (300 MB should be plenty, but trying to exclude it running out of space when trying to create the fallback image)?

I tried to run instalation process again. First Sabayon, then Arch. But this time EFI size was 1000mb. Same error appeared. Here is the new log:
https://termbin.com/vtk7
