### ISSUE TITLE
modules/networkcfg/main.py 

### ISSUE THREAD

**Issue by coreylang** [calamares/calamares#1793]
File modules/networkcfg/main.py::replace_username() line 76  target_network undefined.

`
def replace_username(nm_config_filename, live_user, target_user):
    """
    If @p live_user isn't None, then go through the given
    file and replace @p live_user by the @p target_user.
    Reads the file, then (re-)writes it with new permissions lives.
    """
    # FIXME: Perhaps if live_user is None, we should just replace **all**
    #        permissions lines? After all, this is supposed to be a live
    #        system so **whatever** NM networks are configured, should be
    #        available to the new user.
    if live_user is None:
        return
    if not os.path.exists(nm_config_filename):
        return

    with open(target_network, "r") as network_conf:
        text = network_conf.readlines()

    live_permissions = 'permissions=user:{}:;'.format(live_user)
    target_permissions = 'permissions=user:{}:;\n'.format(user)
    with open(target_network, "w") as network_conf:
        for line in text:
            if live_permissions in line:
                line = target_permissions
            network_conf.write(line)
`

I believe `target_network` needs to be changed to argument variable `nm_config_filename`.
Also `user` needs to be changed to `target_user`.

When using Manjaro linux installer I receive an error 'target_network' is not defined.

**Comment by demonkilleralg** [comment]
installation fails when you have wifi connected right?

**Comment by coreylang** [comment]
Yes. Is it because a network profile is created? I thought about using ethernet.

**Comment by demonkilleralg** [comment]
This is working @philmmanjaro.

**Comment by adriaandegroot** [comment]
Thanks! That got really mangled in refactoring and whatever testing I did -- probably installing KDE neon in VirtualBox, once -- didn't hit this path.
