### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1795]
This is a tracking- and discussion- issue for FreeBSD support. I don't want to write separate issues for all the bits, nor create a wiki page for it, but there's plenty of things that need discussion / tweaking in the existing codebase to support alternate tools (maybe).

**Comment by adriaandegroot** [comment]
There's a `sysutils/calamares` port which installs the basics, **but**:
- No partitioning module because of lacking KPMCore. This might be salvageable with a KPMCore backend, but an approach that says "just do full-disk ZFS" might be acceptable, too.
- No guarantee that the various bits that call system tools work on FreeBSD. The *users* module is OK, that has adaptations for using `pw`.
- The unpack-filesystems code probably needs a good deal of work on FreeBSD.

**Comment by adriaandegroot** [comment]
Too niche for now.

**Comment by AssassinK786** [comment]
@adriaandegroot Can you say what is requirement to restart the work?
