### ISSUE TITLE
EFI partition minimum size is showed wrong

### ISSUE THREAD

**Issue by cfinnberg** [calamares/calamares#1796]
The error/warning message to show the minimum EFI partition size is wrong. It reads "314572800 MiB", when it should read "300MiB" or "314572800 bytes" (probably the former :D)

![kuva](https://user-images.githubusercontent.com/2817326/135110383-63c3dbd9-981f-45b0-942a-3b89402780d0.png)

**Comment by adriaandegroot** [comment]
Thanks! That was an oversight in the re-writing of the messages, indeed. It will land in the next release (presumably 3.2.45, in about two weeks).
