### ISSUE TITLE
Pacman Unable To Remove Packages

### ISSUE THREAD

**Issue by MohammadHisham** [calamares/calamares#1798]
**Describe the bug**
CarbonUI Beta Cutefish
BIOS - x86_64
Calamares Latest Version
Pacman 6.0.1-2

**Expected behavior**
calamares should remove "calamares" package
only "calamares" package not being removed
**Screenshots and Logs**
No Info In LOG
But Pacman Log Available
[pacman.log](https://github.com/calamares/calamares/files/7270835/pacman.log)
THIS HAPPENS IN ALL DESKTOP ENVIORMENTS

**Comment by demmm** [comment]
How is this  calamares issue? The package manager not removing something is certainly not in the realm of Calamares powers.  Check what depends on a package (that you asked to remove without giving any feedback) that wasn't removed.
