### ISSUE TITLE
Grub-mkconfig error

### ISSUE THREAD

**Issue by GiacoLenzo2109** [calamares/calamares#1799]
At the bootloader configuration the installation stop with an error:

**grub-mkconfig -o /boot/grub/grub.cfg: error failed to get canonical path of "overlay".**

**Comment by demmm** [comment]
please read about how to submit useful bug reports:
https://calamares.io/issues/
No indication here if this is an end user report, if so check with your distribution first:
https://calamares.io/issues/#end-users

The least needed is calamares version, distro used and full installation.log, but tha was already asked for in the bug submission form.
Without further info, there is no other option but to close this report.
