### ISSUE TITLE
Bootloader fail: grub error

### ISSUE THREAD

**Issue by GiacoLenzo2109** [calamares/calamares#1800]
**Bug:**
When calamares do chroot grub-mkconfig -o /boot/grub/grub.cfg i get this error: failed to get canonical path of "overlay".
The error is: grub-mkconfig -o /boot/grub/grub.cfg returned error code 1.
I' m testing the iso of my own distro on the virtualmachine. I' m using EFI and it's a 64bit.

Calamares:
I'm using calamares v 3.2.40.
You can find the distro' s iso here: **https://drive.google.com/file/d/1e7K6ZJcxATxlARgb2gC4wgwx2SQp8hPQ/view?usp=sharing**

**To Reproduce**
Just do everything and than try to install. At the end you will get the error described before.

**Log:**
[calamares.txt](https://github.com/calamares/calamares/files/7271537/calamares.txt)

**Comment by philmmanjaro** [comment]
Is this **Manjaro** or **Garuda** based?

**Comment by GiacoLenzo2109** [comment]
I' m using manjaro-tools but edited to use archlinux mirrorlist.

**Comment by philmmanjaro** [comment]
So neither. If you do a [search](https://www.startpage.com/do/dsearch?query=grub.cfg+error%3A+failed+to+get+canonical+path+of+%22overlay%22.&cat=web&pl=ext-ff&language=english&extVersion=1.3.0) you will find a lot of results. Most likely some issue with **efivars**. we had that ages ago. have to lookup the fix ...

**Comment by GiacoLenzo2109** [comment]
Ohh okok, i tried searching a lot but i only found that the problem is about chroot.
I' ve not found anything to do to solve my problem.

**Comment by GiacoLenzo2109** [comment]
That is the error: 

   ..  Running "chroot" ("/tmp/calamares-root-lj77r4x1", "grub-mkconfig", "-o", "/boot/grub/grub.cfg") 
    ..  Target cmd: ("grub-mkconfig", "-o", "/boot/grub/grub.cfg") Exit code: 1 output:
 Generating grub configuration file ...
Found theme: /usr/share/grub/themes/croco/theme.txt
Found linux image: /boot/vmlinuz-linux
Found initrd image: /boot/intel-ucode.img /boot/amd-ucode.img /boot/initramfs-linux.img
Found fallback initrd image(s) in /boot:  intel-ucode.img amd-ucode.img initramfs-linux-fallback.img
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
WARNING: [PYTHON JOB]: "Command 'grub-mkconfig -o /boot/grub/grub.cfg' returned non-zero exit status 1."

**Comment by adriaandegroot** [comment]
That's not much to go on: in the chroot, that specific command (`grub-mkconfig -o /boot/grub/grub.cfg`) is failing. I can't particularly see an error message from grub though; you could chroot into the target system once the install has failed, and then run the command by hand, or tweak debugging output from `grub-mkconfig` to find out what the actual problem is.

**Comment by GiacoLenzo2109** [comment]
After building using buildiso, if i go in var/lib/croco-tools/…./x86_64/rootfs/boot ther’ s not the folder “grub” wich should container grubenv.

Is this possible that because of it when i launch iso file in live and try to install using calamares, i get an error during bootloader installation (grub-mkconfig -o /boot/grub/grub.cfg returned with exit status code 1.

I’ getting creazy. I don t know if is this a problem of calamares or of tools or something else.

**Comment by adriaandegroot** [comment]
Is this still an issue? The Google Drive link is still ok, so I'll take a brief look at the ISO image.

**Comment by GiacoLenzo2109** [comment]
Hi, it' s solved, probably was an error of the tools i was using for building iso. Thx for help, i forgot to close the issue :)
