### ISSUE TITLE
Crypttab should not contain root and swap (with resume)

### ISSUE THREAD

**Issue by aligator** [calamares/calamares#1811]
In the crypttab file itself it even states that:
```
# NOTE: Do not list your root (/) partition here, it must be set up
#       beforehand by the initramfs (/etc/mkinitcpio.conf). The same applies
#       to encrypted swap, which should be set up with mkinitcpio-openswap 
#       for resume support.
```
But both were added to my crypttab.

Reproduction:
I used the manjaro live cd with BTRFS + Encryption + Swap with hybernation.

Not sure if BTRFS is important here.

**Comment by adriaandegroot** [comment]
The text (in `/etc/crypptab`) is one written by the Calamares module itself, presumably the text was  copied from somewhere else. However, even in the earlier versions of Calamares (I looked back to 2017) there is no special handling of / in a LUKS setup. A KaOS 2017 install gave me a `/etc/crypttab` with the root and swap listed. I'm inclined to say that the text is wrong -- overly-restrictive, that is.
