### ISSUE TITLE
Output equivalent shell command

### ISSUE THREAD

**Issue by evan0greenup** [calamares/calamares#1825]
**Is your feature request related to a problem? Please describe.**
The problem is user don't know what `calamares` do during installation.

**Describe the solution you'd like**
Show the terminal command equivalent or dump it to a file.

**Additional context**
It would be nice to let user know all the detailed shell command during installation.

**Comment by adriaandegroot** [comment]
Those are in the log (which is usually in `/root/.cache/calamares/session.log`). How much is logged depends on the flags with which Calamares is started. For debugging purposes, we recommend adding `-D6` to the flags, e.g. by editing the `.desktop` file. Most distro's use default logging, which is a bit light on details.

Those parts of Calamares that run commands through the Calamares API do get logged; look for `Running` or `Runner::run` in the log. Not all parts of Calamares **do** run commands through the API; there's plenty of Python modules that use shortcuts, for instance. There's room for improvement there. Some external libraries (KPMcore in particular) run commands as well but I don't think there's a way to get it to log the commands it runs.

Note that "showing the user shell commands" is not a goal of Calamares. If you want to learn how to do things entirely by hand, I'd recommend Slackware, or Arch, or LFS, and doing the installation from there. PRs that improve logging are welcome, I can think of a couple (e.g. formatting the logged command so it could be pasted into a shell; putting a newline ahead of the logged command so it's easier to copy-paste an entire line; finding instances of `QProcess` in core Calamares modules and using the API instead; finding instances of `subprocess` and `os.system()` in the Python modules and using the API instead).

Somewhat related are #1440 (show log during install, which in turn depends on there **being** good logging) #1593 (logging-related, not specific to showing commands).

Closing with "not a goal", but again: PRs that improve the log's usefulness to you are welcome.
