### ISSUE TITLE
Persian Language is now completely translated

### ISSUE THREAD

**Issue by MahdyMirzade** [calamares/calamares#1830]
![image](https://user-images.githubusercontent.com/63877463/142665438-1fe68107-306a-4d96-a14b-71f5147c2e11.png)

Hi, I just updated the Persian translation of "Calamares" to 100% on [Transifex](https://www.transifex.com/calamares/calamares/language/fa/), You can update (push) the translation.

Also I noticed there were a few typos from previous translators, old translation mistakes or wrong character choice.
But there are no active admins/reviewers for Persian Translation Team to fix these issues or check and make the better suggestion to take place.

Since almost every old/known FOSS Persian translator of this project, has abandoned this project or their last update was 1y ago, I request to become the manager of the Persian translation team and be able to update the support of my language.

Best Regards, Mahdy

**Comment by adriaandegroot** [comment]
Thank you! I've pulled in the translations (as I do fairly regularly) and updated the language-lists, so Persian will be nice and visible in the next release. I have edited your role to be coordinator as well of the team, so you can do reviewing and the like.
