### ISSUE TITLE
rsync failed error code 3

### ISSUE THREAD

**Issue by dfeg** [calamares/calamares#1835]
I've been trying for a few days to install arcolinuxB using calamares. I've posted on the arcolinux forum and after looking at my logs eric suggested i should log it here. https://arcolinuxforum.com/viewtopic.php?t=2871
I've tried multiple times using the iso downloaded from different sources on the arcolinx B site.

Here are the two logs. 

https://termbin.com/wk5p

https://termbin.com/29wx

I'm unsure if I'm in the right place or if it should be posted here. I don't want to cause more work for people and would love to get this installed on my main pc but hopefully the logs help. If you need any more information let me know

**Comment by demmm** [comment]
A few questions not asked in the forum post. Did you check the md5susm/sha5sum of the ISO?  How was the install media created?  Does your distro have a recommended way to create the install media?  Did you follow that recommendation?
Now from the output, can you post the how the partitioning is done right when the install (rsync) fails? needed info:
```
sudo blkid
```
and
```
sudo fdisk -l
```

**Comment by dfeg** [comment]
I have just managed to get everything installed. After trying another arcolinux distro it threw back a rsync failed with error code 11 which led me to here
https://archived.forum.manjaro.org/t/failed-to-unpack-image-rsync-failed-with-error-code-11/152750

Once i disabled execution prevention in the bios i was able to install. 

Sorry for causing any unnecessary work. I'm going to post this on the arcolinux forum encase anyone else has the same problems.
