### ISSUE TITLE
Mysterious behavior of systemd-boot in bootloader.conf

### ISSUE THREAD

**Issue by nd-rt** [calamares/calamares#1839]
When I change GRUB to systemd-boot in bootloader.conf, it strangely goes to look for vmlinuz-linux etc. in the top level /.
In KaOSx calamares, there is bootldr in addition to bootloader, and it looks to me like it specializes in systemd-boot.
KaOSx's calamares seem to look for vmlnuz-linux etc. in /boot, but bootloader doesn't seem to look in /boot.

I'm not very good at changing programs, and this problem itself may be my mistake.
I would appreciate your help in solving this problem.

This text has been translated through a translation tool, so it may be incorrect.
Please help us to solve the problem.

[postscript]
I'm a distribution developer.
The base is arch linux.

I realized after posting that I forgot to mention that I'm a developer of the Linux and distribution I'm based on.
My apologies.

**Comment by demmm** [comment]
Make sure to read about how to write useful bug reports or feature requests:
https://calamares.io/issues/
What distribution is this about?  End user question or distro developer?
If distro dev, read how to adjust the respective .conf, set to your needed kernel image:
https://github.com/calamares/calamares/blob/calamares/src/modules/bootloader/bootloader.conf#L14

**Comment by adriaandegroot** [comment]
The *bootldr* module is KaOS-specific. Unless you are a KaOS-developer, or creating a KaOS-derivative, you won't be using it. The *bootloader* module supports systemd-boot. When enabled, it writes a systemd-boot configuration file.

Some relevant code is this:
```
    lines = [
        '## This is just an example config file.\n',
        '## Please edit the paths and kernel parameters according\n',
        '## to your system.\n',
        '\n',
        "title   {!s}{!s}\n".format(entry, kernel_line),
        "linux   {!s}\n".format(os.path.join("/", entry_name, kernel_name)),
        "initrd  {!s}\n".format(os.path.join("/", entry_name, img_name)),
        "options {!s} rw\n".format(" ".join(kernel_params)),
    ]
```

Is there a problem there?

**Comment by demmm** [comment]
1) bootldr is not used by KaOS anymore
2) question here is about correct kernel image naming (thus my reply that this is a help request, not bug report or feature request).

**Comment by nd-rt** [comment]
> 1. bootldrはKaOSでは使用されなくなりました
> 2. ここでの質問は、正しいカーネルイメージの命名に関するものです（したがって、これはヘルプリクエストであり、バグレポートや機能リクエストではないという私の回答です）。

I see that there was a page dedicated to help.
Sorry about that.

**Comment by nd-rt** [comment]
> kernel_params



> _BOOTLDRの_モジュールはカオス特有です。あなたがKAOS開発者でない限り、またはカオス派生物を作成していない限り、それを使用することはありません。_ブートローダ_モジュールは、システムD-ブートをサポートしています。有効にでき、systemd-boot設定がありれます。
> 
> おいするコードは次のなりです。
> 
> ```
>     lines = [
>         '## This is just an example config file.\n',
>         '## Please edit the paths and kernel parameters according\n',
>         '## to your system.\n',
>         '\n',
>         "title   {!s}{!s}\n".format(entry, kernel_line),
>         "linux   {!s}\n".format(os.path.join("/", entry_name, kernel_name)),
>         "initrd  {!s}\n".format(os.path.join("/", entry_name, img_name)),
>         "options {!s} rw\n".format(" ".join(kernel_params)),
>     ]
> ```
> 
> かに問題はありますか？
[log.txt](https://github.com/calamares/calamares/files/7650511/log.txt)

In order to support Arch linux based OS, we have changed the \ part.
class FileExistsError
17 Error.
What should I do from here?

**Comment by dalto8** [comment]
You don't need to change the python code.  You need to set the correct paths in `bootloader.conf`

By default they look like this:
```text
kernel: "/vmlinuz-linux"
img: "/initramfs-linux.img"
fallback: "/initramfs-linux-fallback.img"
```

However, for Arch they should be:
```text
kernel: "/boot/vmlinuz-linux"
img: "/boot/initramfs-linux.img"
fallback: "/boot/initramfs-linux-fallback.img"
```

**Comment by nd-rt** [comment]
[session.log](https://github.com/calamares/calamares/files/7653447/session.log)
According to the log, "Warning. The system is EFI, but the EFI system partition cannot be found."
It was output.
Where can I fix it?
Please cooperate in solving the problem.

**Comment by demmm** [comment]
Please lets not make bug reports help channels, there are already way too many open reports to handle.  Here it is clear the wiki need to be read, and if further questions, use IRC, Matrix or Telegram.
