### ISSUE TITLE
Calamares fails when installing over an existing installation, while using systemd-boot and reusing the ESP

### ISSUE THREAD

**Issue by chloecormier** [calamares/calamares#1840]
**Describe the bug**
The bootloader module encounters an error when installing, if you have previously installed the same distribution using the same ESP, and are using systemd-boot.

**To Reproduce**
1. Configure Calamares to use systemd-boot.
2. Install to an EFI machine.
3. After installation finishes, reboot back into the live environment and try to install again.
4. Partition in any way, as long as the ESP is kept and reused (as is typical when dual-booting with Windows, for instance).

**Expected behavior**
Calamares should overwrite existing bootloader files, or at least ask the user about it, instead of completely failing.

**Screenshots and Logs**
Screenshot of the error that appears: https://i.imgur.com/YJwJJbk.png

**Additional context**
Currently, the only way to work around this is to either delete your ESP (breaking Windows in a dual-boot setup) or to open the partition and delete your distribution's files manually.

**Comment by demmm** [comment]
If seen correctly, there is no issue with overwriting the existing kernel image, just writing over the existing configuration file.  Not clear from the image (always best to post the real installation.log, not images), if the error is with the <distro_name>.conf or loader.conf. If the former, this could be a job for anyone with some python knowledge to implement.

Idea is to always create a unique <distro_name_id.conf>, with the installer using a random id for each install.
This also would be a good opportunity to again consider splitting the bootloader module into all seperate modules (rEfind is done, so systemd-boot, grub and possible shim).

**Comment by killajoe** [comment]
similar to this: https://github.com/calamares/calamares/issues/1820

**Comment by dalto8** [comment]
This is a bug.  I fixed this in work-3.3 a while back.  I just backported that fix in PR https://github.com/calamares/calamares/pull/1842

**Comment by adriaandegroot** [comment]
I've picked up @dalto8 's patch and pushed to the *calamares* branch. @chloecormier , 6e08da6c8d4bcf7608e6b61dc170d06e0b3246f7 should do the trick (it's a one-liner, and probably applies to whichever Calamares release you are using). There should be at least one more Calamares release before the end of the year if you want one with the fix included.

**Comment by comitodedito** [comment]
@chloecormier it fails cause u are male in wig and not real woman
u rapist xD

die die die hahahaha
![ezgif-4-53ffca5be9](https://user-images.githubusercontent.com/107486488/173593624-bc0dab96-4548-468e-bcb4-df43a2c10156.gif)
![re](https://user-images.githubusercontent.com/107486488/173593628-2d244545-fb63-42e5-a736-30e9bd935a18.png)
![re2](https://user-images.githubusercontent.com/107486488/173593631-c0c7d277-c57a-4381-8a00-cc4752ef462b.png)
