### ISSUE TITLE
Remove btrfs additional mount options from default configuration

### ISSUE THREAD

**Issue by LordTermor** [calamares/calamares#1846]
In my opinion having tweaked btrfs options (like `autodefrag` etc) in example config file is not a good idea as those could be used by distro maintainers as an example and might have some unwanted side-effects. Also it seems some of them (such as `ssd`) are obsolete nowadays.

I propose to leave only minor things like `noatime` and `compress=zstd:1` and let handle distro maintainers the rest.

**Comment by adriaandegroot** [comment]
I wonder, though, if there's not an underlying issue where the mount-flags need to match flags set at creation. For instance, you were reporting that `noatime` could facilitate data corruption .. which sounds quite scary. But maybe a btrfs fs needs to be told at creation time that it won't be doing atime? (I don't know enough about it to say)
