### ISSUE TITLE
Networkcfg setup cannot read network file with name utf-8

### ISSUE THREAD

**Issue by thanh125643** [calamares/calamares#1848]
**Describe the bug**
My wifi name was Nguyên . So when open and read file from installer it just show error unicodekeyError 

**To Reproduce**
1. Change wifi name to Nguyên 
2. Install like normal and error will be show

**Expected behavior**
It just make wifi work affter install.

**Screenshots and Logs**
[session.log](https://github.com/calamares/calamares/files/7694443/session.log)
![Screenshot from 2021-12-11 00-33-13](https://user-images.githubusercontent.com/9133085/145616912-c411e45a-03a6-4f25-a96a-532ab0b523e7.png)
![Screenshot from 2021-12-11 00-44-41](https://user-images.githubusercontent.com/9133085/145618303-034c4b99-ed70-4c1b-b15b-bde6e74275dd.png)

**Additional context**

**Comment by demmm** [comment]
>My wifi name was Nguyên . So when open and read file from installer it just show error unicodekeyError

The module does not read the Wifi ID at the error point, it reads the user name, so it would be best if you could paste the content of `/etc/NetworkManager/system-connections/` (remove or obscure any data you might not want to show).
Error message above shows it is related to line 126, https://github.com/calamares/calamares/blob/calamares/src/modules/networkcfg/main.py#L126
That would mean a username with unsupported character.

**Comment by dalto8** [comment]
> The module does not read the Wifi ID at the error point, it reads the user name

Are you sure?  It looks to me like the error occurs on line 77 where it is reading the network config file.

**Comment by demmm** [comment]
Wifi ID would be a device ID, looks like we are talking here about the target, chosen username.  So instead of going on with confusion, better see the .conf to make sure what uses `Nguyên` and where.

**Comment by thanh125643** [comment]
This is where it error i think in read file and sure it was Nguyên in id
```
[connection]
id=Nguyên 5.0Ghz
uuid=08ff9de5-72ab-4861-a964-6b4f15be392a
type=wifi
interface-name=wlp3s0
permissions=
```

**Comment by demmm** [comment]
`id=Nguyên 5.0Ghz` does not cause an error, so looks like it is the file name that python trips over.  From the above image it looks like the name is `Nguy'$'\303\252''n 5.0Ghz.nmconnections`
I would have expected a `file not found error` with that weird a file name. Can you verify what the exact filename is that causes this fail?

**Comment by demmm** [comment]
Looks like `https://github.com/calamares/calamares/blob/calamares/src/modules/networkcfg/main.py#L76` will need to have encoding added, so it will read `with open(nm_config_filename, "r", encoding='utf-8') as network_conf:`
I'll let others decide if that is the proper fix (or if switching to utf-8 has unwanted side-effects).
