### ISSUE TITLE
swap creation for autopartitions let partition creation fail

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1849]
- Calamares 3.2.49 PKGBUILD: https://github.com/endeavouros-team/PKGBUILDS/blob/master/calamares_current/PKGBUILD
- EndeavourOS configs: https://github.com/endeavouros-team/EndeavourOS-calamares
- install log: https://termbin.com/zr4p

![swap-fail](https://user-images.githubusercontent.com/16797647/145645734-9115b16a-46c1-4d4b-9a3c-7e0ab0d20610.jpg)
![swap-fail-2](https://user-images.githubusercontent.com/16797647/145645999-d01d490f-6eea-40c1-af58-11fc7272d5ab.jpg)

choosing swap without or with hibernation lets partition fail independently from the chosen filesystem (we have BTRFS and ext4 enabled).

Swapfile instead is still working. 

Tested on VirtualBox and real hardware.

Cleaning the disk before starting the installer is not helping too.

Seems that the size of the swap partition it wants to create is very small, at least on the UI, and it does not show the size that it wants to create gives only `--- swap` instead there.

**Comment by adriaandegroot** [comment]
I was looking at the tail end of the log, but the important bit was much earlier:

```
2021-12-10 - 20:59:14 [6]: qint64 PartitionActions::swapSuggestion(qint64, Config::SwapChoice)
    Suggested swap size: -2 GiB 
```

This was a result of an integer overflow introduced in e8ca298712461c694269300422964905ed944af1 (`qRound()` returns an int, not a qint64).
