### ISSUE TITLE
Unpacking kernel to /boot with EFI is skipped

### ISSUE THREAD

**Issue by Hayao0819** [calamares/calamares#1862]
Unpacking the kernel in / boot with EFI enabled will not deploy.
The `efiSystemPartition` of the `partition` module is `/boot/efi`. This unpack operation is successful in the case of the BIOS.
Do I need to make any additional settings? Or is it not supported to extract files to /boot? 

**Expected behavior**
Files should be placed in / boot as in the BIOS.

**Additional context**
It is on Arch Linux.

**Comment by demmm** [comment]
Bugs/issue are not a help channel:
https://calamares.io/issues/#developers-of-distributions
Make sure to read the Wiki and all instructions provided for you in the used modules .conf files.  Use IRC/Matrix if you have questions left after reading the provided docs.
For this module:
https://github.com/calamares/calamares/blob/calamares/src/modules/partition/partition.conf#L8
