### ISSUE TITLE
KeyError in module unpackfs

### ISSUE THREAD

**Issue by scratcher-402** [calamares/calamares#1870]
A KeyError occurs during installation

[ISO](https://drive.google.com/file/d/1GqWHdD9UmxIUQPu9ouSSB04bKTbxdjRg/view?usp=sharing) 
[Log](https://pastebin.com/zt6P33dk)

**Comment by demmm** [comment]
Please make sure to file complete issues reports, and use the issue template provided for you + read https://calamares.io/issues/
Is this a report from an end user?  Distro dev? What distro? If distro dev, what is used in the settings.conf, any warnings in the build log?
Info is insufficient to be used for a bug report.

**Comment by scratcher-402** [comment]
The error occurs during the installation process, I am one of the developers, the calamares package for debian is used.
[Settings.conf](https://paste.debian.net/1226129/)

**Comment by demmm** [comment]
>I am one of the developers
Developer of what distro? What version of Calamares? Please try to be more clear ( and **do** read the issue guidelines, use the issue_template, so there isn't a need for an endless back and force to get absolutely needed info).

**Comment by scratcher-402** [comment]
**Describe the bug**
Python error in job unpackfs:
![unknown](https://user-images.githubusercontent.com/75668082/148373775-abfb17d5-2eff-4406-8b02-804f5676e21a.png)


**To Reproduce**
Steps to reproduce the behavior:
1. Start the installer
2. configure the installation and run it
3. See the error

**Expected behavior**
The system should have been installed without errors

**Screenshots and Logs**
[session.log](https://pastebin.com/zt6P33dk)

**Additional context**
Distro is based on Debian 10
Calamares 3.2.4
In unpackfs.conf squashfs is unpacking on the system disk

**Comment by demmm** [comment]
Again, what is the setting (post the file) in unpackfs.conf. The error you get is by design when you use wrong settings in that file:
https://github.com/calamares/calamares/blob/calamares/src/modules/unpackfs/main.py#L442

**Comment by dalto8** [comment]
As @demmm pointed out, that error means the `unpack` mapping is missing from the config file.  It is almost definitely an issue with unpackfs.conf since that is the only thing in that file.  Arguably, the error message could be better but even if it was, it would still fail without any configuration information.

One thing I would point out is that yaml is very sensitive to indentation.  Make sure that everything in that file is indented properly.
