### ISSUE TITLE
Mount point text lineedit promt text not cleared when editing

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#1877]
When you are setting up a disk partition the dropdown combo box which lists the filesystem format types (ext4 etc) can be freely text edited.  This is confusing and I've no idea what happens if you decide you want to install with AdeFS.

**Comment by dalto8** [comment]
If it didn't have free editing, how would you create partitions other than the ones named in the dropdown?

**Comment by adriaandegroot** [comment]
Which dropdown combo box? Please provide a screenshot, or steps-to-reproduce. I can't reproduce this when running Calamares in a Netrunner installation. There's two "filesystem dropdowns" I can find:

- when choosing *erase disk*, **and** multiple filesystems are enabled, there's a FS dropdown. It looks like select-only to me, and I can't type text into it.
- when choosing *manual partition*, and creating a partiton, there's a FS dropdown. It looks like select-only to me, and I can't type text into it.

I'll give it a stab with KDE neon, though.

**Comment by jriddell** [comment]
![image](https://user-images.githubusercontent.com/89822/151819472-2de6c754-abd9-4a49-8b92-c98fed014d19.png)
It was actually the mount point text edit.  It should clear the "(no mount point)" text when the user click on the box.

**Comment by adriaandegroot** [comment]
Closed with 7f90b9938814ccc3c0d25c3053606439897e8eb3 and commits before that.
