### ISSUE TITLE
calamares data entry; cursor jumps to end of field

### ISSUE THREAD

**Issue by guiverc** [calamares/calamares#1884]
This was noticed during the Lubuntu *hirsute* cycle (21.04) so more than a year ago. Is filed at https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/1904266

**Describe the bug**

At the 'user setup' screen  you enter fields like name, username, hostname, password etc.

This issue occurs in entry of HOSTNAME

**To Reproduce**

Get to the 'user setup' screen; in Lubuntu the field is pre-populated with details from the box or firmware of the box. I tend to amend this detail  Assuming the box starts with a preloaded field of "hpcompaqdc7700" I often shrink to "dc7700", but in this case I decide to add the word "blah" at the front of the field.  I move the cursor to the beginning of the field, with intention of adding "blah" to the start of it.

**Expected behavior**

I move the cursor to the beginning of the field, with intention of adding "blah" to the start of it.

I expect either "blahhpcompaqdc7700" (inserted) or "blahmpaqdc7700" (replaced)

**Actual behavior**

Instead I get the "bhpcompaqdc7700lah"

because on entry of the first character "b" of "blah", the cursor jumps to the end of the field for the subsequent characters. This is occurring anywhere in the field (cursor jumps to the end after typing a letter).

**Screenshots and Logs**

A really old session.log can be found on the provided https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/1904266 bug report, but it's of no value. I don't think logs will help, but will provide if helpful.

**Additional context**

As previously mentioned, it was noted during the hirsute cycle during normal QA  (ie. first noted on 2020-Nov-14) with calamares package 3.2.32.1-0ubuntu1 but still occurs with the current 3.2.41.1-0ubuntu3
 in Ubuntu repositories. 

This is filed upstream today as I noted it today on Debian/PeppermintOS (debian package 3.2.36-1); and I like verification in a non-Ubuntu before I file upstream.

**Comment by adriaandegroot** [comment]
Confirmed in a dev-build, even one that does not pre-populate the hostname field:

- go to *users* page.
- type "d" in the *your name* field, so it fills in "d" in the *login* field, and "d-pc" in the *hostname* field
- click at the start of the *hostname* field and type "b", then "l". 
- field now contains "bd-pcl".
