### ISSUE TITLE
Disable bootloader installation?

### ISSUE THREAD

**Issue by alphamaestro555** [calamares/calamares#1886]
I need the option to not install GRUB during an Artix installation.

I follow the guide at https://wiki.artixlinux.org/Main/InstallationWithFullDiskEncryption

The wiki article suggests editing the script:

` /usr/lib/calamares/modules/bootloader/main.py`

By commenting out the following line near the end of the file at def run() :
` prepare_bootloader(fw_type)`

If I do that, during installation the installer fails with bootloader installation error. Are there more sections to remove from this script in order for it to work or is there a simpler way since there is no option for not installing a bootloader in the GUI?

**Comment by demmm** [comment]
There are several ways, if you want to use a GUI, packagechooser is the best option to create a GUI, so a globalstoarge will be created depending on the user choice, then you can run the bootloader.py script with a switch depending on the globalstorage entry.
Example of running grub this way:
https://github.com/KaOSx/calamares/blob/master/src/modules/packagechooserq/BIOS.qml
https://github.com/KaOSx/calamares/blob/master/src/modules/grub/main.py#L56

That last line: 
```
if bootchoice != 'grub':
        return None
```
Can also be entered as is in the booloader.py under `def run(), with whatever `if` entry you'd prefer.

**Comment by merinfor2021** [comment]
@alphamaestro555 Dear friend, the guide at https://wiki.artixlinux.org/Main/InstallationWithFullDiskEncryption has been updated, and I think it's ready for your test ;-)

@demmm Perhaps you misunderstood OP: he wanted to be able to install Artix Linux with Calamares GUI installer, but without auto-installing the GRUB bootloader during Artix installation process. When using the sophisticated encrypted partition scheme described in the guide above, auto-installing the GRUB bootloader causes an error, so the GRUB auto-installation should be avoided, and GRUB should be installed manually a bit later. Yes, it could be disabled by a `bootloader/main.py` modification.

**Comment by demmm** [comment]
@merinfor2021 Nope, that is exactly what I was explaining.
