### ISSUE TITLE
Arch Linux - sudoers new syntax

### ISSUE THREAD

**Issue by arcolinuxz** [calamares/calamares#1887]
Calamares creates a file in /etc/sudoers.d/ called 10-installer with old syntax

%wheel ALL=(ALL) ALL 

This does not cause any issue (**yet**).

Just wanted you to be aware of this.

Changed the code to 
%wheel ALL=(ALL:ALL) ALL and rebooted and everything is fine

![ArcoLinux-2022-02-16_16-09](https://user-images.githubusercontent.com/36679406/154294469-a626bede-e80d-4675-b58c-ded4e383fedd.png)

**Comment by Neo-29** [comment]
Very informative. Tks.
