### ISSUE TITLE
How to enable the checkbox as choosen to enable the automatic login defautly

### ISSUE THREAD

**Issue by StrongTiger-cloud** [calamares/calamares#1890]
![disable the checkbox to enable automatic login](https://user-images.githubusercontent.com/66662992/154799618-b7a7df1d-f906-476a-ad1d-6779d33a4178.png)
As the shown in the attachment, how to make the checkbox as choosen defaultly and do not permit any other option, so automatic login can be enabled for ever?
thanks in advance.

**Comment by adriaandegroot** [comment]
- There is no way to hide that checkbox (not from the configuration, anyway; right now it would require patching the C++ code)
- To enable the checkbox by default, set `doAutologin:     true` in `users.conf` (this setting is documented in that file)

It seems a bit strange to **always** autologin, regardless of what the user wants or would like. What is the use-case for an installed Linux system with no user selection?

**Comment by demmm** [comment]
That is very possible, when using usersq instead of users, just needs adjusting of the QML file, but as said, not clear what the use-case would be.

**Comment by StrongTiger-cloud** [comment]
Hi, [adriaandegroot](https://github.com/adriaandegroot)

> 

thanks for your comments, but it does not take effect after set doAutologin: true in users.conf.
I do not know what should I do to attain that?

**Comment by dalto8** [comment]
> thanks for your comments, but it does not take effect after set doAutologin: true in users.conf. I do not know what should I do to attain that?

Can you share the contents of your `users.conf` file?

It is working fine here with both `users` and `usersq`

**Comment by StrongTiger-cloud** [comment]
> > thanks for your comments, but it does not take effect after set doAutologin: true in users.conf. I do not know what should I do to attain that?
> 
> Can you share the contents of your `users.conf` file?
> 
> It is working fine here with both `users` and `usersq`
attach the users.conf\userq.conf and usersq.qml:
![usersconf](https://user-images.githubusercontent.com/66662992/154897220-3ec24cad-7204-4427-b547-c0827a47cd6c.gif)
![usersqconf](https://user-images.githubusercontent.com/66662992/154897243-0d68f73f-f9f7-4a41-b5f9-eaccd6a6078f.gif)
![usersqqml](https://user-images.githubusercontent.com/66662992/154897251-b5a2b195-f836-4b42-8205-2e3f41bf6e7d.gif)

**Comment by StrongTiger-cloud** [comment]
Hi, dalto8:
   please change my attached file from their extension name *.jpg to *.conf to show their data contents, thanks.

**Comment by StrongTiger-cloud** [comment]
Seems that the attachments can not show clearly.
users.conf:
# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the one-user-system user module.
#
# Besides these settings, the users module also places the following
# keys into the Global Storage area, based on user input in the view step.
#
# - hostname
# - username
# - password (obscured)
# - autologinUser (if enabled, set to username)
#
# These Global Storage keys are set when the configuration for this module
# is read and when they are modified in the UI.
---
# Used as default groups for the created user.
# Adjust to your Distribution defaults.
#
# Each entry in the *defaultGroups* list is either:
#   - a string, naming a group; this is a **non**-system group
#     which does not need to exist in the target system; if it
#     does not exist, it will be created.
#   - an entry with subkeys *name*, *must_exist* and *system*;
#     if the group *must_exist* and does not, an error is thrown
#     and the installation fails.
#
#     The group is created if it does not exist, and it is
#     created as a system group (GID < 1000) or user group
#     (GID >= 1000) depending on the value of *system*.
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - lp
    - video
    - network
    - storage
    - name: wheel
      must_exist: false
      system: true
    - audio

# Some Distributions require a 'autologin' group for the user.
# Autologin causes a user to become automatically logged in to
# the desktop environment on boot.
# Disable when your Distribution does not require such a group.
autologinGroup:  autologin
# You can control the initial state for the 'autologin checkbox' here.
# Possible values are:
#  - true to check or
#  - false to uncheck
# These set the **initial** state of the checkbox.
doAutologin:     false

# When *sudoersGroup* is set to a non-empty string, Calamares creates a
# sudoers file for the user. This file is located at:
#     `/etc/sudoers.d/10-installer`
# Remember to add the (value of) *sudoersGroup* to *defaultGroups*.
#
# If your Distribution already sets up a group of sudoers in its packaging,
# remove this setting (delete or comment out the line below). Otherwise,
# the setting will be duplicated in the `/etc/sudoers.d/10-installer` file,
# potentially confusing users.
sudoersGroup:    wheel

# Setting this to false, causes the root account to be disabled.
# When disabled, hides the "Use the same password for administrator"
# checkbox. Also hides the "Choose a password" and associated text-inputs.
setRootPassword: true

# You can control the initial state for the 'reuse password for root'
# checkbox here. Possible values are:
#  - true to check or
#  - false to uncheck
#
# When checked, the user password is used for the root account too.
#
# NOTE: *doReusePassword* requires *setRootPassword* to be enabled.
doReusePassword: true

# These are optional password-requirements that a distro can enforce
# on the user. The values given in this sample file set only very weak
# validation settings.
#
# - nonempty rejects empty passwords
# - there are no length validations
# - libpwquality (if it is enabled at all) has no length of class
#   restrictions, although it will still reject palindromes and
#   dictionary words with these settings.
#
# Checks may be listed multiple times; each is checked separately,
# and no effort is done to ensure that the checks are consistent
# (e.g. specifying a maximum length less than the minimum length
# will annoy users).
#
# The libpwquality check relies on the (optional) libpwquality library.
# Its value is a list of configuration statements that could also
# be found in pwquality.conf, and these are handed off to the
# libpwquality parser for evaluation. The check is ignored if
# libpwquality is not available at build time (generates a warning in
# the log). The Calamares password check rejects passwords with a
# score of < 40 with the given libpwquality settings.
#
# (additional checks may be implemented in CheckPWQuality.cpp and
# wired into UsersPage.cpp)
#
#  - To disable specific password validations:
#    comment out the relevant 'passwordRequirements' keys below.
#  - To disable all password validations:
#    set both 'allowWeakPasswords' and 'allowWeakPasswordsDefault' to true.
#    (That will show the box *Allow weak passwords* in the user-
#    interface, and check it by default).
passwordRequirements:
    nonempty: true
    minLength: -1  # Password at least this many characters
    maxLength: -1  # Password at most this many characters
    libpwquality:
        - minlen=0
        - minclass=0

# You can control the visibility of the 'strong passwords' checkbox here.
# Possible values are:
#  - true to show or
#  - false to hide  (default)
# the checkbox. This checkbox allows the user to choose to disable
# password-strength-checks. By default the box is **hidden**, so
# that you have to pick a password that satisfies the checks.
allowWeakPasswords: false
# You can control the initial state for the 'strong passwords' checkbox here.
# Possible values are:
#  - true to uncheck or
#  - false to check (default)
# the checkbox by default. Since the box is labeled to enforce strong
# passwords, in order to **allow** weak ones by default, the box needs
# to be unchecked.
allowWeakPasswordsDefault: false

# Shell to be used for the regular user of the target system.
# There are three possible kinds of settings:
#  - unset (i.e. commented out, the default), act as if set to /bin/bash
#  - empty (explicit), don't pass shell information to useradd at all
#    and rely on a correct configuration file in /etc/default/useradd
#  - set, non-empty, use that path as shell. No validation is done
#    that the shell actually exists or is executable.
userShell: /bin/bash

# Hostname setting
#
# The user can enter a hostname; this is configured into the system
# in some way; pick one of:
#   - *None*, to not set the hostname at all
#   - *EtcFile*, to write to `/etc/hostname` directly
#   - *Hostnamed*, to use systemd hostnamed(1) over DBus
# The default is *EtcFile*.
setHostname: EtcFile

# Should /etc/hosts be written with a hostname for this machine
# (also adds localhost and some ipv6 standard entries).
# Defaults to *true*.
writeHostsFile: true

presets:
    fullName:
        # value: "OEM User"
        editable: true
    loginName:
        # value: "oem"
        editable: true

**Comment by dalto8** [comment]
> doAutologin: false
>
> doAutologin: false

It is set to `false`.  You need to change it to `true`

**Comment by StrongTiger-cloud** [comment]
hi, dalto8:
  even if I had set doAutologin as true, after I do "make" and "make install", I started calamares but the checkbox for autologin has not been choosed yet.
Attach the log:
# calamares -X -D6
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1001
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1001
08:19:35 [6]: Calamares::Settings::Settings(const QString&, bool)
    Using Calamares settings file at "/etc/calamares/settings.conf" 
    .. Required settings.conf key hide-back-and-next-during-exec is missing. 
08:19:35 [6]: void Logger::setupLogfile()
    Using log file: "/root/.cache/calamares/session.log" 
08:19:35 [6]: void CalamaresApplication::init()
    Calamares version: 3.2.52.20220221-b1742876-dirty 
    .. languages: "ar, as, ast, az, az_AZ, be, bg, bn, ca, ca@valencia, cs_CZ, da, de, el, en, en_GB, eo, es, es_MX, et, eu, fa, fi_FI, fr, fur, gl, he, hi, hr, hu, id, is, it_IT, ja, ko, lt, ml, mr, nb, nl, pl, pt_BR, pt_PT, ro, ru, si, sk, sl, sq, sr, sr@latin, sv, tg, th, tr_TR, uk, vi, zh_CN, zh_TW" 
08:19:35 [6]: bool CalamaresUtils::initQmlModulesDir()
    Using Calamares QML directory "/usr/share/calamares/qml" 
08:19:35 [6]: Calamares::Branding::Branding(const QString&, QObject*)
    Using Calamares branding file at "/etc/calamares/branding/debian/branding.desc" 
08:19:35 [2]: void Calamares::flavorAndSide(const YAML::Node&, const char*, Calamares::Branding::PanelFlavor&, Calamares::Branding::PanelSide&)
    WARNING: Branding setting for sidebar is missing, using "widget" "left" 
08:19:35 [2]: void Calamares::flavorAndSide(const YAML::Node&, const char*, Calamares::Branding::PanelFlavor&, Calamares::Branding::PanelSide&)
    WARNING: Branding setting for navigation is missing, using "widget" "bottom" 
08:19:35 [2]: Calamares::Branding::Branding(const QString&, QObject*)
    WARNING: the branding component "/etc/calamares/branding/debian" does not ship translations. 
08:19:35 [6]: Calamares::Branding::Branding(const QString&, QObject*)
    Loaded branding component "debian" 
    .. Loaded QRC translation "tz_" "en_US" 
    .. Loaded QRC translation "calamares_" "en_US" 
    .. STARTUP: initSettings, initQmlPath, initBranding done 
    .. STARTUP: initModuleManager: module init started 
08:19:35 [6]: void Calamares::ModuleManager::doInit()
    Found 63 modules 
08:19:35 [6]: void CalamaresApplication::initView()
    STARTUP: initModuleManager: all modules init done 
08:19:35 [6]: void CalamaresApplication::initView()
    STARTUP: initJobQueue done 
08:19:35 [6]: CalamaresWindow::CalamaresWindow(QWidget*)
    Available desktop QSize(1920, 923) minimum size QSize(1024, 520) 
    .. Proposed window size: 1024 520 
08:19:35 [2]: QString Calamares::_stylesheet(const QDir&)
    WARNING: The branding component "/etc/calamares/branding/debian" does not ship stylesheet.qss. 
08:19:35 [6]: void CalamaresApplication::initView()
    STARTUP: CalamaresWindow created; loadModules started 
08:19:35 [6]: void Config::initLanguages()
    Matching locale QLocale(English, Latin, United States) 
08:19:35 [6]: void Config::setLocaleIndex(int)
    Index 14 Selected locale "en" 
    .. Loaded QRC translation "tz_" "en" 
    .. Loaded QRC translation "calamares_" "en" 
08:19:35 [2]: bool getCheckInternetUrls(const QVariantMap&)
    WARNING: GeneralRequirements entry 'internetCheckUrl' is undefined in welcome.conf, reverting to default ( "http://example.com" ). 
08:19:35 [2]: void GeneralRequirements::setConfigurationMap(const QVariantMap&)
    WARNING: GeneralRequirements configuration map: 
     check :   storage, ram, power, root 
     required :   storage, ram, root 
     requiredRam :   1 
     requiredStorage :   10 
08:19:35 [6]: virtual void Calamares::ViewModule::loadSelf()
    ViewModule "welcome@welcome" loading complete. 
08:19:35 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "locale" found anywhere at 
     "/etc/calamares/modules/locale.conf" 
     "/usr/share/calamares/modules/locale.conf" 
08:19:35 [6]: virtual void Calamares::ViewModule::loadSelf()
    ViewModule "locale@locale" loading complete. 
08:19:35 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "keyboard" found anywhere at 
     "/etc/calamares/modules/keyboard.conf" 
     "/usr/share/calamares/modules/keyboard.conf" 
08:19:35 [6]: KeyboardModelsModel::KeyboardModelsModel(QObject*)
    Loaded 188 keyboard models 
08:19:35 [6]: KeyboardPage::KeyboardPage(Config*, QWidget*)
    Variants now total= 0 selected= -1 
    .. Loaded QRC translation "kb_" "en" 
08:19:35 [6]: void Config::detectCurrentKeyboardLayout()
    ("pc", "us", "inet(evdev)\"") 
08:19:35 [6]: virtual void Calamares::ViewModule::loadSelf()
    ViewModule "keyboard@keyboard" loading complete. 
08:19:35 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "partition" found anywhere at 
     "/etc/calamares/modules/partition.conf" 
     "/usr/share/calamares/modules/partition.conf" 
08:19:35 [6]: CalamaresUtils::Partition::InternalManager::InternalManager()
    KPMCore backend starting .. 
08:19:35 [6]: Loaded backend plugin:  "pmsfdiskbackendplugin"
    .. Backend @0x56098b2780e0 "pmsfdiskbackendplugin" "1" 
08:19:35 [2]: void Config::setConfigurationMap(const QVariantMap&)
    WARNING: Configuration for *initialSwapChoice* is not one of the *userSwapChoices* 
08:19:35 [2]: void Config::fillConfigurationFSTypes(const QVariantMap&)
    WARNING: Partition-module setting *defaultFileSystemType* is missing, will use ext4 
08:19:36 [2]: virtual void PartitionViewStep::setConfigurationMap(const QVariantMap&)
    WARNING: Partition-module setting *defaultPartitionTableType* is unset, will use gpt for efi or msdos for bios 
08:19:36 [6]: virtual void Calamares::ViewModule::loadSelf()
    ViewModule "partition@partition" loading complete. 
08:19:36 [6]: virtual void Calamares::ViewModule::loadSelf()
    ViewModule "users@users" loading complete. 
08:19:36 [6]: virtual void Calamares::ViewModule::loadSelf()
    ViewModule "summary@summary" loading complete. 
08:19:36 [6]: void Calamares::ModuleManager::loadModules()
    Module "partition@partition" already loaded. 
08:19:36 [6]: Calamares::SlideshowQML::SlideshowQML(QWidget*)
    QML import paths: 
     "/usr/share/calamares/qml" 
     "/usr/bin" 
     "qrc:/qt-project.org/imports" 
     "/usr/lib/x86_64-linux-gnu/qt5/qml" 
08:19:36 [6]: Calamares::SlideshowQML::SlideshowQML(QWidget*)
    QML load on startup, API 2. 
08:19:36 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "sources-media" found anywhere at 
     "/etc/calamares/modules/sources-media.conf" 
     "/usr/share/calamares/modules/sources-media.conf" 
08:19:36 [2]: virtual void MachineIdJob::setConfigurationMap(const QVariantMap&)
    WARNING: MachineId: configuration setting *symlink* is deprecated, use *dbus-symlink*. 
08:19:36 [6]: virtual void Calamares::CppJobModule::loadSelf()
    CppJobModule "machineid@machineid" loading complete. 
08:19:36 [6]: void Calamares::ModuleManager::loadModules()
    Module "locale@locale" already loaded. 
08:19:36 [6]: void Calamares::ModuleManager::loadModules()
    Module "keyboard@keyboard" already loaded. 
08:19:36 [6]: void Calamares::ModuleManager::loadModules()
    Module "users@users" already loaded. 
08:19:36 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "services-systemd" found anywhere at 
     "/etc/calamares/modules/services-systemd.conf" 
     "/usr/share/calamares/modules/services-systemd.conf" 
08:19:36 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "bootloader-config" found anywhere at 
     "/etc/calamares/modules/bootloader-config.conf" 
     "/usr/share/calamares/modules/bootloader-config.conf" 
08:19:36 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "grubcfg" found anywhere at 
     "/etc/calamares/modules/grubcfg.conf" 
     "/usr/share/calamares/modules/grubcfg.conf" 
08:19:36 [6]: virtual void Calamares::CppJobModule::loadSelf()
    CppJobModule "luksbootkeyfile@luksbootkeyfile" loading complete. 
08:19:36 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "plymouthcfg" found anywhere at 
     "/etc/calamares/modules/plymouthcfg.conf" 
     "/usr/share/calamares/modules/plymouthcfg.conf" 
08:19:36 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "initramfs" found anywhere at 
     "/etc/calamares/modules/initramfs.conf" 
     "/usr/share/calamares/modules/initramfs.conf" 
08:19:36 [6]: virtual void Calamares::CppJobModule::loadSelf()
    CppJobModule "initramfs@initramfs" loading complete. 
08:19:36 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "sources-media-unmount" found anywhere at 
     "/etc/calamares/modules/sources-media-unmount.conf" 
     "/usr/share/calamares/modules/sources-media-unmount.conf" 
08:19:36 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "sources-final" found anywhere at 
     "/etc/calamares/modules/sources-final.conf" 
     "/usr/share/calamares/modules/sources-final.conf" 
08:19:36 [2]: void Calamares::Module::loadConfigurationFile(const QString&)
    WARNING: No config file for "umount" found anywhere at 
     "/etc/calamares/modules/umount.conf" 
     "/usr/share/calamares/modules/umount.conf" 
08:19:36 [6]: virtual void Calamares::CppJobModule::loadSelf()
    CppJobModule "umount@umount" loading complete. 
08:19:36 [2]: void Config::setConfigurationMap(const QVariantMap&)
    WARNING: Configuring the finished module with deprecated restartNowEnabled settings 
08:19:36 [6]: virtual void Calamares::ViewModule::loadSelf()
    ViewModule "finished@finished" loading complete. 
    .. Loaded QRC translation "kb_" "en" 
08:19:36 [6]: void Calamares::SlideshowQML::loadQmlV2Complete()
    QML component complete, API 2 
08:19:36 [6]: getting smart status failed for  "/dev/sda" :  Success
08:19:36 [6]: error during smart output parsing for  "/dev/sda" :  Success
08:19:36 [6]: getting smart status failed for  "/dev/sdb" :  Success
08:19:36 [6]: error during smart output parsing for  "/dev/sdb" :  Success
08:19:36 [6]: QList<Device*> PartUtils::getDevices(PartUtils::DeviceType)
    Removing unsuitable devices: 2 candidates. 
    .. Removing device with root filesystem (/) on it "/dev/sda" 
    .. Running ("blkid", "/dev/sdb") 
    .. Running ("blkid", "/dev/sdb1") 
    .. Running ("blkid", "/dev/sdb2") 
    .. there are 1 devices left. 
08:19:36 [6]: void PartitionCoreModule::doInit()
    LIST OF DETECTED DEVICES: 
    .. node	capacity	name	prettyName 
    .. "/dev/sdb" 34356994560 DevName$2d5869ed DevNamePretty$8c8d11c5 
    .. 1 devices detected. 
08:19:36 [6]: OsproberEntryList PartUtils::runOsprober(DeviceModel*)
    os-prober gave no output. 
    .. Loading "/etc/calamares/branding/debian/show.qml" 
08:19:36 [6]: void CalamaresApplication::initViewSteps()
    STARTUP: loadModules for all modules done 
08:19:36 [6]: void Calamares::ModuleManager::checkRequirements()
    Checking module requirements .. 
08:19:36 [6]: void CalamaresApplication::initViewSteps()
    STARTUP: Window now visible and ProgressTreeView populated 
    .. 8 view steps loaded. 
08:19:36 [6]: void Config::xkbApply()
    xkbmap selection changed to:  "us" - "" 
08:19:36 [6]: void ChoicePage::updateDeviceStatePreview()
    Updating partitioning state widgets. 
08:19:36 [6]: void ChoicePage::setupActions()
    Setting up actions for "/dev/sdb" with 0 entries. 
    ..  Partition "/dev/sdb1" authorized for resize + autopartition install. 
    .. contains resizable "/dev/sdb1" 
    ..  Checking if "/dev/sdb1" can be replaced. 
    ..  Partition "/dev/sdb1" authorized for replace install. 
    .. contains replaceable "/dev/sdb1" 
    ..  NO, insufficient storage 
     Required  storage B: 13421772800 "(12.5GiB)" 
     Available storage B: 10132405760 "(9GiB)" for "/dev/sdb2" length: 19789855 sectorsUsed: 0 fsType: "linuxswap" 
    ..  Checking if "/dev/sdb2" can be replaced. 
    ..  NO, insufficient storage 
     Required  storage B: 11274289152 "(10GiB)" 
     Available storage B: 10132405760 "(9GiB)" 
08:19:36 [6]: ChoicePage::setupActions()::<lambda()>
    Setting texts for 0 osprober entries 
08:19:36 [6]: void ChoicePage::continueApplyDeviceChoice()
    Previous device -1 new device 0 
08:19:36 [6]: void ChoicePage::applyActionChoice(InstallChoice)
    Prev -1 InstallChoice Config::NoChoice "none" 
08:19:36 [6]: bool ChoicePage::calculateNextEnabled() const
    No partitioning choice 
08:19:36 [6]: void ChoicePage::updateActionChoicePreview(InstallChoice)
    Updating partitioning preview widgets. 
08:19:36 [6]: void Calamares::RequirementsChecker::addCheckedRequirements(Calamares::Module*)
    Got 1 requirement results from "partition" 
08:19:36 [6]: bool GeneralRequirements::checkHasPower()
    A battery exists, checking for mains power. 
08:19:36 [6]: Calamares::RequirementsList GeneralRequirements::checkRequirements()
    GeneralRequirements output: 
     storage :   10737418240 
     enoughStorage :   true 
     RAM :   1073741824 
     enoughRam :   true 
     hasPower :   true 
     hasInternet :   unchecked 
     isRoot :   true 
08:19:36 [6]: void Calamares::RequirementsChecker::addCheckedRequirements(Calamares::Module*)
    Got 4 requirement results from "welcome" 
08:19:36 [6]: void Calamares::RequirementsChecker::finished()
    All requirements have been checked. 
08:19:36 [6]: void Calamares::RequirementsModel::describe() const
    Requirements model has 5 items 
    .. requirement 0 "partitions" satisfied? true mandatory? true 
    .. requirement 1 "storage" satisfied? true mandatory? true 
    .. requirement 2 "ram" satisfied? true mandatory? true 
    .. requirement 3 "power" satisfied? true mandatory? false 
    .. requirement 4 "root" satisfied? true mandatory? true 
08:19:55 [6]: void Config::guessLocaleKeyboardLayout()
    Got locale language "en_US.UTF-8" 
    .. looking for locale part "US" 
    .. matched "us" 
08:19:55 [6]: void guessLayout(const QStringList&, KeyboardLayoutModel*, KeyboardVariantsModel*)
    Next level: "en" 
08:19:59 [6]: void ChoicePage::applyActionChoice(InstallChoice)
    Prev -1 InstallChoice Config::Erase "erase" 
08:19:59 [6]: PartitionTable* CreatePartitionTableJob::createTable()
    CreatePartitionTableJob::createTable trying to make table for device "/dev/sdb" 
08:19:59 [6]: qint64 PartitionActions::swapSuggestion(qint64, Config::SwapChoice)
    Suggested swap size: 9 GiB 
08:19:59 [6]: void PartitionCoreModule::dumpQueue() const
    # Queue: 
    .. ## Device: "/dev/sdb" 
    .. - CreatePartitionTableJob 
    .. - CreatePartitionJob 
    .. - SetPartFlagsJob 
    .. - CreatePartitionJob 
08:19:59 [6]: void ChoicePage::updateActionChoicePreview(InstallChoice)
    Updating partitioning preview widgets. 
08:20:00 [6]: void PartitionCoreModule::setBootLoaderInstallPath(const QString&)
    PCM::setBootLoaderInstallPath "/dev/sdb"

**Comment by dalto8** [comment]
It looks like it is failing to find most of your config files.

Make sure you put them in the correct location.  You should also ensure that the file you are changing is the one Calamares is reading.

**Comment by adriaandegroot** [comment]
When changing configuration files, there is no need to re-build Calamares. You really shouldn't be relying on the configuration files from the Calamares repository **anyway**. Edit the configuration files on your live-ISO, or in your configuration package. You might even want to put a syntax error in `users.conf` just to confirm that Calamares is loading the file you think it should be loading.

(From a build directory where I run `calamares -d` I just confirmed that the *doAutologin* key (mind the capitalization there!) does affect the initial state of the checkmark as documented)

**Comment by StrongTiger-cloud** [comment]
thanks for all of your helps.

I have noticed that the installed configs at my host /etc/calamares/modules/users.conf is like the following, I can not find the settings <doAutologin: true> that comes from the sources :
---
userGroup:       users
defaultGroups:
    - cdrom
    - floppy
    - sudo
    - audio
    - dip
    - video
    - plugdev
    - netdev
    - lpadmin
    - scanner
    - bluetooth
autologinGroup:  autologin
sudoersGroup:    sudo
setRootPassword: false

**Comment by StrongTiger-cloud** [comment]
adriaandegroot and dalto8:
I had already checked and confirmed that my config file for calamares is located at /etc/calamares/modules/users.conf, but 
do not know why I can not find the set for the variable <doAutologin: true> from users.conf .

**Comment by demmm** [comment]
As noted now, this is not a bug report but a help request.
Please don't use issues as a help channel:
https://calamares.io/issues/
https://calamares.io/issues/#developers-of-distributions
If after following those guidelines, you still have questions, use the Matrix or IRC channel for further assistance.

**Comment by kkofler** [comment]
The config files are by default **not** installed from the Calamares sources, but usually packaged separately. So you are looking in the wrong place. In any case, I agree with @demmm that the missing setting is clearly not a bug in Calamares.
