### ISSUE TITLE
RFE - Use the same password for admin user should be default on

### ISSUE THREAD

**Issue by lucamosca1** [calamares/calamares#1891]
"issue" found installing Manjaro 21.2.2 xfce

IMHO a normal or not-so-tech user does not care about have a password for a user and a password to admin the system; but, since it's absolutely correct that the chance is available, I suggest to make this flag DEFAULT ON.

If the user decide to have different password can disable that flag so that password and password confirmation fields appears.

**Comment by demmm** [comment]
This is not an upstream issue, Calamares gives suggestion, it is up to your distribution to choose.
Fact is, Calamares default does set it as true:
https://github.com/calamares/calamares/blob/calamares/src/modules/users/users.conf#L54
So, report this request to your distribution.
