### ISSUE TITLE
Welcome module display error: "has at least one disk device available" 

### ISSUE THREAD

**Issue by akchen001** [calamares/calamares#1893]
Hello, community maintainer:
My calamares installer version is:3.2.36
My disk type is mmcblk,8G
The problem I encountered was detected in the first module welcome："has at least one disk device available" 
I'm sorry to trouble you so much

**Comment by demmm** [comment]
Make sure to read https://calamares.io/issues/ to file proper issues. That also means filling out the issue form presented to you completely.  Issue as is, is not useful, and needs to be closed if no full info is provided.

Are you an end user, and of what distribution?  Then make sure to first go to your distribution:
https://calamares.io/issues/#end-users

Are you a developer of a distribution?  Which one? Started the installer in debug mode, so a full backtrace of what happens can be examined?

**Comment by adriaandegroot** [comment]
See also issues #1885, #1105. Since you mention mmc, there's a reasonable chance it is being detected as a CD instead, and being ignored for that reason.

**Comment by akchen001** [comment]
Thank you very much for taking the time to check my problem. My problem has been solved. I will submit it in detail next time. Thank you again
