### ISSUE TITLE
Use of new ntfs3 fs driver instead of ntfs-3g

### ISSUE THREAD

**Issue by niansa** [calamares/calamares#1907]
**Is your feature request related to a problem? Please describe.**
The ntfs-3g driver is pretty slow and lacks lots of features required to even get a linux system up.

**Describe the solution you'd like**
Use of the new ntfs3 fs driver

**Comment by demmm** [comment]
Calamares is an installer framework, used by your distribution. It has no say whatsoever what version or variation of packages your distribution ships.  You need to go to your distribution to make requests like this.

**Comment by niansa** [comment]
Thanks a lot.
