### ISSUE TITLE
Hostname becoming 'tubophone.calamares.io'

### ISSUE THREAD

**Issue by lucasburlingham** [calamares/calamares#1908]
**Describe the bug**
Hostname becomes `tubophone.calamares.io` 

**To Reproduce**
Make and run the package.

**Expected behavior**
I expected calamares not to change anything about the hostname. I never asked it to, and it has never in the past.

I know that this is a low-effort report, but I need a low effort answer.

**Comment by adriaandegroot** [comment]
Are you running the tests as root, as part of the build? One of the tests (`src/modules/users/TestSetHostNameJob.cpp`) tells systemd to change the hostname.

**Comment by adriaandegroot** [comment]
Don't run the tests as root on a production system (the test is marked expected-to-fail because when run as a regular user, it can't change the hostname).

**Comment by lucasburlingham** [comment]
Thank you! I was surprised to see my hostname change (I didn't see it in any documentation, though correct me if I am wrong).

If I may ask, why does Calamares change the hostname of the system through systemd? Why not just pipe user input to `/etc/hostname`? It would seem that, by doing it without systemd, it would be more compatible with all systems, and would not require a test to be marked as 'expected-to-fail'.

Just a thought.
