### ISSUE TITLE
FS Selection Active for "Replace Partition" option

### ISSUE THREAD

**Issue by TechXero** [calamares/calamares#1911]
**Is your feature request related to a problem? Please describe.**

"Why when selecting the replace partition in cala does not allow me to change filesystem type and swap with it greyed out stuck at default choice?"

**Describe the solution you'd like**

When user selects the "Replace Partition" option file system selection should remain active allowing user to select a different one with swap if he chooses to...

**Comment by philmmanjaro** [comment]
As I see it the quick settings for file system and swap are only linked to erasing disk only. To specify more file systems you have to modify the [config file](https://github.com/calamares/calamares/blob/calamares/src/modules/partition/partition.conf#L159)

**Comment by TechXero** [comment]
I have it like that 

```
efiSystemPartition:     "/boot/efi"

userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Up to 4GB
    - suspend   # At least main memory size
    - file      # To swap file instead of partition

drawNestedPartitions:   false

alwaysShowPartitionLabels: true

initialPartitioningChoice: none

initialSwapChoice: none

defaultFileSystemType:  "btrfs"

availableFileSystemTypes:  ["btrfs","xfs","ext4"]
```

Still won't show

**Comment by philmmanjaro** [comment]
It will only show for erase disk. Not for replace partition! That would be a new feature.

**Comment by TechXero** [comment]
Ok so on the list ? LoL

**Comment by philmmanjaro** [comment]
Which list?

**Comment by TechXero** [comment]
Matter of speech... Feature for the future maybe ?

**Comment by adriaandegroot** [comment]
See branch *issue-1911* for initial work.

**Comment by adriaandegroot** [comment]
Branch *issue-1911* was merged in december, so this one is done.
