### ISSUE TITLE
Calamares crashes when calling setprogress()

### ISSUE THREAD

**Issue by dalto8** [calamares/calamares#1912]
**Describe the bug**
When a Python modules calls `libcalamares.job.setprogress()` too quickly the application crashes.

**To Reproduce**
Run this code:
```
while True:
    libcalamares.job.setprogress(0)
```

**Expected behavior**
Instead of crashing, it would be preferable to set the progress amount/message.

**Comment by adriaandegroot** [comment]
Confirmed (this is a dup of **something**, related to crashes in the packages module when pacman progress-reporting is enabled, isn't it?) Easy to reproduce, although replacing the `while` with something like `for r in range(100000)` doesn't trigger it for me.

**Comment by dalto8** [comment]
> this is a dup of something, related to crashes in the packages module when pacman progress-reporting is enabled, isn't it?

It is definitely the same issue.  I opened this because I didn't think we had an open issue to track it.

**Comment by adriaandegroot** [comment]
With pybind11, this stress test passes, with Boost, it crashes as reported. Closing with "we should be using pybind11 in future".
