### ISSUE TITLE
Log view should be more userfriendly

### ISSUE THREAD

**Issue by davidak** [calamares/calamares#1921]
**Is your feature request related to a problem? Please describe.**
As a user i want to follow the installation. I don't only want to see the current step (like "configuring system"), but a log of every finished step.

**Describe the solution you'd like**
The Log should show mainly the install steps with verbose output (every single package that is installed, what is configured etc.) and error messages secondary. The formatting should be human readable, not in error log style with timestamps. (or are the timestamps really useful?)

Please create design first and discuss it before starting implementing something.

**Describe alternatives you've considered**
Having a bad UX is not an alternative.

**Additional context**
I'm talking about the new log view added in https://github.com/calamares/calamares/pull/1899.

**Comment by adriaandegroot** [comment]
The log view does exactly what the people-who-built-it wanted (namely, show the log file, which is an entirely developer-oriented thing). Feel free, though, to PR an alternative. A copy of `LogWidget.h` and `LogWidget.cpp` without the threading or file-watching, that connects to the global `JobQueue` object and takes signal `progress(percent, prettyname)` and appends the *prettyname* to a text widget .. that would be a start for collecting all the messages that pass by in the progress bar.
