### ISSUE TITLE
About button on Welcome page confusing

### ISSUE THREAD

**Issue by jtojnar** [calamares/calamares#1922]
**Describe the bug**

The welcome page shows several buttons referring to the OS distribution being installed. However, when I click the “About” button, I am shown info about Calamares, not the OS.

https://github.com/calamares/calamares/blob/baf8ef2c33879511bcc168cae03ab0c2aee1f505/src/modules/welcomeq/welcomeq.qml#L66

And to make matters worse, languages like Czech translate this as “About the project”, which makes sense in regular applications but not so much in an installer, where it is not clear what the project is.

**To Reproduce**

1. Start Calamares
2. Click the “About” button
3. See that “About Calamares installer” pops up

**Expected behavior**
The button should be labelled “About the installer”, maybe moved away from the distribution-related buttons. Something like the following might work:

![Mockup of proposed Welcome page with Powered by Calamares moved away from the rest of the buttons](https://user-images.githubusercontent.com/705123/163074627-6f7b0595-bc2f-48a8-b38b-fe4af448e462.png)

**Screenshots and Logs**

![Current Welcome page](https://user-images.githubusercontent.com/705123/163074898-a3e5baa9-b532-4f93-80c2-b5f25aeeefa2.png)

**Comment by demmm** [comment]
You can wait for upstream to decide to implement this feature (or decide not to), but you can already do this by using welcomeq instead of the welcome module.  Any of the QML modules will read complete custom version of a .qml file when placed in the branding directory of your distribution.
https://github.com/calamares/calamares/blob/calamares/src/modules/welcomeq/welcomeq.qml#L54

**Comment by adriaandegroot** [comment]
I kinda like the "powered by Calamares" label; in terms of UI elements, though, that's in the "navigation bar" area, so it might be tricky to implement putting it exactly **there**. (There is a QML navbar which is easier to edit without re-compiling, and a Widget navbar in `CalamaresWindow.cpp`, function `getWidgetNavigation()`) Doable, though: I'd suggest showing that button only on the first step (maybe the last one, too), which is something you can arrange by connecting to the view manager's *currentStepChanged* signal.

You could also leave it inside the welcome page area (e.g. not the nav bar or the progress list).

For non-coding changes to the UI: the welcome page can be done in QML (as @demmm points out) or in Widgets, but the widgets part is generated from a Qt Designer .ui file. You could fiddle a bit with the UI with designer and see what you can achieve. The relevant file is `src/modules/welcome/WelcomePage.ui`. After editing needs a recompile.

**Comment by adriaandegroot** [comment]
@LordTermor I've implemented this in the progress-panel now, because **specifically** for the About button, it's really not part of the distro, it's part of Calamares itself and should, arguably, never have been in the Welcome module at all.
