### ISSUE TITLE
Recheck requirements regularly

### ISSUE THREAD

**Issue by davidak** [calamares/calamares#1924]
**Is your feature request related to a problem? Please describe.**
A user reported that they started the installer in a VM and the wired network took some time to be up. Calamares was already started and showed an issue about networking.

I was able to reproduce it on a system without connected wired network. I connected to Wifi, but Calamares already showed the network issue.

![Screenshot from 2022-04-13 03-51-28](https://user-images.githubusercontent.com/91113/163098916-1954cb07-f570-4016-9684-52d07c41902a.png)

**Describe the solution you'd like**
The requirement checks should be repeated every 2 (?) seconds until all are successful.

(Even the disk size can be increased at runtime in a Xen VM)

**Describe alternatives you've considered**
A user has to reboot or restart the installer program.

**Additional context**
Reported in https://github.com/NixOS/nixpkgs/pull/161788#issuecomment-1097242949

**Comment by adriaandegroot** [comment]
This is basically a dup of #1106, but adding some more implementation details:

- any module can return a list of requirements / check results; these are collected asynchronously by the module manager and each module's `checkRequirements()` method is synchronous.
- a check result is some strings and two bools.

There's no straightforward way to (re)check except by re-checking all the modules (I suppose that's ok) and I expect that the UI will be weird (how to indicate "still checking, but these are the results from the last time" when there are some things not satisfied).

**Comment by davidak** [comment]
>how to indicate "still checking, but these are the results from the last time

"rechecking in 5 .. 4 .. 3 .. 2 .. 1 progress" while the last word counts down. that way we can have longer time to recheck (5 secunds) and the user knows exactly what's happening when. they can fix the issue and don't have to wait long

**Comment by adriaandegroot** [comment]
Fixed for 3.3.0.

**Comment by jstnlth** [comment]
Nice. I'm happy for the opposite reason - because I always want to do offline installs (terrible bandwidth) and so if Internet is connected, I want to pull out the network cord before continuing.
