### ISSUE TITLE
Calamares segfaults with QT 5.15.3

### ISSUE THREAD

**Issue by towo2099** [calamares/calamares#1925]
Calamares 3.2.41 cannot start in latest Ubuntu 22.04 after updates of QT5 from 5.15.2 to 5.15.3

**To Reproduce**
1. Install Ubuntu 22.04, update to latest stand
2. Install Calamres
3. try to start it
4. look in journal

**Expected behavior**
Calamares should start

**Screenshots and Logs**

```
Apr 14 16:23:59 TUXEDOOS dbus-daemon[1651]: [system] Activating service name='org.kde.kpmcore.helperinterface' requested by ':1.7932' (uid=0 pid=24408 comm="/usr/bin/calamares --xdg-config " label="unconfined") (using servicehelper)
Apr 14 16:23:59 TUXEDOOS dbus-daemon[1651]: [system] Successfully activated service 'org.kde.kpmcore.helperinterface'
Apr 14 16:23:59 TUXEDOOS kernel: _tuxedo.calamar[24408]: segfault at 20 ip 00007fce831c209a sp 00007ffc9673d740 error 4 in libQt5Widgets.so.5.15.3[7fce830ec000+3de000]
Apr 14 16:23:59 TUXEDOOS kernel: Code: e8 7b 6d f3 ff e9 c3 e8 ff ff 48 8b 84 24 50 01 00 00 48 85 c0 0f 84 50 11 00 00 f3 41 0f 6f 7c 24 10 0f 29 bc 24 d0 00 00 00 <44> 8b 14 25 20 00 00 00 45 85 d2 0f 85 d6 cb ff ff c7 44 24 20 84
```

On older release-stand with qt5.15.2 calamares is working great.

**Comment by adriaandegroot** [comment]
> Install Ubuntu 22.04, update to latest stand

How? There isn't an Ubuntu 22.04 available for download from ubuntu.com (yeah, yeah, if you go to the mirror list, and hit one of the ftp mirrors, it has a 22.04/ directory .. this isn't making it easier to re-create your problem).

If you're rebuilding Calamares, then you should be able to provide a decent backtrace, too.

**Comment by adriaandegroot** [comment]
FWIW:
- installed 22.04-beta ISO
- clicked to do updates after install
- `apt install calamares calamares-settings-lubuntu` to get Calamares onto the system
- `apt search qt5core` to check that 5.13.3 is installed
- `calamares -D6` shows lubuntu setup

So, I've double-checked and can't reproduce.

**Comment by towo2099** [comment]
Then my branding style changes seems not compatible tio that qt5 version anymore.
Sorry for the noise.

**Comment by mdhishamsayed** [comment]
@towo2099 respected sir/maam could you please post the working stylesheet.qss , i too had that issue
