### ISSUE TITLE
I always got the user@user module error 

### ISSUE THREAD

**Issue by Vampire-Offical** [calamares/calamares#1927]
I always got the user@user module error  

after making the pkgbuild using makepkg command

**Comment by philmmanjaro** [comment]
You may start CAL in debug mode: `sudo calamares -D9` and check for errors like missing libraries. Most likely you have to rebuild Calamares against newer ICU.

> WARNING: No factory: "Cannot load library /usr/lib/calamares/modules/users/libcalamares_viewmodule_users.so: (libicuuc.so.71: cannot open shared object file: No such file or directory)"

**Comment by demmm** [comment]
As already noted, icu rebuild needed (second report of user module issue, which is icu related), but reports like this cannot be used.
Closing, and make sure to follow guidelines to create proper reports:
https://calamares.io/issues/
