### ISSUE TITLE
some trouble with rootfs zfs mounting in calamares latest iso

### ISSUE THREAD

**Issue by osevan** [calamares/calamares#1943]
https://termbin.com/2a37

Thanks and

Best regards

**Comment by demmm** [comment]
Make sure to use the issue template presented to you and read https://calamares.io/issues/ to file proper reports.
No-one can know now whether this is an end user showing a failed install, what distribution is in use or if this is a distribution you are developing.
Issue will be closed as is, please re-open if you can provide complete & useful info.
