### ISSUE TITLE
Calamares needs support for high DPI

### ISSUE THREAD

**Issue by highvoltage** [calamares/calamares#1945]
On high resolution displays, the Calamares window starts really small, making it difficult to use.
Myself and other users have managed to reproduce this, see the following bug report for an example:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=992162

I don't have a clear solution for this, and not sure what's possible in Qt, perhaps Calamares can adjust the size of UI elements when a certain resolution is detected, or just double its pixels.

**Comment by adriaandegroot** [comment]
Calamares has many many things configured per-pixel, and it has window sizes configured in pixels as well (see `branding.conf`). Step 1 would be knowing "when is it HiDPI?" There's surely an answer in the Plasma world already, and then pixel sizes could be bumped up as needed. (While many many things are configured per-pixel, there are only a couple of functions that actually do the math for finding those sizes)

**Comment by codesardine** [comment]
This seems to be present on GTK systems with 2k monitors on my other 3k monitor it works fine, a workaround is, export QT_AUTO_SCREEN_SCALE_FACTOR=1

**Comment by codesardine** [comment]
I seems this is missing in the code and adding could fix it, QApplication::setAttribute(Qt::AA_EnableHighDpiScaling) as @demmm  suggested.

**Comment by demmm** [comment]
@codesardine  Have you tested/tried building with `QApplication::setAttribute(Qt::AA_EnableHighDpiScaling) ` above https://github.com/calamares/calamares/blob/calamares/src/calamares/main.cpp#L110 ?

**Comment by codesardine** [comment]
No, I have no ideia how to build calamares and would have to ask someone in the team when they are available, I am familiar with QT API in Python but have have 0 C++ skills
