### ISSUE TITLE
Matrix link broken

### ISSUE THREAD

**Issue by es20490446e** [calamares/calamares#1950]
In the readme, the matrix link is broken.

The reason, spam-bots:
https://forum.kde.org/viewtopic.php?f=292&t=174194

Maybe use:
https://matrix.to/#/!cRLwScGKLiIvYzilRF:matrix.org?via=matrix.org&via=kde.org&via=peek-a-boo.at

**Comment by demmm** [comment]
If you mean this link:
https://webchat.kde.org/#/room/%23calamares:kde.org
Then the link is not broken, as long as you have an account.
You are referring to that link?

**Comment by es20490446e** [comment]
Yes, that link.

Account creation is locked down:
https://forum.kde.org/viewtopic.php?f=292&t=174194

**Comment by adriaandegroot** [comment]
The "Maybe use" link goes to the wrong room (the "old" Calamares Matrix room, which has been abandoned but not destroyed) **or**, in Firefox, drops me into Element which then tells me to join the conversation with an account.

I've added a suggestion to use IRC for guest-chat.
