### ISSUE TITLE
Shared library no longer found: libkpmcore.so

### ISSUE THREAD

**Issue by es20490446e** [calamares/calamares#1951]
Two nights ago I compiled Calamares. The next morning, when trying to run it, I got:

> /usr/bin/calamares: error while loading shared libraries: libkpmcore.so.11: cannot open shared object file: No such file or directory

I see that my distro, Manjaro, has updated `kpmcore` to have `libkpmcore.so.12`.

And here's my newbie question: what's the best chance I have to prevent this on my own Calamares package?

Thanks for your help.

**Comment by demmm** [comment]
Any time your distro updates a library that Calamares depends, it is up to you to rebuild Calamares, not a bug.

**Comment by es20490446e** [comment]
Do I have any alternative to that. Like statically linking that library?

Or would that be more troublesome?

**Comment by demmm** [comment]
This is not a Calamares question, but one for your distro. You need to ask there, if they provide static libs.  But as long as you are using a rolling distribution, expect to rebuild whenever libraries have changed.
