### ISSUE TITLE
Custom QML translation file not loader on new version of Calamares

### ISSUE THREAD

**Issue by patrick-emmabuntus** [calamares/calamares#1961]
Hello,

I am the main developper of Emmabuntüs distro ; https://en.wikipedia.org/wiki/Emmabunt%C3%BCs

I work now of Emmabuntüs Debian Edition based on Debian bookworm. I communicated with the maintainer of the Calamares package under Debian, and this one advises me to ask my question on your forum.

On the now package Calamares of Debian (3.2.57-1), I identified problems of my translate based on ts files when converted to qml file, are not displayed during slide show, and I didn't have this problem on Calamares version 3.2.36-1. You can see us Calamares translate file here : https://framagit.org/Emmabuntus/emmabuntus_de_5/-/tree/main/Package/branding_calamares/debian

Do you have any idea if there have been any changes in the qml format between these two Calamares versions?

Thanks in advance for your help.

**Comment by demmm** [comment]
See https://github.com/calamares/calamares-extensions how to test your QML, example given there (to use qmlscene):

```
qmlscene \
    -translation build/calamares-fancy_nl.qm \
    -I /usr/local/share/calamares/qml \
    -geometry 600x400 \
    fancy/show.qml
```

qmlscene will probably show why your translation is not showing.

**Comment by patrick-emmabuntus** [comment]
Thank you demmm for your very good advice.

I tested with this command adapted to calamares under Debian:

```
qmlscene \
    -translation /etc/calamares/branding/debian/lang/calamares-debian_fr.qm \
    -I /usr/share/calamares/qml \
    -geometry 600x400 \
    /etc/calamares/branding/debian/show.qml
```

And I can see the French translations loaded and the images in QMLScene.

So the problem must not be in the translations but in a search path for these translations which must have changed.

**Comment by demmm** [comment]
Make sure to check the Calamares log for any entries regarding not found translations & your used branding package.

**Comment by patrick-emmabuntus** [comment]
@demmm my log file which -d and -T options on Calamares : [session.log](https://github.com/calamares/calamares/files/8772558/session.log)

**Comment by demmm** [comment]
See  lines 7 - 11:
```
2022-05-25 - 17:22:51 [6]: Calamares::Branding::Branding(const QString&, QObject*)
    Using Calamares branding file at "/etc/calamares/branding/debian/branding.desc" 
2022-05-25 - 17:22:52 [6]: Calamares::Branding::Branding(const QString&, QObject*)
    Loaded branding component "debian" 
2022-05-25 - 17:22:52 [6]:     .. No translation for "tz_" "fr_FR" using default (en) 
``` 

So this mostly looks like a packaging issue. You had the branding in /etc before, have the translations files packaged relative to that directory?

**Comment by patrick-emmabuntus** [comment]
@demmm this is indeed a message of an issue, but which should not correspond to the translation for the slideshow, because I had the same message on the previous version of Calamares see the log file of this version: 
[session_calamares_3.2.36.log](https://github.com/calamares/calamares/files/8774615/session_calamares_3.2.36.log)


The QML files have not changed places between our two versions of our distribution, and they are in the "lang" folder in /etc/calamares/branding/debian/lang, see https://framagit.org/Emmabuntus/emmabuntus_de_5/-/tree/main/config/includes.chroot/etc/calamares/branding/debian

As I said when testing the default Calamares fancy theme, translations are also not loaded in this new version of Calamares.

**Comment by adriaandegroot** [comment]
There is something odd going on, that's for sure: using a default build of Calamares, running it as `calamares -d` from the build directory, using the default branding, translations aren't found / loaded **either**.

```
14:46:11 [6]: void Config::setLocaleIndex(int)
    Index 39 Selected locale "nl" 
    .. Branding no translation for "nl" using default (en) 
    .. Loaded QRC translation "tz_" "nl" 
    .. Loaded QRC translation "calamares_" "nl" 
```

There's weirdness in the build, too: it looks like the branding translations are build twice, in two different locations. (And neither of them are loaded, it seems)

**Comment by patrick-emmabuntus** [comment]
@adriaandegroot thank you for your feedback and I will await your expertise on this oddity.

**Comment by demmm** [comment]
FWIW, log here also shows the weirdness for loading, but translations are correct for the slideshow.

**Comment by patrick-emmabuntus** [comment]
@demmm you tested this with which version of Calamares and which distribution version?

**Comment by demmm** [comment]
Versions tested 3.2.57 on April ISO from KaOS and latest git (3.2.58) on local test ISO (also KaOS, independent distro).

**Comment by patrick-emmabuntus** [comment]
Indeed @demmm the translations work on KaOS.

**Comment by adriaandegroot** [comment]
## Scenario

Use this for the sequence in `settings.conf` (just so you don't have to go through a lot of steps; this is a highly irregular way to specify the sequence, but it **is** valid, and keeps this comment shorter):

```
sequence:
- show: [ welcome ]
- exec: [ dummyprocess ]
- show: [ finished ]
```

Then, run `./calamares -d` from the build directory. In the welcome screen, change to Dutch, or start the program with `LANG=nl  ./calamares -d` . In both cases, branding translations are not found, and the slideshow is in English even though the default branding contains suitable translations.

After adding some more debugging statements, I see this in the log:

```
    .. Loading "nl" from "calamares-default" in "/home/adridg/src/calamares/build/src/branding/default/lang" 
    .. Branding no translation for "nl" using default (en) 
```

The directory exists, the file `calamares-default_nl.qm` exists .. and yet it's not loading.

**Comment by adriaandegroot** [comment]
See the commit message for an explanation of what was going wrong. FWIW, I can't get it to display the slideshow in Arabic, even with this change.

**Comment by patrick-emmabuntus** [comment]
Thank you very much @adriaandegroot for all the efforts you have made to correct this little problem.

I tested your fix with your build script which is really handy on the live distro: https://github.com/calamares/calamares/wiki/Develop-Guide#quick-deployment-script

Now on my side it works, see this screenshot:

![Calamares_slideshow_fr](https://user-images.githubusercontent.com/84545964/170872294-e578a22d-f2bf-436a-9b5b-eab20c4848c8.png)

This even fixed a translation problem in the Calamares home page where the text was not correct in French, and was not large as in English:

![Calamares_intro](https://user-images.githubusercontent.com/84545964/170872419-3ccb8433-37d0-4a3b-984c-178718eb6c93.png)
