### ISSUE TITLE
Calamares "Segmentation Fault"

### ISSUE THREAD

**Issue by mdhishamsayed** [calamares/calamares#1983]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
This is from a distro maintainer
Hi Sir/Maam, have a nice day,
the calamares built in this bug report was v59 and the boost libraries version was v1.78 and the python version was v3.10.5
it was a 64 bit machine,both on real metal and virtualisation software
Both EFI & BIOS
disks were a 256GB ssd and a 20G hdd on real & virtual machines respectively
download link - https://mega.nz/file/nrwnQLIA#9Bu956qf2edp6hjSoIktgyAXW9yPphLSNXCyaPHpWcE

**To Reproduce**
1. Go to the mega page and please download the iso image
2. please start the iso image in a virtualisation software
3. open mate-terminal and start calamares with sudo calamares -d
4. please go throught the installation process, the crash shall happen somewhere between second QML slide (or) Reading from "/proc/partitions" looking for "sda" 

**Expected behavior**
the installer crashes and the installation aborts, that shall not happen and the installation shall continue.

**Screenshots and Logs**
Session Log File
[session.log](https://github.com/calamares/calamares/files/8861957/session.log)
This might be useful to you.
PKGBUILD ==>>
[PKGBUILD.txt](https://github.com/calamares/calamares/files/8861973/PKGBUILD.txt)

**Additional context**
there are two ways this problem might happen,
first one is the incorrect libraries that might be present, see the boost version which i use v1.78 is NOT compatible with python v3.10.5, i used those versions to compile it, boost 78 uses python 3.9 not 10..,before i used v59 of calamares. i was on v57 which worked perfectly until the update came and i had to recomple to v59,but, due to some conditions,python was updated and the v57 also stopped working. while i came here i see the problem happening.the arch repos have not even updated boost version and even the latest version of boost does not support python 3.9 that is also a problem. the problem otherwise might have happened due to a hardware error.. thanks in advance..
This error happens in cinnamon mate and xfce desktop

Related to
#1975

**Comment by demmm** [comment]
First of, boost 1.78 is used by many distritbutions in combination with python3.10, some patching might be needed, but that is nothing to discuss in a system installer issues section.

Then, again no sign of what distribution this is about, no log showing any error, again asking in a bug report that others do the work for you.
Third, there are no signs whatsoever you have done any research in properly setting Calamares variables for your distribution (as shown in the linked PKGBUILD).

Issues are for bug reports, they are not tutorials or a help channel. Thoroughly read all the documentation provided for you to deploy Calamares, **if** you then have questions left, ask in IRC.

One more time links:
https://calamares.io/issues/
https://github.com/calamares/calamares/wiki/Deploy-Guide
https://github.com/calamares/calamares/blob/calamares/src/modules/README.md

**Comment by kkofler** [comment]
Fedora Rawhide even uses Boost 1.78 with Python 3.11. (That requires [a one-line patch](https://src.fedoraproject.org/rpms/boost/raw/rawhide/f/boost-1.76.0-enum_type_object-type-python-3.11.patch), in addition to any fixing that may or may not be needed for 3.10.) But it is definitely not true that Boost 1.78 cannot work with Python > 3.9.
