### ISSUE TITLE
New Looks?

### ISSUE THREAD

**Issue by mdhishamsayed** [calamares/calamares#1984]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Well, it is not related to a problem but the calamares with the default (fusion) looks looks not so good, why does not someone design a new looks. New calamares release, new looks it might look good

**Describe alternatives you've considered**
there are not many alternatives but kvantum if you see needs to be activated in gtk based desktops and breeze style is too heavy which might result in enlarging of the size of iso, then new looks are preferred

**Comment by demmm** [comment]
Whatever style your distro sets has nothing to do with Calamares, it just **uses** that style you did set.
Not a Calamares issue.
