### ISSUE TITLE
ERROR: Installation failed: "The installer failed to format partition /dev/sda1 on disk 'VBOX HARDDISK

### ISSUE THREAD

**Issue by tulliana** [calamares/calamares#1989]
Calamares gives such an error when installing Archman KDE edition. We do not get the same error in our other desktop environments. I wonder if there are details I missed, what is the problem?

`Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    ERROR: Installation failed: "The installer failed to format partition /dev/sda1 on disk 'VBOX HARDDISK'."
    .. - message: "The installer failed to format partition /dev/sda1 on disk 'VBOX HARDDISK'."
    .. - details:
Create filesystem ext4 on partition ‘/dev/sda1’

Job: Delete file system on ‘/dev/sda1’

Command: wipefs --all /dev/sda1

Job: Create file system ‘ext4’ on partition ‘/dev/sda1’

Command: mkfs.ext4 -qF /dev/sda1

Command: sfdisk --part-type /dev/sda 1 0FC63DAF-8483-4772-8E79-3D69D8477DE4

Job: Check file system on partition ‘/dev/sda1’

Command: e2fsck -f -y -v /dev/sda1

09:10:55 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    Calamares will quit when the dialog closes.
09:10:55 [6]: void CalamaresUtils::callQmlFunction(QQuickItem*, const char*)
    QML "onLeave()" is missing.
09:10:55 [6]: void Config::doNotify(bool, bool)
    Notification not sent; completion: failed
09:10:58 [6]: void Config::doRestart(bool)
    mode= "never"  user wants restart? false force restart? false
Shutting down Calamares...
Finished shutdown.`

I have attached the entire output below
[archman-calamares-log.txt](https://github.com/calamares/calamares/files/8879117/archman-calamares-log.txt)

**Comment by adriaandegroot** [comment]
Probably an over-enthusiastic automount setting in the ISO. Disable it. (Calamares has code that tries to do so, but that fails because it is run as the wrong user)

**Comment by demmm** [comment]
Looks like a duplicate of https://github.com/calamares/calamares/issues/1885

**Comment by tulliana** [comment]
> See if the security box does not show if you adjust the stricter mounting in Plasma 5.24 systemsettings: Systemsettings > Removable Storage > Removable Devices > Un-tick `On Attach`

I checked if the same error log is opened but I couldn't see it, sorry. I saw your post and it solved my problem. Thank you. Kind regards.
