### ISSUE TITLE
Calamares 3.3.0 fails to install on EFI systems

### ISSUE THREAD

**Issue by ArrayBolt3** [calamares/calamares#1990]
**Describe the bug**
I'm installing Lubuntu 22.10 Kinetic Kudu Alpha as part of QA testing, and I and other QA testers have been unable to get a successful EFI installation using Calamares 3.3.0. Our distro's configuration files have been updated to work with Calamares 3.3.0.

Upon installation of the latest Lubuntu Kinetic ISO into a VM with EFI firmware, the installation appears to succeed, but on reboot, the system fails to boot. Further investigation reveals that nothing is being written to `/boot/efi`.

**To Reproduce**
1. Download the latest Lubuntu Kinetic ISO. It contains Calamares 3.3.0 and all updated configuration files.
2. Create a VM using QEMU, ensuring that it uses EFI firmware.
3. Open QTerminal, and run the following command sequence:
    sudo -E bash
    export $(dbus-launch)
    calamares -D6
4. Proceed with the installation, selecting "Erase disk" at the partitioning screen, and not setting up encryption.
5. When finished, do not reboot the system.
6. In QTerminal, run `mount /dev/sda1 /mnt` to mount the EFI partition (your VM might require `/dev/vda1` instead of `/dev/sda1`).
7. Run `ls /mnt`. There should be EFI files in there, but the directory will be empty.
8. Reboot the VM. It will fail to boot from the hard drive.

**Expected behavior**
The virtual machine should boot into Lubuntu normally.

**Screenshots and Logs**
https://pastebin.com/BApNmsQj Session.log file from a new installation in an EFI VM. Of particular note line 731:
    2022-06-11 - 23:26:41 [2]: WARNING: [PYTHON JOB]: "EFI system, and no bootloader is set."

**Additional context**
A legacy BIOS installation of Lubuntu using Calamares 3.3.0 works just fine.

After digging around in src/modules/bootloader/main.py, I discovered the notable log line I mentioned above is caused by `libcalamares.globalstorage.value("bootLoader")` being set to `None`. This is probably also the reason that the EFI partition is empty, since that indicates that `grub-install` is most likely not being executed or is erroring out. I can't see anything in our distro's Calamares configuration that might have caused this.

**Comment by demmm** [comment]
What checkout used to build Calamares?  Make sure to use the very latest commits.
Content of partition.conf used could be helpful.

**Comment by adriaandegroot** [comment]
Bear in mind, too, that there are changes to the config-files. Keys have changed. Names have changed. A set of Calamares-3.2 configuration files will **not** work with 3.3. Try running the configuration-validation tool `ci/configvalidator.py` against your config files.

**Comment by adriaandegroot** [comment]
Note in the linked log:

```
2022-06-11 - 23:24:02 [6]: virtual Calamares::JobResult FillGlobalStorageJob::exec()
    FillGlobalStorageJob writing empty bootLoader value 
```

That comes from the partitioning module, one of the jobs it runs. That explains the later no-bootloader setting, but then the question becomes: why is the bootloader path empty when the *partition* module writes it?

**Comment by demmm** [comment]
The way I see this now, for EFI there never was a bootLoader path/value for EFI systems (checked on a few older installs, all EFI show the same `FillGlobalStorageJob writing empty bootLoader value`).
But the bootloader module was never set to use that GlobalStorage entry for EFI system, only used for legacy BIOS.
You can test this by reverting:
https://github.com/calamares/calamares/commit/e15e57600e3df46ea2a14fff6a807fa354553ae1#diff-91818b0ce02fc61c3ff4b136101ee5f632a3a1febc46632dcd1dc4dc4ddc8594L801  (only edit the bootloader/main.py and revert to the original lines).

**Comment by ArrayBolt3** [comment]
> What checkout used to build Calamares? Make sure to use the very latest commits. Content of partition.conf used could be helpful.

I don't think I used the absolute latest commits, but I checked the commit history for everything after a commit I knew was applied, and saw nothing suspicious. I'll try again with a fresh build.

The configuration I'm using is on GitHub here: https://github.com/ArrayBolt3/calamares-settings-ubuntu/tree/ubuntu/kinetic/lubuntu/modules I fully updated it to work with Calamares 3.3.0 (to the best of my awareness), and it is capable of installing on BIOS systems. Here's my partition.conf:

    efiSystemPartition: "/boot/efi"
    enableLuksAutomatedPartitioning: true
    userSwapChoices:
        - none
        - file
    initialSwapChoice: file
    drawNestedPartitions: true
    defaultFileSystemType: "ext4"

> The way I see this now, for EFI there never was a bootLoader path/value for EFI systems (checked on a few older installs, all EFI show the same `FillGlobalStorageJob writing empty bootLoader value`). But the bootloader module was never set to use that GlobalStorage entry for EFI system, only used for legacy BIOS. You can test this by reverting: [e15e576#diff-91818b0ce02fc61c3ff4b136101ee5f632a3a1febc46632dcd1dc4dc4ddc8594L801](https://github.com/calamares/calamares/commit/e15e57600e3df46ea2a14fff6a807fa354553ae1#diff-91818b0ce02fc61c3ff4b136101ee5f632a3a1febc46632dcd1dc4dc4ddc8594L801) (only edit the bootloader/main.py and revert to the original lines).

I will do this test on the latest commits and report back my results.

**Comment by ArrayBolt3** [comment]
Tested with latest commits (build using deploycala.py), both with and without the diff reversion. Without the diff reversion, the EFI partition is still empty. After reverting the diff, the EFI partition was populated and the newly installed system was able to boot.
