### ISSUE TITLE
Manual Partitioning - selecting existing partition; no format & changing FS_LABEL doesn't reflect that on OK

### ISSUE THREAD

**Issue by guiverc** [calamares/calamares#1992]
This was reported with Lubuntu *kinetic* and is found here - https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/1978766

The issue is MINOR & doesn't impact operation.

**Describe the bug**
With MANUAL PARTITIONING I select a partition, select it for KEEP & MOUNT point then change FS_LABEL; on clicking OK to exit EDIT dialog, the FS_LABEL is not shown on prior screen (but selected mount point is).

**To Reproduce**
- my box has two partitions; SDA1 & SDA2
- start `calamares` installer
- select 'Manual Partitioning"
- select SDA1 and EDIT
  Content: KEEP  (this is what I tested; not sure if key)
  MOUNT: / (likely doesn't matter)
  FS_LABEL: (put in value here; I used SYS_1)
- click OK to return to prior dialog

**Expected behavior**
SDA1 would be mounting as "/" with new File_System_Label displayed

**Actual behavior**
SDA1 is mounted as "/" with no change to File_System_Label field shown 

**Screenshots and Logs**
I didn't keep logs, screenshots are
- dialog where SDA1 is entered; KEEP, MOUNT / & new label SYS_1 https://launchpadlibrarian.net/607184425/screen01.jpg
- prior dialog, SDA1 is shown as / but FS_LABEL is empty - https://launchpadlibrarian.net/607184462/screen02.jpg
- the change to FS_LABEL is shown in the summary DIALOG & works as expected - https://launchpadlibrarian.net/607184633/screen03.jpg

**Additional context**
Maybe after a change has been made; a text message on the prior dialog should report 'some details above may have changed' (ie. my screen2 or after exiting "Edit Existing Partition" dialog is exited) if unable to easily show new label value

Calamares installed - Candidate: 3.3.0~git20220610-0ubuntu1
`calamares --version` reports 3.3.0

As noted - this is only on onscreen 'less than ideal' issue, of little-no significance as operation is as it should be.

(this behavior has been noted before on launchpad/lubuntu, but I didn't find reference to it here upstream.  I have NOT noticed or tested for it on another distribution which I like doing before filing here)

**Comment by abalfoort** [comment]
I can confirm that this is the same behavior I see on Debian 11 and Debian 12. I have briefly looked into this but soon gave up because of the complexity and low priority as this issue does not prevent normal functionality.

**Comment by adriaandegroot** [comment]
Fixing this as part of #2283
