### ISSUE TITLE
Add Smart Card support (for full disc encryption)

### ISSUE THREAD

**Issue by 6543** [calamares/calamares#2000]
**Describe the solution you'd like**

If you select full disc encryption, allow to setup it up via a GPG-Smart-Card.

Nitrokey, Yubikey ... and more hardware tokens, finally become quite more common these days.
And so it should be easy even for beginners to use them to unlock their devices.

**Describe alternatives you've considered**
Develop a new tool that change a setup afterwards to get the same result ...

**Additional context**
- https://blog.mimacom.com/fde-with-yubikey/
- ...

**Comment by adriaandegroot** [comment]
That blog shows that you can add an additional key slot after installation (what it doesn't mention is "and then delete the weak key slot"). So it doesn't have to be in the installer at all.

For it to be part of the installer, you'd probably want some kind of "use a hardware token?" page -- probably *packagechooserq* is a good base for that kind of one-question pages, although it might need a specific "setup <thing>" page as well -- one to get a passphrase or whatever from the hardware token. It sounds like something you should PR to the *calamares-extensions* repository once you've got something.

**Comment by adriaandegroot** [comment]
Closing feature-request issues that don't get acted on inside a year (I think this might be a neat feature, but it needs some volunteer to step up and do the actual work).
