### ISSUE TITLE
[Calamares 3.2.60] error Boost.Python for the job "displaymanager": No such file or directory: '/tmp/calamares-root-eta6ae0b/etc/sddm.conf.d/kde_settings.conf'

### ISSUE THREAD

**Issue by f4iey** [calamares/calamares#2005]
**Describe the bug**
Since I updated to 3.2.60, I keep having this error occuring for the autologin configuration (just after user creation in the installation process). It seems like a file is missing somewhere.

```txt
 <class 'FileNotFoundError'> 
 [Errno 2] No such file or directory: '/tmp/calamares-root-eta6ae0b/etc/sddm.conf.d/kde_settings.conf' 
 File "/usr/lib/calamares/modules/displaymanager/main.py", line 1068, in run
    dm_message = dm.set_autologin(username, do_autologin, default_desktop_environment)

  File "/usr/lib/calamares/modules/displaymanager/main.py", line 824, in set_autologin
```

**To Reproduce**
1. Using the latest [F6KGL OS ISO](https://perso.esiee.fr/~benkemoj/downloads/f6kgl-2022.07.01-x86_64.iso)
2. Once booted in DE: `sudo calamares -d`
3. Leave *autologin* checkbox ticked
4. Start install and wait for the error to occur

**Expected behavior**
Setup autologin as the old versions did when I leave the *displaymanager* module default.

*Screenshots and Logs*
![image](https://user-images.githubusercontent.com/93203507/176933815-df86742c-eeed-4eb5-93ce-e2c44c7eef86.png)
```txt
18:41:53 [6]: virtual void Calamares::JobThread::run()
    Starting job "displaymanager" ( 27 / 35 ) 
18:41:53 [6]: virtual Calamares::JobResult Calamares::PythonJob::exec()
    Job file "/usr/lib/calamares/modules/displaymanager/main.py" 
[PYTHON JOB]: Found gettext "fr_FR" in "/usr/share/locale/fr_FR" 
    .. Job description from __doc__ "displaymanager" = "Configure display managers." 
[PYTHON JOB]: "slim selected but not installed" 
[PYTHON JOB]: "lightdm selected but not installed" 
[PYTHON JOB]: "gdm selected but not installed" 
[PYTHON JOB]: "mdm selected but not installed" 
[PYTHON JOB]: "lxdm selected but not installed" 
[PYTHON JOB]: "kdm selected but not installed" 
[PYTHON JOB]: "greetd selected but not installed" 
[PYTHON JOB]: "Using rootMountPoint '/tmp/calamares-root-eta6ae0b'" 
[PYTHON JOB]: ".. selected DE plasma" 
[PYTHON JOB]: "Setting up autologin for user f4iey." 
Python Error:
 <class 'FileNotFoundError'> 
 [Errno 2] No such file or directory: '/tmp/calamares-root-eta6ae0b/etc/sddm.conf.d/kde_settings.conf' 
 File "/usr/lib/calamares/modules/displaymanager/main.py", line 1068, in run
    dm_message = dm.set_autologin(username, do_autologin, default_desktop_environment)

  File "/usr/lib/calamares/modules/displaymanager/main.py", line 824, in set_autologin
    with open(sddm_conf_path, 'w') as sddm_config_file: 
 
18:41:53 [6]: virtual void Calamares::JobThread::run()
    Skipping non-emergency job "networkcfg" 
    ..  Skipping non-emergency job "hwclock" 
    ..  Skipping non-emergency job "services-systemd" 
    ..  Skipping non-emergency job "Initialistion du trousseau de clés" 
    ..  Skipping non-emergency job "packages" 
    ..  Skipping non-emergency job "grubcfg" 
    ..  Skipping non-emergency job "bootloader" 
    ..  Skipping non-emergency job "Démonter les systèmes de fichiers" 
18:41:53 [1]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    ERROR: Installation failed: "Erreur Boost.Python pour le job \"displaymanager\"." 
    .. - message: "Erreur Boost.Python pour le job \"displaymanager\"." 
    .. - details: <div><strong>&lt;class 'FileNotFoundError'&gt;</strong></div><div>[Errno 2] No such file or directory: '/tmp/calamares-root-eta6ae0b/etc/sddm.conf.d/kde_settings.conf'</div><div><br/>Traceback:</div><div><pre>File &quot;/usr/lib/calamares/modules/displaymanager/main.py&quot;, line 1068, in run
    dm_message = dm.set_autologin(username, do_autologin, default_desktop_environment)

  File &quot;/usr/lib/calamares/modules/displaymanager/main.py&quot;, line 824, in set_autologin
    with open(sddm_conf_path, 'w') as sddm_config_file:</pre></div>
18:41:54 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    Calamares will quit when the dialog closes. 
18:41:54 [6]: QML Component (default slideshow) deactivated
18:41:54 [6]: void Config::doNotify(bool, bool)
    Notification not sent; completion: failed 
18:44:09 [6]: void Config::doRestart(bool)
    mode= "never"  user wants restart? false force restart? false 
```

**Additional context**
My current calamares configuration is [available here](https://gitlab.com/f4iey/f6kgl-calamares-config)
This custom Arch Linux distro comes with SDDM.

**Comment by adriaandegroot** [comment]
@demmm don't forget that *calamares* (development) branch is 3.3, and the 3.2 series comes from *3.2.x-stable*; there's a fair bit of change between the two. That said, looking at `displaymanager/main.py` (and @f4iey , you can check this as well in your distro; that's one thing Python modules are nice for), it sets up:

(line 799)
```
        # Systems with Sddm as Desktop Manager
        sddm_conf_path = os.path.join(self.root_mount_point, "etc/sddm.conf")
```

Then tries to read and modify the file, then tries to write it (line 824). If the file doesn't exist on the target system, it ends up just trying to write it. And if there's a missing directory -- **is** there an `/etc/sddm.conf.d/` in the extracted filesystem? -- then this is how it will fail.

To fix, a PR might:
- use `mkdirs()` on `dirname()` of the configuration-path, to ensure the directory exists
- **or** catch the write-failure and do something more elegant than throw an exception.

As it stands, though, this largely looks like a distro-side problem (the directory sh0ould exist in the squashfs, and the module has been patched away from Calamares upstream).

**Comment by f4iey** [comment]
Thanks a lot guys for your detailed explanations!
Finally, I ended up building the current version myselft and it works back on track!
Something I didn't mention: I was using the binary package from the CARLI project. (I was too lazy to build it) Maybe the source code was edited...
But finally, it was worth the time spent.
Thank you so much for your help!

**Comment by demmm** [comment]
@adriaandegroot I already checked what they used, and noted it was a custom main.py for displaymanager, not at all from upstream Calamares.
