### ISSUE TITLE
[BUG Calamares 3.2.60] - Wrong date month and day language on GNOME topbar

### ISSUE THREAD

**Issue by D3vil0per** [calamares/calamares#2012]
**Describe the bug**
During my tests, I run Calamares Installer and at Locale pane, I set the arguments in the following manner:
![image](https://user-images.githubusercontent.com/83867734/177046673-dd6e6100-3b1c-4075-9218-1888d454f0a6.png)

So:
* Region as **Europe** and Zone as **Zurich**
* The system language will be set to **American English (United States)**
* The numbers and dates locale will be set to **Italiano (Italia)**

At this point I continued the installation until the end and then the system rebooted correctly.

At the reboot, on the GNOME topbar, I get:

![image](https://user-images.githubusercontent.com/83867734/177046795-6943a1bf-291c-4a46-a6a6-476b165561ac.png)

The topbar is reporting "dom 3 lug" (italian language meaning "Sun 3 Jul").

On the Settings -> Region & Language I have:

![image](https://user-images.githubusercontent.com/83867734/177046938-1ecd1154-300b-44c8-bfaa-101571e39b6e.png)

If I click on "Formats" I get:

![image](https://user-images.githubusercontent.com/83867734/177046967-2b3c153d-6bad-476d-84ef-b677e59375d3.png)

So here I have Dates & Times correctly in English language.

So the issue is on GNOME topbar because it takes language information by the wrong source.

**Expected behavior**
The GNOME topbar should show the date (month and day) in the same language specified during the installation in the field "The system language will be set to..."

**Additional context**
Arch Linux (5.18.8-arch1-1) using GDM, GNOME 42.2 and Wayland.

**Comment by demmm** [comment]
See my last comments in https://github.com/calamares/calamares/issues/2008
These issues are related, and the patch I linked fixes both, so closing this one, and lets continue in 2008

Please re-open if you find they are not related.

**Comment by D3vil0per** [comment]
> See my last comments in #2008 These issues are related, and the patch I linked fixes both, so closing this one, and lets continue in 2008
> 
> Please re-open if you find they are not related.

Thank you @demmm

**Comment by demmm** [comment]
The patch does not fix this one yet, but the commits I linked before are also causing this.  When you open the debug window, you will see that the Global Storage is never updated with what the GUI shows when clicking on the map to select Zurich.
No such issue when building Cala prior to the commits from June 18 & 19.
