### ISSUE TITLE
[logview] shows only version of CAL in Release build

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#2014]
**Describe the bug**
In a more recent version of Calamares you have now the option to toggle between slideshow and logview. The later only displays something useful if CAL got built in Debug mode: `DCMAKE_BUILD_TYPE=Debug`, not in Release build. There only the version of CAL got displayed and that's it.

**To Reproduce**
1. Build CAL as Release build via `DCMAKE_BUILD_TYPE=Release`
2. Install your system as usual
3. Toggle to logview during installation
4. You will only see the CAL version as only entry
5. Restart CAL with `-d` or `-D8` to see some in logview

**Expected behavior**
Display regular output you would also see via `pkexec calamares` in a terminal

**Screenshots and Logs**
![VirtualBox_manjaro_04_07_2022_20_36_00](https://user-images.githubusercontent.com/5050022/177207063-0e619e2f-9614-4291-b6d8-bef09ee967d1.png)

Sample screenshot with CAL in Debug mode:
![photo_2022-07-04_20-40-12](https://user-images.githubusercontent.com/5050022/177207126-a43b4180-5154-4d87-bd07-cba32ca2be7b.jpg)

**Comment by demmm** [comment]
If you don't want debug, do you really want to have logs?
Seems more logic to have the option to not show the Log toggle, if not running in any kind of debug mode, so seems this should be configurable:
https://github.com/calamares/calamares/blob/calamares/src/libcalamaresui/viewpages/ExecutionViewStep.cpp#L108

**Comment by philmmanjaro** [comment]
Well, seems a regular call of `pkexec calamares` doesn't show any logs so that logview is empty, which is correct. So I'd suggest to use the `-d` or any `-D{x}` flag to enable that toggle to be visible, as only in debug mode it seems to make sense to have it anyway as this state.

**Comment by adriaandegroot** [comment]
## Command Line Flags

```
  -d, --debug              Also look in current directory for configuration.
                           Implies -D8.
  -D <level>               Verbose output for debugging purposes (0-8).
```

The `-d` flag is something **quite** different from the `-D` flag. One enables debug / develop mode, which -1- enables the Debug Window -2- adds the current (build) directory to the module search path. The other is about debug-verbosity.

**Comment by philmmanjaro** [comment]
Ya, I know. `-d` gives you that hidden developer-view option to see the values you have set. More or less it makes no sense, at least for me, showing only a version number of Calamares in that logview when no verbose output level is set.

**Comment by adriaandegroot** [comment]
For 3.2, if you want to PR a "show toggle-log button only if the debug-level is > 2" (or whatever value you choose), go ahead. For 3.3, see the changelog: the log file is always written (generally at DEBUG, ie. `-D6` level) and only stdout is controlled by the `-D` flag).

**Comment by adriaandegroot** [comment]
Closing with "needs a PR (for 3.2 branch only)". Running `pkexec calamares` won't produce any output on stdout, normally, either: that means the logging is limited to errors, which you shouldn't have. My opinion is that any distro running Calamares 3.2 without `-D6` is doing itself and its users a disservice by making the log file useless in case something goes wrong (and then you need to tell the user to reproduce the problem with `-D6` anyway).

For Calamares 3.3, the log is always written as if level `-D6` or more was specified, and only stdout is impacted by the  command-line flag. In Calamares 3.3, the "show log" toggle always has something to show.
