### ISSUE TITLE
efiSystemPartitionSize controls minimal and default size at the same time

### ISSUE THREAD

**Issue by berolinux** [calamares/calamares#2018]
**Describe the bug**
Setting efiSystemPartitionSize sets the default size for the EFI System Partition when partitions are autoconfigured; however, the same setting is also used to check if the EFI System Partition is large enough for it to work.
This is somewhat problematic because a distribution may want to set a default in the range of 500 MB to allow coexisting with other operating systems (M$ seems to love really huge ESPs), while a user who knows what he's doing and wants to install only one distro will be perfectly happy with a 32 MB ESP containing only the bootloader.

**To Reproduce**
1. Set `efiSystemPartitionSize: 500M` in partition.conf (to make room for coexisting with other stuff)
2. Launch calamares, do custom partitioning and create a /boot/efi smaller than 500M
3. continue
4. Result: Calamares says the filesystem must be at least 500M

Or:

1. Set `efiSystemPartitionSize: 32M` (to please 1 OS, 1-distro installs)
2. Launch calamares, leave partitioning up to the installer
3. continue
4. The ESP is 32M, so someone adding another OS will likely have to create a new ESP or find some way to enlarge the existing one

**Expected behavior**
Automatic partitioning creates a bigger than needed ESP to make coexisting with some other OSes possible, but a user knowing he doesn't need that can shrink it to acceptable levels.

**Screenshots and Logs**

**Additional context**
Should be easy enough to fix, but I thought I'd bring it up as a bug report first so we can agree on a new name everyone will use. My proposal is to keep the current `efiSystemPartitionSize` for default size and add a new `efiMinimumPartitionSize` (if unset, defaulting to `efiSystemPartitionSize`) to specify a different minimal size.

**Comment by demmm** [comment]
Since the user can continue, while seeing that warning about partition size, wouldn't it be best to adjust the warning text? Now the warning looks like it can't be used, but in reality, it can continue just fine (though I think for most it still would be best to actually show some warning when using a smaller size then the distro recommends/sets).

**Comment by adriaandegroot** [comment]
Took a bit of reading, but I understand this issue as:
- when (auto) creating an EFI partition, use size *defaultsize*
- complain only if the EFI partition is below *minimalsize*

The proposed names seem fine to me. A PR would

- [ ] add the key and documentation to `partition.conf`
- [ ] extend the schema to include the new key
- [ ] get the Config object for partition to put the value into global storage; this is a **terrible** design choice, but it's what is already done for the `efiSystemPartitionSize` value (see the `_i` suffixed-key; that's the numeric value). It would be infinitely better to hold this in the Config object, or give *PartUtils* a decent API, or to move some of this information into the *partition* service in libcalamares, but I won't expect that kind of larger refactoring work as part of a feature-PR.
- [ ] Use the new `efiSystemPartitionMinimumSize` (`_i` extension optional; that extension is just another experssion of the terrible design choices already made) in `efiFilesystemMinimumSize()`

**Comment by adriaandegroot** [comment]
I chose to follow @demmm 's suggestion and change the wording, leaving the distro-recommended minimum as just that, a recommendation, and setting 32MiB as the absolute minimum.

**Comment by dalto8** [comment]
Is the minimum size configurable?  Many distros have a hard lower requirement because the kernels and initrds end up in the ESP.  For those distros supporting a hard 32 MiB minimum will will result in a failed install 100% of the time.
