### ISSUE TITLE
Calamares from Debian Live Install is not installing boot loader

### ISSUE THREAD

**Issue by lucasjkr** [calamares/calamares#2023]
I've been at this a few days, gave up and installed Fedora, then thought I could submit an issue for you to look at.

I am using a Dell XPS 9575. I would like to install Debian 11.4 on it.

When I attempt to boot from the standard Debian+Gnome image, the system doesn't recognize my wifi, trackpad or keyboard. Booting from their firmware image (which includes non-free firmware) solves that problem, I'm able to connect to wifi and then run the Calamares installer from start to finish, at which point it appears to be successful.

Upon rebooting, I'm left to discover that no bootloader has been installed. This also occurred when using an installer for Linux Mint Debian Edition.

Other Distros which Calamares install fine - Fedora, Ubuntu, Manjaro and PopOS all seem to install fine, this problem only seems to present itself on Debian-based distro (pure Debian or LMDE) but not Debian-derived distress (Ubuntu, Pop).

Any advice on this would be appreciated. I would prefer to run Debian over Fedora for the time being, but have been acutely unable to get it installed thanks to what I believe is an issue with Calamares.

Thank you!

**Comment by demmm** [comment]
Not clear if this is even related to Calamares. Distributions like you mention here, do not all use Calamares (Ubuntu, Fedora & Linux Mint for example have their own installer). Standard Debian also does not use Calamares.
But as an end user, this most of the time is not the right place to open a report:
https://calamares.io/issues/#end-users

**Comment by kkofler** [comment]
To be clear, Fedora **can** be installed with Calamares, but the installer you see by default on any of the official Editions or Spins is **not** Calamares. (The installer you get by default is called Anaconda. Note that that is **not** the same Anaconda as the one that installs Python modules, they only have in common that they both install something and that they both happen to be written in Python. It is also a completely different code base from Calamares.)

**Comment by lucasjkr** [comment]
Reopen this please. 

I noted that installations of Fedora, Ubuntu, etc were successful simply to demonstrate that the hardware itself is fine with Linux. 

The install is Failing only when using the Debian live media, which uses the calamares installer. The install appears to run successfully, but calamares isn’t writing a boot loader. That’s the issue I am trying to report

**Comment by dalto8** [comment]
> The install is Failing only when using the Debian live media, which uses the calamares installer. The install appears to run successfully, but calamares isn’t writing a boot loader. That’s the issue I am trying to report

Since the issue seems Debian-specific, this should be reported to Debian first.

**Comment by adriaandegroot** [comment]
.. and, if you get back here, with the information that demmm asked for. In particular, the installation log (it's generally in `~root/.cache/calamares/session.log`, you may need to run Calamares with the `-D6` flag to get a decently-detailed log). You're using a specific ISO? Please link to it. Are you using EFI, or BIOS? Is there anything else installed on the HDD already? This kind of information is needed to try to reproduce something vaguely-like your machine, in a VM.
