### ISSUE TITLE
Some modules do not build after improve-kpmcore merge

### ISSUE THREAD

**Issue by abalfoort** [calamares/calamares#2026]
**Describe the bug**
Modules fsresizer and partition are not built.

**To Reproduce**
1. Build from source:
```
rm -rf build
mkdir -p build
cd build
echo "### Calamares build log ###" > ../../buildonly.log
cmake -DSKIP_MODULES=$MODS -DCMAKE_BUILD_TYPE=Debug .. | tee -a ../../buildonly.log
make VERBOSE=1 | tee -a ../../buildonly.log
```
2. Check if fsresizer and partition modules are build/src/modules
3. Files are missing, but no error is logged.

**Expected behavior**
Build all modules correctly.

**Screenshots and Logs**
[buildonly.log](https://github.com/calamares/calamares/files/9158136/buildonly.log)

**Additional context**
If I run:
`git reset --hard 64eed3a40`
(commit prior to Kpmcore change)
The modules are built correctly.
[buildonly.log](https://github.com/calamares/calamares/files/9158136/buildonly.log)

**Comment by demmm** [comment]
Line 38 - 40:
```
-- KPMcore has been searched-for and not found
-- Could NOT find Qt5Location (missing: Qt5Location_DIR)
-- KPMcore has been searched-for and not found
```

I'll check the build with that commit, with latest packages (Qt, frameworks, kpmcore).

**Comment by demmm** [comment]
Same issue on latest KPMCore, also set to not found (thus no partition or fsresizer module build).

**Comment by adriaandegroot** [comment]
So, trace the cmake step. Add `message(STATUS ...)` all over the `KPMHelper.cmake` module. Run CMake again. Put a big ugly `message(FATAL_ERROR ..)` after the `find_package(KPMcore...)` command. Change the `if()` condition.

Your build log is strange: aside from including the build part, which is kind of pointless, the CMake part does not include the stderr output, which is exactly where the important bits show up. Namely, the message CMake produces while looking for KPMcore, and the list of modules skipped (and why they are skipped).

**Comment by abalfoort** [comment]
> ...the CMake part does not include the stderr output...
Sorry, I don't know how to do that.

**Comment by abalfoort** [comment]
I now get the error:
```
CMake Error at CMakeModules/KPMcoreHelper.cmake:45 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "KPMcore_FOUND" is not allowed.
Call Stack (most recent call first):
  src/modules/fsresizer/CMakeLists.txt:10 (include)
```

**Comment by kkofler** [comment]
> > ...the CMake part does not include the stderr output...
>
> Sorry, I don't know how to do that.

`2>&1`
