### ISSUE TITLE
Questions regarding calamares' font and theme

### ISSUE THREAD

**Issue by Ruturajn** [calamares/calamares#2027]
Hi,
I have been trying to deploy `calamares`, on a custom Arch ISO created using the `archiso` tool, and I wanted to know if there was any way, I could change the font, and the theme for `calamares`. I know, that the branding foldes has a `stylesheet.qss` file, but I am not sure, if that is where, I will be able to do it, or for that matter, how I should go about it. So, I would really appreciate some help with this.

Thanks

**Comment by adriaandegroot** [comment]
The theming documentation is in the wiki, section *Deployment - Configuration*. That refers to `branding.desc`, which contains documentation (in the example file in the Calamares repo) and `stylesheet.qss`. Read those. Calamares will pick up whatever your configured Qt theme is from the the user it runs as (so it may be needed to give the root user on your ISO a Qt theme configuration).

Using branding for colors and some styling is explained inline. The example stylesheet also has inline documentation.

**Comment by Ruturajn** [comment]
Thank you, I'll look into that.

**Comment by Ruturajn** [comment]
Also, I wanted to know, how I can change the line on the first screen that says, 
![image](https://user-images.githubusercontent.com/56625259/180594997-6ed25551-1218-43db-a108-c3f07fc3fe3e.png)
to something else.

Thanks

**Comment by demmm** [comment]
Please keep the issues to bug reports or feature request:
https://calamares.io/issues/
it is not a help channel:
https://calamares.io/issues/#developers-of-distributions
Use the links provided for you there to learn how to deploy Calamares.  If you should have questions left, use IRC or Matrix to get answers.
