### ISSUE TITLE
How to replace Debian installer with Calamares in Debian11?

### ISSUE THREAD

**Issue by ggonek1m** [calamares/calamares#2028]
I want to replace the installation program of Debian install with Calamares. What should I do?

**Comment by abalfoort** [comment]
You should ask this on the Debian forum. Post only here if you have an issue with the Calamares installer.

**Comment by demmm** [comment]
https://calamares.io/issues/
Issue reports are for bugs & features requests, it is not a help channel.
https://calamares.io/issues/#developers-of-distributions

**Comment by adriaandegroot** [comment]
`debian-live-11.0.0-amd64-gnome.iso` (I must have gotten that from the Debian site almost a year ago) at the very least already has Calamares as the installer, so there are examples available already.
