### ISSUE TITLE
can't load module partition

### ISSUE THREAD

**Issue by fengjian1993** [calamares/calamares#2035]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
root@debian:~/calamares-3.2.60/build# ./loadmodule partition
21:30:36 [6]: Calamares::Settings::Settings(const QString&, bool)
    Using Calamares settings file at "" 
21:30:36 [2]: Calamares::Settings::Settings(const QString&, bool)
    WARNING: Cannot read settings file "" 
21:30:36 [6]: bool CalamaresUtils::initQmlModulesDir()
    Using Calamares QML directory "/root/calamares-3.2.60/build/src/qml" 
21:30:36 [6]: int main(int, char**)
    Calamares module-loader testing "partition" 
21:30:36 [6]: Calamares::Module* load_module(const ModuleConfig&)
    Expected a descriptor file "src/modules/partition" 
    .. Module "partition" job-configuration: "/usr/lib/x86_64-linux-gnu/calamares/modules/partition/partition.conf" 
    .. got "partition" "view" "qtplugin" 
qt.qpa.xcb: X server does not support XInput 2
failed to get the current screen resources
21:30:36 [6]: Calamares::Branding::Branding(const QString&, QObject*)
    Using Calamares branding file at "src/branding/default/branding.desc" 
21:30:36 [6]: Calamares::Branding::Branding(const QString&, QObject*)
    Loaded branding component "default" 
21:30:36 [2]: bool Calamares::ModuleManager::checkModuleDependencies(const Calamares::Module&)
    WARNING: Module "partition" loaded externally, no dependency information. 
./loadmodule: symbol lookup error: /usr/lib/x86_64-linux-gnu/calamares/modules/partition/libcalamares_viewmodule_partition.so: undefined symbol: _ZN14CalamaresUtils9Partition10KPMManagerC1Ev

**Describe alternatives you've considered**

**Additional context**

**Comment by fengjian1993** [comment]
when run cmake, output as following:
--   Skipped bootloader (No Python support).
--   Skipped displaymanager (No Python support).
--   Skipped dracut (No Python support).
--   Skipped dummypython (No Python support).
--   Skipped dummypythonqt (No PythonQt support).
--   Skipped fsresizer (missing suitable KPMcore).
--   Skipped fstab (No Python support).
--   Skipped grubcfg (No Python support).
--   Skipped hwclock (No Python support).
--   Skipped initcpiocfg (No Python support).
--   Skipped initramfscfg (No Python support).
--   Skipped interactiveterminal (missing requirements).
--   Skipped localecfg (No Python support).
--   Skipped mkinitfs (No Python support).
--   Skipped mount (No Python support).
--   Skipped networkcfg (No Python support).
--   Skipped openrcdmcryptcfg (No Python support).
--   Skipped packages (No Python support).
--   Skipped partition (missing suitable KPMcore).
--   Skipped plasmalnf (missing requirements).
--   Skipped plymouthcfg (No Python support).
--   Skipped rawfs (No Python support).
--   Skipped services-openrc (No Python support).
--   Skipped services-systemd (No Python support).
--   Skipped unpackfs (No Python support).
--   Skipped webview (No suitable WebEngine).

**Comment by kkofler** [comment]
Your local Calamares build attempts to load a plugin from the system installation of Calamares, which is an older version and, as you can see, not binary-compatible.

**Comment by kkofler** [comment]
And this:

> -- Skipped partition (missing suitable KPMcore).

is probably the reason.

You need the `-dev' package for KPMcore to build the `partition` module. The module (and hence also the dependency) is technically optional, but in practice, Calamares is pretty useless without it.

Since you do not have a locally built `partition` module, but your configuration requires it, it goes on to look elsewhere, and ends up finding the old incompatible system version.

Closing as a user configuration issue, not a Calamares bug.
