### ISSUE TITLE
Support for the aura package manager

### ISSUE THREAD

**Issue by Botan-Yuukan** [calamares/calamares#2037]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when there isnt support for my fav. package manager. 

**Describe the solution you'd like**
I would like to see support be added for the aura package manager.

**Describe alternatives you've considered**
other package manager does not fit my style

**Additional context**
none

**Comment by dalto8** [comment]
To be clear, are you developing a distro?

If so, what is your use case?

Are you referring to [this](https://github.com/fosskers/aura)? If so, why does it make sense for calamares to support an AUR wrapper to begin with?  Adding support for every conceivable AUR wrapper seems like a nightmare.

**Comment by adriaandegroot** [comment]
This is completely up to you to implement. A PR against the *packages* module is welcome. If there is an underlying package manager and *aura* is a wrapper, then it is much preferred to use the underlying package manager during installation: the user doesn't see that happening at all. If aura is something special, then only you know how to call it properly.

**Comment by demmm** [comment]
Make sure to read about how to submit a proper bug report or feature request (starting with filling out the issue report fully):
https://calamares.io/issues/

Is this a request from an end user, that your distribution should include an extra option (an extra package manager this time)?
Then make sure to report this to your distribution, Clamares does not decide what downstream ships.
https://calamares.io/issues/#end-users

If this is from a distribution developer, then it is already answered above.  Upstream Calamares won't implement, but a PR is welcomed.

Issue will stay open for a bit longer, waiting for a response from submitter, but will be closed soon.

**Comment by dalto8** [comment]
I am going to go ahead and close this since no follow-up has been provided.  If there is more information to share please feel free to add a comment and we can re-open it if that is warranted.
