### ISSUE TITLE
I want to use calamares on CentOS. How should I modify the dependency?

### ISSUE THREAD

**Issue by ggonek1m** [calamares/calamares#2039]

**Comment by adriaandegroot** [comment]
The issue tracker is not a help forum. Use the chat channels for that. See eg. the *talk* section of https://calamares.io/issues/ .

Building Calamares is described on the wiki and in the [CONTRIBUTING](/calamares/calamares/CONTRIBUTING.md) document. See in particular https://github.com/calamares/calamares/blob/calamares/CONTRIBUTING.md#dependencies , which describes the dependencies (and points to the wiki as well). If you are having trouble getting through the CMake stage, you will need to chase the individual missing packages that CMake reports.

CentOS is available in several versions, some with very very old packages. Make sure you're using Calamares 3.2 branch, not the development branch. Calamares 3.2 is compatible with Debian 8 and other old Linux distributions. Calamares development (3.3) is for Debian-11 and other up-to-date (-ish) distro's.
