### ISSUE TITLE
bootloader error installation failed

### ISSUE THREAD

**Issue by sureshindiya** [calamares/calamares#2042]
Boost.Python error in job "bootloader".
Command 'grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Debian --force' returned non-zero exit status 1.
Installing for x86_64-efi platform.
grub-install: warning: Cannot set EFI variable Boot0000.
grub-install: warning: efivarfs_set_variable: writing to fd 6 failed: No space left on device.

grub-install: warning: _efi_set_variable_mode: ops->set_variable() failed: No space left on device.
grub-install: error: failed to register the EFI boot entry: No space left on device.

Traceback:
File "/usr/lib/x86_64-linux-gnu/calamares/modules/bootloader/main.py", line 477, in run
prepare_bootloader(fw_type)

File "<string>", line 8, in <module>

HOW TO SOLVE THIS PROBLEM WHILE INSTALLING LINUX DISTROS?

**Comment by dalto8** [comment]
It looks like your EFI partition may be full.

However, since every distro is a little different, you should troubleshoot through the distros support channels.

**Comment by sureshindiya** [comment]
> It looks like your EFI partition may be full.
> 
> However, since every distro is a little different, you should troubleshoot through the distros support channels.

pls help me in clearing filled efipartition

**Comment by demmm** [comment]
Make sure to read how to proper file an issue:
https://calamares.io/issues/
Is this a report from an end user?  Then see:
https://calamares.io/issues/#end-users

If this is a report from a distro developer, then it should be clear much more info is needed (as asked for in the issue template & linked above).  BUT, issues are not a help channel, they are for bug reports or new feature requests, read the Wiki pages, and if you still have questions then use IRC or Matrix to discuss.
