### ISSUE TITLE
usr/bin/chroot is failing initramfs-update

### ISSUE THREAD

**Issue by BCW52** [calamares/calamares#2043]
A problem with update initramfs-tools. Calamares is unable to execute initramfs-update. I tried to skip initramfs and initramcfg module on pkgbuild then it is showing initramfs module not found.
Calamares : https://github.com/BCW52/bengal-installer-zen
PKGBUILD: https://github.com/BCW52/bengal-installer

**Comment by dalto8** [comment]
In order to help with this we will need more information.  Like the full log output.

Make sure to read how to properly file an issue:
https://calamares.io/issues/

**Comment by demmm** [comment]
Plus, as the link shows, this is not build from Calamares, it is build from a fork.  Please file issues for Calamares only, there is no way to figure what all forks do.
