### ISSUE TITLE
libboost_python310.so.1.79.0: cannot open shared file: No such file or directory

### ISSUE THREAD

**Issue by izzy8799** [calamares/calamares#2050]
Making an image via alci-zen in a virtual machine, but in the image there is no working calamares, it gives an error: error while loading shared librares: libboost_python310.so.1.79.0: cannot open shared file: No such file or directory

**Comment by dalto8** [comment]
That probably means your Calamares was built against different library versions than what you have on your ISO.

Either rebuild Calamares against the libraries on your ISO or change the version of libboost installed on your ISO.

Alternatively, it could mean that your ISO doesn't have libboost installed at all.

**Comment by izzy8799** [comment]
> That probably means your Calamares was built against different library versions than what you have on your ISO.
> 
> Either rebuild Calamares against the libraries on your ISO or change the version of libboost installed on your ISO.
> 
> Alternatively, it could mean that your ISO doesn't have libboost installed at all. In that case, you need to include it on your ISO.

That is, I only need to embed libboost correct version?

**Comment by demmm** [comment]
If you search the issue reports, you will see this has been reported over and over and over.......
Anytime your distribution updates boost, it is up to you to rebuild Calamares against the correct (new) version of boost.
