### ISSUE TITLE
Locale setting problems immediately after installation

### ISSUE THREAD

**Issue by Jin-Asanami** [calamares/calamares#2053]
Hello. Please forgive my poor English.
This bug was occured when installing to a PC with 64-bit EFI and no Secure Boot enabled from an ISO image created with Archiso.
The point is that the correct locale is not displayed in the OS after installation.

The failure can be reproduced by the following procedure. In addition, the repository of "Chaotic AUR" must be added in advance when Step 1 is executed.

1. Create an ISO image in Archiso using the profile in "https://github.com/Jin-Asanami/univaiso-channels/" and write it to DVDs or USBs.
2. Insert the installation drive created in 1 into the PC and boot from the drive.
3. Run "Install System" from the Start Menu or "sudo calamares" from the terminal.
4. Select an appropriate language and proceed with the installation.
5. After restarting the PC, the contents of "/etc/locale.conf" are as follows.

Example:
```
LANG=ja_JP.UTF-8
LC_ADDRESS=ja_JP.UTF-8/UTF-8 \
LC_IDENTIFICATION=ja_JP.UTF-8/UTF-8 \
LC_MEASUREMENT=ja_JP.UTF-8/UTF-8 \
LC_MONETARY=ja_JP.UTF-8/UTF-8 \
LC_NAME=ja_JP.UTF-8/UTF-8 \
LC_NUMERIC=ja_JP.UTF-8/UTF-8 \
LC_PAPER=ja_JP.UTF-8/UTF-8 \
LC_TELEPHONE=ja_JP.UTF-8/UTF-8 \
LC_TIME=ja_JP.UTF-8/UTF-8 \
```

In addition, the following is added at the end of "/etc/locale.gen".

```
###
#
# Locales enabled by Calamares
# Missing: ja_JP.UTF-8/UTF-8 \
```

For this reason, languages other than American English, such as Japanese, will not be displayed correctly. Also, I thought that it might be bad because it was v3.2.61, so I downgraded it to v3.2.47 and executed it, but the result was the same.

Please teach me how to deal with it.

Version of Calamares I ran
3.2.47
3.2.60
3.2.61

Postscript
This is not me, but there seems to be some people in the forum in Manjaro who are suffering from the same phenomenon.
https://forum.manjaro.org/t/gnome-terminal-not-working-in-cinnamon-new-install/122151/

**Comment by dalto8** [comment]
That is an issue introduced by Arch in a recent glibc commit.  It has been fixed and should be corrected in the next version of glibc.

**Comment by Jin-Asanami** [comment]
Thank you for your reply! I'll try it right away.

**Comment by Jin-Asanami** [comment]
I created the ISO by incorporating the glibc v2.36-3 I put in my own repository, and Japanese was displayed correctly.

![VirtualBox_xfce_28_09_2022_15_50_57](https://user-images.githubusercontent.com/101626649/192709280-3dd888a1-5752-4815-a8cb-8af317665b89.png)

**Comment by demmm** [comment]
As reported in Telegram, above mentioned patch is applied downstream, closing.
