### ISSUE TITLE
User Module won't use /etc/skel for new user

### ISSUE THREAD

**Issue by pcrepix** [calamares/calamares#2062]
Hi.
I'm having an issue on Debian Testing & Calamares 3.2.61-1 (the version hosted by the Debian Repo's). I have setup conf files for the calamares modules in /etc/calamares, & they all seem to work, except for user creation. There the new user that gets created doesn't use the settings in /etc/skel... This worked previously (but I don't remember which was the last version that worked).
Thanks for any help,
rindi

**Comment by philmmanjaro** [comment]
You can always debug the installer via `sudo -E calamaers -d` A normal debug log can be started with `sudo -E calamares -D6`. The one with `-d` gives you also access to the debug tools. Simply check why the config in /`/etc/calamares` is not loaded.

**Comment by demmm** [comment]
And besides the above, post the .conf file you use that has this issue.

**Comment by adriaandegroot** [comment]
The user module runs `useradd` in the target system, so it follows whaterver that program does. Relevant code is in `src/modules/users/CreateUserJob.cpp` if you want to see the exact command. So you might (re)mount the target system after installation, or insert an interactive shell, and experiment in the target to see if the commands are "doing the right thing".

**Comment by pcrepix** [comment]
Thanks for the input.
It looks like Debian Testing has been updated to a version of "useradd" from which /etc/skel just won't get copied to the new user's account. It won't work from the terminal either, while the tool "adduser" works, but that doesn't use the same options as "useradd" does. I'll try finding an older version of the file that still works to get my system going again with Calamares.

**Comment by patrick-emmabuntus** [comment]
Hi all,
I confirm that following an evolution of Debian Bookworm, there was a regression during the installation with Calamares.
On October 22, there were these changes to the "passwd" package which contains the "useradd" utility: 
https://metadata.ftp-master.debian.org/changelogs//main/s/shadow/shadow_4.12.3+dfsg1-2_changelog
Now "useradd" add this new option : "-F, --add-subids-for-system   add entries to sub[ud]id even when adding a system user"
I don't know if this regression induced in Calamares is due to a desired evolution of "useradd" or if it is a regression of "useradd".
In any case, during the last assemblies of Emmabuntüs based on Debian Bookworm, I found the problem brought up by @pcrepix.

**Comment by dalto8** [comment]
Calamares isn't doing anything special here.  It is just calling `useradd`.  If `useradd -m` isn't copying the files from `/etc/skel`, that seems like a regression that should be reported to debian.

**Comment by demmm** [comment]
To add, see what is used:
https://github.com/calamares/calamares/blob/calamares/src/modules/users/CreateUserJob.cpp#L66

If that now needs adjusting for Debian, make sure to start testing what calls are now needed for Debian.

**Comment by patrick-emmabuntus** [comment]
Indeed the -m option of `useradd` no longer completely copies the contents of /etc/skel.
Depending on the contents of the /etc/skel folder, `useradd` fails to copy everything.
If /etc/skel doesn't contain any hidden folders it works to copy the config files present in the root of /etc/skel, but the contents of the folders are not even copied.
I will try to contact the maintainers of this package at Debian.

**Comment by pcrepix** [comment]
I have already tried reporting the Bug to Debian Previously, but that failed probably because I didn't know what package useradd belongs to. Now that you mentioned the passwd package, I have tried again. I'm not sure yet whether that worked, but here is the link:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023132

**Comment by patrick-emmabuntus** [comment]
Thank you @pcrepix for your feedback and personally, I sent an email to this list and to all the managers of this package.
On this mailing list, I was blocked because I am not registered on this one.

**Comment by pcrepix** [comment]
Thanks for the info.

**Comment by raymerjacque** [comment]
Following ...

**Comment by pcrepix** [comment]
Debian has closed the Bug, saying it is probably fixed, but the fix hasn't yet been published, so we are still waiting...

**Comment by patrick-emmabuntus** [comment]
Thanks @pcrepix for the info, and the fix is published here : https://packages.debian.org/sid/passwd and https://metadata.ftp-master.debian.org/changelogs//main/s/shadow/shadow_4.12.3+dfsg1-3_changelog

**Comment by pcrepix** [comment]
OK, Debian has updated the testing Repo with the new passwd package, & it is working now. I have tested useradd manually, & also with Calamares. All is OK.
Thanks & cheers.
