### ISSUE TITLE
No partition creation

### ISSUE THREAD

**Issue by MTCT-COMPUTERS** [calamares/calamares#2071]
While trying to install, there is no option to partition the hard disk.  If I boot up with the option of OEM install, I receive the option to partition the hard disk by running 'sudo calamares -D6' .  I do not receive the option if I boot up with regular KDE Neon install.

**Comment by demmm** [comment]
For proper issue creation see:
https://calamares.io/issues/
For end users:
https://calamares.io/issues/#end-users

Set to close soon, since this is not a usable report as is now.

**Comment by demmm** [comment]
No further response from submitter, closing.
