### ISSUE TITLE
Debug should be Debug in German not "Beheben von Fehlern" 

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#2072]
Debug should be Debug in German not "Beheben von Fehlern" 

https://www.transifex.com/calamares/calamares/translate/#de/calamares/419151915

As we can see it looks bad and is not fitting default GUI:
![2022-11-09_00-23](https://user-images.githubusercontent.com/16797647/200697396-7343e081-c8bd-4349-ad90-aa7d93874a99.png)
I do added a hint on transiflex.. but I have no clue if this will trigger anything to change the translation in calamares sources..

**Comment by demmm** [comment]
Translations are done in Transifex:
https://github.com/calamares/calamares/wiki/Translate-Guide
Please make the correction there.
