### ISSUE TITLE
Issue #1757 not resolved, please reopen

### ISSUE THREAD

**Issue by eeickmeyer** [calamares/calamares#2073]
@demmm I'm standing next to @adriaandegroot , we discussed this per https://bugs.launchpad.net/ubuntu/+source/calamares-settings-ubuntu/+bug/1984136. Please reopen? 

Thanks! :)

**Comment by demmm** [comment]
I have nothing to do with that feature request, did not open or close it. Bigger question, why open an issue to re-open a request, without a link.....

**Comment by dalto8** [comment]
I took care of it.
