### ISSUE TITLE
100% CPU before LUKS password

### ISSUE THREAD

**Issue by Dmole** [calamares/calamares#2076]
**Describe the bug**
100% CPU before LUKS password
64 bit x86 KVM btrfs.

**To Reproduce**
1. Install the LUKS/btrfs option in any distro using Calamares (Spiral, Endeavour) in KVM
2. reboot and don't type in a password.

**Expected behavior**
Let the CPU idle like Debian, Fedora, etc do.

**Additional context**
https://github.com/SpiralLinux/SpiralLinux-project/issues/198

**Comment by demmm** [comment]
Do you mean to say, if Calamares is used in Debian for this setup, issue does not occur? Not clear how an installer has anything to do with LUKS/btrfs behavior, long after the installer is done, and system has rebooted into the new install.

**Comment by dalto8** [comment]
Does your Debian install have an unencrypted `/boot`?  It could be the difference between grub doing the decryption and the initrd/initramfs doing it.

Calamares isn't doing anything special here.  It sounds like an issue with grub that should probably be reported upstream to grub.

**Comment by Dmole** [comment]
@dalto8 yes both Debian and Fedora place boot outside of LUKS (Spiral and Endeavour place boot inside LUKS).
I hope grub considers CPU idle in scope, if not is there an option in Calamares to place boot outside of LUKS/btrfs?
(would remove the option to roll back kernel updates)

**Comment by dalto8** [comment]
> if not is there an option in Calamares to place boot outside of LUKS/btrfs?

Yes, you can use manual partitioning and create a separate partition for `/boot` that isn't encrypted.

**Comment by kkofler** [comment]
Indeed. Long ago, there used to be several problems when attempting to use separate unencrypted `/boot` with Calamares, but they should be all fixed now. So it can be done with manual partitioning. If it (still/again) does not work, please file a new issue here.

As for "It sounds like an issue with grub that should probably be reported upstream to grub.", well, it is a known issue that GRUB does not use AES-NI or vector instructions to unencrypt, so it makes heavier use of the CPU and is slower than the implementations in the kernel or userspace. Artificially reducing CPU usage by putting it into idle does not make sense, it would only make decryption even slower, and I see no valid reason to not make use of the CPU power that is available. (If your CPU does not handle that load, it is broken, overclocked, or undercooled, so it needs to be replaced, underclocked, or cooled more aggressively.)

**Comment by kkofler** [comment]
And the reason GRUB does not use AES-NI nor vector instructions is that the code in GRUB is heavily optimized for space, to fit even into tiny slots like the MBR, not for speed, and that it is not optimized specifically for your CPU, but needs to work on all x86_64 CPUs. Any instructions beyond the x86_64 baseline would have to be runtime-detected and use a separate copy of the code, which would significantly increase the size of the machine code.

**Comment by Dmole** [comment]
> ...don't type in a password...

> ...GRUB does not use AES-NI...

The issue is  before  any decryption is attempted.

**Comment by Dmole** [comment]
https://github.com/calamares/calamares/issues/1938#issuecomment-1323051911

**Comment by bigsmile74** [comment]
Hi,

I figured there are more people out there running into the same issue. So I decided to post here as well.

---snip---
_I am a Debian 12 (released on June 10th, 2023) user running into the same issue. (currently at 12.6)

During installation I opted for "full disk encryption" which includes /boot. My situation is more cumbersome as I use a passively cooled computer without any fans. Besides draining my energy bill the computer gets HOT! I've measured 160°F/71°C on the chassis (a big cooling block) which is still within spec, but very undesirable over longer periods of time.

To make matters worse, there is an option in the BIOS "AC power loss" which does not work properly. The computer turns on after power loss, no matter the setting. Effectively turning it into a frying pan while begin asleep or not at home. So if the power grid glitches, my computer turns on :scream:

A desirable solution to my problem would be to idle and power off after no input for a given period._
---snip---

**Comment by dalto8** [comment]
It sounds like the issue here is that when using grub for decryption, there is high CPU usage at the decryption prompt.  This is really an issue that should be reported to grub, not Calamares.

Calamares already supports not encrypting the `/boot` partition if that is your preference to work-around this issue.  Calamares also already supports bootloaders other than grub.

I am going to close this because I don't believe there is anything that can be done on the Calamares side to resolve this issue.
