### ISSUE TITLE
Grub config generated with duplicate '/boot/boot/' path when setting custom boot (/boot) + root (/) partition.conf template

### ISSUE THREAD

**Issue by GloriousEggroll** [calamares/calamares#2077]
I'm trying to get calamares 3.2.61 working on fedora with a template for separate /boot and /btrfs root (/) partitions.

I'm using the following custom partition scheme:

/usr/share/calamares/modules/partition.conf 

partitionLayout:
    - name: ""
      filesystem: "ext4"
      mountPoint: "/boot"
      size: 1G
    - name: ""
      filesystem: "btrfs"
      mountPoint: "/"
      size: 100%

and the following subvolume btrfs mount options:

/usr/share/calamares/modules/mount.conf 

btrfsSubvolumes:
     - mountPoint: /
       subvolume: /@root

and the following to unpack everything:

/usr/share/calamares/modules/unpackfs.conf

unpack:
    -   source: "/dev/mapper/live-base"
        sourcefs: "ext4"
        destination: ""

In the partitions section of the installer I choose Erase Disk, Swap with Hibernate, and everything appears to look fine:

![Screenshot from 2022-11-19 12-50-10](https://user-images.githubusercontent.com/11287837/202864584-63a7fe13-4ae2-423c-b3b0-02afeda11777.png)

But after the install finishes, grub fails to boot the kernel:

 
![Screenshot from 2022-11-19 12-57-35](https://user-images.githubusercontent.com/11287837/202864906-6fee66b8-6bb1-4173-b4d4-ed51835031b0.png)
![Screenshot from 2022-11-19 12-57-54](https://user-images.githubusercontent.com/11287837/202864910-c19aa33a-cb37-4823-92fe-6e698262d93f.png)

Inspection reveals a duplicate '/boot' entry added to the linux and initrd path:

![Screenshot from 2022-11-19 12-58-07](https://user-images.githubusercontent.com/11287837/202864915-dc8f8777-dcd9-4417-81f1-32fcb53b139d.png)

If I remove the '/boot/' from those paths then ctrl+x to continue the boot process, the system boots as expected. A look at grubby reveals the same issue:

```
# grubby --default-kernel
/boot/boot/vmlinuz-6.0.8-202.fsync.fc36.x86_64
```

Note, I also tried this using:

/usr/share/calamares/modules/mount.conf 

btrfsSubvolumes:
     - mountPoint: /
       subvolume: ""

With the same resulting problem minus a subvolume being defined in the grub options.

**Comment by dalto8** [comment]
What version of Calamares are you using?

Can we see the full contents of `partition.conf`

**Comment by GloriousEggroll** [comment]
> What version of Calamares are you using?
```
calamares 3.2.61 
```


> Can we see the full contents of `partition.conf`

Sure, sorry for the paste, hope its collapsable, could not add .conf as file attachment type:

`
# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# This setting specifies the mount point of the EFI system partition. Some
# distributions (Fedora, Debian, Manjaro, etc.) use /boot/efi, others (KaOS,
# etc.) use just /boot.
#
# Defaults to "/boot/efi", may be empty (but weird effects ensue)
efiSystemPartition:     "/boot/efi"

# This optional setting specifies the size of the EFI system partition.
# If nothing is specified, the default size of 300MiB will be used.
#
# This size applies both to automatic partitioning and the checks
# during manual partitioning. A minimum of 32MiB is enforced,
# 300MiB is the default, M is treated as MiB, and if you really want
# one-million (10^6) bytes, use MB.
#
efiSystemPartitionSize:     600M

# This optional setting specifies the name of the EFI system partition (see
# PARTLABEL; gpt only; requires KPMCore >= 4.2.0).
# If nothing is specified, the partition name is left unset.
# efiSystemPartitionName:     EFI

# In autogenerated partitioning, allow the user to select a swap size?
# If there is exactly one choice, no UI is presented, and the user
# cannot make a choice -- this setting is used. If there is more than
# one choice, a UI is presented.
#
# Legacy settings *neverCreateSwap* and *ensureSuspendToDisk* correspond
# to values of *userSwapChoices* as follows:
#    - *neverCreateSwap* is true, means [none]
#    - *neverCreateSwap* is false, *ensureSuspendToDisk* is false, [small]
#    - *neverCreateSwap* is false, *ensureSuspendToDisk* is true, [suspend]
#
# Autogenerated swap sizes are as follows:
#    - *suspend*: Swap is always at least total memory size,
#      and up to 4GiB RAM follows the rule-of-thumb 2 * memory;
#      from 4GiB to 8 GiB it stays steady at 8GiB, and over 8 GiB memory
#      swap is the size of main memory.
#    - *small*: Follows the rules above, but Swap is at
#      most 8GiB, and no more than 10% of available disk.
# In both cases, a fudge factor (usually 10% extra) is applied so that there
# is some space for administrative overhead (e.g. 8 GiB swap will allocate
# 8.8GiB on disk in the end).
#
# If *file* is enabled here, make sure to have the *fstab* module
# as well (later in the exec phase) so that the swap file is
# actually created.
userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Up to 4GB
    - suspend   # At least main memory size
    # - reuse     # Re-use existing swap, but don't create any (unsupported right now)
    - file      # To swap file instead of partition

# This optional setting specifies the name of the swap partition (see
# PARTLABEL; gpt only; requires KPMCore >= 4.2.0).
# If nothing is specified, the partition name is left unset.
# swapPartitionName:      swap

# LEGACY SETTINGS (these will generate a warning)
# ensureSuspendToDisk:    true
# neverCreateSwap:        false

# Correctly draw nested (e.g. logical) partitions as such.
drawNestedPartitions:   true

# Show/hide partition labels on manual partitioning page.
alwaysShowPartitionLabels: true

# Allow manual partitioning.
#
# When set to false, this option hides the "Manual partitioning" button,
# limiting the user's choice to "Erase", "Replace" or "Alongside".
# This can be useful when using a custom partition layout we don't want
# the user to modify.
#
# If nothing is specified, manual partitioning is enabled.
#allowManualPartitioning:   true

# Initial selection on the Choice page
#
# There are four radio buttons (in principle: erase, replace, alongside, manual),
# and you can pick which of them, if any, is initially selected. For most
# installers, "none" is the right choice: it makes the user pick something specific,
# rather than accidentally being able to click past an important choice (in particular,
# "erase" is a dangerous choice).
#
# The default is "none"
#
initialPartitioningChoice: none
#
# Similarly, some of the installation choices may offer a choice of swap;
# the available choices depend on *userSwapChoices*, above, and this
# setting can be used to pick a specific one.
#
# The default is "none" (no swap) if that is one of the enabled options, otherwise
# one of the items from the options.
initialSwapChoice: none

# Default partition table type, used when a "erase" disk is made.
#
# When erasing a disk, a new partition table is created on disk.
# In other cases, e.g. Replace and Alongside, as well as when using
# manual partitioning, this partition table exists already on disk
# and it is left unmodified.
#
# Suggested values: gpt, msdos
# If nothing is specified, Calamares defaults to "gpt" if system is
# efi or "msdos".
#
# Names are case-sensitive and defined by KPMCore.
# defaultPartitionTableType: msdos

# Requirement for partition table type
#
# Restrict the installation on disks that match the type of partition
# tables that are specified.
#
# Possible values: msdos, gpt. Names are case-sensitive and defined by KPMCore.
#
# If nothing is specified, Calamares defaults to both "msdos" and "gpt".
#
# requiredPartitionTableType: gpt
# requiredPartitionTableType:
#     - msdos
#     - gpt

# Default filesystem type, used when a "new" partition is made.
#
# When replacing a partition, the existing filesystem inside the
# partition is retained. In other cases, e.g. Erase and Alongside,
# as well as when using manual partitioning and creating a new
# partition, this filesystem type is pre-selected. Note that
# editing a partition in manual-creation mode will not automatically
# change the filesystem type to this default value -- it is not
# creating a new partition.
#
# Suggested values: ext2, ext3, ext4, reiser, xfs, jfs, btrfs
# If nothing is specified, Calamares defaults to "ext4".
#
# Names are case-sensitive and defined by KPMCore.
defaultFileSystemType:  "btrfs"

# Selectable filesystem type, used when "erase" is done.
#
# When erasing the disk, the *defaultFileSystemType* is used (see
# above), but it is also possible to give users a choice:
# list suitable filesystems here. A drop-down is provided
# to pick which is the filesystems will be used.
#
# The value *defaultFileSystemType* is added to this list (with a warning)
# if not present; the default pick is the *defaultFileSystemType*.
#
# If not specified at all, uses *defaultFileSystemType* without a
# warning (this matches traditional no-choice-available behavior best).
# availableFileSystemTypes:  ["ext4","f2fs"]

# Show/hide LUKS related functionality in automated partitioning modes.
# Disable this if you choose not to deploy early unlocking support in GRUB2
# and/or your distribution's initramfs solution.
#
# BIG FAT WARNING:
#
# This option is unsupported, as it cuts out a crucial security feature.
# Disabling LUKS and shipping Calamares without a correctly configured GRUB2
# and initramfs is considered suboptimal use of the Calamares software. The
# Calamares team will not provide user support for any potential issue that
# may arise as a consequence of setting this option to false.
# It is strongly recommended that system integrators put in the work to support
# LUKS unlocking support in GRUB2 and initramfs/dracut/mkinitcpio/etc.
# For more information on setting up GRUB2 for Calamares with LUKS, see
# https://github.com/calamares/calamares/wiki/Deploy-LUKS
#
# If nothing is specified, LUKS is enabled in automated modes.
#enableLuksAutomatedPartitioning:    true

# Partition layout.
#
# This optional setting specifies a custom partition layout.
#
# If nothing is specified, the default partition layout is a single partition
# for root that uses 100% of the space and uses the filesystem defined by
# defaultFileSystemType.
#
# Note: the EFI system partition is prepend automatically to the layout if
# needed; the swap partition is appended to the layout if enabled (small of
# suspend).
#
# Otherwise, the partition layout is defined as follow:
#
# partitionLayout:
#     - name: "rootfs"
#       type: "4f68bce3-e8cd-4db1-96e7-fbcaf984b709"
#       filesystem: "ext4"
#       mountPoint: "/"
#       size: 20%
#       minSize: 500M
#       maxSize: 10G
#       attributes: 0xffff000000000003
#     - name: "home"
#       type: "933ac7e1-2eb4-4f13-b844-0e14e2aef915"
#       filesystem: "ext4"
#       mountPoint: "/home"
#       size: 3G
#       minSize: 1.5G
#       features:
#         64bit: false
#         casefold: true
#     - name: "data"
#       filesystem: "fat32"
#       mountPoint: "/data"
#       features:
#         sector-size: 4096
#         sectors-per-cluster: 128
#       size: 100%
#
# There can be any number of partitions, each entry having the following attributes:
#   - name: filesystem label
#           and
#           partition name (gpt only; since KPMCore 4.2.0)
#   - uuid: partition uuid (optional parameter; gpt only; requires KPMCore >= 4.2.0)
#   - type: partition type (optional parameter; gpt only; requires KPMCore >= 4.2.0)
#   - attributes: partition attributes (optional parameter; gpt only; requires KPMCore >= 4.2.0)
#   - filesystem: filesystem type (optional parameter)
#       - if not set at all, treat as "unformatted"
#       - if "unformatted", no filesystem will be created
#       - if "unknown" (or an unknown FS name, like "elephant") then the
#         default filesystem type, or the user's choice, will be applied instead
#         of "unknown" (e.g. the user might pick ext4, or xfs).
#   - mountPoint: partition mount point (optional parameter; not mounted if unset)
#   - size: partition size in bytes (append 'K', 'M' or 'G' for KiB, MiB or GiB)
#           or
#           % of the available drive space if a '%' is appended to the value
#   - minSize: minimum partition size (optional parameter)
#   - maxSize: maximum partition size (optional parameter)
#   - features: filesystem features (optional parameter; requires KPMCore >= 4.2.0)
#       name: boolean or integer or string

# Checking for available storage
#
# This overlaps with the setting of the same name in the welcome module's
# requirements section. If nothing is set by the welcome module, this
# value is used instead. It is still a problem if there is no required
# size set at all, and the replace and resize options will not be offered
# if no required size is set.
#
# The value is in Gibibytes (GiB).
#
# BIG FAT WARNING: except for OEM-phase-0 use, you should be using
#                  the welcome module, **and** configure this value in
#                  `welcome.conf`, not here.
# requiredStorage: 3.5

partitionLayout:
    - name: ""
      filesystem: "ext4"
      mountPoint: "/boot"
      size: 1G
    - name: ""
      filesystem: "btrfs"
      mountPoint: "/"
      size: 100%
`
> Also, are you using the default grubcfg module?

Yes, the one that comes with the calamares source tarball.

**Comment by dalto8** [comment]
Are the sources available somewhere to browse?

If not, can we also see bootloader.conf ?

**Comment by GloriousEggroll** [comment]
Beyond the mentioned mount and partition changes, here are the two patches fedora applies to the calamares package:

https://src.fedoraproject.org/rpms/calamares/blob/rawhide/f/calamares-3.2.61-default-settings.patch

https://src.fedoraproject.org/rpms/calamares/blob/rawhide/f/calamares-3.2.40-kdesu.patch

Note that Fedora's default btrfs subvolume scheme also does not work, in fact using that scheme just results in no entries at all being present in the grub boot menu except the UEFI firmware option:

https://src.fedoraproject.org/rpms/calamares/blob/rawhide/f/calamares-3.2.61-default-settings.patch#_175

This is why I was trying to get it to load without using a /boot subvolume. Also their anaconda installer does not use a /boot subvolume either by default:

```
nvme0n1                                       259:0    0  3.6T  0 disk  
├─nvme0n1p1                                   259:1    0  600M  0 part  /boot/efi
├─nvme0n1p2                                   259:2    0    1G  0 part  /boot
└─nvme0n1p3                                   259:3    0  3.6T  0 part  
  └─luks-cb0169ec-0e26-48fe-b9d7-44da6cf88bab 253:0    0  3.6T  0 crypt /
```

If luks is not used it just creates a standalone btrfs root partition instead. The goal I was attempting was to align the calamares partition scheme to be more in line with what anaconda does.

**Comment by GloriousEggroll** [comment]
> Are the sources available somewhere to browse?
> 
> If not, can we also see bootloader.conf ?

Sure here's everything tarballed:
[calamares-3.2.61.tar.gz](https://github.com/calamares/calamares/files/10047716/calamares-3.2.61.tar.gz)

**Comment by dalto8** [comment]
So you are using `sb-shim` as your bootloader option as is default from Fedora?

I wonder if this is related to Fedora's BLS implementation....

 > Sure here's everything tarballed:

Those are the Calamares sources.  I was looking for the config changes you had made specifically and your settings.conf.

**Comment by GloriousEggroll** [comment]
> 

'My mount.conf and partition.conf changes have already been applied to the calamares-3.2.61-default-settings.patch patch in the tarball'

That patch contains everything fedora applies to the calamares source in addition to my changes, including settings.conf

**Comment by GloriousEggroll** [comment]
update:

It happens with ext4 as the root partition in the custom table as well so it's not just btrfs triggering it:

- name: ""
filesystem: "ext4"
mountPoint: "/"
size: 100%

**Comment by dalto8** [comment]
Yeah, I wouldn't expect it to be related to btrfs in anyway since your boot partition is ext4.

Calamares isn't really doing anything interesting here, it is just calling grub2-mkconfig.  That is why I was wondering is Fedora's BLS configuration is getting in the way.  I don't think Calamares is aware of that at all.

**Comment by GloriousEggroll** [comment]
After you mentioned that I went back and did some comparisons. The entries on my working rig in /boot/loader/entries/ do not have /boot/ appended to them. Additionally the /etc/default/grub.cfg on that system has:

GRUB_ENABLE_BLSCFG=true

So, I deleted the entries on the test VM in /boot/loader/entries and regenerated them using kernel-install, and they were regenerated without /boot appended. I'm wondering if during installation the script maybe checks to see if somehow BLS is enabled or not? All I could see is this in the kernel-install script:

```
if [ -z "$layout" ]; then
    # Administrative decision: if not present, some scripts generate into /boot.
    if [ -d "$BOOT_ROOT/$MACHINE_ID" ]; then
        layout="bls"
    else
        layout="other"
    fi
fi
```

And further down:
```
export KERNEL_INSTALL_LAYOUT="$layout"

[ "$layout" = "bls" ]
```

**Comment by dalto8** [comment]
> I'm going to give a shot at adding
> `GRUB_ENABLE_BLSCFG=true`

Those are only defaults if `/etc/default/grub` is missing or `overwrite` is set to true.  That change probably didn't do anything.

That being said, I would think the fedora `/etc/default/grub` would already have that set.

> No luck there, kernel-install still acts as if bls isn't enabled

Keep in mind, Calamares doesn't call `kernel-install`, it just writes `/boot/grub2/grub.cfg`.  This is my concern.  Is that the right thing to do on Fedora?  It is so non-standard from a grub perspective in recent versions.

**Comment by GloriousEggroll** [comment]
> 

Calamares shouldn't call kernel-install. It's called by the kernel during package installation. This is why I'm thinking there's got to be some envvar or trigger or something.

In the live environment /boot/ -is- the correct path because its booting from the iso, not a separate partition, so my thought is it's installing the package but taking the boot path from the live  environment instead of the new installation

**Comment by dalto8** [comment]
> Calamares shouldn't call kernel-install. It's called by the kernel during package installation.

So are you installing the kernel packages after the grubcfg and bootloader modules run?

**Comment by GloriousEggroll** [comment]
yes, but i also tried changing the order to before and it made no difference:

  - grubcfg
  - bootloader
  - packages
  
  - packages
  - grubcfg
  - bootloader

**Comment by GloriousEggroll** [comment]
I figured out -- it's not generating them with kernel-install, it's actually copying them directly from the live environment some time around when it makes the partitions.

```
# ls -la /tmp/calamares-root-wdioayus/boot/loader/entries/
total 16
drwx------. 2 root root 4096 Nov 18 16:41 .
drwxr-xr-x. 3 root root 4096 Nov 18 16:38 ..
-rw-r--r--. 1 root root  471 Nov 18 16:41 c8c7cb1aab2044af828271520a15a808-0-rescue.conf
-rw-r--r--. 1 root root  415 Nov 18 16:40 c8c7cb1aab2044af828271520a15a808-6.0.8-202.fsync.fc36.x86_64.conf

# ls -la /boot/loader/entries
total 16
drwx------. 2 root root 4096 Nov 18 16:41 .
drwxr-xr-x. 3 root root 4096 Nov 18 16:38 ..
-rw-r--r--. 1 root root  471 Nov 18 16:41 c8c7cb1aab2044af828271520a15a808-0-rescue.conf
-rw-r--r--. 1 root root  415 Nov 18 16:40 c8c7cb1aab2044af828271520a15a808-6.0.8-202.fsync.fc36.x86_64.conf
```

Any ideas where that copy action happens?

**Comment by GloriousEggroll** [comment]
Well, not sure where the copy happens but I fixed it with a hack at least:
```
diff --git a/src/modules/bootloader/main.py b/src/modules/bootloader/main.py
index d7f4a71..c0222b9 100644
--- a/src/modules/bootloader/main.py
+++ b/src/modules/bootloader/main.py
@@ -28,6 +28,8 @@ import libcalamares
 
 from libcalamares.utils import check_target_env_call
 
+# This is a hack for fedora to enforce not picking up the live environment /boot/ path
+check_target_env_call(['sh', '-c', 'sed -i "s| /boot| |g" /boot/loader/entries/*.conf'])
 
 import gettext
 _ = gettext.translation("calamares-python",

```

**Comment by dalto8** [comment]
I don't think Calamares would be copying them.  I have spent a lot of time in the bootloader module.

Are you sure it isn't `kernel-install` doing that?

**Comment by GloriousEggroll** [comment]
> I don't think Calamares would be copying them. I have spent a lot of time in the bootloader module.
> 
> Are you sure it isn't `kernel-install` doing that?

Yes I'm positive. kernel-install only generates new ones, not copies, and those files pop up almost immediately after the partitions are mounted, not after the packages are installed. It's definitely weird.

**Comment by dalto8** [comment]
Are you installing by unpacking the ISO image?  If so, they are probably part of the image you are installing.

You could add a script to delete them after the unpack step.

**Comment by GloriousEggroll** [comment]
going to go ahead and close this as it has to do with calamares copying from the existing image, not an issue with calamares itself.
