### ISSUE TITLE
greetd: incorrect user and group in Debian

### ISSUE THREAD

**Issue by Sunderland93** [calamares/calamares#2090]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
`greetd` is now in Debian main archive, but it uses different user and group unlike upstream. Upstream uses `greeter` as user and `greetd` as a group, but Debian's packages uses `_greetd` as user and `_greetd` as a group

**To Reproduce**
1. Install 

**Expected behavior**
Calamares probably should check if it is running on Debian/Ubuntu, and set user name `_greetd` and group for greetd in
https://github.com/calamares/calamares/blob/d8a03bb34b7f05f737eab26c84f0db01de90399a/src/modules/displaymanager/main.py#L763

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Calamares has an installation log (usually `~/.cache/calamares/session.log`), please check it for confidential information and attach it if possible.

**Additional context**

**Comment by demmm** [comment]
Since it is not an upstream default, but a decision by a distribution, not really a Calamares bug, more a feature request to make to greetd user & group configurable.  This is best done by those who use a distribution that created this need, thus a PR is very welcomed (so, add an option in displaymanager.conf to set the greetd user & group and use that .conf variable in the main.py).

**Comment by adriaandegroot** [comment]
There might be more configuration-thingies that are distro-specific or should be customized for a distro. The PR adds a general mechanism to do so (frankly I'm not entirely happy with "greetd creates users on the target system" but it is what it is -- or it needs a nicer API in libcalamares). The schema should prevent people from shooting themselves in the foot too hard.

**Comment by demmm** [comment]
With https://github.com/calamares/calamares/pull/2091 merged, can this now be closed?

**Comment by Sunderland93** [comment]
Yes
