### ISSUE TITLE
/etc/initramfs-tools not generating

### ISSUE THREAD

**Issue by jakethesnake1126** [calamares/calamares#2099]
I am building from source without the use of PKGBUILDS or anything like that, and update-initramfs seems to be failing.  Here is the full log that it gives me: https://termbin.com/18zgd

It appears that the folder initramfs-tools does not exist.  It is my understanding from reading another issue thread that it is supposed to be creating this automatically, but for me it does not.

Distribution: Arch

**Comment by dalto8** [comment]
The `initramfs` module is for Debian-based distros.  It is probably failing because the command doesn't exist.

**Comment by demmm** [comment]
Make sure to create usable bug reports, fill out the issue page presented to you fully and read through https://calamares.io/issues/
Without any basic info, like based on what distribution, etc, there is no other option but to close this issue.

**Comment by jakethesnake1126** [comment]
> The `initramfs` module is for Debian-based distros.  It is probably failing because the command doesn't exist.

This was it thank you!
