### ISSUE TITLE
Bootloader id error

### ISSUE THREAD

**Issue by heapbytes** [calamares/calamares#2105]
**Describe the bug**
Heyy, i was developing a new arch distro (Vitunix), i choose calamares for installation, at the end of the setup i get the following error: 
```
The bootloader could not be installed. The installation command <pre>grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=vitunix_OS --force</pre> returned error code 127.`
```
Architecture: 64 bit
EFI to boot (Virtualbox)
and ext4 disk type.

**Expected behavior**
Should install the iso setup. 

could you please connect me through discord so i can describe the issue more precisely ( lenon#6176 )

**Comment by dalto8** [comment]
Need the full logs from the install to see what is happening.  That error message just tells us it failed.  Hopefully the logs will tell us why it failed.

**Comment by heapbytes** [comment]
heyyy, i am sorry but can u please tell me where are the logs stored again? , i searched in the cache folder and also the whole system but couldn't find one 

![image](https://user-images.githubusercontent.com/56447720/221590768-2eba2290-e767-4fd4-84d0-5b25cba3952f.png)

**Comment by heapbytes** [comment]
okayy will check that!!

**Comment by heapbytes** [comment]
Heyy , so i have installed grub package manually and still got the same error 

![image](https://user-images.githubusercontent.com/56447720/221595272-ac5ca5cb-a37c-4716-86c3-f94f2b07e2a9.png)

i didn't get any logs, but i have copied all the things (from toggle log) before my postinstall script starts, 
https://notepad.pw/vitunix

**Comment by heapbytes** [comment]
Okay, here's the session logs that was created with the command you gave, 
https://notepad.pw/vitunix

**Comment by dalto8** [comment]
>  failed to run command 'grub-install': No such file or directory"

The install is failing to find `grub-install` in the target system.

**Comment by heapbytes** [comment]
yess, i installed grub package with `sudo pacman -Sy grub` and checked if grub-install exist

**Comment by dalto8** [comment]
Installing it on the ISO probably won't install it into the target system because it isn't in the image you are unpacking.

**Comment by kkofler** [comment]
Yes, it is no use installing packages on the running system, you have to install them during the ISO compose.

**Comment by heapbytes** [comment]
ohh should i compile the ISO again? putting the grub package in `packages.x86_64` ?

**Comment by dalto8** [comment]
> ohh should i compile the ISO again? putting the grub package in `packages.x86_64` ?

Yes

**Comment by killajoe** [comment]
> so i have installed grub package manually and still got the same error

usually installing a package on the livesession will not be installed on target it will use what ever is installed inside the squashfs image also used to start the livesession.. what will not be changed in that case..

**Comment by heapbytes** [comment]
ok guys, the grub install while compiling the iso helped, thanks a lot :heart:
