### ISSUE TITLE
test

### ISSUE THREAD

**Issue by lawyoum** [calamares/calamares#2112]
# Objective
The test goals. e.g.: Evaluate the language selection and the partitioning configurations.

# Requirements

## Environment
What is the environment that should be tested and how it should be prepared. e.g.: The test needs to run in the release 3.32.34 installing Manjaro.

## User profile
Describe the target users you are looking for the test. e.g.: A user that has already used a system-installer.

## Facilitator
What the facilitator should be familiar with to run the tests. e.g.: The facilitator needs to know how to build Calamares to be able to run the tests.

# Test design
## Tasks
A list of tasks that the user has to perform. e.g.:

* Use another language.
* Change partitioning configurations.

## Scenarios
A list of scenarios for the user to perform the tasks. They should put the user in a context and not give specific hints about what you want the user to do. e.g.:

1. You want to change the installer language to English. Please, look for this option in the application.
2. You are a big fan of a lot of distributions and want to have some space left to install other distributions in your disk after this installation. Please, resize your disk to have 35GB of space left.

**Comment by killajoe** [comment]
?

**Comment by dalto8** [comment]
This appears to be an empty templat.  

Closing.
