### ISSUE TITLE
[feature request, very optional] Add music as the installer as the installation process starts

### ISSUE THREAD

**Issue by mdhishamsayed** [calamares/calamares#2119]
**Is your feature request related to a problem? Please describe.**
This request is not related to a problem, but doing the Windows XP era, we used to have a Background music in the background while the OOBE was going on..

**Describe the solution you'd like**
So whenever the installation starts, like after the warning, with users consent, background music,
there should be a button enabling and disabling the music.
either mpv or gstreamer backend must be there

**Describe alternatives you've considered**
Nothing much

**Additional context**
This is a very optional request

**Comment by dalto8** [comment]
You need to fill out the template.  You appear to have posted the template without making any changes.

**Comment by adriaandegroot** [comment]
You've got a QML slideshow, you can do whatever you like in there. Feel free to file a PR to add a little music-player or theme song in the slideshow -- it would probably fit best in the *calamares-extensions* repo, which is where there are fancy examples of branding.

**Comment by demmm** [comment]
Closing here, since it belongs to the calamares-extensions, examples (and is not a feature request, but merely a question of how to customize QML):
https://github.com/calamares/calamares-extensions/tree/calamares/branding
To add media to QML:
https://doc.qt.io/qt-5/qml-qtmultimedia-audio.html

**Comment by demmm** [comment]
This option is on trial in KaOS now (forum post will let users decide whether it will be included in the next ISO):
![Screenshot_20230402_154503](https://user-images.githubusercontent.com/5360485/229357520-648af25a-cd89-47f3-a343-a0863125f72c.png)
