### ISSUE TITLE
Calamares fails to activate systemd timers because it appends .service to the end. 

### ISSUE THREAD

**Issue by bsmith7581** [calamares/calamares#2120]
I was viewing the Calamares log after installing Manjaro KDE 22.0.5. I found two warnings stating that it failed to enable fstrim.timer.service and pkgfile-update.timer.service. The reason they failed is because they shouldn’t end with .service. I looked at the Manjaro KDE ISO profile and found the line: 
```enable_systemd=('bluetooth' 'cronie' 'ModemManager' 'NetworkManager' 'cups' 'haveged' 'fstrim.timer' 'pkgfile-update.timer')```
It seems that Calamares automatically adds .service to every one of them, which is the correct behavior for bluetooth, cups, etc.  
Despite the failed timer activations, Calamares still informed me that Manjaro was successfully installed at the end.

**Comment by demmm** [comment]
>Despite the failed timer activations, Calamares still informed me that Manjaro was successfully installed at the end.

It only fails if a distribution sets `mandatory` to true, but since there is no log or link to the used .conf files, make sure to first contact your distribution, and let them decide if this a Calamares issue or an issue with their used settings.
https://calamares.io/issues/#end-users.

Will be closed shortly, unless distribution can show this is an upstream issue.

**Comment by adriaandegroot** [comment]
Calamares just runs `systemctl <action> <name>` for the units listed in the `services-systemd.conf` file, so this seems more like an issue with the way Manjaro is generating this file (and they are not setting the key *mandatory*, so failures are ignored -- which is the documented behavior)

**Comment by dalto8** [comment]
In this case, this issue should be reported to Manjaro.

**Comment by bsmith7581** [comment]
@dalto8  aren’t you on the Manjaro team?

**Comment by dalto8** [comment]
> @dalto8 aren’t you on the Manjaro team?

I am not part of the Manjaro team.  In the past, I was a moderator on the forum and was contributing to manjaro-architect.

**Comment by philmmanjaro** [comment]
Fixed via: https://gitlab.manjaro.org/profiles-and-settings/iso-profiles/-/commit/dcb71265b4b3ac38bc59cf266e190a1ad87e093f and https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/-/commit/2ddcc62973811537ccb88e6168208252ef0ae93e

I'll look into the unit port at a later state.
