### ISSUE TITLE
unapackfs installation error

### ISSUE THREAD

**Issue by JustANerd1999** [calamares/calamares#2121]
So while trying to install via calamares I get this following error:

Installation Failed

Boost.Python error in job "unpackfs".

<class 'AttributeError'>
module 'libcalamares.utils' has no attribute 'host_env_process_output'

Traceback:

File "/usr/lib/x86_64-linux-gnu/calamares/modules/unpackfs/main.py", line 488, in run
    return unpackop.run()

  File "/usr/lib/x86_64-linux-gnu/calamares/modules/unpackfs/main.py", line 309, in run
    entry.do_count()  # Fill in the entry.total

  File "/usr/lib/x86_64-linux-gnu/calamares/modules/unpackfs/main.py", line 87, in do_count
    libcalamares.utils.host_env_process_output(["unsquashfs", "-l", self.source], cb_count)

[Full session log](https://github.com/calamares/calamares/files/11075348/session.log)

Any help is appreciated!

**Comment by demmm** [comment]
Please make sure to follow either the issue report template presented to you and/or read:
https://calamares.io/issues/
Is this a report from an end user?  Then first go to your distribution:
https://calamares.io/issues/#end-users
If you are a distro developer, then provide all the missing info (distribution, installation.log, settings used and so on).
Issue as is will have to be closed soon without further info.

**Comment by demmm** [comment]
No further response from submitter, closing.
