### ISSUE TITLE
Error autologin xfce

### ISSUE THREAD

**Issue by Deblinux** [calamares/calamares#2123]
I made a module that does select with calamares on debian, 2 XFCE and MATE desktops.
As soon as I select on calamares I have to autologin and restart the pc the autologin doesn't do it and instead it has to do it because I selected it on calamares. This happens when I install XFC desktop or KDE PLASMA

**Comment by Deblinux** [comment]
Debian 11
https://sourceforge.net/projects/deblinux/files/Deblinux%2064%20bit/Deblinux4.1.1-mate%2064bit.iso/download
Calamares 3.2.36

~/.cache/calamares 
File log not found

**Comment by dalto8** [comment]
For an issue like autologin, you need to first look into why it is isn't working in the installed system.

Once you determine why it isn't working in the system, then you can start to debug the installation process.  Until you have determined what the problem is with the installed system, there is no point in looking at the installation process.

There are too many things that could cause a failure to autologin.

**Comment by adriaandegroot** [comment]
So, I went a lot farther in trying-to-help than is necessary:
- downloaded the ISO
- figured out that you need to pick "debian live", not "graphical installer" from the GRUB menu
- closed the Italian welcome application
- started terminal, found localized directory names in /home (I think that's kind of cool though)
- noticed that calamares is started with no logging, no debugging, via `install-debian`
- edited `install-debian` to add `-D6` flag to the command
- run `install-debian` from the terminal
- now i can see that the log is printed to stdout, and also stored in `/root/.cache/calamares/session.log` (this was, possibly, a bit confusing in earlier instructions: the log is written to `~/.cache`, but what `~` means depends on how you're running Calamares)
- check the `settings.conf`; you're running *displaymanager* before *packages*, which might be an issue depending on how the displaymanager and desktop are going to be installed

I clicked through the installation, ticked the box *log in automatically* on the user page, then waited for the install to complete.

After reboot, I am automatically logged in.

So can't reproduce the problem, even when generously interpreting the issue.
