### ISSUE TITLE
Percent value is not localised

### ISSUE THREAD

**Issue by bitigchi** [calamares/calamares#2124]
During the installing part, the progress bar percentage value shows in the following format: 10%. This is what most locales use, but in some other languages, including Turkish for instance, the sign precedes the number; e.g. %10. The percentage text value should be explicitly made available for translation.

![Ekran Resmi 2023-04-09 13 27 57](https://user-images.githubusercontent.com/2769571/230767757-1e8ab80b-47c5-4816-a053-22ee31229722.png)

**Comment by adriaandegroot** [comment]
This is an interesting one, it seems that a `QProgressBar` has a `format()` property that defines how the value is shown. This does **not** seem to update if you start a Qt-based application in one language or another, so it's not locale-aware by default.

I'll add it to the translations, sure. It will be a bit weird translating `%p%` (which becomes `%%p` in Turkish).

**Comment by bitigchi** [comment]
Awesome, thanks! Just to confirm, there is no need to escape the percent sign in this case, right? Like `%%%p`.

**Comment by kkofler** [comment]
According to https://doc.qt.io/qt-5/qprogressbar.html#format-prop apparently not.
