### ISSUE TITLE
Partitioning a disk into btrfs sub-volumes

### ISSUE THREAD

**Issue by saber716rus** [calamares/calamares#2130]
**Is your feature request related to a problem? Please describe.**
Partitioning a disk into btrfs sub-volumes

**Describe the solution you'd like**
The ability to create a btrfs partition, as well as the ability to split into btrfs sub-volumes and bind mount points to sub-volumes.

**Comment by dalto8** [comment]
There is no UI for this currently but as a workaround you can edit `mount.conf` before launching the installer.  However, this may not be supported by the distro.

**Comment by dalto8** [comment]
Closing as a duplicate of #1580

**Comment by dalto8** [comment]
It was closed because we already have an open issue for it which is linked above.  

Not because it wasn't important/necessary.
