### ISSUE TITLE
[FEATURE] Creation of a user by a different shell

### ISSUE THREAD

**Issue by D3vil0p3r** [calamares/calamares#2131]
**Is your feature request related to a problem? Please describe.**
Hello! I am a FISH shell lover and I was wondering if in the future, the "Users" section will give the possibility to select a shell for the user instead of bash as default shell. 

**Describe the solution you'd like**
I would like to have a radio button menu on "Users" section that allows to select your favourite shell (i.e., bash, fish, zsh).

**Describe alternatives you've considered**
Currently I'm trying to manage it by .sh scripts containing `chsh -s <shell> -u <username>` run by Calamares logic but the problem is that I don't know how to extract the username set by the user during the installation.

**Comment by adriaandegroot** [comment]
If you are using the *shellprocess* module, it is documented to support `${USER}` in 3.3 (`@@USER@@` in 3.2). That, plus a *packagechooser* page, can get you what you want. Additions to the user page: PRs welcome.

**Comment by D3vil0p3r** [comment]
@adriaandegroot thank you. As the `USER` variable, is there also a variable (or an array variable) where selected packages/tools are chosen on netinstall modules?

**Comment by dalto8** [comment]
The packagechooser module can be configured to write a variable with the selection to global storage.

If you use a packagechooser module to choose the shell, you could call a script using a shellprocess which installs the package for the shell if needed and then sets the default shell for the user.

I don't think there is currently an easy way to drive this from a selection in netinstall.
