### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by AlbertoN97** [calamares/calamares#2143]
Hi, i am trying to do a distro following LFS and BLFS guides.
I succesfully compiled and installed calamares, but when i execute the calamares command to invoke the installator i get the following error:
![imagen](https://github.com/calamares/calamares/assets/91640565/e3054157-8c39-4126-9cee-c9da002cf18b)
I dont understand why i get that error considering the file is in the default path of its installation.
Thanks in advance for the help.

**Comment by demmm** [comment]
Issues are for reporting bugs or feature request, it is not a help channel:
https://calamares.io/issues/
https://calamares.io/issues/#developers-of-distributions
Please use the IRC or Matrix channel for help.
