### ISSUE TITLE
A little bit about bugs and a couple of suggestions for new features

### ISSUE THREAD

**Issue by Boria138** [calamares/calamares#2148]
I have both errors and suggestions here
1) If calamares open then close, only manual partitioning is left
2) The partition module in ventoy first takes 2 minutes to work and then crashes the system.
3) How do I specify different configurations for grub? On some motherboards grub is set only with the flag --no-vram otherwise grub says that nvram is out of memory and that it does not have enough memory.
4) Will the pacstrap implementation for arch based systems pacstrap calamares from endeavour os not work with new versions of calamares

**Comment by Boria138** [comment]
Here are my calamares settings [URL ](https://gitlab.com/hybrid-project-developers/iso/hybrid-calamares-config) If any of these errors are due to improper settings I humbly apologize but I had the grub and partitioning bug on manjaro as well so at least these two errors are not due to my settings

**Comment by Boria138** [comment]
`Remaining modules: 1 
     "partition" 
05:01:58 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
05:01:59 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
05:02:00 [6]: smartctl initialization failed for  "/dev/sdb" :  Resource temporarily unavailable
05:02:00 [6]: error during smart output parsing for  "/dev/sdb" :  Success
05:02:00 [6]: QList<Device*> PartUtils::getDevices(DeviceType)
    Removing unsuitable devices: 2 candidates. 
    .. Running ("blkid", "/dev/sda") 
05:02:01 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
    .. Finished. Exit code: 0 output:
 /dev/sda: PTUUID="5a1b71f3-6f1d-4e4e-904c-9fbc05543bba" PTTYPE="gpt"
    .. Running ("blkid", "/dev/sda1") 
    .. Finished. Exit code: 0 output:
 /dev/sda1: UUID="7DB0-F864" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="269dbd47-7f91-8146-b007-13abf7ecd69a"
    .. Running ("blkid", "/dev/sda2") 
    .. Finished. Exit code: 0 output:
 /dev/sda2: UUID="ba1a52e6-5348-4b92-81d7-4b23902cc77f" TYPE="swap" PARTUUID="a7363670-e94c-5c4c-a2dd-07e9e0fb1344"
    .. Running ("blkid", "/dev/sda3") 
    .. Finished. Exit code: 0 output:
 /dev/sda3: UUID="5b537f6f-2c01-402f-8b2a-3b418bf52286" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="28596ac0-6441-354b-a3d4-2a4c22e9cf01"
    .. Running ("blkid", "/dev/sda4") 
    .. Finished. Exit code: 0 output:
 /dev/sda4: UUID="f9671202-5688-48b7-94cc-daa974820d61" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="root" PARTUUID="28ebac88-ab21-42d9-a86e-3741f7cb65c9"
    .. Running ("blkid", "/dev/sdb") 
    .. Finished. Exit code: 0 output:
 /dev/sdb: PTUUID="87cb75a8-d5a6-42f6-fc42-304d7396fa1f" PTTYPE="gpt"
    .. Running ("blkid", "/dev/sdb1") 
    .. Finished. Exit code: 0 output:
 /dev/sdb1: LABEL="Ventoy" UUID="879C-5822" BLOCK_SIZE="512" TYPE="exfat" PARTLABEL="Ventoy" PARTUUID="1d3cc77a-670a-8761-5dd5-cc024f9fa2f3"
    .. Running ("blkid", "/dev/sdb2") 
    .. Finished. Exit code: 0 output:
 /dev/sdb2: SEC_TYPE="msdos" LABEL_FATBOOT="VTOYEFI" LABEL="VTOYEFI" UUID="83A6-E98E" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="VTOYEFI" PARTUUID="8cd70d01-6cfc-b14a-f9cc-dcfd174a9e3e"
    .. there are 2 devices left. 
05:02:01 [6]: void PartitionCoreModule::doInit()
    LIST OF DETECTED DEVICES: 
    .. node     capacity        name    prettyName 
    .. "/dev/sda" 750153761280 DevName$f3134a03 DevNamePretty$2b54b8d1 
    .. "/dev/sdb" 15521103360 DevName$c10d0ad0 DevNamePretty$ee64caa0 
    .. 2 devices detected. 
05:02:02 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
05:02:03 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
05:02:04 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
05:02:05 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
05:02:07 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
05:02:08 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
05:02:09 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
05:02:10 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
05:02:11 [6]: void Calamares::RequirementsChecker::reportProgress()
    Remaining modules: 1 
     "partition" 
`
    Remaining modules: 1 
     "partition"  repeats 2 minutes and then the system crash

**Comment by Boria138** [comment]
I found solutions to two problems
1) Pacstrap did not work because the locale of archiso was not english with english locale everything works
2) I can not erase the entire disk when reopening calamares because it will not mount the /tmp directory when closing if I write umount -R /tmp/ before opening calamares all partitioning choices will work

**Comment by demmm** [comment]
For issues, please use one topic per issues, otherwise will be impossible to track.
So open a few feature requests, and if still seeing a bug, open bug reports for each separate issue.
https://calamares.io/issues/
