### ISSUE TITLE
When you close calamares and open it again in the partition module, only the manual partitioning of the disk remains

### ISSUE THREAD

**Issue by Boria138** [calamares/calamares#2149]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
A clear and concise description of what the bug is. Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.

**To Reproduce**

**Expected behavior**

**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Calamares has an installation log (usually `~/.cache/calamares/session.log`), please check it for confidential information and attach it if possible.

**Additional context**

This problem occurs because calamares will not unmount the temporary partitions if before opening calamares you write umount -R /tmp then the automatic partitioning will be available again I guess calamares itself should unmount the temporary partitions when closed

**Comment by dalto8** [comment]
You need to use the template properly as described in your other issue.  Also make sure that you have the unmount module set as an emergency module.

If emergency modules don't run when you close calamares, that would probably be a good feature request but we would need proper information to determine what is happening here.  That is why the template exists, to show you how to provide the proper details.

**Comment by dalto8** [comment]
This has an existing open issue: https://github.com/calamares/calamares/issues/2063
