### ISSUE TITLE
Add more flexible grub settings

### ISSUE THREAD

**Issue by Boria138** [calamares/calamares#2150]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

On some motherboards grub may not install by writing that vram ran out of vram and adding --no-vram seems to be just write this flag in bootloader.conf but on motherboards where this error does not occur with this flag bios simply will not see

**Comment by dalto8** [comment]
You need to clean this up.  The template is intended to be used to help you give us enough detail.  You are supposed to replace the non-bold template text with your details.  The template is provided to help you make a request that has sufficient details.

Additionally, you need to make it more specific and actionable.  "Add more flexible grub settings" isn't specific or actionable.  What might be actionable is "Add the ability to pass specific options to `grub-install` conditionally".  However, even then you would need to clearly explain how you would expect that to work.

This is a pretty common feature request so I think it is worth keeping(unless we already have an open feature for this) but it needs to be described using the template in the correct way.

**Comment by dalto8** [comment]
There is already an open issue for this: https://github.com/calamares/calamares/issues/2110
