### ISSUE TITLE
Partition module stuck if kill calamares

### ISSUE THREAD

**Issue by Boria138** [calamares/calamares#2154]
**Describe the bug**
If you close calamares using ctrl+alt+esc or sudo kill -9 when you reopen calamares, the partition module freezes

**To Reproduce**
sudo killall calamares or  ctrl+alt+esc or sudo kill -9 

**Expected behavior**
The module must work out correctly

**Additional context**
When using ventoy, this bug occurs even if you just close calamares through the cross at the first launch, it sees my markup at the next no

**Comment by demmm** [comment]
Full info needed, https://calamares.io/issues/
Will be closed shortly otherwise.

**Comment by Boria138** [comment]
A little late, but as it turned out this problem occurs only if you use ventoy with the setting ` "VTOY_LINUX_REMOUNT": 1` with ordinary flash drives and also with ventoy without this setting the problem is not observed
