### ISSUE TITLE
Foolproof check of user account name

### ISSUE THREAD

**Issue by ss11mik** [calamares/calamares#2156]
**Is your feature request related to a problem? Please describe.**
So, yesterday I was trying to install system (Manjaro) a few times, always getting a strange error about useradd command failing. I have tried various versions of the system etc, until I realized I was trying to create a user with name "sys" (it was a system for testing purposes). And the name clashed with system user. So, I thought it would be nice if the installer had a list of "stupid" usernames which it would not allow instead of failing later with distantly-related error as it would save some users an hour of confusion.

**Describe the solution you'd like**
A list of "stupid" usernames which it would not allow.

**Describe alternatives you've considered**
Currently it fails later in installation on useradd command and more experienced users eventually figure out what the problem is.

**Additional context**
I was using Manjaro, but I guess it does not matter much. The "core" list of forbidden usernames would be shared for all distros and each distribution might add its own to their list.

**Comment by dalto8** [comment]
This already exists.  It is called `forbidden_names`.  Your distro would simply need to add `sys` to their list.

**Comment by demmm** [comment]
To clarify, your distro will have to add here:
https://github.com/calamares/calamares/blob/calamares/src/modules/users/users.conf#L209

**Comment by kkofler** [comment]
That is actually the list of forbidden host names. The forbidden user name will have to be added here instead:
https://github.com/calamares/calamares/blob/f4e9b3689de77698e90aeb68094c9b7686df7307/src/modules/users/users.conf#L163

**Comment by kkofler** [comment]
By the way, you should always link to a commit hash rather than a branch name, because branch contents can change and the line number can end up being off (even if you point to the correct line ;-) ). GitLab has a convenient "Permalink" button for that, whereas here on GitHub, it is unfortunately not easily discoverable: you have to click on History and then on the "View at this point in the history" button (<>📄) for the latest revision.
