### ISSUE TITLE
Installation of Manjaro using Calamares always fails

### ISSUE THREAD

**Issue by fidelski** [calamares/calamares#2158]
**Several independent problems provide the worst experience installing Linux ever**

When trying to install Manjaro Linux the installer fails for different reasons:

* The installer fails to select continue when first selecting manual partitioning.
* The installer randomly crashes when trying to find available block devices.
* The installer fails to install on systems with less than 8GB memory.
* The installer ALWAYS fails to install grub - since the partitions are mounted in `/tmp` (why on earth one would do that?)

**To Reproduce**

Try to install Manjaro Linux with the installer on a fresh system - you may chose to use the entire disk or try to use a custom LVM partitioning scheme. Use 512MiB of an EFI partition at the start of the gpt formatted device.

Installation fails - always.

**Expected behavior**

The installation succeeds.

**Comment by dalto8** [comment]
These don't look like Calamares issues at first glance.

These look like issues that should be reported to Manjaro.
