### ISSUE TITLE
XFS - ERROR: file not found: '' No fsck helpers found. fsck will not be run on boot

### ISSUE THREAD

**Issue by D3vil0p3r** [calamares/calamares#2165]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
I'm using Calamares 3.2.62 and I'm setting for my first time XFS as file system. The system has `xfsprogs` package installed. During the installation, I get the following error only when I set XFS (when I use BTRFS or EXT4, it works well):
```
19:26:22 [6]: virtual Calamares::JobResult InitcpioJob::exec()
    Updating initramfs with kernel "linux" 
    .. Running ("mkinitcpio", "-p", "linux") 
    .. Target cmd: ("mkinitcpio", "-p", "linux") Exit code: 1 output:
 ==> Building image from preset: /etc/mkinitcpio.d/linux.preset: 'archiso'
==> Using configuration file: '/etc/mkinitcpio.conf'
  -> -k /boot/vmlinuz-linux-zen -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-zen.img
==> Starting build: '6.3.9-zen1-1-zen'
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: 'xhci_pci'
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [consolefont]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> ERROR: file not found: ''
==> ERROR: file not found: ''
==> WARNING: No fsck helpers found. fsck will not be run on boot.
==> Generating module dependencies
==> Creating lz4-compressed initcpio image: '/boot/initramfs-linux-zen.img'
==> WARNING: errors were encountered during the build. The image may not be complete.
```

Here the complete logs by `-D8`: https://pastebin.com/Bmb3wfv8

**To Reproduce**
1. Run Calamares and set XFS as default File System
2. In Partitions section, use Replace Partition for replacing a partition where installing the system
3. Run the installation and wait

**Comment by dalto8** [comment]
This is not a Calamares issue.  This is either a distro issue with mkinitcpio or a configuration issue with the installed system.

**Comment by tanxiang** [comment]
you need install fsprogs,. xfsprogs etc...
