### ISSUE TITLE
XFS - error: file '/grub/1386-pc/normal.mod' no found

### ISSUE THREAD

**Issue by D3vil0p3r** [calamares/calamares#2166]
Calamares, in case of XFS as selected or default file system, during the partitioning by Erase disk or Replace Partition option, formats automatically the boot partition as XFS.

The installation finishes correctly but at reboot, it enters in GRUB rescue with the following error:
```
GRUB loading.
Welcome to GRUB!

error: file '/grub/1386-pc/normal.mod' no found.
Entering rescude mode....
grub rescue>
```
It occurs also in Manual Partition mode if `/boot` partition is formatted as XFS.

The issue above is not produced if the data partition is XFS and `/boot` partition is NOT set as XFS (this can be set in Manual Partition but not in other partition modes (i.e., Erase disk)).

Is bootloader or partition module not managing XFS file system in proper manner? Tested on Arch Vanilla and Athena OS with `xfsprogs` pkg installed.

**Comment by ptr1337** [comment]
KNown issue. Downgrade grub, nothing helps currently.
Its a upstream issue i think.
[grub-2:2.06.r499.ge67a551a4](https://mirror.cachyos.org/repo/x86_64/cachyos/grub-2%3A2.06.r499.ge67a551a4-1-x86_64.pkg.tar.zst)

This version is fine.

**Comment by dalto8** [comment]
Since this is an issue with grub, I will close this now.

**Comment by philmmanjaro** [comment]
Here is the upstream issue: https://savannah.gnu.org/bugs/?64376 However when the commit ef7850c757fb3dd2462a512cfa0ff19c89fcc0b1 (fs/xfs: Fix issues found while fuzzing the XFS filesystem) gets reverted installing on XFS /boot works.

**Comment by D3vil0p3r** [comment]
> Here is the upstream issue: https://savannah.gnu.org/bugs/?64376 However when the commit ef7850c757fb3dd2462a512cfa0ff19c89fcc0b1 (fs/xfs: Fix issues found while fuzzing the XFS filesystem) gets reverted installing on XFS /boot works.

Let's hope they will apply that fix asap.
