### ISSUE TITLE
Runtime configuration

### ISSUE THREAD

**Issue by Dancheg97** [calamares/calamares#2169]
**Problem description.**

I was creating my own ISO image based on arch, and ran into problem configuring _calamares_. I was not able to compile the installer to adjust it for my distribution. I wrote my [own installer](https://fmnx.su/core/ainst) ([github mirror](https://github.com/fmnx-su/ainst)) based on [archinstall](https://wiki.archlinux.org/title/archinstall), but it is really buggy 😅

**Solution**
I used [flutter](https://flutter.dev/) as UI framework, so it can be adjusted for multiple platforms. But it is still missing a lot of useful features which already exist in _calamares_. The main idea behind my project was to completely move installer configuration to runtime, so that ISO developers don't have to recompile the installer. Also that would be nice to have an ability to reuse values from user input in text fields in post-installation scripts (to set up git or gpg for example).

**Context**
I think it is reasonable not to recompile _calamares_ each time for different distributions, it would make calamares adjustment process much easier for distribution developers.

**Comment by dalto8** [comment]
I am not sure I understand the direction you are going here?

Can you be more clear about what you are proposing here?

There are existing PKGBUILDs for arch-based distros so it should be pretty easy to build Calamares.  Also, many distros ship with a calamares package that is already built.  Arch just isn't one of those.

**Comment by Dancheg97** [comment]
If i understand this correct, calamares is configured before build.
I think that it would be cool, if application would read some configuration file from user directory or specific file and draw the whole UI in runtime. So that developers don't need to recompile it for different adjustments.
I am not sure that it is reasonable, but it would be easier to iterate quicker when adjusting the installer for specific distribution (because no time is spent for calamares compilation), similarly with 'hot restart' in flutter applications.

**Comment by dalto8** [comment]
Lots of distros never build/compile Calamares.  Many look and feel elements can be configured via conf files and/or drop in Qml elements.

**Comment by Dancheg97** [comment]
Thank you! Should have explored calamares better.
