### ISSUE TITLE
[HELP] packages module, pacman dont have acces to internet while installation process after unpackfs and networkcfg

### ISSUE THREAD

**Issue by Lamborge** [calamares/calamares#2171]
**Describe the bug**
64bit, EFI, custom image of system created by archiso (https://github.com/DwarvenOS/DwarvenOS)
On the packages module stage pacman dont have acces to internet and cant resolve db files

**Screenshots and Logs**
Full log: https://0x0.st/HjlT.txt
settings.conf: https://github.com/DwarvenOS/DwarvenOS/blob/main/airootfs/etc/calamares/settings.conf
packages.conf: https://github.com/DwarvenOS/DwarvenOS/blob/main/airootfs/etc/calamares/modules/packages.conf

**Additional context**
You can see in packages.conf comment string where i try to apply pacman keyring and calamares can't find any commands/programs at /bin/sh -c "[this]"

**Comment by dalto8** [comment]
A couple of things
* If you are doing something that needs to install packages from the repos, you can require an internet connection in welcome.conf.
* It isn't clear to me what you are trying to accomplish in that packages module.  You appear to be doing a traditional install where you unpack the contents of the live ISO to perform the installation.  However, you are then trying to install `base` in the packages module.  It doesn't seem like that should be needed in that case.

**Comment by Lamborge** [comment]
Thank for fast answer

> * If you are doing something that needs to install packages from the repos, you can require an internet connection in welcome.conf.
on the virtual machine on which I tested, there is Internet, I can install packages from it, visit websites, etc.

> * It isn't clear to me what you are trying to accomplish in that packages module.  You appear to be doing a traditional install where you unpack the contents of the live ISO to perform the installation.  However, you are then trying to install `base` in the packages module.  It doesn't seem like that should be needed in that case.
this set of 3 packages is just for testing, the core of my problem is that pacman can't access the internet as you can see from the logs

**Comment by Lamborge** [comment]
i entered in chroot via arch-chroot and everything was okay

i think calamares maybe somehow mounts some partitions incorrectly or starts the installation of packages incorrectly

**Comment by dalto8** [comment]
> i think calamares maybe somehow mounts some partitions incorrectly or starts the installation of packages incorrectly

You can chroot into the actual chroot setup by calamares.  As long as you don't acknowledge the error, everything should still be mounted in `/tmp/`.  chroot into that location and see what is happening.  Don't use arch-chroot.

**Comment by Lamborge** [comment]
I have chrooted into /tmp/calamares via just chroot and it really problem with dns, but on system(this system copies by calamares) dns is working. What could be the problem?

**Comment by Lamborge** [comment]
Im mounted /run from live system to chroot and dns start works, maybe i was wrong in configs?

**Comment by Lamborge** [comment]
I was chaned mount.cfg and dns start working, but my problem in **Addition context** still existing, anything command int " " after sh -c not found

**Comment by Lamborge** [comment]
It was mistake in sytax, closing issue
