### ISSUE TITLE
ArchLinux - Initramfs@initramfs

### ISSUE THREAD

**Issue by gentoolman** [calamares/calamares#2172]
Getting this error when starting Calamares:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
23:04:10 [1]: void Calamares::ModuleManager::loadModules()
    ERROR: Module "initramfs@initramfs" not found in module search paths. 
     "/usr/lib/calamares/modules" 
23:04:10 [1]: void CalamaresApplication::initFailed(const QStringList&)
    ERROR: STARTUP: failed modules are ("initramfs@initramfs") 
23:04:10 [1]: OsproberEntryList PartUtils::runOsprober(DeviceModel*)
    ERROR: os-prober cannot start. 

![grafik](https://github.com/calamares/calamares/assets/20800804/019ae016-9861-4280-b652-63b73623269b)

Any Idea how to solve this?

**Comment by kkofler** [comment]
Do not use the `initramfs` module on Arch Linux or a derivative, that module is for Debian. You want the `mkinitcpio` module instead.
