### ISSUE TITLE
Calamares can't see partitions if boot Live CD via Ventoy

### ISSUE THREAD

**Issue by Flashwalker** [calamares/calamares#2173]
**Describe the bug**
Calamares does not see the partitions if you use Ventoy to boot the live CD and put the ISO on the same hard disk you want to install the OS on.

**Summary**: the ISO is on the first partition, and the empty formatted linux partitions in the extended partition next to it on the same disk.

**Result**: Calamares fails to find any installable partitions 👎.
KDE Partiotion Manager and GNOME Disks running on the same Live CD see partitions fine.

**Tested**: Nitrux, Feren, KDE neon

So we have here: You can edit partiotions from Live CD, but you can't install anything on it via Calamares.

**To Reproduce**
1. Install Ventoy on a disk with additional partition
2. Copy some kde based Live CD on Ventoy partition
3. Make extended partition on the free space on that disk
4. Make some ext4 partitions inside the extended one
5. Boot that disk
6. Run Calamares, run KDE Partition Manager or GNOME Disks

**Expected behavior**
Calamares see partitions as well as KDE Partition Manager or GNOME Disks

**Additional context**
IMHO If you able to edit the disk partitions from the Live CD you must be able to install anything on these partitions from the same Live CD.

**Comment by dalto8** [comment]
This issue is well known and there are already existing open issues for it including #545 and #2088.

Closing as a duplicate.
