### ISSUE TITLE
Plymouth on unencrypted boot has plymouth-encrypt erroniously added to mkinitcpio.conf hook. Arch

### ISSUE THREAD

**Issue by bkmo** [calamares/calamares#2182]
When setup has an unencrypted boot and plymouth, the mkinitcpio.cfg has sd-encrypt hook added. This hook has been removed from plymouth and the standard encrypt hook is all that is needed. This is at least the case with the Arch package of Plymouth. This seems to be the culprit: src/modules/initcpiocfg/main.py
` if encrypt_hook:
        if detect_plymouth() and unencrypted_separate_boot:
            hooks.append("plymouth-encrypt")`

This affects Arch because the plymouth-encrypt hook is no longer packaged since plymouth works with the standard encrypt hook now. Manjaro still packages it with the hook.

**Comment by Boria138** [comment]
Kind of corrected plymouth 
https://github.com/calamares/calamares/pull/2183/commits/5769c9c6da618aaac9c07672caf47b9aeed472f2

**Comment by bkmo** [comment]
This should be resolved when PR #2183 is merged.
