### ISSUE TITLE
Default locale should be international/Oxford or British English, not US English

### ISSUE THREAD

**Issue by getsnoopy** [calamares/calamares#2184]
**Is your feature request related to a problem? Please describe.**
It seems like the installer sets the language drop-down and number/date format drop-down to "English (US)" by default. This, however, makes little sense considering that US English is used by a minority (~26%) of English users around the world. Moreover, the English labels for the two are `American English – English` and `British English (United Kingdom) – English (United Kingdom)`. This is silly, seeing as "English" does not mean US English by default given the previously mentioned fact, and having `(United Kingdom)` next to `British English` is redundant.

Similarly, the number and date formats defaulting to "American English" is even more egregious, as essentially [96% of the world](https://en.wikipedia.org/wiki/Date_format_by_country) does not use these formats.

**Describe the solution you'd like**
The default should be British English for both options, as this is used by [the overwhelming majority of English users](https://en.wikipedia.org/wiki/English_in_the_Commonwealth_of_Nations) around the world. The default keyboard layout, however, can be left as `en_US.UTF-8` because the ANSI keyboard is the most common keyboard layout around the world.

**Describe alternatives you've considered**
An alternative would be to default to [international (Oxford) English](https://en.wikipedia.org/wiki/Oxford_spelling), as it's used by practically every international organization (e.g., the UN, ISO, BIPM, NATO, etc.) and is taught as the standard of English to most second language learners.

**Comment by kkofler** [comment]
Since Unix was designed in the USA, the default locale in all *nix systems is American English. E.g., the untranslated messages, i.e., the ones you get if you set the default `C` locale, or its more modern `C.UTF-8` variant, are always expected to be in American English (though there are a few odd programs using British English or even French there, which is a bad idea).

I also question your statement about the overwhelming majority of English users using British English. That may be true for the native speakers, but English is widely used as a second or additional (third/fourth/…) language. Those people often learn either American English or a weird mix (from textbooks written in British English and other content mostly in American English). The largest single country with English as its official language is the USA. (The most populous is arguably India, but most people in India are actually not native English speakers, and not all even speak English at all.)

**Comment by getsnoopy** [comment]
That may well be, but I'm referring to the locale highlighted by default in the drop-down for the installer, which gives people the option to choose "American English" (`en_US.UTF-8`) and "British English" (`en_GB.UTF-8`) as options, not whether the system uses the `C.UTF-8` locale. This should be highlighting the option that is used overwhelmingly everywhere.

Regarding that, it's a fact that the overwhelming majority of people use British or Oxford English (please see the links I provided). The number of English speakers in Nigeria and India alone (both of which have English as an official language) outnumber those of the US (and that's not counting sheer people, but people who know English and use it). This isn't even including the people from the UK, Australia, New Zealand, etc., and not even including countries which have English speakers where the country's official language is not English (e.g., France, the Netherlands, etc.). British/Commonwealth English speakers/users outnumber US English users 3:1. The options in the installer are clearly not just for native English speakers (which would be silly), so one must consider all English speakers in the world.

Moreover, this isn't even getting to the point about numbers and date formats, for which the installer still defaults to US English conventions. In this metric, it's basically 4% of the world (using the `Month DD, YYYY` format and 12-hour clock in written times) vs. the rest of the 96%, so the default option there is even more egregious.

_PS: Please don't close the issue without a proper discussion even having happened._

**Comment by dalto8** [comment]
The locale defaults are set based on location.

Where it defaults to is configurable by the distro.  If you would like it to default to somewhere else for your distro you can change it.

**Comment by kkofler** [comment]
> The locale defaults are set based on location.

Only if geolocation is enabled by the distribution. Otherwise it just defaults to New York (en_US.UTF-8 locale and America/New_York time zone).

**Comment by thisguy786** [comment]
> Only if geolocation is enabled by the distribution. Otherwise it just defaults to New York (en_US.UTF-8 locale and America/New_York time zone).

Both of those settings, the enablement of geolocation and the default location are controllable by the distro in `locale.conf`.  The distro can set a different location if they don't prefer it to be America/New York.

**Comment by getsnoopy** [comment]
> Only if geolocation is enabled by the distribution. Otherwise it just defaults to New York (en_US.UTF-8 locale and America/New_York time zone).

That's what I'm referring to: I had no internet connection set up when I opened the installer, and it defaulted to those in the drop-down menus. In the absence of any information from the computer or decision made by the distro, the installer should choose the option that is as neutral or ubiquitous as possible.

This should be `Etc/UTC` for the time zone, and `British English` for the locales (which would presumably follow from the time zone).

Of course, if a distro chooses otherwise, they can, but that's a different point.

> To be precise, setting (without geolocation is set at:
> https://github.com/calamares/calamares/blob/calamares/src/modules/locale/locale.conf#L20

So I just need to open a pull request to update that file, yeah?

**Comment by dalto8** [comment]
> Of course, if a distro chooses otherwise, they can, but that's a different point.

Not really.  Distros are expected to change the defaults.  The defaults don't even produce a working system.

> So I just need to open a pull request to update that file, yeah?

It wouldn't be likely to be accepted.

> I had no internet connection set up when I opened the installer, and it defaulted to those in the drop-down menus.

That is an issue you should take up with distro.

**Comment by getsnoopy** [comment]
> The defaults don't even produce a working system.

Unless you're saying that the settings in the `locale.conf` specifically don't produce a working system without having changed them, this doesn't apply. While other settings from the installer might require changing to get it to work as a whole, if the settings in this file work without any change (which seems to be the case), then distributions will not need to change it.

Insofar as that is true, the default should be changed.

> It wouldn't be likely to be accepted.

Why not? New York is not a sensible default for the entire world.

**Comment by dalto8** [comment]
> Why not? New York is not a sensible default for the entire world.

There is no single location that is sensible for the entire world.  The current default is sane and well tested.  As it is something that distros are expected to change anyway, there is little practical reason to change it.

**Comment by kkofler** [comment]
If anything, the default locale should be truly international: `C.UTF-8` locale and `Etc/UTC` time zone. But both of those would need to be supported by Calamares at all (which they are not) before they can become the default.

**Comment by getsnoopy** [comment]
> There is no single location that is sensible for the entire world.

Hence, UTC. Or somewhere in the world that defaults to "British English", since that is an appropriate default for the most number of people in the world.

A distro is a merely a flavour of Linux; changing the default geolocation that that distro will be used in does not make sense for the vast majority of distros which are not "location-dependent" to begin with.

The main concern here is which locale is being chosen by default, not which location on the map pops up first. Insofar as they seem to be linked and that picking a default location is arbitrary (since it is expected to be changed by the user anyway), we should pick a location that yields appropriate results for the most number of users *without requiring any action* (hence, sensible defaults).

**Comment by kkofler** [comment]
Calamares does not currently support UTC at all. The closest you can use is `Atlantic/Reykjavik`, which is effectively UTC, but it will lead Calamares to pick `is_IS` (Icelandic (Iceland)) as the locale for all of `LC_NUMERIC`, `LC_TIME`, `LC_MONETARY`, `LC_PAPER`, `LC_NAME`, `LC_ADDRESS`, `LC_TELEPHONE`, and `LC_MEASUREMENT`, since there is a questionable "feature" in Calamares using the time zone as the locale for all of these.

**Comment by kkofler** [comment]
And again, I do not see why the default should be British English and not `C.UTF-8`, which is the operating system's default locale.

**Comment by kkofler** [comment]
And note that `Europe/London` is **not** UTC, it is actually UTC+1 more than half of the year. UTC does **not** perform daylight saving time transitions.

**Comment by getsnoopy** [comment]
> And note that `Europe/London` is not UTC, it is actually UTC+1 more than half of the year. UTC does not perform daylight saving time transitions.

Indeed, but the problem here is that the location and locale are linked, so it's the closest we can get to it at the moment.

> And again, I do not see why the default should be British English and not `C.UTF-8`, which is the operating system's default locale.

Well because right now, it's `American English` and `America/New_York` (which also is a DST time zone), which it surely shouldn't be. And as explained above, `C.UTF-8` is basically American English, which still has all the same issues outlined above.
