### ISSUE TITLE
computer starts in gnu grub

### ISSUE THREAD

**Issue by cregory777** [calamares/calamares#2188]
─$ sudo su
[sudo] password for mastervenger: 
┌──(root㉿kali)-[/home/mastervenger]
└─# update-grub
Searching for GRUB installation directory ... found: /boot/grub
                                                                                
┌──(root㉿kali)-[/home/mastervenger]
└─# grub-install /dev/sda
grub-probe: error: failed to get canonical path of `dev/sda1'.
grub-probe: error: failed to get canonical path of `dev/sda1'.
Could not find device for /boot: Not found or not a block device.
                                                                                
┌──(root㉿kali)-[/home/mastervenger]
└─# sudo grub-install /dev/sda1                   
grub-probe: error: failed to get canonical path of `dev/sda1'.
grub-probe: error: failed to get canonical path of `dev/sda1'.
Could not find device for /boot: Not found or not a block device.
                                                                                
┌──(root㉿kali)-[/home/mastervenger]
└─# sudo sh -x /usr/sbin/grub-mkconfig >/dev/null 2>grub-mkconfig.err

                                                                                
┌──(root㉿kali)-[/home/mastervenger]
└─# sudo fdisk -l                                                    
Disk /dev/sda: 465.76 GiB, 500107862016 bytes, 976773168 sectors
Disk model: ST500DM002-1BD14
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0xdd74e9d2

Device     Boot     Start       End   Sectors   Size Id Type
/dev/sda1  *         2048 974772223 974770176 464.8G 83 Linux
/dev/sda2       974774270 976771071   1996802   975M  5 Extended
/dev/sda5       974774272 976771071   1996800   975M 82 Linux swap / Solaris

Partition 2 does not start on physical sector boundary.
                                                                                
┌──(root㉿kali)-[/home/mastervenger]
└─#  sudo blkid /dev/sda1
/dev/sda1: UUID="8cf1a52c-256a-4578-b5af-9ead5bb3673f" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="dd74e9d2-01"
                                                                                
┌──(root㉿kali)-[/home/mastervenger]
└─# mount /dev/sda1 /boot/efi
mount: /boot/efi: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
                                                                                
┌──(root㉿kali)-[/home/mastervenger]
└─#  grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=debian --force
Installing for x86_64-efi platform
Unrecognized option `--target=x86_64-efi'
Usage: grub-install [OPTION] install_device
Install GRUB on your drive.

**Comment by cregory777** [comment]
ow can i fix this

**Comment by dalto8** [comment]
This doesn't appear to be a Calamares issue from your description.  It would probably be better to get assistance from the distro instead of Calamares.

**Comment by kkofler** [comment]
Make sure you are using `grub-install` from the `grub2-common` package, not the `grub-legacy` package. Calamares does not support GRUB Legacy (GRUB 1), only GRUB 2.

**Comment by dalto8** [comment]
This doesn't appear to be a calamares issue and since there is no feedback we will close this issue.
