### ISSUE TITLE
Choose the drive to install dualboot

### ISSUE THREAD

**Issue by IndexZeroZzz** [calamares/calamares#2198]
**Is your feature request related to a problem? Please describe.**
When you make dualboot with automatic partitioning, calamares chooses the drive itself and you can't choose it.

**Describe the solution you'd like**
Allow user to choose the drive, like when making full format of drive.

**Comment by dalto8** [comment]
Can you clarify what you are referring to?  Calamares offer the ability to select the disk:
![image](https://github.com/calamares/calamares/assets/57767042/b1c1732b-a4de-4f61-819a-a9ce656c51f6)

Also, just to clarify, "Install alongside" doesn't refer to dual boot.  It refers to installing to a disk that already contains other data.

**Comment by IndexZeroZzz** [comment]
> Can you clarify what you are referring to? Calamares offer the ability to select the disk: ![image](https://user-images.githubusercontent.com/57767042/266034252-b1c1732b-a4de-4f61-819a-a9ce656c51f6.png)
> 
> Also, just to clarify, "Install alongside" doesn't refer to dual boot. It refers to installing to a disk that already contains other data.

Sorry, didn't know about this. Kubuntu's calamares doesn't allow you to choose the drive when you choose "Install Alongside"

**Comment by dalto8** [comment]
You might want to discuss with Kubuntu but, again, "Install alongside" doesn't mean dual-boot.

Even choosing "Erase disk" could result in a dual-boot as long as you choose a different disk than where your other OS is and don't mind erasing that disk.
