### ISSUE TITLE
Remove keymap and consolefont hooks from mkinitcpio 

### ISSUE THREAD

**Issue by Boria138** [calamares/calamares#2200]
**Is your feature request related to a problem? Please describe.**
With these hooks error "setfont kdfontop function not implemented" appears 

**Describe the solution you'd like**
Earlier I suggested to add setfont in binaries, but with the new kernel version this approach leads to another error, so the best solution is to remove these hooks altogether, because consolefont can be set without them as well as keymap.

**Describe alternatives you've considered**
It looks like using systemd hooks also solves this problem but I haven't tested this solution since systemd hooks can break some things

**Additional context**
To check if it helps I used Cyrillic without these hooks Cyrillic is also displayed fine

**Comment by dalto8** [comment]
It looks like this may be fixed upstream:
https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/merge_requests/259

**Comment by Boria138** [comment]
> It looks like this may be fixed upstream:
> https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/merge_requests/259

This fix just adds setfont to binaries if there is a consolefont hook, but then there might be another error, so I think it is better to remove the hook, because consolefont is applied without it using the systemd service.

**Comment by Boria138** [comment]
Although maybe I misunderstood the code, because it says it's a fix for distributions without systemd and it adds setfont which is part of systemd.

**Comment by adriaandegroot** [comment]
There are knobs for this now.
