### ISSUE TITLE
Calamares is compiled with latest libs but still refers to old libs

### ISSUE THREAD

**Issue by D3vil0p3r** [calamares/calamares#2201]
Since `yaml-cpp` has been updated to the 0.8.0 version, I recompiled Calamares in an environment containing only:
```
lrwxrwxrwx root root  18 B  Mon Sep 11 10:15:57 2023  /usr/lib/libyaml-cpp.so@ ⇒ libyaml-cpp.so.0.8
lrwxrwxrwx root root  20 B  Mon Sep 11 10:15:57 2023  /usr/lib/libyaml-cpp.so.0.8@ ⇒ libyaml-cpp.so.0.8.0
.rwxr-xr-x root root 306 KB Mon Sep 11 10:15:57 2023  /usr/lib/libyaml-cpp.so.0.8.0*
```
When I run Calamares, it fails because of:
```
WARNING: No factory: "Cannot load library /usr/lib/calamares/modules/loginchooser/libcalamares_viewmodule_packagechooser.so: (libyaml-cpp.so.0.7: cannot open shared object file: No such file or directory)"
```
Why it is still referring to the older version of yaml-cpp despite I compiled it in a new clean machine with no 0.7 version?

Recompiled again just now and same issue...

**Comment by demmm** [comment]
This is not a help channel:
https://calamares.io/issues/#developers-of-distributions

For help figuring where you have old yaml-cpp, please use the Matrix channel.  This is not a Calamares issue or feature request.

**Comment by adriaandegroot** [comment]
If you don't recompile your custom modules against updated shared libraries, that's really your own problem.
