### ISSUE TITLE
Issue with running

### ISSUE THREAD

**Issue by KittenPixel-cell** [calamares/calamares#2211]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
When I build and run it pops up with a screen saying stuff couldn't load?

**To Reproduce**
Unknown steps for reproducing

**Expected behavior**
The installer to pop up the home screen of it

**Screenshots and Logs**
![image](https://github.com/calamares/calamares/assets/79544605/e596e567-5c8c-4bee-b062-0f207d828934)

**Additional context**
none

**Comment by adriaandegroot** [comment]
The issue tracker isn't for debugging help. Use the Matrix channel for debugging help (and be patient).

That said, you mention "build and run" so I am going to assume you are a distro-developer or distro-builder, trying to build and use Calamares on a live-ISO image of your distro. You *must* read the Calamares log file (at `~/.cache/calamares/session.log` of the user who is running it -- that might be your live user, and that might be root). That will tell you exactly where Calamares is trying to load modules from and why each module succeeds or fails.

**Comment by KittenPixel-cell** [comment]
wheres the Matrix channel?

**Comment by KittenPixel-cell** [comment]
Please respond.

**Comment by KittenPixel-cell** [comment]
I can't make a account on the matrix channel.

**Comment by dalto8** [comment]
You don't have to register on that server.  Choose any matrix server.
