### ISSUE TITLE
Add optional env vars for ProcessJob

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#2212]
I'm using `ProcessJob` to call `apt`. I'd like to set an environment variable to reliably change `apt` behavior, but inserting the env var as a prefix doesn't work.

I propose we add an optional argument to `ProcessJob` which accepts env vars, that are set before running the command.

**Comment by adriaandegroot** [comment]
I think that's a great idea, actually. We should do it both for contextual and for process *modules*, by doing whatever futzing needs to be done internally (the module is what is exposed to the distro-user of Calamares, `ProcessJob` and similar are the internal implementation details)
