### ISSUE TITLE
Flatpak on /home Option

### ISSUE THREAD

**Issue by genefyx** [calamares/calamares#2216]
**Is your feature request related to a problem? Please describe.**
I’ve defaulted to using Flatpaks, but have been running into root file size issues.
The suggested 15GB - 25GB file size resulted by search engines is no longer enough with regular Flatpak use.
In attempting to reinstall to a larger size HDD, I thought of asking for a Calamares Feature Request

**Describe the solution you'd like**
The option to:
- Install/Restore flatpaks to/from the /home partition 
  * (Calamares option under Flatpaks && Replace a Partition: “[ ]Flatpaks in /home” which would symlink to ~/flatpak
- Or: Create a custom installation file: 
  * https://docs.flatpak.org/en/latest/tips-and-tricks.html#adding-a-custom-installation

**Describe alternatives you've considered**
I had created a Distro specific request with the option for software center. 
They had suggested creating a Calamares upstream request which appears to more appropriate

**Additional context**
This feature would help greatly as after choosing original file sizes many users may be affected by later Flatpak usage
competing with root for file space. Thank you, I appreciate such a great installer, the "Replace a Partition" is my favorite feature and I hope this feature will be considered.

**Comment by dalto8** [comment]
IMO, this is something that should be distro-specific, not part of Calamares.  Every distro is different.

There is an inherent assumption here that `/home` is larger and/or different than `/`.  This often isn't the case.

Of course, any distro could use the functionality in Calamares to do this already using the existing modules.

Lastly, I am not sure I understand the logic of forcing system flatpaks to be installed in a single user's home directory.  Flatpak already offers support for this with user flatpaks.


> I had created a Distro specific request with the option for software center.

IMO, this is where it belongs.  The software center should allow you to choose between system flatpaks and user flatpaks.  Then there would be no need to change paths or create symlinks.

**Comment by kkofler** [comment]
People should just stop using Flatpaks (or other containerized applications, e.g., Snaps). They are a horrible waste of space, and the bundled libraries are a security nightmare. See:
* http://flatkill.org/
* https://ludocode.com/blog/flatpak-is-not-the-future
* https://blog.brixit.nl/developers-are-lazy-thus-flatpak/

**Comment by yochananmarqos** [comment]
@dalto8 

> The software center should allow you to choose between system flatpaks and user flatpaks.

What software center? Neither GNOME Software, Discover nor Pamac has this feature. Why should they?

**Comment by dalto8** [comment]
> @dalto8
> 
> > The software center should allow you to choose between system flatpaks and user flatpaks.
> 
> What software center? Neither GNOME Software, Discover nor Pamac has this feature. Why should they?

flatpak provides functionality to choose if you install the flatpak to the system or for the user.

The OP is requesting a way to have flatpaks be installed to their home directory.

IMO, having the software center offer the choice between user and system installs for flatpaks much much more sense than adding functionality to Calamares to change the default flatpak location for system flatpaks to be inside the user's home directory.

Alternatively, the end-user could just configure their flatpak remotes to only have user remotes.

**Comment by adriaandegroot** [comment]
@kkofler Stop being rude in arbitrary issues. We get it, you don't like containerized apps. That has no bearing on the technical discussion of the feature request, nor on whether it rolls out for your particular distro.

@genefyx I think the way to go for this request is to use *packagechooser* (which doesn't necessarily have to be about packages) to present the user with a choice -- flatpak per-user or system-wide -- and then use *contextualprocess* to handle that choice later. You can then do whatever configuration needs to be done in the target system, after it is installed, based on the user's choice.

This makes the feature independent: doesn't need any changes in Calamares code, and you can drop in the choice+handling into your `settings.conf` if it is something you like. It would be keen to have an example of the two -- eg. just the config-files and things for sertting this up -- in the *calamares-extensions* repo to serve as an example to other potential users.

**Comment by adriaandegroot** [comment]
Closing as "I think this is out-of-scope" and "this has an acceptable solution without code in Calamares with existing modules".
