### ISSUE TITLE
I can't get calamares to start after building it

### ISSUE THREAD

**Issue by SysWhiteDev** [calamares/calamares#2218]
It seems like the installer can't access some shared libraries

**To Reproduce**
1. Just build calamares and try starting it

**Expected behavior**
You should get this error in the terminal when starting calamares:

```
root@hideos ~ # calamares
calamares: error while loading shared libraries: libKF5Crash.so.5: cannot open shared object file: No such file or directory
```

**Additional context**
I am trying to implement calamares in my archiso

**Comment by demmm** [comment]
Issues are are for bug reports or feature requests, they are not a help channel:
https://calamares.io/issues/
https://calamares.io/issues/#developers-of-distributions
Use the Matrix channel for help, if you can't figure how to fix the clear error of the missing library.

**Comment by SysWhiteDev** [comment]
I am deeply sorry, i was convinced it was a bug

**Comment by SysWhiteDev** [comment]
@demmm can you please this issue?
