### ISSUE TITLE
installer crashes

### ISSUE THREAD

**Issue by genesoo77072** [calamares/calamares#2220]
Attempting to install Neon Unstable 10/22/23 

Installer crashes with Detail:
Executable: _neon PID: 1735 Signal: Segmentation fault (11) Time: 23 Oct 2023 01:09:30 CDT

Developer Information is empty with message:
The debugger has quit unexpectedly.

Reload seems to start collecting crash data but terminates unsuccessfully.

No calamares log could be found based on reporting instructions for new issue.

**Comment by demmm** [comment]
For end users, it is far better to report any issue with your distribution:
https://calamares.io/issues/
https://calamares.io/issues/#end-users
If your distrubution then decides it is an upstream Calamares problem, they can then report here (with full system info, logs and backtracks).

**Comment by adriaandegroot** [comment]
That's probably KDE neon packaging the latest HEAD commit from *calamares* branch, which is pre-alpha unstable. We fixed some of the issues, but for neon unstable in particular, it's better to report on Matrix and be on-hand for debugging and rebuilding, than to file issues.
