### ISSUE TITLE
[REGRESSION] grubcfg module fails to append missing items to the end of /etc/default/grub

### ISSUE THREAD

**Issue by ArrayBolt3** [calamares/calamares#2233]
**Describe the bug**
When using the grubcfg module to add items to /etc/default/grub that don't exist in the file yet, the added items are silently ignored. For instance, if doing an installation with encrypted /boot, `GRUB_ENABLE_CRYPTODISK=y` has to be set in /etc/default/grub. However, if the `GRUB_ENABLE_CRYPTODISK` option doesn't existing in the config file by default, attempting to add it with a line like `GRUB_ENABLE_CRYPTODISK: true` in the grubcfg YAML configuration file will fail silently, resulting in an installation failure when Calamares attempts to install the bootloader.

This bug is being observed in Calamares 3.3.0-alpha4 on Lubuntu Noble (24.04 development version), causing this bug in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/2043301. However, the file that appears to be the source of the bug appears to be identical in git master and in Calamares 3.3.0-alpha4.

**To Reproduce**
1. Download the latest daily ISO of Lubuntu Noble from https://cdimage.ubuntu.com/lubuntu/daily-live/current/.
2. Launch the ISO in a VM with at least 15 GB of disk space.
3. Open QTerminal in the VM.
4. Run `vim /etc/calamares/modules/grubcfg.conf and verify that the contents are as follows:
```
overwrite: false
defaults:
    GRUB_ENABLE_CRYPTODISK: true
```
5. Run `vim /etc/default/grub` and verify that no `GRUB_ENABLE_CRYPTODISK` option can be seen in this file.
6. Run the installer, enabling the "Encrypt system" feature on the "Partitions" screen.
7. Start the actual installation and wait for it to finish.

**Expected behavior**
The installation should finish on the "All done" screen.

**Actual behavior**
The installation fails with an error indicating that the `grub-install` command failed. If you run `sudo vim /root/.cache/calamares/session.log` in a terminal and search for `grub-install` you will find that GRUB is complaining about the `GRUB_ENABLE_CRYPTODISK` option not being set to `y`.

**Suggested fix**
The bug here appears to be in the function `update_existing_config` in the file https://github.com/calamares/calamares/blob/calamares/src/modules/grubcfg/main.py. The function states that "Items that exist in the file will be updated and new items will be appended to the end". However, only the code that updates the existing contents are present, and there is no code that appends any remaining items to the end. I was able to solve this by opening the corresponding file in the Lubuntu filesystem (`/lib/x86_64-linux-gnu/calamares/modules/grubcfg/main.py`), and making two changes:
1. I changed the `if key in grub_config_items.keys():` block to this:
```
if key in grub_config_items.keys():
    print(f"{key}={grub_config_items[key]}")
    del grub_config_items[key]     # this line is added
```
2. Then at the bottom of the function (below the final `else: print(line)`), I added:
```
if len(grub_config_items) != 0:
    with open(default_grub, "a") as grub_file:
        for dict_key, dict_val in grub_config_items.items():
            grub_file.write(f"{dict_key}={dict_val}")
```
After making these modifications, I was then able to install Lubuntu successfully.

**Additional context**
The commit that introduced this bug appears to be https://github.com/calamares/calamares/commit/a45f6a316e6eafd3f01d6013d88d328b7199fef8.

**Comment by dalto8** [comment]
By default, the `defaults` array is only used when `overwrite` is set to true.

If you want it to be used all the time, you need to set `always_use_defaults: true`

**Comment by ArrayBolt3** [comment]
@dalto8 We've been using Calamares 3.3 for well over six months and updated our configuration to be compatible with 3.3 long ago. In alpha3 this worked, in alpha4 this regressed.

I had tried setting `always_use_defaults: true` and it has no effect.

As I understand it, the `update_existing_config` function gets called if `overwrite` is false, and the `default_grub` file exists, and the `prefer_grub_d` option is not set, all of which are true in this instance. That's the function that is missing append functionality.

**Comment by ArrayBolt3** [comment]
@dalto8 I don't believe the `defaults` array is involved here, fwiw. In any event the `update_existing_config` function is getting called despite `always_use_defaults` being unset, and it doesn't appear that the `always_use_defaults` setting is used to determine whether to run `update_existing_config` or not (perhaps that's a bug of its own?).

**Comment by dalto8** [comment]
> it doesn't appear that the `always_use_defaults` setting is used to determine whether to run `update_existing_config`

It is used to determine whether to read the defaults at all.  Unless `overwrite`, `update_existing_config` is set or the config file doesn't exist, it doesn't read that config at all.

> In alpha3 this worked, in alpha4 this regressed.

The commit you linked was from 2022.  It should be in alpha3 and alpha4.  Prior to that commit, it didn't support updating the config file with items from `defaults` at all.

That being said, `GRUB_ENABLE_CRYPTODISK` is calculated.  It is possible that it was always being ignored and prior to alpha4 was being calculated differently.

> The function states that "Items that exist in the file will be updated and new items will be appended to the end".

I think this comment is in error.  I don't believe it has ever actually done that.

It only updates the existing values.

It seems much more likely that the calculated value for `GRUB_ENABLE_CRYPTODISK` has changed for some reason in your scenario.  It may be related to the recent changes surrounding encryption hooks.  Perhaps there was some unintended consequence there.

**Comment by ArrayBolt3** [comment]
> It is used to determine whether to read the defaults at all. Unless overwrite, update_existing_config is set or the config file doesn't exist, it doesn't read that config at all.

The function seems to not need to load the defaults ahead of time - it just skips anything that isn't set and copies it verbatim, only changing things that are set. (So in a way it is reading the config, it just isn't doing it the way it would if defaults were read.) I'm sure there's a subtle difference between loading and not loading defaults that I'm missing, but they seem to do more-or-less the same thing.

> The commit you linked was from 2022. It should be in alpha3 and alpha4. Prior to that commit, it didn't support updating the config file with items from defaults at all.

Apologies, I misspoke. This worked in alpha2, and broke in alpha4. I had assumed that we upgraded from alpha3 to alpha4, but looking closer at the packaging I see we skipped alpha3. Sorry about that.

> That being said, GRUB_ENABLE_CRYPTODISK is calculated. It is possible that it was always being ignored and prior to alpha4 was being calculated differently.

Perhaps. But since the cryptodisk value isn't in `/etc/default/grub` at all to begin with, I don't see any scenario in which is can get added to the file with the current code. As you pointed out, the comment in `update_existing_config` is wrong. But it seems as if the function that calls it (`modify_grub_default`) uses it as if that comment was correct.

> Alternatively, maybe the file once contained the value?

Possibly, I'll check.

**Comment by dalto8** [comment]
> Apologies, I misspoke. This worked in alpha2, and broke in alpha4. I had assumed that we upgraded from alpha3 to alpha4, but looking closer at the packaging I see we skipped alpha3. Sorry about that.

That change was made prior to the 3.3 merge so it was in all the alpha's.

**Comment by ArrayBolt3** [comment]
The grubcfg/main.py file from alpha2 doesn't appear to have the `update_existing_config` function at all though? https://github.com/calamares/calamares/blob/v3.3.0-alpha2/src/modules/grubcfg/main.py

**Comment by ArrayBolt3** [comment]
(btw I just joined the Matrix room for Calamares, if it would be more comfortable to discuss things there I can switch over easily.)

**Comment by dalto8** [comment]
> The grubcfg/main.py file from alpha2 doesn't appear to have the `update_existing_config` function at all though?

That is strange, but if that was the case, that older code didn't even use the default values to update the config at all.  So there is no way that value was getting added to an existing config file unless it was using the calculated value.

Do the older versions of `/etc/default/grub` also not contain that key on your distro?

**Comment by ArrayBolt3** [comment]
> Do the older versions of /etc/default/grub also not contain that key on your distro?

It appears that Lubuntu 23.10 (which uses 3.3.0~alpha2) does not have `GRUB_ENABLE_CRYPTODISK` in the /etc/default/grub file either. However an encrypted installation (with encrypted /boot) works just fine there.

**Comment by dalto8** [comment]
OK, so I guess we need to reintroduce the ability to add keys to the existing file.
