### ISSUE TITLE
3.3.0-alpha5 doesn't install config files to /usr/share/calamares/modules for python modules

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#2238]
**Describe the bug**
A clear and concise description of what the bug is. Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.

**Expected behavior**
Since I rename services-systemd to services I noticed that python module configs don't get installed to `/usr/share/calamares/modules` when `INSTALL_CONFIG=ON` is used. They are somehow kept in `/usr/lib`. I didn't test to compile it with **legacy** boost.

**Screenshots and Logs**
Build-Log:  [3.3.0alpha5.r11672.c490434f0-1-build.log](https://github.com/calamares/calamares/files/13370814/3.3.0alpha5.r11672.c490434f0-1-build.log)
Packages-File-List: [3.3.0alpha5.r11672.c490434f0-1-tree.log](https://github.com/calamares/calamares/files/13370817/3.3.0alpha5.r11672.c490434f0-1-tree.log)

**Comment by demmm** [comment]
Confirmed here (and reported on Matrix too), this patch fixed the install location with pybind11 build:
https://github.com/KaOSx/calamares/commit/745d4b83e621ec2cac99b77b4b5632b01c7b2602

**Comment by adriaandegroot** [comment]
Fixed in 5f06b321b
