### ISSUE TITLE
Calamares might need changes due to Appstream 1.0 release

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#2239]
**Describe the bug**
Arch Linux just pushed Appstream 1.0 to their repos. There are several rebuilds and patches added for application like deepin-store, discover and others. Maybe we also need to adapt to changes made in Appstream 1.0 release.

**To Reproduce**
- Calamares uses **apstream-qt5** on Arch Linux now
- Compiling of both 3.2.62 and current 3.3-alpha6 went fine (however appstream was not found)

**Expected behavior**
Adopt to Appstream 1.0 changes

**Screenshots and Logs**
Build-Log:  [calamares-3.2.62.log](https://github.com/calamares/calamares/files/13401951/calamares-3.2.62.log)

**Additional context**
Here some patches from other applications:
https://gitlab.archlinux.org/archlinux/packaging/packages/deepin-store/-/blob/30e12d5fa8d7c9d1bb8bdb77977a4eedd4f9a9f2/appstream-1.0.patch
https://gitlab.archlinux.org/archlinux/packaging/packages/discover/-/blob/9bef5c42c4c1fd615014d73387bd47fd963755d3/appstream-1.0.patch
https://gitlab.archlinux.org/archlinux/packaging/packages/plasma-workspace/-/blob/ce262dec7287bff82ab0fe47470334cd9bbeffcc/appstream-1.0.patch

**Comment by demmm** [comment]
Just to make sure you know there are already several patches added for Appstream 1.0:
https://github.com/calamares/calamares/commit/757f8a8f9ed2c226bc1064d54de1fe3fe7ba3974
https://github.com/calamares/calamares/commit/a6dd49ac0789ae172b2e00b04a665a3dfce09590

**Comment by philmmanjaro** [comment]
OK, have to check the git version then once more.

**Comment by philmmanjaro** [comment]
Seems appstream-qt is not found after all: [3.3.0alpha6.log](https://github.com/calamares/calamares/files/13403068/3.3.0alpha6.log)

**Comment by adriaandegroot** [comment]
Not sure what you're asking for, here. If there are different names of the AppStream config file (AppStream*Config.cmake) then you'll need to say what they are. You could say "the Arch package is called appstream-qt5, and it installs a config file AppStreamQt5Config.cmake" for instance. That's inconvenient, because it means potentially searching for AppStream twice by Calamares. I'm not going to play guessing games as to how distro's name things (unless it's Debian, openSUSE, Fedora, or EndeavourOS).

**Comment by philmmanjaro** [comment]
To compile with **appstream-qt5** package on Arch-based distros this patch is needed: https://gitlab.manjaro.org/packages/extra/calamares/-/blob/master/arch-appstream-qt5.patch

**Comment by adriaandegroot** [comment]
There is now CMake machinery to help figure this (multiple AppStreamQt versions, variations in CMake module names and include directories).
