### ISSUE TITLE
Unclear string

### ISSUE THREAD

**Issue by yarons** [calamares/calamares#2241]
https://github.com/calamares/calamares/blob/65f93168f23bdbc7b8b55ca7115979d9ea39357c/src/modules/keyboard/KeyboardPage.ui#L153

I was trying to translate this string but I'm not sure what it means, is it a keyboard key? layout switch? some other switch? It's hard to tell.
Thanks.

**Comment by dalto8** [comment]
Honestly, we probably need to fix the English string there.  Looking at it context, I think it should be "Switch keyboard".  It is a label for a dropdown/combobox allowing you to choose between keyboards.

**Comment by adriaandegroot** [comment]
It probably *should* be "Switch keyboard", and with a comment like "shortcut keys to switch from one keyboard layout to another".

**Comment by adriaandegroot** [comment]
Fixed in 8748a52c6821641f05cd8b1b204398ea44236807
