### ISSUE TITLE
[modules/initcpiocfg/main.py] replace old-style bash array 

### ISSUE THREAD

**Issue by fhdk** [calamares/calamares#2243]
[modules/initcpiocfg/main.py] replace old-style bash array 

The module uses the oldstyle bash array.

The attached patch file change the array format to use brackets instead of quotation marks.

    MODULES=""

becomes

    MODULES=()

[01-calamares-fix-oldstyle-arrays-mkinitcpio.patch.txt](https://github.com/calamares/calamares/files/13447149/01-calamares-fix-oldstyle-arrays-mkinitcpio.patch.txt)

**Comment by adriaandegroot** [comment]
@dalto8 can you take a look at this? It seems like a "yeah, whatever" kind of change but I don't know how sensitive initcpiocfg is to the varieties of bash syntax.

**Comment by dalto8** [comment]
This matches the upstream default which changed a while back(More than a year ago).

I think this is a good change.  Although, it would probably be more readable with fstrings.  

It is an improvement either way.

**Comment by adriaandegroot** [comment]
@fhdk Please file a regular merge request  / pull request for this - apply the patch to the initcpiocfg code, add your name to CHANGES (can be a separate commit), file PR. Then we have the usual workflow, and credits where due.

**Comment by fhdk** [comment]
I have added PR

**Comment by dalto8** [comment]
Closing via https://github.com/calamares/calamares/commit/63ce03680b8e59d9d04cab4c7f858c4a17de51f4
