### ISSUE TITLE
[refactoring][python] module initcpiocfg

### ISSUE THREAD

**Issue by papajoker** [calamares/calamares#2244]
Why create a class cpuinfo in actual file ?

Not useful in this module, exists only [one call](https://github.com/calamares/calamares/blob/calamares/src/modules/initcpiocfg/main.py#L238)

Can replace by simple function, less memory, more speed and no import `OrderedDict`
```
def cpu_vendor(vendor = "intel") -> bool:
    """ cpu is intel or amd ? """
    vendors = {"intel": "genuineintel", "amd": "authenticamd"}
    with open("/proc/cpuinfo") as cpuinfo_file:
        for line in cpuinfo_file:
            if line.startswith("vendor_id"):
                #TODO ? test if vendor not a key 
                return vendors[vendor] == line.split(":", maxsplit=2)[1].strip().lower()
    return False
...
 modules.append("crc32c-intel" if cpu_vendor("intel") else "crc32c")
```
Or a little more simple by function `is_intel()` ...

**Comment by dalto8** [comment]
If you have a proposed optimization, feel free to submit a PR.

**Comment by adriaandegroot** [comment]
The code is definitely over-wrought (see commit messages in it). It needs a couple of things -- cpu type, core count, whatever. Anything that can return those bits of information is fine, preferably while reading the `cpuinfo` file just once. But this is code that is run just once, so it's not like performance is important.

**Comment by adriaandegroot** [comment]
This is firmly in "PR is welcome" territory.
