### ISSUE TITLE
Enh: Include gparted ui elements

### ISSUE THREAD

**Issue by Actr0n** [calamares/calamares#2254]
Hello,

i thought it would look familiar to include the gparted ui elements in calamares,
since i think looks cool and already contains a bunch of features.

![Screenshot from 2023-12-12 20-41-03](https://github.com/calamares/calamares/assets/17412080/bbece1d6-ab79-400c-a52e-a548565d3860)

kind regards

**Comment by demmm** [comment]
Kind of a similar request as a few years ago:
https://github.com/calamares/calamares/issues/1710
It was closed then, since no-one stepped up to implement.
Partitionq would make it possible to create any kind of GUI, but that work is also stalled:
https://github.com/calamares/calamares/issues/1954

**Comment by Actr0n** [comment]
Hi, thanks for mentioning issues which need to be fixed first. I'll stale this issue until #1954 is fixed and will take a look whether I can help.
