### ISSUE TITLE
What's With The Unencrypted "/boot" Warning After Moving On From "Manual Partitioning?"

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [calamares/calamares#2256]
From what I've read on the Arch/Manjaro universe, it's not possible to encrypt "/boot," "boot/efi," and or "/efi." So why is that when one tries to only manually set up encrypted "/home," "/," and "/swap" partitions, calamares shows a pop-up with a scary warning that it considers leaving /boot unencrypted so the PC can boot from it a security risk?

**Comment by dalto8** [comment]
> it's not possible to encrypt "/boot," "boot/efi," and or "/efi."

It is possible to encrypt `/boot` as long as your EFI partition isn't mounted there.

Is that warning still there in the latest code?  I thought it had been removed in more recent versions.

It is technically true that it is more secure to encrypt your initrd.  If it is *meaningfully* more secure is questionable.

**Comment by neurodiverseEsoteric** [comment]
Yeah, that efi bit what was mentioned here:
 https://forum.manjaro.org/t/luks-encrypted-boot-partition/96023

https://unix.stackexchange.com/questions/702498/grub-install-with-encrypted-boot-partition

The warning may have been removed, but it's still in the versions used by manjaro, nobara, and probably a ton of other distros...

**Comment by tsimonq2** [comment]
We recently received some followup opinions from the Ubuntu Security Team and the Ubuntu Foundations Team on this issue. I'm not saying to blindly trust us, what I **am** saying is I vouch for them; especially the Security Team, they're very well-read.

The impact of an unencrypted boot, in reality, I'm told is negligible. Here's a quote:

 > IMHO it's hard to see value from encrypting the boot process: an attacker could replace either one just fine, right? That's where the signatures come in, but that really only helps if the measurements contribute to unsealing a key for the rest of the data, and I'm not sure that's really there for most platforms yet

Also, you're at the mercy of GRUB's encryption protocols, which do not receive security updates. 

Lubuntu will be disabling FDE and keeping /boot **unencrypted** for 24.04. I'd suggest we at least re-visit this discussion.

**Comment by dalto8** [comment]
The latest version of Calamares has an option for this in partition.conf, `showNotEncryptedBootMessage`.

It is up to each distro to decide if they want the message or not.

**Comment by neurodiverseEsoteric** [comment]
Okay thanks
