### ISSUE TITLE
 Installer lists "American English" twice on welcome step

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#2257]
I'm upstreaming this bug [from Launchpad](https://bugs.launchpad.net/ubuntu/+source/calamares/+bug/2045741).

Testing Lubuntu Noble daily image 20231205.1

The installer lists "American English" twice on the welcome screen.

Minor bug that has no real influence on the install. see attached screenshot

ProblemType: Bug
DistroRelease: Ubuntu 24.04
Package: calamares (not installed)
ProcVersionSignature: Ubuntu 6.5.0-9.9-generic 6.5.3
Uname: Linux 6.5.0-9-generic x86_64
ApportVersion: 2.27.0-0ubuntu6
Architecture: amd64
CasperMD5CheckResult: unknown
CurrentDesktop: LXQt
Date: Wed Dec 6 08:25:31 2023
InstallationDate: Installed on 2023-12-06 (0 days ago)
InstallationMedia: Lubuntu 24.04 LTS "Noble Numbat" - Daily amd64 (20231205.1)
SourcePackage: calamares
UpgradeStatus: No upgrade log present (probably fresh install)

![image](https://github.com/calamares/calamares/assets/3689821/07ceff1b-9a9d-43da-ae16-769397f32987)

**Comment by demmm** [comment]
Which Calamares version is in use?

**Comment by tsimonq2** [comment]
Sorry, I really thought it was in the bug metadata!

We follow the latest **tag** and our only vendor patch (iirc) is for adding apport support (pipe the logs to a special location and trigger apport if needed).

So, to be clear, 3.3.0 :)
