### ISSUE TITLE
Garbage characters on some strings

### ISSUE THREAD

**Issue by bitigchi** [calamares/calamares#2259]
After the release of 3.3.0, some strings have trailing `{1?}`. I missed the step for taking a screenshot beforehand, but I can see in the source translations in the repo.

**Comment by adriaandegroot** [comment]
This has happened before -- see e.g. the CHANGES-3.2 file which mentions stray `{1?}` in translations.

**Comment by adriaandegroot** [comment]
I can see they have been added to the source texts on the Transifex end, and so also ended up in the translations. But there's no `{1?}` in the **actual** source. I do not know what is special about these two strings that they trigger this addition in Transifex.

**Comment by adriaandegroot** [comment]
`lupdate` creates them sometimes. I have hunted them down, pushed new source strings to transifex and added some code to the tx-scripts in an attempt to prevent them from coming back.
