### ISSUE TITLE
CI bot: sucessfully

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#2263]
e.g. ☑ Workflow issues [completed sucessfully 🎉](https://github.com/calamares/calamares/actions/runs/7342718590) for calamares/calamares on branch calamares

`s/sucessfully/successfully/`

**Comment by adriaandegroot** [comment]
You're right, that is a typo in the message, but I'm not entirely sure that is code from any calamares repo sending the message.

**Comment by demmm** [comment]
I'm pretty sure that is a bug in the Element Matrix bot for Github commits, but can't find the repo for it, should be somewhere in here:
https://github.com/orgs/element-hq/repositories?type=all

**Comment by demmm** [comment]
Found the line:
https://github.com/matrix-org/matrix-hookshot/blob/main/src/Connections/GithubRepo.ts#L318
So closing the issue here, not a Calamares issue
