### ISSUE TITLE
Asahi Remix - AZERTY keyboard not applied 

### ISSUE THREAD

**Issue by MonsieurRz** [calamares/calamares#2264]
**Describe the bug**
During Asahi Fedora Remix 39 KDE installation the following happens on a 2020 MacBook pro M1.
The selected AZERTY keyboard layout is not applied to the installer configuration.
Calamares version at the time of the installation 3.2.62.

**To Reproduce**
1. Go to keyboard section
2. Select French (AZERTY)
3. Try to type 'azerty' like the displayed layout 
4. But I have written 'qwerty'

**Expected behavior**
The AZERTY layout is applied correctly.

**Comment by kkofler** [comment]
I had [warned](https://github.com/calamares/calamares/pull/2180#issuecomment-1696511436) in the review of PR #2180 that this is not going to work. Both upstream and downstream still decided to ship that code as is. So it is not a big surprise to me that the keyboard layout is not applied properly on the Fedora Asahi Remix (though I would have expected it to work at least on that particular distribution, but apparently this was committed without even proper testing on the developer's own distribution).

Setting the layout through `locale1` is not going to affect the running Calamares instance. It looks like in Wayland, using compositor-specific protocols (e.g., [this approach](https://github.com/calamares/calamares/pull/2180#issuecomment-1696525114) for KWin) is the only way. (This is a major design flaw in Wayland, and an extension (corresponding the the X11 `xkb` extension) needs to be added to fill that gap. Or maybe a "portal" or something. But it will take months for such an extension/portal/… to be designed and adopted by the compositors. Short-term, we will likely have to support compositor-specific protocols.)

**Comment by ptr1337** [comment]
FYI, this does apply on any layout. QWERTZ also does not get applied on live session.
