### ISSUE TITLE
Slideshow not ported to Qt 6

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#2275]
Using KDE neon unstable which builds Calamares from the "calamares" branch.

Qt is 6.6

The slideshow does not load

Error in log says
```
2024-01-25 - 12:13:36 [2]: void Calamares::SlideshowQML::loadQmlV2Complete()
2024-01-25 - 12:13:36 [2]:     WARNING: QML component not ready: QList(file:///usr/share/ubiquity-slideshow/slides/index.qml:24:1: Type Presentation unavailable
    Presentation
    ^, file:///usr/share/calamares/qml/calamares/slideshow/Presentation.qml:199:35: "Text.padding" is not available in QtQuick 2.5.
                        property real padding: 16;
                                      ^) 
2024-01-25 - 12:13:37 [6]: void Calamares::RequirementsChecker::reportProgress()

```

**Comment by jriddell** [comment]
If I change the import to be `6.0` then the error changes to `Cannot override FINAL property`

**Comment by jriddell** [comment]
Seems to be a general issue of not being ported to Qt 6 so I've updated the title.

**Comment by adriaandegroot** [comment]
Thanks also for the PR you started. Slideshows are fairly "personal" to a distro, so I do not know who uses the stock support files -- I guess you do :)

**Comment by adriaandegroot** [comment]
The QML bits have all been ported (see `src/qml/calamares-qt5/` and `calamares-qt6`).
