### ISSUE TITLE
Translation Problem

### ISSUE THREAD

**Issue by towo2099** [calamares/calamares#2276]
**Is your feature request related to a problem? Please describe.**
Problem: translation in Summary Page

**Describe the solution you'd like**
At the moment the code:  (PartitionViewStep.cpp)

```
static QString
modeDescription( Config::InstallChoice choice )
{
    const auto* branding = Calamares::Branding::instance();
    static const char context[] = "PartitionViewStep";

    switch ( choice )
    {
    case Config::InstallChoice::Alongside:
        return QCoreApplication::translate( context, "Install %1 <strong>alongside</strong> another operating system", "@label" )
            .arg( branding->shortVersionedName() );
    case Config::InstallChoice::Erase:
        return QCoreApplication::translate( context, "<strong>Erase</strong> disk and install %1", "@label" )
            .arg( branding->shortVersionedName() );
    case Config::InstallChoice::Replace:
        return QCoreApplication::translate( context, "<strong>Replace</strong> a partition with %1", "@label" )
            .arg( branding->shortVersionedName() );
    case Config::InstallChoice::NoChoice:
    case Config::InstallChoice::Manual:
        return QCoreApplication::translate( context, "<strong>Manual</strong> partitioning", "@label" );
    }
    return QString();
}
```

will not be translated after Build. I would like to know, what's the cause?

**Describe alternatives you've considered**

Most Strigs in code are `tr(fo bla blub)` and can be translated with help of calamares_$lang.ts but not the above.

**Additional context**
![Clipboard - 25  Januar 2024 10 48](https://github.com/calamares/calamares/assets/37433490/529b83ad-4c61-439b-b2cf-473eefdd630d)

**Comment by adriaandegroot** [comment]
You're right. I had set up the translation mechanism for those strings in a weird way that isn't recognized by the Qt translation system. I've fixed it and pushed the strings to the translators. Hopefully they will be handled quickly and we can include them in the upcoming release.

**Comment by adriaandegroot** [comment]
I did forget to pull translations for 3.3.2, so this isn't translated in that release, but will be in the next.
