### ISSUE TITLE
No English keyboard layout after installation

### ISSUE THREAD

**Issue by behdanisohrab** [calamares/calamares#2307]
**Describe the bug**
Persian only keyboard layout after installing the distribution.
this prevents the user from login into the desktop environment.

Parch Linux Gnome build 2024-03-25 Calamares 3.3.5

**To Reproduce**
1. Install any distribution with offline install like debian live
2. Change the main language to persian or arabic
3. Choose the persian keypad
4. Now you cant login because your password is in english and your keyboard is stuck in persian or arabic

**Expected behavior**
To include Live Session keyboard layout (EN) after install. just like ubuntu ubiquity or fedora anaconda.

**Screenshots and Logs**

- xorg.conf.d file:
[![image.png](https://i.postimg.cc/HnfWS3RV/image.png)](https://postimg.cc/bS9jr0zh)
- GDM
[![image.png](https://i.postimg.cc/MpJKVP1L/image.png)](https://postimg.cc/bsLhjRC0)

**Comment by demmm** [comment]
Can you add the installation log?

**Comment by behdanisohrab** [comment]
installation log

https://paste.ubuntu-ir.org/addw

**Comment by ivan1986** [comment]
i work with near issue some time ago and fix swith layout, but found this
https://github.com/calamares/calamares/pull/2136#issuecomment-1646117190

we have file `src/modules/keyboard/non-ascii-layouts` and it usage in `src/modules/keyboard/Config.cpp:125`

firstly, try adding a line to it for your case, secondly, I’ll repeat that question, why is this file needed, why is this option not activated for all other layouts except English

**Comment by behdanisohrab** [comment]
> i work with near issue some time ago and fix switсh layout, but found this [#2136 (comment)](https://github.com/calamares/calamares/pull/2136#issuecomment-1646117190)
> 
> we have file `src/modules/keyboard/non-ascii-layouts` and it usage in `src/modules/keyboard/Config.cpp:125`
> 
> firstly, try adding a line to it for your case, secondly, I’ll repeat that question, why is this file needed, why is this option not activated for all other layouts except English


Thanks for the information.
I forked the repo and tried adding Persian into that [file](https://github.com/parchlinux/calamares/blob/cae7b9e868acc4a9ffa08a3b1e944b10800b48ec/src/modules/keyboard/non-ascii-layouts), recompiled the calamares and re-installed the distro with it, still the issue persists.

**Comment by ivan1986** [comment]
hm, in your logs

```
14:24:38 [6]: QString SetKeyboardLayoutJob::findConvertedKeymap(const QString&) const
    Looking for converted keymap in "/tmp/calamares-root-16f8pqa0/lib/kbd/keymaps/xkb" 
14:24:38 [6]: QString findLegacyKeymap(const QString&, const QString&, const QString&)
    Looking for legacy keymap "ir" "pc105" "" in QRC 
14:24:38 [6]: bool SetKeyboardLayoutJob::writeVConsoleData(const QString&, const QString&) const
    Trying to use X11 layout "ir" as the virtual console layout 
    .. Written KEYMAP= "ir" to vconsole.conf 0 
14:24:38 [6]: bool SetKeyboardLayoutJob::writeX11Data(const QString&) const
    Writing X11 configuration to "/tmp/calamares-root-16f8pqa0/etc/X11/xorg.conf.d/00-keyboard.conf" 
    .. Written XkbLayout "ir" ; XkbModel "pc105" ; XkbVariant "" to X.org file "/tmp/calamares-root-16f8pqa0/etc/X11/xorg.conf.d/00-keyboard.conf" 0 
14:24:38 [6]: bool SetKeyboardLayoutJob::writeDefaultKeyboardData(const QString&) const
    Writing default keyboard data to "/tmp/calamares-root-16f8pqa0/etc/default/keyboard" 
    .. Written XKBMODEL "pc105" ; XKBLAYOUT "ir" ; XKBVARIANT "" to /etc/default/keyboard file "/tmp/calamares-root-16f8pqa0/etc/default/keyboard" 0 
14:24:38 [6]: virtual void Calamares::JobThread::run()
```

can you try add not only
```
fa        us                  -                    fa
```
but also
```
fa        us                  -                    ir
ir        us                  -                    fa
ir        us                  -                    ir
```
i think ot look on layout, not to locale, and need check `ir`

**Comment by behdanisohrab** [comment]
Thanks for your information, i had added 
```
fa        us                  -                    fa
ir        us                  -                    fa
```
into it and now im testing i hope it works now.

**Comment by behdanisohrab** [comment]
so i fixed the problem and send a PR #2324

**Comment by ivan1986** [comment]
i think `non-ascii-layouts` it's bad solution
many layouts without english letters - all cyrilic, all west and east asia and other
https://en.wikipedia.org/wiki/Keyboard_layout#Keyboard_layouts_for_non-Latin_alphabetic_scripts
https://en.wikipedia.org/wiki/Keyboard_layout#East_Asian_languages

Even the decision to add an English layout additionally for everyone else seems to me to be the best solution, but ideally find some parameter for the layout, and not add it for those who have it in latin (en,fr,de,it,es and other)
All people with this keyboards also use english for work in terminal and web

**Comment by behdanisohrab** [comment]
Yes i agree, it is not a good solution at all.

and i think adding en_US without this file to non english keyboards
automatically is a better solution.

**Comment by kkofler** [comment]
Adding an en_US layout by default to European keyboards with the same Latin letters does not sound like that great an idea to me.

**Comment by behdanisohrab** [comment]
well I can't think of a better solution for this problem 🤷🏻‍♂️

**Comment by kkofler** [comment]
I think the current whitelist solution is fine, any missing non-Latin layouts just need to be added, as in the PR for the Persian one that had been overlooked.

**Comment by ivan1986** [comment]
in `/usr/share/X11/xkb/rules/base` exist this list, i think need start from add this
```
//! $nonlatin = af am ara bd bg bt by eg et ge gn gr id il in ir \
//              jp jv kg kh kr kz la lk ma me mk mm mn mv my \
//              pk rs ru sy th tj tz ua uz
```

**Comment by ivan1986** [comment]
also if look into dir `/usr/share/X11/xkb/rules/` in `base.lst` we can found all layout and non latin more that half, maybe better change ths file to `ascii-layouts` and swap if-else

**Comment by ivan1986** [comment]
#2325
