### ISSUE TITLE
document how to not encrypt /boot

### ISSUE THREAD

**Issue by adrelanos** [calamares/calamares#2308]
* https://github.com/calamares/calamares/issues/1311 implies that an option to have unencrypted `/boot` has been implemented.

I couldn't find information on how to use that.

Could you tell me please, what settings do need to be changed in `/etc/calamares` folder to have unencrypted `/boot` by default?

**Comment by demmm** [comment]
Issues are for bug reports or feature requests, it is not a help channel.
For help, please use the Matrix channel.
https://calamares.io/issues/
https://calamares.io/issues/#developers-of-distributions

**Comment by dalto8** [comment]
There are multiple ways to do that depending on what you want.  The documentation is in [partition.conf](https://github.com/calamares/calamares/blob/calamares/src/modules/partition/partition.conf).
