### ISSUE TITLE
Link errors and qt version mismatch

### ISSUE THREAD

**Issue by jghodd** [calamares/calamares#2309]
Building calamares-3.3.5 does not work. I'm seeing the following errors during the build:

/bin/ld: /usr/lib/libQt6Quick.so.6.6.3: undefined reference to `QFont::stringToTag(char const*)@Qt_6'
/bin/ld: /usr/lib/libQt6Quick.so.6.6.3: undefined reference to `QFont::tagToString(unsigned int)@Qt_6'
/bin/ld: /usr/lib/libQt6Quick.so.6.6.3: undefined reference to `QFont::setFeature(unsigned int, unsigned int)@Qt_6'
/bin/ld: /usr/lib/libQt6Quick.so.6.6.3: undefined reference to `QFont::featureValue(unsigned int) const@Qt_6'
collect2: error: ld returned 1 exit status
make[2]: *** [src/libcalamaresui/CMakeFiles/test_libcalamaresuipaste.dir/build.make:152: test_libcalamaresuipaste] Error 1
make[1]: *** [CMakeFiles/Makefile2:5038: src/libcalamaresui/CMakeFiles/test_libcalamaresuipaste.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

I'm going to speculate that building and installing v6.7.0 of parts of qt6, when the OS itself is only on qt6 v6.6.3 is a big problem, obviously, since the link errors are pointing directly to such an issue. Expected behavior is that a build runs through to completion and doesn't crash due to version mismatches.

The bigger issue is that there is currently no version of calamares that runs or can be built - it's completely useless in its current form, but is badly needed by anyone trying to maintain an archlinux-based distro (and all other sub-distros). This is therefore a *very urgent* bug.

**Comment by dalto8** [comment]
It is building and working fine here on Qt 6.7 and Arch.  Can you share your PKGBUILD?

**Comment by jghodd** [comment]
Sure I can provide the PKGBUILD. It's the one from the AUR, downloaded several times, including today. It might be working under arch with qt6.7, but for all of us regular folks, arch is currently on qt6.6.3 - that's a version mismatch.

To emphasize my point, I had to downgrade qt6-base and qt6-xcb-private-headers just to run a graphical editor to copy and paste the contents of the PKGBUILD. So, the build of v6.7.0 of those 2 packages not only messes up the builder's graphical environment, but they also cause a version mismatch that causes a build/link error.

Apparently I can;t attach a PKGBUILD file, so I'll have to paste it here:

# Maintainer: Rustmilian Rustmilian@proton.me

pkgname=('calamares'
	'calamares-qt5')

pkgver=3.3.5
pkgrel=1
pkgdesc='Distribution-independent installer framework'
arch=($CARCH)
url="https://github.com/calamares/calamares"

license=('BSD-2-Clause'
	'CC-BY-4.0'
	'CC0-1.0'
	'GPL-3.0-or-later'
	'LGPL-2.1-only'
	'LGPL-3.0-or-later'
	'MIT')

depends=('ckbcomp'
	'efibootmgr'
	'gtk-update-icon-cache'
	'hwinfo'
	'icu'
	'kpmcore>=24.01.75'
	'libpwquality'
	'mkinitcpio-openswap'
	'squashfs-tools'
	'yaml-cpp')

makedepends=('extra-cmake-modules' 'git')

backup=('usr/share/calamares/modules/bootloader.conf'
	'usr/share/calamares/modules/displaymanager.conf'
	'usr/share/calamares/modules/initcpio.conf'
	'usr/share/calamares/modules/unpackfs.conf')

source=("$pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz"
	"calamares.desktop"
	"calamares_polkit"
	"49-nopasswd-calamares.rules"
	"paru-support.patch"
	"flag.patch")

sha256sums=('65b11d6bb2ba76fc74fed08faa4b6fe43d1a5bf4a2522b30fc43b44151686c47'
            'b9e65ab87f69b2d3f8f8eaea60c78625aef57dd336314ab75389f31a447445be'
            'c176b28007bd1c1f23d8dbb2c936fa54d0c01bacfb67290ddad597606c129df3'
            '56d85ff6bf860b9559b8c9f997ad9b1002f3fccc782073760eca505e3bddd176'
            'f00c90bd87d6dfd73b3ec53fa9a145ac25234676be41604807f05f05a4bf5bbb'
            '0830c8fe57c94a63ef87b6a025eb729b4f098a9e46e729b63415f4d3a2755762')

prepare() {
	makedepends() {
	if [[ $pkgname == 'calamares' ]]; then
		makedepends+=('qt6-tools' 'qt6-translations')
	elif [[ $pkgname == 'calamares-qt5' ]]; then
		makedepends+=('qt5-tools' 'qt5-translations')
	fi
	handle_qt_version
	}

	handle_qt_version() {
	if [[ $pkgname == 'calamares' ]]; then
		qt=6
		handle_qt6_base
	elif [[ $pkgname == 'calamares-qt5' ]]; then
		qt=5
	fi
	cd "${srcdir}/${pkgname}-${pkgver}" || return
		sed -i 's/"Install configuration files" OFF/"Install configuration files" ON/' "${srcdir}/${pkgname}-${pkgver}/CMakeLists.txt"
		sed -i "s|\${CALAMARES_VERSION_MAJOR}.\${CALAMARES_VERSION_MINOR}.\${CALAMARES_VERSION_PATCH}|${pkgver}-${pkgrel}|g" CMakeLists.txt
		sed -i "s|CALAMARES_VERSION_RC 1|CALAMARES_VERSION_RC 0|g" CMakeLists.txt
		git apply --verbose ../paru-support.patch
	}

##	Non-standard ##
	handle_qt6_base() {
	if ls ./qt6-base/qt6-base-*.pkg.tar.zst 1> /dev/null 2>&1; then
		echo "qt6-base already exists"
		update_qt6_base
	else
		clone_and_build_qt6_base
	fi
	}

	update_qt6_base() {
		cd qt6-base || exit
		echo -e "\e[1;32mUpdate qt6-base? (y/n) : \e[0m\c"
		read -r input
	if [ "$input" = "y" ]; then
		git pull
		git apply --verbose ../flag.patch
		makepkg -sif
	else
		makepkg -si
	fi
	}

	clone_and_build_qt6_base() {
		git clone https://gitlab.archlinux.org/archlinux/packaging/packages/qt6-base.git
		cd qt6-base || exit
		git apply --verbose ../flag.patch
		makepkg -si
	}
##	Non-standard ##

	# Call the function to start the process
	makedepends

}

build() {
	cd "${srcdir}/${pkgname}-${pkgver}" || return
	mkdir -p build
	cd build || return
	cmake .. \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DWITH_QT"${qt}"=ON \
		-DWITH_PYTHONQT=OFF \
		-DWITH_KF5DBus=OFF \
		-DBoost_NO_BOOST_CMAKE=ON \
		-DWEBVIEW_FORCE_WEBKIT=OFF \
		-DSKIP_MODULES="webview \
						tracking \
						interactiveterminal \
						initramfs \
						initramfscfg \
						dracut \
						dracutlukscfg \
						dummyprocess \
						dummypython \
						dummycpp \
						dummypythonqt \
						services-openrc \
						keyboardq \
						localeq \
						welcomeq"
	make
}

package_calamares() {
	depends=('kconfig>=5.246'
		'kcoreaddons>=5.246'
		'ki18n>=5.246'
		'kiconthemes>=5.246'
		'kio>=5.246'
		'polkit-qt6>=0.175.0'
		'qt6-base>=6.6.0'
		'qt6-svg>=6.6.0'
		'solid>=5.246')

	cd "${srcdir}/${pkgname}-${pkgver}/build" || return
	make DESTDIR="$pkgdir" install
	install -Dm644 "${srcdir}/calamares.desktop" "$pkgdir/etc/xdg/autostart/calamares.desktop"
	install -Dm755 "${srcdir}/calamares_polkit" "$pkgdir/usr/bin/calamares_polkit"
	install -Dm644 "${srcdir}/49-nopasswd-calamares.rules" "$pkgdir/etc/polkit-1/rules.d/49-nopasswd-calamares.rules"
	chmod 750 "$pkgdir"/etc/polkit-1/rules.d

}

package_calamares-qt5() {
	depends=('kconfig5>=5.113.0'
		'kcoreaddons5>=5.113.0'
		'kiconthemes5>=5.113.0'
		'ki18n5>=5.113.0'
		'kio5>=5.113.0'
		'solid5>=5.113.0'
		'qt5-base>=5.15.11'
		'qt5-svg>=5.15.11'
		'polkit-qt5>=0.175.0'
		'plasma-framework5>=5.58'
		'qt5-xmlpatterns>=5.15.11')

	cd "${srcdir}/${pkgname}-${pkgver}/build" || return
	make DESTDIR="$pkgdir" install
	install -Dm644 "${srcdir}/calamares.desktop" "$pkgdir/etc/xdg/autostart/calamares.desktop"
	install -Dm755 "${srcdir}/calamares_polkit" "$pkgdir/usr/bin/calamares_polkit"
	install -Dm644 "${srcdir}/49-nopasswd-calamares.rules" "$pkgdir/etc/polkit-1/rules.d/49-nopasswd-calamares.rules"
	chmod 750 "$pkgdir"/etc/polkit-1/rules.d
}

**Comment by dalto8** [comment]
> It might be working under arch with qt6.7, but for all of us regular folks, arch is currently on qt6.6.3 - that's a version mismatch.

Oops.  That is a mistake on my part.  I built it in Qt 6.6.3, not 6.7.

**Comment by jghodd** [comment]
Ok... so now what? I've been working around the clock to get my distro back on line after the mal-timed qt6 release, and all I have left now is the installer. What needs to be changed to get this built. I have to still work on merging in my own customizations which takes a good amount of time in and of itself.

**Comment by dalto8** [comment]
> To emphasize my point, I had to downgrade qt6-base and qt6-xcb-private-headers just to run a graphical editor

It sounds like you have a general issue with Qt on your system.  Why did you have to downgrade Qt to use your tools?

Are you building in a clean chroot?

**Comment by jghodd** [comment]
Qt6-6.6.3 is the current qt release from arch's official repositories. The calamares build builds, and installs, qt6-base and qt6-xcb-private-headers v6.7.0 which are incompatible with qt6-6.6.3 which is the version currently used by my desktop. It's irrelevant whether or not I'm building in a clean chroot environment when the version of qt6 will still be 6.6.3, not 6.7.0.

**Comment by dalto8** [comment]
Oh, I see the issue.  That PKGBUILD is installing a new version of Qt and patching it.

That is a complete mess.  That has nothing to do with Calamares, it is an issue with that PKGBUILD.

I would recommend a simple PKGBUILD that is built to the needs of your distro instead of relying on that.

**Comment by jghodd** [comment]
I tried my original PKGBUILD first and it failed the build because of the dependencies on qt5.

**Comment by jghodd** [comment]
Yeah. That PKGBUILD is force installing v6.7.0 of qt6-base and qt6-xcb-private-headers, which is why I had to downgrade those packages to run any graphical apps.

**Comment by jghodd** [comment]
I'll give that build option a try.

**Comment by jghodd** [comment]
That did the trick. Other than having to remove references to QVariant::Map from WelcomeViewStep.cpp, it all built with the `-DWITH_QT6=ON` option added to the cmake. Thanks much for helping fix this. I'll make sure to pass this info on to the AUR package maintainer.

**Comment by kkofler** [comment]
That AUR PKGBUILD is really broken, why would a calamares package want to build its own Qt? Especially since the minimum required version according to the dependencies further down in the PKGBUILD is only 6.6.0. I guess this hack was added when Arch was still on 6.5.x? In any case, we need to get that fixed in AUR. Clearly a downstream issue.

**Comment by kkofler** [comment]
Looking at that "flag.patch", it looks like a workaround to undo this change:
https://gitlab.archlinux.org/arojas/qt6-base/-/commit/5cd71aed56de955b182e20263a50cd91bf7b6aaa
which was recommended by an upstream developer:
https://bugreports.qt.io/browse/QTBUG-112332
but which seems to break applications:
https://github.com/PrismLauncher/PrismLauncher/issues/991
https://github.com/qutebrowser/qutebrowser/issues/7624

**Comment by kkofler** [comment]
I added a comment to the Qt bug, hoping Qt upstream can help getting this mess cleared up:
https://bugreports.qt.io/browse/QTBUG-112332?focusedId=786408&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-786408

**Comment by spikerguy** [comment]
> It is building and working fine here on Qt 6.7 6.6.3 and Arch. Can you share your PKGBUILD?

Any update for QT 6.7 ?

I am trying to rebuild calamares for qt6.7 and it fails with similar issue even with the QT6 flag.

[Build Log](https://gitlab.manjaro.org/manjaro-arm/packages/extra/calamares/-/jobs/14280)

**Comment by dalto8** [comment]
> Any update for QT 6.7 ?

I am building on x86 but it is working here on Qt 6.7.

**Comment by spikerguy** [comment]
> > Any update for QT 6.7 ?
> 
> I am building on x86 but it is working here on Qt 6.7.

Yes just saw that Manjaro X86 have it working too. I am out of option to know what is causing this to fail. 

Can you advice on something ?

**Comment by adriaandegroot** [comment]
The linked build log isn't very helpful because it doesn't show any errors or any of the build commands. It's a lot more helpful if you have a build log with an error message from the compiler or linker. A repeatable way to reproduce the problem would help, too.

**Comment by spikerguy** [comment]
> The linked build log isn't very helpful because it doesn't show any errors or any of the build commands. It's a lot more helpful if you have a build log with an error message from the compiler or linker. A repeatable way to reproduce the problem would help, too.

For now the fix is to set some LDFlags to the build.

https://gitlab.manjaro.org/manjaro-arm/packages/extra/calamares/-/commit/36071c2540e9eefaee50e1e79e5326843b57e7af#9b9baac1eb9b72790eef5540a1685306fc43fd6c_27_28
