### ISSUE TITLE
Module fstab should not add keyfile/password options in crypttab when luksbootkeyfile module is disabled

### ISSUE THREAD

**Issue by eugenesan** [calamares/calamares#2310]
I am working on Kubuntu installer with systemd-boot, encrypted root, no boot partition.
So far I managed to get it working by altering only config files but there is one issue that requires code change.

When I remove `luksbootkeyfile`, `fstab` still adds keyfile/password option to crypttab, making target unbootable without manual edit of crypttab.

I guess the following logic
https://github.com/calamares/calamares/blob/1645874973669475954e039fbfbd5b3d126fa938/src/modules/fstab/main.py#L159
should check when `luksbootkeyfile` is disabled or/and when bootloader doesn't require access to /boot as it is with systemd-boot which boots linux/initrd from EFI.

Tested on Ubuntu 24.04, Calamares 3.3.5

**Comment by dalto8** [comment]
I think we should fix line: https://github.com/calamares/calamares/blob/1645874973669475954e039fbfbd5b3d126fa938/src/modules/fstab/main.py#L154

It should be "none" by default and only get set to the keyfile path if the keyfile exists.
