### ISSUE TITLE
Feature request: module bootloader should check for plymouth and splash (similarly to grubcfg)

### ISSUE THREAD

**Issue by eugenesan** [calamares/calamares#2311]
Currently when using systemd-boot, bootloader module doesn't check if plymouth is installed and doesn't add "splash" to kernel options.

I suggest replicating the functionality from grubcfg
https://github.com/calamares/calamares/blob/1645874973669475954e039fbfbd5b3d126fa938/src/modules/grubcfg/main.py#L149

**Comment by dalto8** [comment]
Feel free to create a PR for this.
