### ISSUE TITLE
Installation error /usr/sbin/grub-probe: error: failed to get canonical path of `/dev/sdb2'

### ISSUE THREAD

**Issue by Hranitel123** [calamares/calamares#2317]
Platform: Debian Sid
Version calamares 3.3.5-1

An error occurs during installation. The system is not being installed. There is no error on version 3.2.61

```
Running bootloader-config...
 * Installing grub-efi (uefi)...
Reading package lists...
Building dependency tree...
Reading state information...
grub-efi-amd64-signed is already the newest version (1+2.12+2).
grub-efi-amd64-signed set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/usr/sbin/grub-probe: error: failed to get canonical path of `/dev/sdb2'.
```

**Comment by demmm** [comment]
Is this a report from an end-user? If so, it might be better to report to your distribution first:
https://calamares.io/issues/#end-users

If this is a report from a distribution developer, make sure to include all needed info, like installation log, Qt5 0r 6 used, etc:
https://calamares.io/issues/
https://calamares.io/issues/#developers-of-distributions

**Comment by DerGrossmann7272** [comment]
Hello. Topic starter is the developer of this system, I am the main developer.
Config and settings files:
https://repo.d2wos.net/external/gitissue/
ISO image:
https://repo.d2wos.net/iso/d2w_os-2404_Antikorper-1.066-amd64.hybrid.iso
Session.log:
https://repo.d2wos.net/external/gitissue/log/session.log

Description of the problem: we decided to switch to the Debian Sid repository, after which problems began. I tried to specify both the sb-shim and grub loader, but the installation still crashes when I run any script from the grub package.

A modified package calamares-settings-debian is installed on the system

**Comment by DerGrossmann7272** [comment]
Additionally, I’ll point out that I tried to run both with Luks of the first version and the second

**Comment by ptr1337** [comment]
grub doesnt support luks2 and according your configs youre using luks2

**Comment by DerGrossmann7272** [comment]
As I wrote above, I tried both luks1 and luks2

**Comment by demmm** [comment]
Session.log quickly shows that old & new styles are mixed for configuration settings.
Did you you update all .conf files to move from Calamares 3.2 to 3.3?  Considerable changes have been done in (for example) the mount and fstab modules.
See the release notes for more info.  All the .conf files explain current needs too.

**Comment by dalto8** [comment]
Yes, after reviewing your conf files, you are using old versions of those from 3.2.  They need to be updated to version 3.3.  The config options changed substantially.  Without that, it is likely that your partitions aren't being mounted properly which is causing your bootloader installation to fail.

**Comment by demmm** [comment]
Plus there are a lot of big errors in custom modules, make sure they are made compatible with Calamares 3.3 (most obvious fail is in `bootloader-config`, whatever that might include).

**Comment by DerGrossmann7272** [comment]
These are the config files I used from the package calamares-settings-debian (https://salsa.debian.org/live-team/calamares-settings-debian) as well as the scripts. It turns out that most likely that package has not yet been updated. Thanks, I'll fix it. I ask you not to close the topic for a couple of days, because more questions may arise.

**Comment by demmm** [comment]
As noted in the issue link posted for you earlier, issues are not a help channel.  If determined this is a downstream issue, then please close this issue and use the Matrix channel for further questions/assistance.
