### ISSUE TITLE
Calamares Error 100 on Debian 12 custom build.

### ISSUE THREAD

**Issue by gbvunzar** [calamares/calamares#2319]
Good morning, first of all, it's a pleasure to have your help in the possible resolution of problems that may arise for my Calamares Installer. Below I present my problem.

**PROBLEM**
_So, I've created a custom build based on Debian 12 through a script dedicated to it. The build proceeds successfully and an ISO file is created, but when testing it in VirtualBox and after running Calamares, it doesn't finish installing and displays error 100._

_The message in question is the following:
- The package manager could not make changes to the installed system. The command <pre> apt-get --purge -q -y autoremove </pre> returned error code 100._

**CONFIGURATION**
_My virtual machine configuration is 2GB RAM, 2 CPUs and 20GB storage._

Below I attach screenshots and my code to review possible problems. **I must say that I tried to get the Calamares installer logs but the folders don't exist.**

**CODE**
WKDIR="$(pwd)"

mkdir livebuild

cd livebuild

lb config --binary-images iso-hybrid --mode debian --architectures amd64 i386 --linux-flavours amd64 --distribution bookworm --parent-archive-areas "main contrib non-free non-free-firmware" --updates true --security true --cache true --apt-recommends true --firmware-binary true --firmware-chroot true --debian-installer live --debian-installer-gui true --win32-loader false --iso-application gluz --iso-preparer OSLUZ --iso-publisher https://osluz.unizar.es --iso-volume gluz_3.2 --image-name "gluz-xfce.iso" --bootappend-live "boot=live components hostname=gluz-host locales=es_ES.UTF-8 keyboard-layouts=es,es"

echo task-xfce-desktop > $WKDIR/livebuild/config/package-lists/desktop.list.chroot

echo haveged ca-certificates less gdebi galculator grsync psensor synaptic gparted bleachbit flac faad faac mjpegtools x265 x264 mpg321 ffmpeg streamripper sox mencoder dvdauthor twolame lame asunder aisleriot gnome-mahjongg gnome-chess dosbox libxvidcore4 vlc obs-studio soundconverter hplip-gui cdrdao frei0r-plugins htop jfsutils xfsprogs ntfs-3g cdtool mtools gthumb gimp testdisk numix-gtk-theme greybird-gtk-theme breeze-icon-theme breeze-gtk-theme xorriso cdrskin p7zip-full p7zip-rar keepassx hardinfo inxi gnome-disk-utility simplescreenrecorder thunderbird chromium simple-scan remmina arc-theme gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good gnome-system-tools dos2unix dialog papirus-icon-theme transmission-gtk handbrake handbrake-cli audacity rar unrar cifs-utils gvfs-fuse gvfs-backends gvfs pciutils squashfs-tools syslinux syslinux-common dosfstools isolinux live-build fakeroot linux-headers-amd64 lsb-release menu build-essential dkms curl wget iftop apt-transport-https dirmngr nvidia-detect openvpn network-manager-openvpn openvpn-systemd-resolved libqt5opengl5 zulumount-gui zulucrypt-gui zulupolkit neofetch xscreensaver gnome-nettool guvcview libreoffice-l10n-es libreoffice-help-es firefox-esr-l10n-es-es thunderbird-l10n-es-es vlc-l10n chromium-l10n shotcut telegram-desktop openssh-server openssh-client dolphin dolphin-dev konsole ark thunderbolt-tools module-assistant flameshot kate default-jdk default-jre nvidia-openjdk-8-jre icedtea-netx firmware-linux firmware-linux-nonfree firmware-misc-nonfree > $WKDIR/livebuild/config/package-lists/packages.list.chroot

echo grub-common grub2-common grub-pc-bin efibootmgr grub-efi-amd64 grub-efi-amd64-bin grub-efi-amd64-signed grub-efi-ia32-bin libefiboot1 libefivar1 mokutil shim-helpers-amd64-signed shim-signed-common shim-unsigned  > $WKDIR/livebuild/config/package-lists/grubuefi.list.binary

echo dmidecode usbutils irqbalance hdparm lshw parted busybox-static cpio cron apparmor iptables telnet openssh-client tcpdump iputils-tracepath friendly-recovery ftp lsof strace ltrace psmisc systemd-sysv bash-completion command-not-found manpages man-db mlocate nano uuid-runtime plymouth kpartx rename dnsutils rsync ufw file mime-support info libpam-systemd logrotate time b43-fwcutter dpkg-dev g++ patch pptp-linux setserial fwupdate virtualbox-guest-additions-iso gcc make linux-headers-amd64 git software-properties-common ca-certificates ca-certificates-java printer-driver-all openjdk-17-jre icedtea-netx fonts-freefont-ttf fonts-freefont-otf ffmpeg libavcodec-extra gstreamer1.0-pulseaudio vorbis-tools gstreamer1.0-libav clamav clamav-daemon clamtk libnss3-tools > $WKDIR/livebuild/config/package-lists/my.list.chroot

echo firmware-b43-installer firmware-b43legacy-installer  > $WKDIR/livebuild/config/package-lists/wifidrivers.list.chroot

echo calamares calamares-settings-debian > $WKDIR/livebuild/config/package-lists/calamares.list.chroot

mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/livebuild
mkdir -p $WKDIR/livebuild/config/includes.chroot/etc/skel/.config
mkdir -p $WKDIR/livebuild/config/includes.chroot/etc/skel/.local
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/images/desktop-base
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/icons/default
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/local/bin
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/applications
mkdir -p $WKDIR/livebuild/config/hooks/normal
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/doc/livebuild
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/doc/driverimpresorasharp
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/doc/guestAdditions
mkdir -p $WKDIR/livebuild/config/includes.chroot/etc/skel/Desktop
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/active-theme/wallpaper/contents/images
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/homeworld-theme/wallpaper/contents/images
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/plymouth/themes/homeworld
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/homeworld-theme/login
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/plymouth/themes/futureprototype
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/plymouth/themes/lines
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/plymouth/themes/moonlight
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/plymouth/themes/softwaves
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/active-theme/grub
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/live/build/bootloaders/grub-pc
mkdir -p $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/homeworld-theme/grub/
mkdir -p $WKDIR/livebuild/config/includes.chroot/etc/xdg/xfce4/
mkdir -p $WKDIR/livebuild/config/includes.chroot/etc/guest

mkdir -p $WKDIR/livebuild/config/includes.chroot/etc/calamares/branding

cp -r $WKDIR/gluz3 $WKDIR/livebuild/config/includes.chroot/usr/share/livebuild/gluz3
cp -r $WKDIR/gluz3/bootloaders $WKDIR/livebuild/config/
cp -r $WKDIR/gluz3/xfce4 $WKDIR/livebuild/config/includes.chroot/etc/skel/.config/xfce4
cp -r $WKDIR/gluz3/share $WKDIR/livebuild/config/includes.chroot/etc/skel/.local/share
cp -r $WKDIR/gluz3/dolphin/* $WKDIR/livebuild/config/includes.chroot/etc/xdg/xfce4/
cp -r $WKDIR/gluz3/hooks/* $WKDIR/livebuild/config/hooks/normal/
cp $WKDIR/gluz3/scripts/guestadditions.sh $WKDIR/livebuild/config/includes.chroot/usr/local/bin/
cp -r $WKDIR/gluz3/doc/* $WKDIR/livebuild/config/includes.chroot/usr/share/doc/livebuild/
cp -a $WKDIR/gluz3/sharp/* $WKDIR/livebuild/config/includes.chroot/usr/share/doc/driverimpresorasharp/
cp -ar $WKDIR/gluz3/guestAdditions/* $WKDIR/livebuild/config/includes.chroot/usr/share/doc/guestAdditions/
cp -r $WKDIR/gluz3/backgrounds/* $WKDIR/livebuild/config/includes.chroot/usr/share/images/desktop-base/
cp -r $WKDIR/gluz3/icons/* $WKDIR/livebuild/config/includes.chroot/usr/share/icons/default/

cp -r $WKDIR/gluz3/instalador/* $WKDIR/livebuild/config/includes.installer/preseed.cfg

ln -s /usr/share/doc/livebuild $WKDIR/livebuild/config/includes.chroot/etc/skel/Desktop/informacion
ln -s /usr/share/doc/driverimpresorasharp $WKDIR/livebuild/config/includes.chroot/etc/skel/Desktop/
#ln -s /usr/share/doc/guestAdditions $WKDIR/livebuild/config/includes.chroot/etc/skel/Desktop/
cp -r $WKDIR/gluz3/backgrounds2/* $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/active-theme/wallpaper/contents/images/
cp -r $WKDIR/gluz3/backgrounds2/* $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/homeworld-theme/wallpaper/contents/images
cp $WKDIR/gluz3/backgrounds2/logogluz264.png $WKDIR/livebuild/config/includes.chroot/usr/share/plymouth/themes/homeworld/debian.png
cp $WKDIR/gluz3/backgrounds2/logogluz264.png $WKDIR/livebuild/config/includes.chroot/usr/share/plymouth/themes/futureprototype/debian.png
cp $WKDIR/gluz3/backgrounds2/logogluz264.png $WKDIR/livebuild/config/includes.chroot/usr/share/plymouth/themes/lines/debian.png
cp $WKDIR/gluz3/backgrounds2/logogluz264.png $WKDIR/livebuild/config/includes.chroot/usr/share/plymouth/themes/moonlight/debian.png
cp $WKDIR/gluz3/backgrounds2/logogluz264.png $WKDIR/livebuild/config/includes.chroot/usr/share/plymouth/themes/softwaves/debian.png
cp $WKDIR/gluz3/backgrounds2/gluz_640x480.jpg $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/homeworld-theme/grub/grub-4x3.png
cp $WKDIR/gluz3/backgrounds2/gluz1920x1080.jpg $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/homeworld-theme/grub/grub-16x9.png
cp $WKDIR/gluz3/backgrounds2/splashgluz640x480.png $WKDIR/livebuild/config/includes.chroot/usr/share/live/build/bootloaders/grub-pc/splash.png
cp $WKDIR/gluz3/backgrounds2/2620x1474.svg $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/homeworld-theme/login/background.svg
cp $WKDIR/gluz3/backgrounds2/2620x1474.svg $WKDIR/livebuild/config/includes.chroot/usr/share/desktop-base/homeworld-theme/login/background-nologo.svg
cp -r $WKDIR/gluz3/hooks/guest_6.1.0/* $WKDIR/livebuild/config/includes.chroot/etc/guest

cp $WKDIR/gluz3/navegador/defaults.list $WKDIR/livebuild/config/includes.chroot/usr/share/applications/defaults.list

cp $WKDIR/gluz3/calamares/settings.conf $WKDIR/livebuild/config/includes.chroot/etc/calamares/settings.conf
cp $WKDIR/gluz3/calamares/usr/share/applications/install-debian.desktop $WKDIR/livebuild/config/includes.chroot/usr/share/applications/install-debian.desktop
cp -r $WKDIR/gluz3/calamares/branding/gluz $WKDIR/livebuild/config/includes.chroot/etc/calamares/branding/gluz

cp -r $WKDIR/gluz3/guestAdditionsDeb/* $WKDIR/livebuild/config/packages.chroot/
cp -r $WKDIR/gluz3/guestAdditionsDeb/* $WKDIR/livebuild/config/packages.binary/
#cp -r $WKDIR/gluz3/Kernel/linux-5.18.1/* $WKDIR/livebuild/config/packages.chroot/

lb build #>> /home/gluz/gluz_crearISO/iso.log 

mv $WKDIR/livebuild/gluz-xfce.iso-amd64.hybrid.iso $WKDIR/gluz-xfce.iso
rm -r $WKDIR/livebuild

**SCREENSHOTS**
_This is the process of installation_
![imagen](https://github.com/calamares/calamares/assets/167294761/135eafbb-a663-406b-ae64-82c3960e2385)
![imagen](https://github.com/calamares/calamares/assets/167294761/2e1b69e8-020a-47b0-99f2-142eeff354c1)
![imagen](https://github.com/calamares/calamares/assets/167294761/61e00156-9aed-4215-80d6-d0f3f28d96fa)
![imagen](https://github.com/calamares/calamares/assets/167294761/c3dbb1aa-9362-4ef5-87b8-7d52db1ff522)
![imagen](https://github.com/calamares/calamares/assets/167294761/6edaf9dc-9ddf-49c3-9256-3cf56624cbc4)
![imagen](https://github.com/calamares/calamares/assets/167294761/6b1505c9-250b-4528-887b-174e12cf98c5)
![imagen](https://github.com/calamares/calamares/assets/167294761/18484542-a927-4fe3-b37a-c0b88545c884)
![imagen](https://github.com/calamares/calamares/assets/167294761/37401359-bfd7-4291-a909-e12dd7bafc07)

_Error_
![imagen](https://github.com/calamares/calamares/assets/167294761/7a064ef3-6794-4d4a-a3aa-e6370c1ff575)

Thank you all for your help!

**Comment by adriaandegroot** [comment]
That is very extensive. It'd be even nicer to have a link to (preliminary) ISO images, because that means we can test it "live". Error 100 from `apt` can mean many things, but basically what is happening is "run this command in the almost-installed-target-system" and then that command fails somehow. Maybe because a package isn't installed in the target (and therefore can't be purged).

The extensive logs are in `~/.cache/calamares/session.log` of the user that Calamares runs as. Sometimes that is root, sometimes that is a live user (to figure out what `~/` means).

**Comment by gbvunzar** [comment]
> That is very extensive. It'd be even nicer to have a link to (preliminary) ISO images, because that means we can test it "live". Error 100 from `apt` can mean many things, but basically what is happening is "run this command in the almost-installed-target-system" and then that command fails somehow. Maybe because a package isn't installed in the target (and therefore can't be purged).
> 
> The extensive logs are in `~/.cache/calamares/session.log` of the user that Calamares runs as. Sometimes that is root, sometimes that is a live user (to figure out what `~/` means).

Thank you for your response, I can attach a link to my iso, here it is. 

https://www.justbeamit.com/ii8av

**Comment by ezsit55** [comment]
This appears to be someone using my EznixOS project to build a Debian respin. The error code 100 points to a possible problem with https use in the sources.list and the need for the package: apt-transport-https. I do not notice the package: apt-transport-https in the list of packages to be included in your build. This should solve your problem.

**Comment by demmm** [comment]
Closing as explained in last comment.
