### ISSUE TITLE
"Automatic merge of Transifex translations" has not worked since Mar 4

### ISSUE THREAD

**Issue by utuhiro78** [calamares/calamares#2328]
"Automatic merge of Transifex translations" has not worked since [Mar 4](https://github.com/calamares/calamares/commits/calamares/lang).
Most translations have not been updated since [Feb 24](https://github.com/calamares/calamares/tree/calamares/lang).
Please merge the latest translations.

**Comment by utuhiro78** [comment]
I found many translators had not updated translations since Mar 4,
but Assamese (as)/Japanese (ja)/Portuguese (Brazil) (pt_BR)/Chinese (China) (zh_CN) have been [updated](https://app.transifex.com/calamares/calamares/languages/).

**Comment by adriaandegroot** [comment]
The commit message is "automatic" but it is a manual process, running `ci/txpull.sh`. It usually happens before a release.
