### ISSUE TITLE
JobQueue.cpp:19:10: fatal error: QApplication: No such file or directory

### ISSUE THREAD

**Issue by es20490446e** [calamares/calamares#2329]
When I try to compile with:
```
cmake \
	-S "${source}" \
	-G Ninja \
	-DCMAKE_BUILD_TYPE="Release" \
	-DCMAKE_INSTALL_PREFIX="/usr" \
	-DCMAKE_INSTALL_LIBDIR='lib' \
	-DWITH_QT6=ON \
	-DINSTALL_CONFIG=ON \
	-DBUILD_TESTING=OFF \
	-WfPIC \
	-Wno-dev
```

I get the error in the title.

But if in such file I change the line:
`#include <QApplication>`

For:
`#include <QtWidgets/QApplication>`

The error is gone.

**Comment by demmm** [comment]
What version of Calamares is this about?

**Comment by es20490446e** [comment]
3.3.5

**Comment by es20490446e** [comment]
3.3.6

**Comment by demmm** [comment]
That line is removed in git https://github.com/calamares/calamares/commit/cca2cd32604e8d003812c2be20e6b8fffe4d08b0
No release with it yet.

**Comment by es20490446e** [comment]
👌
