### ISSUE TITLE
Error, /dev must be mounted first

### ISSUE THREAD

**Issue by mdhishamsayed** [calamares/calamares#2332]
**Describe the bug**
Whenever I try to install via the latest release, it says mkinitcpio fails because /dev is not mounted, is it not supposed to mount it?, i didn't notice this issue in 3.2.62, which was the last release
**To Reproduce**
1. Download ISO Image
2. Go Through Installation Process
3. Wait Until you see the error

**Expected behavior**
/dev must be mounted by default, so that mkinitcpio may make initramfs

**Screenshots and Logs**
[session.log](https://github.com/calamares/calamares/files/15307817/session.log)

**Additional context**
This issue might be specific to my distro, since i built the package from aur
BTW, Thanks for Responding 😀

**Comment by dalto8** [comment]
You are using config from 3.2 with Calamares 3.3.  Several config files changed layouts.  Most notably in your case, `mount.conf `and `fstab.conf`.  

You need to update your config to match.  That is why `/dev` is failing to mount.

**Comment by mdhishamsayed** [comment]
@dalto8 Hope you're having a good day, can i ask you which modules have been changed so that i can update accordingly

**Comment by dalto8** [comment]
Off the top of my head, there are the changes to fstab.conf and mount.conf plus #1438.  Those are the ones which typically trip people up.

3.3 was in development for a long time though so I may have missed something.

**Comment by mdhishamsayed** [comment]
@dalto8 Thanks Man, Have A Nice Day 😀
