### ISSUE TITLE
OS: KDE NEON PLASMA 6

### ISSUE THREAD

**Issue by ZkyRPT** [calamares/calamares#2334]
We are sorry, Calamares closed unexpectedly.
The reporting assistant is disabled because the crash handler dialog was started in safe mode.
You can manually report this bug to https://github.com/calamares/ calamares/issues (including the backtrace from the Developer Information tab.)
Details:
Executable: _neon PID: 2644 Signal: Aborted (6) Time: 21 May 2024

I keep getting this error while running the kde installer i rebooted remaked the image is still stuck here
![IMG_1657](https://github.com/calamares/calamares/assets/154022385/3950dd10-d7dc-471d-a3ff-4c849d1fe3b9)

**Comment by demmm** [comment]
Is this a report from an end user?  If so, best contact Neon first, they know best if a found issue is Neon specific or a Calamares upstream issue:
https://calamares.io/issues/#end-users
If this is a report from a Neon developer, please add the needed logs, used settings, used layout as asked for in the issue template & https://calamares.io/issues  https://calamares.io/issues/#developers-of-distributions

**Comment by adriaandegroot** [comment]
@jriddell can you take a look?

@ZkyRPT as demmm has already pointed out, we need more information.

**Comment by demmm** [comment]
Closing, since no further response from submitter.
