### ISSUE TITLE
displaymanager using daemon.conf instead of custom.conf in current GDM

### ISSUE THREAD

**Issue by Lt-Henry** [calamares/calamares#2335]
Title is self-descriptive but... displaymanager module is looking for /etc/gdm3/daemon.conf (ie: setting autologin) instead of /etc/gdm3/custom.conf. 

This is happening on Ubuntu 24.04 with gdm 46.0

**Comment by Lt-Henry** [comment]
I think it should work, but to be honest, I am not familiar with Gnome evolution recently and I have no clue where they decided to change that. Gnome docs refer to custom.conf. 

I can workaround this with a symlink to gdm -> gdm3, until someone with deeper gnome knowledge can confirm us the proper way to fix this.

**Comment by Lt-Henry** [comment]
It looks like Manjaro is using /usr/sbin/gdm and /etc/gdm/custom.conf for gdm 46.0 where ubuntu uses /usr/sbin/gdm3 and /etc/gdm3/custom.conf. To make things more complicated :D

**Comment by Lt-Henry** [comment]
> It looks like both Arch and Fedora use `/etc/gdm`
> 
> EDIT: Looking at the code, that seems fine, there is a separate codepath for distros which have `gdm3`

No it is not, there is a missing codepath for /etc/gdm3/custom.conf. Now Calamares write the config at /etc/gdm3/daemon.conf

**Comment by dalto8** [comment]
I wasn't implying we don't need to make changes to fix this.

I was pointing out that it is fine that some distros use `/etc/gdm3` and others use `/etc/gdm` because the code already accommodates that.

**Comment by demmm** [comment]
> I think it should work, but to be honest, I am not familiar with Gnome evolution recently and I have no clue where they decided to change that. Gnome docs refer to custom.conf.
> 
> I can workaround this with a symlink to gdm -> gdm3, until someone with deeper gnome knowledge can confirm us the proper way to fix this.

No need to workaround (or even recompile Calamares to test), just add one line in Live mode to the file linked above, line 382 add `( "gdm3", "etc/gdm3/custom.conf" )` and run Calamares again, if that fixes either report here or open a PR with the needed change.

**Comment by dalto8** [comment]
You can't just add a row there.  It is matching on the binary name which is the same with a different config.  It will match whichever one is first.

**Comment by Lt-Henry** [comment]
Wouldn't be a solution an override path in settings? Something like this:
- gdm
  - settings: "etc/gdm3/foo.conf"

**Comment by adriaandegroot** [comment]
I made the search-for-things look for both config-files and the executables, so it can now find the specific mix @Lt-Henry is interested in.
