### ISSUE TITLE
Policy for schema change and runtime validation

### ISSUE THREAD

**Issue by SuibianP** [calamares/calamares#2336]
**Is your feature request related to a problem? Please describe.**

In the `mount` module, the `options` config was [changed from a string to an array](https://github.com/calamares/calamares/pull/1865), and interprets `bind` as `['b', 'i', 'n', 'd']` [here](https://github.com/calamares/calamares/blob/48554cf310273455507de11d2a2db0ac0eec63a7/src/modules/mount/main.py#L90), which caused bugs like https://github.com/NixOS/calamares-nixos-extensions/pull/32.

**Describe the solution you'd like**

- #1552 - Runtime validation of schema
- Clarify the policy for schema changes
    Should configs
    - Be forward compatible?
    - Not necessarily be forward compatible but must not be interpreted differently across versions?
    - Give no compatibility guarantee across version?

**Describe alternatives you've considered**

Ideally it should be up to maintainers to keep track of all upstream schema changes and rectify discrepancies before bumping calamares version, but it is good for calamares to be forward compatible or at least fail early instead of silently misinterpreting the config.

**Comment by dalto8** [comment]
I agree that there should be run-time validations for the schemas of python modules.

As for compatibility.  We generally try to ensure that compatibility is maintained within a given series but not across significant releases like 3.2 to 3.3.  These are not frequent however.  3.2 was released in 2018 and 3.3 in 2023.

**Comment by adriaandegroot** [comment]
Closing as I don't think there is anything more to do than answer the question (feel free to PR an improvement to documentation somewhere, though, or expand the tests / validation tool).
