### ISSUE TITLE
Partition recognition problem.

### ISSUE THREAD

**Issue by Squalthor** [calamares/calamares#2337]
Good morning,
When installing Manjaro via Calamares I had a problem with the partitions, Calamares did not use the requested partitions, instead it used and deleted the two partitions of my other system, erasing it Thus.

I used manual partitioning, I should have suspected a problem in the order of display of the partitions:

/dev/nvmen0p3
/dev/nvmen0p4
/dev/nvmen0p1
/dev/nvmen0p2

I had chosen /dev/nvmen0p3 (Manjaro bootfs), /dev/nvmen0p4 (manjaro rootfs) but it used /dev/nvmen0p1 and /dev/nemen0p2. He made a mistake in the partition.

I only had this problem Under manjaro, Linux-Aarhus asked me to send you a bug report.

Kind regards, Skwal

**Comment by dalto8** [comment]
There isn't really enough information here to help you.

At the very least we would need to see the install logs.

**Comment by dalto8** [comment]
Closing due to lack of follow-up
