### ISSUE TITLE
Add BTRFS automatic partitioning option 

### ISSUE THREAD

**Issue by souchikjoardar201** [calamares/calamares#2338]
It would be great if there was an option to select creating a recovery partition like a `BTRFS` partition with reasonable automatic sizing that could also be adjusted in the GUI.

Also with to make it available when having *Full Disk Encryption* option selected.

This would be a great addition for new and advanced linux users alike as having snapshot options saves time and headache if but more likely when a user breaks a configuration etc.

This also might help bring more people to Linux if there was a recovery backup option (like Windows RE) in the GUI installer that creates a `BTRFS` partition for snapshots.

**Comment by dalto8** [comment]
Can you explain how you expect this would work?  You want to add a separate partition for btrfs snapshots?  What would the snapshots be of and how would they get to this other partition?

**Comment by dalto8** [comment]
Closing due to lack of follow-up.
