### ISSUE TITLE
Include Support for MATE Desktop

### ISSUE THREAD

**Issue by blue-devil-93** [calamares/calamares#2339]
**Is your feature request related to a problem? Please describe.**
The current Mate installer requires snap to be installed, while technically ubuntu mate 24.04 does not require snaps to run. As the current subiquity installer uses flutter framework, the overhead of using qt wirh calamares is even smaller, considering that calamares can even be forced tonuse gtk2 themes as it is a pure qt application.

**Describe the solution you'd like**
A  fork of the lubuntu config to be able to install mate with calamares.

**Describe alternatives you've considered**
Using ubiqquity, but as this software is EOL its better to use the customizable calamares.

**Additional context**

The unpackfs file can be changed to the following:

---
unpack:
    -   source: "/cdrom/casper/minimal.squashfs"
        sourcefs: "squashfs"
        destination: ""
    -   source: "/cdrom/casper/minimal.standard.squashfs"
        sourcefs: "squashfs"
        destination: ""
    -   source: "/cdrom/casper/minimal.standard.live.squashfs"
        sourcefs: "squashfs"
        destination: ""

**Comment by kkofler** [comment]
Please take this up with Lubuntu. Providing installer images with Calamares is something the downstream distribution (so Lubuntu in your case) has to do, not Calamares upstream.

**Comment by kkofler** [comment]
Just to clarify my previous comment, the downstream to contact here is [Ubuntu MATE](https://ubuntu-mate.org/), though the Lubuntu folks who have already been shipping Calamares for a while might be willing to help.
