### ISSUE TITLE
Calamares fails to install on external drive

### ISSUE THREAD

**Issue by Taddaeus** [calamares/calamares#2342]
So far I have been able to install Kubuntu directly onto an external hard disk, encrypted or unencrypted, without any issues. With the new "Calamares" installer this is no longer possible, it always ends with an error message during partitioning. Is this a missing feature, a bug... or an Apple-like "feature"? Anyway, please restore this function - for Linux this should be a matter of course.

Thanks in advance.

**Comment by dalto8** [comment]
If you are an end-user, you should report this issue to kubuntu instead.

If you are a distro maintainer, you would need to provide the full logs from the failure.

**Comment by adriaandegroot** [comment]
At the very least, Kubuntu version -- preferably a download link -- and Calamares version. See https://calamares.io/issues/ for more information. Right now there's nothing we can even try.
