### ISSUE TITLE
[with solution proposal] This storage device already has an operating system on it, but the partition table vmd is different from the needed msdos or gpt

### ISSUE THREAD

**Issue by qmastery16** [calamares/calamares#2344]
Good day! So I've decided to re-test the ["InstallationWithFullDiskEncryption"](https://wiki.artixlinux.org/Main/InstallationWithFullDiskEncryption) manual - but this time using a fresh weekly ISO of [Artix Linux](https://artixlinux.org/) _(user-friendly arch without SystemD)_ with a **Calamares 3.3.6** instead of an older stable Artix ISO with Calamares 3.2.62.  Everything was going well like usual: I set up the encrypted LVM volume using a custom encryption method _(the primary goal of this instruction, because Calamares still does not let any user customization in this life-important regard)_ and launched a Calamares; however, a couple of steps later I've been unpleasantly surprised with this screen:

![calamares_3 3 6](https://github.com/calamares/calamares/assets/24974135/cabaeddd-7062-4252-a6a8-6eee8d359008)

> This storage device already has an operating system on it, but the partition table **vmd** is different from the needed **msdos or gpt**.

As you see, because of "m_somethingElseButton->hide();" at ./calamares/src/modules/partition/gui/ChoicePage.cpp or some change at default Calamares configuration, I am blocked from manual partition choices inside of this encrypted LVM volume - while with an older ISO everything was working fine... By launching the calamares with -D8 flag, I got a more extended message:

> WARNING: Partition table "vmd" does not match the requirement  "msdos,gpt" , ENABLING erase feature and DISABLING alongside, replace and manual features.

I am not sure if something got changed in the recent version of Calamares, or this is a matter of configuration change by the Artix maintainers - but still getting blocked for no good reason is quite discouraging, and I don't even understand why such blocking is needed at all.

**Solution Proposals:**
1) partition.conf mentions for "requiredPartitionTableType" that - if nothing is specified, Calamares defaults to both "msdos" and "gpt". Please add "vmd" to this default "requiredPartitionTableType" list to join them
2) change the Calamares behaviour in this "unknownTableType" situation to "m_somethingElseButton->show()", otherwise the freedom of user for a manual action is being infringed for no good reason

**Comment by adriaandegroot** [comment]
Although the documentation in the example configuration file doesn't mention it -- didn't, because I expanded that documentation a little today -- you can fill in other partition types that KPMcore recognizes. So for your distro experiments, you can add *vmd* to the list by editing the config file, and then report whether that works. This is largely a distro-decision, too: the distro will have to support *vmd*-based installs through whatever.

**Comment by qmastery16** [comment]
@adriaandegroot Thank you, I have found two possible solutions - open the
```
 nano /etc/calamares/modules/partition.conf
 nano /etc/calamares-offline/modules/partition.conf
 nano /etc/calamares-online/modules/partition.conf
```
and either add the "- vmd" line to the end of "requiredPartitionTableType" block:
 ```
requiredPartitionTableType:
     - msdos
     - gpt
     - vmd
```
or remove this block entirely - before launching a Calamares of course
