### ISSUE TITLE
Remove the "requiredPartitionTableType" anti-feature

### ISSUE THREAD

**Issue by qmastery16** [calamares/calamares#2346]
See https://github.com/calamares/calamares/issues/2344 - this "requiredPartitionTableType" does not do any good, it only prevents the people from manually installing their desired distro like Artix _(arch without SystemD)_ to whatever kind of partition they want. While I found two solutions for forcing my way, I do not understand the purpose behind this "gatekeeping" anti-feature and would like to see it removed to prevent the user frustration

**Comment by dalto8** [comment]
Please don't open duplicate issues.

Data validation isn't a "gatekeeping anti-feature".  It is a minimum expectation of any properly written code.

**Comment by qmastery16** [comment]
@dalto8 if the partition type is known to be supported - like vmd - then there is no reason to block the installation there
