### ISSUE TITLE
Calamares puts 'none' instead of '/crypto_keyfile.bin' into 'crypttab password-field'

### ISSUE THREAD

**Issue by Rockets31** [calamares/calamares#2356]
**Describe the bug**
Calamares 3.3.8 puts 'none' instead of '/crypto_keyfile.bin' into 'crypttab password-field' while "full-disk-encryption" over manual partitioning. Last 'debian-testing-kde-live-iso' (I think 15.07.24): 64-bit, EFI, root is btrfs inside luks1 container via manual partitioning.

Installer sets fields 1,2,4 correct, but nr. 3 'none' instead of '/crypto_keyfile.bin' -> after reboot root-volume won't open: /bin/cat tells luks-container some silent stuff => 'bad password options..."
Tried extracting initramfs & correcting crypttab -> I gave up... I did a arch-chroot (fast & convenient...) => system boots as expectetd.

**To Reproduce**

1. Install with calamares as `full-disk-encryption' just used btrfs -> root is on subvolume '/@'
2. Reboot after Calamares finished
3. See error: 'Bad password options...'

**Expected behavior**

Calamares puts '/crypto_keyfile.bin' in crypttab password-field => regular boot

**Screenshots and Logs**
[Calamares_debian-testing_session.log](https://github.com/user-attachments/files/16325184/Calamares_debian-testing_session.log)

**Additional context**
I read, there were some things changed for "unencrypted-boot' & '/crypto_keyfile.bin', so I think upstream is correct place.

**Comment by dalto8** [comment]
For that to work correctly, the `fstab` module needs to be after `luksbootkeyfile` in settings.conf.

There is an open PR(https://github.com/calamares/calamares/pull/2354) to change that in the default config.  That being said, it will really need to be changed by the distro.

**Comment by Rockets31** [comment]
👍👍👍 Nobody could expect a faster solution... As I understand, before that modification distros did not need to care about the sequence.

**Comment by dalto8** [comment]
> As I understand, before that modification distros did not need to care about the sequence.

Yes, that is correct.
