### ISSUE TITLE
error: module "users@users" exists but not loaded

### ISSUE THREAD

**Issue by xjlsigmaboy** [calamares/calamares#2361]
I'm making my distro with archiso, I built calamares and a binary calamares configuration pkg and It's working. When I login to kde Calamares says that It can't load users@users module. I tried starting from terminal to see the output and It prints errors. (Output : [here](https://imgur.com/a/WtXTDxR). How can I fix it.

**Comment by dalto8** [comment]
That means that your ISO has different library versions than Calamares was built against.  It looks like you built a new ISO and then installed Calamares from a repo.  Likely you need to rebuild Calamares.

If you call Calamares with `calamares -D8` you will see full debug output and the error would be more obvious.  It is likely that your ISO has a newer version of `icu` than Calamares was built against.
