### ISSUE TITLE
Arch kde latest netlink kernel issue

### ISSUE THREAD

**Issue by claudemods** [calamares/calamares#2363]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

LINUX-ZEN LATEST

**Describe the bug**
A clear and concise description of what the bug is. Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.
crashes the application upon entry

open calamares and crash 

**To Reproduce**
2. use your brain open calamares the normal way or enter in konsole sudo calamares
3. Click on '....'
4. Scroll down to '....'
5. See error
![Screenshot_archlinux_2024-08-31_18:51:25](https://github.com/user-attachments/assets/ae00dc54-f171-43c6-8e3b-620837d7c29e)
![Screenshot_archlinux_2024-08-31_18:51:16](https://github.com/user-attachments/assets/877b082c-2e8a-45f5-b603-a7108c394fb9)

just update to latest arch kernel and you be met with your fears
**Expected behavior**

what does any one expect calamares todo when it opens ha
**Screenshots and Logs**

If applicable, add screenshots to help explain your problem. Calamares has an installation log (usually `~/.cache/calamares/session.log`), please check it for confidential information and attach it if possible.

**Additional context**
i didnt make calamares so im not a calamares expert but i can read error messages and try to troubleshoot issues and from what ive read it says its a kernel issue

**Comment by claudemods** [comment]
[session.log](https://github.com/user-attachments/files/16825473/session.log)
here is some more details

**Comment by dalto8** [comment]
Please take the time to fill out the template with all the requested details.

**Comment by claudemods** [comment]
i cannot give a description to something so basic ive provided logs it doesnt take scientist to realise its arch kde latest packages and kernel ive been build distros now nearly 2 years

**Comment by dalto8** [comment]
There is literally a template in the issue that describes exactly what we expect.  It is actually embedded in your report above.  Take the time to replace that with the information we are requesting.

You haven't even reported which kernel you are using or what the hardware configuration you are running on is.

**Comment by claudemods** [comment]
> There is literally a template in the issue that describes exactly what we expect. It is actually embedded in your report above. Take the time to replace that with the information we are requesting.
> 
> You haven't even reported which kernel you are using or what the hardware configuration you are running on is.

just updated some bits im not just sure what else you need text wise

**Comment by dalto8** [comment]
Well, if you are too busy to provide the information, there isn't much we can do to help.

Closing due to insufficient information.

**Comment by claudemods** [comment]
> Well, if you are too busy to provide the information, there isn't much we can do to help.
> 
> Closing due to insufficient information.

im asking you what you need me to give i gave you the info and how i encountered the issue why are you being so rude who said im busy today

**Comment by claudemods** [comment]
> Well, if you are too busy to provide the information, there isn't much we can do to help.
> 
> Closing due to insufficient information.

rude

**Comment by claudemods** [comment]
ive narrowed it down to kpmcore i blocked the package from updating and it works fine

**Comment by claudemods** [comment]
> Well, if you are too busy to provide the information, there isn't much we can do to help.
> 
> Closing due to insufficient information.

ive narrowed it down to kpmcore i blocked the package from updating and it works fine

**Comment by claudemods** [comment]
![Screenshot_archlinux_2024-08-31_21:48:19](https://github.com/user-attachments/assets/009a6510-0136-49af-a517-628812c4c518)
![Screenshot_archlinux_2024-08-31_21:48:36](https://github.com/user-attachments/assets/65d66192-71ba-431a-93a8-c91e34760bd0)
i hope you can fix please known im not against you and id rather make things better than argue

**Comment by dalto8** [comment]
Did you rebuild your Calamares against the newer kpmcore?  Make sure you aren't using an older prebuilt Calamares.

**Comment by claudemods** [comment]
> Did you rebuild your Calamares against the newer kpmcore? Make sure you aren't using an older prebuilt Calamares.

ill be honest i tried to build it and had issues i can try again but im not to clued of the procedure hence why i failed last time

**Comment by demmm** [comment]
https://github.com/calamares/calamares/issues/2367 is most probably related, so please continue there, and add any and all relevant info you may have, since this bug is effecting a lot of distributions.

**Comment by claudemods** [comment]
> #2367 is most probably related, so please continue there, and add any and all relevant info you may have, since this bug is effecting a lot of distributions.
Thats been Fixed sorry ill build calamares from source from now ive now reported a problrm to archinstall huge issue could be the end of arch without being fixed
