### ISSUE TITLE
Summary screen has a few minor text issues

### ISSUE THREAD

**Issue by highvoltage** [calamares/calamares#2364]
![calamares-summary](https://github.com/user-attachments/assets/821937b5-f652-4435-ae50-382bae378438)

Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1080189

A user has reported two minor issues on the summary screen in Debian, I've highlighted them in the attach screenshot so that they're easier to find:

1. In the Keyboard section, the newline seems to be there too early, so the period occurs afterwards on the newline before the next line of text.
2. In the Location section, "New_York" contains an underscore where it doesn't in the map selection (not sure if this is intentional or even a bug).

**Comment by adriaandegroot** [comment]
You have eagle-eyed users. Repaired for 3.3.10:

![image](https://github.com/user-attachments/assets/8c997085-c9ea-419e-af5a-f1e34505fa55)
