### ISSUE TITLE
After installation and Calamares restart button it hangs, not properly unmounting installation root?

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#2366]
Hi, this issue is with Calamares 3.3.9 to install a spin of openSUSE Tumbleweed and the Cinnamon desktop.

The openSUSE packages of Calamares have always modified the Calamares `.desktop` file to use `Exec=kdesu -c /usr/bin/calamares` instead of `pkexec` because `pkexec` [doesn't use the proper environment variables](https://bugs.freedesktop.org/show_bug.cgi?id=96713) needed for things like theming support. At any rate, I tried manually running Calamares with `sh -c "pkexec calamares"` and I had the same result:

After a successful installation and clicking the Calamares restart button, it goes to a black screen with a blinking cursor, and later it shows a systemd message about a process running in the live session user account, and then when that finally hits timeout after about 2 minutes the system cleanly shuts down.

I'm wondering if it's due to the fact that `/tmp/calamares-root-*` is still mounted after the installation is finished?

![Screenshot from 2024-09-05 08-19-18](https://github.com/user-attachments/assets/d24d99fe-733d-4131-bf74-c9513483e5f3)

I don't quite understand why that's the case, as I am including the `umount` step in my 
[settings.conf](https://github.com/user-attachments/files/16898572/settings.conf.txt). At any rate, I can make it immediately shutdown if I change the `finished.conf` setting to `restartNowCommand: "reboot -f"`, but I'm concerned about it doing a dirty shutdown with the Calamares installation root still mounted.

I confirmed that the live OS normally shuts down / restarts without abnormal delays.

Here's a complete installation log with debugging enabled: [log.txt](https://github.com/user-attachments/files/16898626/log.txt)

**Comment by adriaandegroot** [comment]
Have you got and ISO that demonstrates this effectively? Presumably the root stays mounted because **something** is running in the chroot, still (sometimes processes get started in there, mostly by accident).

**Comment by dalto8** [comment]
This is a bug actually.  It isn't even trying to unmount the root.

I fixed this and apparently forgot to upstream the fix.  I will do that now.

**Comment by geckolinux** [comment]
Hi @adriaandegroot and @dalto8 , appreciate the reply. Here's an ISO if you still need to test it:
https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_ROLLING_Cinnamon.x86_64-999.240905-BETA.iso/download
