### ISSUE TITLE
Insane password safety checks - need bypass option

### ISSUE THREAD

**Issue by it9exm** [calamares/calamares#2370]
**Describe the bug**
I’m genuinely baffled by the current password safety checks in the installer. Forcing users into specific password requirements without any option to bypass them is downright excessive and borderline paranoid.

There are many cases where users don’t need, want, or care for the password restrictions, especially in secure, personal environments where the users are fully aware of what they’re doing. Not allowing an option to skip or bypass this is just ridiculous. Users should have the flexibility to set their own passwords, even if they don’t meet arbitrary complexity standards.

This is supposed to be a tool for installing the operating system, not a nanny. Please consider implementing a bypass option in the password check, because this restriction is frustrating and unnecessary.

Looking forward to some sanity in future releases.

**To Reproduce**
Go through install wizard;
Type a one-character password;
Next button is grayed out.

**Expected behavior**
Go through install wizard;
Type a one-character password;
Next button clickable;
prompt user to continue anyway

**Comment by dalto8** [comment]
Calamares does not require password restrictions.  It is up to the distro to choose if there are restrictions or not.

You probably need to address this with the distro you are observing this behavior in.

**Comment by it9exm** [comment]
Thank you for clarifying.
I made sure to also bring this to the attention of the debian team as well. 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082020
Sorry for the misunderstanding. I guess we can close this.
