### ISSUE TITLE
LANG env not set with selected locale

### ISSUE THREAD

**Issue by SixK** [calamares/calamares#2371]
When Calamares set grub.cfg in bootloader module, 
it seem's that $LANG variable is not set with selected locale.

chroot take LANG from host env.
In my case, I run Calamares with a custom Ubuntu 24.04 cdrom iso using default $LANG that is "LANG=C.UTF-8".
As the result, grub-mkconfig don't set lang section (and locale) in grub.cfg

To set grub.cfg content, grub-mkconfig use "/etc/grub.d/00-header" file containing this snippets:
```
grub_lang=`echo $LANG | cut -d . -f 1`
# Gettext variables and module
if [ "x${LANG}" != "xC" ] &&  [ "x${LANG}" != "x" ]; then
  cat << EOF
  set locale_dir=\$prefix/locale
  set lang=${grub_lang}
  insmod gettext
EOF
fi
```

Final result is that grub is not using selected language and show a "IE" keyboard (Ireland instead of "FR" in my case),
when unlocking partitions at boot. 
That may be confusing even if unlock partition is using right keyboard layout.

Is there a quick way to fix this behavior using any calamares or calamares modules .cfg files ?
Would it be a good idea to change env LANG value on the host side when language is selected by user in calamares ?
Would it be a good idea to do something like check_target_env_call(["env", f"LANG={libcalamares.globalstorage.value('localeConf.LANG')}",libcalamares.job.configuration["grubMkconfig"], "-o", output_file]) ?
Is there something better to do ?

**Comment by demmm** [comment]
What version of Calamares is this referring to? (please fill out all asked for info when submitting)

**Comment by SixK** [comment]
Calamares base version I use is 3.3.5

**Comment by SixK** [comment]
Found in documentation here https://github.com/calamares/calamares/blob/calamares/src/modules/README.md#running-commands-in-python

``` 
    target_env_call(command, stdin, timeout) returns the exit code, does not raise.
    check_target_env_call(command, stdin, timeout) raises on a non-zero exit code.
    check_target_env_output(command, stdin, timeout) returns a single string with the output of command, raises on a non-zero exit code.

All of the API functions for running commands set the environment LC_ALL and LANG to "C" for the called command.```

This mean that `check_target_env_call([libcalamares.job.configuration["grubMkconfig"], "-o", output_file])` from https://github.com/calamares/calamares/blob/calamares/src/modules/bootloader/main.py
can't set grub locales and add lang lines in grub.cfg

**Comment by SixK** [comment]
I did a test forcing LANG=fr_FR.UTF-8 before running calamares 
and now grub.cfg have lang lines and locales are generated.

This means documentation is not right, LANG is not set to "C" when running check_target_env_call().
This confirm chroot and check_target_env_call() take host env parameters.

So to have a grub.cfg set with locales, we need to force LANG on host (but LANG env may not be be available in processes or subprocess). 
Or we need to add LANG=xxxx before each grub command.

**Comment by SixK** [comment]
A quick fix, I simply added in localecfg module:
os.environ["LANG"]=locale_conf["LANG"]

like this:
```
def run():
    """ Create locale """
    import libcalamares

    locale_conf = libcalamares.globalstorage.value("localeConf")

    if not locale_conf:
        locale_conf = {
            'LANG': 'en_US.UTF-8',
            'LC_NUMERIC': 'en_US.UTF-8',
            ...... cutted dict ....
        }
    os.environ["LANG"]=locale_conf["LANG"]
```

**Comment by SixK** [comment]
Canceled this PR, it seem's my problem is not related to lang variable in grub.cfg.
I need to investigate more.

**Comment by SixK** [comment]
OK, finally found my problem.
I had wrong keyboard layout cause plymouth added more keyboards in the keymap-render.png file.
Pb is related to this issue: https://bugs.launchpad.net/ubuntu/+source/lubuntu-artwork/+bug/2063895

Closing the issue.
