### ISSUE TITLE
If systemd-inhibit is present, use it to stop the system from sleeping/locking while calamares is open

### ISSUE THREAD

**Issue by Justinzobel** [calamares/calamares#2384]
**Is your feature request related to a problem? Please describe.**
Devices can go to sleep while the installer is open and running, this can cause partial installs and wasted time.

**Describe the solution you'd like**
Detect if systemd-inhibit is present and use it to prevent the device going to sleep, shutting down or locking during the installation process.

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.freedesktop.org/software/systemd/man/latest/systemd-inhibit.html for reference

Example: `systemd-inhibit --what=sleep:shutdown --mode=block --who="Calamares Installer" --why="Installation in progress" calamares`

**Comment by erikdubois** [comment]
great idea for plasma

When I leave my machine unattended during installation kde will go to sleep.
Waking up Plasma will result in a crash and I can do the installation again and make sure it does not go to sleep

**Comment by killajoe** [comment]
By disable the options to sleep all together.

**Comment by Justinzobel** [comment]
Yes, so this would stop the device from sleeping, shutting down while calamares is open. Once calamares closes, it can resume normal operations.

**Comment by Valeria-Fadeeva** [comment]
> great idea for plasma
> 
> When I leave my machine unattended during installation plasma will go to sleep. Waking up Plasma will result in a crash and I can do the installation again and make sure it does not go to sleep
> 
> other distro's with Plasma must experience the same thing
> 
> How do other distros overcome this?

The liveuser profile (https://git.melawy.ru/Core/melawy-skel-liveuser) is installed on LiveISO, the installed system will have other settings (https://git.melawy.ru/Core/melawy-etc-skel-std-powerman-kvantum) + modifying logind.conf (https://git.melawy.ru/Installer/melawy-archiso-config/src/branch/main/Melawy-Linux-Base-System/airootfs/etc/systemd/logind.conf) to ignore button presses.

**Comment by jpetso** [comment]
The same inhibit functionality is also available in the [login1 D-Bus interface](https://www.freedesktop.org/software/systemd/man/latest/org.freedesktop.login1.html) on the system bus, which might fit better with what Calamares is already [trying to do with org.freedesktop.PowerManagement.Inhibit](https://github.com/calamares/calamares/blob/4cd1f0f40299e37e5ba1041142b923f2575232dd/src/libcalamares/JobQueue.cpp#L125) on the session bus but fails at least when running as root in the KDE neon live session.
