### ISSUE TITLE
Install error: No such file or directory: '/tmp/calamares-root-zzj6p_tb/boot/refind_linux.conf'

### ISSUE THREAD

**Issue by alsemenov** [calamares/calamares#2396]
I downloaded cachyos-desktop-linux-241003.iso and tried to install. I selected manual disk partitioning, rEFInd boot manager, created 2048MiB partition for boot and reused existing 100MiB /boot/efi partition from Windows 11.
The installation proceeds normally, but at the very end I get the error "No such file or directory: '/tmp/calamares-root-zzj6p_tb/boot/refind_linux.conf'". Full log https://termbin.com/96bk

**Comment by ptr1337** [comment]
Please close this issue here, this is not related to normal calamares.
