### ISSUE TITLE
Message telling calamares do not support python modules

### ISSUE THREAD

**Issue by nintyfan** [calamares/calamares#2403]
**Describe the bug**
I build Calamares, but without Python modules support. Some modules do not go to ${build}/src/modules/. I copy modules from src/modules, but Calamares complain this version do not support python modules.

How to select modules to build? How to force python support? Sorry for asking, maybe trivial question, but cannot find any information.

**To Reproduce**
Ran ./deploycala.py . Some modules are inside ${build}/src/modules. Copying python modules do not made it supported.

**Expected behavior**
Only to enhance documentation with info why python modules are not supported, or how to enable support of it. Also, clarify how to select modules to build.

**Comment by demmm** [comment]
Issues are for reporting bugs or feature request, they are not a help channel:
https://calamares.io/issues/
https://calamares.io/issues/#developers-of-distributions
Make sure to read the documentation:
https://github.com/calamares/calamares/blob/calamares/src/modules/README.md
https://github.com/calamares/calamares/wiki/Deploy-Configuration
See the section how to skip modules to build:
https://github.com/calamares/calamares/wiki/Develop-Guide#build

If you have questions left after reading the docs, join the Matrix channel  for support.

**Comment by adriaandegroot** [comment]
- all modules build unless you use `SKIP_MODULES` to skip them
- .. unless there are missing dependencies, in which case it will say something about missing dependencies
- look in the configure log (output of CMake) early on to see what it's doing when trying to find Python
- by default, only Python libraries and development headers are needed; check that you have these installed
- if you pick Boost.python as the Python support implementation, you will need that as well.

`deploycala.py` is a best-effort tool, and not actively maintained (the scripts `ci/deps-`*something* are more up-to-date now).
