### ISSUE TITLE
A SEGV may occur when collecting boot loader information.

### ISSUE THREAD

**Issue by phoepsilonix** [calamares/calamares#2405]
A SEGV may occur when collecting boot loader information.

    14:33:33 [2]: WARNING (Qt): beginResetModel called on BootLoaderModel(0x5555565c5b70) without calling endResetModel first
    14:33:33 [2]: WARNING (Qt): endResetModel called on BootLoaderModel(0x5555565c5b70) without calling beginResetModel first
    14:33:33 [2]: WARNING (Qt): beginResetModel called on BootLoaderModel(0x5555565c5b70) without calling endResetModel first
    14:33:33 [2]: WARNING (Qt): endResetModel called on BootLoaderModel(0x5555565c5b70) without calling beginResetModel first
    
    Thread 1 "calamares" received signal SIGSEGV, Segmentation fault.
    0x00007ffff60c8b65 in ?? () from /usr/lib/libQt6Gui.so.6

**Describe the bug**
When updating boot loader information or partition information, multiple threads are started, and SEGV occurs in some cases. From the log, it can be inferred that mutex is not working properly.

**To Reproduce**
1. sudo gdb --args calamares -D8 -T --debug
2. catch signal SIGSEGV
3. run
4. next and next and next...
5. Select Manual partitioning and click next
6. After the screen changes, a dialog box will appear and the partition information will be scanned.
7. SEGV may occur

**Expected behavior**
After collecting partition information, no SEGV occurs and a list of partition information is displayed.

**Screenshots and Logs**
    14:33:33 [2]: WARNING (Qt): beginResetModel called on BootLoaderModel(0x5555565c5b70) without calling endResetModel first
    14:33:33 [2]: WARNING (Qt): endResetModel called on BootLoaderModel(0x5555565c5b70) without calling beginResetModel first
    14:33:33 [2]: WARNING (Qt): beginResetModel called on BootLoaderModel(0x5555565c5b70) without calling endResetModel first
    14:33:33 [2]: WARNING (Qt): endResetModel called on BootLoaderModel(0x5555565c5b70) without calling beginResetModel first
    
    Thread 1 "calamares" received signal SIGSEGV, Segmentation fault.
    0x00007ffff60c8b65 in ?? () from /usr/lib/libQt6Gui.so.6

**Additional context**
I have observed this occur with some frequency when a Chrome OS (brunch) partition is present on /dev/sdc.

**Comment by phoepsilonix** [comment]
2. If the installer crashes during manual partitioning.  
try selecting "Coexistence with other OS" or "Replace partition" before choosing manual partitioning. By selecting "Coexistence with other OS" or "Replace partition" first, you can complete the collection of partition information.
After that, selecting manual partitioning will make it easier to avoid crashes.

**Comment by phoepsilonix** [comment]
#2407 
When you select manual partitioning and click Next, after the screen changes, a partition information scan is performed, and then a SEGV may occur.
To prevent this, I added a process to scan the partition information when you select manual partitioning in the menu, just like when you select other menus.

**Comment by adriaandegroot** [comment]
Proposed fix merged just now.
