### ISSUE TITLE
The source filesystem "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs" does not exist

### ISSUE THREAD

**Issue by helwan-linux** [calamares/calamares#2408]
Hello Sir , 
I am building my own arch based distro using archiso I put everything togother 
and everything went well , but every time I try to install the distro after I choose 
EFI partion and root partion then hit next , Calamares brings this error and 
the installing process stops :

The source filesystem "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs" does not exist

I am not experienced enough to handle this error , so please help me to pass this error
why it pop up and how to fix it , thanks in foreword

**Comment by erikdubois** [comment]
Give more info - this seems exactly like the post on our forum.
Can we see your data on github or gitlab?

**Comment by erikdubois** [comment]
How do you build your ISO?

**Comment by helwan-linux** [comment]
> How do you build your ISO?

sudo mkarchiso -v "."

**Comment by erikdubois** [comment]
After building the ISO you doubleclick on it
it gets mounted
see if /run/archiso/bootmnt/arch/x86_64/airootfs.sfs exists

**Comment by helwan-linux** [comment]
> After building the ISO you doubleclick on it it gets mounted see if /run/archiso/bootmnt/arch/x86_64/airootfs.sfs exists

it ain't exists

**Comment by erikdubois** [comment]
so now you know your issue

**Comment by erikdubois** [comment]
I can only give you three ways to learn how to build an ISO with calamares.
I think that is enough. Start from one of those.
1. Arcolinux
2. Alci
3. Carli

There are no shortcuts - you need to learn a lot in order to create your own ISO.
https://www.arcolinuxiso.com/a-comprehensive-guide-to-iso-building/

**Comment by erikdubois** [comment]
your airoofts.sfs exists in /arch/x86-64 and that is where it should be

![image](https://github.com/user-attachments/assets/e3b2be08-76c7-4b7e-b7b8-b4dcd143c026)

**Comment by erikdubois** [comment]
Unable to boot up your ISO

![image](https://github.com/user-attachments/assets/fb1ceeba-be2d-4c63-859c-4da08b771c0e)

Here my help stops. Study up I would say. Do not get discouraged.

**Comment by demmm** [comment]
As posted often, issues are not a help channel, they are for bug reports or feature requests:
https://calamares.io/issues/
https://calamares.io/issues/#developers-of-distributions
Closing, since this is a help request, if you should need further assistance, please use the Matrix channel.

**Comment by erikdubois** [comment]
I should have started with that ;-)
