### ISSUE TITLE
 libpython3.12.so

### ISSUE THREAD

**Issue by helwan-linux** [calamares/calamares#2418]
I don't know if it is the right place or not but every time I try to start Calamares it gives ::
 
calamares 3.3.12: error while loading shared libraries: libpython3.12.so.1.0: cannot open shared object file: no such file or directory , I am on arch linux with python 3.13.1-1

**Comment by demmm** [comment]
See https://github.com/calamares/calamares/issues/2417
You need to rebuild Calamares.
