### ISSUE TITLE
CAL-103: Set User Information on first Boot

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#291]
Jira issue originally created by user @teo:

drakx installer ask for the username and password after the first boot, so it is possible the install the OS and let the user set up his log-in details, when he/she is ready for it.

Thats nice for each case, where a admin have to setup the OS and the user is away in this moment.
This makes it also possible, to install the OS and send the disk by post to the user.
(So long as each GPU/WLAN drivers stay installed, which is another issue report)

Thanks a lot in advance, Matthias.

**Comment by adriaandegroot** [comment]
Track it in the much-more-recent #762
