### ISSUE TITLE
CAL-130: geoip based auto language keyboard and time default configuration - able to change -

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#321]
Jira issue originally created by user @teo:

I would suggest the use of geoip to select default language instalation (or offer the 2 main at bilingual locations), keyboard layout, time zone, and laguage settings, and of course being able to select other if you want.

**Comment by adriaandegroot** [comment]
I'm closing this one as "but we have that already". You can enable geoip, and in the timezone selection widget you can also modify language and such. I don't think that picking a language for the installed system based on geoip is a good idea -- let's stick with the installer language or explicit selection for that.
