### ISSUE TITLE
CAL-131: GPT as default and migrate MBR disks to GPT keeping partitions as option

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#322]
Jira issue originally created by user @teo:

Calamares should detect if the target disk is GPT capable and suggest as default the more modern GPT and if one disk is MBR and is able to switch to GPT offer to switch it and keep the partitions that it would have

**Comment by demmm** [comment]
This feature request is now well over 8 years old, never a PR submitted for it, time to close.

**Comment by mirh** [comment]
That's not really how feature requests should work. 
On the other hand e8264a4503c88bdd565df7d81712e6b975ba9687 seems to have been it. 

If any, even though I definitively agree with the last comment, I guess like you could still ask for conversion to GPT when the user selects the erase/automatic procedure.

**Comment by demmm** [comment]
Clean-up is done to see which requests are still wanted/needed. No-one is benefiting from letting issues pile up up, never to be touched.  And as noted, this request has some form of implementation already.
