### ISSUE TITLE
Automatic set needed flags on GPT installations

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#400]
Jira issue originally created by user philm:

On EFI-based installations EFI system partitions requires a boot flag (boot, esp) to work properly. We are currently doing that within **bootloader* module. *partition** module should normally take care of that.

Also GRUB requires a BIOS Boot Partition (2 MiB, no filesystem, "EF02" type code in gdisk or "bios_grub" flag in GNU Parted) in BIOS systems to embed its core.img file due to lack of post-MBR embed gap in GPT disks.

Some users might not been aware of that fact. We can add a feature to **partition** module to do that automatically, if needed ...

Take a look at **create_bios_gpt_boot_partition()** function from [thus](https://github.com/manjaro/thus/blob/master/src/installation/advanced.py)

**Comment by abucodonosor** [comment]
@stikonas 

is this now possible from KPM ?

**Comment by stikonas** [comment]
Strange, I think it was always possible. You just need to add SetPartFlagsOperation. It's the same API as calling any other operation like partition resize, etc...

**Comment by demmm** [comment]
AFAIK, this was implemented with the rebase to kpmcore (late 2015?).

**Comment by kkofler** [comment]
I implemented the EFI case in commit 5377003f891e5bae382d79a96bacda8f878aaddd on 2016-10-29, replacing the previous workaround that was calling the `sfdisk` executable from Python code. I don't think we support BIOS boot partitions at this time.

**Comment by adriaandegroot** [comment]
Closing this one: GPT (+EFI, or +BIOS) works and is bootable (tested with Manjaro).
