### ISSUE TITLE
CAL-202: Create correct GPT setup in BIOS systems

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#401]
Jira issue originally created by user demmm:

There seems to be quite a bit of confusion/misunderstanding of how to set up GPT correctly for BIOS systems.  Instead of keeping the required info scattered all over different comments and discussions, a command line walk through will follow here.  It uses the interactive cgdisk.  For scripting, it is better replaced with sgdisk.
gptfdisk is needed to be installed.  To set the needed bios_grub flag, parted is needed.

Setup on /dev/sda, 8Gb example drive:
```# cgdisk /dev/sda```

If no GPT partition table available yet, cgdisk will create one, so hit enter on the warning messages, as in the example below:

```
# cgdisk /dev/sda
Warning! Non-GPT or damaged disk detected! This program will attempt to
convert to GPT form or repair damage to GPT data structures, but may not
succeed. Use gdisk or another disk repair tool if you have a damaged GPT
disk. Press any key to continue....
Next view:
cgdisk 0.8.0
Disk Drive: /dev/sda
Size: 15654912, 7.5 GiB
Part. # Size Partition Type Partition Name
----------------------------------------------------------------
1 7.5 GiB Microsoft basic data Microsoft basic data
[ Align ] [ Backup ] [ Delete ] [ Help ] [ Info ] [ Load ]
[ naMe ] [ Quit ] [ Type ] [ Verify ] [ Write ]
Change the filesystem type code GUID
```

Select "delete", if any similar partition shows. Once your disk shows as "free-space", create the first partition as unallocated space, 8Mb minimum:

```
First sector (40-15654878, default = 40): 
Size in sectors or {KMGTP} (default = 15654839): 8Mb
Current type is ef02 (Linux filesystem)
Hex code or GUID (L to show codes, Enter = 8300): ef02
Current partition name is
```

Enter new partition name, or to use the current name:
```BIOS boot```

This example created an 8Mb efi boot partition Next select remaining free space, and that will become a 7.4Gb root partition, for an ext4 filesystem:

```
First sector (4194344-15654878, default = 4194344): 
Size in sectors or {KMGTP} (default = 15654839): 7400Mb
Current type is 8300 (Linux filesystem)
Hex code or GUID (L to show codes, Enter = 8300): 
Current partition name is
```

Enter new partition name, or to use the current name:
```Root```

The partitions are setup at this point, so next select "write", and type "yes" to make the changes permanent. Then select "quit" to leave cgdisk. This only setup partitions, no file systems created yet, so back in the normal console, create an ext4 filesystem for the root partition (sda2 in this example):

```# mkfs.ext4 /dev/sda2```

Make sure that the first partition is completely empty:

```# dd if=/dev/zero of=/dev/sda1 bs=4M```

And last, the 8Mb unallocated space on sda1, needs the bios_grub boot flags set:

```# parted /dev/sda set 1 bios_grub on```

As of this writing partitionmanager is not capable of creating an unformatted partition, so any attempt to set this or assign a bios_grub flag in GUI will fail

**Comment by abucodonosor** [comment]
#720 , #459
