### ISSUE TITLE
CAL-206: Add KEYMAP in /etc/vconsole.conf

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#405]
Jira issue originally created by user TPG:

Looks like calamares does not set up /etc/vconsole.conf properly.
KEYMAP entry is missing as based on user localization.

Without KEYMAP set in /etc/vconsole.conf user in VT may have different key layout than in X11.

More information can be found here:
https://issues.openmandriva.org/show_bug.cgi?id=1140

**Comment by demmm** [comment]
As reported, fixed https://issues.openmandriva.org/show_bug.cgi?id=1140#c19

**Comment by kkofler** [comment]
Huh? We still don't write `KEYMAP` anywhere. I think there must be some distro-specific workaround being used there, or a different default behavior of `systemd-localed`.
