### ISSUE TITLE
CAL-209: Unable to handle encrypted Logical Volumes

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#408]
Jira issue originally created by user philm:

User schamane reported followed issue in our forums:

Even with running `sudo calamares -d` I couldn't start the graphical installer.
But then I think I found it: it seems calamares doesn't like encrypted Logical Volumes present. After removing them, it works.

However I'm unable to create a 'msdos' partition table with my current setup. See attachment.

**Comment by adriaandegroot** [comment]
Crash is solved, LVM support is in other issue numbers.
