### ISSUE TITLE
CAL-214: Keyboard layout for tty one is not set correctly

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#414]
Jira issue originally created by user leszek:

Choosing language english and keyboard layout german ends up with an installation that uses german as keyboard layout for X11 though the tty ends up with an english keyboard layout. 

It seems like /etc/vconsole.conf  is ignored. 
Running localectl shows
VCC set correctly to de-latin1-nodeadkeys &
X11 Keyboard set to us instead of de. 

Running localectl set-keymap de-latin1-nodeadkeys 
fixes the problem and sets the correct keymap for tty and x11. 

Maybe it makes sense to use localectl --set-keymap instead of directly writing to the configs

**Comment by demmm** [comment]
Closing as fixed & duplicate of https://github.com/calamares/calamares/issues/405
