### ISSUE TITLE
Allow user to choose default desktop

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#426]
Jira issue originally created by user TPG:

Allow user to choose default desktop after the installation, based on desktop files found in /usr/share/{xsessions,wayland-sessions} and defined directories on config file.

**Comment by abucodonosor** [comment]
@adriaandegroot 

this should go to OEM mode I think ?

**Comment by kkofler** [comment]
This is relevant regardless of whether the installation is a normal or OEM installation. Live images can also contain more than one desktop environment.

**Comment by abucodonosor** [comment]
Ok but then displaymanager code need go to a GUI option too ,
so one can choose what DM to use also..

**Comment by adriaandegroot** [comment]
![Screenshot_20190801_144203](https://user-images.githubusercontent.com/19431457/62295173-c7056d00-b46c-11e9-8bbc-fd64e0f635c0.png)

This is how you might do it with the plain netinstall module, but it looks terrible and is error-prone (choose just one of the sub-boxes, and it shows package names, not something human-readable).

**Comment by kkofler** [comment]
Well, it could be done like this:
```
[ ] Office Suite                 CHOOSE ONE
 +--[x] LibreOffice              LibreOffice suite (recommended)
 |   +--[x] libreoffice
 |
 +--[ ] OpenOffice               Apache OpenOffice suite
 |   +--[ ] openoffice
 |
 +--[ ] Calligra                 KDE Calligra office suite
     +--[ ] calligra
```
The single-package groups add the descriptions and make it easy to add extra packages such as `libreoffice-l10n` if wanted or needed. And you can also preselect (`selected: true`) the recommended option by default so that just clicking through will not leave the user with no office suite.

**Comment by adriaandegroot** [comment]
![Screenshot_20190801_214935](https://user-images.githubusercontent.com/19431457/62322979-904c4880-b4a6-11e9-9707-74748758a9e6.png)

With more data in the netinstall file, you could also render it like this (this is from a quickly-hacked-together QML-based thing; having spent an hour with it I'm inclined to do it in widgets like everything else in Calamares). This is a much more shiny way of presenting the same thing, although it will only work for a small(er) number of groups and items within each group.

**Comment by kkofler** [comment]
I prefer the text-based tree view (as currently implemented): more scalable (to larger numbers of items and to deeper hierarchies), more room for descriptions. We could optionally put small icons between the checkboxes and the names, but I don't think the Windows-3.1-style icon view look (as in your mockup) is a good idea.

**Comment by kkofler** [comment]
And another technical reason why the icons are problematic is that it is not obvious how to provide them for not yet installed applications (and you wouldn't want to netinstall applications that are already installed on the live image anyway). Hotlinking them from the upstream sites is likely not desirable, and uploading them all next to the netinstall.conf is logistically non-trivial (and then you probably have to upload some license files next to them, etc.).

**Comment by adriaandegroot** [comment]
So I've left netinstall alone -- @kkofler is right that that's good for high-density package choices. Some distro's might want a version with more flexibility, for low-density choices (e.g. Manjaro's pick-an-office-suite) where the visuals are more important. There is a new *packagechooser* module for that, which needs support from some **other** module to turn the decision into something that can be installed.
