### ISSUE TITLE
Better guessing for hostname

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#432]
Jira issue originally created by user @teo:

see ubiquity/misc.py method dmimodel

**Comment by abucodonosor** [comment]
What is this about ?

I guess host OS is meant here ?

**Comment by kkofler** [comment]
The referenced method is this:
https://github.com/linuxmint/ubiquity/blob/18e22dbd75e384c698e8e1f9c53fd49a613fca6e/ubiquity/misc.py#L599
but it does not really compute a host name, but a model name. Maybe the idea was to build a default host name from that, I'm not sure. @teo?

**Comment by teo** [comment]
To clarify: this is about building a nicer hostname based on things like manufacturer name etc. Strings can be gathered from dmidecode or /sys/devices/virtual/dmi/id/product_name and related.
It was never a high priority thing, indeed more like a "note to self" that this might be nice some time in the future.

**Comment by stappersg** [comment]
2017-09-19, previous update,  until 2019-10-17, this update, were almost 25 months of silence.

What is the point of having this _"note to self"_  public visible?   (Please close the issue)

**Comment by abucodonosor** [comment]
@adriaandegroot 

maybe something like this?

https://gitweb.frugalware.org/frugalware-current/raw/master/source/installer-extra/calamares-frugalware/0001-Try-to-guess-suggested-hostname-from-dmi.patch

**Comment by adriaandegroot** [comment]
Applied patch from @abucodonosor in 7c323bdcdc1f87ac831b26f64be0b0b56adfe87a
