### ISSUE TITLE
CAL-235: Expose pretty module descriptions in Install step, instead of "Run script..."

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#437]
Jira issue originally created by user @teo:

**Comment by adriaandegroot** [comment]
This was already done.

**Comment by adriaandegroot** [comment]
Applies to python modules, which still say *Running <modulename> operation ...". Reopen and leave lying around for the big Python re-think.

**Comment by adriaandegroot** [comment]
The python modules (regular, not PythonQt) are translated and there is a not-yet-documented approach to calling gettext from within them.
