### ISSUE TITLE
GPT table on BIOS system fails in grub install

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#459]
Jira issue originally created by user @teo:

Using GPT in a BIOS system needs an unformatted space at the beginning of the disc.
Trying to install without that partition, or with 32 Mb set as unformatted, results in failed grub job.
https://gist.github.com/demmm/19eac0e5e7b04b9a9cfa
There needs to be an option to set the bios_grub boot flag in the unformatted partition
https://www.gnu.org/software/parted/manual/html_node/set.html

**Comment by demmm** [comment]
For manual partitioning this bug report can be closed.  All works now for adding the unformatted space and setting the needed bios_grub flag.
Not sure if this needs to stay open for automated GPT installs on BIOS system.

**Comment by abucodonosor** [comment]
sort #720

**Comment by adriaandegroot** [comment]
Looks like grub has improved; the default settings work fine for GPT on BIOS (just tested in Manjaro).
