### ISSUE TITLE
CAL-261: Store the configuration if installer aborts due to internal error

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#466]
Jira issue originally created by user bshah:

In case installation aborts due to some modules or other error, save progress and configured values somewhere so when user restarts Calamares they don't have to re-enter everything again.

**Comment by hubslave** [comment]
This is especially annoying when it fails at the final stages (e.g. grub-mkconfig) - have to go though all configuration again.
An alternative approach could be to implement "Back" button to rerun the previous stage(s) again.

**Comment by demmm** [comment]
This feature request is now well over 7 years old, never any PR submitted for it, time to close.
