### ISSUE TITLE
CAL-267: QBasicTimer can only be used with threads started with QThread

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#472]
Jira issue originally created by user philm:

After closing Calamares throws following Warnings/Errors:

{quote}09:47:05 [8]: Shutting down Calamares... 
09:47:05 [8]: Finished shutdown. 
09:47:05 [0]: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
09:47:05 [0]: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
09:47:07 [0]: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
09:47:07 [0]: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
09:47:07 [0]: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
09:47:07 [0]: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
09:47:07 [0]: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
09:47:07 [0]: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
09:47:07 [0]: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
09:47:07 [0]: QBasicTimer::start: QBasicTimer can only be used with threads started with QThread{quote}

**Comment by adriaandegroot** [comment]
I've squashed at least one of these. Basically, auto-deletion of QObjects through their parents relies on delete-later, which uses a QTimer, .. I've chosen to leak memory instead, since it is after-shutdown.
