### ISSUE TITLE
"After Install" Snapshot when using btrfs

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#483]
Jira issue originally created by user @teo:

It would be a real benefit for the user who installs on an btrfs filesystem to have an "After Install" or "Initial Configuration" snapshot that gets an entry in grub. 
This allows the user whenever he wants to boot into the initial state of his system after the installation and is a good alternative to "safe mode" boot options in disaster cases. 

This should be optional as a checkbox when choosing btrfs. (maybe activated by default as it only brings benefits for the majority of users)

**Comment by adriaandegroot** [comment]
For distro's using btrfs, this can be done with a *contextualprocess* module checking for FS type; for a UI, you could use *packagechooser* with a suitable configuration (probably *packagechooserq*, for more UI flexibility).
