### ISSUE TITLE
CAL-353: Add translator contributors to an About page

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#503]
Jira issue originally created by user jobava:

It would be nice to have translator's name in a list somewhere in the Calamares interface, perhaps in an "About" page somewhere. Is this workable?

**Comment by adriaandegroot** [comment]
Would be poilite for translators, yes .. but since we're using Transifex as the source of the translations, do we even have that information?

**Comment by adriaandegroot** [comment]
no, we do not have that information. It is quite difficult even in the Transifex web interface to find out who is translating in any particular language, and without real names (e.g. what we have in KDE i18n) I don't think we should put a bunch of user-handles in the interface.
