### ISSUE TITLE
CAL-364: Use definied filesystem as first option in manual partitioning

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#515]
Jira issue originally created by user TPG:

Hi,

in case of manual partitioning, and ext2 is proposed as first on the list.
Would be nice to use as a first option value based on config set in here:
https://github.com/calamares/calamares/blob/master/src/modules/fstab/fstab.conf#L4

**Comment by adriaandegroot** [comment]
Picking something from a different module's config does not make much sense. But the partition module already has a setting for default FS. I don't know if manual partitioning uses it as default.

For Hacktoberfest:
 - check if the default set in `partition.conf` applies to manual partitioning
 - if so, document it as such
 - if not, make it so and see above

**Comment by stikonas** [comment]
Manual partitioning uses
defaultFileSystemType:  "ext4"
from partition.conf. So ext2 is not default anymore.

gui/CreatePartitionDialog.cpp in partitioning module construct default file system using this value.

**Comment by adriaandegroot** [comment]
Closed with b3723371c811cfc032ffea877bb8e190e8d12df3 / PR 838
