### ISSUE TITLE
CAL-367: It probably doesn't prevent itself from setting KEYMAP in /etc/vconsole.conf to a missing keymap.

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#518]
Jira issue originally created by user crocket:

I installed manjaro xfce 15.12 with korean as the locale.
KEYMAP in /etc/vconsole.conf was set to `ko`, but `localectl list-keymaps` didn't contain `ko`. Thus, systemd-vconsole-setup.service failed during boot. I had to manually set KEYMAP to an empty string and rebuild initramfs to fix the error.

Is it an issue of calamares or some other software?

**Comment by abucodonosor** [comment]
@philmmanjaro 

is this still a bug on manjaro ?

**Comment by philmmanjaro** [comment]
@abucodonosor: I have to check that ...

**Comment by abucodonosor** [comment]
downstream bug , closing
