### ISSUE TITLE
CAL-368: QtWebEngine use will crash Calamares with Nouveau drivers

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#519]
Jira issue originally created by user demmm:

The webview module has now the option to either use QtWebkit or QtWebEngine (Qt 5.6 is needed for the latter option).
Using QtWebengine in this module will crash Calamares as soon as any scrolling is done and the Nouveau graphics driver is in use.
This is a known issue upstream, sample bug reports of Nouveau not being able to use QtWebEngine:
https://bugs.freedesktop.org/show_bug.cgi?id=91632
https://bugreports.qt.io/browse/QTBUG-41242

This does not effect any other graphics driver, non-free Nvidia for example is not effected.

**Comment by kkofler** [comment]
This is an upstream Nouveau and QtWebEngine issue. There is not much Calamares can do here.
