### ISSUE TITLE
Creating a User / Usermanagement in Calamares

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#526]
Jira issue originally created by user blackcrack:

Hi,

At moment it is 
--------
*only possible
*- for create a user
*- Name
*- Passwort
*- rootpassword
--------
but not
----------------
*but not possible / need to make possible
*- for Create a User with [User]
*- manual UID [1234] and  
*- for Create a UserGroup with [UserGroup]
*- manual GID in form of a number [1234]
*- select a prompt shell ( tcsh, bash, tc, zsh, ksh9, csh and so on) [/bin/bash][<sup>]
*- select a Homedirectory  [/home/blackcrack][</sup>] //(editable for manual typing)
*- [X] Use this userpasswd as Rootpassword //automatic checked by routine if Root have no password and this is the first user (not uncheckable, only if Root become a PW)
*- [X] Able this User as Administrator (SU)

like it should possible.

Maybe it's better to change the whole User Creation in a Listing to be possible to 
create different user-accounts with the possible to have a checkbox 
[X] Use this userpasswd as Rootpassword
[X] Able this User as Administrator (SU)
----------------
===========================================
[Root User Config] (Popup Button)// =>no adjustment, root have no password and become automatic the password from 1st user <sup></sup>

```
// Some comments here
User 1 //<=>Blackfox (usernames listed by Name, for better finding a,b,c)
User 2 //<=>Calacurley
User 3 //<=>Fullchecker
~(a.s.o.)
```
```Create/Add a User``````Edit the User``````Remove a User```
(Popup Buttons)
[X]Enhanced // for easy Configuration or enhancement Configuration for Professionals and server Owners
Headuser Group GID [**1010]  //adjustable by Administrator/InstallUser and in the Distribution can it automatic adjusted by install
===========================================

it is the possible for have a whole pop-up page for Configuring the ROOT and the Users, how many it want (Usergroups, Family and so on) and how extended it want..

Fully enhanced or only User&User password, easy determine with the checkbox
for have the able to install and configuring a Server or Professional Linux System
With users, Administrators and specific users with uid and gid and specific home-folders and prompt shell's.

so, the possible for make it easy (without checking the checkbox or with checking the checkbox) or enhanced and fully custom able Setup for User and Root

best regards
Blacky

**Comment by abucodonosor** [comment]
parts of that seems be done in PR #280

**Comment by benbullard79** [comment]
I agree, I definitely have a need to be able to set UID and GID.

**Comment by Dizirgee** [comment]
I'm not sure if this is right place, but it seemed not worth to create new issue for this as this issue is dealing with user creation...

Installer on user creation page should prohibit to enter "root" as username because if it is chosen than installation fails at the end as "root" user obviously already exists (so useradd cmd fails to add another root user)

I found this on Endeavour and also Manajaro installs.

**Comment by killajoe** [comment]
> I'm not sure if this is right place, but it seemed not worth to create new issue for this as this issue is dealing with user creation...
> 
> Installer on user creation page should prohibit to enter "root" as username because if it is chosen than installation fails at the end as "root" user obviously already exists (so useradd cmd fails to add another root user)
> 
> I found this on Endeavour and also Manajaro installs.

better create a new issue..

**Comment by demmm** [comment]
This feature request is now well over 6 years old, a very old PR was never completed and is not usable, time to close.
