### ISSUE TITLE
Installer does not write input method variables into /etc/locale.conf

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#529]
Jira issue originally created by user yochenhsieh:

There are some variables that should be written into system locale config (in openMandriva it's /etc/locale.conf):
XIM=
GTK*IM*MODULE=
QT*IM*MODULE=
XIM_PROGRAM=
XMODIFIERS=

Missing these variables will cause input method (e.g. ibus,fcitx) unusable after installed. It is needed that a default value should be set for certain specific locales, e.g. CJK.

**Comment by abucodonosor** [comment]
tbh .. none of these should be supported by calamares itself and there are reasons.

When calamares does this based on language detection this can break the 'distro' 
implementatiton. Also for all this to work 'ibus and some more other packages' need
be installed.. we really can't expect calamares to check whatever packages get installed,
what kind IM methode the user wishes and so on..

Also this kind setup of variables is usualy done when 'installing the packages from your distro' ..

**Comment by demmm** [comment]
This feature request is now well over 6 years old, no PR ever submitted, so it is time to close.
