### ISSUE TITLE
Add to Calamares the ability to run in Command Line mode

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#530]
Jira issue originally created by user @teo:

Feature request, imported from GitHub:
I would like to know if there is planed to do a CLI mode for Calamares or if it has been done.
￼
Note:
This idea is on the table, but it's not a short term focus right now. One would probably have to take libcalamares, and then develop a non-interactive mode and/or a ncurses interface on top of it. It is an interesting project, and I'd definitely like to see it done at some point.

**Comment by pieroproietti** [comment]
I'm the author of [penguins-eggs](https://github.com/pieroproietti/penguins-eggs), a remaster system who let you to build or rebuild a personalized iso from your installed system.

eggs use calamares as installer ot the system and take cure to create the configurations files needing for it. What you need to do is just install calamares before the iso production.

eggs is a CLI application, I made it thinking not only to desktop but also to the servers.

So I'm working now to krill, a light CLI installer inside eggs made in typescript, trying to mimics calamares GUI as possible. 

It work actually in an accettable way on Debian, but I have again some problems with ubuntu. 

To be clear, I used more look and feel of calamares than others, just I'm able to run /usr/lib/x86-gnu-linux/calamares modules, read some variables from branding and so on. I'm not able to run python modules and others modules and so on. 

Krill at moment it is just  a working mess, but I think can evolve. 

In particular I'm interested about the possibility to use calamares python modules to improve it. 

That can be a suitable way to use just the pythons module of calamares? 

This is the sea of calamares, but maybe there is room for krill too. Anyone willing and able to collaborate?

Thanx

![krill](https://user-images.githubusercontent.com/958613/122039244-c2cf6800-cdd6-11eb-9ef6-44b15bce2c05.png)
 installed system.

**Comment by kkofler** [comment]
> That can be a suitable way to use just the pythons module of calamares?

Not really, I'm afraid. Some essential modules such as `partition` are and have always been in C++, and the plan is actually to port the remaining essential modules (if not all modules) from Python to C++ (and in fact, some have already been ported over time).

**Comment by pieroproietti** [comment]
OK, thanx kkofler. I thought was possible, but I can again try to take something following - from distant - calamares.

**Comment by demmm** [comment]
This feature request is well over 6 years old, there is no indication Calamares will ever be anything but a GUI installer. Time to close.

**Comment by D3vil0p3r** [comment]
Huge pity. Having Calamares as CLI version too, like `archinstall` CLI, would be too interesting, too much.

**Comment by pieroproietti** [comment]
It has been a long time since my previous post, but not in vain. Currently you can use krill on Arch, of course it does not have the capabilities of calamares, on the other hand it is extremely fast. 

You can try the installation with krill of this lightweight configuration called [colibri](https://sourceforge.net/projects/penguins-eggs/files/ISOS/arch/).

**Comment by adrelanos** [comment]
Any alternatives to calamares to run in command line mode?

**Comment by pieroproietti** [comment]
It's not so great, but penguins-eggs include it's CLI installer named krill
to stay in the theme. Eggs let to remaster systemd and install them with
calamares or krill.

It mimics calamares on TUI, and at the moment erase the installing device.


https://github.com/pieroproietti/penguins-eggs

https://penguins-eggs.net

Il mer 10 gen 2024, 09:52 Patrick Schleizer ***@***.***> ha
scritto:
