### ISSUE TITLE
Ability to preseed user account creation in users module via users.conf

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#534]
Jira issue originally created by user mckinney-subgraph:

The Debian Installer supports the ability to pre-configure much of the install process via the use of a preseed file. The configuration files for Calamares seem to support similar functionality but not all options are pre-configurable. In particular, it does not seem possible to pre-configure user creation with a fixed username, computer name, etc.

The Debian preseed configuration for these variables looks like this:
# To create a normal user account.
d-i passwd/user-fullname string User
d-i passwd/username string user

# Any hostname and domain names assigned from dhcp take precedence over
# values set here. However, setting the values still prevents the questions
# from being shown, even if values come from dhcp.
d-i netcfg/get_hostname string subgraph
d-i netcfg/get_domain string unassigned-domain

At the bare minimum, it would be great if it were possible to set these variables from the `users.conf` file included within the users module. Ideally, it would be great if all variables set by this and other modules were configurable in this way (though that is obviously a much bigger feature request).

**Comment by adriaandegroot** [comment]
Closing this as "superceded by #1654"
