### ISSUE TITLE
CAL-383: Segfault if Calamares launched when USB device is plugged in

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#536]
Jira issue originally created by user shainer:

If I launch Calamares and I have a USB device plugged in, Calamares crashes at startup. The problem is within the device scanning functionality; I will debug more and post more updates if I find something interesting.

This happens both when the device is mounted and when it is not. The backtrace attached has been collected when the device was mounted

**Comment by adriaandegroot** [comment]
Closing due to insufficient information -- also sounds like one of the kpmcore-device-scanning crashes that was fixed around 3.1.
