### ISSUE TITLE
Calamares could display a friendly dialogue instead of crashing when a ntfs error is found.

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#542]
Jira issue originally created by user highvoltage:

See: https://jonathancarter.org/files/temp/calamares-fsckcrash.png

ntfsresize checks a partition before resizing it. If it finds an error, it will exit with a non-zero code. This causes calamares to invoke the crash handler, which isn't particularly friendly or informative for the user.

If Calamares could detect this case, and display a message similar to the following instead, then it would be a lot more friendly to dual booters:
"""
A problem has been detected on your Windows partition, and the installer cannot continue. To fix this, reboot to Windows, perform a filesystem check to fix the error, and restart this installer.
"""

That would make it clearer to the user what they need to do to fix their problem.

**Comment by abucodonosor** [comment]
@stikonas 

something we can do about this in kpmcore ?

**Comment by stikonas** [comment]
Well, kpmcore calls ntfsresize to check for consistency of the file system but I don't think ntfsresize can fix errors. So, maybe the fix should be in calamares?

**Comment by adriaandegroot** [comment]
This one is kind of tricky, though:
- Calamares "just" asks KPMCore to resize a partition,
- KPMCore says "no" (and has an error message from the underlying tool).

I suppose Calamares could look at the error messages and translate them -- or some of them -- and translating to something more meaningful. However, that requires being really familiar with the underlying tools. The relevant code is in `KPMHelpers.cpp`, function `execute()`. I'm going to close this issue, but welcome PRs that examine the output from KPMCore and do that translation.
