### ISSUE TITLE
Request to add a login shell definition

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#548]
Jira issue originally created by user udeved:

I would be very nice to be able to define a login shell for user creation.
It would make it possible to install a system with default zsh for example.

**Comment by abucodonosor** [comment]
that is already done in PR #280..

@adriaandegroot 

is #280 even going to be merged ?

**Comment by adriaandegroot** [comment]
This can be configured at the distro-level, via `users.conf`:

```
userShell: /bin/bash
```

Not selectable at install-time, though. PR #280 no longer merges, so I don't think that **that** form of user-configuration is going to happen soon.
