### ISSUE TITLE
CAL-395: netinstall buttons inverted

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#549]
Jira issue originally created by user oberon:

In the netinstall module widget the arrow buttons, used to display members of package groups appear pressed while not selected and not pressed while selected. See screenshot.

**Comment by adriaandegroot** [comment]
Current netinstall looks (ui-wise) nothing like the screenshots in the referenced commit, uses standard Qt tree, so I'm going to close this issue as "done".
