### ISSUE TITLE
CAL-402: When installing on Btrfs, no subvolumes are created nor added to /etc/fstab

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#558]
Jira issue originally created by user @teo:

It is expected of Calamares to create subvolumes for / and /home, and add them to /etc/fstab.

**Comment by philmmanjaro** [comment]
This is connected to #797 and #796.

**Comment by abucodonosor** [comment]
Someone pleased close ist fixed now

**Comment by philmmanjaro** [comment]
Fixed in current master branch.
