### ISSUE TITLE
CAL-405: LUKS accepts every WRONG password after install 

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#561]
Jira issue originally created by user philm:

Several independed users reported an issue with manual luks encryption in our [bugtracker](https://bugs.manjaro.org/index.php?do=details&task_id=72). They create at least two partitions and at least one is encrypted.

The latest reproducable step-by-step report is this one:

{quote} I reported meaningless passphrase for LUKS emcrypted root filesystem with Calamares installation.
It occured Manjaro 16.08 XFce (x86*64), and it was reproduced on 16.10.1 XFce (x86*64).

[What does]

(16.08)
On hp Z400 workstation with 8disks.
* Choose Language
* Choose Timezone
* Choose Keyboard layout
* Manual Partitioning:
 - 1024MiB ext3 boot
 - 250GiB XFS on LUKS root
* Enter user infomation
* Install

(16.10)
On ASRock FM2A88X+Killer with 2disks, UEFI boot.
* Choose Language
* Choose Timezone
* Choose Keyboard layout
* Manual Partitioning:
 - sda1 : 300MiB FAT32 esp
 - sda2 : 1000MiB ext3 boot
 - sda3 : 110.5GiB ext4 on LUKS root
* Enter user infomation
* Install

[What happened]

Manjaro boots after 14 seconds from hit enter key when input right passphrase.
Manjaro boots after 28 seconds from hit enter key when input wrong (like "abcde") or empty passphrase.
Manjaro boots after long time (at least more of 30 minutes) when input nothing.

It must input right passphrase when access other system.

Regards,
MASAKI Yuhsuke{quote}

We should check if this is a general issue and also reproduceable in other Distros shipping **CAL**.

**Comment by adriaandegroot** [comment]
Those have been fixed.
