### ISSUE TITLE
CAL-406: Any way to reduce KDE Framework dependencies?

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#562]
Jira issue originally created by user sb56637:

**Comment by adriaandegroot** [comment]
KPMCore is here to stay; I'm not *really* happy with all of the Frameworks dependencies it drags in, though, like KIO and KService, but that's really something to fix in the way KPMCore is packaged and/or split up. @stikonas ?

**Comment by stikonas** [comment]
Well, KIO is only used in KPMcore once to get currentMountPoints.
KMountPoint::List mountPoints = KMountPoint::currentMountPoints(KMountPoint::NeedRealDeviceName);
Some custom code could probably be written to avoid this dependency.

KService is used to load backand plugins such as libpartedbackand plugin. At the moment the only other backend is dummy backend with fake devices but that might change at some point. I think there is some lighter plugin mechanism but I'm not too familiar with them, there might be some ideas in early agateu code...

**Comment by demmm** [comment]
As for KIO, afaik it is also needed for the netinstall module.

**Comment by kkofler** [comment]
No, `netinstall` does not use KIO, only QtNetwork (`QNetworkAccessManager`).
