### ISSUE TITLE
 Allow "[  ] Partitions are already created and mounted at /install"

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#563]
Jira issue originally created by user haletom:

There are many advanced partition configuration options which need to happen at install time, but would be a waste of time to try to code into `calamares`.

For example:

* LVM custom setups like thin provisioning
* Customised LUKS setups (eg ciphers, iterations)
* [Multiple subvolumes in btrfs](https://forum.manjaro.org/t/installation-with-precreated-install-folder/11615)
* `btrfs` quotas ([if a subvolume should be part of a qgroup, it has to be added to the qgroup at creation time](https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-quota#INHERITANCE))
* You name it...

To support these and other unimaginable configuration needs with minimal effort, how about creating the ability for a user to tick a box on the "Partitioning" page:

```
[  ] Partitions are already created and mounted at /install (advanced users only)
```

Which would then allow enable the `Next` button to proceed to the next screen?

**Comment by demmm** [comment]
This feature request is now close to 6 years old, no PR ever done for it, time to close.
