### ISSUE TITLE
No check for disk space or error if space is exhausted during installation

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#565]
Jira issue originally created by user haletom:

I just tried installing Manjaro 16.10.1 in to a 5GB root-only setup and all seemed well... until I booted and the tty7 (the X ptty) just had a flashing cursor (no error message there, or in tty1 either).

It took me a while to work out that the / filesystem was 100% full.

1. Check for available space before installing?
2. Let the user know that their installation failed if the disk somehow becomes full anyway

**Comment by abucodonosor** [comment]
@adriaandegroot 

seems to be this issue downstream:

https://bugs.manjaro.org/index.php?do=details&task_id=95

Just not sure we can do something about..

**Comment by philmmanjaro** [comment]
I think we have settled that already. Have to check.

**Comment by adriaandegroot** [comment]
If the filesystem fills up, rsync exits with code 11:

```
rsync: write failed on "/tmp/unpackfs-test-run-rootdir3/smalldest/src/modules/fsresizer/CMakeFiles/fsresizertest.dir/Tests.cpp.o": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]
Job set progress to 90.57086614173228%.
17:26:32 [2]: WARNING: [PYTHON JOB]:  "rsync failed with error code 11." 
```

I'm not sure there's anything left to do, then, for this one: possibly the OP had the error from rsync squashed.
