### ISSUE TITLE
Misaligned partitions in encrypted system install

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#567]
Jira issue originally created by user ciddegh:

I just installed a Manjaro system on a notebook computer using the "Encryt system" option in calamares. (On the partitions page I selected "Erase disk" and then checked "Encrypt system"). 
All works well, only when I had a look at the partition table from the installed system, fdisk shows that the partitions that calamares created are not correctly aligned. Calamares creates two partitions, a Linux partition and a swap partition. The Linux partition starts at sector 2049 (which should usually be 2048) and the swap partition at 959367789 (500 GB disk) which is also not divisible by 4, this should also be one less (or even better should be on a 1M boundary).

I've measured hard disk write performance on this disk (not an SSD) and it doesn't seem to be deteriorated by this, but I am not so sure, how an SSD would like this.

Anyway, I think this is not intended. (Or is it? Haven't found anything about this on the net.)
So it might be a bug - and probably not hard to fix (offset of 1 in the sector calculation somewhere?).

**Comment by abucodonosor** [comment]
@stikonas 

any ideas about that ?

**Comment by stikonas** [comment]
I'm not too sure why this happens.

It would be helpful to know what bool PartitionTable::isSectorBased(const Device& d) const returns for device during installation. But maybe it's not this... That offset 1 looks strange... Could happen if somebody incorrectly replaces [start sector, end sector] with [start sector, start sector + length] but I don't think there is any bug like that in kpmcore.

**Comment by adriaandegroot** [comment]
Feedback timeout.
