### ISSUE TITLE
CAL-414: Calamares crash after switch between "Erase" and "Manual" partitioning

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#570]
Jira issue originally created by user sb56637:

Hi, I'm testing Calamares 2.4.4 on openSUSE Tumbleweed. I got it to crash with an empty Vbox disk. I was presented with "Erase" or "Manual" partitioning. I first selected "Erase", and then switched to "Manual", and after clicking "Next" it crashed. I'm attaching the output.

After restarting a Calamares and only selected manual partitioning I was able to successfully complete an installation.

Thanks!

**Comment by abucodonosor** [comment]
I cannot reproduce that ..

Maybe Not abug anymore in calamres 3.x ?

**Comment by abucodonosor** [comment]
Works for me with calamares 3.x.x
