### ISSUE TITLE
CAL-415: Assert in libparted on Calamares startup

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#571]
Jira issue originally created by user sb56637:

Hi, I noticed this issue while testing the Calamares installer on a spin of openSUSE Leap 42.2 in the SuseStudio TestDrive VNC viewer.

I ran Calamares via `xdg-su`, not `pkexec`, for various reasons. I noticed that the Calamares window just started to open and then disappeared. Since it was VNC I couldn't copy the terminal output, but I'm pasting a screenshot. Basically, it fails at:
`"Need at least storage bytes: 5905580032"`
I have tested this many times in the SuseStudio TestDrive, and it **almost** always fails this way, but once in a while it runs. However, when I `su root` and run `calamares` it always runs correctly with no memory errors. I checked with `free -m` both as a regular user and as root, and the VM has like 1600 MB free + 500 MB of free swap. So it looks like something is weird with that memory check.

Thanks!

**Comment by adriaandegroot** [comment]
I'm pretty sure this is related to #686 , which also shows tracebacks into parted or kpmcore depending on where things fall over exactly. Closing also because of lack o0f backtrace.
