### ISSUE TITLE
CAL-420: Calamares crash if user in removeuser.conf not exist

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#577]
Jira issue originally created by user embar-:

**Comment by adriaandegroot** [comment]
The transition from Jira obscured the fact that there was a Boost.Python error in there, caused by bad PEP8 conversion which added commas, turning

```
libcalamares.utils.debug("userdel failed")
```

into

```
libcalamares.utils.debug("userdel",
 "failed")
```

(Paraphrased) This is fixed working towards 3.1.2.
