### ISSUE TITLE
CAL-421: Crash during displaymanager configuration for kdm as configuration file not exist

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#578]
Jira issue originally created by user embar-:

In openSUSE KDM configuration is stored /usr/share/kde4/config/kdm/kdmrc
But calamares forces to use /usr/share/config/kdm/kdmrc
and fails.

08:40:07 [0]: Starting job "displaymanager" 
08:40:07 [1]: [PYTHON JOB]:  "slim selected but not installed" 
08:40:07 [1]: [PYTHON JOB]:  "lightdm selected but not installed" 
08:40:07 [1]: [PYTHON JOB]:  "gdm selected but not installed" 
08:40:07 [1]: [PYTHON JOB]:  "mdm selected but not installed" 
08:40:07 [1]: [PYTHON JOB]:  "lxdm selected but not installed" 
08:40:07 [1]: [PYTHON JOB]:  "Setting up autologin for user nauajs." 
08:40:07 [0]: Installation failed: 
08:40:07 [0]: - message: "Cannot write KDM configuration file" 
08:40:07 [0]: - details: "KDM config file /tmp/calamares-root-plpebc0x/usr/share/config/kdm/kdmrc does not exist" 
08:42:33 [0]: Calamares will now quit. 

Note, that for other display managers, Calamares skipped configuring and not crashed.

**Comment by adriaandegroot** [comment]
@philmmanjaro Does Manjaro even have or support KDM? I mean, that's KDE4 technology, EOL'ed a few years ago.

**Comment by philmmanjaro** [comment]
@adriaandegroot: not anymore. We use SDDM on our KDE edition. Does Debian or Suse still use KDE4?
