### ISSUE TITLE
CAL-426: xfs not mounted after finish of installation

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#583]
Jira issue originally created by user chsinlmu:

If one selects manual partitioning in the partitioning section of the installer and xfs as file-system for the /home-Partition (as an example), the partition cannot be mounted at the first start of 
the fresh installed system. This is caused by a wrong entry in /etc/fstab: the filesystem entry is written in **uppercase letters (XFS)**,  which is not vaild. It should be lower case. 

Otherwise, the installer works great and fast, you have done a great job on it.

**Comment by adriaandegroot** [comment]
The filesystem type (e.g. "XFS" is now lowercased, fixed in 3.1.2 I think).
