### ISSUE TITLE
CAL-427: Long hang on final umount stage of installation

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#584]
Jira issue originally created by user sb56637:

Hi, I had this install hang at the umount stage for about 15 min. Eventually it finished, still showing the umount status line at the bottom, but it also had the restart checkbox and the Quit button, which was successful. Thanks!

**Comment by adriaandegroot** [comment]
With no logs, and no steps to reproduce, close with "needsinfo", but there's no original submutter still attached to ask.
