### ISSUE TITLE
CAL-428: When using Encryption the system will show error messages regarding swap when the system first boots up

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#585]
Jira issue originally created by user andrebrait:

When selecting the use of encryption, Calamares sets up the partitions using LVM and LUKS, but it creates the Swap partition separate from the one used for LVM. The partition is created as a Linux-swap partition (type 82), which causes systemd to discover the partition and try to use the swap partition directly, which fails, since it's also encrypted, prompting an error message. By running fdisk/gdisk and setting the partition type to 83, systemd stops auto discovering the swap partition and the error goes away. It continues to work as intended since the swap can be of any partition type and it's set up correctly in the fstab (which points to the device created when the partition is unencrypted).

When using encryption, Calamares should use a different partitioning scheme, either setting the swap partition's type to 83 or by creating it inside the LVM volume (which is what Fedora, Ubuntu, etc. do).

**Comment by adriaandegroot** [comment]
This has been fixed as #772 and #730
