### ISSUE TITLE
Don't create to create btrfs subvolumes that already exist

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#586]
Jira issue originally created by user sb56637:

Hi, I'm trying to see if I can install openSUSE via Calamares to a BtrFS partition that lets me enable Snapper integration with GRUB2. For that to work, openSUSE expects certain BtrFS sub-volumes to be present. So I pre-created a partition with @ and @/home subvolumes, then used Calamares to try to install onto that partition with the "keep" option. However, it looks like Calamares fails because it still tried to re-create those sub-volumes:

`Boost.Python error in job "mount".
<class 'subprocess.CalledProcessError'>
Command '['btrfs', 'subvolume', 'create', '/tmp/calamares-root-q3kdlt07/@']' returned non-zero exit status 1
Traceback:
  File "/usr/lib64/calamares/modules/mount/main.py", line 124, in run
    mount*partitions(root_mount*point, partitions)

  File "/usr/lib64/calamares/modules/mount/main.py", line 74, in mount_partitions
    root*mount*point + '/@'])

  File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
    raise CalledProcessError(retcode, cmd)`

**Comment by demmm** [comment]
This feature request is now well over 6 years old, never a PR submitted for it, time to close. It should be implemented with other, much more recent BTRFS changes requested.
