### ISSUE TITLE
CAL-432: checkHasInternet always returns true

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#590]
Jira issue originally created by user paddatrapper:

In a VM, checkHasInternet() always returns true, even if the VM is not connected to a network

**Comment by adriaandegroot** [comment]
There was an additional check added as part of 3.1, which fetches a user-defined URL as part of the check. Can you re-confirm with 3.1, or provide very specific instructions to reproduce the problem (host OS, VM type, guest OS, network configuration).

**Comment by adriaandegroot** [comment]
Naturally, there's no original-poster involved anymore, so asking for feedback is pointless. I'm going to assume that the additional check works as expected.
