### ISSUE TITLE
CAL-435: More horizontal space for logo

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#593]
Jira issue originally created by user highvoltage:

The logo space in the installer is hardcoded to a square, but the space available is a much longer horizontal rectangle. For basic square or round logos this works fine, but for logos that contain text or are longer horizontally this results in a really tiny logo.

It would be nice if it was possible to use that whole space to display wider logos.

**Comment by adriaandegroot** [comment]
It is no longer hard-coded to a square. If you name a big rectangular png in the branding file (eg something 600x150px) , you get a rectangular logo.
