### ISSUE TITLE
CAL-436: Calamares should be self-aware, don't try to install on source drive

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#594]
Jira issue originally created by user sb56637:

Hi everyone, I have noticed that Calamares often tries to offer installing to the source drive that is being used to boot the live system. This is almost never a sane choice, so it looks like Calamares needs to become aware of what device its booted from.

Thanks a lot for Calamares!

**Comment by adriaandegroot** [comment]
This has been fixed somewhere in the 3.x series; there is code to exclude the device holding / from the list of selectable devices.

**Comment by lfdominguez** [comment]
> This has been fixed somewhere in the 3.x series; there is code to exclude the device holding / from the list of selectable devices.

Uff this breaks my recover install system... explain:
I only have an .iso to reinstall my system, so i created a new partition on my hard drive, `dd` the iso to that filesystem and used the grub to boot the live manjaro.... but when i will use manjaro installer dont allow select source disk, ufff, but manjaro installer is booting from different partition, i think that really this is not a bug, better put a warning....
