### ISSUE TITLE
CAL-437: Can't create NILFS2 filesystems due to mkfs.nilfs2 warnings

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#595]
Jira issue originally created by user sb56637:

Hi, just for kicks I decided to try to install my OS to a NILFS2 root. Calamares fails during the filesystem creation stage, because mkfs.nilfs2 is very verbose and requires "ARE YOU SURE? Y/N" confirmation for things like pre-existing superblocks from previous filesystems.

As a workaround, I was able to pre-create the NILFS partition and install to that with Calamares via the partition "Keep" option.

Thanks!

**Comment by stikonas** [comment]
Should have reported this to kpmcore (bugs.kde.org). I'll try to fix it though.

**Comment by stikonas** [comment]
Fixed:

https://commits.kde.org/kpmcore/2cfcefd9c93156206533effc3e5a383910c99728
