### ISSUE TITLE
CAL-438: Calamares should create /etc/lightdm/lightdm.conf if it doesn't exist

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#596]
Jira issue originally created by user sb56637:

Hi there, for whatever reason my spins of openSUSE don't use a `/etc/lightdm/lightdm.conf`, just a minimal `lightdm-gtk-greeter.conf`. Of course if `/etc/lightdm/lightdm.conf` is created, it will work for adding auto-login users. But as it is right now, the displaymanager module fails on me. Would it be possible to make Calamares add this file if it doesn't exist?

Thanks a lot.

**Comment by adriaandegroot** [comment]
I'm going to call this "wontfix". Current behavior is to bail out if the DM config file is absent (for all of the different DM's). I think creating config files is outside the scope of Cala: the file should be on your live or squashed filesystem.
