### ISSUE TITLE
Enryption on Debian

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#602]
Jira issue originally created by user pavroo:

I built debs 2.4.6 on Debian testing (for Sparky). It works fine on not encrypted partition, but failed when installing the system on LUKS. I tried the automated and manual partitioning, but both stopped trying unpack the squashfs by rsync. The point is that the non encrypted installation mounts root fs in /tmp/calamares-root-xxxx, but encrypted installation do not mount root fs in /tmp at all. And the rsync stops couse there is not enough space (and the root partition) to copy the files.

**Comment by abucodonosor** [comment]
Still a bug on Debian ?

**Comment by highvoltage** [comment]
I can confirm that this isn't a problem with the latest version of calamares. If you need help configuring encryption let me know.

**Comment by adriaandegroot** [comment]
Closing following @highvoltage 's comment.
