### ISSUE TITLE
CAL-446: reboots if it doesn't find the squashfs

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#605]
Jira issue originally created by user jriddell:

testing Calamares on Neon with the wrong settings it complained that it couldn't find the squashfs file. /etc/calamares/modules/unpackfs.conf points to the wrong file so this is sensible and correct.  On clicking OK it reboots! no questions asked.  very harsh.

**Comment by adriaandegroot** [comment]
@jriddell Confirmed with a Neon build from may 2017.

**Comment by adriaandegroot** [comment]
What happens is that the error triggers a click of quit / cancel on the page *after* the summary. Which  happens to be the "everyything is wonderful" page, which has a checkbox "rebooty now".

So it's working as designed, only .. well, you get the picture.
