### ISSUE TITLE
Suggest to format in fat32 in EFI mode

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#607]
Jira issue originally created by user koldbyte:

Please add an alert to change the Filesystem to FAT32 for the /boot/efi partition since it seems to be the only one supported. Otherwise, the grub installation fails everytime(using ext4 by default). 
I had to search on the internet and read a lot to pin-point that the filesystem was the issue.
A nice and simple warning should be good.

**Comment by itchka** [comment]
Here's an extract from our release notes for our last major release of OpenMandriva.
As can be seen there is more than one issue around this point. Also the filesystem must be the correct type for the partition size. 

"When the installer reaches the partitioning stage the / (root) partition should be removed and a small (330mB) FAT32 partition created at the start of the drive. If diskspace is critical then a smaller partition may be used but be sure to set it as FAT16 in Calamares otherwise the install will fail. If you fail to observe these steps installation of the boot loader will fail. Subsequently partition the disk in the normal way."

**Comment by adriaandegroot** [comment]
Isn't the automatic EFI-detection supposed to do that? I have not looked closely at that code, since my default VirtualBox test systems are all BIOS-setups.

**Comment by demmm** [comment]
@adriaandegroot 
To stop numerous failures in manual mode, I added the text, it has helped a lot to lessen the EFI failures:
https://github.com/KaOSx/calamares/blob/master/src/modules/partition/gui/ChoicePage.cpp#L237
Detection later on will warn too, but seems clearer to many users to have it there.

**Comment by itchka** [comment]
Ok but 512Mb is much bigger than it need be; 300Mb is sufficient to allow fat32 it is when you go < 300Mb you must use fat16 which incidently works fine. Why not say "If your EFI partition is less than 300Mb then you MUST use fat16 else the installation will fail" 
People don't want to waste disk space unless they need to.

**Comment by kkofler** [comment]
Doesn't the UEFI spec actually mandate FAT32, even for small partitions? If `mkfs.vfat` refuses to set that up, that sounds like an issue in `mkfs.vfat` that ought to be fixed.

**Comment by itchka** [comment]
mkfs.vfat will do it but it produces a warning that the filesystem is too small. I suspect calmares interprets the return code as a failure.

**Comment by stikonas** [comment]
Why does fat32 have to be 300MiB? I can successfully create 32MiB  FAT32 partitions with KPM, so I don't think return code is different, else KPM would also fail.

fat16 is probably working fine in most case but who knows if there area any weird UEFI's that would fail... I actually use 1MiB FAT12 partition here and it boots fine...

**Comment by mirh** [comment]
http://www.uefi.org/sites/default/files/resources/UEFI%20Spec%202_7_A%20Sept%206.pdf#page=579
This is latest UEFI spec. 
FAT32 is expressively mandated for any non-removable media. 
And I don't think user should even have to select anything (unless we want to give choice for FAT12?)

p.s. Windows 7 created me a 100MB ESP, and it's working perfectly good.

**Comment by fattredd** [comment]
Any update on this? Why is this still open?

**Comment by JoelStienlet** [comment]
About the size of a fat32 partition: you can have a look at the specification of fat32 from Microsoft: http://read.pudn.com/downloads77/ebook/294884/FAT32%20Spec%20%28SDA%20Contribution%29.pdf
p14: "Determination of FAT type when mounting the volume " "The FAT type is determined solely by the count of clusters on the volume " 
Then p15 you have the algorithm that MUST be used to determine if the filesystem is fat16 or fat32.
So the smallest fat32 partition allowed, assuming a 512 bytes cluser size, is: 65525*512=33548800 bytes.

**Comment by kkofler** [comment]
The problem there is that the UEFI spec contradicts the FAT spec, because the UEFI spec requires support only for FAT32. UEFI implementations may or may not support FAT12 and FAT16. And it is possible to create undersized FAT32 partitions.

**Comment by JoelStienlet** [comment]
1) I've seen a previous comment from itchka saying that "it is when you go < 300Mb you must use fat16", any reference for this? Does this come from an UEFI spec?
2) kkofler " it is possible to create undersized FAT32 partitions" -> what do you mean exactly? Do you mean "some random software allows the user to ask for a size of a fat 32 partition that is smaller than 33548800 bytes, without displaying an error", or: do you mean that Microsoft's fat32 specification allows to create a fat32 partition smaller than 33548800bytes, in which case I misunderstood Microsoft's spec?
As I see things:
- UEFI implementations not supporting fat 16 (nor 12) will not work on a partition smaller than 
33548800bytes. (which is pretty small actually, not sure this is really an issue in any practical situation)
- UEFI implementations pretending to support fat32 must work with partitions as small as 33548800bytes, provided these partitions are formatted as fat32. If these uefi implementations fail to work on such a small partition, then tey can't pretend to be fully fat32 compliant.

**Comment by JoelStienlet** [comment]
I think Microsoft's spec may be unclear. p13: 
"For 512 byte sector sized media: if volume size is < 512 MB, the volume is formatted
FAT16 else it is formatted FAT32. It is possible to override the default FAT type selection."
As I understand this, p13 only **recommends** that <512MB volumes are formatted as FAT16. What they call "override" is actually not following the recommendation given p13, but you are still required to hava a legal cluster count with respect to the calculation p15.
So what we actually only have to care about is the calculation p15.

**Comment by mirh** [comment]
I don't think FAT12/16 should be excluded (you never know how people are gonna use calamares, though at least a warning is definitively welcome)
And 300MB seems quite a lot of space. Like, my aforementioned 100MB is a bit tight arguably, but that's just because I keep a lot of old kernels around - and I'd really be super pissed if I had to re-format my whole disk only to install linux.

**Comment by mirh** [comment]
The spec actually seems to suggest all types of FAT should be supported, one way or another.. if any this guarantee should be taken with a pinch of salt insofar as it will be less tested (e.g. my 2011 laptop had a pretty [hairy bug](https://bbs.archlinux.org/viewtopic.php?id=199871) with long names, even on FAT32). 

Anyhow, last time I checked /boot means the efi partition when you are on UEFI.

**Comment by stikonas** [comment]
> Anyhow, last time I checked /boot means the efi partition when you are on UEFI.

That's definitely not true in many cases. Often distros mount EFI partition to /boot/efi and /boot is either another partition or part of rootfs and contains kernels, initramfs, rest of bootloader files.

**Comment by mirh** [comment]
https://www.freedesktop.org/software/systemd/man/systemd-gpt-auto-generator.html
At least everything that uses systemd should (also see https://github.com/systemd/systemd/pull/3757#issuecomment-234290236), though of course the ways of grub are infinite. 

Anyway, I guess that's still another reason 300MB is exaggerated.
