### ISSUE TITLE
home folder encryption

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#608]
Jira issue originally created by user jriddell:

<stikonas> Riddell: I think encrypt home folder feature uses ecryptfs and unlocks it with user's password (I guess it uses some PAM module)
<stikonas> there is something called pam_ecryptfs
<stikonas> can probably be done as a calamares module
<stikonas> it is mostly just running sudo ecryptfs-migrate-home -u user
<stikonas> http://www.howtogeek.com/116032/how-to-encrypt-your-home-folder-after-installing-ubuntu/
<stikonas> and you don't even need temporary user as you are still in live cd

**Comment by abucodonosor** [comment]
@adriaandegroot 

Maybe plasma-vault ( or code from there ) can help with that ?

**Comment by es20490446e** [comment]
[systemd-homed](https://www.howtogeek.com/673018/systemd-will-change-how-your-linux-home-directory-works/)

**Comment by nexryai** [comment]
I thought I could do the same thing by adding ` ecryptfs-migrate-home -u @@USER@@` to the shellprocess, but it seems not to be the case. This command will prompt you for your login passphrase. I still think I should add a module to encrypt the home directory.

**Comment by demmm** [comment]
This feature request is now well over 5 years old, never a PR submitted for it, time to close.

**Comment by es20490446e** [comment]
If nobody else does I will eventually implement it, when I finish a few things I'm working on.
