### ISSUE TITLE
CAL-452: Print output of failed commands on error dialog

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#612]
Jira issue originally created by user shainer:

When a critical command is run through Calamares and fails, an error dialog is shown (check*target_env*call).

This error dialog only shows a short stacktrace and the exit code of the program, which may or may not be informative enough to spot the issue. I usually rerun the command in the target chroot separately to know what actually happened. When it's a distro tester encountering an error, they don't always know to do this, so it's hard to debug problems.

I am thinking we should display the full command output in the dialog, maybe as a QTextEdit or similar widget so even long outputs will not disrupt the visualization. Thoughts?

**Comment by adriaandegroot** [comment]
@shainer I'll make it log the output (always) for failed commands; that way you get a much better picture of what's going on, but I think the error dialog is bad enough with tracebacks and gobbledygook as it is.
