### ISSUE TITLE
CAL-454: User reports segfault with pre-existing LUKS partitions

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#614]
Jira issue originally created by user sb56637:

Hi, a user has been having trouble installing GeckoLinux (openSUSE based) with Calamares 3.0. 
https://nwrickert2.wordpress.com/2017/01/06/geckolinux-422-a-review/#comments
The only thing different about his setup is the presence of LUKS partitions, so I assume that is the issue. Any comments on what might be going wrong?

**Comment by stikonas** [comment]
It might be a dublicate of #691 (LUKS crashes on NVMe) which is fixed in recent kpmcore versions.

**Comment by abucodonosor** [comment]
Not sure what we can do about this one. We are left without logs or anything when
that issue moved.. So I close it for now..
