### ISSUE TITLE
CAL-457: GRUB Config missing for encrypted debian-based systems

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#617]
Jira issue originally created by user highvoltage:

GRUB installation fails with a message that GRUB*ENABLE*CRYPTODISK=y needs to be set in /etc/default/grub

Not sure if that should be handled by calamares or whether we'd want an additional hook that detects that encryption was enabled for debian systems, but this should be fixed as encryption is becoming critical for more and more users.

**Comment by abucodonosor** [comment]
@highvoltage 

is this still an issue ?

if yes can you point me to a debian-calamares iso so I can have a look ?

**Comment by abucodonosor** [comment]
I've tested that with debmo-17.09-buster-amd64 from @highvoltage and 
grub entry is OK. Grub unlocks just fine..

**Comment by abucodonosor** [comment]
closing now since works just fine .. 

for part2 #602 I wait @highvoltage to have a new fixed ISO
