### ISSUE TITLE
CAL-463: Calamares not handling EFI bootloader correctly with complex drive layout

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#624]
Jira issue originally created by user sb56637:

Hi there, I've been trying to help a GeckoLinux user that is having major trouble installing a working bootloader with Calamares on a UEFI setup. It's an extremely complex setup with no less than 5 hard drives, and the first one has an EFI partition that needs to boot Windows.

Here are all the gory details:
https://github.com/geckolinux/geckolinux-project/issues/35

Here's his drive layout:
[screenshot](https://photos.google.com/share/AF1QipPD46ib2HXAkYBVu3PmBiF46auGE8DFj9YPf3ZI*vp7UmebI34envRvVJXqH3*Jdw?key=dmV2YzltenBqaUIyNzNoQ0JZSWpJMTdaQmNiUk1R)

And I am attaching his Calamares log from an installation that appears to have completed successfully but doesn't lead to his UEFI firmware seeing the bootloader. It just boots straight into Windows still, and there is no openSUSE bootloader in the UEFI boot devices list.

Thanks for the help.

**Comment by geckolinux** [comment]
The user reports this issue as solved with Calamares 3.1. Thanks a lot for the fix!

**Comment by demmm** [comment]
Fixed
