### ISSUE TITLE
CAL-464: Setting up a TimeZone and set def. lang variables for next step

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#625]
Jira issue originally created by user blackcrack:

Hi Peep's

Setting up a Location and set lang variables for next step 
and set a def. Language by Timezone (as Example: Berlin => "de-DE") 
for Keyboard setting up and selecting by default Land/Language spezific
but should be possible for selecting other. 
It should only use as Language spezific variable trigger for the next Step: 
Keyboard-Language-Selecting. 

exist language variable by selected Land ? => use $language$ for first first selecting Keyboard language.

In my example case =Used Region :Germany, Zone: Berlin=> German/ German(eliminate dead Keys)

Setting up by selecting Region and TimeZone the default Language

in this case, 
TimeZone Berlin = de-DE 
TimeZone Zurich = de-CH 
TimeZone Hong Kong = zh-CN 
=> 
and use this as default Keyboard lang for autoselecting at first and the possibile for fine adjustment. And later the Default Language with possibility to adjustment

best regards
Blacky

**Comment by adriaandegroot** [comment]
This already happens when you click on the timezone widget, or when a location is selected through geo-ip.
