### ISSUE TITLE
CAL-465: EFI and new Package error after last beta release.

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#626]
Jira issue originally created by user chrisfernandez:

Was trying the new beta to test EFI.. as in CAL-44* ticket.
this update introduced a new bug in Packages, :(
was able to work around it, comenting the Install part of packages
and using netinstall to install packages instead..

then try to boot in EFI mode.. STILL no luck.. :( attached screen also with the EFI Shell

**Comment by paddatrapper** [comment]
This should be fixed in the latest release

**Comment by ChrisFernandez** [comment]
thanks, I will give it a try.

**Comment by adriaandegroot** [comment]
@ChrisFernandez what is the status? The original text imported from jira doesn't really tell me what the problem was, though.
