### ISSUE TITLE
CAL-83: SSD support/detection

### ISSUE THREAD

**Issue by calamares-user** [calamares/calamares#667]
Jira issue originally created by user @teo:

I would be nice to have automatic SSD detection to enable TRIM and for Btrfs ssd optimization. There can be some RAID user where TRIM will/can be harmful, so we should have these at least as an option.

    (Linux 3.14->
      Btrfs on a SSD for system installation and an emphasis on maximizing performance:
           noatime,compress=lzo,ssd,discard,autodefrag)

               Note: The following examples can decrease performance on less capable hardware. Performance may increase by removing the nospace_cache option and using lzo as compression.

**Comment by adriaandegroot** [comment]
Such flags can be set, on a per-filesystem-type basis, in `fstab.conf`
