### ISSUE TITLE
After several installations, HDD will not boot, until manually setting boot flag

### ISSUE THREAD

**Issue by AlManja** [calamares/calamares#687]
Older 32 bit desktop with upgraded 4gb ram.

I tried to install several different (latest) flavors of Manjaro with newest Calamares (btw, beautiful design) and previous version and every single time HDD will not boot on this particular desktop. Once I tried cli installation, all was OK. Someone told me, he had the same problem, that boot flag was not properly set, and he needed to set it manually. So I followed his tip, took latest OpenRC version and again, after installation, HDD was not boot-able. I logged into live session, with Gparted, set the boot flag to mbr (sda - there is no other OS on it and system has only one hdd) and all is OK. Also forgot to mention, every installation ended with successful installation msg. 

So, it seems like Calamares on this old computer sets boot flag to partition instead to mbr and that's why HDD does not boot? Just a guess... Computer is 32 bit if this means anything. 

I installed Manjaro with Calamares on few other computers without any problem. This will probably not be of much help to you but I decided to report it any way. Thanks for all your good work!

**Comment by adriaandegroot** [comment]
This would need more details on how, exactly, to reproduce the problem (something based on VirtualBox would be ideal). What flags, exactly, and how are you setting them? What kind of partitioning scheme are you using beforehand? (closing as has-workaround and needs-more-info and use-newer-manjaro-releases).
