### ISSUE TITLE
About system local and system language

### ISSUE THREAD

**Issue by tulliana** [calamares/calamares#688]
After I opened Calamares (3.1.0) , I continued with the Turkish language option. Calamares has set my location. City choice and system local selection true. However, the system language is set to English. I guess this is a mistake. The system language should have been marked in Turkish

Calamares images attach
![cala](https://cloud.githubusercontent.com/assets/2324162/23526700/f4b16798-ff8a-11e6-91d0-328d5c9510e6.png)
![calamar](https://cloud.githubusercontent.com/assets/2324162/23526705/fb494468-ff8a-11e6-8210-56b90ada9a03.png)

**Comment by philmmanjaro** [comment]
Not all elements are translate-able. Example: `The system language will be set to %1.`

**Comment by tulliana** [comment]
I'm not talking about translation. Calamares not set to system language as automatic

**Comment by philmmanjaro** [comment]
Default language is set to **English-US** and **New York**. On the first page you only set the translation of the Installer. If you enable GeoIP **Calamares** should detect your locales and set it automatically. However this is disabled by default. Therefore you have to click on **Istanbul**.

**Comment by tulliana** [comment]
I'm talking about GeoIP. GeoIP enabled. GeoIP not set to system language as automatic.

One click required on Istanbul. ;)

**Comment by philmmanjaro** [comment]
Please run **sudo -E calamares -d** with English locales loaded and a second run with Turkish locales loaded on your OS before you start **calamares**. For both runs please post the console output.

**Comment by philmmanjaro** [comment]
Most likely you don't provide a full **locale.gen** file with all locales enabled.

**Comment by kkofler** [comment]
Actually, if you have GeoIP disabled, the language you pick for the installer is used as the default language in the locale screen. So GeoIP being enabled might actually be the source of the issue here, it might be detecting the country incorrectly.

**Comment by shadeslayer** [comment]
Hi
I have managed to reproduce this bug. It seems to me that internally calamares has the right setting however, the UI does not get updated with what calamares know's internally.

A quick way to confirm this is by choosing another language such as German on the welcome page and then looking at the string on the timezone page. Then if you choose a different timezone on the map, the string is updated to the right value.

**Comment by adriaandegroot** [comment]
I can reproduce this with netrunner, too ..  the string updates as soon as you click on another timezone, but going back, changing the language on the welcome screen and then clicking next leaves the previously selected language showing.

**Comment by adriaandegroot** [comment]
Scenario 1:
 - start
 - click next (leave language unchanged)
 - notice language is English (US), numbers is English (US), zone is NY
 - click on New York (it's already selected)
 - no change
 - click on London
 - language is English (UK), numbers is English (UK)
 - click on Amsterdam
 - language is English (US), numbers is Dutch (NL)
 - click ''change'' button for system language
   - double-click "da_DK" (dialog doesn't close, probably should)
   - clock ''ok''
 - language is Danish (Denmark), numbers is Dutch (NL)
 - click New York
 - language is English (US), numbers is English (US)
 
Scenario 2:
 - start
 - select Danish language
 - notice installer is re-translated
 - click naeste (next)
 - notice language is English (US), numbers is English (US), zone is NY
 - click on New York (it's already selected)
 - language is Danish (DK), numbers is English (US)
 - click on London
 - language is Danish (DK), numbers is English (UK)
 - click on Amsterdam
 - language is Danish (DK), numbers is Dutch (NL)
 - click ''change'' button for system language
   - double-click "da_DK" (dialog doesn't close, probably should)
   - clock ''ok''
 - click New York
 - language is Danish (Denkmark), numbers is English (US)
 
 
Three issues identified:
 - when entering the page from the welcome page, wrong language is
   displayed (scenario 2 shows this)
 - double-clicking on language selection doesn't close it
 - explicitly selected language is ignored by click on timezone widget

**Comment by philmmanjaro** [comment]
@adriaandegroot: **welcome** and **locale** are not connected and therefore also not linked. **Locale** will be either set by **geo-ip** or default setting in config file of the module.
