### ISSUE TITLE
Preselect keyboard layout that matches the langauge

### ISSUE THREAD

**Issue by benbullard79** [calamares/calamares#689]
OpenMandriva user is reporting:

"During install if i select my language (danish) i would like for the danish keyboard layout to be preselected on the next screen.

I assume people mostly need the danish keyboard layout when selecting danish language and same for other languages."

here: https://issues.openmandriva.org/show_bug.cgi?id=2045

**Comment by adriaandegroot** [comment]
I'm not sure we can do this with any kind of real accuracy, not without building up tables of correspondence between locales and most-likely keyboard layout.

 - Locales are language first, then country - region variants. For Danish, it's straightfoward: da_DK. English (Nigeria) is en_NG, and Hausa (also spoken in Nigeria) is ha_NG. Greek is el_GR and el_CY (on Cyprus).
 - Keyboard layouts tend to be national: country first. So there is a layout dk, and there is a layout ng. There are also variants, for typing different languages within a country: there's ng and ng(hausa) for the different variants in Nigeria. There is a layout gr (for Greek), but no national layout for Cyprus; locale el_CY should pick keyboard layout gr.

There are more special cases.

I have added a branch, i689-kayboard-layout (yes, typo) that tries to do layout-selection based on locale, but I am not convinced it's going to work.

**Comment by philmmanjaro** [comment]
@adriaandegroot: I've [merged](https://github.com/manjaro/calamares/commit/4c33e9a16a5b2c400f0f151bbfdf98ca4d6d9875) these changes now into my [development branch](https://github.com/manjaro/calamares/commits/development). I didn't had the time yet to test this yet. The package including these changes is called **calamares-git**. 

For the special cases I suggest to create a list and set the layout manually and not by the guessing-routine. However, we have to test the routine in general first and get some feedback from the community on this one.

**Comment by petsam** [comment]
Here is some feedback @philmmanjaro 
https://forum.manjaro.org/t/virtual-console-has-wrong-keymap-bug/36149/3?u=petsam

**Comment by adriaandegroot** [comment]
For the Manjaro issue, note that X11 defines an Austrian keyboard layout in `/usr/share/X11/xkb/rules/base.lst` .. Calamares uses that list, so there's not much to do about it from our end. Keyboard layout "at" looks (in the widget, which isn't guaranteed to be accurate) the same as layout "de".

On the (text) console end, Calamares tries to set the same key mapping as on X11, if it can find a corresponding mapping. The mappings are searched in the *convertedKeymapPath* directory.

**Comment by adriaandegroot** [comment]
This branch was merged -- the keyboard layout is guessed based on the selected language (see debugging output, like

```
07:07:59 [1]: Got locale language "de_AT.UTF-8" 
07:07:59 [1]:  .. extracted country "Austria" :: ("de", "AT") 
07:07:59 [1]:    .. looking for locale part "AT" 
07:07:59 [1]:    .. matched "at" 
07:07:59 [1]: Next level: "de" 
07:08:00 [1]: xkbmap selection changed to:  "at" - ""
```

Which matches keyboard layout *at* (Austrian) with selected language *de_AT*. There is a table of exceptions in the code, translating e.g. *ig_NG* to layout *ng_igbo* -- see `KeyboardPage.cpp` around line 309.

**Comment by philmmanjaro** [comment]
@adriaandegroot: so now also merged by upstream?

**Comment by es20490446e** [comment]
Works well for es_ES.
