### ISSUE TITLE
Autocheck packetmanager and autointegrate rpm/deb a.s.o. Installer

### ISSUE THREAD

**Issue by blackcrack** [calamares/calamares#690]
Hi,
a suggestion/ask :
it is possible for let check the if it is installed apt-get, urpmi, rpm (and so on) 
(also on a live iso/system) if it is exist and then via auto-packet-installer-script's
(check the distriebution and architecture and select the right script) 
for the Distribution like Debian,Redhat/Fedora, OpenMandriva and others, 
and it is in Live-Iso mode, for make it possible automatical open for the mirror-list , connect the ftp,
search the right /open the right ftp-folder and start an rpm-installer insteat decompress a squash-fs and makes in the directly way a live deb,rpm (and so on) install and not (and maybe disable) 
a squash-decompress.
With this makes the way free for have a fully fresh and clean (maybe also for bughunting with this possible) System with packets, where it is fully fresh direct install on the hardware directly down 
from the FTP's with the packes from the Distriebution.

With this makes also possible for let see if something in the distriebution bad
and the packets of the distriebution it is clean and works like it should.

best regards
Blacky

**Comment by adriaandegroot** [comment]
No, we expect the distro to provide a sensible configuration for the packages module, if that is what they are going to use. It is fairly straightforward to create a usable squashfs for experimentation: there is a target `example-distro` in current Cala to build one.
