### ISSUE TITLE
bootloader module fails when /EFI/Boot exists

### ISSUE THREAD

**Issue by agaida** [calamares/calamares#692]
```
Boost.Python error in job "bootloader".
<class 'subprocess.CalledProcessError'>
Command 'mkdir -p /boot/efi/EFI/boot' returned non-zero exit status 1
Traceback:
  File "/usr/lib/calamares/modules/bootloader/main.py", line 309, in run
    prepare_bootloader(fw_type)

  File "/usr/lib/calamares/modules/bootloader/main.py", line 283, in prepare_bootloader
    install_grub(efi_directory, fw_type)

  File "/usr/lib/calamares/modules/bootloader/main.py", line 231, in install_grub
    check_target_env_call(["mkdir", "-p", efi_boot_directory])

  File "<string>", line 2, in <module>
```
In the current case /boot/efi/EFI/Boot was created by MS Win 10 - the bug is reproducible, one of our Users reported exactly the same bug on  new machine with a pre installed Win10.

**Comment by agaida** [comment]
additional info: in bootloader/main.py should be a case check for boot, as boot, Boot, BOOT are common for the fallback efi.

>         # VFAT is weird, see issue CAL-385
>         efi_directory_firmware = os.path.join(efi_directory, "EFI")
>         if os.path.exists(efi_directory_firmware):
>             efi_directory_firmware = vfat_correct_case(efi_directory, "EFI")
> 
>         efi_boot_directory = os.path.join(efi_directory_firmware, "boot")
>         if os.path.exists(efi_boot_directory):
>             efi_boot_directory = vfat_correct_case(efi_directory_firmware, "boot")
>         else:
>             check_target_env_call(["mkdir", "-p", efi_boot_directory])

**Comment by highvoltage** [comment]
What version of calamares are they using? This sounds a lot like #538 which has been solved.

**Comment by agaida** [comment]
Unfortunately nothing was solved.

**Comment by agaida** [comment]
@highvoltage - latest git as usual

**Comment by mimecry** [comment]
got this bug on the latest Manjaro KDE 17.1.10 ISO at the start of the installation process

![error msg](https://i.imgur.com/d55TdOe.png)

i did as advised by a post on the Manjaro forum to run the following commands before installation

```
sudo pacman -Sy
sudo pacman -S grub
```
but no dice

**Comment by philmmanjaro** [comment]
@mimecry: I assume your problem may be something else. How did you install Manjaro? Manual partitioning or with automatic setup? Please post your install.log or start CAL via `sudo -E calamares -d` from within a terminal and post the terminal output somewhere. We have however also a great guide on how to restore [grub](https://wiki.manjaro.org/index.php?title=Restore_the_GRUB_Bootloader).

**Comment by philmmanjaro** [comment]
@mimecry: please read the [user guide](https://osdn.net/projects/manjaro/storage/Manjaro-User-Guide.pdf) on how to partitioning your harddrives. `/boot/efi` needs to be **fat32** and not **ext2**. [Arch](https://wiki.archlinux.org/index.php/EFI_System_Partition) recommends 550 MiB fat32 ...

```
04:15:10 [1]: "/dev/nvme0n1p6" mtpoint: "/boot/efi" fs: QVariant(QString, "ext4") ( QVariant(QString, "ext4") ) "f3b0d6dc-6f6b-4f2c-92b4-c849bcb149ed"
04:15:10 [1]: "/dev/nvme0n1p7" mtpoint: "/" fs: QVariant(QString, "ext4") ( QVariant(QString, "ext4") ) "a1de2eb1-40e2-45a3-b206-9e69ae390186"
04:15:10 [1]: "/dev/nvme0n1p8" mtpoint: "/home" fs: QVariant(QString, "ext4") ( QVariant(QString, "ext4") ) "cfbd6bb4-c552-4159-8265-42b9453a2ae2" 
```

**Comment by mimecry** [comment]
@philmmanjaro: yes, quite embarrassing from me.. i'll retry again at the earliest opportunity

**Comment by mimecry** [comment]
@philmmanjaro you are right, the installation completes without a hitch after i've set the proper filesystems. sorry again for my oversight
