### ISSUE TITLE
If atasmart isn't installed cmake passes but the build itself fails.

### ISSUE THREAD

**Issue by geetam** [calamares/calamares#694]
![screenshot_20170312_221648](https://cloud.githubusercontent.com/assets/15955915/23834941/c0b0ca04-0784-11e7-9989-75dce50648ea.png)

however installing the required library fixes the issue, would it be okay to make a PR with atasmart marked as required in CMakeLists.txt?

**Comment by demmm** [comment]
Are you not using kpmcore?  How did you build kpmcore?  The need for libatasmart is covered there:
https://github.com/KDE/kpmcore/blob/master/CMakeLists.txt#L78

**Comment by geetam** [comment]
I am, actually, I installed kpmcore through pre-built packages but since need for libatasmart is covered there i am closing this issue.
