### ISSUE TITLE
improvements of netinstall

### ISSUE THREAD

**Issue by excalibur1234** [calamares/calamares#706]
i have recently created a manjaro netinstall using the new netinstall feature of calamares:
https://forum.manjaro.org/t/manjaro-lxqt-17-0-net-edition/19023
i am happy, that users can now select, which packages they want to install on their system (see screenshot in link).
i use this chrootcfg.yaml file, to define which packages users can select:
https://github.com/manjaro/calamares-netgroups/blob/master/lxqt/chrootcfg-systemd.yaml

as you can see, there are groups of packages. every package can be selected by the user. i have some suggestions to improve this feature:
- please make it possible to include a text string for each package (like the "description" of package groups). this text string could contain a package description or instructions for installation.
- please make it possible to nest groups. currently, package groups are possible, but subgroups or even sub-subgroups of packages are not possible. i would like to add subgroups and sub-subgroups of packages.
- it would be great to specify conditions of package selections. for example: i want the user to choose one of two possible packages. but installing both are a bad idea, because these packages conflict.
this condition and other conditions would be great.

if these features are already available, please give me the syntax for them.

**Comment by shainer** [comment]
The support for nested groups was added recently. The module README describes how to use this (look for "subgroups"), although the example YAML does not show the feature at the moment.

The other two features you mention are not supported. IMHO the conflict management is pretty complex both in terms of implementation and in terms of keeping the UI user-friendly, while the package description would be hard to fit in the UI as it is now.

So if you plan to contribute them in the future please keep this in mind.

**Comment by adriaandegroot** [comment]
Soo .. what's the status here? Is it something that can be merged from manjaro, and made useful for other distro's as well?

**Comment by adriaandegroot** [comment]
.. and what's the relationship with #666, which has a long and complicated story? I'm not inclined to put a whole lot of complications into Calamares.

**Comment by shainer** [comment]
There is nothing to merge from Manjaro, the reporter used the available features of netinstall and had some proposals for more. My initial analysis stands: the missing ones are nice-to-have, not a high priority. I might be able to devote some time to them if you think it's worthwhile.

Basic support for netinstall was implemented, you can close #666 . What long and complicated story are you referring to?

**Comment by adriaandegroot** [comment]
Closing this one since, as @shainer points out, the netinstall module offers descriptions and nested groups, and the soon-to-land low-density software chooser can do radio-button type installs.
