### ISSUE TITLE
bad module configuration format

### ISSUE THREAD

**Issue by oberon2007** [calamares/calamares#707]
Launching calamares from terminal I keep seeing this message:
```
void Calamares::Module::loadConfigurationFile(const QString&) bad module configuration format "/usr/share/calamares/modules/umount.conf"
```
We are using the default config file on Manjaro.

**Comment by adriaandegroot** [comment]
- Created new VM in Virtual Box, 4GB mem, 8GB disk, 1CPU
 - Installed FreeBSD in that VM
 - Booted Manjaro 17.01 CD, chose "From CD/DVD" in the GRUB menu
 - Clicked away the "Welcome to Manjaro" window, opened a console
 - That message shows up *once* (or is this me being pedantic, that "keep seing" implies that it shows up more than once in a run?)

The problem is that the config file is empty of actual content. In the next Calamares release, empty configs will not trigger the warning.

**Comment by oberon2007** [comment]
“keep seeing" just because we had this "issue"for a while already and it didn't go away for obvious reasons :wink: I was suspecting that it could be related to #686, especially because that issue for me only occurs when I launch CAL for a 2nd time... So it seemed to make sense that it would have something to do with unmount during first run was not happening properly...

**Comment by philmmanjaro** [comment]
@oberon2007: please check one of our **v17.02** preview releases. There I've changed it to following content:

```
---
srcLog: "/root/.cache/Calamares/Calamares/Calamares.log"
destLog: "/var/log/Calamares.log"
```

**Comment by adriaandegroot** [comment]
.. and whatever is the next version of Calamares will accept the empty file without complaining, so either that or @philmmanjaro's modification will squash the warning.

**Comment by oberon2007** [comment]
Yes, @philmmanjaro I just built a i3-pre with your not-empty umount.config and the warning has disappeared as expected. However it is not related - as I had hoped - to the [crash on 2nd run issue](https://github.com/calamares/calamares/issues/686#issuecomment-282519292) Nothing has changed there.

**Comment by philmmanjaro** [comment]
I also applied the patch to accept empty files. [2nd run crash issue](https://github.com/calamares/calamares/issues/686#issuecomment-282519292) I never had. We need to be more specific on how to repeat it. I still assume it may happen on a fresh VM with a really blank HDD without any master boot record what so ever. Same for HDDs fresh from the manufacturer without any formation. Did you tried it already with the latest **v17.0.2-pre6**, which ships with **kpmcore v3.1**?
