### ISSUE TITLE
Spaces are missing in languages list (UnitedStates UnitiedKingdom)

### ISSUE THREAD

**Issue by scootergrisen** [calamares/calamares#712]
When Calamares starts the language list says "English (UnitedStates)" and "English (UnitiedKingdom)" so its seems spaces are missing.

**Comment by scootergrisen** [comment]
About "NorweiganBokmal (Norway)":
There is a problem with the "a" in "Bokmal".
"a" should properly be "å".
Properly other problems with none a-z charaters i would guess.

**Comment by adriaandegroot** [comment]
This is actually a Qt bug (or Calamares shouldn't be using the Qt locale information). The list of country names used to build QLocale data has no spaces in the country names (except for "European Union" and "Outlying Oceania"). It doesn't include accents either, like "Reunion". The list of languages is similarly inconsistent ("NorwegianNynorsk" vs "Western Frisian") and missing accents ("Hawaiian").

So it's something to take up upstream, I think.

**Comment by adriaandegroot** [comment]
QTBUG 32487 (since 2013)

**Comment by gladhorn** [comment]
QTBUG-32487 is about pulse audio. https://bugreports.qt.io/browse/QTBUG-34287 is the right one.

**Comment by adriaandegroot** [comment]
National names seem to be less derpy (at least in Qt 5.9) than the English names, so this has gone away as a side-effect of using the native language and country names.

**Comment by wxl** [comment]
I'm still seeing this in Lubuntu 18.10 and we have Qt 5.11. Given the date of your comment @adriaandegroot I would presume that Calamares 3.2.2 would be sufficient, but that does not play out that way. What am I missing?

**Comment by tsimonq2** [comment]
@wxl We have 3.2.1 in Disco as of right now; does this make a difference?

**Comment by wxl** [comment]
@tsimonq2 I'm confused by your message, as we had 3.2.2 in Cosmic and still do in Disco, though we have some more patches.

**Comment by tsimonq2** [comment]
Ah, right.

**Comment by wxl** [comment]
@adriaandegroot Since I still see this as a problem, can we please reopen this? Or let me know what I'm lacking to see the correct behavior?

**Comment by adriaandegroot** [comment]
It looks like the commit from @apachelogger wasn't actually merged :(

**Comment by adriaandegroot** [comment]
@wxl the country name was fixed in the *welcome* page, but not in the *locale* page. @apachelogger 's patch did the latter as well, and I didn't take that over.

**Comment by wxl** [comment]
Just wanted to officially confirm this is doing what it's supposed to be doing in 3.2.4.
