### ISSUE TITLE
Suggest timezone and keyboard layout should follow selected language

### ISSUE THREAD

**Issue by scootergrisen** [calamares/calamares#713]
During installation if i select Danish language and press next, the next screen show the time zone for Europe/London as default.
I would like the default time zone to follow the language.
So if i select Danish language i would like Europe/Copenhagen to be preselected on the time zone screen.

Again on the keyboard layout screen i would like danish to be preselected if i selected danish language on the first screen.

Tested in OpenMandrivaLx.3.01-PLASMA.x86_64.iso

**Comment by philmmanjaro** [comment]
It always depends what the distro chooses. For some **Europe/London** is selected [by default](https://github.com/calamares/calamares/blob/master/src/modules/locale/locale.conf). We recently changed it to **America/New_York** to match the default **locale** settings. Also we have the service **geo-ip**, which selects automatically based on your IP address.

**Comment by scootergrisen** [comment]
Why select Europe/London by default if i select Danish language?
I would like Europe/Copenhagen to be selected by default.

**Comment by oberon2007** [comment]
That someone speaks Danish doesn't necessarily mean it's also his location! 😉 I think that geoip makes more sense there.

**Comment by philmmanjaro** [comment]
Well, you select the language in **welcome** module to set the translations, nothing more. By default some distros use **Europe/London**, others **America/New_York** for the **locale** module. In some **geo-ip** detection is enabled. Only there **Calamares** and autodetect your location and sets automatically most likely the right setting for you.

Since most distros disable that feature the location is used based on the setting of the given distro. In your case it is **[Europe/London](https://github.com/OpenMandrivaAssociation/calamares/blob/master/omv-locale.conf)**. By selecting the language/translation in **welcome** module you don't automatically select anything in **locale** module. Those modules don't interact with each other.

**Comment by scootergrisen** [comment]
Why select anything by default if its wrong 99.9% of times?

When i install Debian i select danish language and on the next screens the timezone for denmark and danish keyboard layout is selected by default. It just makes more sense.

**Comment by oberon2007** [comment]
Empty locale creates all sorts of problems on a Linux system. Hence it makes sense to define a default. Also, why is no default better than a wrong one? 😉 
As @philmmanjaro has already explained, you need to talk to the distribution in question. This is where these decisions are made. Calamares will just handle their configuration.

**Comment by scootergrisen** [comment]
Generally i think its better not to fill in information that is going to be wrong most times anyways.
If empty locale is a problem you could make it required so user cant go to next screen unless selecting something. But i dont think this is the best solution because now users cant just click next to get started quickly if they just want move on.

I think the good solution is it see what the users selects on the first screen (Danish for example) and then on the next screen Europe/Copenhagen and Danish (Denmark) is already preselected for all the options.

I already filed a bug at https://issues.openmandriva.org/show_bug.cgi?id=2071 but was told to file it upstream.

**Comment by philmmanjaro** [comment]
If they would enable **geoip** it might look differently. Simply try it out by editing the [config](https://github.com/OpenMandrivaAssociation/calamares/blob/master/omv-locale.conf) like this:

```
---
region:        "America"
zone:          "New_York"
localeGenPath: "/etc/locale"
geoipUrl:      "freegeoip.net"
```
Also you can compare it with the [upstream config](https://github.com/calamares/calamares/blob/master/src/modules/locale/locale.conf) and the one used by [Manjaro](https://github.com/manjaro/calamares/blob/development/src/modules/locale/locale.conf).

**Comment by oberon2007** [comment]
For your timezone your location is the determinating factor, no doubt. It doesn't matter which language is selected. You can speak Danish in Mexico as much as you like, the correct timezone with still be Mexico City! 😉
It would make more sense for the keyboard layout maybe, since most likely people will use a keyboard for their language...
In any case it is not really a problem to select what people need in the dialog.

**Comment by kkofler** [comment]
> By default some distros use **Europe/London**, others **America/New_York** for the **locale** module.

And Kannolo defaults to `Atlantic/Reykjavik` because that is the UTC time zone. (The default in the Fedora package is `America/New_York` though, matching the Fedora-wide default. The Kannolo setting is a customization in the remix kickstart.)

**Comment by adriaandegroot** [comment]
Returning to the original question about pre-selecting timezone and locale based on the selected language, I think the discussion is obscured by there being roughly two classes of language:
 - those for which the language *is* geographically bound
 - .. and those for which it isn't.
Danish is a reasonable example of the first; it can be found between Padborg and Hirtshals, from Hvide Sande to Kobenhavn .. but let's not forget the Faeroer, which are another timezone. English, Spanish, Russian, Indonesian, Arabic, Mandarin are examples where there's no telling based on the selected language. And as oberon2007 pointed out, you might be installing your Danish-language system while living in Mexico City.

So I'd say no, location does not follow from language.

**Comment by adriaandegroot** [comment]
(Marking this "next" to indicate intention to close the first issue; the second issue, about pre-selecting keyboard layout based on language, that I think makes sense)

**Comment by adriaandegroot** [comment]
Keyboard layout issue stands on its down in #689
