### ISSUE TITLE
Some language codes appear twice (both .utf8 and .UTF-8)

### ISSUE THREAD

**Issue by scootergrisen** [calamares/calamares#715]
On time zone screen when you click Change... button:

Some language code appear twice like "*.utf8" and "*.UTF-8".
I suppose only one of them should appear.

Also "UTF-8" appear in the list which i suppose should be removed.

**Comment by philmmanjaro** [comment]
That is distro-specific. Please open an issue for your distro to fix the locale list from their end. You can compare for example with [Manjaro](https://manjaro.org/get-manjaro/).

**Comment by adriaandegroot** [comment]
Closing as distro-specific configuration bug. Calamares reads `/usr/share/i18n/SUPPORTED`, or a `/etc/locale.gen` (this is configurable) or `locale -a` output. The first one it finds is used.
