### ISSUE TITLE
Don't allow installing uefi to msdos partitioning and installing bios-legacy to gpt partitioning.

### ISSUE THREAD

**Issue by gohlip** [calamares/calamares#720]
Currently, calamares allows installing uefi to msdos partitioning and installing bios-legacy to gpt partitioning. While this may not be a problem to experienced users - notably when installing bios-legacy to gpt partitioning devices (with a bios-grub partition) - new users are caught up in a tangle after installation particularly when trying to boot windows.
I suggest a warning sign at calamares installer that this sort of installation is not recommended.

Thank you.

**Comment by oberon2007** [comment]
In the Manjaro forums we see a lot of issues because of exactly this. If Calamares is in fact able to recognize this situation it should maybe actually refuse to install this way - or, yes give a warning at least.
Are there actually good reasons why you should actually be able to install in the wrong mode? Or is the problem right now just that Calamares doesn't know or check what is present?

**Comment by demmm** [comment]
As noted in the first post, for the experienced user there are no issues, in fact there are many advantages of using GPT on legacy BIOS too, so having it as an option is preferred imo.

Warnings or checks are needed though if an incorrect setup is used/found (which happens easily, users not setting the needed unformatted partition for BIOS GPT and/or not setting the bios_grub flag).
Example warning used in KaOS (too limited to be used in master Calamares):
```diff
--- /master/calamares/src/modules/partition/gui/PartitionViewStep.cpp	2017-07-04 20:50:35.748479092 -0400
+++ /kaos/calamares/src/modules/partition/gui/PartitionViewStep.cpp	2017-07-04 21:21:15.618483242 -0400
@@ -386,7 +386,11 @@
 
     if ( m_widget->currentWidget() == m_manualPartitionPage )
     {
+        bool isEfi = false;
         if ( QDir( "/sys/firmware/efi/efivars" ).exists() )
+            isEfi = true;
+        
+        if ( isEfi )
         {
             QString espMountPoint = Calamares::JobQueue::instance()->globalStorage()->
                                         value( "efiSystemPartition").toString();
@@ -430,6 +434,38 @@
                                       message,
                                       description );
             }
+        }
+            
+        if ( !isEfi )
+        {
+            
+            cDebug() << "device: BIOS";
+            
+            Partition* bios_p = m_core->findPartitionByMountPoint( "" );
+            QString message;
+            QString description;
+
+            message = tr( "Option to use GPT on BIOS" );
+            description = tr( "A GPT partition table is the best option for all "
+                              "systems. This installer supports such a setup for "
+                              "BIOS systems too."
+                              "<br/><br/>"
+                              "To configure a GPT partition table on BIOS, "
+                              "(if not done so already) go back "
+                              "and set the partion table to GPT, next create a 8 MB "
+                              "unformatted partition with the "
+                              "<strong>bios_grub</strong> flag enabled.<br/><br/>"
+                              "An unformatted 8 MB partition is necessary "
+                              "to start %1 on a BIOS system with GPT." )
+                          .arg( Calamares::Branding::instance()->
+                                string( Calamares::Branding::ShortProductName ) );
+            
+            if ( !message.isEmpty() )
+            {
+                QMessageBox::information( m_manualPartitionPage,
+                                      message,
+                                      description );
+            }
         }
 
         Partition* root_p = m_core->findPartitionByMountPoint( "/" );
```

**Comment by abucodonosor** [comment]
Since the resulting installation is broken with such combos I would call it a bug

**Comment by mirh** [comment]
> in fact there are many advantages of using GPT on legacy BIOS too, so having it as an option is preferred imo.

~~Not as a boot disk though. Or if not any at least, not without hybrid mbr scheme.~~
Ok nvm, hybrid mbr would [only](http://www.rodsbooks.com/gdisk/booting.html) be needed if dual booting with windows. 

In this case then, I see no point in either of the two proposed ideas. 
Installing bios to gpt is totally legit (with some [exceptions](http://www.rodsbooks.com/gdisk/bios.html)) as I said. And you have #459 for that. 
As for installing uefi/esp to MBR scheme... Maybe wouldn't you just have better to offer [conversion](http://www.rodsbooks.com/gdisk/mbr2gpt.html) of disk to GPT?

You could add warnings and all, to be sure these options are what user really wants then.

**Comment by adriaandegroot** [comment]
The warning has been added, *caveat emptor*.

**Comment by mirh** [comment]
[Thanks](https://github.com/calamares/calamares/commit/b6228d137ca11353c94c784438d0f87630229b88)!
Given the warning recommendation though, should I understand GPT is also the default scheme for bios systems for automatic partitioning?

**Comment by abucodonosor** [comment]
No is not, but could be added. I think I should have a patch somewhere for that.
