### ISSUE TITLE
readonly? having an issue that says readonly but is not..

### ISSUE THREAD

**Issue by ChrisFernandez** [calamares/calamares#724]
here are two screenshoots..
![screenshot_blackarch-gui_2017-04-24_15 02 27](https://cloud.githubusercontent.com/assets/5316229/25360780/7d17d066-28ff-11e7-8d3d-55bec0b71f61.png)
![screenshot_blackarch-gui_2017-04-24_15 04 02](https://cloud.githubusercontent.com/assets/5316229/25360787/806081b4-28ff-11e7-8d26-afbcf6a9103b.png)

first one is the error then the other is the mount command, so not sure if this is complaing about the .sfs file or the destination on /tmp/calamares-*

**Comment by philmmanjaro** [comment]
Can you retry with debug mode and post the full terminal output? `sudo -E calamares -d`

**Comment by ChrisFernandez** [comment]
sure.. I'll do that as soon I get home later after work. wont need sudo because is running as root.. this is why I am puzzle...

**Comment by ChrisFernandez** [comment]
@philmmanjaro hey, here it is.. did it very fast before dinner.
![screenshot_blackarch-gui_2017-04-24_19 20 47](https://cloud.githubusercontent.com/assets/5316229/25366235/3aa4a500-2923-11e7-9adb-fc931667d219.png)

**Comment by philmmanjaro** [comment]
It is always better to have it in text form rather than screenshot.

**Comment by ChrisFernandez** [comment]
@philmmanjaro sure, here it is..

[log-calamares.txt](https://github.com/calamares/calamares/files/954311/log-calamares.txt)

**Comment by kkofler** [comment]
Looks like it tries to `rmtree` the `source_mount_path` while the source image is still mounted under it. It is getting unmounted with `umount -l` lazy unmount, so I sense a race condition.

You are also missing the `unsquashfs` tool.

**Comment by ChrisFernandez** [comment]
@kkofler hey thanks for taking a look... let me try installing unsquashfs  this may be the issue..

**Comment by ChrisFernandez** [comment]
@kkofler ok that was it, so far... it was missing that package on my live cd install.
I encounter another minor issue.... in the auto partition why does it take SO MUCH swap space? can I change the defaults for the % of size it uses for ram or dissable it?(who needs swap now a days anyways) I rather add later a fs swap if needed.

**Comment by ChrisFernandez** [comment]
Anyone have experience using calamares with archiso https://wiki.archlinux.org/index.php/Archiso ? I'm having issues now because calamares is looking for vmlinux linux kernel etc on boot but archiso does not install grub etc I belive... so now I am forced to enable network in the iso so the calamares install can download and iinstall the kernel on /boot etc.. and I am afraid Im going to have to manually somehow configure EFI stuff etc.. there is no place searching in google with an actual howto/manual of each module and how to configure it/hack it so works with different ISO buildings.. like archiso

**Comment by ChrisFernandez** [comment]
ok I have put this on the side, to busy at work will open a new ticket if I still have this issues when I get back to it.

**Comment by adriaandegroot** [comment]
Just as a double-check: you're trying to use Calamares as the installer for an Arch-derivative? Or was this while installing something that already exists and is supposed to work?

**Comment by ChrisFernandez** [comment]
@adriaandegroot and arch derivate, plus archiso tools... the way archiso tools do things and what calamares needs from it or viceversa is not very clear in the comments of the config files..so after adding calamares to the archiso so installs in the livecd, the actuall install from livecd to harddrive is what is creating problems.. seems like each distro like manjaro has its own way of working around it but there is no documentation in how and what to do it. So really where I was stuck is in the boot loader.. was driving me crazy cause Im missing something because when(Calamares)  uncommpress the image created by archiso into the HD partitions /boot is empty. etc etc. I mean I can write a new module on calamares to fill in the blanks but do not really want to have a fork of upstream.. will be hell to update later on.. so I am sure there are ways to get this working right but nobody has made a document specially for archiso installs.

**Comment by philmmanjaro** [comment]
Well, ArchISO is mounting differently than Manjaro-Tools. So we have to add ArchISO support first. Also I don't see any Arch-based Distro using **Calamares**, since there is already Antergos.
