### ISSUE TITLE
User is part of disk group

### ISSUE THREAD

**Issue by robert1826** [calamares/calamares#726]
i've installed manjaro with calamares and i noticed that when i type the command "cfdisk" there is no warning about permissions ... so i test deleting the partitions using the user privileges and i worked so the system was totally broken (the test was run in a virtual machine), then i figured out that the /dev/sdX files was owned by root and are part of "disk" group which the normal user is also part of .... so i'm wondering why the normal user was made part of "disk" group where he/she can delete all the partitions from the disk by mistake ? ... can you just not include the user in "disk" group ?

**Comment by philmmanjaro** [comment]
The Live-User has root privilege thru **sudo** without password request. This is by design. This is not a general problem. If you however see it as a problem, please use the right [bugtracker](https://bugs.manjaro.org/).

**Comment by robert1826** [comment]
thanks for the quick reply.
anyway i'm not talking about the live user ... i'm talking about the "after install" user.

**Comment by philmmanjaro** [comment]
The groups can be configured by **calamares**. The default groups are listed in **[users.conf](https://github.com/calamares/calamares/blob/master/src/modules/users/users.conf)**

**Comment by robert1826** [comment]
ok thanks.
