### ISSUE TITLE
Default size of swap file.

### ISSUE THREAD

**Issue by blazeblaze** [calamares/calamares#727]
To have a swap file twice as the amount of RAM installed as default choice is pointless nowadays. Nearly all computers come with a minimum of 4 GB RAM, and what is the point of a swap file that is 8 GB?

**Comment by demmm** [comment]
What if you want to use hibernate and are using 6-7 Gb of RAM when you start hibernate?
That is why swap is set this way.

Once you start having systems with 256 Gb RAM.......then it will be another story.

**Comment by adriaandegroot** [comment]
I've extended the documentation in that configuration file a little (see link in @demmm 's comment).

With *ensureSuspendToDisk* on, 4GiB RAM gives 8GiB swap; with it off, 4GiB swap. As @demmm  points out, if you expect to be able to suspend to disk, you need enough swap to support that, and Calamares defaults to something safe (unless the distro configures it differently).

**Comment by blazeblaze** [comment]
Thanks for the explanation. Appreciate it. Calamares has worked very well
for me so far. So thanks again.  :)

On Mon, Jun 12, 2017 at 10:24 AM, Adriaan de Groot <notifications@github.com
