### ISSUE TITLE
minimum resolution won't fit on small screen or virtuabox

### ISSUE THREAD

**Issue by mandian-lx** [calamares/calamares#731]
Hi,
in certain case lower resolution of 1010,x520 is too high for small monitor and especially  in virtualbox

https://github.com/calamares/calamares/blob/master/src/calamares/CalamaresWindow.cpp#L49

Here is an example in witch calamares doesn't fit vbox screen:

http://www.meadows.pair.com/mandriva_problem.png

A minimum resolution of 800x600 should work in all situations.

Original discussion was here:
https://forum.openmandriva.org/t/impossible-to-install-in-virtualbox-as-controls-are-off-screen

**Comment by abucodonosor** [comment]
what do you mean by 'small monitor' ? 

also I don't see how this is an calamares bug..

**Comment by adriaandegroot** [comment]
The linked Mandriva discussion shows what the problem is. For very small displays (e.g. 800x600, or the default Virtual Box screen size) the Calamares window falls outside the physical display. There's specific code in Calamares that sets the minimum window size to 1010x520. That ought to fit vertically even on a small screen, but if you've got a Plasma toolbar at the bottom, and window decorations at the top, I can see the buttons being squeezed out of view.

**Comment by mandian-lx** [comment]
I apologize I didn't explain so well but adriaandegroot get exactly the point: the problem is when small resolution (e.g. 800x600), maybe also small display (but I only tested on vbox). According to OpenMandriva developers the 800x600 window size is hard coded in vbxvideo kernel module while in Calamres  a minimum window size to 1010x520 is hard coded. This can be patched in OpenMandriva anyway it remains in all the other distros and OS and It because I wrote here.

**Comment by blackcrack** [comment]
it is maybe able to overwrite it, like the css theming,
the variable exist "size 800x600" but later if
the kernel check to be in vbox, "set up variable size => screen resolution / size =1024x768"
if behind modprobe something like

if (lsmod | grep virtualbox == virtualbox) set size=1024x768
else auto

or something ..
so it is no more hardcoded so it is setting up a vesa/svga size
what it is also possible.. or should be possible..
to change the resolution of the xserver behind it is start
and reset it up to an other , imho should it works..
and a script it is easy to handle like i think..
if something wrong can it every time changed.

or how make it they are who
use also calamares, there must be give a possible imho.

best regards
blacky
