### ISSUE TITLE
Closing and restarting issue

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#743]
There are two ways to stop calamares. One that will end calamares (and you will be able to restart) and the other (closing windows cross) that will NOT stop calamares as we can see in htop. Since it is running no other instance will be launched. You are forced to reboot or go to htop and kill the process.

Is this happening just over here?

![calamares](https://cloud.githubusercontent.com/assets/10594806/26760188/83e0488c-4912-11e7-82ff-b659fc257636.gif)

![calamares](https://cloud.githubusercontent.com/assets/10594806/26760343/bdc3e84e-4915-11e7-9de7-f786137ce893.png)

**Comment by oberon2007** [comment]
You are using openbox, right?
The thing is that on other DEs you will not have to option to close the window like this :wink:
Cinnamon here as an example:
![](http://imgur.com/0v6alAR.png)

**Comment by oberon2007** [comment]
Seems like openbox closes the window but doesn't actually quit the application. Can CAL maybe catch that the window has been destroyed?

**Comment by erikdubois** [comment]
what exactly is cal? can we fix it on the iso?

**Comment by philmmanjaro** [comment]
**CAL** is the short name for **Calamares**.

**Comment by oberon2007** [comment]
> can we fix it on the iso?

@erikdubois I don't know about openbox but in other WMs you have ways to configure window behaviour for certain applications. Like in fluxbox for example you could preconfigure the system to not show any borders or a titlebar for calamares...

**Comment by erikdubois** [comment]
thanks for trying to help - no solution found yet
