### ISSUE TITLE
RFE: Port shipped Python modules to C++

### ISSUE THREAD

**Issue by kkofler** [calamares/calamares#744]
Filing this for tracking purposes.

Since commit 00d9f211f5a90e5b21a7f3487f85147da7dff436, it is possible to use C++ also for batch job modules. It would be nice to port the modules we ship ourselves to C++ so that Python support can become truly optional. Distros would still be able to use Python for their custom modules if they prefer.

The `dummycpp` module (commit 0ae41dd286d70286e36ff8e98a23043baecaa935) and the `dracutlukscfg` module (commit d5dfe86525865f5b63e5644fde1d34a18c866650) are examples of existing C++ batch job modules.

**Comment by demmm** [comment]
This feature request is now well over 5 years old, some python modules have been ported to C++ since, no PR submitted for it otherwise, time to close.
