### ISSUE TITLE
RFE: Use PythonQt also for batch job modules

### ISSUE THREAD

**Issue by kkofler** [calamares/calamares#745]
Filing this for tracking purposes.

Calamares currently supports 2 different Python bindings:
* batch job modules use Boost::Python,
* GUI view step modules use PythonQt.

It would make things easier for packagers if only one binding system were required.

Therefore, I suggest adding batch job module support to the PythonQt module system (which would probably work similarly as for C++ modules, see commit 00d9f211f5a90e5b21a7f3487f85147da7dff436).

The transition would be easier if our own Python modules were ported to C++ first (see #744).

**Comment by adriaandegroot** [comment]
I'm curious about two things
 - is there **any** distro that uses the PythonQt bindings for something
 - is there any distro that ships PythonQt such that it can be used by Calamares?

Most distro's -- if they have PythonQt at all -- seem to be missing PythonQt "All" which are the bindings themselves. Or maybe the CMake code is way too strict and only finds stuff on Arch.

**Comment by demmm** [comment]
KaOS ships with the "All" parts enabled:
http://kaosx.tk/packages/pkg-ls.php?package=pythonqt-3.2-3-x86_64.pkg.tar.xz&subdir=main

It is not used for anything in Calamares, though the sole reason it was added to the repositories was for Calamares.

**Comment by philmmanjaro** [comment]
Also Manjaro ships with **pythonqt** enabled. For now not used at all from our end.

**Comment by jriddell** [comment]
KDE neon does have pythonqt as a build-depenends but looking at the log it's not being picked up at build time, so I guess we don't use it.
https://build.neon.kde.org/job/xenial_unstable_kde-extras_calamares_bin_amd64/254/consoleFull

05:09:23 -- Searching for PythonQt (PythonLibs 3.5) ..
05:09:23 --   .. found include /usr/include/PythonQt
05:09:23 --   .. found library optimized;/usr/lib/libPythonQt.so;debug;/usr/lib/libPythonQt.so
05:09:23 -- PythonQt not found, missing components qtall
05:09:23 -- Disabling PythonQt modules

**Comment by adriaandegroot** [comment]
jriddell: Neon only has PythonQt base. It is missing the QtAll component, so you need /usr/lib/libPythonQtAll.so as well -- see e.g. KaOS package listed above, or Manjaro.

On the other hand, existing (Boost) Python job modules should be able to run with just the base libraries, I think. Something to experiment with. Regardless, having the same API available for Python modules independent of their embedding mechanism is a good thing.

**Comment by adriaandegroot** [comment]
@jriddell In any case the thing is moot, since Neon's PythonQt seems to be Python 2.7 based, and Calamares wants Python3 -- so even if it **could** find PythonQt, it would probably crash in "interesting" ways.

**Comment by adriaandegroot** [comment]
@jriddell libpythonqt3.0 xenial plus libpythonqt-dev seems to do the trick; but that still only provides libPythonQt, not libPythonQt_All which is the actual Qt binding bits.

I think it would make sense to do the following:
 - if PythonQt_All is available, then run all the Python modules (both jobs and view modules) through PythonQt
 - else if Boost::Python is available and PythonQt is not, then run the Python job modules through Boost::Python (view modules are not supported)
 - else if PythonQt is available, then run the Python job modules through PythonQt (view modules are not supported)

This reduces the "binding load" to just one kind of embedded Python, and means that the "next generation experimental" API can run all the previous-generation (e.g. Python Job modules) as well. Any other Python embedding in Calamares (for instance, I hear that PyQt also can work as embedded scripting engine) would have to support the same set of scripts.

**Comment by adriaandegroot** [comment]
See branch update-python.

**Comment by adriaandegroot** [comment]
Taking this off the milestone, since (a) it's still a lot of work and (b) I wonder if the PythonQt stuff is worth it. In Calamares proper there is only the one dummy module and I have not heard of any downstreams using PythonQt modules. I think there's more mileage to be had from doing a QML module instead of putting in the hours to support something unused.

**Comment by adriaandegroot** [comment]
Closing this as "PythonQt has gotten no meaningful uptake and is still stuck in *experimental* mode; no modules are known to use it." In addition, I think moving to QML for quick-yet-slick UI parts within Calamares makes much more sense than maintaining two sets of Python bindings. I expect PythonQt support to be removed in the 3.3 series.

That said, I **did** do a lot of work to be able to run Job modules using the PythonQt bindings; in the end, though, I don't think it is worth it. There were branches "update-python" and "fix-pythonqt" which worked on the problem, but never really finished.
