### ISSUE TITLE
LUKS encryption during install results in very slow LUKS decryption on boot

### ISSUE THREAD

**Issue by karlo12** [calamares/calamares#746]
Hi! I did install Manjaro Linux about four weeks ago with the latest iso available then (Manjaro 17.0) using a modern Thinkpad with SSD. and I think I encountered a Calamares bug. I did a full disk encryption using the whole disk with no other OS installed. But when I decrypt LUKS during boot now it takes a lot of time (~27 seconds). Maybe the encryption parameters in Calamares could be improved to solve this issue.

I did read about it in the Manjaro forum:
https://forum.manjaro.org/t/very-slow-disk-decryption-at-boot/19856/27

So it may be a problem with the encryption during install after boot and the decryption in Grub being different environments.

... And maybe also related: https://bbs.archlinux.org/viewtopic.php?id=217193

Thanks for helping solving this.

**Comment by stikonas** [comment]
Could be that your distribution compiles GRUB without AES-NI support.

**Comment by stikonas** [comment]
Looks like for some reason /boot unlock happens very slowly in GRUB. Thus I think it is not calamares issue but grub issue. I use this encrypted /boot setup but somehow grub unlocks it reasonably quickly, (1 or 2 seconds, definitely not 27)

Maybe post your iteration counts from cryptsetup luksDump /dev/sda# and also speeds reported by cryptsetup benchmark (even though this is different environment, GRUB uses its own code to unlock).

**Comment by karlo12** [comment]
Is the reason the encrypted /boot or /root then, really? I used different distros (e.g. Mint) with full disk encryption and had way shorter decryption times, too. More like 1-3 seconds. Calamares starts with two Key slots in Manjaro 17.0 though. What is that about? I will ask that in the Manjaro forum, too.

My settings+benchmarks are:

> 
> sudo cryptsetup luksDump /dev/sda2
> LUKS header information for /dev/sda2
> 
> Version:        1
> Cipher name:    aes
> Cipher mode:    xts-plain64
> Hash spec:      sha256
> Payload offset: 
> MK bits:        
> MK iterations:  135500
> UUID:           
> 
> Key Slot 0: ENABLED
>         Iterations:             1120349
>         Salt:                   
>         Key material offset:    8
>         AF stripes:             4000
> Key Slot 1: ENABLED
>         Iterations:             1186556
>         Salt:                   
>         Key material offset:    512
>         AF stripes:             4000
> Key Slot 2: DISABLED
> Key Slot 3: DISABLED
> Key Slot 4: DISABLED
> Key Slot 5: DISABLED
> Key Slot 6: DISABLED
> Key Slot 7: DISABLED
> 
> 
> cryptsetup benchmark
>  Tests are approximate using memory only (no storage IO).
> PBKDF2-sha1      1075462 iterations per second for 256-bit key
> PBKDF2-sha256    1257285 iterations per second for 256-bit key
> PBKDF2-sha512     983654 iterations per second for 256-bit key
> PBKDF2-ripemd160  819200 iterations per second for 256-bit key
> PBKDF2-whirlpool  571742 iterations per second for 256-bit key
>      Algorithm | Key |  Encryption |  Decryption
>         aes-cbc   128b   561,5 MiB/s  2447,3 MiB/s
>     serpent-cbc   128b    51,4 MiB/s   464,2 MiB/s
>     twofish-cbc   128b   152,1 MiB/s   304,1 MiB/s
>         aes-cbc   256b   412,7 MiB/s  1833,2 MiB/s
>     serpent-cbc   256b    73,7 MiB/s   479,3 MiB/s
>     twofish-cbc   256b   157,8 MiB/s   302,9 MiB/s
>         aes-xts   256b  2002,8 MiB/s  2090,5 MiB/s
>     serpent-xts   256b   481,2 MiB/s   466,9 MiB/s
>     twofish-xts   256b   288,5 MiB/s   286,3 MiB/s
>         aes-xts   512b  1539,3 MiB/s  1585,9 MiB/s
>     serpent-xts   512b   465,1 MiB/s   465,0 MiB/s
>     twofish-xts   512b   294,3 MiB/s   301,1 MiB/s

**Comment by stikonas** [comment]
Yeah, Calamares encrypts /boot, so kernel and initramfs are also encrypted, so this setup is more secure. I use the same setup (although not with calamares, I just manually set it up so).

Your iteration count is about four times larger than mine, so maybe that's why I don't notice slow down. Although, it still wouldn't explain 27x slowdown...

Two key slots are necessary for automatic decryption in initramfs. When grub unlocks /boot partition, kernel loads but when kernel starts it has to unlock that LUKS partition itself, there is no way to pass master key to kerel and keep partition unlocked. So a second LUKS slot with keyfile is added and key is stored in initramfs (which is located in encrypted /boot). This allows to avoid entering password twice. In principle, that second slot doesn't need large iteration count (since keyfile is long, no way to brute force it anyway). But this second slot is not what is slowing your boot down. Grub only uses that first slot.

**Comment by adriaandegroot** [comment]
Closing on the basis of this discussion (points at grub) and being told on IRC that this falls outside of Calamares scope.
