### ISSUE TITLE
Crash on start on Wayland

### ISSUE THREAD

**Issue by jriddell** [calamares/calamares#747]
Using KDE neon Dev Unstable ISO from today Calamares crashes if you try to start it when running a Wayland session.

This is probably because Wayland doesn't like stuff running as root.

**Comment by adriaandegroot** [comment]
Wayland's stance "no GUI application may be setuid" is really annoying for applications that need to be (for various reasons) root. pkgexec is not sufficient as a workaround.

This is a workaround:
    sudo touch /etc/foo
    SUDO_EDITOR=konsole sudoedit /etc/foo
    (in resulting konsole) calamares -d

If Wayland continues its no-possible-root stance, then there's not much else to do than either declare Cala X11-only (the easy way out) or start the long and tedious process of moving the bits that need root into helper processes.

**Comment by demmm** [comment]
Calamares has been used in KaOS for about a year now in Wayland sessions, with no issues as reported above.  Does the crash occur on starting with pkgexec? Here it is always started with `sudo calamares -d`

**Comment by adriaandegroot** [comment]
@demmm Can you do "sudo xterm" (assuming xterm is installed in your distro)? There has been much discussion about Wayland + setuid-root applications, and the general line is "they won't work." But that's with current(-ish) Wayland.

@jriddell xhost + ; sudo calamares -d does do the trick on that KDE Neon release

**Comment by demmm** [comment]
@adriaandegroot 
`sudo xtern` runs fine in a Wayland session.  Just in case needed, latest versions used, Qt 5.9.0, Frameworks 5.35.0, Plasma 5.10.2.

**Comment by stikonas** [comment]
You can start root apps on Wayland too. E.g. KDE Partition Manager can successfully run on wayland as it sets the following environmental variables DBUS_SESSION_BUS_ADDRESS, KDE_FULL_SESSION, QT_WAYLAND_FORCE_DPI, QT_QPA_PLATFORM, XDG_RUNTIME_DIR

See https://cgit.kde.org/partitionmanager.git/tree/src/util/guihelpers.cpp#n67 for implementation details.

**Comment by abucodonosor** [comment]
That seems to be sort Distro issues too also ..

**Comment by demmm** [comment]
This is a very old issue.  Wayland use is now widespread, closing since no reports received since 2017.
