### ISSUE TITLE
Libpythonqt error

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#748]
Tried building an iso today - sudo calamares ends up with message
calamares : error while loading shared libraries : libPythonQt.so.1 : cannot open shared object file : no such file or directory

any idea in what direction I have to look to solve this

**Comment by demmm** [comment]
That means you need to rebuild Calamares on new used PyhtonQt (3,2), .so change in that version.

**Comment by erikdubois** [comment]
thanks
will do that now
