### ISSUE TITLE
Calamares build incompatible with PythonQt 3.2

### ISSUE THREAD

**Issue by jghodd** [calamares/calamares#749]
PythonQt-3.2 changes library names from libPythonQt.so.1.0.0 and libPythonQt_QtAll.so.1.0.0 to libPythonQt-Qt5-Python3.so.3.2.0 and libPythonQt_QtAll-Qt5-Python3.so.3.2.0, respectively. The FindPythonQt cmake can no longer find the pythonqt library, and the executable from the build (which notes that it cannot find PythonQt) crashes with an error that libPythonQt.so.1.0.0 could not be found.

**Comment by demmm** [comment]
Discussion regarding name changes & patches:
https://sourceforge.net/p/pythonqt/discussion/631392/thread/b4311a4b/

**Comment by jghodd** [comment]
Attached is a patch for pythonqt-3.2

[pythonqt-3.2.patch.txt](https://github.com/calamares/calamares/files/1082744/pythonqt-3.2.patch.txt)

**Comment by philmmanjaro** [comment]
Bumping to minimum version **v3.2** is missing in your patch. Take a look at this one: https://github.com/manjaro/calamares/commit/9b9789d299ece78c61c040c0b0c935eac22e11f7

**Comment by jghodd** [comment]
Thanks, philmmanjaro. Looks good. I'll apply that one too.

**Comment by jghodd** [comment]
Here's the new patch file for both CMakeLists.txt and CMakeModules/FindPythonQt.cmake:
[pythonqt-3.2.patch.txt](https://github.com/calamares/calamares/files/1083200/pythonqt-3.2.patch.txt)

**Comment by kkofler** [comment]
Can't we support both the old and the new version? Or do you expect all distros to have 3.2 already?

(I am not building the Fedora/Kannolo package with PythonQt support at this time, so I don't really care, but other distros may be affected.)

**Comment by philmmanjaro** [comment]
@kkofler: yes, it should be possible. Thought of it also. Having **v3.1** as minimum, but also support higher versions of **v3.2+** ...

**Comment by philmmanjaro** [comment]
Here we go for the proper patch: 
[cal-python-qt-32-v3.patch.txt](https://github.com/calamares/calamares/files/1083335/cal-python-qt-32-v3.patch.txt)

**Comment by jghodd** [comment]
That works. Will use the 3.1/3.2 patch.

**Comment by philmmanjaro** [comment]
@adriaandegroot: should I push it the patch to **master** and close this one?

**Comment by jghodd** [comment]
If everyone else is good with it, sure. It works fine with both versions (tested) and fixes the issue.

**Comment by adriaandegroot** [comment]
@philmmanjaro looks good to me, so please do
