### ISSUE TITLE
Calamares theming - use different theme than desktop environment

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#752]
Is it possible to tell calamares to take a different theme like arc-theme and use theme B for the rest of the system?

**Comment by kkofler** [comment]
Pass `-style arc-theme` to calamares in the `.desktop` file.

**Comment by erikdubois** [comment]
wow that would be awesome

**Comment by erikdubois** [comment]
unfortunately it will not work
. desktop file is now
Exec= sudo calamares -style Arc-Dark
no solution still takes the standard theme

then  I opened a terminal and tried these combinations
sudo calamares --style Arc
sudo calamares -style Arc
sudo calamares --style Arc-Dark
sudo calamares -style Arc-Dark
sudo calamares -style Bright
sudo calamares --style Bright

calamares does not change and will continue to use the theme set by the system.

Can you assist please...

**Comment by erikdubois** [comment]
I just found something that might help
in terminal after running
sudo calamares -style Arc-Dark
i get this message
![calamares](https://user-images.githubusercontent.com/10594806/27479445-4372df92-5814-11e7-84dd-33dfdb47c134.jpg)

**Comment by philmmanjaro** [comment]
Since you use **qt5ct** on your system, the style is managed by this application.

**Comment by erikdubois** [comment]
meaning....

**Comment by philmmanjaro** [comment]
... `invalid style override passed, ignoring it.`

**Comment by erikdubois** [comment]
sorry but what i am supposed to do

**Comment by erikdubois** [comment]
ok i catfished on qt5ct 
i have a folder in my etc/skel.config i can delete and see if that helps...
what do you think?

**Comment by oberon2007** [comment]
Would it maybe be an option to call calamares with an environment variable override for `QT_QPA_PLATFORMTHEME` ?
Removing qt5ct config will remove theming for all qt ... I assume you are in a gtk environment?

**Comment by oberon2007** [comment]
What does `echo $QT_QPA_PLATFORMTHEME` say? qt5ct?

**Comment by erikdubois** [comment]
on my system it says qt5ct
virtualbox iso says same

**Comment by oberon2007** [comment]
something like
`env QT_QPA_PLATFORMTHEME=theme-name sudo -E calamares`
might work.
Or you could also consider to simply configure qt5ct differently for root 😉

**Comment by erikdubois** [comment]
Oh that works fine
put that line in the .desktop file?
this would be awesome

**Comment by oberon2007** [comment]
hm. it doesn't work entirely I'm afraid. passing QT_QPA_PLATFORMTHEME= seems to work, but it doesn't take a theme name, only a platform name...
At least you can achieve default qt theme like that 😉 
maybe there's still a way to pass a proper qt style, I don't know. I'm not very much at home with QT environment 😜

**Comment by erikdubois** [comment]
do not be too modest
it works!
archlabs will have calamares with a nice Arc-Dark theme thanks to you
thank you very much

**Comment by oberon2007** [comment]
Cool. For me it doesn't work 😆 What exactly did you put in your launcher now literally if I may ask?

**Comment by erikdubois** [comment]
[Desktop Entry]
Type=Application
Name=Install ArchLabs
Comment=Installer for ArchLabs
Categories=Utility;
Exec=env QT_QPA_PLATFORMTHEME=Arc-Dark sudo -E calamares
Icon=al-calamares

**Comment by erikdubois** [comment]
![2017-06-23--1498218917_3840x1080_scrot](https://user-images.githubusercontent.com/10594806/27481479-1058c0be-581d-11e7-9af2-e9c1214ac7ae.png)
Thanks again

**Comment by oberon2007** [comment]
Great that is works for you - no idea why I can't reproduce it here... 🤣

**Comment by erikdubois** [comment]
computers.... hope it stays this way
