### ISSUE TITLE
[Travis-CI] Updated Trusty images breaking our tests

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#753]
I've managed to add a [workaround](https://github.com/calamares/calamares/commit/ea8b6c8ba8b965c7985e1a44d1cb49941819a708) until September 1st to our **master** branch. However, we should check why [newer GCEs](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch) create [issues on our end](https://travis-ci.org/calamares/calamares/builds/246043536?utm_source=github_status&utm_medium=notification):

```
0.38s$ docker run -v $PWD:/build calamares bash -lc "cd /build && cmake -DWEBVIEW_FORCE_WEBKIT=1 -DKDE_INSTALL_USE_QT_SYS_PATHS=ON . && make -j2"
CMake Error at /usr/share/cmake-3.5/Modules/CMakeDetermineSystem.cmake:184 (file):
  file failed to open for writing (No such file or directory):
```

**Comment by adriaandegroot** [comment]
More a consequence of updated docker, somewhere, changing the permissions on -v bind-mounts to read-only. I've added a tmpfs for the build artifacts now, which solves the issue (and introduces out-of-source builds, too).
