### ISSUE TITLE
lightdm session defaults on i3 after installation

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#754]
ArchLabs has been working great with calamares. But next release we are going to include i3wm besides openbox.
I have been looking for the net now for several days and then it hit me, I have to ask the question here.
When the live cd loads, it autologins liveuser. If we logout, lightdm session (top right icon) is set to default openbox. But after installation of ArchLabs (and calamares) the lightdm session has changed to i3. 
We do want openbox still to be the default session for any user to start with.
Is there any module that might be responsible for this behaviour.
![modules](https://user-images.githubusercontent.com/10594806/27512448-457bf986-5940-11e7-8aca-027acca1fb8e.jpg)
These are in /usr/lib/calamares/modules
And these are in /etc/calamares/modules.
![etc](https://user-images.githubusercontent.com/10594806/27512452-6ade9044-5940-11e7-8ced-f6e54897fcc3.jpg)
Further detail can be provided if calamares somehow can be responsible for changing the lightdm default session.
Thanks in advance.

**Comment by adriaandegroot** [comment]
Usually that is part of the lightdm configuration, right? (I'm not familiar with lightdm myself) So check that the lightdm config files on the live FS and on the installed FS make sense. You don't seem to have the displaymanager module in calamares enabled, so it probably is not doing anything with the files you need.

But if you *did* have the DM module in Calamares, the most likely candidate is the `defaultDesktopEnvironment` setting.

**Comment by erikdubois** [comment]
unfortunately it did not work
I added displaymanager.conf with these lines

displaymanagers:

-lightdm

then once with 

basicSetup: false

and once with 

basicSetup: true

Every installation goes fine. But after reboot "something" changes the line in /etc/lightdm/lightdm.conf from

user-session=openbox
to
user-session=i3

So if you used automatic login - you have openbox after reboot
If you used no automatic login (session default on right top) is set to i3 for default and people logging in will get a scare as they will be logged in with i3.

I can not get my head around it.

What can cause this behavior?

**Comment by erikdubois** [comment]
is there a way in calamares to run a command only after the installation and upon rebooting
to change (sed command)

user-session=i3
to
user-session=openbox

**Comment by philmmanjaro** [comment]
It would be easier if you read the [displaymanager.conf](https://github.com/calamares/calamares/blob/master/src/modules/displaymanager/displaymanager.conf) and set there your default session :smile_cat:

**Comment by philmmanjaro** [comment]
Since [i3](https://github.com/calamares/calamares/blob/master/src/modules/displaymanager/main.py#L50) is found before **openbox**, **displaymanager** will set that by default, when not `defaultDesktopEnvironment:` function is set properly. By default, this function is commented.

**Comment by erikdubois** [comment]
Thanks for helping 
This solved the issue of i3 becoming the default session rather than openbox

`---
#The DM module attempts to set up all the DMs found in this list, in that precise order.
#It also sets up autologin, if the feature is enabled in globalstorage.
#The displaymanagers list can also be set in globalstorage, and in that case it overrides anything set up here.
displaymanagers:

  - lightdm


#Enable the following settings to force a desktop environment in your displaymanager configuration file:
defaultDesktopEnvironment:openbox
executable: "openbox-session"
desktopFile: "openbox"

#If true, try to ensure that the user, group, /var directory etc. for the
#display manager are set up correctly. This is normally done by the distribution
#packages, and best left to them. Therefore, it is disabled by default.
basicSetup: false`

**Comment by erikdubois** [comment]
not sure however if these lines are necessary
executable: "openbox-session"
desktopFile: "openbox"
