### ISSUE TITLE
Autologin is not applied upon reboot when selected during installation

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#755]
ArchLabs boots automatically into openbox with user "liveuser". Calamares starts automatically.
We leave autologin on during installation. After rebooting we end up at the login screen because /etc/lightdm/lightdm.conf has still **liveuser** as autologin.
[Pastebin to lightdm.conf](https://pastebin.com/VBbzY32K)
I reported another issue today #754 and we solved that one with adding a new configuration file to the calamares modules. This currently my setting. [Pastebin to displaymanager.conf](https://pastebin.com/rtiwNTXU). Since I have been trying for 5 hours to make sense of it. Changing and reverting back to previous versions, I wonder if there is a correlation between solving previous issue resulting in this new issue? Issue 754 is still solved at this moment. Openbox stays the default login sesseion. What are your thoughts on the matter?
All files can be found here [github](https://github.com/ARCHLabs/Archlabs-Iso)

**Comment by erikdubois** [comment]
Read this code to get get my head around it.
[calamares](https://github.com/calamares/calamares/blob/master/src/modules/displaymanager/main.py)
Line 277 should take care of it.
Permission issues?

**Comment by philmmanjaro** [comment]
First of all: which version of **CAL** do you use? [v3.1.1](https://github.com/calamares/calamares/releases/tag/v3.1.1) is the current stable release. I just did some tests with our release **v17.0.2** of Manjaro, which also uses **lightdm** in some of our editions. Autologin works there. CAL-Module configs should not affect **/etc/lightdm/lightdm.conf** at all.

**Comment by adriaandegroot** [comment]
There is an effect if you have the user page module selected, and the user checks the autologin field, or fills in a username there. It does not look like the cross-dependency is very well-documented.

**Comment by erikdubois** [comment]
I am running on calamares 3.1.0.

**Comment by philmmanjaro** [comment]
@erikdubois: please update to the latest release.

**Comment by erikdubois** [comment]
3.1.1 are all language corrections [link](https://github.com/calamares/calamares/compare/v3.1.1...master)

**Comment by philmmanjaro** [comment]
Either use **git** or the tarballs we release. It doesn't matter. Translations will be pulled on daily basis and should not affect the code.

**Comment by erikdubois** [comment]
where is this github you did this test on
i would like to compare code
thanks

**Comment by philmmanjaro** [comment]
Be more precise. [calamares-git](https://github.com/calamares/calamares/archive/master.zip), [calamares v3.1.1](https://github.com/calamares/calamares/archive/v3.1.1.zip).

On Manjaro side we have a fork of **Calamares** including some of our own modules and patches. There we have also some PKGBUILDs to use either the [git version](https://github.com/manjaro/packages-extra/tree/master/calamares-git) or [stable release](https://github.com/manjaro/packages-extra/tree/master/calamares).

It always depends which source code you use on your end currently to that we released upstream. We always assume you either complain against the current **master** code or the latest stable release of **CAL**, which is currently **v3.1.1**, we might announce properly in the coming days.

**Comment by erikdubois** [comment]
Build from this source
https://raw.githubusercontent.com/manjaro/packages-extra/master/calamares/PKGBUILD

**Comment by erikdubois** [comment]
Building 3.1.1 now from same source

**Comment by erikdubois** [comment]
I guess i have stable

**Comment by philmmanjaro** [comment]
@erikdubois: Don't get me wrong, but you use a modified **CAL** source for **Manjaro** and not the upstream sources when you use my **PKGBUILDs**. We added some modifications to **CAL**, as we use **Manjaro-Tools** to compile our ISOs and not **ArchISO**.

This would only make sense when your distro is based on Manjaro. Binary packages got released today, since I'm currently building ISOs for **v17.0.2** release of Manjaro.

So you may compare [CAL v3.1.1 (manjaro)](https://github.com/manjaro/calamares/archive/aea947a517086b4938e3a3d72de1fd9e0e332a2a.zip) against [CAL v3.1.1 (upstream)](https://github.com/calamares/calamares/archive/v3.1.1.zip) and precise your issue with the current code in more detail, so we may help you.

**Comment by erikdubois** [comment]
ok new iso build on basis of 3.1.1
still end up on the login screen with autologin selected and autologin-user in the lightdm.conf is still liveuser

**Comment by erikdubois** [comment]
I will try to give you more detail.
