### ISSUE TITLE
lightdm greeter not configured

### ISSUE THREAD

**Issue by oberon2007** [calamares/calamares#756]
It turns out that [the condition](https://github.com/calamares/calamares/blob/master/src/modules/displaymanager/main.py#L449) we introduced a while ago to configure **lightdm-deepin-greeter** is apparently not met any longer.
Today I built a Manjaro Deepin ISO and on the targt install **lightdm.conf** is unconfigured while I would expect the displaymanager module to set `greeter-session=lightdm-deepin-greeter` when **/usr/bin/startdde** is present.
Apart from that, since there are more than two different greeters possible for lightdm like for example **slick-greeter** I suggest that in order to detect the correct lightdm greeter to configure we change strategy and check for greeter launchers present in **/usr/share/xgreeters** instead of DE launcher  - similar to what [**manjaro-architect does**](https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-desktop.sh#L238)

**Comment by philmmanjaro** [comment]
You may add some debug lines to the python file on your ISO to see if the routine is working.

Example: `libcalamares.utils.debug("kdm selected but not installed")`

Also it would be good to actually link to the **manjaro-architect** code, to showcase what you mean :smile:

**Comment by oberon2007** [comment]
OOps, 😜 here, like that:
https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-desktop.sh#L238

**Comment by oberon2007** [comment]
Ok. I found the issue with deepin. It's simply an extra whitespace that makes the `sed` ineffective 😉 
I'll send a PR.
Regarding slick-greeter and possible other lightdm greeters I'll try to come up with something proper... :)

**Comment by philmmanjaro** [comment]
The issue was introduced by this: https://github.com/calamares/calamares/commit/f9695cabac242fbbbaad790b7e1a9bfcf590ab7b
