### ISSUE TITLE
Wrong chmod

### ISSUE THREAD

**Issue by pavroo** [calamares/calamares#760]
Hi
Calamares 3.1 and 3.1.1 sets current and parent dirs with wrong chmod 777 on SparkyLinux.
The base system (Debian stable Stretch & testing Buster as well) used to create live, and the live system have set chmod 755.
To make sure I don't waste your time, I used older, Yad based installer and the chmod of the two dirs are fine.
The screenshot of just system installed via Calamares 3.1.1 
![sparky-20170705-calamares311](https://user-images.githubusercontent.com/4991910/27882946-0c4388f4-61cf-11e7-8914-65bf6a7952d2.png)

**Comment by philmmanjaro** [comment]
Be more precise. You mean the **initrd** images or a folder like **tmp**?

**Comment by adriaandegroot** [comment]
It *looks* like / has 0777 permissions in that screenshot. But is the permission set correctly in the squashfs that you extract to the drive? I don't think Calamares actually chmod's much in the target filesystem except for DM config files.

**Comment by pavroo** [comment]
It quite strange, but the live system has / set to 0755 but squashfs to 0777.
Calamares copies the mounted squashfs with the same chmod, but my old installer copies the live system, that's why different. 
So can be closed, not Calamares related.

**Comment by adriaandegroot** [comment]
Thanks for following up.
