### ISSUE TITLE
Wrong SWAP UUID

### ISSUE THREAD

**Issue by pavroo** [calamares/calamares#761]
The latest Calamares 3.1 and 3.1.1 sets wrong swap uuid on SparkyLinux (Debian stable & testing based).
![sparky-20170705-calamares311-swap](https://user-images.githubusercontent.com/4991910/27883253-37827e84-61d0-11e7-87a9-bf04826fd65c.png)
Used old, yad based installer sets it ok.

**Comment by philmmanjaro** [comment]
Can you provide a full installation log via `sudo -E calamares -d`?

**Comment by adriaandegroot** [comment]
Quick test doesn't reproduce (Cala master, running in a Neon VM w/ a second virtual dist attached, so not necessarily comparable). Phil asks for a full install log because then you can see this (the UUIDs Calamares finds and writes to disk).


```
03:55:35 [1]: Gathering UUIDs for partitions that exist now. 
03:55:35 [1]: QHash(("/dev/sdb2", "4373402b-346e-4cee-9551-7c5f99fae0b7")("/dev/sdb1", "157d4348-edd8-4efc-bd8c-699c2ed7baa4")) 
03:55:35 [1]: Writing to GlobalStorage["partitions"] 
03:55:35 [1]: "/dev/sdb1" mtpoint: "/" fs: QVariant(QString, "ext4") "157d4348-edd8-4efc-bd8c-699c2ed7baa4" 
03:55:35 [1]: "/dev/sdb2" mtpoint: "" fs: QVariant(QString, "linuxswap") "4373402b-346e-4cee-9551-7c5f99fae0b7" 
```

**Comment by pavroo** [comment]
Found a problem already, not Calamares related.
Sorry to bother you, and thank's for quick respond.
