### ISSUE TITLE
Crashes with "blkid: unkown file system type"

### ISSUE THREAD

**Issue by psamim** [calamares/calamares#764]
Hi,

I was trying to install Manjaro. I got this and then a `Segmentation fault`:

```
blkid: unkown file system type "" on "/dev/sda2"
```

Then I ejected the CD which was unknowingly in the CD drive and the error is gone.
Inserting it back into the CD drive makes calamares crash again.

Thanks

**Comment by adriaandegroot** [comment]
Can you provide a full log of the install? Start a konsole from the Manjaro live system, then run `sudo calamares -d` in that konsole, so that the log is dumped in the konsole.

Also, which Manjaro download? On real hardware, or virtual hardware?

**Comment by psamim** [comment]
I am installing on a real hardware. 
I am not sure if I can reproduce the error log as I changed the partitions and installed Manjaro.

**Comment by adriaandegroot** [comment]
Can't reproduce.
