### ISSUE TITLE
Select locale format based on system language

### ISSUE THREAD

**Issue by es20490446e** [calamares/calamares#767]
HOW TO REPRODUCE:

1. On the Manjaro bootloader screen, select Spanish from Spain as language. And Spanish as keyboard layout method.

2. Launch the Manjaro image, and proceed with installation. Till the location selection screen (the one with a map to choose your location).

RESULT:

- The map shows "Berlin" as default location, were it would be "Madrid" (capital of Spain).

**Comment by philmmanjaro** [comment]
Location detection is GeoIP based. Currently we are working on a [locale format based guessing](https://github.com/calamares/calamares/commit/88715b9a0fbf8a77104408b1e37d68762dc63d87). You can test it with our **calamares-git** package. Give us your feedback if that works better for you in that regard.

**Comment by es20490446e** [comment]
Many thanks. I will test you and let you know!

**Comment by adriaandegroot** [comment]
Basically a dup of #713 

Yes, es_ES will often mean Spanish, in Spain, but if you're installing a machine for yourself while in Caracas, Madrid is equally useless as Berlin for the timezone default. Languages without country-modifiers (e.g. Danish) are spoken across many timezones and locations, so this isn't doable in a sensible way (unless someone else comes up with some nice PR that guesses location based on locale).
