### ISSUE TITLE
Calamares not able to see virtual drive under Virt manager

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#768]
Hello, I'm copying this bug report I just received:

-----------------------------------

https://github.com/geckolinux/geckolinux-project/issues/43
> I am testing out Gecko linux using Virtmanager under Leap 42.2 and for some reason the Calamares installer cannot see the virtual machine drive i set up. Gparted within the iso can see it and was able to create a partition table and a partition but alas when i go to try an install it i get nothing in the option for drives and if i chose automatic, the installer crashes without any error.
> 
> I can see and manage the Virtual drive via YAST > Partition Manager just fine.
> 
> Here is a copy of the log.
> 
> http://paste.opensuse.org/34633383

**Comment by demmm** [comment]
What version of kpmcore is in use?

**Comment by jcfrosty** [comment]
This is fixed in latest version of KPMcore 3.1.2

**Comment by adriaandegroot** [comment]
I'm going to close this based on the comment from @jcfrosty ; there's a crash in that OpenSUSE paste, which looks like it might be the libparted-race I fixed for #782.

(Milestone 3.1.3 means it's in the release called "3.1.4", coming out soon)
