### ISSUE TITLE
calamares freezing on 83% (Swag-Arch)

### ISSUE THREAD

**Issue by star-buck** [calamares/calamares#775]
http://distrowatch.com/weekly.php?issue=20170807#swagarch

**Comment by philmmanjaro** [comment]
@star-buck: this has to do with a 3rd-party module: _The status bar in the installer indicated it froze while "Running mrpacman operation"._ CAL is fine in that regard. Needs to be addressed @ swagarch

**Comment by demmm** [comment]
Tol clarify, this is the distro specific module where it fails:
https://github.com/SwagArch/calamares-configs/blob/master/src/modules/mrpacman/main.py

Possible fail can already be `pacman -Syyu`. without it checking if there is an internet connection.

**Comment by adriaandegroot** [comment]
@memoryleakx should probably be notified, but I don't see an issue tracker or easy way to contact him. The check for internet connectivity was recently removed from the module, so it does look like a downstream configuration problem, not an upstream Calamares thing at all.

I'm going to try installing SwagArch once, just to see what happens, and then close this.

**Comment by star-buck** [comment]
okay to close then.
its just irking that the distrowatch article didnt differentiate that much (and i dont blame them) so people could think its a calamares related issue.

**Comment by adriaandegroot** [comment]
Reported downstream.
