### ISSUE TITLE
Review BTRFS branch

### ISSUE THREAD

**Issue by lisamccoy** [calamares/calamares#777]
Seems Teo did some for BTRFS in 2016. Maybe we should review that [branch](https://github.com/calamares/calamares/commits/btrfs) and check if that is still useful.

**Comment by kkofler** [comment]
These changes have already been merged into master.
https://github.com/calamares/calamares/commit/e9ecb64a360e466e55baf146fb24b3e17b0c5747
https://github.com/calamares/calamares/commit/a9d8107b3b4b13fa37aff4ef62bd4291463fc183
