### ISSUE TITLE
install part of packages modules does not really work

### ISSUE THREAD

**Issue by abucodonosor** [calamares/calamares#781]
with a simple configuration file like this 

```
operations:
  - install:
      - real_package1
      - real_package2
```

I get lots python 'string indices must be integer' .. errors.

Also pre-* and post-* targets give the same errors

Backend used is pacman.

Guess something around this line ?

https://github.com/calamares/calamares/blob/master/src/modules/packages/main.py#L212

Also using just pkgman.install(entry[key]) seems to work.

Regards

**Comment by philmmanjaro** [comment]
Please post your full config file and also the error you get for review.

**Comment by abucodonosor** [comment]
Error is this 

```
<class 'TypeError'>
string indices must be integers
Traceback:
  File "/usr/lib/calamares/modules/packages/main.py", line 219, in run
    run_operations(pkgman, entry)

  File "/usr/lib/calamares/modules/packages/main.py", line 159, in run_operations
    pkgman.run(package["pre-script"])
```

and I get that with any config file .. this one was produced with just 'bash' package.

```
[root@fvbe modules]# cat packages.conf
---
#
# Which package manager to use, options are:
#  - packagekit  - PackageKit CLI tool
#  - zypp        - Zypp RPM frontend
#  - yum         - Yum RPM frontend
#  - dnf         - DNF, the new RPM frontend
#  - urpmi       - Mandriva package manager
#  - apt         - APT frontend for DEB and RPM
#  - pacman      - Pacman
#  - portage     - Gentoo package manager
#  - entropy     - Sabayon package manager
#
backend: pacman

update_db: false

#
# List of maps with package operations such as install or remove.
# Distro developers can provide a list of packages to remove
# from the installed system (for instance packages meant only
# for the live system).
#
# A job implementing a distro specific logic to determine other
# packages that need to be installed or removed can run before
# this one. Distro developers may want to install locale packages
# or remove drivers not needed on the installed system.
# This job will populate a list of dictionaries in the global
# storage called "packageOperations" and it is processed
# after the static list in the job configuration.
#
#operations:
#  - install:
#      - pkg1
#      - pkg2
#  - remove:
#      - pkg3
#      - pkg4
#  - try_install:   # no system install failure if a package cannot be installed
#      - pkg5
#  - try_remove:    # no system install failure if a package cannot be removed
#      - pkg2
#      - pkg1
#  - install:
#      - pkgs6
#      - pkg7
#  - localInstall:
#      - /path/to/pkg8

operations:
  - install:
      - bash
[root@fvbe modules]# 
```
Also with the same config it does work when you comment out this

```

            if isinstance(entry[key], list):
                for package in entry[key]:
                    pkgman.run(package["pre-script"])
                    pkgman.install([package["package"]])
                    pkgman.run(package["post-script"])

**Comment by adriaandegroot** [comment]
This has been severely re-written; the package list could contain two things: package names (string), or package-dicts with pre- and post- script data and a package name. The config file still needs more docs, and tests need to be added to check that this stuff works (also on multiple locales) (and with netinstall).

**Comment by abucodonosor** [comment]
@adriaandegroot 

I've tested the new re-written module and it does work just fine.

Testing was done with an normal plasma installation so lots packages 

Also tested pre-* post-* with one install: target and with more install: targets without any problems.

Also tested without any pre-* and post-* targets and that is working fine too

For me the issue is fixed you can close it.

( do you want me to open an feature request about the UI feedback we talked about on IRC ? )

**Comment by adriaandegroot** [comment]
It should now report (translatable, but not-translated-yet) progress information.
