### ISSUE TITLE
"Command timeout while starting"

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#784]
Hi, I'm getting a consistent failure to format a simple new partition on a VirtualBox drive with EXT4. It fails every time with `Command timeout while starting`. The `mkfs.ext4` command that it was trying to run worked when I ran it manually. Eventually I used manual mode to install to a partition without formatting it, and the installation proceeded.

This is with the Master branch of Calamares from 2017-08-31.

I'm attaching the log.
[calamares.log](https://github.com/calamares/calamares/files/1270621/calamares.log.txt)

Thanks a lot!

**Comment by abucodonosor** [comment]
@geckolinux 

How do you start calamares ?

I think I saw something like this with an broken sudo setup in the past.

**Comment by geckolinux** [comment]
Hmm could be. I used to use `pkexec`, but recently switched to `xdg-su -c /usr/bin/calamares`

**Comment by geckolinux** [comment]
Looks like that was the problem, `pkexec` works fine. Thanks a lot @abucodonosor
