### ISSUE TITLE
Calamares sometimes not able to see virtual drive under VirtulaBox

### ISSUE THREAD

**Issue by embar-** [calamares/calamares#785]
Calamares 3.1.3 sometimes does not see hard disk in VirtualBox. Interesting, that the same disk was visible then disk was empty; it became not visible after installing system with calamares and booting again installation medium; and disk can be visible again if create new partition table for same disk. 

![screenshot_20170903_131549](https://user-images.githubusercontent.com/1218781/30002165-2ddd8252-90ab-11e7-87ef-d80cd63bb254.png)

...and Calamares crash if I select to any of first three option.

![screenshot_20170903_131632](https://user-images.githubusercontent.com/1218781/30002167-31cae49a-90ab-11e7-959a-0e169d1e19d2.png)
...while forth option for "Manual partitioning" shows no disks.

Perhaps related https://github.com/calamares/calamares/issues/768 , but KPMcore 3.1.2 is already installed.

Becides, (g)parted successfully see this disk.

`# parted -l`
`Model: ATA VBOX HARDDISK (scsi)`
`Disk /dev/sda: 21,6GB`
`Sector size (logical/physical): 512B/512B`
`Partition Table: msdos`
`Disk Flags: `
` `
`Number  Start   End     Size    Type     File system     Flags`
` 1      1049kB  19,3GB  19,3GB  primary  ext4            type=83`
` 2      19,3GB  21,6GB  2362MB  primary  linux-swap(v1)  type=82`

KDE partition manager also succesfully see disk:
![screenshot_20170903_133941](https://user-images.githubusercontent.com/1218781/30002256-6b831fac-90ad-11e7-9e91-1376c29b63c0.png)

**Comment by embar-** [comment]
If I downgrade to Calamares 3.1.1, Calamares successfully see disk:

![screenshot_20170903_145537](https://user-images.githubusercontent.com/1218781/30002673-2a82cd4e-90b8-11e7-9e64-140e5e772346.png)

**Comment by embar-** [comment]
Start-up log of Calamares 3.1.3:

> pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY calamares
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
15:09:14 [1]: Calamares version: 3.1.2 
Translation: Calamares: Using system locale: "lt_LT"
15:09:14 [1]: Default font ===== 
Pixel size:    -1 
Point size:    9 
Point sizeF:   9 
Font family:   "Sans Serif" 
Metric height: 14 
15:09:14 [1]: Font height: 14 
15:09:14 [1]: Available languages: ("ar", "ast", "bg", "ca", "cs_CZ", "da", "de", "el", "en", "en_GB", "es_MX", "es", "eu", "fr", "he", "hr", "hu", "id", "is", "it_IT", "ja", "lt", "nl", "pl", "pt_BR", "pt_PT", "ro", "ru", "sk", "sv", "th", "tr_TR", "zh_CN", "zh_TW") 
15:09:14 [1]: CalamaresApplication thread: 0x1365820 
15:09:14 [1]: Using log file: "/root/.cache/Calamares/Calamares/Calamares.log" 
15:09:14 [1]: Using Calamares settings file at "/usr/share/calamares/settings.conf" 
15:09:14 [1]: Using Calamares branding file at "/usr/share/calamares/branding/default/branding.desc" 
15:09:14 [1]: WARNING: the selected branding component does not ship translations. 
15:09:14 [1]: Loaded branding component "default" 
15:09:14 [1]: STARTUP: initQmlPath, initSettings, initBranding done 
15:09:14 [1]: STARTUP: initModuleManager: module init started 
15:09:14 [1]: STARTUP: initModuleManager: all modules init done 
15:09:14 [1]: STARTUP: initJobQueue done 
15:09:14 [1]: Available size QSize(1600, 763) 
15:09:14 [1]:   Proposed window size: 1024 520 
15:09:14 [1]: STARTUP: CalamaresWindow created; loadModules started 
15:09:14 [1]: Initial locale  "lt_LT" 
15:09:14 [1]: Welcome string false "Linux" 
15:09:14 [1]: ViewModule "welcome@welcome" loading complete. 
15:09:14 [1]: ViewModule "partition@partition" loading complete. 
15:09:14 [1]: ViewModule "users@users" loading complete. 
15:09:14 [1]: ViewModule "summary@summary" loading complete. 
15:09:14 [1]: Module "partition@partition" already loaded. 
15:09:14 [1]: QML import paths: ("/usr/share/calamares/qml", "/usr/bin", "qrc:/qt-project.org/imports", "/usr/lib/qt5/qml") 
15:09:14 [1]: Module "users@users" already loaded. 
15:09:14 [1]: FinishedPage() 
15:09:14 [1]: FinishedViewStep() 
15:09:14 [1]: FinishedViewStep::widget() 
15:09:14 [1]: FinishedViewStep::widget() 
15:09:14 [1]: FinishedViewStep::widget() 
15:09:14 [1]: ViewModule "finished@finished" loading complete. 
15:09:14 [1]: STARTUP: loadModules for all modules done 
15:09:14 [1]: STARTUP: Window now visible and ProgressTreeView populated 
15:09:14 [1]: Need at least storage bytes: 9663676416 
15:09:15 [1]: Need at least ram bytes: 1073741824 
15:09:15 [1]: A battery exists, checking for mains power. 
15:09:15 [1]: enoughStorage, enoughRam, hasPower, hasInternet, isRoot:  true true true false true 
15:09:16 [1]: Removing unsuitable devices: 1 candidates. 
15:09:16 [1]: Checking for mounted partitions in "/dev/sda" 
15:09:16 [1]:   .. "/dev/sda2" is mounted on "swap" 
15:09:16 [1]:   .. Removing "/dev/sda" 
15:09:16 [1]: LIST OF DETECTED DEVICES: 
15:09:16 [1]: node      capacity        name    prettyName 
15:09:16 [1]: .. 0 devices detected. 
15:09:17 [1]: checking if "/dev/sda1" can be resized. 
15:09:17 [1]: "/dev/sda1" seems like a good path 
15:09:17 [1]: Partition "/dev/sda1" CANNOT BE RESIZED FOR AUTOINSTALL. 
15:09:17 [1]: "Osprober lines, clean:\n/dev/sda1:openSUSE Tumbleweed:openSUSE:linux" 
Segmentation fault (core dumped)

**Comment by philmmanjaro** [comment]
You may just test one of our [v17.0.3](https://manjaro.org/get-manjaro/) releases, which ships the latest **Calamares** code in our installer, including partitioning fixes ...

**Comment by embar-** [comment]
Manjaro 17.0.3 with Calamares 3.1.3 successfully finds disk. What partitioning patches did you apllyied?

**Comment by embar-** [comment]
OK, seems this bug is duplicate of https://github.com/calamares/calamares/issues/780

**Comment by embar-** [comment]
After compiling current master code, I can no longer reproduce this bug.

**Comment by adriaandegroot** [comment]
It is a dupo of #780; that you get buttons when there is no partition available is #774; the crash when you click one of the shouldn't-be-available buttons is something I'm investigating (either I want to stop the crash, or stop the buttons from being there if there are no selectable devices; the UI code there is weird).
