### ISSUE TITLE
libcrashreporter-qt (calamares 3.1.4) does not compile with LLVM/clang

### ISSUE THREAD

**Issue by tpgxyz** [calamares/calamares#788]
Full logs you can find here:
http://file-store.openmandriva.org/api/v1/file_stores/00465342641385959a37b4bd64502c65dd44c307.log?show=

In file included from /builddir/build/BUILD/calamares-3.1.4/thirdparty/libcrashreporter-qt/3rdparty/breakpad/client/linux/handler/exception_handler.cc:66:
/builddir/build/BUILD/calamares-3.1.4/thirdparty/libcrashreporter-qt/3rdparty/breakpad/./client/linux/handler/exception_handler.h:192:21: error: field has incomplete type 'struct ucontext'
    struct ucontext context;
                    ^

**Comment by adriaandegroot** [comment]
It's easier to read build logs when they're not running -j<lots>.

Kind of strange, I would assume ucontext comes from some system headers, not internal bits. Personally I'd suggest just disabling the crash reporter at this time (because you can't actually send crash reports with it, unless you're patching in a different target URL).

The huge list of clang warnings tells me I really need to sit down with clang locally, though, to fix them all.

**Comment by tpgxyz** [comment]
@adriaandegroot  btw we are running on clang 5.0

**Comment by kkofler** [comment]
IMHO, you should either make sure the target URL for the reports actually works or remove the crashreporter stuff from the tarballs again. It makes no sense to bundle something that does not work.

**Comment by adriaandegroot** [comment]
Since the crashreporter is an external module, it might make more sense to report the whole problem there.

**Comment by adriaandegroot** [comment]
(but I'll see what I can do with it standalone .. I don't think crashreporter is very active)

**Comment by adriaandegroot** [comment]
@tulliana has this same problem with gcc 7, so it does not seem to be a clang-specific problem. Can you look to see if <sys/ucontext.h> actually contains a definition for struct ucontext?

**Comment by adriaandegroot** [comment]
It is definitely not clang 5 in itself -- that compiles Calamares master on KDE Neon (stable) just fine. Might be CMake, or might be changed system headers somewhere else. I would need more information about the distro in use.

**Comment by demmm** [comment]
@adriaandegroot Looked into this being a glic 2.26 issue?  Does Neon already have that?

**Comment by adriaandegroot** [comment]
@demmm  Thanks! That is exactly it, according to https://sourceware.org/glibc/wiki/Release/2.26 .. so, since the crashreporter is the source of other problems, too (mostly, it's totally useless to me and also looks unmaintained upstream), I have switched it off.

**Comment by jriddell** [comment]
KDE neon is on libc-2.23.so
