### ISSUE TITLE
Suggest to integrate a xtermconsole like yakuake

### ISSUE THREAD

**Issue by blackcrack** [calamares/calamares#789]
Hi,

i suggest to integrate a pulldown terminal/commandline console via F12 to open like in different games,
to support debugging directly by install if something not works or need a wm for 
work around in the Gui and so on, or to be in able with maybe to see the installations process 
in console, so maybe with F11 to be in able to fellow / monitor the whole installations process 
commandos , open with F11 the promt/console where run the actual calamares prozess  .

is this able to integrate this in Calamares the 2 possibility's ?
therewith it is no body any more independent on any WM manager .

best regards
Blacky

**Comment by adriaandegroot** [comment]
This is met by three different features already in Calamares:
* There is a module interactiveterminal, which spawns inside the installed system
* There is the debug-window, which shows the debug log as Calamares goes along
* You can start Calamares from a terminal if you like

You're still going to need X11 and / or a WM to run Calamares, regardless.

**Comment by blackcrack** [comment]
Hi @adriaandegroot  :)
With a terminal/prompt window would be the possibility, 
that one could directly follow how everything runs
and be in able to directly could track how everything goes,
the problem is when you have the whole thing on a CD,
as iso, do you be not in able to save anywhere and as programmer could you directly tracking what's goes on and be maybe more in able to see what's by this or an other Distro not works nice and be in the able to see what's goes direcktly wrong, if X runs and camamares, without any WM
and be in able directly to make a really tiny installer iso with Calamares if no wm on it and only the tools what's really need for installing.. , kernel, bash-tools, the one or other recoverytool, network stack, xorg/wayland, rpmtools or urpmi, who makes able to install the distro directly over network from a mirrorlisting.
With the Recoverytools could it able to manipulating the harddisk's file and so on, so at the same time
could it be a recovery terminal without need to let run tty instances, because we can call a F12 or something, Terminal to be in able at the same time do something other .. before the system run (and therewith meant i am different Distributions, where makes able to manipulating files, hosts, exports and other files and so on.. and be in able to let before the reboot starts mounting an other drive, take own scripts and so on.. This feature would be certainly interesting for others too.

On a minimal System on a iso, which starts kernel, xorg, calamares, gives a less possibility to let start an terminal :) A logwindow it's nice, but display only a Log and a Interactiveterminal who spawns automatical it is also not the non+ultra, on this place it is maby better to have a possible for a hotkey who open (or slide down) an Teminalwindow who the normal User not know, except if he wants to know for have the possibility to know more or to have an terminal to have the possibility for recovery or many other things ..
Like mirroring harddisk's, make backups from not running systems, more less on a Installmedium on it, more faster run's the tools (if i right :) ) would really nice if the Distriebutors become something on hand to be in able for make more tiny iso's :)

Why do you need a WM to run a Program without Frame if the program centered ?
the program hold the X on running .. as example the emergymode on sddm , the xterm window
so should calamares also running without an WM as pure installer / install program, or ?
(normally, i guess..)

best regards
Blacky :)

**Comment by abucodonosor** [comment]
Like @adriaandegroot  said , there are already at least 3 features doing that , or similar to what you wish.
