### ISSUE TITLE
Do not allow to short or broken passwords

### ISSUE THREAD

**Issue by abucodonosor** [calamares/calamares#790]
Right now the min password length for users an crypt is a 'space'.

I think we should not allow ( at least for now ):
 passwords with < 6 chars
 password = user name

**Comment by kkofler** [comment]
I think it is not the job of the installer to patronize the user. We should even allow empty user passwords, the empty password is a valid password!

**Comment by abucodonosor** [comment]
@kkofler 

Well it is .. at least to have a option for that..

**Comment by philmmanjaro** [comment]
it can be might optional for sure and each distro may decide how they want it.

**Comment by kkofler** [comment]
I strongly believe that software should not tell the user what he/she is allowed to do with his/her own computer. Refusing a password that is not valid for real technical reasons is OK. Refusing a password that is not "strong" enough by some arbitrary standard is not.

**Comment by adriaandegroot** [comment]
Seems both patronising (in depoloyment) and annoying (in testsing). But distro's might want to be that way. I can imagine having an entry in the users.conf like

```
passwordrules:
    min-length: 8
    required-chars: alpha+ALPHA+digit+punct
    exclude-username: true
```

I'd accept a pull-request that implemented such checks.

**Comment by adriaandegroot** [comment]
Ideas for other checks that could be implemented (right now it's only got length checks, disabled by default):
 - nonempty
 - RE matching
 - disallow username
 - character checking

The framework is there, and the implementation bits are quite small (in `UsersPage::addPasswordCheck()`). This would *also* let us allow empty passwords, by replacing the hard-coded check for non-emptiness with a configurable check for non-emptiness.

**Comment by kkofler** [comment]
Nonempty is equivalent to a minimum length of 1. So you can already do that: just remove the emptiness check and default the minimum length to 1 instead of -1.

**Comment by adriaandegroot** [comment]
While it is easy to switch to `minLength: 1`, I don't want to count on distro's adjusting their `users.conf` immediately, so switching wholesale to the *passwordRequirements* approach might let empty passwords slip through the cracks. (And I'm not even sure that Cala correctly sets empty passwords)
