### ISSUE TITLE
KPMCore 3.1.50 dependency

### ISSUE THREAD

**Issue by plfiorini** [calamares/calamares#792]
README still states a lower version required and the 3.1.4 announcement doesn't say the dependency was bumped although it was changed prior to the release:

https://github.com/calamares/calamares/blob/master/src/modules/partition/CMakeLists.txt#L11

**Comment by philmmanjaro** [comment]
If you look more closely:

```
find_package( KPMcore 3.1.50 )
if ( ${KPMcore_FOUND} )
    add_definitions(-DWITH_KPMCORE22)
endif()
find_package( KPMcore 3.0.3 REQUIRED )
```
v3.1.50 is still optional.
