### ISSUE TITLE
With lang set to != en_US some things won't work

### ISSUE THREAD

**Issue by abucodonosor** [calamares/calamares#797]
#### Submission type

  - [*] Bug report

#### Info regarding which version of Calamares is used, which Distribution

> calamares 3.1.4
> KPMcore 3.1.2
> Frugalware Linux ( but the used  Distribution  doesn't matter )

#### What do you expect to have happen when Calamares installs?

> Everthing to work even with other languages.

#### Describe the issue you encountered

>  The bug is in KPMcore to start with and this issue is reported already there:
     https://bugs.kde.org/show_bug.cgi?id=364648

> Since the filesystems are being translated we get the translated
> string back from KPMcore and so simple checks fails or the condition 
> won't trigger in calamares.

>  We look in some places for:

``` ....["fs"] == fstype```

> to decide what to do for swap , luks , detect btrfs and so on.

> Eg: we look for 'linuxswap' but get back the fs type being 'Linux-Swap' 
> or Swap or whatever is translated to so the condition never triggers.

#### Steps to reproduce the problem

> start calamares from konsole with LANG set to de_DE as example:

   `` LC_ALL=de_DE.utf8 pkexec calamares -d ``

> Try to install with LUKS as example .. or simple install and watch 
> for swap being added correctly

**Comment by stikonas** [comment]
@adriaandegroot Should we try to keep both translated and untranslated fstypes (in two different variables).

**Comment by philmmanjaro** [comment]
It would be better to simply convert all to lowercase and check then.

**Comment by abucodonosor** [comment]
no .. is not about only lower case .. see linuxswap example ..

so you get the Linux-Swap -> linux-swap which is still broken

**Comment by philmmanjaro** [comment]
@abucodonosor: this makes now totally sense that we have some issues when used non `en_US`.

**Comment by abucodonosor** [comment]
@philmmanjaro 

yes .. I tested most of the time en_US but then did some test installs in de_DE , fr etc
and stuff startet to break all over the place.

then saw the translated strings comming in and all was clear to me :)

**Comment by philmmanjaro** [comment]
@adriaandegroot & @stikonas: I've tested now my last changes. Seems to work now.

**Comment by philmmanjaro** [comment]
Hmm, `strip("-")` seems not yet to work ...

**Comment by stikonas** [comment]
Well, we need to fix it properly in kpmcore... These workarounds  would be too unreliable since we can't predict what translators would do.

**Comment by philmmanjaro** [comment]
I've just looked the translations. Most of them used `linuxswap` as translations. Also I see variations of these:

```
de/kpmcore.po:msgid "linuxswap"
de/kpmcore.po:msgstr "Linux-Swap"
is/kpmcore.po:msgid "linuxswap"
is/kpmcore.po:msgstr "swap"
nds/kpmcore.po:msgid "linuxswap"
nds/kpmcore.po:msgstr "Linux-Swap"
```

**Comment by philmmanjaro** [comment]
I created now a workaround which works for all cases fo `linuxswap` as given in **kpmcore v3.1.2**. Also the `btrfs` issue is now covered.

@stikonas: please keep me in the loop when you have a proper fix added to **kpmcore**, which I may test also on my end.

**Comment by adriaandegroot** [comment]
The "big" problem is going to be свап and سؤإب

**Comment by adriaandegroot** [comment]
.. which is why we need a means to access the untranslated name, as well as the translated name.

**Comment by stikonas** [comment]
@philmmanjaro @adriaandegroot 
https://cgit.kde.org/kpmcore.git/commit/?id=5d65d83990b3dc1c4a093ae70ab1b85405a383c6

**Comment by philmmanjaro** [comment]
@adriaandegroot we should update as needed when a new version of **kpmcore** got released. With the current code of **CAL** I see no pressure yet. @stikonas: thx for fixing it in **kpmcore**.

**Comment by stikonas** [comment]
@adriaandegroot actually after reading some more docs I am thinking that we shouldn't duplicate strings. Any objections to using KLocalizedString instead? It allows retrieving untranslated version of the string. Sounds a bit less hacky...
