### ISSUE TITLE
BTRFS LUKS

### ISSUE THREAD

**Issue by lawmanuk** [calamares/calamares#803]
#### Submission type

  - [X ] Bug report

#### Info regarding which version of Calamares is used, which Distribution

>
Manjaro 17.02 XFCE used, so whichever Calamares ships with that.

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> MSDOS style partition table.   Separate partitions for Windows, Boot, Linux.

#### What do you expect to have happen when Calamares installs?

> Setup BTRFS root with LUKS encryption.

#### Describe the issue you encountered

> Halts when booting as can't find HOME directory/subvolume.  

Works fine if installing with EXT4 on LUKS.   Problem is only when installing with BTRFS on LUKS

#### Steps to reproduce the problem

> Just install Manjaro 17.02 with BTRFS file system on root, encrypted with LUKS

#### Include the installation.log:

> …

**Comment by lawmanuk** [comment]
Just checked this with Manjaro 17.04 and the updated Calamares they use.

Same issue.

When installing with BTRFS on root, encrypted with LUKS - the system halts when booting with error stating FAILED TO MOUNT HOME.

The problem doesn't exist if installing with EXT4 on LUKS.   Only happens when trying to use BTRFS.

As a I want BTRFS and also wanted that encrypted, it means I can't install Manjaro - so heading back to Antergos again as that installs fine with BTRFS on LUKS using CNCHI.

Please fix.

Thanks.


![virtualbox_manjaro1704_14_09_2017_22_23_32](https://user-images.githubusercontent.com/30639079/30456480-aec6290c-999b-11e7-9017-3ab6f2e415a2.png)

**Comment by stikonas** [comment]
Wasn't this fixed recently in new calamares versions (https://github.com/calamares/calamares/issues/796#issuecomment-328814015)

**Comment by abucodonosor** [comment]
yes it is fixed

**Comment by philmmanjaro** [comment]
Yes, it is already fixed and deployed with **Calamares v3.1.4-9**. Please get it from our **unstable** branch.

**Comment by lawmanuk** [comment]
Thanks for update.

Can you please advise how I can get from unstable branch and use to install Manjaro 17.04 XFCE.

newbie here.

Thanks

**Comment by philmmanjaro** [comment]
Please use **v17.0.5** ISOs, which got updated to that version of **Calamares**.
