### ISSUE TITLE
BTRFS on LVM on LUKS

### ISSUE THREAD

**Issue by lawmanuk** [calamares/calamares#810]
#### Submission type

  - [X ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> … 3.1.4 on manjaro 17.04 XFCE

#### Describe the issue you encountered

> …  At present most partition managers/distro installers etc. aren't fully capable to handle full BTRFS subvolume capability.

So the current compromise is to use LVM on LUKS.

However, Calamares doesn't seem to allow LVM management/creation etc. for root/home/boot/data and put on top of a LUKS container, so other distros / data can be put into LVM without asking for more LUKS passwords.

I can't recall which distro installers right now, but i've seen others handle this with ease.  Perhaps Ubuntu from memory.

**Comment by abucodonosor** [comment]
So the feature request should be : Want LVM support first

**Comment by abucodonosor** [comment]
Which is basically #427.. Once LVM is supported everything else should work.

closing as dupe for now..
