### ISSUE TITLE
(DBus) Notification on finished hangs, then errors out

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#811]
When started as a regular user, the finished-page for Calamares does a DBus call to the desktop-notifications address to notify that it's finished. When started through sudo or pkexec, the application gets a different user / session bus and there is no desktop-notifications listening on *that* bus. So the dbus at the end hangs for 30 seconds, then errors out.

**Comment by kkofler** [comment]
Notifications also don't work under `kdesu` (using its `su` backend), I tested with:
```kdesu notify-send "test notification" "the quick brown fox jumps over the lazy dog"```
So disabling the notifications by default as you did makes sense, I just wonder whether it's even worth having the option at all, as I don't think it will work in any reasonable Calamares setup.

If you really want to put up a notification, you will have to use a custom mechanism, such as `KPassivePopup` from the `KNotifications` framework:
https://api.kde.org/frameworks/knotifications/html/classKPassivePopup.html
