### ISSUE TITLE
Bootloader destination options

### ISSUE THREAD

**Issue by lawmanuk** [calamares/calamares#813]
#### Submission type

  - [X ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> … 3.1.4 manjaro 17.0.5

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> …  MSDOS partition table

#### What do you expect to have happen when Calamares installs?

pls allow installing bootloader on partition as an option, instead of only on MBR

This is allowed in most other installers.

Thanks

**Comment by abucodonosor** [comment]
Hmm ? that is already supported for BIOS installations..

**Comment by abucodonosor** [comment]
http://sigsegv.24-7.ro/~crazy/813.png

**Comment by lawmanuk** [comment]
yes.  you're correct.

I think I checked bootloader destination by selectin gpartition before choosing root.  

After choosing root, it works fine.
