### ISSUE TITLE
calamares about

### ISSUE THREAD

**Issue by lawmanuk** [calamares/calamares#814]
#### Submission type

  - [X ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> …  3.1.4 on manjaro 17.05

#### What do you expect to have happen when Calamares installs?

> …  can you pls put the sub version number in about box for calamares.  that makes it easier to check if we have the latest version in distro.  eg. in manjaro 17.05 I believe we have at least 3.1.4.9, but it only shows 3.1.4 when I check it.

**Comment by abucodonosor** [comment]
There is nothing like 3.1.4.'9' . This seems to be some manjaro versioning.

3.1.4 is latest release.

**Comment by philmmanjaro** [comment]
It depends on how we display the version. I can add the revision if needed also to our stable releases. For development versions we even add the git-commit. Let me think about it. And yes, the current stable release is **v3.1.4**.
