### ISSUE TITLE
btrfs installation subvolume options

### ISSUE THREAD

**Issue by lawmanuk** [calamares/calamares#815]
#### Submission type

  - [X ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> … 3.1.4 on manjaro 17.05

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> … msdos partition.

#### What do you expect to have happen when Calamares installs?

> …  when formatting btrfs and mounting as root, home, data etc.   please allow mounting options such as compression and other options etc.

This allows high compression of root subvolume and faster compression for home partition, with all data written during installation complying with options required.

At present, there are no compression options at all.

We could add these options in fstab later for mounting, but the previous data written to root on installation will remain uncompressed etc.

**Comment by abucodonosor** [comment]
There are but is up2 your Distro to enable .. 

https://github.com/calamares/calamares/blob/master/src/modules/fstab/fstab.conf

**Comment by philmmanjaro** [comment]
@lawmanuk: which exact option you're missing?

**Comment by lawmanuk** [comment]
Eg.

Diff Compression options for each subvolume created.  Eg.  Root home etc

**Comment by philmmanjaro** [comment]
Then simply modify **fstab.conf** as needed and do some tests. We have always keep in mind that is a generic installer and should work for the common use cases.

**Comment by kkofler** [comment]
Configuring the options per subvolume is only possible if #807 is implemented first. If the subvolumes can be managed like partitions in the UI, then it would just be an extra text field, or more user-friendlily, a set of checkboxes and dropdowns. But as long as the UI knows nothing about subvolumes, there is no way we can let you configure options per subvolume.

**Comment by abucodonosor** [comment]
Well yes .. however we we go allow per 'partition' flags that has to be a generic
option for all FS'es not only btrfs. Other FS'es can have different flags too.

**Comment by adriaandegroot** [comment]
Needs a PR, closing as "duplicate, not enough interest".
