### ISSUE TITLE
"No rootMountPoint in global storage"

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#817]
Hi, when trying to install an openSUSE Leap 42.3 based distro using the current Calamares master version as of right now, installation is failing at the timezone step because it can't create the symlink. It appears that it can't find the root installation target, since just before that in the log I see:
`No rootMountPoint in global storage`
Here's the complete log:
[log](https://github.com/calamares/calamares/files/1322997/calamares.log.txt)

This issue just started happening in master somewhere between yesterday and today.

Thanks a lot!

**Comment by adriaandegroot** [comment]
The problem is actually that none of your Python job-modules are working -- and so neither is the mount-job, which sets up that information. I know I was messing around with finding the Python libs recently. Probably I have broken Python libraries detection for you.

**Comment by geckolinux** [comment]
Hi there, this bug appeared again, now with Calamares 3.1.11 and the current openSUSE Tumbleweed. I'm seeing in the Calamares terminal output:

     Python modules are not supported in this version of Calamares

and so therefore 

     No rootMountPoint in global storage

My Python3 installation appears to be normal:

````````````
whereis python3
python3: /usr/bin/python3.6 /usr/bin/python3.6m /usr/bin/python3 /usr/lib/python3.6 /usr/lib64/python3.6

**Comment by adriaandegroot** [comment]
You're going to have to provide actual configure output if you want help on this: Calamares **at build time** is not finding suitable libraries to build the Python job modules. Whether you have a working Python 3 interpreter executable (at build or run time) is really not relevant.

**Comment by adriaandegroot** [comment]
Typically you'll see this CMake output:

```
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable version "3.5.2", minimum required is "3.3") 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   PYTHON-PY35
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found version "3.5.2") 
-- Searching for PythonQt (PythonLibs 3.5) ..
```

Note that you need Python development headers, Boost, **and** Boost-Python for the (regular) Python modules.

**Comment by geckolinux** [comment]
> Calamares at build time is not finding suitable libraries to build the Python job modules. 

Ah, I see, thanks for explaining that. Here's the build log:
[build.log](https://github.com/calamares/calamares/files/1628910/build.log)
Meanwhile I'll keep on experimenting with the spec file.

**Comment by geckolinux** [comment]
The problem seems to be here:

     No header defined for python3; skipping header check

I found these related bug reports, but don't really understand what the problem is or how to fix it:
- https://github.com/davisking/dlib/issues/1043
- https://gitlab.kitware.com/cmake/cmake/merge_requests/201

**Comment by geckolinux** [comment]
Update: OK, it looks like it was a missing boost devel package for the build environment, they changed the names between the Tumbleweed and Leap versions. Thanks to @adriaandegroot for pointing me in the right direction.

**Comment by kkofler** [comment]
You should add the required packages as `BuildRequires` in your specfile, then RPM will fail the build immediately if something is missing. And if you ever want to build your specfile in `mock` or any build system based on it (e.g., Koji, Copr, etc.), you will need them anyway (because `mock` uses the `BuildRequires` to populate the chroot, whereas OBS does its own magic for some reason).

**Comment by geckolinux** [comment]
@kkofler Yep, I used to have:
`BuildRequires:  boost-devel`
...which worked for both Leap and Tumbleweed. Now they appear to have split out at least part of it into `libboost_python3-devel` for Tumbleweed. It did seem kind of strange that Calamares would happily compile away without Boost support, only throwing cmake warnings. Seems like it should fail if such important functionality is missing.

Anyway I now have:

     %if %{?suse_version} == 1315
     BuildRequires:  boost-devel >= 1.59.0
     %else
     BuildRequires:  libboost_python3-devel
     %endif

**Comment by adriaandegroot** [comment]
Glad it got sorted out. I guess the CMake code could be a little more explicit about what is (not) found. The tradition is that Calamares should build what-is-possible rather than erroring out on missing requirements -- which is why missing boost and python isn't a big deal. Even without python, though, the python-based modules (scripts) are copied, which is probably confusing. I'll see if I can easily suppress them -- which would at least trigger packaging failures for you, when the Python modules aren't copied to the package staging area.

**Comment by geckolinux** [comment]
@adriaandegroot Thanks a lot Adrian. That would make sense for it error out if the Python and Boost build dependencies aren't satisfied, since Calamares essentially becomes a UI that can't do anything without them.
