### ISSUE TITLE
Calamares does not build on ARM64

### ISSUE THREAD

**Issue by shadeslayer** [calamares/calamares#818]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution
> Calamares 3.1.4
> Debian Testing Snapshot 20170904

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> NA

#### What do you expect to have happen when Calamares installs?

> NA

#### Describe the issue you encountered

> Calamares does not build on ARM64
> Build log http://dci.pangea.pub/job/1710_release_calamares_calamares-debian_bin_arm64/1/console

#### Steps to reproduce the problem

> Try to build Calamares on ARM64

#### Include the installation.log:

> NA

**Comment by adriaandegroot** [comment]
On it .. basically the test for ARM is too-specific (arm32 only). A 3.1.5 (without crashreporter, with some recent fixes) will come out this week, which ought to resolve this problem.

**Comment by adriaandegroot** [comment]
3.1.5 released, that should do the trick.
