### ISSUE TITLE
Hidden OS via Plausibly Deniable Encryption (with DELUKS or other solution)

### ISSUE THREAD

**Issue by lawmanuk** [calamares/calamares#819]
#### Submission type

  - [ x ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> … 3.1.4  - manjaro 17.05

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> … msdos partition table

#### What do you expect to have happen when Calamares installs?

> … an equivalent solution to veracrypt hidden os.

namely, allow calamares to install hidden encrypted system volume by:

1.  Installing dummy outer OS booted via password 1

2.  Install true hidden OS booted via password 2 (by using DELUKS https://github.com/kriswebdev/grub-crypto-deluks)

3.  Allow user customisable boot message to avoid screaming that drive is encryped.   eg. similar to what DriveCrypt (and I believe Veracrypt) allow.  eg.   Instead of stating 'Enter Password...", state "Hard Disk Error...".    

I appreciate (3) in itself can be implemented almost immediately  and doesn't provide plausible deniability, but its a start in misdirecting the initial 90% of inexperienced queries raised.

**Comment by adriaandegroot** [comment]
This strikes me as something way beyond the core of Calamares. A paranoia-focused distro could develop modules for this (probably a fork of the partitioning module, and extra settings in the mount module) and I'd be receptive to a pull-request, but for core calamares this is way down the priorities list.

**Comment by lawmanuk** [comment]
I was thinking more of pulling DELUKS into Calamares, as they've already done all the work for creating the deniable LUKS.

I understand yr thoughts though.  Its a real pity, as this function in Calamares would really make it stand out from the crowd, with minimal work due to pulling in DELUKS project.

**Comment by kkofler** [comment]
We cannot just "pull DELUKS into Calamares". Distros can package it, if they want, but it is a fork of GRUB, so they will be reluctant. And Calamares can get support for it, but this is configuration work to set it up properly (just look at the instructions on the GitHub page to see how many settings it needs), which is all new Calamares code that would have to be written (to detect DELUKS, if available offer a checkbox in the GUI to enable it, then write all the relevant settings in the various Calamares modules, at least in the `grubcfg` module). And of course all this will only do any good on distros that actually package the GRUB fork.

**Comment by kkofler** [comment]
And as @adriaandegroot already wrote, the `partition` module would also need major changes to support DELUKS. This is again all code that would have to be written in Calamares (or even kpmcore), not something we can just "pull in". (We could "pull it in" if DELUKS were maintaining Calamares patches, but they aren't, they are working only on the lowest layer with manual setup instructions.)

**Comment by abucodonosor** [comment]
Well DELUSk are just patches to grub ( not yet accepted upstream ) see:

http://lists.gnu.org/archive/html/help-grub/2017-02/msg00017.html

Also from what I see one still need on top these patches a random  'peter/devmapper'
branch etc ..

I'm not sure we want even consider supporting that before this 
feature is merged upstream..

**Comment by kkofler** [comment]
In any case, I doubt Fedora is going to carry the DELUKS-patched software any time soon. What other distros will do, I have no idea.

**Comment by abucodonosor** [comment]
see #836

**Comment by Raj2032** [comment]
Can you create a hidden OS using deluks?
