### ISSUE TITLE
ARM

### ISSUE THREAD

**Issue by texrg** [calamares/calamares#820]
Calameres can working with ARM machines?

Is possible to using my package manager? for example opkg

**Comment by adriaandegroot** [comment]
Yes, Calamares works on ARM machines. Netrunner ARM, for instance, uses it as an OEM installation tool. Version 3.1.5 (just released) drops some code that is not-ARM-compatible.

Calamares is not an end-user tool; I don't know what you mean about using the package manager. `opkg` is not .. oh, that's OpenWRT. It's not supported in the standard packages modules of Calamares, and I think you'd be better off not using packages during installs, but just moving a disk image around. (I'd accept a pull request to add opkg support to `src/modules/packages/main.py`, though)

**Comment by kkofler** [comment]
Well, using the `packages` module to remove Calamares from the installed system is a nice feature.
