### ISSUE TITLE
Encrypted Home (with ecryptfs or other solution)

### ISSUE THREAD

**Issue by lawmanuk** [calamares/calamares#822]
#### Submission type

  - [X ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> … 3.1.4 Manjaro 17.05 xfce

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> … msdos partition table

#### What do you expect to have happen when Calamares installs?

> … pls allow encrypting home mount with ecryptfs, regardless of whether system is luks encrypted or not.  

If os partition is luks encrypted, allowing home encryption adds another layer of individual encryption.   most users can have the luks password for os access, with each user having their own encrypted home folder underneath.

Alternatively, if we don't need luks os encryption, users can still have their home encrypted for some level of privacy.

I know ubuntu installer permits home encryption option.  Not sure if it does so on top of luks aswell.

thanks

**Comment by abucodonosor** [comment]
@lawmanuk btw I've already closed #809 as duplicated of #608 .. so why open yet
another feature request about same thing ?

**Comment by lawmanuk** [comment]
Sorry.   Slipped my mind that already requested
