### ISSUE TITLE
finished.conf: restartNowEnabled: false does't hide the CheckBox

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#829]
#### Submission type

  - [ ] Bug report

#### Info regarding which version of Calamares is used, which Distribution

> ArchMerged and Calamares 3.1.5-1

#### What do you expect to have happen when Calamares installs?

> /ect/calamares/modules/finished

restartNowEnabled: **false**

```
Configuration for the "finished" page, which is usually shown only at
the end of the installation (successful or not).
---
# The finished page can hold a "restart system now" checkbox.
# If this is false, no checkbox is show and the system is not restarted
# when Calamares exits.
restartNowEnabled: **false**
# Initial state of the checkbox "restart now".
restartNowChecked: false
# If the checkbox is shown, and the checkbox is checked, then when
# Calamares exits from the finished-page it will run this command.
restartNowCommand: "systemctl -i reboot"

# When the last page is (successfully) reached, send a DBus notification
# to the desktop that the installation is done. This works only if the
# user as whom Calamares is run, can reach the regular desktop session bus.
notifyOnFinished: false
```

#### Describe the issue you encountered

> checkbox still visible and NOT working 
![archmerged-restart-now](https://user-images.githubusercontent.com/10594806/31313847-b64ca2b2-abef-11e7-8925-badf0b72afb4.jpg)

Running as debug shows a line
qbasictimer::start: Qbasictimer can only be used with threads started with Qthread
#472

**Comment by archmerge** [comment]
I have the same on ArchMerge... thinking that I may have compiled calamares wrong.
There was a patch reference inside the pkgbuild that I did not have...?
Going to investigate on that idea

**Comment by erikdubois** [comment]
i reverted back to calamares 3.1.4 to see if there was in issue with the 3.1.5.
same thing - checkbox is displayed even when i said 
restartNowEnabled: false
in the finished file

**Comment by philmmanjaro** [comment]
Well, it is wanted that way. You can see that in the code:

```
FinishedPage::setUpRestart()
{
    cDebug() << "FinishedPage::setUpRestart()";
    if ( !m_restartSetUp )
    {
        connect( qApp, &QApplication::aboutToQuit,
                 this, [this]
        {
            if ( ui->restartCheckBox->isVisible() &&
                    ui->restartCheckBox->isChecked() )
                QProcess::execute( "/bin/sh", { "-c", m_restartNowCommand } );
        } );
    }
}
```
Only when visible and checked uses the restart cmd. Else it does nothing. What you guys want is a forced restart, which even makes no sense with the current text written on that page.

**Comment by erikdubois** [comment]
I want the checkbox NOT to be visible at all.
Can I achieve that?

**Comment by philmmanjaro** [comment]
With the given code it is not designed to restart when you check it with the config file. It has also to be visible: 

```
        {
            if ( ui->restartCheckBox->isVisible() &&
                    ui->restartCheckBox->isChecked() )
                QProcess::execute( "/bin/sh", { "-c", m_restartNowCommand } );
        } );
```
Therefore you have to modify the C-code on your end to some like this:

```
        {
            if ( ui->restartCheckBox->isChecked() )
                QProcess::execute( "/bin/sh", { "-c", m_restartNowCommand } );
        } );
```

**Comment by philmmanjaro** [comment]
@adriaandegroot: should we remove the `ui->restartCheckBox->isVisible()` in general? IMO not needed at all ...

**Comment by erikdubois** [comment]
I suppose you can leave it out - less maintenance on your part

or

if it stays in, I would like to have the possibility to either show it or not.
If shown and checked reboot after exiting
if shown and not checked - do nothing
if not shown - do nothing

I am not going to patch parts of calamares and trust your judgement on how to proceed.

**Comment by abucodonosor** [comment]
@philmmanjaro 

Well @erikdubois  is right .. 

We set the CheckBox visible , then we check:

https://github.com/calamares/calamares/blob/master/src/modules/finished/FinishedViewStep.cpp#L171

but we are missing a 'else' there to set the CheckBox hidden when !restartNowEnabled.

**Comment by erikdubois** [comment]
looks like we can improve calamares
glad I could help

**Comment by philmmanjaro** [comment]
@erikdubois, @abucodonosor seems I was then on the wrong code lines. For setting up the page, this is used:

```
void
FinishedViewStep::setConfigurationMap( const QVariantMap& configurationMap )
{
    if ( configurationMap.contains( "restartNowEnabled" ) &&
            configurationMap.value( "restartNowEnabled" ).type() == QVariant::Bool )
    {
        bool restartNowEnabled = configurationMap.value( "restartNowEnabled" ).toBool();

        m_widget->setRestartNowEnabled( restartNowEnabled );
        if ( restartNowEnabled )
        {
            if ( configurationMap.contains( "restartNowChecked" ) &&
                    configurationMap.value( "restartNowChecked" ).type() == QVariant::Bool )
                m_widget->setRestartNowChecked( configurationMap.value( "restartNowChecked" ).toBool() );

            if ( configurationMap.contains( "restartNowCommand" ) &&
                    configurationMap.value( "restartNowCommand" ).type() == QVariant::String )
                m_widget->setRestartNowCommand( configurationMap.value( "restartNowCommand" ).toString() );
            else
                m_widget->setRestartNowCommand( "systemctl -i reboot" );
        }
    }
    if ( configurationMap.contains( "notifyOnFinished" ) &&
            configurationMap.value( "notifyOnFinished" ).type() == QVariant::Bool )
        m_notifyOnFinished = configurationMap.value( "notifyOnFinished" ).toBool();
}
```
Then it will be set to visible or not with this:

```
void
FinishedPage::setRestartNowEnabled( bool enabled )
{
    ui->restartCheckBox->setVisible( enabled );
}
```
Now we have to find out why that never happens and it is permanent visible.

**Comment by philmmanjaro** [comment]
@abucodonosor [line 168](https://github.com/calamares/calamares/blob/master/src/modules/finished/FinishedViewStep.cpp#L168) contains the value **true** or **false** and that will get converted to a **bool** within [line 170](https://github.com/calamares/calamares/blob/master/src/modules/finished/FinishedViewStep.cpp#L170). Then executed to be set either to **visible** or **not** within [line65](https://github.com/calamares/calamares/blob/master/src/modules/finished/FinishedPage.cpp#L65). Therefore an else is not needed at all. We have to check what the value is, as this might not work at all. So it is always visible.

**Comment by abucodonosor** [comment]
@philmmanjaro 

yes you are right .. is sometimes hard to figure code on the smartphone..

looking now closer I cannot see broken code but the configuration file is broken.

see https://github.com/calamares/calamares/commit/74c19fc02d6f3cdf9693dcc35efc75b837a6e3e9#diff-c228482fbc13c25ef3f01f4b80b13e60R1

line1,2 is broken .. that will give out bad configuration format.. so I guess we end up in
 !m_restartSetUp..

Can you or @erikdubois try this with a fixed configuration file please ? ( eg: comment or remove first 2 lines of the configuration file ).

**Comment by abucodonosor** [comment]
yes configuration file is broken.. just got home and tested that
