### ISSUE TITLE
option to customise grub luks prompt on installation (for stealth)

### ISSUE THREAD

**Issue by lawmanuk** [calamares/calamares#836]
#### Submission type

  - [X ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> …  manjaro 17.05

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> …  luks full OS encrypted with btrfs file system.

#### What do you expect to have happen when Calamares installs?

> … Could you please consider an option on LUKS OS encryption to permit a custom grub prompt and feedback message.

This would:

1.  Permit me to replace the password prompt to something like "Hard Disk Error"

2.  Permit me to change feedback on wrong password to no error message.

3.  By using above, allow me to have a stealth LUKS OS, where it is not immediately apparent that drive has password encryption, as opposed to a faulty disk.   (I accept this is not water tight as luks header exists, but it would resolve 99% lay inspection).

4.  This feature for stealth encryption already exists in Veracrypt and previously Drivecrypt.  Would be helpful with grub for luks, when installed via Calamares.

5.  By allowing a customised prompt at installation, it removes standard prompts.

Thanks

**Comment by abucodonosor** [comment]
And how you think we can do that ? By live patching grub source and recompiling it ?

You are requesting such a feature to the wrong project. Grub has this _hardcoded_ in his
source code , so you may want to request such a feature to grub itself first.

see grub-core/disk/luks.c in grub source.
 ...

```
  /* Get the passphrase from the user.  */
  tmp = NULL;
  if (source->partition)
    tmp = grub_partition_get_name (source->partition);
  grub_printf_ (N_("Enter passphrase for %s%s%s (%s): "), source->name,
               source->partition ? "," : "", tmp ? : "",
               dev->uuid);

```

and so on ..

**Comment by abucodonosor** [comment]
There is no way to implement that with grub right now. 

IF grub ever add such a way to change the messages re-open that.
