### ISSUE TITLE
Missing package for viewing the letters on the keys

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#837]
We are using calamares to our satisfaction to install ArchMerge and ArchMergeD.

But i recently installed Manjaro Xfce and they do have letters on the keys on this image.

Hoping this is just an issue of installing a package. 

Calamares 3.1.4 is used. Posted another question online to ask what this 'kpmcore-3.2.patch' is in your build for Calamares 3.1.5. [](https://github.com/manjaro/packages-extra/issues/124)

![calamares](https://user-images.githubusercontent.com/10594806/31803260-03c01f6c-b553-11e7-900e-6a53b6bd0081.jpg)

**Comment by philmmanjaro** [comment]
Font [Helvetica](https://github.com/calamares/calamares/blob/master/src/modules/keyboard/keyboardwidget/keyboardpreview.cpp#L35) is used. On XFCE we have installed the following fonts:

```
cantarell-fonts
terminus-font
```

`kpmcore-3.2.patch` is a snapshot of **[kpmbcore-3.2](https://github.com/calamares/calamares/tree/kpmcore-3.2)** branch.

**Comment by erikdubois** [comment]
thanks trying now and closing

**Comment by erikdubois** [comment]
tried installing helvetica font and others - to no avail
![vb-no-keys](https://user-images.githubusercontent.com/10594806/31849002-99961c4c-b63b-11e7-9853-cede08990fcf.jpg)

**Comment by abucodonosor** [comment]
@erikdubois 

this is because you are missing to read:

https://github.com/calamares/calamares/tree/master/src/modules/keyboard

```
Requires ckbcomp script.

```
Install that and your problem is gone.

**Comment by erikdubois** [comment]
I am so happy...
![keyboard](https://user-images.githubusercontent.com/10594806/31851627-f5ae0aa2-b669-11e7-9f5f-589a0ce8ce40.jpg)

**Comment by adriaandegroot** [comment]
@abucodonosor This suggests that the documentation isn't easy enough to find, and should be mentioned in a Run-Time Dependencies section in the deployer's guide, and that the .conf file mention it too, and that there's a sensible message printed when the runtime dependencies are not met -- little things that can make some future deployer's life easier.

**Comment by adriaandegroot** [comment]
For hacktoberfest:
 - polish up the documentation inside calamares repo
 - polish deployer's guide in the calamares wiki
 - add (once-only) warning when ckbcomp isn't installed

**Comment by erikdubois** [comment]
I would appreciate it ...
and I do appreciate your help 
thanks again

**Comment by abucodonosor** [comment]
@adriaandegroot  well I did not close this one ..

What do you mean by a run-time warning ? one in UI ? or a cDebug() ?

**Comment by abucodonosor** [comment]
@adriaandegroot  maybe this?

https://github.com/abucodonosor/calamares/commit/055e3ad46efa6770be656420d711b93c1f36c367

**Comment by adriaandegroot** [comment]
Fixed in 9b5772c4820f3bda81e0ec3680162261cfc16185, thanks @abucodonosor
