### ISSUE TITLE
Explain howto setup branding in deployer's guide

### ISSUE THREAD

**Issue by archmerge** [calamares/calamares#841]
Is there a manual/documentation about making the installer look good or did I miss it.

All info you have about the show.qml would be great.
Heard something about writing more documentation for users
Can this be on the list? If it does not exist yet.
Maximize images, text on top of image...

**Comment by abucodonosor** [comment]
@archmerge this is the **issue** tracker not an forum. If you wish to talk about things
then please on freenode , #calamares.

This place is only for reporting bugs or requesting features.

See: 

```
https://github.com/calamares/calamares/tree/master/src/branding
https://github.com/calamares/calamares/tree/master/src/branding/default
```

**Comment by adriaandegroot** [comment]
Well .. it's a QML slideshow, I think that's fairly firmly *outside* of the documentation of Calamares itself. Perhaps one of the downstreams has something that is useful as an example. In Calamares proper, with default branding, everything is in `src/branding/default/show.qml`. It is all based on the QML Presentation systen

**Comment by archmerge** [comment]
I know but I also knew you were going to organize the Hacktoberfest. I hope to get a great documentation. Better than the one we can find here [qt docs](http://doc.qt.io/qt-5/)

**Comment by adriaandegroot** [comment]
"Please improve docs" still isn't a real issue, but this along with #904 have prompted me to heavily go over the branding examples and engine for 3.2 (branch *branding*, which isn't merged to master yet). There was a lot of polishing to be done, as well as some bugs to resolve.

Short term goal is to make it much nicer to create branding for Calamares, without forking Calamares.

Useful links to other example branding files:
 - https://github.com/KaOSx/calamares/tree/master/src/branding/kaos_branding
 - https://src.fedoraproject.org/cgit/rpms/calamares.git/tree/calamares-auto_de.ts
