### ISSUE TITLE
Cleanup bitness mess in bootloader

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#842]
Depending on bitness, EFI installations need different source- and target-filenames, and grub needs different options. A pattern that occurs in `src/modules/bootloader/main.py` is one where a dictionary is populated with values per bitness:

```
    d = {"32":"--with-32", "64":"--with-longer"}
    option = d[bitness]
```

This construction is repeated several times; it hurts readability since instead of doing a single if-ifelse cascade to set the relevant variables, they are spread out, there's the surprising dictionaries to process, and many path-constructions are duplicated.

For hacktoberfest, clean up that python code and simplify it to

```
    if bitness == "32":
        option = "--with-32"
        other_option = "--not-long"
    elif bitness == "64":
        option = "--with-longer"
        other_option = "--yes-long"
````

**Comment by Bezzy1999** [comment]
Hi @adriaandegroot I'd like to work on this should I just submit a pr?

**Comment by abucodonosor** [comment]
Hi @Bezzy1999 , yes just send a PR

**Comment by adriaandegroot** [comment]
This was done in 2aa5a14b514bf986445879e32b063b528ff20d7e, PR #843
