### ISSUE TITLE
find pythonqt issue

### ISSUE THREAD

**Issue by rezso** [calamares/calamares#857]
pythonqt needs python version declaration in build/python.prf:

`# Change this variable to your python version (2.6, 2.7, 3.3, ...)`
unix:PYTHON_VERSION=2.7

If I set PYTHON_VERSION to 3.6 (for example), qmake builds libPythonQt-Qt5-Python3.6.so and libPythonQt_QtAll-Qt5-Python3.6.so libraries, but the FindPythonQt.cmake in Calamares searches only libPythonQt-Qt5-Python3.so and libPythonQt_QtAll-Qt5-Python3.so libraries, so the result is NOTFOUND.

**Comment by adriaandegroot** [comment]
Do note that PythonQt is considered experimental, and has no useful modules (that I know of) using it. On the other hand, there's a separate issue asking to drop Boost::Python in favor of all modules in PythonQt, so there's a good reason to update the find-module.

**Comment by abucodonosor** [comment]
The reason for that is r451 upstream .. 

See https://sourceforge.net/p/pythonqt/code/451/

So if you use > r450 helll breaks
