### ISSUE TITLE
Calamares doesn't see raw disk device under qemu 

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#858]
Hi there,

I'm testing Calamares 3.1.7 and kpmcore 3.0.3 on an openSUSE Leap 42.3 based live CD with qemu, using the following command:

`qemu-system-x86_64 -cdrom /tmp/XFCE/GeckoLinux_STATIC_XFCE.x86_64-423.171102.0.iso -drive file=/root/image_file,format=raw,if=virtio -m 1800 -vnc :0 -enable-kvm`

`image_file` is an 8GB raw disk device, and it is visible via gparted and also to the old `yast2-live-installer` as an installation target. But Calamares can't see any disks:

![screenshot from 2017-11-03 12-05-56](https://user-images.githubusercontent.com/2692138/32387346-344e6b58-c092-11e7-9e7d-d758c7c8f0f8.png)

Sorry I can't easily attach the logs, since it's in qemu, but here's a screenshot of the relevant part:

![screenshot from 2017-11-03 12-19-55](https://user-images.githubusercontent.com/2692138/32387395-551a89f2-c092-11e7-8942-d35ff7d6844d.png)

Could this be related to #785 ?

**Comment by abucodonosor** [comment]
what is major:minor of your vda ?

**Comment by abucodonosor** [comment]
I guess you need update your KPMcore package .. See:

https://bugs.kde.org/show_bug.cgi?id=378607
#768

**Comment by geckolinux** [comment]
Ah, thanks for finding that bug. I guess I'll mark this closed, since it's not Calamares code.
