### ISSUE TITLE
Netinstall segfault

### ISSUE THREAD

**Issue by abucodonosor** [calamares/calamares#859]
#### Submission type

  - [x] Bug report

#### Steps to reproduce the problem

Have an empy or invalid groupsUrl , start calamares , on netinstall step
you'll see the 'Netinstall disabled:' error , click on next or back .. crash

BT:
http://paste.opensuse.org/view/raw/12146926

**Comment by abucodonosor** [comment]
@adriaandegroot 

Netinstall seems to have some more bugs.

 https://github.com/calamares/calamares/blob/master/src/modules/netinstall/NetInstallPage.cpp#L61

That seems wrong to me to return always true since this should 
return based on whatever m_groups is != nullptr. 

While that is always true we now go always true for  m_nextEnabled.

https://github.com/calamares/calamares/blob/master/src/modules/netinstall/NetInstallViewStep.cpp#L33
https://github.com/calamares/calamares/blob/master/src/modules/netinstall/NetInstallViewStep.cpp#L84

That should just return m_widget->isReady(). 
We should not allow 'next' step on broken data/url/syntax .. at that point 
the installation is broken and in fact not even isBackEnabled() should be 
allowed but a big read warning and cancel here , we are in 'no way out here' , 
nothing to fix from UIX other that tell 'Fatal ERROR go an check netinstall configuration files'

Not sure @kkofler will like that ?

Also we are missing to check whatever the URL/File isEmpy() / isValid() , has spaces etc

https://github.com/calamares/calamares/blob/master/src/modules/netinstall/NetInstallViewStep.cpp#L181
 
nor here:

https://github.com/calamares/calamares/blob/master/src/modules/netinstall/NetInstallPage.cpp#L130

So whatever crap is acceped even empty or broken syntax.

Also I noticed with an ``groupsUrl: file:///dev/null`` no check will trigger .. 
so I think we should check for 'file being character device' too?

**Comment by adriaandegroot** [comment]
There's two things crossed here:
 - whether the user receives valid netinstall groups data at **runtime**
 - whether the module is properly configured at, um, .. configure time

If the user receives no data, or bad data, that could mean many things: for instance, the wifi dropped between start of Calamares and the netinstall page. No problem, there's no data but you can go back, next, and try again (poor UI, but possible). That crash is fixed (nullptr dereference).

Whether a given URL is valid is, as far as I'm concerned, up to the deployer and QNetworkManager.

I've introduced a configuration option to distinguish "this distro **must** have a complete netinstall or the finished system will be broken" and "this distro **likes** a netinstall, but the system is usable without".
