### ISSUE TITLE
Calamares screen size does not fit in

### ISSUE THREAD

**Issue by tpgxyz** [calamares/calamares#863]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> 3.1.7

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> …

#### What do you expect to have happen when Calamares installs?

> …

#### Describe the issue you encountered

> Calamares window does not fit in vbox screen.
See here:
https://forum.openmandriva.org/t/set-course-for-3-03-release/1292/207?u=tpg
https://issues.openmandriva.org/show_bug.cgi?id=2256

Well this commit fixed this issue long time ago:
https://github.com/calamares/calamares/commit/b7a0b3930f18250085e65fc550943a71dd9f0ee4

Second, when "check: screen" in enabled in welcome.conf then Calamares throws an error that screen is too small even if screen size is 800x600.

#### Steps to reproduce the problem

> …

#### Include the installation.log:

> …

**Comment by adriaandegroot** [comment]
I would appreciate it if this issue contained the actual problems had (preferably with screenshots) rather than pointing to various other threads. Also note that I don't have an OpenMandriva setup to test your specific welcome screen configuration -- I'm pretty sure it fits with the default font sizes and everything that KDE Neon has, but you might have it set up differently.

**Comment by abucodonosor** [comment]
I do have one and was never able to reproduce .. No matter what mode 'Live' or 'Installer'
( BIOS or UEFI )  , I never saw this error.

**Comment by abucodonosor** [comment]
@adriaandegroot well even I cannot reproduce that the 'warning' is right .. we do this:

```
 bool enoughScreen = (availableSize.width() >= CalamaresUtils::windowPreferredWidth) && (availableSize.height() >= CalamaresUtils::windowPreferredHeight);

```

meaning we check for our preferred size not the minimum size and that ofc gives a warning

```
constexpr int windowMinimumWidth = 800;
constexpr int windowMinimumHeight = 520;
constexpr int windowPreferredWidth = 1024;
constexpr int windowPreferredHeight = 520;

```

**Comment by abucodonosor** [comment]
so I guess we want this ?:

```
diff --git a/src/modules/welcome/checker/RequirementsChecker.cpp b/src/modules/welcome/checker/RequirementsChecker.cpp
index 654434513..741802fb5 100644
--- a/src/modules/welcome/checker/RequirementsChecker.cpp
+++ b/src/modules/welcome/checker/RequirementsChecker.cpp
@@ -79,7 +79,7 @@ RequirementsChecker::RequirementsChecker( QObject* parent )
         bool hasPower = false;
         bool hasInternet = false;
         bool isRoot = false;
-        bool enoughScreen = (availableSize.width() >= CalamaresUtils::windowPreferredWidth) && (availableSize.height() >= CalamaresUtils::windowPreferredHeight);
+        bool enoughScreen = (availableSize.width() >= CalamaresUtils::windowMinimumWidth) && (availableSize.height() >= CalamaresUtils::windowMinimumHeight);
 
         qint64 requiredStorageB = CalamaresUtils::GiBtoBytes(m_requiredStorageGB);
         cDebug() << "Need at least storage bytes:" << requiredStorageB;

```

**Comment by benbullard79** [comment]
Here's a screen-shot of the error message. I get it every time unless I manually resize VBox screen myself. Users can only do this when booted to 'Live' if they use our 'Install' option things are much trickier as their screen cannot be resized and is stuck at 800x600.

This is using OM's VBox-5.1.30 but is the same with our VBox-5.1.26. I don't know if things work differently with Oracle's proprietary VirtualBox packages. Hope this helps.

OM=OpenMandriva.

**Comment by benbullard79** [comment]
Dadgummit! I forgot the screen-shot:

http://tinypic.com/usermedia.php?uo=bpRy0IYlPgM17O3TvaUHV4h4l5k2TGxc

**Comment by adriaandegroot** [comment]
Thanks (nice desktop behind the VirtualBox, btw). I could try claiming it's not a problem (tm), since the screen obviously says "installation can continue", but that red X is scary. You could switch off the check for screen size, which will silence the whole warning, too. 800x600 **is** kind of small for Calamares -- it pretty much guarantees that the partitioning widget will fall outside the screen, and you'll get really ugly scroll bars in various places.

That said, I think we need to polish this requirements-check-report a bit, so that it is less scary, and more clear that installation can proceed.

**Comment by benbullard79** [comment]
Good to know all that. FWIW this isn't a major issue to me. The point was made I think by Bero (Bernhard Rosenkranzer) that it would look bad for reviewers and new users. Colin and I agreed that would be a concern. But I myself have done plenty of installs with this. Getting rid of the red X would be great. I'm thinking the default screensize of VirtualBox should be larger for Calamares. Easy for me to say but apparently not so easy for developers to do.

**Comment by tpgxyz** [comment]
```


    xwininfo: Please select the window about which you
    would like information by clicking the
    mouse in that window.

    xwininfo: Window id: 0x2e00005 "OpenMandriva Lx Installer"
    Absolute upper-left X: 6
    Absolute upper-left Y: 31
    Relative upper-left X: 6
    Relative upper-left Y: 31
    Width: 800
    Height: 576
    Depth: 24
    Visual: 0x1b1
    Visual Class: TrueColor
    Border width: 0
    Class: InputOutput
    Colormap: 0x2e00004 (installed)
    Bit Gravity State: NorthWestGravity
    Window Gravity State: NorthWestGravity
    Backing Store State: NotUseful
    Save Under State: no
    Map State: IsViewable
    Override Redirect State: no
    Corners: +6+31 --6+31 --6--7 +6--7
    -geometry 800x576+0+0

```

**Comment by adriaandegroot** [comment]
In master this has changed in two ways:
 - icons are now more friendly
 - check is for the minimum size
The phrasing can probably still be improved. If you take a look at that, we could probably backport it.
