### ISSUE TITLE
[netinstall]: a main group with hidden and not hidden subgroup(s) cannot be selected 

### ISSUE THREAD

**Issue by abucodonosor** [calamares/calamares#864]
#### Submission type

  - [x] Bug report

#### Info regarding which version of Calamares is used, which Distribution

> v3.1.8

#### Describe the issue you encountered

> On a  group with at least one hidden subgroup  selected: true is ignored.
> The group is always unselected in UI.

#### Steps to reproduce the problem

> Use this minial yaml file
  > http://ftp.frugalware.org/pub/other/people/crazy/group-with-hidden-subgroup.yaml

**Comment by abucodonosor** [comment]
Seems that bug occurs only when the first subgroup is hidden.

**Comment by abucodonosor** [comment]
While playing with hidden in subgroups I've found even more broken things. 

When a normal Group with subgroups is de-selected all subrgoups are de-selected too.

When you have a Group with subgroups , from which at least one is hidden and selected 
on de-selecting the main Group the 'hidden' subgroup is still installed.
That doesn't make any sense since it should not matter whatever the subgroup 
is hidden or not , when the main group is gone it should just de-select everything 
like for normal Group with subgroups.

**Comment by adriaandegroot** [comment]
Hm. Didn't auto-close. @abucodonosor , please test and continue adding more corner cases to your netinstall testing.
