### ISSUE TITLE
Little typos in calamares-master.ts

### ISSUE THREAD

**Issue by ujdhesa** [calamares/calamares#866]
Hello,

It seems that calamare-master.ts has two little typos:

1. A punctuation space error in __Boost.Python error in job \"%1\".__

2. A (double) lowercase error in __Please install the kde konsole and try again!__ Both KDE and Konsole should be uppercase.

**Comment by adriaandegroot** [comment]
**Boost.Python** is a name, so that is not a typo. The other one is, good catch.
