### ISSUE TITLE
UEFI or BIOS Instillation 

### ISSUE THREAD

**Issue by rahmanshaber** [calamares/calamares#868]
can’t we ask user if he/she want to install OS with UEFI or BIOS.
If user choses UEFI then set the perttion table to GPT. Also give warning if they enable the UEFI in BIOS settings.
I think it should be the in the advance or first option in perttion section of Calamares.

**Comment by abucodonosor** [comment]
Hmm ? Not sure what do you mean.. ? 
 If you boot with BIOS you cannot do an UEFI install that won't boot .. 
and the other way around is broken too.

**Comment by philmmanjaro** [comment]
Calamares autodetects if it is loaded on a standard BIOS or UEFI setup. It will over either of it. This will ensure always a working system. Really don't know what you try to achieve with this request. Enlighten me here a little bit more.

**Comment by physkets** [comment]
As per the discussion on the Manjaro forum, what seems to be requested, is a prominently displayed "Indicator" that tells the user whether it's been booted in UEFI or legacy mode.

**Comment by abucodonosor** [comment]
@physkets 

partitions modules already tells ..

Also *really* what kind of indicator ?
HOW someone can forget what he boot too ?

**Comment by philmmanjaro** [comment]
@physkets: point me to that thread as we focus to have the same user experience on both modes. Why is a indicator needed?

**Comment by rahmanshaber** [comment]
Indicator is needed to get a better info of the instillation.
It will be helpful to new users and unlikely to install UEFI in there LAPTOPS.
Because desktop will to face the UEFI problems.
As LATEST laptop comes with a secure boot and UEFI enabled.

**Comment by abucodonosor** [comment]
@rahmanshaber 

I really don't know what you are about however and *again* calamares
does tell you on the 'partitions page' what mode are you on.

If you don't know what your hardware is set too .. 
well this is simple issue and is called 'PEBCAK'..
"Problem Exists Between Chair And Keyboard"..

To your secure boot and whatnot this doesn't belong to calamares.
A Distribution without secure boot support simple won't boot your UEFI 
secure boot enabled box.. 

The indicator you ask for  *could* be implemented in your Distribution grub menus..

```

if [ "${grub_platform}" = "efi" ]; then
   menuentry 'THIS IS UEFI MENU SO THEREFOR YOU ARE ON UEFI' {
            do_your_setup_here
   }
else
  menuentry 'THIS IS BIOS MENU SO THEREFOR YOU ARE ON BIOS' {
         do_your_setup_here
  }

fi

```

**Comment by physkets** [comment]
@philmmanjaro It is very long:
https://forum.manjaro.org/t/why-there-is-less-or-no-support-for-uefi-out-of-the-box-in-linux/35638/

**Comment by rahmanshaber** [comment]
because some people facing the same problem as i did.
and in that post we came to a conclusion that we need a UEFI or BIOS indicator.
and @abucodonosor i am only a user .I  do not understand where i put that code .
I am just pointing out my problem's solution.
I also did not saw any indicator what you are talking about.
