### ISSUE TITLE
hwclock issue prevents installation - calamares halts

### ISSUE THREAD

**Issue by erikdubois** [calamares/calamares#873]
#### Submission type

Hwclock prevents installation of calamares

#### Info regarding which version of Calamares is used, which Distribution

> 3.1.8 for ArchMerge and ArchMergeD

#### Steps to reproduce the problem

> it is an hardware issue - you need the hardware to reproduce

More information is being gathered by 2 users in this topic.

https://archmergeforum.com/viewtopic.php?f=30&t=56&p=706#p706

Could you change the code so IF an error occurs the user can bypass this procedure?
Check the solution our users have found? 

Thanks in advance

**Comment by abucodonosor** [comment]
well .. I would like to see the output of:

hwclock --test -D

and 

hwclock --systohc --utc -D

from such a box..

Also a full dmesg would be good to see..

**Comment by adriaandegroot** [comment]
@erikdubois Ignoring errors is easy. That's what your users have done (easier would have been to disable the hwclock module in Calamares config). There are two underlying questies:

 - does it matter if the hwclock can't be set (from the live system)? the module could easily drop the error and only copy `/etc/adjtime` if hwclock succeeds, but what's the effect on the resulting system?
 - could be introduce a way to report non-fatal errors? Right now (python) modules are all-or-nothing things, with any error reporting leading to immediate termination of Calamares.

70 isn't a documented return value from hwclock, so @abucodonosor asks for test and regular output for the systems where this is a problem. I'd add *also* distinguishing between the installed system and the live iso; there might be a difference there.

**Comment by archmerge** [comment]
I will post the questions on the forum.

**Comment by abucodonosor** [comment]
@erikdubois @archmerge 

Looks like there is no RTC at all on that box. From what I've read  only our friend HP :)) 
has a !Linux RTC implementation but seems like  some Toshibas have problems too.

However looking around for that particular model I've found some 'reported' issues
about failing RTC ( broken CMOS , BIOS confused by bad keyboard ( huh?) , etc).

@adriaandegroot  

how about we change hwclock to run test mode , grab the return code and on success we
run it for real on failure we print a debug message and continue ?

Other way would be to blacklist some vendors , or just run it an hope the best :))

**Comment by abucodonosor** [comment]
Ok this is not really our bug .. for the problem @erikdubois posted here is clear an 
ArchLinux kernel configuration BUG..

However there are really HP laptops with very broken RTC ( if at all supported on Linux ) 
therefor we should still try to workaround some sort and not error out.

@erikdubois I've posted about the kernel issues Arch has in your forum ( still waiting to moderator to approve the post )

**Comment by abucodonosor** [comment]
@adriaandegroot 

I got bored while traveling and re-wrote hwclock. Please have a look..

http://sigsegv.24-7.ro/~crazy/0001-hwclock-re-write.patch

**Comment by erikdubois** [comment]
Hi,

i follow it up
Everything approved.

Thanks for looking into it.

A just woke up Erik

Cheers

Erik

2017-12-12 23:44 GMT+01:00 abucodonosor <notifications@github.com>:

**Comment by kkofler** [comment]
> http://sigsegv.24-7.ro/~crazy/0001-hwclock-re-write.patch

Just one small nitpick: "method" should be spelled without 'e' in English.

**Comment by adriaandegroot** [comment]
I likeit. I'llapply to 3.1.x-stable w/ minor spelling fixes
