### ISSUE TITLE
contextual package removal

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#874]
#### Submission type

  - [x] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> neon

#### What do you expect to have happen when Calamares installs?

> Depending on what the user configures during installation certain packages need to get removed or need to explictly be prevented from being auto-removed (on Debian systems e.g. by preventing them from autoremoval with `apt-mark manual`). For example when installing in (legacy) BIOS mode 'grub-pc' must be installed while 'grub-efi' must be removed and vice versa for UEFI systems. Equally, depending on distribution preference unnecessary filesystem support packages may be removed. For example reiserfs may be supported, but it being largely unused these days, doesn't need to be in the installed system unless the user actually has a partition which requires its presence so 'reiserfsprogs' should be removed. Not doing so ultimately litters the final system and potentially slows down the initrd as FS helpers often add fsck parts to the initrd.

**Comment by abucodonosor** [comment]
Well for just Bios/UEFI this should be already possible with an small post-packages
modules, however if you start with removing packages based on FS(es)  choise 
things will get complicated.

**Comment by adriaandegroot** [comment]
As usual there's two parts to this:

 - does the global configuration hold enough information to be able to distinguish the contexts (e.g. is the context actually there, for jobs to work on?)
 - what does the contextual-removal module actually want to do?

A simple approach would be a module with configuration "run *this* script in EFI installs, and *that* script in BIOS installs"; that at least makes the context-distinction visible to all users of calamares. Or it could be a single script, run as a process-job, which does the detection itself.

**Comment by abucodonosor** [comment]
@adriaandegroot 

or we export all variables to a file , add some example modules and let Distros
write specific modules , which we can ofc add later on to Calamares.

Not only FS'es , BIOS vs UEFI but also GPU drivers , extra kernel modules and some
other things can be removed based on 'whatever the user installs' and based on
his HW..

**Comment by adriaandegroot** [comment]
Globalstorage already has a firmwareType which may be `efi` or `bios` (depending on the existence of `/sys/firmware/efi/efivars`, which I'm assured is the way to detect an EFI boot?). So any Python job module could do something based on that value.

I'm inclined to make a multiscript module, though, which will loop through globalstorage variables and run scripts (by injecting dummyprocess jobs) based on the values found there. That would help with the execution part, while offering a useful API for ViewModules to hook onto.
