### ISSUE TITLE
Suggestion squid.png in calamares

### ISSUE THREAD

**Issue by archmerge** [calamares/calamares#876]
- [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution
3.1.9
Just build calamares and there was this pink squid in top left since I last made it. That is new for me.

Why not use this one in your future releases... 

https://calamares.io/about/ - orange one
![squid](https://user-images.githubusercontent.com/31759042/34068035-58e276ac-e235-11e7-9e3c-97aabbbadc20.png)

Personally I will keep this logo of Calamares on the installer. No matter how proud I am about ArchMerge. I could use our logo. BUT Calamares is the one making our work so much easier. So a nice Calamares logo is a way to give credits to your hard work. 

Keep at it guys.

**Comment by philmmanjaro** [comment]
The change was made here: https://github.com/calamares/calamares/commit/452cefd482b67be484f82f2a38e30139db684085 Also especially noticed in the [release announcement](https://github.com/calamares/calamares/releases/tag/v3.1.9).

**Comment by adriaandegroot** [comment]
@archmerge Calamares now displays what you have configured as *productLogo* where previously it (re)used the *productIcon* for that spot. So it's your own configuration file that points to a pink squid, while the Calamares default branding ships that orange-ish installer logo you put in this bug report.

I recommend looking at your `branding.desc` file.
