### ISSUE TITLE
Pull #875 might had introduced a regression in handling partitions [kpmcore-3.2] 

### ISSUE THREAD

**Issue by philmmanjaro** [calamares/calamares#882]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

Calamares **v3.1.11-5** (incl. **kpmcore-3.2** branch) on Manjaro v17.1-rc3

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

When you select **erase disk** option you most likely will fail with **rsync error 11** (disk full).

#### What do you expect to have happen when Calamares installs?

kpmcore job should create and format and mount the partitions as needed

#### Describe the issue you encountered

Somehow the disk runs full during unsquash step. When you use **replace partition** or **manual partitioning** you're able to install.

#### Steps to reproduce the problem

Simply try to install your Distro using **erase** disk option. By reverting pull #875 this option is functional again. Most likely the regression is within 1b3ce39ffb93f6d355c5be9fd7ae44cc4ffff280.

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

* Log can be found [here](https://gist.githubusercontent.com/philmmanjaro/35345d961b15a4c428861e6c7652a4f9/raw/f273d73e3cedd0edbbb3d9979ba7f530d3183dcb/cal-3.1.11-5-erase-disk.txt). Somehow the **tmpfs** runs full, as the new partitions never get mounted ...
* Log with pull #875 reverted can be found [here](https://gist.githubusercontent.com/philmmanjaro/74fa37f11a6e1f15ded9b45c20cae5b3/raw/0d747ac2ab5fe3abbf4187a2cf0d1da38e05f6cf/cal-3.1.11-7-erase-disk.txt).
* **CAL** binaries can be found [here](https://sourceforge.net/projects/manjarodev/files/users/philm/calamares/)

**Comment by stikonas** [comment]
@philmmanjaro any chance you can try with FormatPartitionJob reverted? Just to make sure it is this commit and not creation of partition table.

My calamares only has partitioning module enabled, so I can't reproduce it yet...

**Comment by abucodonosor** [comment]
@philmmanjaro 

so I need stable branch+kpmcore-3.2 branch to reproduce ?

Btw maybe get my debug patch for this lsblk , and partitions jobs output , is hard to read as is.

https://github.com/abucodonosor/calamares/commit/79a183010ae789a3b876ba0b6be635f17280ccd7.patch

**Comment by philmmanjaro** [comment]
@stikonas: the regression got introduced via 806b84973aa3b364370fba223270a0a03ade6367. Seems you know your code best. So we have to find a way what might be wrong with the creation of the partition table code.

@abucodonosor: your lsblk patch need a rebase against the **kpmcore-3.2** branch.

**Comment by stikonas** [comment]
Strange, so far I don't see anything wrong with that commit... Don't see anything suspicious in the logs.

**Comment by abucodonosor** [comment]
@philmmanjaro 

try this one:

http://sigsegv.24-7.ro/~crazy/rebase-for-kpmcore-3.2-branch.patch

**Comment by abucodonosor** [comment]
@stikonas 

didn't looked yet at kpmcore code however something is confused ( from the logs ):

```
13:26:58 [1]: Creating new partition table of type "gpt" , uncommitted yet:
 QObject(0x7ff6ec007be0) 

```
hmm ?

**Comment by stikonas** [comment]
@abucodonosor don't think this is what causes this bug. Looks like some calamares debug output is incompatible with objects what kpmcore offers? In any case partition table gets created. And KPMcore CreatePartitionJob seems more or less identical to what was in Calamares job.

**Comment by philmmanjaro** [comment]
The question is more or less what get filled for `libcalamares.globalstorage.value("partitions")`, which is needed for the **mount** module. Partition table and partitions get created, however somehow not populated for later steps. Let me see if we can debug this a little more ...

**Comment by philmmanjaro** [comment]
Seems I found the issue now. When we check **CAL v3.1.11-8.1**, which reverts commit https://github.com/calamares/calamares/commit/806b84973aa3b364370fba223270a0a03ade6367, we get this:

```
08:28:26 [0]: Starting job "Create new 300MB partition on /dev/sda (ATA VBOX HARDDISK) with file system fat32." 
08:28:26 [0]: Starting job "Set flags on partition /dev/sda1." 
08:28:26 [0]: Starting job "Create new 12256MB partition on /dev/sda (ATA VBOX HARDDISK) with file system ext4." 
08:28:29 [0]: Starting job "Set partition information" 
08:28:29 [1]: Gathering UUIDs for partitions that exist now. 
08:28:29 [1]: QHash(("", "")("/dev/sda2", "810ef2d2-8732-4d4e-aa49-57f6eb96b017")("/dev/sda1", "B9A5-D8FD")) 
08:28:29 [1]: Writing to GlobalStorage["partitions"] 
08:28:29 [1]: "" mtpoint: "" fs: QVariant(QString, "unknown") ( QVariant(QString, "unknown") ) "" 
08:28:29 [1]: "/dev/sda1" mtpoint: "/boot/efi" fs: QVariant(QString, "fat32") ( QVariant(QString, "fat32") ) "B9A5-D8FD" 
08:28:29 [1]: "/dev/sda2" mtpoint: "/" fs: QVariant(QString, "ext4") ( QVariant(QString, "ext4") ) "810ef2d2-8732-4d4e-aa49-57f6eb96b017" 
08:28:29 [1]: FillGlobalStorageJob writing empty bootLoader value 
08:28:29 [0]: Starting job "mount" 
```
![cal-3 1 11-8 1-partitions](https://user-images.githubusercontent.com/5050022/34374401-f967e9a0-eaae-11e7-867f-d3d356beb422.jpg)

Full log [here](https://gist.githubusercontent.com/philmmanjaro/94d01b30ec6ba2c792451aad3b44ae74/raw/3b80e98e3c99df2ceb3addb096bd126888900058/cal-3.1.11-8.1-erase-disk.txt).

On the other hand, when we use commit https://github.com/calamares/calamares/commit/806b84973aa3b364370fba223270a0a03ade6367 in **CAL v3.1.11-5.1** the value **partitions** is empty somehow:

```
08:23:01 [0]: Starting job "Create new 300MB partition on /dev/sda (ATA VBOX HARDDISK) with file system fat32." 
08:23:01 [0]: Starting job "Set flags on partition /dev/sda1." 
08:23:01 [0]: Starting job "Create new 12256MB partition on /dev/sda (ATA VBOX HARDDISK) with file system ext4." 
08:23:04 [0]: Starting job "Set partition information" 
08:23:04 [1]: Gathering UUIDs for partitions that exist now. 
08:23:04 [1]: QHash() 
08:23:04 [1]: Writing to GlobalStorage["partitions"] 
08:23:04 [1]: FillGlobalStorageJob writing empty bootLoader value 
08:23:04 [0]: Starting job "mount" 
```

![cal-3 1 11-5 1-partitions](https://user-images.githubusercontent.com/5050022/34374457-351246f8-eaaf-11e7-95ba-c5ee4a70cdc1.jpg)

Full log [here](https://gist.github.com/philmmanjaro/b329a035f63459f8aa469d3542791262/raw/2dad5963d7b341af1a4197e718d4949397b6b245/cal-3.1.11-5.1-erase-disk.txt).

We have now to find out why that is and what the missing link might be ...

**Comment by stikonas** [comment]
@philmmanjaro Nice catch. With this information I have a suspected culprit line. Let me try something.

**Comment by stikonas** [comment]
@philmmanjaro Can you test this? I think it fixes global storage.

https://github.com/stikonas/calamares/commit/2027a5538e2e16f6d942c57154ed337de8ac4889

**Comment by abucodonosor** [comment]
@stikonas 

Well this strange ' table = QObject(.....) '  is exact the line you change now :)

I was investigating same code paths.. I guess I let you find out since you
should know the code best :)

**Comment by stikonas** [comment]
@abucodonosor well, table is still table = QObject(...) now, just different one.

**Comment by philmmanjaro** [comment]
@stikonas: your commit fixed it. Here the [log](https://gist.github.com/philmmanjaro/a52ca891d8ab2e3e9065b16720f17e81/raw/9880ce73c87a9311189dec9cddee249a1ab48be1/cal-3.1.11-5.2-erase-disk.txt). Also nice catch on the matter with the second table.

**Comment by stikonas** [comment]
Can you push my commit to calamares repo then?

On 27 December 2017 15:17:51 GMT+00:00, "Philip Müller" <notifications@github.com> wrote:
>@stikonas: your commit fixed it. Here the
>[log](https://gist.github.com/philmmanjaro/a52ca891d8ab2e3e9065b16720f17e81/raw/9880ce73c87a9311189dec9cddee249a1ab48be1/cal-3.1.11-5.2-erase-disk.txt).
>Also nice catch on the matter with the second table.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/calamares/calamares/issues/882#issuecomment-354128143

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by philmmanjaro** [comment]
@stikonas: done via 2027a5538e2e16f6d942c57154ed337de8ac4889

**Comment by stikonas** [comment]
Thanks! Hopefully there are no more regressions from this calamares/kpmcore code deduplication.
