### ISSUE TITLE
can't delete calamares packages after os installation

### ISSUE THREAD

**Issue by alick01** [calamares/calamares#885]
#### Submission type

  - [x ] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

>3.1.1.1

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> …

#### What do you expect to have happen when Calamares installs?

> …

#### Describe the issue you encountered

> …

#### Steps to reproduce the problem

>
![screenshot_20171227_115758](https://user-images.githubusercontent.com/3515303/34383885-87577526-eb29-11e7-9201-4bfbe6a2450f.png)
can't delete calamares packages after os installation

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

> …

**Comment by abucodonosor** [comment]
First of all what kind bug report is that ? Are you serious about ?

We don't have any pisi package backend so nothing to fix for us.
If you want pisi support open an feature request and / or an PR
but don't open bug reports about your(?) own broken code , right ?

**Comment by alick01** [comment]
ok
