### ISSUE TITLE
Support for PisiLinux package manager

### ISSUE THREAD

**Issue by alick01** [calamares/calamares#886]
#### Submission type

  - [ ] Bug report
  - [ x] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

>calamares 3.1.11 distribution PisiLinux

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> …

#### What do you expect to have happen when Calamares installs?

> …

#### Describe the issue you encountered

> …

#### Steps to reproduce the problem

> …We need help for installing PisiLinux os in UEFİ mode with live iso.We sucsess many things Live system installed and working but can't delete calamares packages after os disk installation.
![screenshot_20171227_115758](https://user-images.githubusercontent.com/3515303/34385565-bf6b3ba4-eb34-11e7-8768-8aacfef56a4b.png)

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

> …system don't create log

**Comment by philmmanjaro** [comment]
Upstream module **[packages](https://github.com/calamares/calamares/blob/master/src/modules/packages)** don't yet support **pisi**. Please contact @Rmys from Pisi-Linux on how you got the error.

**Comment by abucodonosor** [comment]
@philmmanjaro 

Yes told him that in https://github.com/calamares/calamares/issues/885 already.

Someone has to add that 'pisi' support first..

**Comment by alick01** [comment]
we want support for installing Pisilinux iso with calamares.There is a bug for deleting calamares packages after installation Pisilinux os.Our pisi packages manager works fine

**Comment by abucodonosor** [comment]
@alick01 

We got that , you just don't get , 'Calamares' doesn't *have* yet psi support at all.
So is up2 you ( or someone motivated to install PISI linux and mess with it )
to send us an 'patch' adding pisi support to 'our packages module'.

**Comment by abucodonosor** [comment]
Right now you complain about Calamares being broken with 'code we do NOT have'

So at least _show_ us your PSI support module or patch ?

Also while from your screenshot is see:

psi rm ..

the wiki tells is:

pisi remove ...

However I've never used pisi so not a clue about

**Comment by abucodonosor** [comment]
Oh and 'there is no log can't be true'.. Strat calamares from terminal then

pkexec calamres -d >log

or

sudo -E calamares -d >log

**Comment by philmmanjaro** [comment]
You can also review our [postcfg](https://github.com/manjaro/calamares/tree/development/src/modules/postcfg) module, which uses pacman to remove **Calamares** if present on target installation. Similar may apply to **pisi**. However, the upstream module **packages** don't yet support **pisi** at all.

**Comment by abucodonosor** [comment]
I also found this:

https://github.com/pisilinux/PisiLinux/wiki/Pisi-Linux-Commandline-usage

@alick01 

are these commands still right ?

**Comment by abucodonosor** [comment]
Also according to this wiki it should be *pisi-cli* and not *pisi* also I cannot
find any command to just update the database without to trigger an full
update..

**Comment by abucodonosor** [comment]
Also this may work:

```

diff --git a/src/modules/packages/main.py b/src/modules/packages/main.py
index 14b4318b2..e4e8c9dad 100644
--- a/src/modules/packages/main.py
+++ b/src/modules/packages/main.py
@@ -152,6 +152,22 @@ class PMPackageKit(PackageManager):
     def update_db(self):
         check_target_env_call(["pkcon", "refresh"])
 
+class PMPisi(PackageManager):
+    # from https://github.com/pisilinux/PisiLinux/wiki/Pisi-Linux-Commandline-usage
+    backend = "pisi"
+
+    def install(self, pkgs, from_local=False):
+        for pkg in pkgs:
+            check_target_env_call(["pisi", "install", pkg])
+
+    def remove(self, pkgs):
+        for pkg in pkgs:
+            check_target_env_call(["pisi", "remove", pkg])
+
+    def update_db(self):
+        # Fixme ? no idea whatever this is OK , maybe just pass ?
+        check_target_env_call(["pisi", "update-repo"])
+        # pass
 
 class PMZypp(PackageManager):
     backend = "zypp"
diff --git a/src/modules/packages/packages.conf b/src/modules/packages/packages.conf
index 2d6ca116f..672b566ca 100644
--- a/src/modules/packages/packages.conf
+++ b/src/modules/packages/packages.conf
@@ -2,6 +2,7 @@
 #
 # Which package manager to use, options are:
 #  - packagekit  - PackageKit CLI tool
+#  - psi         - Pisi Cli ?
 #  - zypp        - Zypp RPM frontend
 #  - yum         - Yum RPM frontend
 #  - dnf         - DNF, the new RPM frontend

```
there as an patch:
http://sigsegv.24-7.ro/~crazy/pisi-backend-from-wiki-commands.patch

Not tested ( since I can't ) and writen over my mobile phone

**Comment by shadeslayer** [comment]
Wouldn't it make more sense to hook into packagekit instead ?

**Comment by abucodonosor** [comment]
@shadeslayer 

This is up2 the Distros whatever they do / use , PK support is there..

Also I have no idea whatever PK supports PISI ?

**Comment by alick01** [comment]
Yes we still and forever use the pisi package system. I will say this solution to my developer.

**Comment by abucodonosor** [comment]
@alick01 

can you test that patch ?

**Comment by alick01** [comment]
[Calamares.log](https://github.com/calamares/calamares/files/1589762/Calamares.log)
we use patch but calamares modules doesn't delete.thıs is log.
we don't use any option for pisi remove but "pkcon", "-py", "remove" use option -py
we can only use pisi -y remove
now pisi developer try this option

**Comment by abucodonosor** [comment]
@alick01 

I really don't get you .. you mix packagekit with psi commands ?

psi remove <package> is documented , psi rm <package> NOT .. and again
can you test _my_ patch and nothing else please ? 

If you refuse to post whatever custom things you use and refuse to test things
I'll go an close this and won't care anymore about until 'you' or any of your
developers contribute the code to have that support , OK ?

**Comment by alick01** [comment]
yes we test your patch but nothing
our package manager cli is not psi true word is pisi where do you see psi

**Comment by abucodonosor** [comment]
Uhmm what ?

From your screenshot you are using 'backend = *psi*' ( which is not upstream )
From your LOG:

```

2017-12-27 - 16:46:52 [0]: Running "chroot" ("/tmp/calamares-root-dujocgjc", "pisi", "rm", "Calamares") 
2017-12-27 - 16:47:11 [0]: Finished. Exit code: 1 
2017-12-27 - 16:47:11 [0]: Target cmd ("pisi", "rm", "Calamares") 
```
so that _is_ not my patch but whatever else you are using , right ?

And now you tell : 'we use pisi  backend ( custom patches ) and ohh we don't
use pisi cli but something different' ?!? what ? '

So last try here:

1) describe what you are using and what package manager support you want
2) post your custom patches here if you wish any help
3) mixed packages manager support 'does NOT' work
   ( for that kind things see what @philmmanjaro  told you )
4) always post installation / debug logs

**Comment by abucodonosor** [comment]
Trying to decode ...

"pkcon", "-py", "remove" <-- so what you wish is packagekit ?
we can only use pisi -y remove <-- broken PK support for pisi ? ( not our bug )

**Comment by V3n3RiX** [comment]
Merhaba arkadas,

Digerleri soyledigi gibi su anda Calamares pisi ile calismaz bir durumda. Nedeni cok basit, pisi arka ucu yazilmamis. Pisi Linux'u yapan dosta soyle iki seceneyi var : 
- ya pisi arka ucu yazar
- ya baska bir arka uc kullanir, mesela packagekit

Ikinci secenek calisabilir, ama sadece Pisi Linux'un kendisi PackageKit'i kullanabiliyorsa. Yok kullanamiyorsa, pisi arka ucunu yazmak cok basit bir is. Eger lazim ise, yardim edebilirim.

**Comment by philmmanjaro** [comment]
@alick01 and @V3n3RiX what I see from the screenshot is this:

* the backend **pisi** was configured in the config file for **packages** module
* the cmd `pisi rm Calamares` was executed by **packages** module and failed
* the source code used is unknown to us

To solve the matter:

* we need the modified source of **packages** module to review. This you can find on your install media, as python modules are the source code
* most likely the package is called **calamares** and therefore **Calamares** will fail as not existing. What happens if you call `pisi rm Calamares` in live-session? What would be the output?

@abucodonosor: your patch might work. You called the backend **pisi** but had a typo in config file: **psi**. As @alick01 seems to be a user and not a developer, he most likely is the wrong person to talk to. I assume he simply reported a found issue on his end we can't do any about it, without having a code for review.

**Comment by bionel** [comment]
There seems to be two issues there, looking at the log provided:

> 2017-12-27 - 16:47:11 [0]: Target cmd ("pisi", "rm", "Calamares") 
> 2017-12-27 - 16:47:11 [0]: Target out "The following list of packages will be removed\nin the respective order to satisfy dependencies:\nCalamares \n\u001B[01;32mRemoving package Calamares\n\u001B[0mRunning pre removal operations for Calamares\n\u001B[01;31mProgram terminated.\n\u001B[0m\u001B[01;31mCannot connect to COMAR: \n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket

- the comand it is wrong (i cannot found any "rm" option in any pisi doc/source code, the right command seems to be "pisi remove <pkg>" as in the provided patch)
- the call it is also raising a 'socket exception' (asuming i am looking into the right code of the package manager used). This may indicate wrong permissions or/and wrong backend/module implementation:
https://github.com/SolusOS-discontinued/pisi/blob/master/pisi/comariface.py#L88

**Comment by adriaandegroot** [comment]
In master / Calamares 3.2 the output of this kind of commands called from Python is improved -- see issue #865. So that would improve the situation a little.

I'm all for including a pisi package manager class in the packages module. It just needs someone to say what the commands should be, exactly -- and @abucodonosor's example patch can be used as-is for testing.

Removing Calamares after installation is a special case: if you're installing to a target system, why are you installing Calamares there? And if you are doing something like an OEM mode, either the *packages* module should be used, or Netrunner's *deferred_remove* can serve as inspiration.

If your package manager needs DBus to be up-and-running, then that is a big complication: the target system might not even be complete yet, and it hasn't booted, so there's no DBus to be found in there. In the live system, or an OEM mode, you don't have that complication (but why bother deinstalling in a live system, and OEM mode is special anyway).

[[ Partly related question: where **are** Pisi-Linux resources to be found? All of the sites seem to be down, broken, or unmaintained. The link from Calamares.io now goes to a deleted Wordpress site. ]]

**Comment by V3n3RiX** [comment]
@philmmanjaro 

In my previous message I just sumarized in turkish language what you guys already told @alick01 . I was asked to do so by @abucodonosor .

**Comment by philmmanjaro** [comment]
@V3n3RiX: all good. However we have to find a proper solution for **PISI** in general. When we can help, we help.

**Comment by alick01** [comment]
thıs ıs output;
pisilive@pisilinux: ~ $ sudo pisi rm Calamares
The following list of packages will be removed
in the respective order to satisfy dependencies:
Calamares 
Removing package Calamares
Running pre removal operations for Calamares
Running post removal operations for Calamares
Removed Calamares
pisilive@pisilinux: ~ $

**Comment by bionel** [comment]
@adriaandegroot 

> Removing Calamares after installation is a special case: if you're installing to a target system, why are you installing Calamares there? And if you are doing something like an OEM mode, either the packages module should be used, or Netrunner's deferred_remove can serve as inspiration.

It make sense in some cases to remove Calamares, e.g redcore linux: during the install, it is unpacking the squashfs, same used for live boot, to the chroot, and after it is removing uneeded packages related to live media. Not the best scenario but it works.

@alick01 so, from the live system, seems like the "sudo pisi rm Calamares" works. That lead's to the second issue, the bus socket needed. You cannot expect some commands running on a live system to work exactly the same into an chrooted environment, where, as already mentioned, you have no running services at the "calamares install" time.

So, will be of a great help if the source code of the actualy package manager used is provided, and also how you and your developpers are trying to implement calamares. An up-to-date iso may help also, we can look into it and do some manualy digging.

**Comment by aligulle1** [comment]
V3n3RiX  bız packagekit konusunu beceremedık dedıgın gıbı bu konuda bıze yardımcı olursanız seviniriz

**Comment by V3n3RiX** [comment]
Uzerinde calistiginiz bir ISO var mi acaba? Onu indirip daha yakindan bakip, yardim edebiliriz. Gereken kodu yazabiliriz.

**Comment by aligulle1** [comment]
V3n3RiX https://transfer.sh/m7BZF/Pisilinux-KDE5-UEFI-LIVE-x86_64.iso bu var kalamarı kaldıramadıgımızdan 3 sqfs dosyası oluşturup 2 nı kuruyorduk

**Comment by V3n3RiX** [comment]
Bu ISO'nun icinde calamares var ise, yeterli olabilir. Eger ki yoksa, icinde calamares olan bir ISO hazirlamani rica ederim.

**Comment by aligulle1** [comment]
V3n3RiX  var abı calamares sadece kaldıramadıgımızdan ısoyu 3 sqfs ye bolup calamaresin unpackfs.conf ıle 2 sını kurduk

**Comment by aligulle1** [comment]
V3n3RiX  var abı calamares sadece kaldıramadıgımızdan ısoyu 3 sqfs ye bolup calamaresin unpackfs.conf ıle 2 sını kurduk

**Comment by aligulle1** [comment]
V3n3RiX  var abı calamares sadece kaldıramadıgımızdan ısoyu 3 sqfs ye bolup calamaresin unpackfs.conf ıle 2 sını kurduk

**Comment by V3n3RiX** [comment]
Anladim...bu ISO'da sorun yok...tek sqfslik bir ISO lazim. :) Onu hazirlarsan, tekrar test edebilirim.

**Comment by aligulle1** [comment]
V3n3RiX hemen hazırlarım abi

**Comment by philmmanjaro** [comment]
I just downloaded the ISO and reviewed it. Similar to Manjaro it has three layers:

* rootfs.sqfs
* desktop.sqfs
* livecd.sqfs

When **Calamares** is installed in **livecd.sqfs** (which is true in this case) a removal is not needed/possible, as not installed in target system at all.

@alick01: so I don't get your issue here at all. Sure **pisi** package manager is not yet support, however for this case not needed, as there is no case at all for the need to remove **Calamares** as with given situation ...

**Comment by V3n3RiX** [comment]
The three layer setup of the ISO is a workaround from their part, in order to make things work, since they didn't manage to make pisi to work. Their intended goal is to have one layer ISO, and they want/need pisi suport in calamares.

**Comment by bionel** [comment]
@V3n3RiX aha, so that is completely different story.
Help for implementing a sane package manager and a proper ISO layout it is needed.

**Comment by philmmanjaro** [comment]
Well, we need an ISO with the final structure and the current code they had developed. When we then get also the right documentation, we might try to help you guys from upstream side. However the developers from **PISI** might need to step up and try to communicate also in English. If not, @V3n3RiX you seems to be the middle man here :smile_cat:

**Comment by V3n3RiX** [comment]
I requested them a one layer ISO, they said they will bake it and make it available for us to play with.

**Comment by bionel** [comment]
![67699b623ebffa3bdd571109e805c236](https://user-images.githubusercontent.com/2083469/34420464-567b41a0-ec12-11e7-96e6-1349164101b6.jpg)

**Comment by aligulle1** [comment]
V3n3RiX elektrık kesıntılerı yuzunden ancak yukleye bıldık https://transfer.sh/jZvQh/Pisilinux-KDE5-UEFI-LIVE-x86_64.iso depo guncelleme pisi ur dosya sılme pisi rm -y dosys ısmı kurma pisi it -y dosya ısmı etc/calamaras/setting.conf da package modulunueklemedık sız buraya - packageyı ekleyıp ıstedıgınız gıbı calışabılırsınız abi

**Comment by erkanisik1** [comment]
Hii
Pisilinux iso download link > https://transfer.sh/jZvQh/Pisilinux-KDE5-UEFI-LIVE-x86_64.iso
pisi commands
repository update : pisi ur
delete file       : pisi rm -y 
install file      : pisi it -y filename.pisi

etc/calamaras/setting.conf package did not add modul, you can add the package here and run it as you like.

**Comment by abucodonosor** [comment]
OK so what kind 'pisi' is that? own fork ? re-write ? mixup ? 

Wiki of older pisi don't tell anything about these commands.

Anyway I'm going to have a look tomorrow

**Comment by erkanisik1** [comment]
**P**ackages **I**nstalled **S**uccessfully as **I**ntended 
https://tr.wikipedia.org/wiki/PiSi_Paket_Y%C3%B6neticisi

**Comment by alick01** [comment]
we usually use abbreviation for command update-repo > ur update-packages > up remove >rm
whole set of command;
pisilive@pisilinux: ~ $ pisi help
usage: pisi [options] <command> [arguments]

where <command> is one of:

           add-repo (ar) - Add a repository
              blame (bl) - Information about the package owner and release
              build (bi) - Build PiSi packages
                   check - Verify installation
                   clean - Clean stale locks
  configure-pending (cp) - Configure pending packages
       delete-cache (dc) - Delete cache files
              delta (dt) - Creates delta packages
       disable-repo (dr) - Disable repository
             emerge (em) - Build and install PiSi source packages from repository
         emergeup (emup) - Build and install PiSi source packages from repository
        enable-repo (er) - Enable repository
              fetch (fc) - Fetch a package
                   graph - Graph package relations
                help (?) - Prints help for given commands
            history (hs) - History of pisi operations
              index (ix) - Index PiSi files in a given directory
                    info - Display package information
            install (it) - Install PiSi packages
     list-available (la) - List available packages in the repositories
    list-components (lc) - List available components
     list-installed (li) - Print the list of all installed packages
        list-newest (ln) - List newest packages in the repositories
      list-orphaned (lo) - List orphaned packages
       list-pending (lp) - List pending packages
          list-repo (lr) - List repositories
       list-sources (ls) - List available sources
      list-upgrades (lu) - List packages to be upgraded
        rebuild-db (rdb) - Rebuild Databases
             remove (rm) - Remove PiSi packages
    remove-orphaned (ro) - Remove orphaned packages
        remove-repo (rr) - Remove repositories
             search (sr) - Search packages
        search-file (sf) - Search for a file
        update-repo (ur) - Update repository databases
            upgrade (up) - Upgrade PiSi packages

Use "pisi help <command>" for help on a specific command.


Options:
 --version                    : show program's version number and exit
 -h [--help]                  : show this help message and exit

 general options:
  -D [--destdir] arg          : Change the system root for PiSi commands
  -y [--yes-all]              : Assume yes in all yes/no queries
  -u [--username] arg         
  -p [--password] arg         
  -L [--bandwidth-limit] arg  : Keep bandwidth usage under specified KB's
  -v [--verbose]              : Detailed output
  -d [--debug]                : Show debugging information
  -N [--no-color]             : Suppresses all coloring of PiSi's output
and pisi help remove or pisi help rm;
pisilive@pisilinux: ~ $ pisi help rm
remove (rm): Remove PiSi packages

Usage: remove <package1> <package2> ... <packagen>

Remove package(s) from your system. Just give the package names to remove.

You can also specify components instead of package names, which will be
expanded to package names.


Options:
 --version                    : show program's version number and exit
 -h [--help]                  : show this help message and exit

 remove options:
  --ignore-dependency         : Do not take dependency information into account
  --ignore-comar              : Bypass comar configuration agent
  --ignore-safety             : Bypass safety switch
  -n [--dry-run]              : Do not perform any action, just show what would
                                be done
  --purge                     : Removes everything including changed config
                                files of the package
  -c [--component] arg        : Remove component's and recursive components'
                                packages

 general options:
  -D [--destdir] arg          : Change the system root for PiSi commands
  -y [--yes-all]              : Assume yes in all yes/no queries
  -u [--username] arg         
  -p [--password] arg         
  -L [--bandwidth-limit] arg  : Keep bandwidth usage under specified KB's
  -v [--verbose]              : Detailed output
  -d [--debug]                : Show debugging information
  -N [--no-color]             : Suppresses all coloring of PiSi's output

**Comment by erkanisik1** [comment]
hii 
https://transfer.sh/jZvQh/Pisilinux-KDE5-UEFI-LIVE-x86_64.iso incorrect iso
https://transfer.sh/9Hvqy/Pisilinux-KDE5-UEFI-LIVE-x86_64.iso actually iso

**Comment by adriaandegroot** [comment]
What is the status here? I've downloaded an ISO, I think I got the *actually iso* linked above.

```
SHA256 (Pisilinux-KDE5-UEFI-LIVE-x86_64.iso) = df4737b4b607f9d1880ef66e8373b4f066137844ea002c0e1fe5f81fea7b0bd0
```

I like Kaptan on startup; it does a lot of nice work guiding through the UI possibilities. I can't read Turkish, so it's a bit tough to navigate.

Anyway, the calamares config on that ISO doesn't include the package module -- @erkanisik1 says so earlier -- but even if I add that, there's no pisi support in the package module that is on that ISO. In Calamares *master* I have just added a pisi package manager class in the packages module, based on some guesses from running pisi in the live environment. So you might want to try that -- whatever experiment you have to use the package manager module, copy in the latest version from Calamares master, set the package manager backend to `pisi` and see what happens.

(Aside, clicking on the "Pisi Linux Wiki" link in the window labeled *Pisi Linux'a Hosgeldiniz* which comes up after going through Kaptan, that leads to a plesk domain-configuration site. So the Pisi online presence is a bit broken.)

**Comment by adriaandegroot** [comment]
.. so, leaving the issue open for a bit, but right now it's back to you guys: in principle youi can use pisi package manager now.

**Comment by erkanisik1** [comment]
hii...

team will try and return

**Comment by erkanisik1** [comment]
hii...
Checking "tr_TR" in "/usr/share/locale" 
00:34:16 [1]: Job file "/usr/lib/calamares/modules/packages/main.py" 
00:34:16 [1]: Job description from pretty_name "packages" = "Paketleri yükle" 
00:34:16 [0]: Installation failed: 
00:34:16 [0]: - message: "Bad backend" 
00:34:16 [0]: - details: "backend=\"pisi\"" 
00:34:16 [0]: Calamares will quit when the dialog closes. 
00:34:16 [1]: FinishedPage::setUpRestart()
gave an error

**Comment by adriaandegroot** [comment]
@erkanisik1 Did you use Calamares *master*? You'll have to compile that yourself. There are probably no packages for it yet. In my tests of master, setting the backend to "pisi" does work.

You can check if your configuration is OK with the `testmodule.py` script which you can run from the Calamares build directory:

```
~/src/calamares/build> PYTHONPATH=`pwd`: python3 ../src/modules/testmodule.py packages - src/modules/packages/packages.conf 
Testing module in: src/modules/packages
No global configuration loaded.
Local configuration 'src/modules/packages/packages.conf' loaded.
('Bad backend', 'backend="pisy"')
```

Here you can see I have written "pisi" wrong; if I **do** set it to use "pisi", then it does not complain about the backend.

**Comment by aligulle1** [comment]
Installation failed: 
22:25:33 [0]: - message: "Boost.Python iş hatası \"packages\"." 
22:25:33 [0]: - details: "<div><strong>Command 'pisi remove -y Calamares' returned non-zero exit status 1.</strong></div><div>The following list of packages will be removed\nin the respective order to satisfy dependencies:\nCalamares \n\u001B[01;32mRemoving package Calamares\n\u001B[0mRunning pre removal operations for Calamares\n\u001B[01;31mProgram terminated.\n\u001B[0m\u001B[01;31mCannot connect to COMAR: \n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n  org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory\n\n\u001B[0mPlease use 'pisi help' for general help.</div><div><br/>Traceback:</div><div><pre>File &quot;/usr/lib/calamares/modules/packages/main.py&quot;, line 467, in run\n    run_operations(pkgman, entry)\n\n  File &quot;/usr/lib/calamares/modules/packages/main.py&quot;, line 400, in run_operations\n    pkgman.remove(entry[key])\n\n  File &quot;/usr/lib/calamares/modules/packages/main.py&quot;, line 261, in remove\n    check_target_env_call([&quot;pisi&quot;, &quot;remove&quot;, &quot;-y&quot;] + pkgs)\n\n  File &quot;&lt;string&gt;&quot;, line 47, in &lt;module&gt;</pre></div>" 
22:25:33 [0]: Calamares will quit when the dialog closes. 
22:25:34 [1]: FinishedPage::setUpRestart()

**Comment by philmmanjaro** [comment]
@pisi-developers: This issue is somehow ongoing a long time now. The cal-developers tried to create the needed **pisi** package manager backend. In theory it kinda works. However I see some lack of packaging and creating a proper ISO to provide the needed basis of the now new created code we have added to the **master** branch of **Calamares** (CAL).

So what is still missing?

- How to create a proper package of our git-code?
- A proper ISO supporting CAL as needed?
- A missing functionality the CAL developers might have missed?

Based on the last error message some issues with **dbus** might exist.

So what is the status on the example ISO the Pisi Linux Project might provide to us CAL developers? And we need to have English as default language to help you out. Non of us understand Turkish by the way.

**Comment by kkofler** [comment]
So, according to your error messages, the `pisi` command relies on D-Bus to do its work. This is an issue because D-Bus typically does not work in a chroot environment. (This is also why Calamares cannot rely, e.g., on `timedatectl`.)

**Comment by adriaandegroot** [comment]
You can run Calamares through sudo -E, for instance, to keep the DBus environment variables around; that way it can talk to the (live session?) DBus. The Plasma LNF module soft-of needs the same, since it runs the lnftool in the live session to give a live preview, which needs DBus to inform the running Plasma of the change.

But obviously there's no dbus running in the target system yet at this point.

**Comment by adriaandegroot** [comment]
Looking back at the comments from december 28th, where @abucodonosor had already written a patch to add pisi to the packages module (and what was added to master later is basically his code). We can see the same COMAR error happening there as well. So I'd say at this point it's up to you (Pisi Linux) guys to make sure that the target system is in shape to run the package manager at the time the packages module is executed by Calamares.

**Comment by V3n3RiX** [comment]
Ok, I’m the only one in here who speaks turkish, but I cannot help you guys if you don’t do what is asked for and come back with feedback.

**Comment by aligulle1** [comment]
V3n3RiX
bize ıletişim konusunda yardımcı ol ıngılızce bılınler su an burda yok translete ıle anlamaya cslışıyoruz

**Comment by V3n3RiX** [comment]
Calamares ekibindeki arkadaslar ellerinden geleni yaptilar. Pisi arka ucu
yazildi. Artik siz bunu test etmelisiniz. Gonderdigin mesajlardan anladigim
kadar, pisi kendi kendine calisamiyor, Komar diye dbus uzerinden bir arka
uc kullaniyor. Eger bu dogru ise, Pisi'yi calamares uzerinden calistirmak
bir az zor olur, cunku calamares dbus kullanamiyor.

English translation for others :

The calamares team did what they could to help you. The pisi backend was
written. From now on it's up to you to make it work. From your previous
messages, we understand that pisi cannot work on it's own, but uses komar
and dbus. If this is true, pisi would be rather difficult to properly
implement in calamares, since calamares itself doesn't start a dbus session.

**Comment by aligulle1** [comment]
V3n3RiX 
calamar ekipine teşekur ederiz

**Comment by alick01** [comment]
we will go on the solution of the problem thanks calamares team
