### ISSUE TITLE
Calamares should only allow installing bootloader on (KPMcore) DiskDevices

### ISSUE THREAD

**Issue by stikonas** [calamares/calamares#887]
#### Submission type

  - [x] Bug report
  - [x] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> Manjaro 17.1 rc4 (Calamares 3.1.x with kpmcore-3.2 patches)

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> /dev/sda contains a single LVM PV partition. I created a single LVM volume group containing /dev/sda1. (LVM Volume Group and LVM PV were created in advance with KDE Partition Manager)

#### What do you expect to have happen when Calamares installs?

> Only /dev/sda is listed in bootloader location combobox

#### Describe the issue you encountered

> All Devices are listed there, including LVM devices.

**Comment by adriaandegroot** [comment]
Fixed with merge of Caio's branch.
