### ISSUE TITLE
Calamares 3.1.11 path to grubx64.efi is wrong for openSUSE

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#890]
Hi, I'm the maintainer of GeckoLinux, which is based on openSUSE Leap 42.3. It appears that something has changed in openSUSE that is now preventing Calamares from finding the grubx64.efi file. Here a reviewer details what happens, which I can also confirm:
https://nwrickert2.wordpress.com/2018/01/07/geckolinux-423-180105-a-review/

    Boost.Python error in job "bootloader".
    <class 'FileNotFoundError'>
    [Errno 2] No such file or directory: '/tmp/calamares-root-a2mwc42r/boot/efi/EFI/grubx64.efi'
    Traceback:
      File "/usr/lib64/calamares/modules/bootloader/main.py", line 348, in run
        prepare_bootloader(fw_type)

      File "/usr/lib64/calamares/modules/bootloader/main.py", line 319, in prepare_bootloader
        install_grub(efi_directory, fw_type)

It turns out that the file is present at `/boot/efi/EFI/grub/grubx64.efi`

Thanks for the help.

**Comment by philmmanjaro** [comment]
So what do you expect now? The **efi_directory** get defined as `efi_directory = libcalamares.globalstorage.value("efiSystemPartition")`. Then we define the following also:

        install_path = libcalamares.globalstorage.value("rootMountPoint")
        install_efi_directory = install_path + efi_directory

Based on that we copy the efi files:

        # Workaround for some UEFI firmwares
        efi_file_source = {"32": os.path.join(install_efi_directory_firmware,
                                              efi_bootloader_id,
                                              "grubia32.efi"),
                           "64": os.path.join(install_efi_directory_firmware,
                                              efi_bootloader_id,
                                              "grubx64.efi")}

        efi_file_target = {"32": os.path.join(install_efi_boot_directory,
                                              "bootia32.efi"),
                           "64": os.path.join(install_efi_boot_directory,
                                              "bootx64.efi")}

        shutil.copy2(efi_file_source[efi_bitness], efi_file_target[efi_bitness])

So the question is here, what the bootloader ID for you is. You can configure it in the [conf](https://github.com/calamares/calamares/blob/3.1.x-stable/src/modules/bootloader/bootloader.conf).

**Comment by geckolinux** [comment]
Thank you. I would appreciate a clearer explanation in the comments of `bootloader.conf` for that part.

**Comment by philmmanjaro** [comment]
@geckolinux: what is unclear with this?

```
# Optionally set the --bootloader-id to use for EFI. If not set, this defaults
# to the bootloaderEntryName from branding.desc with problematic characters
# replaced. If an efiBootloaderId is specified here, it is taken to already be a
# valid directory name, so no such postprocessing is done in this case.
# efiBootloaderId: "dirname"
```
If enabled the following code is not used:

        if "efiBootloaderId" in libcalamares.job.configuration:
            efi_bootloader_id = libcalamares.job.configuration[
                                    "efiBootloaderId"]
        else:
            branding = libcalamares.globalstorage.value("branding")
            distribution = branding["bootloaderEntryName"]
            file_name_sanitizer = str.maketrans(" /", "_-")
            efi_bootloader_id = distribution.translate(file_name_sanitizer)

**Comment by geckolinux** [comment]
> what is unclear with this?

I find the term "ID" to be confusing. I understand that it comes from the `grub-install ... --bootloader-id=` command switch, but I would appreciate something in the comments explaining that "dirname" is inside the `/boot/efi/EFI/` path.

**Comment by philmmanjaro** [comment]
What is the `bootloaderEntryName` from `branding.desc`? Did something changed there?

**Comment by geckolinux** [comment]
`branding.desc` was changed 4 months ago, I don't think I've tested (U)EFI with Calamares since then, so that might be the problem. `bootloaderEntryName` is commented out. The `productName` is `GeckoLinux` .

**Comment by philmmanjaro** [comment]
I hope you found a working solution for your problem ...

**Comment by geckolinux** [comment]
@philmmanjaro  Thanks, setting `efiBootloaderId: "grub"` seems to have worked.

**Comment by kkofler** [comment]
The reason GRUB and Calamares call this directory name a "bootloader id" is because the UEFI firmwares will normally display this as a name in the menu.
