### ISSUE TITLE
Wrong/strange UID logic for user account creation

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#894]
Hi, I distribute a spin of openSUSE Tumbleweed, currently using Calamares 3.1.12 and kpmcore 3.3.0.

For some reason, Calamares is creating the user account with a UID of 2000. It should start at 1000, which is what happens when I use the old `yast2-live-installer`. My live CD user UID is 1999, so maybe Calamares is using the liveUID +1 ? 

Thanks a lot for the help.

**Comment by abucodonosor** [comment]
calamares fires useradd nothing else .. if that doesn't work for you fix your distro tools ?

https://github.com/calamares/calamares/blob/master/src/modules/users/CreateUserJob.cpp#L150

**Comment by adriaandegroot** [comment]
From the manpage for adduser:

```
      -u, --uid UID
           The numerical value of the user's ID. This value must be unique,
           unless the -o option is used. The value must be non-negative. The
           default is to use the smallest ID value greater than or equal to
           UID_MIN and greater than every other user.
```

(note that Calamares doesn't pass in the `-u` flag, so the default behavior is used). If your live user also exists in the target system, (e.g. is listed in `/etc/passwd` in the installed image, even though no live user is intended to run there) then the default logic of useradd is going to find liveUID+1, yes.
