### ISSUE TITLE
pwquality password quality checking

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#896]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

It would be cool if calamares did password quality checks using https://github.com/libpwquality/libpwquality so it enforces the same password strength expectations as elsewhere in the system (e.g. it's also used in plasma's user management kcm)

**Comment by demmm** [comment]
Do you mean this feature? 
https://github.com/calamares/calamares/blob/master/src/modules/users/users.conf#L52
Was implemented in https://github.com/calamares/calamares/commit/d839f8e0b311a3312eadbbc78d7e4e9ccdbcf708

**Comment by adriaandegroot** [comment]
@demmm, that's part of it, but @apachelogger is asking for more password-quality checks. When I added those checks in the users module, I did suggest additional checks might be added to the users page. This would be a useful #ifdeffed additional check.
