### ISSUE TITLE
bootx64.efi make optional

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#898]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

https://github.com/calamares/calamares/blob/54a9bbb9499f64a93747c773b5ebfd82b05ccfa4/src/modules/bootloader/main.py#L271

There is a bit of code which installs the grub efi loader to `boot/bootx64.efi` the code comment suggests this is for obscure firmwares but doesn't give any detail as to when or why or how. Some research suggests the claim comes from the arch wiki which suggests DH87MC is the only board affected by this. Additional research suggested that no one actually ever determined if this was DH87MC's fault or the user/distro's fault for incorrectly setting up the nvram vars.

`boot/bootx64.efi` is the standard fallback path outlined by the EFI spec. It acts as global fallback if no other loaders are found, this path is searched. It being present can hide any matter of badly configured nvram and putting the loader there in no way indicates that the firmware is broken, it merely indicates that the firmware actually implements the fallback as required by the spec.

In any event, this should be an opt-in feature for distros to enable or not. In fact, ideally, the feature should only ever be enabled if DH87MC was detected.
So perhaps a `installBootx64OnBadUEFIFirmware: false` flag in the bootloader.cfg and backing code which checks for DH87MC and installs bootx64.efi iff the distro opted into this workaround.

**Comment by adriaandegroot** [comment]
I've called it `installEFIFallback` (defaults to True), and at least VirtualBox is fine with an installation where that is set to False (and hence, no `boot/bootx64.efi` is installed). That one Intel board isn't *so* old that it isn't possibly relevant anymore -- I'm going to leave it up to downstreams to figure out if there is a way to auto-detect that board (if the distro wants to change the value for `installEFIFallback` to False)
