### ISSUE TITLE
unpackfs fails, rsync error 10

### ISSUE THREAD

**Issue by agaida** [calamares/calamares#907]
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> latest git, latest kpmcore git

#### What do you expect to have happen when Calamares installs?

> not to have this bug

#### Describe the issue you encountered
```
10:41:07 [6]: Job file "/usr/lib/calamares/modules/unpackfs/main.py" 
10:41:07 [6]: Job description from __doc__ "unpackfs" = "Unsquash filesystem." 
Assertion 'fd' failed at ../src/basic/socket-util.c:1011, function getpeergroups(). Aborting.
rsync: [receiver] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(829) [receiver=3.1.2]

rsync: [sender] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(829) [sender=3.1.2]
10:42:03 [0]: Installation failed: 
10:42:03 [0]: - message: "Failed to unpack image /tmp/calamares" 
10:42:03 [0]: - details: "rsync failed with error code 10." 
10:42:03 [0]: Calamares will quit when the dialog closes. 
10:42:03 [6]: FinishedPage::setUpRestart() 
```

#### Steps to reproduce the problem

> use an unfixed systemd 237 - the bug in unpackfs seems to be related to https://github.com/systemd/systemd/pull/8080 - will build an iso with the fixed systemd and report.

**Comment by agaida** [comment]
Apply the mentioned patch and be done with. Works fine again,

**Comment by kkofler** [comment]
Since this is a systemd bug, can we close this here?

**Comment by agaida** [comment]
Sure it could be closed - but that was not the reason for filing a non-bug here - i have an idea that some people with an unfixed systemd 237 could use calamares too - and in that case it would be nice to have this open - just to prevent the filing of a bunch of bugs against calamares.

**Comment by adriaandegroot** [comment]
I have added this to the deployer's guide, on the [known-issues page](https://github.com/calamares/calamares/wiki/Deployers-Issues), so I'm closing the issue as "downstream, but documented now".
