### ISSUE TITLE
Improvement to Deployer's guide in calamares.wiki

### ISSUE THREAD

**Issue by cmacq2** [calamares/calamares#908]
#### Submission type

  - [x] Bug report

#### Info regarding which version of Calamares is used, which Distribution

This is about the wiki. (calamares.wiki.git).

#### Describe the issue you encountered

The Deployer's guide mentions a rather invasive way to *mask* a systemd generator. It should be sufficient to put the symlink in `/etc/systemd/system-generators` instead. This avoids the rather invasive hack (messing with package managers/vendor trees) in favour of fixing it at the system configuration level (/etc). Note that this location is also mentioned in the final comment on the linked bug report thread by the same guy who implemented support for masking systemd generators.

See also: the `fixup-systemd-generator-masking` branch of cmacq2/calamares.wiki.git (I'd submit a PR but it turns out Github doesn't let you do the PR thing with wikis, which is a shame).

**Comment by kkofler** [comment]
Well, arguably, shipping distro-provided files in `/etc/systemd` is also a hack, that tree is intended only for the system administrator. (Try doing that in a Fedora package and face Lennart's wrath. ;-) ) But if it's on the live image only, it should be acceptable.

**Comment by adriaandegroot** [comment]
The original text is from 2014. Who knows what it does right now -- but there are still issues with auto-mounting. See #860. It may not be systemd any more that is auto-mounting everything.

Anyway, I've massaged the text a little. @cmacq2 , it's a wiki, feel free to submit fixes.

**Comment by cmacq2** [comment]
@adriaandegroot 
Sorry to reopen this but unfortunately:

>  it's a wiki, feel free to submit fixes.

That doesn't work, because Github wikis are weird like that. You can't do the normal fork + PR, and you can't edit it from the web UI either (or at least not as the calamares wiki is currently configured)... Hence all this fuss in an issue. ;)
