### ISSUE TITLE
Command 'systemd-machine-id-setup' returned non-zero exit status 127.

### ISSUE THREAD

**Issue by wellington1993** [calamares/calamares#909]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

```
Manjaro Linux                                                                                                                        
DISTRIB_ID=Netrunner
DISTRIB_RELEASE=2018.01
DISTRIB_CODENAME=Rolling
DISTRIB_DESCRIPTION="Netrunner Rolling"
```

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 
When try to install:

```

Boost.Python erro na tarefa "machineid".
<class 'subprocess.CalledProcessError'>
Command 'systemd-machine-id-setup' returned non-zero exit status 127.
Traceback:
  File "/usr/lib/calamares/modules/machineid/main.py", line 57, in run
    check_target_env_call("systemd-machine-id-setup")

  File "<string>", line 2, in <module>

```
#### What do you expect to have happen when Calamares installs?

No problems :-/

#### Describe the issue you encountered

Error after partition tool, at step: extract squash

#### Steps to reproduce the problem

Try to install (Maybe problem with partitioning)

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

no log...

**Comment by adriaandegroot** [comment]
Is it Manjaro you're installing, or Netrunner Rolling? Probably a recent Netrunner rolling version. It would be nice to have a download link, so I can more easily try to reproduce the problem. Is the problem reproducible? Exit code 127 is, I think, command-not-found which would mean that the target system filesystem is missing that command.

**Comment by philmmanjaro** [comment]
@adriaandegroot: Netrunner Rolling can be downloaded from [here](https://www.netrunner.com/download/).
@wellington1993: Does this also happen with Manjaro v17.1 series? You can get it from [here](https://manjaro.org/get-manjaro/).

**Comment by abucodonosor** [comment]
@adriaandegroot 

yes 127 is command not found .. so something wrong with that Distro's LiveCD

**Comment by adriaandegroot** [comment]
Just installed netrunner-rolling 18.01-rc6 twice, no problem. Once in English, once in Brasilian Portuguese. Found some translation problems with Netrunner, but not with Calamares. So closing this as "once-off" or "not-reproducible". It's more of a downstream issue, anyway.
