### ISSUE TITLE
next/own Cloud integration

### ISSUE THREAD

**Issue by DarkknightAK** [calamares/calamares#914]
#### Submission type
  - [x] Feature Request

The idea is to ask at the installation if you'd like to use your home partition from a cloud storage. e.g. you can install a new system with all settings.

**Comment by adriaandegroot** [comment]
This falls pretty firmly under the "improve user configuration possibilities" tickets, which are also booked under "OEM installer mode". But I'm not quite sure what you mean: load home directory settings from an Cloud server, or mount /home from a server, or configure access to that server for the system user?

**Comment by DarkknightAK** [comment]
I'm thinking on something like

calamares ask after username / pw and online resource.

the online resource will than be used as ~/home folder I think this would be the best practice.

on a new installation you will again connect to the cloud storage and have all settings cause you have your /home into the cloud.

**Comment by adriaandegroot** [comment]
.. ok, so how do you do that? The UI can be dealt with later, the first thing to know is, what commands need to be executed (in whatever distro) to make this happen? Ideally, there would be a script or executable *make-nextcloud-homedir* which takes parameters *username*, *online resource* and *password* as parameters, and sets it up. Calamares can easily run such a script during setup.

**Comment by blackcrack** [comment]
hummm... webdavfs mounting /home/userdir ?
ehh is Calamares not a Linux/Distributions Installer .. ?

It should also stop somewhere... but hey, if you want install 
in an installer an webdavfs for checking if it's works.. oh well.. all iss possible, toyota ..
\*lol*   holymouly, did you see how have a horse puke !  ohh man.. 
best regards
Blacky

**Comment by adriaandegroot** [comment]
Closing this one as "unclear what is being asked".
