### ISSUE TITLE
Manjaro 17.1.6 fails to install in UEFI

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#918]
Some of the Manjaro flavors -- LXDE for instance -- fail to install. A Python error is shown by Calamares during the bootloader module. The Manjaro 17.1.6 KDE flavor does install normally on UEFI systems.

From examining the log of a failed install in LXDE, 

```
2018-03-16 - 12:01:20 [0]: Target cmd ("grub-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=Manjaro", "--force") 
2018-03-16 - 12:01:20 [0]: Target out "Installing for x86_64-efi platform.\ngrub-install: error: efibootmgr failed to register the boot entry: Unknown error 32766." 
```

Doint a chroot to the target system at this point and running the same `grub-install` command with the `-v` option shows what it is doing. The grub installation process ends with:

```
grub-install: info: executing efibootmgr --version </dev/null >/dev/null.
grub-install: info: executing modprobe -q efivars.
grub-install: error: efibootmgr failed to register the boot entry: Unknown error 32765.
```

(The error number varies). There is no kernel module *efivars* (but the KDE flavor doesn't have one either, so I'm not sure why the same command does work there).

The current upstream recommendation is: get Manjaro to fix their ISOs, or install Manjaro KDE and switch desktops after that.

**Comment by philmmanjaro** [comment]
OK, seems to be an issue with **v17.1.7** series after all. We updated **grub** and now **EFI** installation seems not to work:

```
14:32:30 [0]: Starting job "bootloader" 
14:32:30 [1]: Job file "/usr/lib/calamares/modules/bootloader/main.py" 
14:32:30 [1]: Job "bootloader" (doc) -> "Starts procedure and passes 'fw_type' to other routine." 
Bootloader: grub (efi)
14:32:30 [0]: Running "chroot" ("/tmp/calamares-root-b9xp_y3n", "grub-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=Manjaro", "--force") 
14:32:36 [0]: Finished. Exit code: 1 
14:32:36 [0]: Target cmd ("grub-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=Manjaro", "--force") 
14:32:36 [0]: Target out "Installing for x86_64-efi platform.\ngrub-install: error: efibootmgr failed to register the boot entry: Unknown error 32767." 
14:32:37 [1]: tbMsg "  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 351, in run\n    prepare_bootloader(fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 322, in prepare_bootloader\n    install_grub(efi_directory, fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 253, in install_grub\n    &quot;--force&quot;])\n\n  File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;\n" 
14:32:37 [0]: Installation failed: 
14:32:37 [0]: - message: "Boost.Python error in job \"bootloader\"." 
14:32:37 [0]: - details: "<div><strong>&lt;class 'subprocess.CalledProcessError'&gt;</strong></div><div>Command 'grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Manjaro --force' returned non-zero exit status 1.</div><div>Traceback:</div><div><pre>  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 351, in run\n    prepare_bootloader(fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 322, in prepare_bootloader\n    install_grub(efi_directory, fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 253, in install_grub\n    &quot;--force&quot;])\n\n  File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;\n</pre></div>" 
14:32:37 [0]: Calamares will quit when the dialog closes.
```

**Comment by philmmanjaro** [comment]
Most likely created with this commit: http://git.savannah.gnu.org/cgit/grub.git/commit/util/grub-install.c?id=6400613ad0b463abc93362086a491cd2a5e99b0d

**Comment by philmmanjaro** [comment]
**XFCE v17.1.7-rc5** resolved the issue by reverting commit 6400613. It boots normal to EFI. Now we have to see if **efibootmgr v15** needs to be patched or what is going on with this **Debian** freature.

**Comment by fhdk** [comment]
If I rebuild the ISO will it have the right efibootmgr?

**Comment by philmmanjaro** [comment]
@fhdk: with **grub v2.03.0-2** it works again. This however doesn't "fix" the issue, as I only reverted the new feature checking how **efibootmgr** was able to install.

**Comment by abucodonosor** [comment]
@philmmanjaro 

That's the *wrong* fix .. the right one is to fix all your kernels and enable
CONFIG_EFI_VARS=m since efibootmgr *need* that to work right.

Reverting 6400613 ofc make things working again by ignoring the return values
again however other things breaks.

**Comment by tdd11235813** [comment]
meanwhile, I have tried to workaround with 17.1.4 and then 17.1.0, last one went almost through, but then os-prober took about 15min (due to another arch OS, can be fixed by mounting the arch OS partition, have to do this after the installation as well). After upgrade latest manjaro is running fine.

**Comment by abucodonosor** [comment]
@tdd11235813 

looks like grub-mount problem ( which need fuse ) .. however os-prober does not need grub-mount to work.

**Comment by tdd11235813** [comment]
this os-prober thing run after grub-mount, I guess. While watching `htop` the os-prober thing popped up (on the 17.0 install routine). On the other other versions `grub-mount` get stuck with 100% CPU core usage at the `fw_type` message.
For the arch OS and os-prober bug I found the workaround [here](https://forum.manjaro.org/t/grub-update-hangs-takes-10-min-to-generate/22611/17).

**Comment by abucodonosor** [comment]
@tdd11235813 

Well you cannot guess what other OS'es have or not have installed.
So do an quick test .. move grub-mount to grub-mount-do-not-run-me and see
how things are working fine without

**Comment by tdd11235813** [comment]
sure, let's check it out:
<details>
 
```bash
# fix enabled (sda partitions are mounted)
$ time os-prober
/dev/sda1@/efi/elilo.efi/elilo.efi:ELILO Boot Manager:ELILO:efi
/dev/sda1@/efi/Microsoft/Boot/bootmgfw.efi:Windows Boot Manager:Windows:efi
/dev/sda2:Slackware 14.1:Slackware:linux
/dev/sda4:Arch Linux:Arch:linux

real	0m4,065s
user	0m1,943s
sys	0m0,635s

# fix disabled (no sda partitions mounted)
$ time os-prober
/dev/sda1@/efi/elilo.efi/elilo.efi:ELILO Boot Manager:ELILO:efi
/dev/sda1@/efi/Microsoft/Boot/bootmgfw.efi:Windows Boot Manager:Windows:efi
/dev/sda2:Slackware 14.1:Slackware:linux
/dev/sda4:Arch Linux:Arch:linux  #<-- hanging around

real	13m17,783s
user	0m3,135s
sys	0m1,286s

# moved grub-mount
$ time os-prober
# did not find any OS here
real	0m1,202s
user	0m0,775s
sys	0m0,216s
```

`grub-mount /dev/sda4 /var/lib/os-prober/mount` was the command that popped up at the end of the installation.
</details>

**Comment by abucodonosor** [comment]
@tdd11235813 

then grub2 itself need fixing too in Arch and Arch based Distros it seems..

Have a look:

```

crazy@devnull:~$ sudo which grub-mount
which: no grub-mount in (/usr/lib/jvm/java-8-openjdk/jre/bin:/usr/lib/jvm/java-8-openjdk/bin:/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin)
crazy@devnull:~$ time sudo  os-prober
/dev/sda4:KaOS (rolling):KaOS:linux

real    0m1,230s
user    0m0,296s
sys     0m0,182s
crazy@devnull:~$ sudo pacman -Sy grub2-mount
:: Synchronisiere Paketdatenbank ...
(1/1) frugalware-current [################] 100%     472K   15054K/s  00:00:00
Löse Abhängigkeiten auf ... erledigt.
Suche nach Zwischen-Konflikten (1/1)              [#######################] 100%

Pakete:  grub2-mount-2.02-16

Paket-Gesamtgröße:      0,2 MB

Entpackte Paket-Gesamtgröße:       0,8 MB

Aktualisierung fortsetzen? [J/n] 


:: Empfange Pakete von frugalware-current ...
(1/1) grub2-mount-2.02-1 [################] 100%     208K    1923K/s  00:00:00
Prüfe Paketintegrität ... erledigt.
(1/1) installiere grub2-mount                     [#######################] 100%
crazy@devnull:~$ time sudo  os-prober
/dev/sda4:KaOS (rolling):KaOS:linux

real    0m2,810s
user    0m0,395s
sys     0m0,340s
crazy@devnull:~$ sudo pacman -R grub2-mount
Prüfe Abhängigkeiten ... erledigt.
(1/1) entferne grub2-mount                        [#######################] 100%

crazy@devnull:~$ time sudo  os-prober
/dev/sda4:KaOS (rolling):KaOS:linux

real    0m1,838s
user    0m0,517s
sys     0m0,292s

```

**Comment by abucodonosor** [comment]
@tdd11235813 

does your kernel have CONFIG_EFI_VARS=m ?

**Comment by abucodonosor** [comment]
ehh.. os-prober in ArchLinux is build without any fixes ... 

@tdd11235813 

if you wish look https://github.com/frugalware/frugalware-current/blob/master/source/base/os-prober/FrugalBuild#L24

You maybe want more patches from there ..

**Comment by tdd11235813** [comment]
@abucodonosor thanks for the hints, I have just used the plain installer. `CONFIG_EFI_VARS` is not set. 
```bash
zgrep "CONFIG_EFI_VARS" /proc/config.gz
# CONFIG_EFI_VARS is not set
zgrep "CONFIG_IKCONFIG" /proc/config.gz #just check, if it is set to yes
CONFIG_IKCONFIG=y
CONFIG_IKCONFIG_PROC=y
```
As the mount-workaround is sufficient for me, I would not patch os-prober for now.

**Comment by abucodonosor** [comment]
@tdd11235813 

Well os-prober is an Debian app and even is meant to work generic it just doesn't on
!Debian for reasons.. dash vs bash , *stable* debian vs *rolling*  distros and much more.

So to make it work you really need to patch it.

While you can workaround that should work out of the box.

**Comment by philmmanjaro** [comment]
@abucodonosor: thx again for all your hints. I'll fix it in Manjaro accordingly.

**Comment by philmmanjaro** [comment]
@abucodonosor: in regard of `CONFIG_EFI_VARS`. Are you sure that it is needed? This was discussed [here](https://bugs.archlinux.org/task/51695) and therefore it got disabled back in [2013](https://git.archlinux.org/svntogit/packages.git/commit/?h=packages/linux&id=ebf4d782ffe29e3b00e93011a493cbedffbd7415). Even Fedora [adopted this](https://bugzilla.redhat.com/show_bug.cgi?id=1252137).

> According to the archlinux wiki
> 
> "Enabling both OLD sysfs-efivars and NEW efivarfs can cause data inconsistency issues (see See https://lkml.org/lkml/2013/4/16/473 for more info). Due to this OLD sysfs-efivars is completely disabled in Arch's official kernels (since core/linux-3.11 and core/linux-lts-3.10) and only NEW efivarfs is enabled/supported going forward. All the UEFI Variables related tools and utilities in official repositories support efivarfs as of 01 October 2013."
> 
> https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface#Userspace_Tools

So, do you have [commit 6400613](http://git.savannah.gnu.org/cgit/grub.git/commit/util/grub-install.c?id=6400613ad0b463abc93362086a491cd2a5e99b0d) applied to your OS to see if you have the same error?

**Comment by abucodonosor** [comment]
@philmmanjaro 

grub2 need it still yes.. but if you want to play around here an patch to disable
looking for efivars in grub2:

http://ant.spdns.eu/stop-looking-for-efivars-modules.patch

So you can have that commit in but disable modprobing efivars.
Maybe worth a try? Also when that really works for you we could
bug grub peoples to make that configurable.

I have an grub2 git build but I have different kernel so that won't return any error here.
I can build an kernel with your config and play around next week.

**Comment by philmmanjaro** [comment]
@abucodonosor thx again for pointing me into the right direction. On Manjaro we use **efivarfs** module instead.

**Comment by abucodonosor** [comment]
@philmmanjaro 

Yes that worth a try too also .
Also that still can be made configurable if is working for you.
Some sort --with-efi-modules= or similar

**Comment by philmmanjaro** [comment]
Well, it is more that we use a different module than different folders ...

**Comment by abucodonosor** [comment]
@philmmanjaro 

yes sure so it can be : --with-efi-modules=efivars/efivarfs and everyone should be happy

**Comment by philmmanjaro** [comment]
@abucodonosor: this flag `--with-efi-modules` is not given in current **configure** file of **grub2**. I think my patch should fix it for Manjaro, though.

**Comment by abucodonosor** [comment]
@philmmanjaro 

Well like I've said , test first with your patch and if is working for you we need
open an bug report for grub2 to add such an switch.

**Comment by philmmanjaro** [comment]
Ah, now I got what you ment ...

**Comment by adriaandegroot** [comment]
Closing this as "solved downstream, not Calamares-related"
