### ISSUE TITLE
packages.conf states wrong format for LOCALE

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#922]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

the packages.conf documentation says the following

```
# - otherwise $LOCALE or ${LOCALE} is replaced by the Bcp47 name of the selected
#   system locale, e.g. nl_BE. Note that just plain LOCALE will not be replaced,
#   so foo-LOCALE will be unchanged, while foo-$LOCALE will be changed.
```

which is incorrect. The BCP 47 notation would be 'nl-BE'. What is shown in the example is a POSIX locale. Depending on which is actually used the documentation should be cleaned up.
On an added note: BCP 47 is case insensitive, while package managers may be case sensitive. So, if BCP is used it probably should be documented if it downcased or something.

https://tools.ietf.org/rfc/bcp/bcp47.txt
http://pubs.opengroup.org/onlinepubs/007908799/xbd/envvar.html

**Comment by adriaandegroot** [comment]
The format is, unfortunately, kinda useless. But documented now.
