### ISSUE TITLE
package module: map locale to a different format altogether

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#923]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

Different projects use different notations for their language packages. Some use a mangled locale, some use bcp47, some use a made up variant somewhere in between locale and bcp, some are upcased, some are downcased, some are mixed cased. etc. etc.

To properly install localization we therefore often need a way to translate the input LOCALE to a different format. I propose the following new property:

```
- install
  - package: language-pack-${LOCALE}
    locale-transform: /usr/share/calamares/locale-to-ubuntulang.sh
  - package: kde-l10n-${LOCALE}
    locale-transform: /usr/share/calamares/locale-to-kdelang.sh
```

Before constructing the package name the package module would run the LOCALE through the locale-transform helper. The helper outputs a single line which is the transformed named of the locale.

For example for ca@valencia:

- ca@valencia :arrow_right: transform :arrow_right:  ca :arrow_right:  install language-pack-ca
- ca@valencia :arrow_right: transform :arrow_right:  ca-valencia :arrow_right: install kde-l10n-ca-valencia

**Comment by adriaandegroot** [comment]
Closing this one in favor of #924, which is more general.
