### ISSUE TITLE
Unofficial Calamares repositories?

### ISSUE THREAD

**Issue by essine** [calamares/calamares#927]
#### Submission type

  - [ ] Bug report
  - [ ] Feature Request
  - [x] Suggestion

Does it make sense to organize something like  unofficial user repositories, where developers could upload and describe their Calamares modules?

Unofficial repositories could have a warning that: The official Calamares Developers and the Trusted Users do not perform tests of any sort to verify the contents of these repositories ( taken from
https://wiki.archlinux.org/index.php/Unofficial_user_repositories).

Here is, for example, a simple module 'shtask' that allows to perform a shell command or script selected by user ( https://github.com/essine/shtask/blob/master/README.md ). In contrast to existing 'shellprocess' module, 'shtask' interface can be customized in module configuration file.

The more useful modules could appear later.

**Comment by adriaandegroot** [comment]
There's a couple of different angles we could take on this:
 - listing "here are more modules you might like" somewhere; probably in the deployer's guide on the Calamares wiki, or in the main website
 - actively collecting modules into https://github.com/calamares/calamares-branding (that needs to be renamed, really .. and the README adjusted, but there are both branding examples and other modules there, as well as being normative on how one should write and organize modules),
 - actively upstreaming modules into Calamares main.

**Comment by adriaandegroot** [comment]
(as for *shtask* itself, I'm kinda struggling to see a use-case for it in an installer; why would the user want to, or need to, pick commands to execute during installation? There are all kinds of other things to comment on the code, but this issue isn't about a code review for shtask).

All in all I think I'd prefer to put this (kind of) module into the calamares-branding (whatever it is renamed to) module, and to encourage people to actively fork-and-resbmit-upstream.

**Comment by essine** [comment]
Thank you for your comments. As mentioned above, 'shtask' is just an example. There are some Calamares modules potentially required for installation of an Arch-based Linux 'TankOS' distribution (https://tankos.tk/).
One of the module, for example, will be responsible for the desktop environment selection (GNOME, KDE, xfce et cetera). It is not realised in Calamares, if I didn't miss something. 
After creation of a new module, I will make a reference to it in the deployer's guide on the Calamares wiki, as you suggested.
