### ISSUE TITLE
welcome module l10n UX

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#934]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

Currently, the welcome page always defaults to the system language, which, unless the distro has made additional arrangements will be english. On the welcome page the user then has to select the installer language.
When geoip is enabled, cala does get superior locale information from there though. A fact which is reflected in the location page then getting defaulted to the geoip derived information.

I'd like to propose an opt-in feature whereby cala's locale itself is also derived from geoip and used as a default.

e.g.
I am in Seoul. I start cala. Cala geoips that I am in Seoul. Cala defaults to Korean.
I am in Austria. I start cala. Cala geoips that I am in Austria. Cala defaults to German.

It's most likely that I will speak German and want to install in German when I am in a German speaking country. Given the default behavior should be the most-likely desired behavior I would think geoip should impact the default locale in cala.

Additional considerations:

- should be on a fairly short timeout, and possibly the initial show should be delayed until the timeout passes or the geoip data is available (does cala have a busy indicator? could be that the cala window shows a busy indicator and transitions to the welcome page once geoip returned/timedout)
- we'd probably not want to switch the language on the already visible welcome page unless avoidable (hence the above point)
-  this could possibly have an additional configuration parameter `only-geoip-if-locale-c`. namely, assuming that the distro defaults to `C` and only switches the locale iff the user explicitly selected one. such that calas behavior becomes `if LANG==C.UTF-8 ? geoip : nogeoip`. this would prevent us from overriding a user decision, and also enable distros to implement other means for language selection (ISO boot screen, login manager, what have you) so long as they have C by default.
- this has particular value for OEM installations, where the OEM system may have any locale set and quite possibly offer no way to change that locale (e.g. by only running cala as single window).

**Comment by jriddell** [comment]
'unless the distro has made additional arrangements will be english' in ubuntu distros the user can also select this at the plymouth boot splash

**Comment by adriaandegroot** [comment]
This has been requested before; if you want to go down that road, really there should be a GeoIP query earlier (e.g. in startx) so that the live environment is correct.

**Comment by apachelogger** [comment]
@jriddell that's a) not plymouth b) not applicable to anything uefi c) ubuntu live session default to C; see my additional consideration regarding that

@adriaandegroot this is not necessarily applicable to the environment. e.g. on ubuntu a locale is only configured when its related core language package is installed, meaning `de_AT` for example is simply not an enabled locale at that point and setting it may have adverse side effects.
Additionally, changing the session language is usually not as easy as scrolling through a readily visible dropdown. So, if the geoip query gave incorrect results the distro would then switch the entire session to a language the user possible doesn't understand a word of and the means to change it to a language of their choosing will be hidden in some app in some menu. e.g. say one is on vacation in Seoul and wants to install neon, they'd get a Korean session by default, good luck finding the correct setting ^^
All that said, same rules applying for C=default it certainly is a viable wholesale approach to this. Any opinions on providing a tiny binary helper which distros can use to implement that? (geoips queries; returns locale for geoip query).

**Comment by demmm** [comment]
Probably not very relevant for this request, but (very small distro) KaOS has this option at boot up for all sessions enabled, user can select preferred locale/language for both UEFI & BIOS systems, so not a feature needed here.

**Comment by abucodonosor** [comment]
@apachelogger 

I don't agree on this one .. it should speak to you based on whatever your locale
settings are and not 'where you are' .. If you can't do that with your Live images ,
well then you should fix these. 

 Also please note something like C.UTF-8 does not exist upstream and is an Ubuntu/Fedora *patch* ...

**Comment by adriaandegroot** [comment]
A distro **can** enable this in the Welcome module in 3.2.8 (to be released soon) and then it auto-switches to whatever GeoIP thinks is likely (based on the 2-letter country code).
