### ISSUE TITLE
change desktop entry Name to something generic

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#936]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

The default desktop file for calamares has `Name=Calamares`, I'd like to propose changing it to `Name=Install System` or `Name=Install Now` or something along this line.

The current name doesn't really help anyone.

We install the desktop file by default, but distros shouldn't really ship it verbatim since the user wouldn't know what to do with an entry titled 'Calamares'. Ideally, the final user would not need to know anything ever about Calamares. So it offers poor UX for the end user.

The distro itself also has no use for it being called Calamares since the distro developer would know that this is Calamares and usually one distro would only have one installer installed at any one time, so differentiating between Calamares or Floobywhoops in the app menu or where ever is also not really a thing.

In the grand scheme of things I believe it more beneficial for everyone if the Name was something that would, in general, make sense to indicate that this is the thing you want to open to install the system. 
It would mean distributions can ship the verbatim desktop file (which some are doing already anyway, irregardless of the poor UX it offers) to save on translation work and the user would get a decent menu entry even if the distro doesn't supply their own desktop file.

**Comment by agaida** [comment]
@kkofler- the desktop entry spec isn't and wasn't written in stone. And the request is resonable, to be true i patch the desktop entry to Name=Installer :D - And no, i don't care about Translations right now.

**Comment by adriaandegroot** [comment]
I'm open to suggestions here. To make downstream modification of the desktop file superfluous, we need a Name that is applicable in two scenarios:
 - Regular Live-install mode
 - OEM mode
I suppose we could pick one of the two and optimize Name for that, leaving the other scenario to (still) patch.

Note that the desktop file as shipped is full of redundancies which the 1.1 spec says it shouldn't have, anyway. So one more violation for being overly generic in the Name doesn't bother me.

**Comment by apachelogger** [comment]
To support the two scenarios it'd be better to install two desktop files IMO, assuming we want different `Name`s  for the two modes. calamares.desktop and calamares-oem.desktop. Then have the distros either package them separately or pick one at runtime by deleting the other.

I'd go with simply `Name=Install System` for both cases.

Arguments could be made that `Name=Configure System` is better for OEM, but I think to an end user there isn't really a difference between the two.

As an additional thought that just occured to me: a really fancy (opt-in?) version of this would be cala not installing a desktop file at all, but instead install it into /usr/share/calamares or wherever with `Name=Install @PRODUCT@` (gets translated as verbatim `@PRODUCT@`) and then have a helper binary which gets run via a /etc/profile.d/ hook on session startups. The helper would then copy the template file and `s/@PRODUCT@/productNameFromBrandingFile/g` making the Name reflect the product name rather than the generically 'System'. e.g. on manjaro the actual desktop file would then be `Name=Install Manjaro`.

(Also, FTR, for OEM the much more reasonable UX would be for the distro to autostart cala, instead of having the user do it, rendering the desktop entry largely moot)
