### ISSUE TITLE
grubcfg.conf should document how cmdline values are auto detected

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#939]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

e.g. `splash` is only added to cmdline iff global config `hasPlymouth` and it is only set by plymouthcfg, so in order to have `splash` set you have to run plymouthcfg even when not wanting to set a theme or else splash will be missing from the cmdline

**Comment by adriaandegroot** [comment]
This was addressed in 0ccca6902bb8a58203e2fd8b7b26225d8d1f8185 (which makes the grubcfg module check separately whether it has plymouth and can add splash to the grub command line).
