### ISSUE TITLE
ability to "preseed" & lock values

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#942]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

I am currently working on a functional OEM mode for neon (special operation mode for OEMs to install a system, prepare it, then ship to customer for final user/tz/keyboard config).

This mode has 2 variants of how calamares is run.
One is done by the OEM to install the system. One is done by the user to configure it once they received their device from the OEM.

To reliably and easily handle the former, a distribution may wish to pre-fill and possibly lock down certain fields in the UI.

Specific example: during OEM installation the user page should use the username 'oem' as initial username and disable the field such that this username cannot be changed during OEM installation. The end result ought to be that there is a user named 'oem' on the final system.

This could be done by implementing a generic system to preseed (IOW provide the default value of any field anywhere). Such a system would also be necessary if cala ever were to get a headless/enterprise use case where one would do mass deployments across multiple devices using such a pre-configuration. I am not sure how feasible that is to implement though, or practical even.

Short of that I'd be happy with the ability to force a specific username in the user module.

**Comment by adriaandegroot** [comment]
This release solves **only** the specific issue raised by @apachelogger , the user name and full name. Those can be set (and prevent the UI from changing) from the config file. Only fixed values are accepted right now.
