### ISSUE TITLE
oem installation identifier

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#943]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

OEMs may wish to mark installations with a custom stringy tag. This enables support staff to determine what type of installation a given device is based on.

To enable this use case we'd need a text input field which is then dumped in a static file location somewhere on the final system. This could be a text field on the welcome page (opt-in via config) or a completely separate module/page. The file should be created even when the input was empty. It'd then simply act as an identifier that this is an OEM installation (rather than a user installation)

e.g. in ubiquity this is a bit awkwardly grafted onto the welcome page (mind, UX isn't a particular concern for this feature since only OEMs ought to ever see this) and then dumped into `/var/log/installer/oem-id`
![oem-installer-welcome](https://user-images.githubusercontent.com/809987/39180445-2ec23226-47b7-11e8-9870-45842e49ce6c.png)

**Comment by adriaandegroot** [comment]
With all these OEM things, wouldn't an OEM page in the installer, and an explicit OEM module, make more sense?

**Comment by apachelogger** [comment]
Sure, assuming the user module functionality can be easily enough shared with another module that'd absolutely be an option. And neatly isolate the OEM-specific stuff from the rest of calamares.
