### ISSUE TITLE
networkmanager setup page

### ISSUE THREAD

**Issue by hsitter** [calamares/calamares#946]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

When configuring an OEM provided base system it is necessary to help the user set up wifi. This is particularly true if the device only has wifi or it is its primary type of connectivity (e.g. ultra portal laptops).

For one, this helps a potentially new user set up one of the most crucial bits of their new system without having them resort to web searching how to do it, or try to find the relevant config app on their own in a potentially overwhelmingly new system. In the OEM scenario specifically, the user is already on the final system in-chroot, as it were, so configuring the network during configuration can easily carry over to the final user. (could also be done across chroot, certainly more work though)

More importantly, however, setting up a network connection may drastically improve the overall user experience as network-dependent services will be able to run during configuration. Such as geoip-based locale/tz detection and automatic installation of additional packages for best localization experience (e.g. CJK font and IM packages which aren't on the base system). Thinking about future features I could also imagine a great benefit in auto-installing security updates when internet access is available.

To this end it'd be grand if there was a wifi setup page (based on networkmanager? there's already a lovely qt lib for it).

**Comment by abucodonosor** [comment]
Can we please stop assuming everything and 
everyone is using Plasma or Neon some sort ? 

So what will that Nm support looks like ?

Support for plasma5 based NM ...
Support for Gnome2/3 ... 
Support for Xfce4 ...
Support for LXQt ( does it have NM support ? )
Support for <put here all Gnome clones and forks> ..
Support for ... < you got the idea>
 
Now for that to work .. we yet need first detect the Desktop.
( for that ofc we can have a configuration option and let the Distros tell
us what they want DE they want to configure )

Then we need change the whole logic on Welcome page ..
That again would need some configure option(s) and some UIX option to click on
to disable. Just keep in mind some users have bad internet they may _not_ want to
use that or simple _cannot_ use it.

So now we can  first bring up WIFI stuff ( NM or whatever GUI ) and delay 
any kind _checks_ in Welocme .. Based on user(s) wishes from UIX we setup now  NET/WIFI 
and fire up delayed check .. 

< and some more stuff to care about depending on DE >

Also I'm with @agaida .. this is overkill and does not really belogs to calamres that
way. 

We can have for OEM different solution for the DE's with much less pain.
These NM GUIs already exists for Gnome* , Plasma and so on.

Have a a option like:

use_nm_gui_cmd: <bring_up_MN_GUI_for_that_DE>

eg: use_nm_gui_cmd: "kcmshell5 kcm_networkmanagement" ,for plasma
That brings up native plasma5 GUI and set it right way .. 

If that is set delay at least inet check in Welcome.. etc

( That may even work for !OEM when we copy the configuration over )

**Comment by kkofler** [comment]
> Can we please stop assuming everything and
> everyone is using Plasma or Neon some sort ?

That's why the idea is to have a Calamares view step configuring the network using the `networkmanager-qt` KDE Framework, not using the desktop's NM UI at all. That will work on all desktops.

**Comment by adriaandegroot** [comment]
See also #620:

> But in case when systemd-networkd is used, at least in OpenMandriva byt default devices like enp2s0 or eth are configured and started by systemd-networkd.
>
> Would be nice to make use of it and allow user to configure wifi/eth connection based on systemd-networkd.

**Comment by tpgxyz** [comment]
> Can we please stop assuming everything and
> everyone is using Plasma or Neon some sort ?

This is bold assumption.  Well a `networkmanager-qt` is good option same as calling `systemd-network` directly.

**Comment by blackcrack** [comment]
it's maybe not bad(/good option) to use this networkmanager-qt ln -s as draknet (maybe as script to use nmtui or networkmanager-qt by surface prompt/X ) and add this in the drakconf/mcc or "setup"
because the network manager it's not bad and have something like "iso/en" in the Linuxworld" because it's a really good possibility to configuring the network stack.. imho

and by side to hold the "drakthings" in OpenMandriva and the possibility to MDK Standart's
to have a possibility to call drak[tabTab] to see what's all possibility to configuring with drak[tabtab]
also the dnfdragora maby linking to drakrpm/rpmdrake and dnf to urpmi .. maybe all as script's and placeholders .

best regards
Blacky

(can anyone maybe checking out php on 3.0 ? for make workable Nextcloud and other Webapplications and so on, it works still not (so also the mariadb-connectivity and so on.. plz test the full nextcloud include accounts and files in NC, and so on.. in php at OMLx 3.x ))

**Comment by abucodonosor** [comment]
@blackcrack 

can you please stop these nonesense OM things in here ?

**Comment by kkofler** [comment]
Using `drak*` in Calamares is not going to happen, those tools are inherently distro-specific.

**Comment by tsimonq2** [comment]
I'm +1 for this being in Calamares.

Reason being, down the road, Lubuntu's going to have the option to "Install Lubuntu" from the boot screen. If they select that, only Calamares will be shown.

Ubiquity does this within the installer, I don't see any reason why we can't make a module available for distributions who don't assume the user will always be able to configure networking from the desktop.

An interesting project is [nm-tray](https://github.com/palinek/nm-tray) which is a pure Qt implementation of a network manager applet. Lubuntu uses this by default, and maybe we can reuse some code.

Thanks.

**Comment by demmm** [comment]
This feature request is now well over 4 years old, never a PR submitted for it, time to close.
