### ISSUE TITLE
3.1.13 build crashing

### ISSUE THREAD

**Issue by jghodd** [calamares/calamares#948]
#### Submission type

  - [ X] Bug report

#### Info regarding which version of Calamares is used, which Distribution

3.1.13

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> …

#### What do you expect to have happen when Calamares installs?

> …

#### Describe the issue you encountered

[ 20%] Building CXX object src/libcalamaresui/CMakeFiles/calamaresui.dir/calamaresui_autogen/mocs_compilation.cpp.o
In file included from /distro/repository/calamares-plasma-bluestar/src/calamares-3.1.13/build/src/libcalamaresui/calamaresui_autogen/mocs_compilation.cpp:3:
/distro/repository/calamares-plasma-bluestar/src/calamares-3.1.13/build/src/libcalamaresui/calamaresui_autogen/4DS6FYB4U4/moc_PythonQtGlobalStorageWrapper.cpp: In static member function ‘static void GlobalStorage::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
/distro/repository/calamares-plasma-bluestar/src/calamares-3.1.13/build/src/libcalamaresui/calamaresui_autogen/4DS6FYB4U4/moc_PythonQtGlobalStorageWrapper.cpp:97:28: error: variable ‘QVariant _r’ has initializer but incomplete type
         case 5: { QVariant _r = _t->value((*reinterpret_cast< const QString(*)>(_a[1])));
                            ^~
/distro/repository/calamares-plasma-bluestar/src/calamares-3.1.13/build/src/libcalamaresui/calamaresui_autogen/4DS6FYB4U4/moc_PythonQtGlobalStorageWrapper.cpp:97:88: error: invalid use of incomplete type ‘class QVariant’
         case 5: { QVariant _r = _t->value((*reinterpret_cast< const QString(*)>(_a[1])));
                                                                                        ^
In file included from /usr/include/qt/QtCore/qobject.h:54,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/QWidget:1,
                 from /distro/repository/calamares-plasma-bluestar/src/calamares-3.1.13/build/src/libcalamaresui/calamaresui_autogen/4DS6FYB4U4/../../../../../src/libcalamaresui/viewpages/AbstractPage.h:22,
                 from /distro/repository/calamares-plasma-bluestar/src/calamares-3.1.13/build/src/libcalamaresui/calamaresui_autogen/4DS6FYB4U4/moc_AbstractPage.cpp:9,
                 from /distro/repository/calamares-plasma-bluestar/src/calamares-3.1.13/build/src/libcalamaresui/calamaresui_autogen/mocs_compilation.cpp:2:
/usr/include/qt/QtCore/qmetatype.h:1926:1: note: forward declaration of ‘class QVariant’
 QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/libcalamaresui/CMakeFiles/calamaresui.dir/build.make:464: src/libcalamaresui/CMakeFiles/calamaresui.dir/calamaresui_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:273: src/libcalamaresui/CMakeFiles/calamaresui.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

#### Steps to reproduce the problem

makepkg

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

> …

**Comment by jghodd** [comment]
Getting the same build error with 3.2-rc4:

[ 17%] Building CXX object src/libcalamaresui/CMakeFiles/calamaresui.dir/calamaresui_autogen/mocs_compilation.cpp.o
In file included from /distro/repository/calamares-plasma-bluestar/src/calamares-3.2.0/build/src/libcalamaresui/calamaresui_autogen/mocs_compilation.cpp:3:
/distro/repository/calamares-plasma-bluestar/src/calamares-3.2.0/build/src/libcalamaresui/calamaresui_autogen/4DS6FYB4U4/moc_PythonQtGlobalStorageWrapper.cpp: In static member function ‘static void GlobalStorage::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
/distro/repository/calamares-plasma-bluestar/src/calamares-3.2.0/build/src/libcalamaresui/calamaresui_autogen/4DS6FYB4U4/moc_PythonQtGlobalStorageWrapper.cpp:97:28: error: variable ‘QVariant _r’ has initializer but incomplete type
         case 5: { QVariant _r = _t->value((*reinterpret_cast< const QString(*)>(_a[1])));
                            ^~
/distro/repository/calamares-plasma-bluestar/src/calamares-3.2.0/build/src/libcalamaresui/calamaresui_autogen/4DS6FYB4U4/moc_PythonQtGlobalStorageWrapper.cpp:97:88: error: invalid use of incomplete type ‘class QVariant’
         case 5: { QVariant _r = _t->value((*reinterpret_cast< const QString(*)>(_a[1])));
                                                                                        ^
In file included from /usr/include/qt/QtCore/qobject.h:54,
                 from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/QWidget:1,
                 from /distro/repository/calamares-plasma-bluestar/src/calamares-3.2.0/build/src/libcalamaresui/calamaresui_autogen/4DS6FYB4U4/../../../../../src/libcalamaresui/viewpages/AbstractPage.h:22,
                 from /distro/repository/calamares-plasma-bluestar/src/calamares-3.2.0/build/src/libcalamaresui/calamaresui_autogen/4DS6FYB4U4/moc_AbstractPage.cpp:9,
                 from /distro/repository/calamares-plasma-bluestar/src/calamares-3.2.0/build/src/libcalamaresui/calamaresui_autogen/mocs_compilation.cpp:2:
/usr/include/qt/QtCore/qmetatype.h:1926:1: note: forward declaration of ‘class QVariant’
 QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/libcalamaresui/CMakeFiles/calamaresui.dir/build.make:467: src/libcalamaresui/CMakeFiles/calamaresui.dir/calamaresui_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:337: src/libcalamaresui/CMakeFiles/calamaresui.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by adriaandegroot** [comment]
Probably something subtle has changed in implicit includes; an #include <QVariant> at the top of src/libcalamaresui/viewpages/PythonQtGlobalStorageWrapper.cpp should do the trick.

**Comment by jghodd** [comment]
Sounds good. What exactly should I include?

**Comment by jghodd** [comment]
Ok. I added #include <QVariant> right after #include <QObject> in PythonQtGlobalStorageWrapper.h and that did the trick. Nothing I tried in PythonQtGlobalStorageWrapper.cpp changed anything.

**Comment by jghodd** [comment]
btw, I don;t know if you gave me the full #include in your last comment; apparently anything posted here between angle brackets, including the angle brackets, disappears, so all I can see is "an #include at the top of..."

**Comment by adriaandegroot** [comment]
`#include <QVariant>` .. there were actually some other missing includes, too. And yes, the angle-brackets disappear unless you use backticks, my bad.
