### ISSUE TITLE
Installmovies from Mandriva, take a look :)

### ISSUE THREAD

**Issue by blackcrack** [calamares/calamares#952]
@adriaandegroot 

#### Submission type

  - [ ] Bug report
  - [X] Feature Request

#### What do you expect to have happen when Calamares installs?

> a excellent user guidance through the configuration of the system to have as new/Fresh Administrator on Linux the best (best is not ever easy) way for configuration the whole System include also controlling the User ID's and the Group ID's of each new created User

#### Describe the issue you encountered

> Old Times was not ever bad times, installer, Userid's and Groupid's be setting up by Install too and therewith the possibility for configure also the Users in a very nice way, maybe can you are make a possibility to create directly a multi user configuration by adding more as 1 users, so a listing where it is possible to adding a list of Users of the system (On top the Root account, 2nd Frame the User listing with editable Users or "+" "-" User button with scrollbar at side if need ) and with a checkbox at bottom rightfor configuring directly Samba as 1. Server or 2. Domainserver/Controller as 2nd Step (was never was) if the Checkbox checked, add Sambausers with Name,Passwords out from the Users of the System ( Maybe also with a Listing where can add Users to the Samba and add shares at the account "+" "-" Samba User) and the configuration the samba stack directly by install to have shares directly behind in in the System start, this makes possibility to setting up a Serversystem for WinNT (like Reactos ;) ) as Workstations (maybe for Munich too ;) )

>The 2nd Option with Samba Users shold only comes if the Checkbox checked to have the possibility
to configuring Samba directly by install with calamares in relation to the system users (maybe also with editable U/G ID's, Names/Passwords of Windowssystem for have a Possibility to Create Nonsystem Users for Samba, where only on the Workstation's and as Domain Controller for WinNT Workstations Systems

>Maybe in work together with The Reactos Project as Brother in GPL ( That I mean seriously ! This is a possibility to work together with a WinNT Project out of the LinuxCommunity where is Wine also involved.
See the whole as thing and not only Linux, see the NonMS-need :) )

#### Steps to reproduce the problem

> http://blackysgate.de/files/folder-root/Mandriva-install-movies/

Include Fun or other Suggetions and Ideas ?
> Have Fun ! :)))

best regards
Blacky

**Comment by adriaandegroot** [comment]
This kind of "many things at once" feature request is difficult to handle. Please write one request per issue, or structure the requests in a list, or start pull-requests for the individual parts of the feature.

As far as I understand the items in this feature request:
 - allow explicitly setting UID and GID for regular users in the target system -- is there an actual use-case for this? I'm a bit concerned about adding complexity for a purpose which is very local-network-specific. #548 is also an extension to what-can-be-configured for the user, for instance.
 - multiple users configuration -- there is a pull request for that, and another issue filed for that. Doing multiple users is something I have talked with the KDE Visual Design Group about, to get a workable UI. There are ideas, nothing close to implementation yet. #526
 - samba server configuration -- wouldn't KIO or GVFS autodiscover usually do the right thing here?
 - users from samba / AD -- this strikes me as a very different kind of user-config approach. Calamares doesn't support branching / conditional modules at all right now, so you either add massive complexity to the user configuration module to do both, or use two modules, and two configuration files with different user modules selected.

Is there something specific in those old Mandriva installs? They don't seem relevant to

**Comment by blackcrack** [comment]
>This kind of "many things at once" feature request is difficult to handle. Please write one request per >issue, or structure the requests in a list, or start pull-requests for the individual parts of the feature.
>
>As far as I understand the items in this feature request:
>
>  *  allow explicitly setting UID and GID for regular users in the target system -- is there an actual use-case for this? I'm a bit concerned about adding complexity for a purpose which is very local-network-specific. 
>#548 is also an extension to what-can-be-configured for the user, for instance.

look the Mandrake install movies (to get suggestions) .. there it is possible by each user as extended configuration dialog for enhanced Users who want Configuring the System like the user/Amin/owner/w.e. .. it want, include the UID and GID..
was it ever and should it also possible in the future .. \:)

 > *  multiple users configuration -- there is a pull request for that, and another issue filed for that. Doing multiple users is something I have talked with the KDE Visual Design Group about, to get a workable UI. There are ideas, nothing close to implementation yet. #526 

*thumps up*
need only a listing where it is the possible for 3 buttons, "Add" "Change" "Remove" if there wrong entrys
just a listing with the possible to more as one user adding.. (calc design, nothing extra spezial, calc design with 3 buttons , this makes possible for manage more as one user, why complicate if works easy ;) 
and this maby behund a button (Extended User Managing)

>  *  samba server configuration -- wouldn't KIO or GVFS autodiscover usually do the right thing here?
connection to a Surface like KDE or Gnome it's nonsense,
this is also because it was programmed the Draktools/ Drakconf and different modules for Draktools
to be easy independent from an Surface/Windowmanager in any form, this was the idea behind..
and as next step to give the User a possible to be not bound on a Specially WM..

this what i now see, the KIO and the other things in Gnome for configuration the System, bound the user to an WM and this is really wrong .. a System configuration mus be like in Windows, an Controlcenter with modules where be able to call in a independence way like drakx11 drakconf in prompt and in Xorg/Wayland way, this should also be in Calamares, independence from an WM so, it's maybe also to have a way to be in able for calling ConfigurationDialog for different things.. in easiest way..
and to make dependent on a windowmanager should be avoided
 
> *  users from samba / AD -- this strikes me as a very different kind of user-config approach. Calamares doesn't support branching / conditional modules at all right now, so you either add massive complexity to the user configuration module to do both, or use two modules, and two configuration files with different user modules selected.

naaa.. don't think complicate, think easy ... first, we have Linuxusers, ^^ out of the Listing where be done first, the next way is, read out the exist Users .. and add it as Sambausers..
Add shares where you need and make it able to r/w the shares to the Users ...
...
did you see the Drakconf --- Samba-configuration Dialog (in Mandrake/OpenMandriva (or did you testing it out .. ? myabe in VirtualBox ? \;) ) ) ? 
Something in this direction .., we have users in the //rootfs//etc/ , they can we 
take/create in //rootfs//etc/samba to create the possible for 1. normal Samba users, Sharepoints for different Samba-users and Share-points for different Share points and different users, also prospective Printer and User-homefolders to samba in the smb.conf
This could be able as calamares extended Plugin maybe if included, create a Button where can call the Samba User guided Configuration of Samba Shares or more extended something like in Drakconf a Sambaconfiguration ... (where to make sure that the UID and GID are also used in Samba like in the System for the users )
In any case is a Administrator based sharing of Samba Shares more meaningful as to logging in on each users and give free Sambashares ..
I have a Sambaserver in the basement running.. and it's really good to have because
if we use more as only one Ordering System  :) :+1: also an WinNT System as Workstation where it is the Linuxuser configured too like in WinNT or visa-versa .. and The filesystem is for this user Browsable .. where is exploring in the unc-fs from any computer on the House .. like \\Linuxserver\myshare\andsoon\ in WinNT/Explorer  well..

because the User-configuration.. can be the Mandrake/Mandriva Installer movie an reference point ;)
also for suggestions and ideas ..

best regards
Blacky

**Comment by abucodonosor** [comment]
@blackcrack 

fking stop that drakX crap and Mandriva things in here ..

**Comment by philmmanjaro** [comment]
@blackcrack I don't get your request at all. Those movies are tagged from 2015. Also your request is all over the place. If you want to configure Samba, every distro does it differently. @adriaandegroot I don't think we will get with this request anywhere ...

**Comment by blackcrack** [comment]
well, standard -configuration's folder it is /etc/samba/  with the smb.conf 
and this affects every distribution where uses a Standart"iso" Samba
if you did not mess up as a distributor in it / If you are not a distributor in it blundered

best regards
Blacky

**Comment by abucodonosor** [comment]
This has nothing to do with calamares.
