### ISSUE TITLE
Cala lets me succeed with 5 primary partitions on MS-DOS

### ISSUE THREAD

**Issue by ShalokShalom** [calamares/calamares#953]
#### Submission type

  - [x] Bug report
  - [x] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> 3.1.104 (KaOS)

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> https://pastebin.com/0zNVJ76x

#### What do you expect to have happen when Calamares installs?

> Error message

#### Describe the issue you encountered

> Calamares lets me decide to setup more than 4 primary partitions on MS-DOS 

#### Steps to reproduce the problem

> Setup more as 4 primary partitions, try to install

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

> https://pastebin.com/0zNVJ76x

**Comment by adriaandegroot** [comment]
Confirmed. To reproduce:
 - start with (preferably) an empty disk; create an MBR partition table on it.
 - create a bunch of partitions. For each partition, leave the selector set to "primary"
 - once "a bunch" is more than four, carry on with the installation

Eventual message is "Failed to add partition 'New partition' to device". After Calamares shuts down, you can see there are four primary partitions on the disk.
