### ISSUE TITLE
add opensuse to the documentation

### ISSUE THREAD

**Issue by vpereira** [calamares/calamares#959]
openSUSE distributes calamares on the upcoming version https://en.opensuse.org/openSUSE:Roadmap#Upcoming_openSUSE_Leap_Release

**Comment by kkofler** [comment]
Do they use it by default? I guess not, i.e., that it should be listed along with Debian, Fedora, and Gentoo as a distro that provides it in the repos but defaults to something else, is that correct?

**Comment by vpereira** [comment]
Yes @kkofler  you are correct. 

BTW gecko linux  (http://geckolinux.github.io/) is using it by default as you can see it here: https://github.com/geckolinux/geckolinux-project

**Comment by adriaandegroot** [comment]
Gecko was already on the list; I've added openSUSE to the "big four" list.

**Comment by candrapersada** [comment]
how to use calamares for openSUSE?

**Comment by adriaandegroot** [comment]
@candrapersada That is not a good question to tag onto a closed issue. openSUSE has a package for Calamares -- that means you can install and run Calamares (e.g. boot a tumbleweed live install CD, install Calamares into that image). I have no idea what configuration is needed to then install from there -- that's something for openSUSE / some derivative to figure out.
