### ISSUE TITLE
xfsprogs 4.16 onward will fail grub install

### ISSUE THREAD

**Issue by demmm** [calamares/calamares#960]
#### Submission type

  - [ X] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

> Detected first in KaOS, Calamares 3.2RC, but this is not a Calamares issue

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> Create a partition with XFS as root, which also contains /boot for a BIOS grub install.

#### What do you expect to have happen when Calamares installs?

> …

#### Describe the issue you encountered

> Partitions created with xfsprogs onward will result in grub install erroring out with `unknown filesystem`

The issue is known in grub, but a patch is not available yet afaik:
http://savannah.gnu.org/bugs/?func=detailitem&item_id=48645

Since this is not a Calamares issue, but distributions need to be warned about this failure, not sure if you want to keep this report, or close it immediately as `upstream`
There is a bug already reported in KaOS and being tracked there..

**Comment by demmm** [comment]
Reverting the commit that set spinode as default fixes the issue in grub for now.
Patch used:
https://github.com/KaOSx/core/commit/cc635ed6176a82c00f068ca330973a1d9649be7d
Once grub has the needed fix to enable spinode again, it will be noted here.

**Comment by adriaandegroot** [comment]
These kind of issues also get the "not-a-calamares-bug" label. Noted in the wiki entries for "known issues" (in the deployer's guide).

**Comment by adriaandegroot** [comment]
Is there no command-line-option that might be passed to mkfs_xfs?

**Comment by demmm** [comment]
Yes, the -i option has a switch for sparse:
```
/* inode size */        [-i log=n|perblock=n|size=num,maxpct=n,attr=0|1|2,
                            projid32bit=0|1,sparse=0|1]
```
I checked in kpmcore to see where to add (it looks like it would be here https://github.com/KDE/kpmcore/blob/6b6ddbdcef1e04f2828bb7f2705a18e4196d7fd0/src/fs/xfs.cpp#L146), but found it easier to patch xfsprogs right now.

**Comment by demmm** [comment]
Tested and working cli line:
```
sudo mkfs.xfs -i sparse=0 /dev/sda1 -f
```

**Comment by demmm** [comment]
A patch from Fedora to have grub see sparse inode enabled filesystems fixes this bug properly:
https://src.fedoraproject.org/rpms/grub2/raw/master/f/0250-xfs-accept-filesystem-with-sparse-inodes.patch

This patch is tested on XFS filesystem created with sparse=1, grub-probe now correctly returns `xfs` again.

**Comment by adriaandegroot** [comment]
Closing this one (since it's now listed in the known-issues section of the wiki).
