### ISSUE TITLE
Fatal error with luks and bootloader on /

### ISSUE THREAD

**Issue by 2lafru** [calamares/calamares#969]
#### Submission type

  - [ X] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

3.1.13-1 for Manjaro Linux 17.1 "Hakoila"

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

I'm trying to do a full wipe of the sda disk. I want to install Manjaro Linux with most of the disk dedicated to it, and a 8Go swap partition. This is the default configuration when selecting to do a full wipe. I want the system to be encrypted. Instead of installing the bootloader on the MBR, I want to install it on /.

#### What do you expect to have happen when Calamares installs?

As what I want to do is proposed by the Calamares GUI, I would expect this to be possible and to succeed. 

#### Describe the issue you encountered

The installer can't finish this type of installation (full disk encryption with bootloader not on MBR). However nothing prevents me to try this. At some point during the installation, I get an error window with : 

`Erreur Boost.Python pour le job "bootloader".`
`<class 'subprocess.CalledProcessError'>`
`Command 'grub-install --target=i386-pc --recheck --force /dev/sda1' returned non-zero exit status 1.`
`Traceback:`
`  File "/usr/lib/calamares/modules/bootloader/main.py", line 351, in run`
`    prepare_bootloader(fw_type)`

`File "/usr/lib/calamares/modules/bootloader/main.py", line 322, in prepare_bootloader`
`    install_grub(efi_directory, fw_type)`

`File "/usr/lib/calamares/modules/bootloader/main.py", line 292, in install_grub`
`    boot_loader["installPath"]])`

`File "<string>", line 2, in <module> `

#### Steps to reproduce the problem

During the installation, select an installation on the whole disk. Enable disk encryption. Specify you do not want to install the bootloader on the MBR.

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

```
13:56:12 [0]: Starting job "grubcfg" 
13:56:12 [1]: Job file "/usr/lib/calamares/modules/grubcfg/main.py" 
13:56:12 [1]: Job "grubcfg" (doc) -> "Calls routine with given parameters to modify '/etc/default/grub'." 
13:56:12 [0]: Running "chroot" ("/tmp/calamares-root-fwwxd3u4", "sh", "-c", "which dracut") 
13:56:12 [0]: Finished. Exit code: 1 
13:56:12 [0]: Target cmd ("sh", "-c", "which dracut") 
13:56:12 [0]: Target out "which: no dracut in (/usr/sbin:/usr/bin:/sbin:/bin:/root/bin)" 
13:56:12 [0]: Starting job "bootloader" 
13:56:12 [1]: Job file "/usr/lib/calamares/modules/bootloader/main.py" 
13:56:12 [1]: Job "bootloader" (doc) -> "Starts procedure and passes 'fw_type' to other routine." 
Bootloader: grub (bios)
13:56:12 [0]: Running "chroot" ("/tmp/calamares-root-fwwxd3u4", "grub-install", "--target=i386-pc", "--recheck", "--force", "/dev/sda1") 
13:56:35 [0]: Finished. Exit code: 1 
13:56:35 [0]: Target cmd ("grub-install", "--target=i386-pc", "--recheck", "--force", "/dev/sda1") 
13:56:35 [0]: Target out "Installing for i386-pc platform.\ngrub-install: error: unable to identify a filesystem in hostdisk//dev/sda; safety check can't be performed." 
13:56:35 [1]: tbMsg "  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 351, in run\n    prepare_bootloader(fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 322, in prepare_bootloader\n    install_grub(efi_directory, fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 292, in install_grub\n    boot_loader[&quot;installPath&quot;]])\n\n  File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;\n" 
13:56:35 [0]: Installation failed: 
13:56:35 [0]: - message: "Erreur Boost.Python pour le job \"bootloader\"." 
13:56:35 [0]: - details: "<div><strong>&lt;class 'subprocess.CalledProcessError'&gt;</strong></div><div>Command 'grub-install --target=i386-pc --recheck --force /dev/sda1' returned non-zero exit status 1.</div><div>Traceback:</div><div><pre>  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 351, in run\n    prepare_bootloader(fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 322, in prepare_bootloader\n    install_grub(efi_directory, fw_type)\n\n  File &quot;/usr/lib/calamares/modules/bootloader/main.py&quot;, line 292, in install_grub\n    boot_loader[&quot;installPath&quot;]])\n\n  File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;\n</pre></div>" 
13:56:35 [0]: Calamares will quit when the dialog closes. 
13:56:35 [1]: FinishedPage::setUpRestart() 
```

**Comment by adriaandegroot** [comment]
I'm going to ask @philmmanjaro to comment on this; certainly the grub-install command looks strange if you're not installing on the MBR.

**Comment by philmmanjaro** [comment]
@2lafru: which exact install media did you use? I've to test if it is possible to do so when not installed on MBR. Why do you choose the root-folder instead?

**Comment by 2lafru** [comment]
I used a USB live version of manjaro 17.1 with XFCE. I was trying to install Manjaro on my main HDD (sda).

Actually I tried to install the bootloader on the root-folder because when I tell the installer to put it on the MBR, I get a password prompt in qwerty (I use fr-oss). Changing the keyboard layout seems easier to do if the bootloader isn't on the MBR.

**Comment by philmmanjaro** [comment]
Which exact version of **v17.1** series. **v17.1.10** is the latest one as of now.

**Comment by 2lafru** [comment]
Yes, it's actually a 17.1.10 live version.

**Comment by abucodonosor** [comment]
@2lafru 

can we see an full log of the installation ?

the error leading to that lies in the partitions setup.

**Comment by 2lafru** [comment]
@abucodonosor 
Well, that's weird. I didn't have the full log of the installation, so I tried to redo an installation to reproduce the bug, but the drop-down list asking me where I want to put the bootloader doesn't appear anymore. It was on this screen, below the two colored bars. 
https://imgur.com/JGHAhJt.png
I didn't update anything; however I'm not able to reproduce the bug...

**Comment by 2lafru** [comment]
@abucodonosor Oops sorry, I wasn't seeing the drop-down list because my computer was booting with UEFI. I got it back by booting with BIOS. Here is the full log.
[calamares.log](https://github.com/calamares/calamares/files/2062951/calamares.log)

**Comment by abucodonosor** [comment]
@2lafru 

if you change defaults you are in 'I'm know what I'm doing mode'..

We allow bc it is possible to have 2 disks or more ..

**Comment by adriaandegroot** [comment]
Closing as "overcome by events".
