### ISSUE TITLE
Calamares does not compile with Qt 5.7.1

### ISSUE THREAD

**Issue by llelectronics** [calamares/calamares#979]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

3.2 Git 20180605

#### Describe the issue you encountered

It fails compiling with Qt 5.7.1 due to incompatible methods (QString const char* comparison) and not included libs for the new GeoIP stuff.

#### Steps to reproduce the problem

Try to compile under Qt 5.7.1

This patch lets me compile it against Qt 5.7.1. 
https://github.com/NeptuneOS/calamares-packaging/blob/master/debian/patches/make_qt571_compatible.patch
In the code it probably needs to check for Qt Version smaller than 5.9 (or 5.8 not 100% sure) and provide then compatibility for those lower Qt Versions. 
(Or raise the Qt Compatibility to 5.9 alltogether for Calamares)

**Comment by kkofler** [comment]
Who still uses Qt 5.7.1? IMHO, Qt 5.9.x LTS is a sane minimum to require in current Calamares 3.2.x. The current non-LTS is now even 5.11.x.

**Comment by llelectronics** [comment]
Debian Stable and Distros like Neptune who are built upon it use 5.7.1

**Comment by kkofler** [comment]
Well, your change to `CalamaresAddTranslations.cmake` breaks reproducible builds for newer Qt versions that support the (IMHO broken) RCC "format version 2" with the embedded timestamps. So at least this part needs a version check. The 2 code changes should probably be fine unconditionally. (I'd personally use `if ( value == QStringLiteral("*") )` for maximum efficiency, but that's splitting hairs.)

**Comment by adriaandegroot** [comment]
Fixed with a bunch of commits that mention this issue.
