### ISSUE TITLE
GPT Partition Table Should Not Enforce /boot/efi fat32 partition creation

### ISSUE THREAD

**Issue by nobicycle** [calamares/calamares#981]
#### Submission type

Bug report

#### Info regarding which version of Calamares is used, which Distribution

3.2.05
Manjaro 17.1.10 Hakoila

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

GPT partition table

#### What do you expect to have happen when Calamares installs?

Calamares should not enforce creation of  a /boot/efi fat32 partition.

#### Describe the issue you encountered

The baggage associated with Secure Boot creates complexity for end users without any significant benefit.  As reference lookup in support forums of those many end users who ABANDON Linux installation. Calamares is making things worse (see below)

Users who run legacy BIOS should not be forced to face  uefi issues just because they have a GPT partition table. They should not be forced by Calamares to create an unnecessary  550 MB (recommended)  /boot/efi fat32 partition **and then**  discover the **installation will not boot**
The solution to this is to switch to MBR partition table, reboot and install again, but end users will not be aware of this!
 
#### Steps to reproduce the problem
Install on a legacy BIOS computer with GPT partition table.

**Comment by abucodonosor** [comment]
There is no Secure Boot support right now in 3.2.x .. What are you talking about ?

The only way to do that is in manual partitioning which again means 
you know what you are doing ..

Please attach full logs for such an installation..

@philmmanjaro 

Do you guys have the Secure Boot branch merged or something ?

**Comment by nobicycle** [comment]
"The only way to do that is in manual partitioning which again means
you know what you are doing .."

Yes, I forgot mention manual install. A GPT install requires a BIOS partition as well as partitions desired by the user. If one attempts such an install, Calamares will warn the user to go back and create a  /boot/efi fat32 partition.

A user on Manjaro's forum suggested this was because Calamares assumes GPT means the user will be running on a UEFI BIOS. This is not necessarily the case.

I will attach logs in the next post..

**Comment by abucodonosor** [comment]
@nobicycle 

There is nothing assumes is 'whatver' and BIOS install do work fine 
with GPT when you do it right.

Read up this as example:
```
https://kaosx.us/docs/bios_gpt/
```
From calamares point of view right now , manual partitioning means:
* Use what the user told you to use ..

There is no way to guess why the user did partitioning that way
or how it meant to be used after installation finished.

The only thing calamares may do is do add a warning like some such:

'BIOS boot detected but WRONG partitioned HDD for an BIOS boot'

**Comment by abucodonosor** [comment]
Here just did base installation with my own ISO in VirtualBox (BIOS)..
There is no /boot .. nor swap , sda is GPT.. 
It boots and works just fine.

![gpt-on-bios](https://user-images.githubusercontent.com/18563759/41193826-8f14808c-6c12-11e8-80c7-8c4bb0b29942.png)

**Comment by abucodonosor** [comment]
Also please point me to a Manjaro 17.1.10 ISO with 
calamares 3.2.x on it since these seems to have calamares 3.1.3.

**Comment by abucodonosor** [comment]
> I don't know whether the VirtualBox environment is a fair test.

Is same I would install on real BIOS there is no difference ..

I Installed Manjaro 17.1.10 plasma edition .. NOTHING promted me 
to do anything like /boot/efi ..

No Idea what you are doing.

Really simple .. Boot the iso , start the installer , once on partitioning
widget just go to manual partitioning, change to GPT , remove partitions ,
add a at least 8MB empty unformated partition and mark it bios_boot ,
create whatever else , goto install , reboot and there you are BIOS on GPT.

**Comment by nobicycle** [comment]
"No Idea what you are doing."
It is extremely simple and verified by a Manjaro Team member.
Issue closed.

**Comment by adriaandegroot** [comment]
I can't tell if the problem has been resolved, or if @nobicycle has given up on explaining the issue. Probably the latter. 

> A user on Manjaro's forum suggested this was because Calamares assumes GPT means the user will be running on a UEFI BIOS. This is not necessarily the case.

It would (have) be useful to have the full warning message at the beginning of this thread. There **is** a message in Calamares saying *No EFI system partition configured*. This is shown when (1) manual partitioning is done (2) the system is EFI and (3) no partition is configured for `/boot/efi`. That logic doesn't match what's described here, so it needs extra explanation. I suspect, though, that the check for is-this-an-EFI-system is what's going wrong -- because I can't find any code that goes "GPT means EFI".

**Comment by adriaandegroot** [comment]
> Users who run legacy BIOS should not be forced to face uefi issues just because they have a GPT partition table.

I just tried an install with a (virtual) disk with an existing GPT partition table, with one existing partition (from block 618498 to 45131405, so weirly placed on the disk). Went through manual partitioning, it shows me that it has detected BIOS & GPT, and I can edit the existing partition to give it the boot flag. I suspect that the original distro in this report has a `/sys/firmware/efi/efivars` directory, even though there's no actual EFI on the system.
