### ISSUE TITLE
boost-libs 1.67

### ISSUE THREAD

**Issue by robin0800** [calamares/calamares#982]
#### Submission type

  - [* ] Bug report
  - [ ] Feature Request

Calamares will not start with boost-libs 1.67
 it requires 1.66,  1.67 is in Manjaro testing branch at present.

> ...

**Comment by philmmanjaro** [comment]
This is a packaging issue and should have been reported in [our bugtracker](https://gitlab.manjaro.org/applications/calamares/issues). Fixed via 3.2.0-6 and 3.2.0.r4698.c652970f0-1
