### ISSUE TITLE
error in installation process

### ISSUE THREAD

**Issue by joksik** [calamares/calamares#996]
Hi, I'm a bit confused at start because under Manajro that use Calamares i dont have any problem to install OS using f2fs partition but when i use different arch based system (SwagArch) that use also latest Calamares i cant install system. after mkinitcpio i have this error:

https://i.imgur.com/lYYjD6k.png

and yes i install f2fs-tools under SwagArch (it is not installed by default) and after i install f2fs-tools i can create f2fs partition in Calamares but i dont know what case the problem and stop install process.

i setup my partition like this:

```
/boot/efi 256mb fat32 with esp and boot flag
/boot ext4 256 mb (probably not necessary because new grub support f2fs)
/ f2fs
```
any tips what i do wrong?

**Comment by kkofler** [comment]
This is a distribution issue. It is the distribution-specific `mkinitcpio` tool that is failing, and it fails because it cannot find `fsck.f2fs`. So you need to ask your distribution (SwagArch) to add support for f2fs (in particular, the `fsck.f2fs` tool) to their live media images.

**Comment by philmmanjaro** [comment]
On Manjaro we have also a patched **grub** to support f2fs.
