### ISSUE TITLE
preservefiles/umount chown and chmod control and default restriction

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#997]
I'm always frustrated when confidential data is leaked. 

When preservefiles and umount place files on the target system, the files ought to be `root:root` and `0o400` by default. The rationale is that by default great care must be taken to not accidentally leak confidential information. And what one might consider confidential is impossible to assume, so the defaults should be super restrictive to save guard against (future) data leakage. This in particular affects, but is not limited to, the calamares session log.

Since not all files need ultimate restriction, configuration keys to selectively chmod and chown preserved files as something else should be added to give the distributor control over the target permissions.

Example data we archive in kde neon (via a custom module):

- calamares session.log `root:root@0o600`
- syslog of installation session `root:root@0o600`
- dump of package states and versions after installation `root:root@0o644`
- reference of installation iso `root:root@0o644`

Example config for preservefiles (suggestion only, I am not hung up on this at all):

```
  - from: cala.log
    dest: /var/log/cala.log
  - from: syslog.log
    dest: /var/log/syslog.log
  - from: state.log
    dest: /var/log/state.log
    chown: root
    chmod: 644
  - from: ref.log
    dest: /var/log/ref.log
    chown: root
    chmod: 644
``

As a final thought: directory access should possible also be restricted/restrictable, I am not sure how that factors into anything though as the handling of missing directories is apparently not supported anyway.

**Comment by adriaandegroot** [comment]
I'm not going to apply this kind of change to the *umount* module, for two reasons:
 - file preserving doesn't belong in umount anyway
 - umount should be rewritten to C++ anyway

The new filepreserver module has support for individual permission setting, as well as restrictive defaults.
